### ISSUE TITLE
Hello, ask if there is any, know installation documentation, novice, I'm not sure how to load a new module.

### ISSUE THREAD

**Issue by net592** [F5Networks/f5-ansible#1]
Thank you, but I am a novice, don't know how to load into ansible, I am using version 2.1, is there a simple and practical, the official community module with more no, thank you very much!!!!!

**Comment by caphrim007** [comment]
@net592 at the moment the simplest way to load these modules is to clone this repository and use them locally by placing them in a library/ directory alongside your playbooks. There will be a couple more ways to install these in the future when ansible makes galaxy 2.0 available.

Aside from that I hope to see some of these modules upstreamed into ansible core and have this repository around as an incubator for modules not yet upstreamed.

I'll update this issue when galaxy 2.0 is made available.

**Comment by net592** [comment]
Thank you very much, patient answer, I will try it ~

**Comment by ric79** [comment]
Hello,
I did not understand the solution.
Let us suppose that my playbook is: `/home/xxx/F5/lbf5.yml`
```
---
- name: "XXX"
  hosts: localhost
  gather_facts: no
 connection: local
  tasks:
    - bigip_partition:
          name: "riccardo"
          server: "10.10.10.10"
          password: "aaaa"
          user: "admin"

```
I cloned (`git clone https://github.com/F5Networks/f5-ansible.git`) the repository in `/home/xxx/F5/f5-ansible`

Now I don't understand how to link the repository to my playbook

R
