### ISSUE TITLE
bigip_ssl_certificate does not support encrypted files (vault)

### ISSUE THREAD

**Issue by dano0b** [F5Networks/f5-ansible#100]
##### ISSUE TYPE
 - Bug Report
 - Feature Idea

##### COMPONENT NAME
bigip_ssl_certificate

##### ANSIBLE VERSION
ansible 2.2.0.0
  config file = /root/.ansible.cfg
  configured module search path = Default w/o overrides

##### PYTHON VERSION
Python 2.7.5

##### BIGIP VERSION
Sys::Version
Main Package
  Product     BIG-IP
  Version     12.1.2
  Build       0.93.249
  Edition     Engineering Hotfix
  Date        Fri Jan 20 15:48:38 PST 2017

Hotfix List
ID624023-3    ID623119  ID639492-1  ID624457-5

##### SUMMARY
Our ssl keys are encrypted via ansible-vault, using the encrypted file in "key_src:" just raises an unknown format exception. 

##### STEPS TO REPRODUCE

```
- name: import certificate and key
  bigip_ssl_certificate:
    server: "{{ loadbalancer }}"
    user: "{{ user }}"
    password: "{{ secret }}"
    validate_certs: False
    state: "present"
    partition: "Common"
    name: "{{ name}}"
    cert_src: "roles/f5service/files/{{ cert }}"
    key_src: "roles/f5service/files/{{ key }}"
  delegate_to: localhost
  no_log: True
```

##### EXPECTED RESULTS
I expected the common way of file handling known from copy/template module: transparent usage of encrypted files

##### ACTUAL RESULTS

```
raise TransactionSubmitException(e)\nf5.sdk_exception.TransactionSubmitException: 400 Unexpected Error: Bad Request for uri: https://cdlbet01:443/mgmt/tm/transaction/1490185487777615/\nText: u'{\"code\":400,\"message\":\"transaction failed:01070712:3: Certificate/Key has unknown format or security type (/Common/20170320-143112-textchat).\",\"errorStack\":[],\"apiError\":1}'\n", "module_stdout": "", "msg": "MODULE FAILURE"}
```

Additionally it would be great to use the default file lookup order known from copy/template too. At the moment only absolut and relative paths based on the playbook are possible, rolename/files is ignored.
