### ISSUE TITLE
bigip_device_httpd re-arranges ssl_cipher_suite tokens

### ISSUE THREAD

**Issue by MVogel91** [F5Networks/f5-ansible#1018]
##### ISSUE TYPE
Bug Report

##### COMPONENT NAME
bigip_device_httpd

##### ANSIBLE VERSION
```
ansible 2.7.0
  config file = None
  configured module search path = [u'/home/mvogel/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python2.7/dist-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 2.7.15+ (default, Oct  2 2018, 22:12:08) [GCC 8.2.0]

```

##### PYTHON VERSION
```
Python 2.7.15+
```

##### BIGIP VERSION

```
Sys::Version
Main Package
  Product     BIG-IP
  Version     12.1.3.7
  Build       0.0.2
  Edition     Point Release 7
  Date        Tue Sep 11 10:03:49 PDT 2018
```

##### LIBRARY VERSIONS

```
bigsuds==1.0.6
f5-sdk==3.0.20
```

##### CONFIGURATION

N/A

##### OS / ENVIRONMENT

N/A

##### SUMMARY

The input to ssl_cipher_suite is rearranged which makes it behave different.
In my certain case, DEFAULT:!SHA was altered to !SHA:DEFAULT which does not work, while my input would work.

##### STEPS TO REPRODUCE

Extra-Vars to be added:
* node == BIG-IP
* user == admin username
* pass == admin password

```
---

- name: define HTTPD parameters
  hosts: "{{ node }}"
  connection: local

  vars:
    prov:
      user: "{{ user }}"
      pass: "{{ pass }}"
      server: "{{ node }}"
      validate_certs: no

  tasks:
  - name: HTTPD parameters
    bigip_device_httpd:
      provider: "{{ prov }}"
      auth_pam_idle_timeout: 900
      ssl_protocols: TLSv1.2
      ssl_cipher_suite: "DEFAULT:!SHA"

```

##### EXPECTED RESULTS

It should modify the "sys httpd ssl-ciphersuite to 'DEFAULT:!SHA' "

##### ACTUAL RESULTS

Due to the re-arrangement, an error was thrown

```
fatal: [192.168.150.100]: FAILED! => {"changed": false, "msg": "01070920:3: Application error for confpp: Syntax OK\nError in cipher list\n47144362779144:error:1410D0B9:SSL routines:SSL_CTX_set_cipher_list:no cipher match:ssl_lib.c:1292:\n'!SHA:DEFAULT' invalid.\n"}
```

Running the two commands in tmsh shows a reason for the error:
#
#modify sys httpd ssl-ciphersuite !SHA:DEFAULT
01070920:3: Application error for confpp: Syntax OK
Error in cipher list
47564045451784:error:1410D0B9:SSL routines:SSL_CTX_set_cipher_list:no cipher match:ssl_lib.c:1292:
'!SHA:DEFAULT' invalid.
#
#modify sys httpd ssl-ciphersuite DEFAULT:!SHA
#

Plain REST works fine as well:
#curl -H "Content-Type: application/json" -ku '*USER*:*PASS*' https://*BIG-IP*/mgmt/tm/sys/httpd/ -d '{"sslCiphersuite":"DEFAULT:!SHA"}' -X 'PATCH' 2>/dev/null | json-format
{
  "kind": "tm:sys:httpd:httpdstate",
  "selfLink": "https://localhost/mgmt/tm/sys/httpd?ver\u003d12.1.3.7",
  "allow": [
    "All"
  ],
  "authName": "BIG-IP",
  "authPamDashboardTimeout": "off",
  "authPamIdleTimeout": 900,
  "authPamValidateIp": "on",
  "fastcgiTimeout": 300,
  "fipsCipherVersion": 0,
  "hostnameLookup": "off",
  "logLevel": "warn",
  "maxClients": 10,
  "redirectHttpToHttps": "disabled",
  "requestBodyMaxTimeout": 0,
  "requestBodyMinRate": 500,
  "requestBodyTimeout": 60,
  "requestHeaderMaxTimeout": 40,
  "requestHeaderMinRate": 500,
  "requestHeaderTimeout": 20,
  "sslCertfile": "/etc/httpd/conf/ssl.crt/server.crt",
  "sslCertkeyfile": "/etc/httpd/conf/ssl.key/server.key",
  "sslCiphersuite": "DEFAULT:!SHA",
  "sslOcspDefaultResponder": "http://127.0.0.1",
  "sslOcspEnable": "off",
  "sslOcspOverrideResponder": "off",
  "sslOcspResponderTimeout": 300,
  "sslOcspResponseMaxAge": -1,
  "sslOcspResponseTimeSkew": 300,
  "sslPort": 443,
  "sslProtocol": "TLSv1.2",
  "sslVerifyClient": "no",
  "sslVerifyDepth": 10
}
