### ISSUE TITLE
bigip_device_facts module

### ISSUE THREAD

**Issue by pg0581** [F5Networks/f5-ansible#1019]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
bigip_device_facts

##### ANSIBLE VERSION
```
ansible 2.6.1
```

##### PYTHON VERSION
```
Python 2.7.12
```

##### BIGIP VERSION
```
12.1.2
```

##### LIBRARY VERSIONS
```
bigsuds==1.0.6
f5-sdk==3.0.17
```

##### OS / ENVIRONMENT

N/A

##### SUMMARY
I'm not sure if this is a bug or not, but, I can't seem to get this module to work. When I run the playbook it's telling me that there is no action detected in the task and suggests that the module name is misspelled or is using the incorrect module path. The play is also showing a syntax error, but I don't believe there is one. 

The environment I'm using is able to run other F5 modules successfully 

##### STEPS TO REPRODUCE
```
-Run the below playbook and attempt to gather device facts:

---
- name: Gather LTM Facts
  hosts: f5_hosts
  connection: local
  gather_facts: no

  tasks:
      - name: Collect BIG-IP facts
        bigip_device_facts:
           gather_subset:
               - all
           provider:
              server: "{{ inventory_hostname }}"
              user: admin
              password: some_password
        delegate_to: localhost

...
```

##### EXPECTED RESULTS
For all device facts to be displayed 

##### ACTUAL RESULTS
```
ERROR! no action detected in task. This often indicates a misspelled module name, or incorrect module path.

The error appears to have been in '/home/user/ansible/bin/bigip_device_facts.yml': line 10, column 9, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:

  tasks:
      - name: Collect BIG-IP facts
        ^ here
```
