### ISSUE TITLE
bigip_traffic_selector add description

### ISSUE THREAD

**Issue by adolphsons** [F5Networks/f5-ansible#1034]
##### ISSUE TYPE

 - Feature Idea

##### COMPONENT NAME

bigip_traffic_selector

##### ANSIBLE VERSION

```
2.7
```

##### PYTHON VERSION

```
2.7
```

##### SUMMARY

Add a description option to bigip_traffic_selector.py module
##### STEPS TO REPRODUCE

```
- name: Create a traffic selector
  bigip_traffic_selector:
    name: "TS_IPSEC"
    description: "Traffic Selector for IPSEC"
    destination_address: "192.168.1.1/32"
    ipsec_policy: "IPSEC_POLICY"
    order: 1
    source_address: "10.1.1.1/32"
  delegate_to: localhost
```
