### ISSUE TITLE
bigip_selfip add option

### ISSUE THREAD

**Issue by adolphsons** [F5Networks/f5-ansible#1038]
##### ISSUE TYPE

 - Feature Idea
 
##### COMPONENT NAME
bigip_selfip

##### ANSIBLE VERSION

```
2.7
```

##### PYTHON VERSION

```
2.7
```

##### SUMMARY

add description option to bigip_selfip module
##### STEPS TO REPRODUCE

```
- name: Create Self IP
  bigip_selfip:
    address: 10.10.10.10
    name: self1
    description: "New Self IP"
    netmask: 255.255.255.0
    password: secret
    server: lb.mydomain.com
    user: admin
    validate_certs: no
    vlan: vlan1
  delegate_to: localhost
```
