### ISSUE TITLE
bigip_data_group doesn't support atomic adds or deletes of members

### ISSUE THREAD

**Issue by skylerbunny** [F5Networks/f5-ansible#1127]
##### ISSUE TYPE
 - Feature Idea

##### COMPONENT NAME
bigip_data_group

##### ANSIBLE VERSION

```
ansible 2.7.5
  python version = 2.7.15 (default, Sep 18 2018, 20:16:18) [GCC 4.2.1 Compatible Apple LLVM 9.1.0 (clang-902.0.39.2)]
```

##### PYTHON VERSION
```
Python 2.7.15
```

##### BIGIP VERSION

```
Sys::Version
Main Package
  Product     BIG-IP
  Version     12.1.1
  Build       2.0.204
  Edition     Hotfix HF2
  Date        Fri Oct 21 17:35:48 PDT 2016

Hotfix List
ID590578-4    ID604211-3  ID606110-3  ID595064-2  ID605314-2  ID521270-1
ID623048      ID607200-1  ID603605-1  ID599068-3  ID600778-1  ID607857-1
ID585120-2    ID606110-4  ID624264-2  ID597708-4  ID575170-5  ID589318-1
ID585366      ID605682-3  ID602061    ID598294-2  ID575170-2  ID595064-1
ID610307      ID595394-4  ID599054-2  ID589318-2  ID596814-9  ID608373-1
ID604211-4    ID597309-2  ID599054-4  ID608373-2  ID599033-3  ID590074-2
ID594910-4    ID561444-1  ID596674-1  ID601938-8  ID601309    ID603997
ID602653-3    ID600859-3  ID527403-1  ID613127-3  ID599769-1  ID585120-1
ID606509-1    ID590608-1  ID596814-5  ID513851-3  ID321971-1  ID603997-3
ID590578-5    ID609677-1  ID622529    ID593355-2  ID603605-2  ID599068-2
ID592716-1    ID600859-4  ID605682-2  ID606509-3  ID606807-1  ID595394-2
ID434573-6    ID589149-2  ID604459-1  ID601938-2  ID609325    ID614599
ID601927-8    ID612564    ID612952-1  ID600778-2  ID594910-1  ID590608-3
ID598294-1    ID590074-1  ID601927-1  ID618382-4  ID513851-2  ID593355
ID585366-2    ID542097-3  ID599033-4  ID599769
```

##### LIBRARY VERSIONS
```
f5-sdk==3.0.20
```

##### CONFIGURATION
N/A

##### OS / ENVIRONMENT
N/A

##### SUMMARY
As the bigip_data_group module works today, it is not possible to add or remove individual data group key/values from a data group - which is possible inside the F5 UI when a data group is created as type 'internal'.

Currently, your choices are to provide a complete list of records in the 'records' list item, the complete list of records via a records_src file, or a complete list of records via the 'content' block statement. 'state: absent' or 'state: present' only adds or deletes the entire data group.

I'd like to propose that this module's functions be split in a way similar to bigip_pool and bigip_pool_member, where bigip_data_group would handle the addition and creation of data groups in full, and bigip_data_group_member would handle the addition and deletion of individual entries IN an internal data group.

##### STEPS TO REPRODUCE
Consider the circumstance of wanting to create a data group named 'stringset'. In tmsh, we'd do something like this to create it, then add a record, in separate operations:

`tmsh create ltm data-group internal stringset type string`
`tmsh modify ltm data-group internal stringset records add {"peanut_butter" {data "jelly"}}`

(Later, perhaps in a different loop):
`tmsh modify ltm data-group internal stringset records add {"sour_cream" {data "onion"}}`

I could go back later and delete the first record I added, without removing the second:
`tmsh modify ltm data-group internal stringset records delete {"peanut_butter" }`

`tmsh modify ltm data-group internal NAME records` (ver 11) allows the following:
```
  add               Add items to the set
  delete            Delete specific items from the set
  modify            Modify existing items in the set
  none              Remove all items from the set
  replace-all-with  Replace the set with a new set
```

I could see a theoretical module working something like this:
```
- name: Create a new data group member, modify key's value instead if key exists
  bigip_data_group_member:
    name: stringset
    internal: yes # May not be necessary if by definition it must be internal
    records:
      - key: "sour_cream"
        value: "onion" # Value is "" by default if not provided (?)
    state: present
    type: string # May not be needed either, since the data group already exists (?)
    provider:
        ...
  delegate_to: localhost

- name: Remove an existing data group member by key
  bigip_data_group_member:
    name: stringset
    internal: yes # May not be necessary if by definition it must be internal
    records:
      - key: "peanut_butter"
    state: absent
    type: string # May not be needed either, since the data group already exists (?)
    provider:
        ...
  delegate_to: localhost
```

##### EXPECTED RESULTS
N/A

##### ACTUAL RESULTS
N/A
