### ISSUE TITLE
Issue applying TCP Protocol profile for new virtual servers

### ISSUE THREAD

**Issue by luuke1** [F5Networks/f5-ansible#114]
##### ISSUE TYPE

```
- Bug Report
```

##### MODULE
```
bigip_virtual_server - Manages F5 BIG-IP LTM virtual servers
```

##### ANSIBLE VERSION

```
ansible 2.2.1.0
```

##### PYTHON VERSION

```
Python 2.7.5
```

##### BIGIP VERSION

```
version 11.6.0
build 6.0.442
```

##### SUMMARY
I am trying to create a playbook to create a new virtual server with some default configuration already applied.

I have managed to have success with a lot of the configuration so far, however whenever I try to chose a TCP Profile I encounter a duplicate profile error message

 I intend to change this so that it uses TCP-WAN-OPTIMIZED and TCP-LAN-OPTIMIZED,
I believe this may be a bug as the script is being used to create a Virtual server and it already encounters the profile clash error even though a profile should not be applied as it is in the creation process.

##### STEPS TO REPRODUCE

```
- name: Test add VIP
  hosts: [test]
  connection: local

  tasks:

   - name: Add virtual server
     bigip_virtual_server:
      server: 1.1.1.1
      user: ansible
      password: *****
      state: present
      partition: Common
      name: luketest6
      destination: 1.1.1.2
      port: 80
      pool: luketest
      snat: Automap
      description: Test Virtual Server
      all_profiles:
          - tcp-lan-optimized
      default_persistence_profile: source_address_3600
     delegate_to: localhost

I run the command ansible-playbook add-virtual-server.yaml -I hosts_inv.txt

```

##### EXPECTED RESULTS
I expect to have a tcp protocol profile applied.

##### ACTUAL RESULTS

I receive the following error and the configuration is not applied: 

fatal: [1.1.1.1 -> localhost]: FAILED! => {"changed": false, "failed": true, "msg": "received exception: Error on setting profiles : Server raised fault: 'Exception caught in LocalLB::urn:iControl:LocalLB/VirtualServer::add_profile()\nException: Common::OperationFailed\n\tprimary_error_code   : 17236119 (0x01070097)\n\tsecondary_error_code : 0\n\terror_string         : 01070097:3: Virtual server /Common/luketest6 lists duplicate profiles.'"}

**Comment by ashS1LV** [comment]
I believe this also occurs when you try this directly via TMSH. You need to use the {context serverside} or {context clientside} configuration to apply more than one profile, however I can't find how to do this within the bigip_virtual_server module, hopefully it's as simple as us missing how you define the context of each profile within the module.

**Comment by caphrim007** [comment]
@luuke1 @ashS1LV the module, at this time, does not make a distinction between server-side and client-side. There is a refactor of this module (i think it's called virtual_server2.py` that accepts a `profiles_client_side` and `profiles_server_side` to distinguish between the two. That's modules `profiles` option continues to work the way this module does; putting it as the context "all".

The vs2 module is probably still in a beta state, but if you'd like to try that one and make mention of any deficiencies you find, I'm all ears.

**Comment by luuke1** [comment]
@caphrim007 thanks for your response. I have now tried this new module however I still encounter the same issue: 

here is the playbook I created and ran:

- name: Test add VIP
  hosts: [test]
  connection: local

  tasks:

   - name: Add virtual server
     bigip_virtual_server:
      server: 1.1.1.1
      user: ansible
      password: ansiblecloud
      state: present
      partition: Common
      name: luketest6
      destination: 10.10.10.10
      port: 80
      pool: luketest
      snat: Automap
      description: Test Virtual Server
      profiles_both:
        - http
        - fix
      profiles_server_side:
        - clientssl
      profiles_client_side:
        - ilx
      default_persistence_profile: source_address_3600
     delegate_to: localhost

Here is the error I encountered:  fatal: [1.1.1.1 -> localhost]: FAILED! => {"changed": false, "failed": true, "msg": "unsupported parameter for module: profiles_client_side"}

**Comment by caphrim007** [comment]
@luuke1 unless you personally renamed the file, the correct file should be called `bigip_virtual_server2.py` and should be used as such in your playbook

```
- name: asdasda
   bigip_virtual_server2:
        param1: asdasd
   ...
```

You look like you're using `bigip_virtual_server` still. here is the file you want

https://github.com/F5Networks/f5-ansible/blob/devel/library/bigip_virtual_server2.py
