### ISSUE TITLE
loginProviderName is invalid

### ISSUE THREAD

**Issue by perzizzle** [F5Networks/f5-ansible#1174]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

bigip_node

##### ANSIBLE VERSION

```
> ansible --version
ansible 2.7.0
```

##### PYTHON VERSION

```
> python -V
Python 2.7.5
```

##### BIGIP VERSION

```
BIG-IP 14.0.0.3 Build 0.0.4 Point Release 3
```

##### LIBRARY VERSIONS

```
> pip freeze | egrep '(f5-sdk|bigsuds)'
bigsuds==1.0.4
f5-sdk==3.0.20
```

##### STEPS TO REPRODUCE

```
- name: Disable node in LTM
  local_action:
    module: bigip_node
    provider:
      server: '{{ f5_ltm_server }}'
      user: '{{ f5_ltm_username }}'
      password: '{{ f5_ltm_password }}'
    state: offline
    partition: Common
    name: "{{ inventory_hostname }}"
```

##### EXPECTED RESULTS

Would expect node to go to disabled state

##### ACTUAL RESULTS

No change on f5, playbook throws error.

```
TASK [disableNode : Disable node in LTM] ************************************************************************
fatal: [hostname -> localhost]: FAILED! => {"changed": false, "msg": "Unable to connect to ltm_server on port 443. The reported error was \"Status code: None. Unexpected Error: HTTP Error 400: Bad Request for uri: None\nText: {\"code\":400,\"message\":\"loginProviderName is invalid.\",\"originalRequestBody\":\"{\\\"username\\\":\\\"ansible\\\",\\\"loginProviderName\\\":\\\"tmos\\\",\\\"generation\\\":0,\\\"lastUpdateMicros\\\":0}\",\"referer\":\"192.168.31.211\",\"restOperationId\":33968753,\"kind\":\":resterrorresponse\"}\"."}
```

I believe this may be related to https://github.com/F5Networks/f5-ansible/issues/976 and basic auth.

**Comment by wojtek0806** [comment]
please install f5ansible galaxy role and test as this is fixed in the devel. Fix will ship with ansible 2.8

**Comment by perzizzle** [comment]
Do you know what commit this was fixed in? I'd like to back patch it into our 2.7 release since using devel in production isn't an option for us.

**Comment by wojtek0806** [comment]
i would not recomend it , however here is the commit hash:
`a9b4ea6e5f3e8b1d5fa0c709746a8f376174176b`

**Comment by wojtek0806** [comment]
if you can please take the opportunity to test with the role it does not override your ansible install. let me know if we need to reopen this

**Comment by perzizzle** [comment]
Do you have any documentation on how to use that galaxy role? I was expecting to find an ansible.cfg that pointed to the library/module_utils folder for this specific role but the only one I found was in tests folder and it just contained

`[defaults]
roles_path = ../../
retry_files_enabled = False
host_key_checking = False`

I tried added (absolute and relative path):
`library        = "/etc/ansible/roles/f5devcentral.f5ansible/"
module_utils   = "/etc/ansible/roles/f5devcentral.f5ansible/"`

I created a tiny playbook to run bigip_node and ran it
`$ ansible-playbook test.yml --extra-vars=@extra_vars.yml -vvv
ansible-playbook 2.7.5
  config file = /etc/ansible/roles/f5devcentral.f5ansible/tests/ansible.cfg
  configured module search path = [u'/etc/ansible/roles/f5devcentral.f5ansible/tests/"/etc/ansible/roles/f5devcentral.f5ansible/"']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible-playbook
  python version = 2.7.5 (default, May 31 2018, 09:41:32) [GCC 4.8.5 20150623 (Red Hat 4.8.5-28)]
Using /etc/ansible/roles/f5devcentral.f5ansible/tests/ansible.cfg as config file
...
"msg": "Unable to connect to mll-ltm01.surescripts.internal on port 443. The reported error was \"Status code: None. Unexpected Error: HTTP Error 400: Bad Request for uri: None\nText: {\"code\":400,\"message\":\"loginProviderName is invalid.\",\"originalRequestBody\":\"{\\\"username\\\":\\\"ansible\\\",\\\"loginProviderName\\\":\\\"tmos\\\",\\\"generation\\\":0,\\\"lastUpdateMicros\\\":0}\",\"referer\":\"192.168.30.200\",\"restOperationId\":38541824,\"kind\":\":resterrorresponse\"}\"."
`

I'm not convinced I'm using the library and module_utils from the galaxy role.

The basic problem I have is we use bigip_node heavily to do rolling deploys in production. Ansible 2.8 isn't expected to be released till 5/2 which means I'm currently stuck on ansible 2.4. I want to upgrade ansible for other reasons.

**Comment by wojtek0806** [comment]
the usage example is on the ansible galaxy, this role requires that you have 2.7 ansible installed already otherwise it will not work

**Comment by wojtek0806** [comment]
You need to look here on how the roles work:
https://docs.ansible.com/ansible/latest/user_guide/playbooks_reuse_roles.html

The code for modules and module_utils as well as plugins is in the role already.

**Comment by perzizzle** [comment]
Gotcha, I was missing the fact you are literally providing an ansible role, I was expecting library/module_utils to be at the root file system an ansible.cfg configured to pull them in (following https://docs.ansible.com/ansible/latest/user_guide/playbooks_best_practices.html)

I created a new test.yml at the /etc/ansible
```
- name: Network Automation Playbook
  hosts: localhost
  connection: local
  gather_facts: false
  roles:
    - f5devcentral.f5ansible
```

And updated roles/f5devcentral.f5ansible/tasks/main.yaml

```
- name: Enable node in LTM
  local_action:
    module: bigip_node
    server: '{{ f5_ltm_server }}'
    user: '{{ f5_ltm_username }}'
    password: '{{ f5_ltm_password }}'
    state: enabled
    partition: Common
    name: "{{ server }}"
    validate_certs: no
```

Then ran it
```
 ansible-playbook test.yml --extra-vars=@extra_vars.yml
PLAY [Network Automation Playbook] ************************************************************************************************************************************************************

TASK [f5devcentral.f5ansible : Check ansible version] *****************************************************************************************************************************************
skipping: [localhost]

TASK [f5devcentral.f5ansible : Enable node in LTM] ********************************************************************************************************************************************
ok: [localhost -> localhost] => (item=[0, u'ltm_server'])
```

Success, guess one option is to package this full role with each role we use for manipulating F5 gear until ansible 2.8 is released. Is this how you expect people to use this role? Would you accept a doc update to the galaxy role with more detailed documentation.

Thanks for the help.
