### ISSUE TITLE
bigip_firewall_rule - Building ICMP protocol Rules, dest/src address_lists are not populated when icmp_message parameters are provided

### ISSUE THREAD

**Issue by neozoolook** [F5Networks/f5-ansible#1190]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

bigip_firewall_rule.py

##### ANSIBLE VERSION

```
Ansible 2.7
```

##### PYTHON VERSION

```
Python 2.7.12
```

##### BIGIP VERSION

```
Sys::Version
Main Package
  Product     BIG-IP
  Version     13.1.0.7
  Build       0.45.1
  Edition     Engineering Hotfix
  Date        Thu Jun  7 09:58:35 PDT 2018

Hotfix List
ID720045-1
```

##### OS / ENVIRONMENT

Ubuntu 16.04TS (ansible server host)

##### SUMMARY

When running a playbook leveraging bigip_firewall_rule.py for ICMP rule create with specific icmp_message values defined as well as source and destination address-list parameters, the rule is created only with the icmp_messages and source/destination objects are not included.  This requires you to break up the play into two separate plays.  First play builds with icmp_messages types, then run second play to include the source/destination objects, then rule is correctly built.  

Seems this isn't normal behavior, as I would expect you can do this with single play, like TCP and UDP protocol rule builds.

##### STEPS TO REPRODUCE

```
Broken Single Playbook Method;
- name: Create Rule - {{ rule_list_scp.rule2_name }}
  bigip_firewall_rule:
    name: "{{ rule_list_scp.rule2_name }}"
    description: "{{ rule_list_scp.rule2_desc }}"
    parent_rule_list: "{{ rule_list_scp.name }}"
    protocol: "{{ rule_list_scp.rule2_proto }}"
    icmp_message:
      - type: 0
      - type: 8
      - type: 30
    source:
      - address_list: "{{ rule_list_scp.rule2_src_addr }}"
    destination:
      - address_list: "{{ rule_list_scp.rule2_dst_addr }}"
    action: "{{ rule_list_scp.rule2_act }}"
    logging: yes
    provider:
      server: "{{ ansible_host }}"
      user: "{{ username }}"
      password: "{{ password }}"
      validate_certs: "no"
  delegate_to: localhost
```

```
Current Workaround using two plays;

- name: Create Rule - {{ rule_list_scp.rule2_name }}
  bigip_firewall_rule:
    name: "{{ rule_list_scp.rule2_name }}"
    description: "{{ rule_list_scp.rule2_desc }}"
    parent_rule_list: "{{ rule_list_scp.name }}"
    protocol: "{{ rule_list_scp.rule2_proto }}"
    icmp_message:
      - type: 0
      - type: 8
      - type: 30
    action: "{{ rule_list_scp.rule2_act }}"
    logging: yes
    provider:
      server: "{{ ansible_host }}"
      user: "{{ username }}"
      password: "{{ password }}"
      validate_certs: "no"
  delegate_to: localhost

- name: Update Rule - {{ rule_list_scp.rule2_name }}
  bigip_firewall_rule:
    name: "{{ rule_list_scp.rule2_name }}"
    description: "{{ rule_list_scp.rule2_desc }}"
    parent_rule_list: "{{ rule_list_scp.name }}"
    protocol: "{{ rule_list_scp.rule2_proto }}"
    source:
      - address_list: "{{ rule_list_scp.rule2_src_addr }}"
    destination:
      - address_list: "{{ rule_list_scp.rule2_dst_addr }}"
    action: "{{ rule_list_scp.rule2_act }}"
    logging: yes
    provider:
      server: "{{ ansible_host }}"
      user: "{{ username }}"
      password: "{{ password }}"
      validate_certs: "no"
  delegate_to: localhost
```

##### ACTUAL RESULTS

```

```

**Comment by neozoolook** [comment]
@wojtek0806 well I installed the galaxy role and reran the playbooks and it's now complaining about module failure, stating that unsupported parameter of 'auth_provider' found in provider.  However I do not specify this parameter at all in my plays;

-vvv output
```
pp2854@dark-kyber:~/ansible-vscp_fw$ ansible-playbook base.yml --ask-vault-pass -vvv
ansible-playbook 2.7.6
  config file = /home/pp2854/ansible-vscp_fw/ansible.cfg
  configured module search path = [u'/home/pp2854/.ansible/roles/f5devcentral.f5ansible/library/modules']
  ansible python module location = /usr/local/lib/python2.7/dist-packages/ansible
  executable location = /usr/local/bin/ansible-playbook
  python version = 2.7.12 (default, Dec  4 2017, 14:50:18) [GCC 5.4.0 20160609]
Using /home/pp2854/ansible-vscp_fw/ansible.cfg as config file
Vault password: 
/home/pp2854/ansible-vscp_fw/hosts did not meet host_list requirements, check plugin documentation if this is unexpected
/home/pp2854/ansible-vscp_fw/hosts did not meet script requirements, check plugin documentation if this is unexpected
Parsed /home/pp2854/ansible-vscp_fw/hosts inventory source with ini plugin

PLAYBOOK: base.yml *****************************************************************************************************************
1 plays in base.yml

PLAY [zrdm6bfrwl47] ****************************************************************************************************************
META: ran handlers

TASK [/home/pp2854/.ansible/roles/f5devcentral.f5ansible : Check ansible version] **************************************************
task path: /home/pp2854/.ansible/roles/f5devcentral.f5ansible/tasks/main.yaml:7
skipping: [zrdm6bfrwl47scp001] => {}

TASK [Create Rule List - TEST_RULE_LIST] *******************************************************************************************
task path: /home/pp2854/ansible-vscp_fw/base.yml:11
Using module file /home/pp2854/.ansible/roles/f5devcentral.f5ansible/library/bigip_firewall_rule_list.py
<localhost> ESTABLISH LOCAL CONNECTION FOR USER: pp2854
<localhost> EXEC /bin/sh -c '/usr/bin/python && sleep 0'
fatal: [zrdm6bfrwl47scp001 -> localhost]: FAILED! => {
    "changed": false, 
    "invocation": {
        "module_args": {
            "description": "Rule List for Cricket IPv4 Flows", 
            "name": "TEST_RULE_LIST", 
            "partition": "Common", 
            "password": null, 
            "provider": {
                "auth_provider": null, 
                "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER", 
                "server": "107.112.169.223", 
                "server_port": null, 
                "ssh_keyfile": null, 
                "timeout": null, 
                "transport": "rest", 
                "user": "admin", 
                "validate_certs": "no"
            }, 
            "rules": [
                "ALLOW-CRICKET-TCP", 
                "ALLOW-CRICKET-ICMP", 
                "DEFAULT-DROP"
            ], 
            "server": null, 
            "server_port": null, 
            "state": "present", 
            "transport": null, 
            "user": null, 
            "validate_certs": null
        }
    }, 
    "msg": "Unsupported parameters for (bigip_firewall_rule_list) module: auth_provider found in provider. Supported parameters include: password, server, server_port, ssh_keyfile, timeout, transport, user, validate_certs"
}
```

**Comment by neozoolook** [comment]
@wojtek0806 here is the playbooks leveraging the use of the role;

```
---
- hosts: zrdm6bfrwl47
  connection: local
  gather_facts: false
  vars:
  roles:
    - role: /home/pp2854/.ansible/roles/f5devcentral.f5ansible


  tasks:
    - name: Create Rule List - {{ rule_list_test.name }}
      bigip_firewall_rule_list:
        name: "{{ rule_list_test.name }}"
        description: "{{ rule_list_test.description }}"
        rules:
          - "{{ rule_list_test.rule1_name }}"
          - "{{ rule_list_test.rule2_name }}"
          - "{{ rule_list_test.rule3_name }}"
        provider:
          server: "{{ ansible_host }}"
          user: "{{ username }}"
          password: "{{ password }}"
          validate_certs: "no"
      delegate_to: localhost

    - name: Create Rule - {{ rule_list_test.rule1_name }}
      bigip_firewall_rule:
        name: "{{ rule_list_test.rule1_name }}"
        description: "{{ rule_list_test.rule1_desc }}"
        parent_rule_list: "{{ rule_list_test.name }}"
        protocol: "{{ rule_list_test.rule1_proto }}"
        source:
          - address_list: "{{ rule_list_test.rule1_src_addr }}"
        destination:
          - address_list: "{{ rule_list_test.rule1_dst_addr }}"
          - port_list: "{{ rule_list_test.rule1_dst_port }}"
        action: "{{ rule_list_test.rule1_act }}"
        logging: yes
        provider:
          server: "{{ ansible_host }}"
          user: "{{ username }}"
          password: "{{ password }}"
          validate_certs: "no"
      delegate_to: localhost

    - name: Create Rule - {{ rule_list_test.rule2_name }}
      bigip_firewall_rule:
        name: "{{ rule_list_test.rule2_name }}"
        description: "{{ rule_list_test.rule2_desc }}"
        parent_rule_list: "{{ rule_list_test.name }}"
        protocol: "{{ rule_list_test.rule2_proto }}"
        icmp_message:
          - type: 0
          - type: 8
          - type: 30
        action: "{{ rule_list_test.rule2_act }}"
        logging: yes
        provider:
          server: "{{ ansible_host }}"
          user: "{{ username }}"
          password: "{{ password }}"
          validate_certs: "no"
      delegate_to: localhost

    - name: Update Rule - {{ rule_list_test.rule2_name }}
      bigip_firewall_rule:
        name: "{{ rule_list_test.rule2_name }}"
        description: "{{ rule_list_test.rule2_desc }}"
        parent_rule_list: "{{ rule_list_test.name }}"
        protocol: "{{ rule_list_test.rule2_proto }}"
        source:
          - address_list: "{{ rule_list_test.rule2_src_addr }}"
        destination:
          - address_list: "{{ rule_list_test.rule2_dst_addr }}"
        action: "{{ rule_list_test.rule2_act }}"
        logging: yes
        provider:
          server: "{{ ansible_host }}"
          user: "{{ username }}"
          password: "{{ password }}"
          validate_certs: "no"
      delegate_to: localhost

    - name: Create Rules - {{ rule_list_test.rule3_name }}
      bigip_firewall_rule:
        name: "{{ rule_list_test.rule3_name }}"
        description: "{{ rule_list_test.rule3_desc }}"
        parent_rule_list: "{{ rule_list_test.name }}"
        action: "{{ rule_list_test.rule3_act }}"
        logging: yes
        provider:
          server: "{{ ansible_host }}"
          user: "{{ username }}"
          password: "{{ password }}"
          validate_certs: "no"
      delegate_to: localhost
```

```

**Comment by wojtek0806** [comment]
FMFA-238

**Comment by wojtek0806** [comment]
i am looking at it but in future please provide playbooks with the actual values or at least the output from the run so I see what values did you use.

**Comment by wojtek0806** [comment]
I have ran this on my devel branch and the issue does not exist:
```
---

- name: AFM_RULE_TEST
  hosts: f5-test[0]
  connection: local
  gather_facts: no

  roles:
    - role: f5devcentral.f5ansible

  vars:
    f5_provider:
      password: "admin"
      server: "{{ ansible_host }}"
      user: "admin"
      validate_certs: "no"
      server_port: "443"



  tasks:
    - name: Create a basic rule list
      bigip_firewall_rule_list:
        name: test_list
        provider: "{{ f5_provider }}"

    - name: Create a source list
      bigip_firewall_address_list:
        name: src_list
        addresses:
          - 1.1.1.1
          - 2.2.2.2
        provider: "{{ f5_provider }}"

    - name: Create a destination list
      bigip_firewall_address_list:
        name: dst_list
        addresses:
          - 3.3.3.3
          - 4.4.4.4
          - 5.5.5.5
        provider: "{{ f5_provider }}"

    - name: Create Rule - TEST_RULE_LIST
      bigip_firewall_rule:
        name: TEST_RULE_LIST
        description: "foobar"
        parent_rule_list: test_list
        protocol: icmp
        icmp_message:
          - type: 0
          - type: 8
          - type: 30
        source:
          - address_list: src_list
        destination:
          - address_list: dst_list
        action: accept
        logging: yes
        provider: "{{ f5_provider }}"
```
Result in GUI:
![result_in_gui](https://user-images.githubusercontent.com/18006037/57581399-3e9fad80-74b7-11e9-86da-3639fa516554.png)

Please use the above playbook to retest. I will close this issue as non reproducible, will reopen once you provide the playbook that reproduces the issue.
