### ISSUE TITLE
BIGIP_DEVICE_FACTS subset gtm-a-pool: pool members is an empty list

### ISSUE THREAD

**Issue by devopswang** [F5Networks/f5-ansible#1191]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

BIGIP_DEVICE_FACTS subset gtm-a-pool

##### ANSIBLE VERSION

```
ansible 2.7.0
  config file = /home/labuser/ansible.cfg
  configured module search path = [u'/home/labuser/library']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, Jul 13 2018, 13:06:57) [GCC 4.8.5 20150623 (Red Hat 4.8.5-28)]
```

##### PYTHON VERSION

```
Python 2.7.5
```

##### BIGIP VERSION

```
Tried both 14.1 and 12.1
```

##### SUMMARY
bigip_device_facts subset gtm-a-pools or gtm-aaaa-pools doesn't return any member info. It is blank.

##### STEPS TO REPRODUCE

```
  - name: Collect BIG-IP facts - GTM Pool
     bigip_device_facts:
       provider: "{{ provider }}"
       gather_subset:
         - gtm-a-pools
         - gtm-aaaa-pools
     register: deviceFactsGTM
     delegate_to: localhost

   - name: Collect GTM facts - GTM Pool
     bigip_gtm_facts:
       provider: "{{ provider }}"
       include: pool

```

##### EXPECTED RESULTS

gtm pool pool_f5lab and pool_f5lab_IPV6 should show the virtual server inside the pool.

bigip_gtm_facts returns the vs member info:
<img width="543" alt="image" src="https://user-images.githubusercontent.com/34286347/51960394-f7178780-24ac-11e9-93dc-e6073be817b7.png">

##### ACTUAL RESULTS
bigip_device_facts returns blank member info:
<img width="453" alt="image" src="https://user-images.githubusercontent.com/34286347/51960433-19a9a080-24ad-11e9-86c9-bcac7da5d02a.png">
