### ISSUE TITLE
Support strict-resume in client-ssl profile

### ISSUE THREAD

**Issue by tdm00** [F5Networks/f5-ansible#1201]
##### ISSUE TYPE

 - Feature Idea

##### COMPONENT NAME

bigip_profile_client_ssl

##### ANSIBLE VERSION

```
ansible 2.7.6
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.15rc1 (default, Nov 12 2018, 14:31:15) [GCC 7.3.0]

```

##### PYTHON VERSION

```
Python 2.7.15rc1
```

##### BIGIP VERSION

```
root@(bigip1)(cfg-sync Standalone)(Active)(/Common)(tmos)# show sys version

Sys::Version
Main Package
  Product     BIG-IP
  Version     13.1.0.7
  Build       0.0.1
  Edition     Point Release 7
  Date        Tue May 15 15:26:30 PDT 2018

```

##### OS / ENVIRONMENT

```
root@adb80a0ee03c:/var/ansible# cat /etc/lsb-release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=18.04
DISTRIB_CODENAME=bionic
DISTRIB_DESCRIPTION="Ubuntu 18.04 LTS"
```

##### SUMMARY

Please add support for the strict-resume option available in client-ssl profiles. This setting has two values available, enabled or disabled.

##### STEPS TO REPRODUCE

```
  - name: 'Create client_ssl profile clientssl_v4'
    bigip_profile_client_ssl:
      name: 'clientssl_v4'
      ciphers: 'DHE-RSA-AES256-GCM-SHA384:DHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-SHA256:DHE-RSA-AES256-SHA:DHE-RSA-AES128-SHA256:DHE-RSA-AES128-SHA:AES256-GCM-SHA384:AES128-GCM-SHA256:AES256-SHA256:AES256-SHA:AES128-SHA256:AES128-SHA:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-RSA-AES256-SHA384:ECDHE-RSA-AES256-CBC-SHA:ECDHE-RSA-AES128-SHA256:ECDHE-RSA-AES128-CBC-SHA:!sslv3:!tlsv1'
      options:
        - 'no-tlsv1'
      parent: '/Common/clientssl'
      strict-resume: 'enabled'
      server: '{{ inventory_hostname }}'
      server_port: 443
      user: '{{ vault_bigip_username }}'
      password: '{{ vault_bigip_password }}'
      validate_certs: no
    delegate_to: localhost

```

##### EXPECTED RESULTS

Successful change

##### ACTUAL RESULTS

The change fails

```
TASK [Create client_ssl profile clientssl_v4] **********************************************************************************************
task path: /var/ansible/base.yml:33
<localhost> ESTABLISH LOCAL CONNECTION FOR USER: root
<localhost> EXEC /bin/sh -c 'echo ~root && sleep 0'
<localhost> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /root/.ansible/tmp/ansible-tmp-1549298371.0-73625138511264 `" && echo ansible-tmp-1549298371.0-73625138511264="` echo /root/.ansible/tmp/ansible-tmp-1549298371.0-73625138511264 `" ) && sleep 0'
Using module file /usr/lib/python2.7/dist-packages/ansible/modules/network/f5/bigip_profile_client_ssl.py
<localhost> PUT /root/.ansible/tmp/ansible-local-471S0gHnn/tmpCbfZ5J TO /root/.ansible/tmp/ansible-tmp-1549298371.0-73625138511264/AnsiballZ_bigip_profile_client_ssl.py
<localhost> EXEC /bin/sh -c 'chmod u+x /root/.ansible/tmp/ansible-tmp-1549298371.0-73625138511264/ /root/.ansible/tmp/ansible-tmp-1549298371.0-73625138511264/AnsiballZ_bigip_profile_client_ssl.py && sleep 0'
<localhost> EXEC /bin/sh -c '/usr/bin/python2 /root/.ansible/tmp/ansible-tmp-1549298371.0-73625138511264/AnsiballZ_bigip_profile_client_ssl.py && sleep 0'
<localhost> EXEC /bin/sh -c 'rm -f -r /root/.ansible/tmp/ansible-tmp-1549298371.0-73625138511264/ > /dev/null 2>&1 && sleep 0'
The full traceback is:
WARNING: The below traceback may *not* be related to the actual failure.
  File "/tmp/ansible_bigip_profile_client_ssl_payload_Sv3bQx/__main__.py", line 226, in <module>
    from library.module_utils.network.f5.bigip import HAS_F5SDK

fatal: [192.168.1.230 -> localhost]: FAILED! => {
    "changed": false,
    "invocation": {
        "module_args": {
            "ciphers": "DHE-RSA-AES256-GCM-SHA384:DHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-SHA256:DHE-RSA-AES256-SHA:DHE-RSA-AES128-SHA256:DHE-RSA-AES128-SHA:AES256-GCM-SHA384:AES128-GCM-SHA256:AES256-SHA256:AES256-SHA:AES128-SHA256:AES128-SHA:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-RSA-AES256-SHA384:ECDHE-RSA-AES256-CBC-SHA:ECDHE-RSA-AES128-SHA256:ECDHE-RSA-AES128-CBC-SHA:!sslv3:!tlsv1",
            "name": "clientssl_v4",
            "options": [
                "no-tlsv1"
            ],
            "parent": "/Common/clientssl",
            "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "provider": {
                "auth_provider": null,
                "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
                "server": "192.168.1.230",
                "server_port": 443,
                "ssh_keyfile": null,
                "timeout": null,
                "transport": "rest",
                "user": "admin",
                "validate_certs": false
            },
            "server": "192.168.1.230",
            "server_port": 443,
            "strict-resume": "enabled",
            "user": "admin",
            "validate_certs": false
        }
    },
    "msg": "Unsupported parameters for (bigip_profile_client_ssl) module: strict-resume Supported parameters include: allow_non_ssl, auth_provider, cert_key_chain, ciphers, name, options, parent, partition, password, provider, secure_renegotiation, server, server_port, state, transport,user, validate_certs"
}
```
