### ISSUE TITLE
Setting up "session user-disabled" and "monitor none" to a pool's specific node with bigip_pool_member

### ISSUE THREAD

**Issue by onurbrc** [F5Networks/f5-ansible#1203]
##### ISSUE TYPE

 - Feature Idea

##### COMPONENT NAME

bigip_pool_member

##### ANSIBLE VERSION

```
ansible 2.7.0
  python version = 2.7.15rc1 (default, Apr 15 2018, 21:51:34) [GCC 7.3.0]
```

##### PYTHON VERSION

```
 python version = 2.7.15rc1
```

##### BIGIP VERSION

```
BIG-IP 12.1.3 Build 0.0.378 Final
```
##### LIBRARY VERSIONS

```
bigsuds==1.0.6
f5-sdk==3.0.18
```

##### OS / ENVIRONMENT
```
Distributor ID: Ubuntu
Description:    Ubuntu 18.04 LTS
Release:        18.04
```

##### SUMMARY
Hi, 

Is it possible to disable a specific node and set up its health monitor to "none" only inside a given pool ? 
I have several pools with a big amount of nodes in. Sometimes, We must disable a small number of them  cutting off the established user-sessions and the health monitor requests in progress without affecting other pools. 

##### STEPS TO REPRODUCE
Example with one server  : 
```
modify ltm pool http_pool members modify { ws999is03:8080  { session user-disabled monitor none } } 
```

##### EXPECTED RESULTS
```
ltm pool http_pool {
    members {
        ws999is01:8080 {
            address 10.10.10.10
            session monitor-enabled
            state up
        }
        ws999is02:8080 {
            address 10.10.10.20
            session monitor-enabled
            state up
        }
        ws999is03:8080_ {
            address 10.10.10.30
            monitor none
            session user-disabled
        }
    }
    monitor myHTTP_HCK
}

```

##### ACTUAL RESULTS

Input : 
```
POOLs: 
   - name: http_pool
     nodes: [ws999is03] 
     targetPort: 8080 
```
Task :
```
     - name: "Force session-client offline and local HealthCheck down"
       bigip_pool_member:
            server: "lb.mydomain.com"
            user: "admin"
            password: "secret"
            state: forced_offline
            pool: "{{ item.0.name }}"
            partition: "{{ partition_zone | default('Common') }}"
            host: "{{ item.1 }}"
            port: "{{ item.0.targetPort}}"
            validate_certs: no
       delegate_to: localhost
       with_subelements: 
          - "{{ POOLs }}"
          - "nodes"
```
Result: 

```
ltm pool http_pool {
    members {
        ws999is01:8080 {
            address 10.10.10.10
            session monitor-enabled
            state up
        }
        ws999is02:8080 {
            address 10.10.10.20
            session monitor-enabled
            state up
        }
        ws999is03:8080 {
            address 10.10.10.30
            session user-disabled
            state user-down
        }
    }
    monitor myHTTP_HCK
}

```
##### QUESTION
Is there any possibility to reproduce the  "session user-disabled" and "monitor none" behavior using bigip_pool_member ? How could I reactivate those nodes doing something like "session user-enabled monitor default" with this module ?

**Comment by wojtek0806** [comment]
Let me clarify something beforehand: node is a different object which is a single IP address representing a server, the said server can run multiple services on different ports, ergo be a source of  multiple pool members for different pools,  a pool member is an IP address with port. You are looking to remove monitor for a pool and set the session to user-disabled. 

This can be achieved by setting up `state: disabled`, and `monitor: 'none` or `monitor: ''` you can also use `state: forced_offline` this will however give you a different state from your example, see below links to the module code:

https://github.com/F5Networks/f5-ansible/blob/devel/library/modules/bigip_pool_member.py#L134
https://github.com/F5Networks/f5-ansible/blob/devel/library/modules/bigip_pool_member.py#L711
https://github.com/F5Networks/f5-ansible/blob/devel/library/modules/bigip_pool_member.py#L1301
https://github.com/F5Networks/f5-ansible/blob/devel/library/modules/bigip_pool_member.py#L1296

Since monitors will be introduced in 2.8, you can either use tmsh command for the meantime, or install and use ansible-galaxy role that wraps around the devel code:
https://galaxy.ansible.com/f5devcentral/f5ansible

**Comment by onurbrc** [comment]
Hi @wojtek0806 , thank you for you reply. 

Actually, I don't want to remove a monitor from the whole pool as you said, I want just disable the health checks of a given node inside a pool without affecting the other nodes inside neither the other pools wrapping this disabled node. 

I wanted use session user-disable to delete existing connections within that node and its pool only. But, I don't know if I'm using well. 

Is there any possibility to kill persistent sessions before waiting its tiemout as said here  https://support.f5.com/csp/article/K13310 ?

I'll look the follow links you mentioned. Thanks.

**Comment by wojtek0806** [comment]
the monitors property are for pool member not the pool

**Comment by onurbrc** [comment]
Thank you @wojtek0806 ! 

The monitor parameter for pool members will be enough for me.

We can close this issue. 
Best regards.

**Comment by wojtek0806** [comment]
can you please explain what do you mean by "ignored" ? If you could provide some output and the playbook you used as well.

**Comment by onurbrc** [comment]
Here it is my playbook : 

```
  roles: 
     - role: f5devcentral.f5ansible 
 
  tasks:
     - name: "Force session-client offline and local HealthCheck down"
       bigip_pool_member:
            server: "lb.mydomain.com"
            user: "admin"
            password: "secret"
            state: forced_offline
            monitors: none
            pool: "{{ item.0.name }}"
            partition: "{{ partition_zone | default('Common') }}"
            host: "{{ item.1 }}"
            port: "{{ item.0.targetPort}}"
            validate_certs: no
       delegate_to: localhost
       with_subelements: 
          - "{{ POOLs }}"
          - "nodes"
```
I'm running the tasks, but the health monitor seems not to be modified to "None" when I use  "state: forced_offline" or  "state: disabled". 

Using "state: forced_offline", my audit log gives me : 
```
modify ltm pool /Common/http_pool { members modify { /Common/ws999is01:80 { state user-down session user-disabled } } }
```

Using "state: disabled", my audit log gives me : 

```
modify ltm pool /Common/http_pool { members modify { /Common/ws999is01:80 { state user-up session user-enabled } } }
```

Could you confirm to me that using "monitors: none", the task should make a changing at "Local Traffic  ››  Pools : Pool List  ››  http_pool ›› members ›› Configuration: Advanced ›› Health Monitors  ›› None" level ?
