### ISSUE TITLE
Creating ha-group resources 

### ISSUE THREAD

**Issue by onurbrc** [F5Networks/f5-ansible#1215]
##### ISSUE TYPE

 - Feature Idea

##### COMPONENT NAME

bigip_ha_group (or bigip_sys_ha_group) 

##### ANSIBLE VERSION

```
ansible 2.7.0
  python version = 2.7.15rc1 (default, Apr 15 2018, 21:51:34) [GCC 7.3.0]
```

##### PYTHON VERSION

```
 python version = 2.7.15rc1
```

##### BIGIP VERSION

```
BIG-IP 12.1.3 Build 0.0.378 Final
```
##### LIBRARY VERSIONS

```
bigsuds==1.0.6
f5-sdk==3.0.18
```

##### OS / ENVIRONMENT
```
Distributor ID: Ubuntu
Description:    Ubuntu 18.04 LTS
Release:        18.04
```

##### SUMMARY
Hi, 

Is it possible to create a new feature to create ha-groups ? 
It would be nice to create a different health criteria groups to control High availability.

##### STEPS TO REPRODUCE
```
GUI > System  ››  High Availability : HA Group List  ››  Add HA Group...

CLI > create sys ha-group MY-HA-GROUP ...

```
Meanwhile, I'm creating ha-groups with the task below : 

```
  tasks:
  
    - name: Add a new HA-Group
      bigip_command:
        commands: "create sys ha-group ha-group-PROD active-bonus 14 trunks add { DATA { weight 20 }} pools add { /{{ partition_zone|default('Common') }}/pool_gateway_ext { weight 25} /{{ partition_zone|default('Common') }}/pool_gateway_int { weight 25}}"
        server: lb.mydomain.com
        user: admin
        password: secret
        validate_certs: no
      delegate_to: localhost
```

##### EXPECTED RESULTS
 HA Group :
```
sys ha-group ha-group-PROD {
    active-bonus 14
    trunks {
        DATA {
            percent-up 100
            weight 20
        }
    pools {
       pool_gateway_ext {
            percent-up 100
            weight 25
        }
        pool_gateway_int {
            percent-up 100
            weight 25
        }
    }
}

```

##### ACTUAL RESULTS
We achieve the expected result with bigip_command until now, but without check-mode neither idempotency. 
Thank you in advance. 
Best regards.
