### ISSUE TITLE
Assign ha-group object to a traffic-group

### ISSUE THREAD

**Issue by onurbrc** [F5Networks/f5-ansible#1216]
##### ISSUE TYPE

 - Feature Idea

##### COMPONENT NAME

bigip_traffic_group

##### ANSIBLE VERSION

```
ansible 2.7.0
  python version = 2.7.15rc1 (default, Apr 15 2018, 21:51:34) [GCC 7.3.0]
```

##### PYTHON VERSION

```
 python version = 2.7.15rc1
```

##### BIGIP VERSION

```
BIG-IP 12.1.3 Build 0.0.378 Final
```
##### LIBRARY VERSIONS

```
bigsuds==1.0.6
f5-sdk==3.0.18
```

##### OS / ENVIRONMENT
```
Distributor ID: Ubuntu
Description:    Ubuntu 18.04 LTS
Release:        18.04
```

##### SUMMARY
Hi, 

Is it possible to add a new feature to the bigip_traffic_group  to accept "Advanced Setup Options"  like the selection of ha-group object as a "Failover Method" option ?

##### STEPS TO REPRODUCE

HA Group list :
```
sys ha-group ha-group-PROD {...}
sys ha-group ha-group-STK {...}
sys ha-group ha-group-SAU {...}

```
Our ha-group already exists, so we associate it to a traffic-group as follow : 
Example with CLI  : 
```
modify cm traffic-group traffic-group-1 ha-group MY-HA-GROUP

```
To do this with Ansible, I'm using bigip_command and the task below :

```
    - name: "Modify Failover Method  > HA Group > ha-group-PROD"
      bigip_command:
        commands: "modify cm traffic-group traffic-group-1 ha-group ha-group-PROD"
        server: lb.mydomain.com
        user: admin
        password: secret
        validate_certs: no
      delegate_to: localhost 
```

##### EXPECTED RESULTS
Traffic-group : 

```
cm traffic-group traffic-group-1 {
    ha-group ha-group-PROD
    mac aa:bb:cc:dd:ff:00
    unit-id 1
}

```

##### ACTUAL RESULTS
We achieve this expected result with bigip_command until now, but without check-mode neither idempotency. 
Thank you in advance. 
Best regards.
