### ISSUE TITLE
bigip_ucs_fetch error

### ISSUE THREAD

**Issue by davbeny** [F5Networks/f5-ansible#1240]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

bigip_ucs_fetch
##### ANSIBLE VERSION

```
2.7.0
```

##### PYTHON VERSION

```
2.7.15RC1
```

##### BIGIP VERSION

```

```

##### SUMMARY
nTypeError: coercing to Unicode: need string or buffer, NoneType found\n", 

##### STEPS TO REPRODUCE

```
---
- name : Sync F5 Device Group
hosts: F5
connection: local
gather_facts: false
tasks:
- name: save ucs
bigip_ucs_fetch:
            backup: "yes" 
            dest: "admin@myserver:/my/remote/folder" 
            provider:
                server: "{{ inventory_hostname }}" 
                user: "{{ user }}" 
                password: "{{ pass }}" 
            validate_certs: "no" 
    delegate_to: localhost

```

##### ACTUAL RESULTS

fatal: [ldb01b.prod.com -> localhost]: FAILED! => {
"changed": false, 
"module_stderr": "Traceback (most recent call last):\n File \"/root/.ansible/tmp/ansible-tmp-1551094081.35-26740244654413/AnsiballZ_bigip_ucs_fetch.py\", line 113, in <module>\n ansiballz_main()\n File \"/root/.ansible/tmp/ansible-tmp-1551094081.35-26740244654413/AnsiballZ_bigip_ucs_fetch.py\", line 105, in _ansiballz_main\n invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\n File \"/root/.ansible/tmp/ansible-tmp-1551094081.35-26740244654413/AnsiballZ_bigip_ucs_fetch.py\", line 48, in invoke_module\n imp.load_module('_main__', mod, module, MOD_DESC)\n File \"/tmp/ansible_bigip_ucs_fetch_payload_fcQj27/__main__.py\", line 526, in <module>\n File \"/tmp/ansible_bigip_ucs_fetch_payload_fcQj27/__main__.py\", line 517, in main\n File \"/tmp/ansible_bigip_ucs_fetch_payload_fcQj27/__main__.py\", line 256, in exec_module\n File \"/tmp/ansible_bigip_ucs_fetch_payload_fcQj27/__main__.py\", line 292, in exec_module\n File \"/tmp/ansible_bigip_ucs_fetch_payload_fcQj27/__main__.py\", line 306, in present\n File \"/tmp/ansible_bigip_ucs_fetch_payload_fcQj27/__main__.py\", line 364, in create\n File \"/tmp/ansible_bigip_ucs_fetch_payload_fcQj27/__main__.py\", line 322, in execute\n File \"/usr/lib/python2.7/genericpath.py\", line 26, in exists\n os.stat(path)\nTypeError: coercing to Unicode: need string or buffer, NoneType found\n", 
"module_stdout": "", 
"msg": "MODULE FAILURE\nSee stdout/stderr for the exact error", 
"rc": 1
}

```

```
