### ISSUE TITLE
big_gtm_server error using default(omit) jinja filter

### ISSUE THREAD

**Issue by gullanetworkcode** [F5Networks/f5-ansible#1265]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
bigip_gtm_server

##### ANSIBLE VERSION
```
ansible 2.7.7
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/paulh/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.15rc1 (default, Nov 12 2018, 14:31:15) [GCC 7.3.0]
```

##### PYTHON VERSION
```
Python 2.7.15rc1
```

##### BIGIP VERSION
```
Sys::Version
Main Package
  Product     BIG-IP
  Version     12.1.3.7
  Build       0.0.2
  Edition     Point Release 7
  Date        Tue Sep 11 10:03:49 PDT 2018

```

##### OS / ENVIRONMENT
XUBUNTU

##### SUMMARY
Trying to use `default(omit)` jinja filter to deal with undefined variable causing play to fail. In this case I want to omit the `translation` parameter when it isn't required.

Currently using the `default(omit)` filter causes the play to fail as it looks like the module tries to pass `__omit_place_holder__f0cf9f93fd85131a0c545ad8d8340a33ee90edb2` to the BIGIP device rather than `null`

##### STEPS TO REPRODUCE

Playbook
```
---
- name: Create GTM servers
  bigip_gtm_server:
    provider: "{{ f5_provider }}"
    name: "{{ item.key }}"
    devices:
      - name: "{{ item.key }}"
        address: "{{ item.value.address }}"
        translation: "{{ item.value.translation | default(omit) }}"
    datacenter: "{{ item.value.datacenter }}"
    virtual_server_discovery: "{{ item.value.virtual_server_discovery }}"
    iquery_options:
      allow_path: "{{ item.value.iquery_allow_path }}"
      allow_service_check: "{{ item.value.iquery_allow_service_check }}"
      allow_snmp: "{{ item.value.iquery_allow_snmp }}"
    link_discovery: "{{ item.value.link_discovery }}"
  with_dict: "{{ f5_gtm_servers }}"
  delegate_to: localhost
  notify: save_config
```

##### EXPECTED RESULTS
Translation parameter to be omitted if variable is undefined

##### ACTUAL RESULTS
```
The full traceback is:
WARNING: The below traceback may *not* be related to the actual failure.
  File "/tmp/ansible_bigip_gtm_server_payload_Z8IDM2/__main__.py", line 952, in main
    results = mm.exec_module()
  File "/tmp/ansible_bigip_gtm_server_payload_Z8IDM2/__main__.py", line 650, in exec_module
    return manager.exec_module()
  File "/tmp/ansible_bigip_gtm_server_payload_Z8IDM2/__main__.py", line 721, in exec_module
    raise F5ModuleError(str(e))

failed: [crlaplcsgtm001.mgmt.cig.local -> localhost] (item={'value': {u'datacenter': u'CRL', u'link_discovery': u'disabled', u'iquery_allow_snmp': True, u'virtual_server_discovery': u'enabled', u'state': u'enabled', u'iquery_allow_service_check': True, u'address': u'10.0.0.1', u'iquery_allow_path': True}, 'key': u'LTM01'}) => {
    "changed": false, 
    "invocation": {
        "module_args": {
            "auth_provider": null, 
            "datacenter": "CRL", 
            "devices": [
                {
                    "address": "10.0.0.1", 
                    "name": "LTM01", 
                    "translation": "__omit_place_holder__f0cf9f93fd85131a0c545ad8d8340a33ee90edb2"
                }
            ], 
            "iquery_options": {
                "allow_path": true, 
                "allow_service_check": true, 
                "allow_snmp": true
            }, 
            "link_discovery": "disabled", 
            "name": "LTM01", 
            "partition": "Common", 
            "password": null, 
            "provider": {
                "auth_provider": null, 
                "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER", 
                "server": "gtm001.local", 
                "server_port": null, 
                "ssh_keyfile": null, 
                "timeout": null, 
                "transport": "rest", 
                "user": "admin", 
                "validate_certs": false
            }, 
            "server": null, 
            "server_port": null, 
            "server_type": null, 
            "state": "present", 
            "transport": null, 
            "user": null, 
            "validate_certs": null, 
            "virtual_server_discovery": "enabled"
        }
    }, 
    "item": {
        "key": "LTM01", 
        "value": {
            "address": "10.0.0.1", 
            "datacenter": "CRL", 
            "iquery_allow_path": true, 
            "iquery_allow_service_check": true, 
            "iquery_allow_snmp": true, 
            "link_discovery": "disabled", 
            "state": "enabled", 
            "virtual_server_discovery": "enabled"
        }
    }, 
    "msg": "400 Unexpected Error: Bad Request for uri: https://gtm001.local:443/mgmt/tm/gtm/server/\nText: u'{\"code\":400,\"message\":\"Invalid IP address: \\\\\"__omit_place_holder__f0cf9f93fd85131a0c545ad8d8340a33ee90edb2\\\\\"\",\"errorStack\":[],\"apiError\":26214401}'"
```
