### ISSUE TITLE
bigip_gtm_server not idempotent

### ISSUE THREAD

**Issue by gullanetworkcode** [F5Networks/f5-ansible#1266]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
bigip_gtm_server

##### ANSIBLE VERSION
```
ansible 2.7.7
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/paulh/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.15rc1 (default, Nov 12 2018, 14:31:15) [GCC 7.3.0]
```

##### PYTHON VERSION
```
Python 2.7.15rc1
```

##### BIGIP VERSION
```
Sys::Version
Main Package
  Product     BIG-IP
  Version     12.1.3.7
  Build       0.0.2
  Edition     Point Release 7
  Date        Tue Sep 11 10:03:49 PDT 2018

```

##### OS / ENVIRONMENT
XUBUNTU

##### SUMMARY
Trying to define a new GTM server but the bigip_gtm_server module is missing the 'redundant-bigip' server_type.

##### STEPS TO REPRODUCE
```
- server_type
        Specifies the server type. The server type determines the metrics that the system can collect from the server. When creating a new GTM server,
        the default value `bigip' is used.
        (Aliases: product)(Choices: alteon-ace-director, cisco-css, cisco-server-load-balancer, generic-host, radware-wsd, windows-nt-4.0, bigip, cisco-
        local-director-v2, extreme, generic-load-balancer, sun-solaris, cacheflow, cisco-local-director-v3, foundry-server-iron, netapp,
        windows-2000-server)[Default: (null)]
```

##### EXPECTED RESULTS
'redundant-bigip' server_type available

##### ACTUAL RESULTS
Not available

**Comment by wojtek0806** [comment]
as per issue opening guidelines, have you verified this with the latest f5-ansible galaxy role ?

**Comment by gullanetworkcode** [comment]
Yes I have

With the following playbook:-
```
---

- name: Playbook testing against Galaxy role
  hosts: gtm_external
  connection: local
  gather_facts: no

  vars:
    ansible_python_interpreter: /usr/bin/python2.7

  roles:
    - role: '/home/paulh/.ansible/roles/f5devcentral.f5ansible'

  tasks:
    - name: Create GTM servers (LTMs)
      bigip_gtm_server:
        provider: "{{ f5_provider }}"
        name: "{{ item.key }}"
        devices: "{{ item.value.devices }}"
        datacenter: "{{ item.value.datacenter }}"
        virtual_server_discovery: "{{ item.value.virtual_server_discovery }}"
        iquery_options:
          allow_path: "{{ item.value.iquery_allow_path }}"
          allow_service_check: "{{ item.value.iquery_allow_service_check }}"
          allow_snmp: "{{ item.value.iquery_allow_snmp }}"
        link_discovery: "{{ item.value.link_discovery }}"
        server_type: redundant-bigip
      with_dict: "{{ f5_gtm_servers_ltms }}"
      delegate_to: localhost
```

I get the following error:-

```
failed: [gtm001 -> localhost] (item={'value': {u'datacenter': u'CRL', u'link_discovery': u'disabled', u'iquery_allow_snmp': True, u'iquery_allow_service_check': True, u'state': u'enabled', u'devices': [{u'name': u'GBLTM01', u'address': u'nn.nn.nn.nn'}, {u'name': u'GBLTM01 Peer', u'address': u'nn.nn.nn.nn'}], u'virtual_server_discovery': u'enabled', u'iquery_allow_path': True}, 'key': u'GBLTM01'}) => {"changed": false, "item": {"key": "GBLTM01", "value": {"datacenter": "CRL", "devices": [{"address": "nn.nn.nn.nn", "name": "GBLTM01"}, {"address": "nn.nn.nn.nn", "name": "GBLTM01 Peer"}], "iquery_allow_path": true, "iquery_allow_service_check": true, "iquery_allow_snmp": true, "link_discovery": "disabled", "state": "enabled", "virtual_server_discovery": "enabled"}}, "msg": "value of server_type must be one of: alteon-ace-director, cisco-css, cisco-server-load-balancer, generic-host, radware-wsd, windows-nt-4.0, bigip, cisco-local-director-v2, extreme, generic-load-balancer, sun-solaris, cacheflow, cisco-local-director-v3, foundry-server-iron, netapp, windows-2000-server, got: redundant-bigip"}
```

**Comment by caphrim007** [comment]
@gullanetworkcode redundant-bigip is automatically used when you specify more than 1 device and you set the server_type to "bigip"

**Comment by gullanetworkcode** [comment]
Hi, indeed it does (if you add "Peer" to the name for the second device).

It doesn't seem to be idempotent though (makes changes every time it is run). Should I  raise that separately?

**Comment by caphrim007** [comment]
If it's not idempotent, I think it would be reasonable to address it in this issue (because we've clarified the problem) and/or change the name of this issue to align with the current problem (as understood).

Basically, just change this issue to address the current problem, provide a playbook example, and let's call it good

**Comment by gullanetworkcode** [comment]
This is the output from running the task subsequent times.

```
paulh@paulh-code-workstation:~/tfs/NetworkAutomation/Ansible/Prod$ ansible-playbook -i inv_f5_gtm_prod f5_bigip_gtm_server_test_with_galaxy_role.yml --vault-id @prompt --limit gtm001 -vvv
ansible-playbook 2.7.7
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/paulh/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/dist-packages/ansible
  executable location = /usr/bin/ansible-playbook
  python version = 2.7.15rc1 (default, Nov 12 2018, 14:31:15) [GCC 7.3.0]
Using /etc/ansible/ansible.cfg as config file
Vault password (default): 
/home/paulh/tfs/NetworkAutomation/Ansible/Prod/inv_f5_gtm_prod did not meet host_list requirements, check plugin documentation if this is unexpected
/home/paulh/tfs/NetworkAutomation/Ansible/Prod/inv_f5_gtm_prod did not meet script requirements, check plugin documentation if this is unexpected
Parsed /home/paulh/tfs/NetworkAutomation/Ansible/Prod/inv_f5_gtm_prod inventory source with ini plugin

PLAYBOOK: f5_bigip_gtm_server_test_with_galaxy_role.yml ***************************************************************************************************************************************
1 plays in f5_bigip_gtm_server_test_with_galaxy_role.yml

PLAY [Playbook testing against Galaxy role] ***************************************************************************************************************************************************
META: ran handlers

TASK [/home/paulh/.ansible/roles/f5devcentral.f5ansible : Check ansible version] **************************************************************************************************************
task path: /home/paulh/.ansible/roles/f5devcentral.f5ansible/tasks/main.yaml:7
skipping: [gtm001] => {}

TASK [Create GTM servers (LTMs)] **************************************************************************************************************************************************************
task path: /home/paulh/tfs/NetworkAutomation/Ansible/Prod/f5_bigip_gtm_server_test_with_galaxy_role.yml:15
<localhost> ESTABLISH LOCAL CONNECTION FOR USER: paulh
<localhost> EXEC /bin/sh -c 'echo ~paulh && sleep 0'
<localhost> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /home/paulh/.ansible/tmp/ansible-tmp-1553519811.26-112714604827484 `" && echo ansible-tmp-1553519811.26-112714604827484="` echo /home/paulh/.ansible/tmp/ansible-tmp-1553519811.26-112714604827484 `" ) && sleep 0'
Using module file /home/paulh/.ansible/roles/f5devcentral.f5ansible/library/bigip_gtm_server.py
<localhost> PUT /home/paulh/.ansible/tmp/ansible-local-14692W27tr1/tmpJ_wReQ TO /home/paulh/.ansible/tmp/ansible-tmp-1553519811.26-112714604827484/AnsiballZ_bigip_gtm_server.py
<localhost> EXEC /bin/sh -c 'chmod u+x /home/paulh/.ansible/tmp/ansible-tmp-1553519811.26-112714604827484/ /home/paulh/.ansible/tmp/ansible-tmp-1553519811.26-112714604827484/AnsiballZ_bigip_gtm_server.py && sleep 0'
<localhost> EXEC /bin/sh -c '/usr/bin/python2.7 /home/paulh/.ansible/tmp/ansible-tmp-1553519811.26-112714604827484/AnsiballZ_bigip_gtm_server.py && sleep 0'
<localhost> EXEC /bin/sh -c 'rm -f -r /home/paulh/.ansible/tmp/ansible-tmp-1553519811.26-112714604827484/ > /dev/null 2>&1 && sleep 0'
changed: [gtm001 -> localhost] => (item={'value': {u'datacenter': u'CRL', u'link_discovery': u'disabled', u'iquery_allow_snmp': True, u'iquery_allow_service_check': True, u'state': u'enabled', u'devices': [{u'name': u'LTM011-12', u'address': u'10.0.0.20'}, {u'name': u'LTM011-12 Peer', u'address': u'10.0.0.21'}], u'virtual_server_discovery': u'enabled', u'iquery_allow_path': True}, 'key': u'LTM011-12'}) => {
    "changed": true, 
    "devices": [
        {
            "deviceName": "LTM011-12", 
            "name": "10.0.0.20", 
            "translation": "none"
        }, 
        {
            "deviceName": "LTM011-12 Peer", 
            "name": "10.0.0.21", 
            "translation": "none"
        }
    ], 
    "invocation": {
        "module_args": {
            "auth_provider": null, 
            "availability_requirements": null, 
            "datacenter": "CRL", 
            "devices": [
                {
                    "address": "10.0.0.20", 
                    "name": "LTM011-12"
                }, 
                {
                    "address": "10.0.0.21", 
                    "name": "LTM011-12 Peer"
                }
            ], 
            "iquery_options": {
                "allow_path": true, 
                "allow_service_check": true, 
                "allow_snmp": true
            }, 
            "limits": null, 
            "link_discovery": "disabled", 
            "monitors": null, 
            "name": "LTM011-12", 
            "partition": "Common", 
            "password": null, 
            "prober_fallback": null, 
            "prober_pool": null, 
            "prober_preference": null, 
            "provider": {
                "auth_provider": null, 
                "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER", 
                "proxy_to": null, 
                "server": "gtm001", 
                "server_port": null, 
                "ssh_keyfile": null, 
                "timeout": null, 
                "transport": "rest", 
                "user": "admin", 
                "validate_certs": false
            }, 
            "server": null, 
            "server_port": null, 
            "server_type": null, 
            "state": "present", 
            "transport": null, 
            "user": null, 
            "validate_certs": null, 
            "virtual_server_discovery": "enabled"
        }
    }, 
    "item": {
        "key": "LTM011-12", 
        "value": {
            "datacenter": "CRL", 
            "devices": [
                {
                    "address": "10.0.0.20", 
                    "name": "LTM011-12"
                }, 
                {
                    "address": "10.0.0.21", 
                    "name": "LTM011-12 Peer"
                }
            ], 
            "iquery_allow_path": true, 
            "iquery_allow_service_check": true, 
            "iquery_allow_snmp": true, 
            "link_discovery": "disabled", 
            "state": "enabled", 
            "virtual_server_discovery": "enabled"
        }
    }, 
    "monitors": []
}
META: ran handlers
META: ran handlers

PLAY RECAP ************************************************************************************************************************************************************************************
gtm001 : ok=1    changed=1    unreachable=0    failed=0   

paulh@paulh-code-workstation:~/tfs/NetworkAutomation/Ansible/Prod$ 
```

**Comment by wojtek0806** [comment]
provide a full reproduction playbook please

**Comment by wojtek0806** [comment]
@gullanetworkcode any updates?

**Comment by wojtek0806** [comment]
Closing this issue until a reproduction playbook is provided

**Comment by gullanetworkcode** [comment]
This is the playbook that produces the issue:-

```
---

- name: Playbook testing against Galaxy role
  hosts: gtm_external
  connection: local
  gather_facts: no

  vars:
    ansible_python_interpreter: /usr/bin/python2.7

  roles:
    - role: '/home/paulh/.ansible/roles/f5devcentral.f5ansible'

  tasks:
    - name: Create GTM servers (LTMs)
      bigip_gtm_server:
        provider: "{{ f5_provider }}"
        name: LTM011-12
        devices: 
          - name: LTM011-12
            address: 10.0.0.20
          - name: LTM011-12 Peer
            address: 10.0.0.21
        datacenter: CRL
        virtual_server_discovery: enabled
        iquery_options:
          allow_path: yes
          allow_service_check: yes
          allow_snmp: yes
        link_discovery: disabled
      delegate_to: localhost
```

**Comment by wojtek0806** [comment]
@gullanetworkcode I have ran the playbook twice and there is no loss of idempotency you were describing:

First Run:

```
└─▪ ansible-playbook -i ../../devsettings/inventory/hosts_v12 ../../devsettings/repros/delete.yaml -vvvv
ansible-playbook 2.7.8
<omitted>

PLAYBOOK: delete.yaml *******************************************************************************************************************************************************************************************************************************************************************************************************************************************
1 plays in ../../devsettings/repros/delete.yaml

PLAY [Some Test] ************************************************************************************************************************************************************************************************************************************************************************************************************************************************
META: ran handlers

TASK [Create GTM servers (LTMs)] ********************************************************************************************************************************************************************************************************************************************************************************************************************************
<omitted>

changed: [bigip_12_1 -> localhost] => {
    "changed": true,
    "datacenter": "/Common/CRL",
    "devices": [
        {
            "deviceName": "LTM011-12",
            "name": "10.0.0.20",
            "translation": "none"
        },
        {
            "deviceName": "LTM011-12 Peer",
            "name": "10.0.0.21",
            "translation": "none"
        }
    ],
    "enabled": true,
    "invocation": {
        "module_args": {
            "auth_provider": null,
            "availability_requirements": null,
            "datacenter": "CRL",
            "devices": [
                {
                    "address": "10.0.0.20",
                    "name": "LTM011-12"
                },
                {
                    "address": "10.0.0.21",
                    "name": "LTM011-12 Peer"
                }
            ],
            "iquery_options": {
                "allow_path": true,
                "allow_service_check": true,
                "allow_snmp": true
            },
            "limits": null,
            "link_discovery": "disabled",
            "monitors": null,
            "name": "LTM011-12",
            "partition": "Common",
            "password": null,
            "prober_fallback": null,
            "prober_pool": null,
            "prober_preference": null,
            "provider": {
                "auth_provider": null,
                "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
                "proxy_to": null,
                "server": <sanitized>,
                "server_port": 443,
                "ssh_keyfile": null,
                "timeout": null,
                "transport": "rest",
                "user": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
                "validate_certs": false
            },
            "server": null,
            "server_port": null,
            "server_type": null,
            "state": "present",
            "transport": null,
            "user": null,
            "validate_certs": null,
            "virtual_server_discovery": "enabled"
        }
    },
    "iquery_allow_path": "yes",
    "iquery_allow_service_check": "yes",
    "iquery_allow_snmp": "yes",
    "link_discovery": "disabled",
    "monitors": [],
    "server_type": "bigip",
    "virtual_server_discovery": "enabled"
}
META: ran handlers
META: ran handlers

PLAY RECAP ******************************************************************************************************************************************************************************************************************************************************************************************************************************************************
bigip_12_1                 : ok=1    changed=1    unreachable=0    failed=0   
```
Second Run:
```
┌─(f5-ansible)[wypior][CHR-ML-00030481][±][devel → upstream {10} ✓][~/Work/f5-ansible]
└─▪ ansible-playbook -i ../../devsettings/inventory/hosts_v12 ../../devsettings/repros/delete.yaml -

<omitted>

PLAYBOOK: delete.yaml *******************************************************************************************************************************************************************************************************************************************************************************************************************************************
1 plays in ../../devsettings/repros/delete.yaml

PLAY [Some Test] ************************************************************************************************************************************************************************************************************************************************************************************************************************************************
META: ran handlers

TASK [Create GTM servers (LTMs)] ********************************************************************************************************************************************************************************************************************************************************************************************************************************
<omitted>

ok: [bigip_12_1 -> localhost] => {
    "changed": false,
    "invocation": {
        "module_args": {
            "auth_provider": null,
            "availability_requirements": null,
            "datacenter": "CRL",
            "devices": [
                {
                    "address": "10.0.0.20",
                    "name": "LTM011-12"
                },
                {
                    "address": "10.0.0.21",
                    "name": "LTM011-12 Peer"
                }
            ],
            "iquery_options": {
                "allow_path": true,
                "allow_service_check": true,
                "allow_snmp": true
            },
            "limits": null,
            "link_discovery": "disabled",
            "monitors": null,
            "name": "LTM011-12",
            "partition": "Common",
            "password": null,
            "prober_fallback": null,
            "prober_pool": null,
            "prober_preference": null,
            "provider": {
                "auth_provider": null,
                "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
                "proxy_to": null,
                "server": <sanitized>,
                "server_port": 443,
                "ssh_keyfile": null,
                "timeout": null,
                "transport": "rest",
                "user": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
                "validate_certs": false
            },
            "server": null,
            "server_port": null,
            "server_type": null,
            "state": "present",
            "transport": null,
            "user": null,
            "validate_certs": null,
            "virtual_server_discovery": "enabled"
        }
    },
    "monitors": []
}
META: ran handlers
META: ran handlers

PLAY RECAP ******************************************************************************************************************************************************************************************************************************************************************************************************************************************************
bigip_12_1                 : ok=1    changed=0    unreachable=0    failed=0   
```

I am running on TMOS: 12.1.4 and latest development, which should be already in the nightly galaxy role build.

Please update your role to the latest one and retest.

**Comment by wojtek0806** [comment]
closing will reopen if the issue is reproducible

**Comment by gullanetworkcode** [comment]
Hi, I've managed to recreate the issue. It seems that the order in which the IP addresses appear in the list of devices matter, in that they need to be ascending.

For example in the playbook above if the peer address needs to be a lower address then the playbook is then not idempotent:-

```
        devices: 
          - name: LTM011-12
            address: 10.0.0.21
          - name: LTM011-12 Peer
            address: 10.0.0.20
```

So the full playbook would be:-

```
---

- name: Playbook testing against Galaxy role
  hosts: gtm_external
  connection: local
  gather_facts: no

  vars:
    ansible_python_interpreter: /usr/bin/python2.7

  roles:
    - role: '/home/paulh/.ansible/roles/f5devcentral.f5ansible'

  tasks:
    - name: Create GTM servers (LTMs)
      bigip_gtm_server:
        provider: "{{ f5_provider }}"
        name: LTM011-12
        devices: 
          - name: LTM011-12
            address: 10.0.0.21
          - name: LTM011-12 Peer
            address: 10.0.0.20
        datacenter: CRL
        virtual_server_discovery: enabled
        iquery_options:
          allow_path: yes
          allow_service_check: yes
          allow_snmp: yes
        link_discovery: disabled
      delegate_to: localhost
```
