### ISSUE TITLE
Modify all existing vlans using bigip_vlan module

### ISSUE THREAD

**Issue by m-kratochvil** [F5Networks/f5-ansible#1269]
##### ISSUE TYPE
 - Enhancement Request

##### COMPONENT NAME
bigip_vlan

##### ANSIBLE VERSION
```
ansible 2.7.2
  config file = /home/michal/git/worklab/ansible/ansible.cfg
  configured module search path = [u'/home/michal/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, Oct 30 2018, 23:45:53) [GCC 4.8.5 20150623 (Red Hat 4.8.5-36)]
```

##### PYTHON VERSION
```
Python 2.7.5
```

##### BIGIP VERSION
```
Main Package
  Product     BIG-IP
  Version     13.1.1.4
  Build       0.0.4
  Edition     Point Release 4
  Date        Wed Jan 16 18:04:36 PST 2019
```

##### CONFIGURATION
No changes done in ansible.cfg
Galaxy not in use

##### OS / ENVIRONMENT
Ansible controller - VM CentOS Linux release 7.6.1810 (Core)
 
##### SUMMARY
Cannot modify all existing vlans on the Big-IP, using the "all" or "ALL" keyword in the bigip_vlan module. The module documentation suggest that keyword "ALL" can be used to remove all vlans from the Big-IP, this suggest it can be used also to modify all vlans.

##### STEPS TO REPRODUCE
Attempted to modify mtu from default 1500 to new 9000 on all existing vlans, the playbook returns error. Tried with lowercase "all" and uppercase "ALL", with or without parentheses.

Example playbook:
```
---
- name: Configure vlans and their attributes.
  hosts: all
  order: sorted
  gather_facts: false
  connection: local
  tasks:
    - name: Modify MTU of all vlans.
      bigip_vlan:
        provider:
          server: "{{ inventory_hostname }}"
          user: "{{ user }}"
          password: "{{ password }}"
        name: all
        mtu: 9000
        validate_certs: no
```

##### EXPECTED RESULTS
Original output of "tmsh list net vlan all mtu":
```
net vlan vlan-2046 {
    mtu 1500
}
net vlan vlan-2055 {
    mtu 1500
}
```

Expected output:
```
net vlan vlan-2046 {
    mtu 9000
}
net vlan vlan-2055 {
    mtu 9000
}
```

##### ACTUAL RESULTS
Following error was returned after the playbook run:
```
TASK [Modify MTU of all vlans.] *********************************************************************************************************************************************************
fatal: [f511-01]: FAILED! => {"changed": false, "msg": "400 Unexpected Error: Bad Request for uri: https://f511-01:443/mgmt/tm/net/vlan/\nText: u'{\"code\":400,\"message\":\"01070088:3: The requested object name (/Common/all) is invalid.\",\"errorStack\":[],\"apiError\":3}'"}
```
