### ISSUE TITLE
Bigip_virtual_server strips Route for IPv6 virtual server address

### ISSUE THREAD

**Issue by vikas7999** [F5Networks/f5-ansible#1295]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME
bigip_virtual_server

##### ANSIBLE VERSION
```
ansible 2.9.0.dev0
  config file = /root/ansible/ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible

```

##### PYTHON VERSION
```
 python version = 2.7.5 (default, Sep 12 2018, 05:31:16) [GCC 4.8.5 20150623 (Red Hat 4.8.5-36)]
```

##### BIGIP VERSION
BIG-IP 13.1.0.8 Build 0.0.3 Point Release 8

##### CONFIGURATION
```
ansible.cfg 
[defaults]
hostfile = ./hostfile
host_key_checking = false
timeout = 5
deprecation_warnings=False
```
##### OS / ENVIRONMENT
```
Red Hat Linux
```

##### SUMMARY

bigip_virtual_server module strips off Route domain % sign only for IPv6 address when it applies config to the actual LTM.
The playbook accepts the IPv6 address with % sign for route domain and runs off successfully without error. However when we check on the actual lTM devices the route domain is not present.

##### STEPS TO REPRODUCE
```
name: create new VIP on F5 LB
      bigip_virtual_server:
        provider: "{{ provider }}"
        partition: "Common"
        name: "{{ item.Virtual_Server_Name|default([omit, true]) }}"
        destination: "{{ item.ip|default([omit, true]) }}"
        ip_protocol: "{{ item.Protocol|default([omit, true]) }}"
        port: "{{ item.Service_Port|default([omit, true]) }}"
        type: "{{ item.type|default([omit, true]) }}"
        enabled_vlans: "{{ item.enabled_vlans|default([omit, true]) }}"
        pool: "{{ item.pool|default([omit, true]) }}"
        snat: "{{ item.SNAT|default([omit, true]) }}"
        description: "{{ item.VS_description|default([omit, true]) }}"
        state: "{{ item.state|default([omit, true]) }}"
        profiles: "{{ item.profiles|default([omit, true]) }}"
```
```
changed: [F5-LBx-01.com] => (item={u'SNAT': u'none', u'Protocol': u'tcp', u'ip': u'2324:1111:1212:f012:2607:1111:1212:f000%2', u'state': u'present', u'profiles': u'', u'irules': u'', u'enabled_vlans': u'all', u'Virtual_Server_Name': u'IPv6_Forwarding_VS_IPv6_ADDRESS', u'VS_description': u'IPv6_Forwarding_RD_testing', u'Service_Port': u'1000', u'type': u'standard', u'pool': u'RD_POOL'})

```
##### EXPECTED RESULTS
On the actual LTM device %2 sign is missing which needs to be configured manually.
IPv4 route domain works absolutely fine. 

##### ACTUAL RESULTS
Expect Route Domain sign to be configured on the LTM device along with IPv6 address which is not working.

**Comment by wojtek0806** [comment]
FMFA-231

**Comment by wojtek0806** [comment]
looking into this now, for your information when you provide playbooks to us, we require them to have values we could use, rather than variables from your inventory, as now I have to take the output of your play and fill in the blanks, to start reproducing the issue.

**Comment by domgonzales** [comment]
Hi Wojciech,

This play will repro the issue:
```
- name: Create a VIP, pool and pool members
  hosts: non-prod
  connection: local
  vars:
    provider:
      password: admin
      server: 10.155.71.64
      user: admin
      validate_certs: "no"
      server_port: 443

  tasks:
    - name: Create a VS
      bigip_virtual_server:
        provider: "{{ provider }}"
        description: ansible-vs_ipv6 wildcard
        destination: ::/0%1
        name: demo_ipv6_vs_wildcard
        port: any
        ip_protocol: tcp
      tags: create_vs_ipv6_wildcard

    - name: Create a non wildcard VS
      bigip_virtual_server:
        provider: "{{ provider }}"
        description: ansible-vs_ipv6 specific address
        destination: 2700:bc00:1f10:101::6%1
        name: demo_ipv6_vs
        port: "80"
        ip_protocol: tcp
      tags: create_vs_ipv6

```
===================================
LTM Output showing that the RD is applied to the wildcard IPv6 VS, but not to the other:

```
ltm virtual demo_ipv6_vs {
    description "ansible-vs_ipv6 specific address"
    destination 2700:bc00:1f10:101::6.http                     <----RD Notation Missing
    ip-protocol tcp
    metadata {
        f5-ansible.last_modified {
            value "2019-04-30 19:15:05.632466"
        }
        f5-ansible.version {
            value 2.8.0.dev0
        }
    }
    profiles {
        tcp { }
    }
    translate-address disabled
    translate-port disabled
    vs-index 70
}
ltm virtual demo_ipv6_vs_wildcard {
    description "ansible-vs_ipv6 wildcard"
    destination ::%1.any                                <----RD Notation Applied
    ip-protocol tcp
    mask any6
    metadata {
        f5-ansible.last_modified {
            value "2019-04-30 17:19:08.502361"
        }
        f5-ansible.version {
            value 2.8.0.dev0
        }
    }
    profiles {
        tcp { }
    }
    source ::%1/0
    translate-address disabled
    translate-port disabled
    vs-index 71
}
```
This is also being tracked under SR 1-5014045591, you should also have access to that lab unit for testing if you need it.
