### ISSUE TITLE
bigip_firewall_rule - fails to bind existing rule_list defined to existing policy

### ISSUE THREAD

**Issue by neozoolook** [F5Networks/f5-ansible#1314]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

bigip_firewall_rule.py <--Issue Here as best can tell
bigip_firewall_policy.py

##### ANSIBLE VERSION

```
ansible 2.7.8
  config file = /tmp/pycharm_project_513/ansible.cfg
  configured module search path = [u'/tmp/pycharm_project_513/library/modules']
  ansible python module location = /usr/local/lib/python2.7/dist-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 2.7.12 (default, Dec  4 2017, 14:50:18) [GCC 5.4.0 20160609]
```

##### PYTHON VERSION

```
Python 2.7.12
```

##### BIGIP VERSION

```
Sys::Version
Main Package
  Product     BIG-IP
  Version     13.1.0.7
  Build       0.45.1
  Edition     Engineering Hotfix
  Date        Thu Jun  7 09:58:35 PDT 2018

Hotfix List
ID720045-1
```

##### ROLE VERSION

```
Role: f5devcentral.f5ansible
        description: Ansible role that allows use of the F5 Ansible Modules
        active: True
        commit: 6af85de2b0f696e768c6c84a99b22a8489ebc98e
        commit_message: removed mention of SDK
        commit_url: https://api.github.com/repos/f5devcentral/ansible-role-f5ansible/git/commits/6af85de2b0f696e768c6c84a99b22a8489e
        company: F5 Networks
        created: 2018-10-04T16:14:10.510085Z
        download_count: 3922
        forks_count: 1
        github_branch: master
        github_repo: ansible-role-f5ansible
        github_user: f5devcentral
        id: 30341
        imported: 2019-04-26T04:08:32.945387-04:00
        is_valid: True
        issue_tracker_url: 
        license: GPLv3
        min_ansible_version: 2.7
        modified: 2019-04-26T08:08:33.046875Z
        open_issues_count: 0
        path: [u'/tmp/pycharm_project_513/roles']
        role_type: ANS
        stargazers_count: 4
        travis_status_url: https://travis-ci.org/f5devcentral/ansible-role-f5ansible.svg?branch=v2019.4.26
```

##### CONFIGURATION

inventory      =./hosts.inv
library        =./library/modules
module_utils   =./library/module_utils

##### OS / ENVIRONMENT

Ubuntu 16.04TS

##### SUMMARY

We create a new policy using the bigip_firewall_policy.py module, this works fine and creates the policy with a default reject action.  Then we leverage the bigip_firewall_rule.py module to then update the rule in the policy to bind an existing rule-list, despite doing this per documentation the playbook runs with out errors, but never binds the rule-list to the policy as it should.
Effectively breaking the ability to setup rule-lists into policy for AFM.

##### STEPS TO REPRODUCE

```
- name: ///AFM POLICY/// TEST PLAY
  bigip_firewall_policy:
    name: TESTPOLICY
    rules: TESTPOLICY-RULES
    provider:
      password: "{{ password }}"
      server: "{{ ansible_host }}"
      user: "{{ username }}"
      validate_certs: "no"
  delegate_to: localhost

- name: ///AFM RULE/// Bind rule-list to Rule used in Policy
  bigip_firewall_rule:
    name: "TESTPOLICY-RULES"
    description: "Test Rule Binding to Policy"
    parent_policy: "TESTPOLICY"
    rule_list: "CRICKET-RL-IPV4"
    provider:
      password: "{{ password }}"
      server: "{{ ansible_host }}"
      user: "{{ username }}"
      validate_certs: "no"
  delegate_to: localhost
```

##### EXPECTED RESULTS

Expect the policy to be created with rule, then existing rule-list to be bound to the rule name in the said policy that was created in first portion of playbook.
```
security firewall policy TESTPOLICY {
    rules {
        TESTPOLICY-RULES {
            action reject
            description "Test Rule Binding to Policy"
        }
    }
}
```
##### ACTUAL RESULTS

```
pp2854@dark-kyber:/tmp/pycharm_project_513$ ansible-playbook site.yml --ask-vault-pass --tags policy -vvvv
ansible-playbook 2.7.8
  config file = /tmp/pycharm_project_513/ansible.cfg
  configured module search path = [u'/tmp/pycharm_project_513/library/modules']
  ansible python module location = /usr/local/lib/python2.7/dist-packages/ansible
  executable location = /usr/local/bin/ansible-playbook
  python version = 2.7.12 (default, Dec  4 2017, 14:50:18) [GCC 5.4.0 20160609]
Using /tmp/pycharm_project_513/ansible.cfg as config file
Vault password: 
setting up inventory plugins
/tmp/pycharm_project_513/hosts.inv did not meet host_list requirements, check plugin documentation if this is unexpected
/tmp/pycharm_project_513/hosts.inv did not meet script requirements, check plugin documentation if this is unexpected
/tmp/pycharm_project_513/hosts.inv did not meet yaml requirements, check plugin documentation if this is unexpected
Parsed /tmp/pycharm_project_513/hosts.inv inventory source with ini plugin
Loading callback plugin default of type stdout, v2.0 from /usr/local/lib/python2.7/dist-packages/ansible/plugins/callback/default.pyc

PLAYBOOK: site.yml *****************************************************************************************************************
1 plays in site.yml

PLAY [zrdm6bfrwl44] ****************************************************************************************************************
META: ran handlers
Trying secret <ansible.parsing.vault.PromptVaultSecret object at 0x7efd837bd0d0> for vault_id=default

TASK [///ROLE/// F5 AFM] ***********************************************************************************************************
task path: /tmp/pycharm_project_513/site.yml:47
statically imported: /tmp/pycharm_project_513/roles/bigip_afm/tasks/port_list.yml
statically imported: /tmp/pycharm_project_513/roles/bigip_afm/tasks/address_list.yml
statically imported: /tmp/pycharm_project_513/roles/bigip_afm/tasks/rule_list_scp.yml
statically imported: /tmp/pycharm_project_513/roles/bigip_afm/tasks/rule_list_cricket.yml
statically imported: /tmp/pycharm_project_513/roles/bigip_afm/tasks/rule_list_udr.yml
statically imported: /tmp/pycharm_project_513/roles/bigip_afm/tasks/policy.yml

TASK [bigip_afm : ///AFM POLICY/// TEST PLAY] **************************************************************************************
task path: /tmp/pycharm_project_513/roles/bigip_afm/tasks/policy.yml:30
<localhost> connection transport is rest
Using module file /tmp/pycharm_project_513/library/modules/bigip_firewall_policy.py
<localhost> ESTABLISH LOCAL CONNECTION FOR USER: pp2854
<localhost> EXEC /bin/sh -c '/usr/bin/python && sleep 0'
changed: [zrdm6bfrwl44scp001 -> localhost] => {
    "changed": true, 
    "invocation": {
        "module_args": {
            "auth_provider": null, 
            "description": null, 
            "name": "TESTPOLICY", 
            "partition": "Common", 
            "password": null, 
            "provider": {
                "auth_provider": null, 
                "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER", 
                "proxy_to": null, 
                "server": "107.112.169.237", 
                "server_port": null, 
                "ssh_keyfile": null, 
                "timeout": null, 
                "transport": "rest", 
                "user": "admin", 
                "validate_certs": false
            }, 
            "rules": [
                "TESTPOLICY-RULES"
            ], 
            "server": null, 
            "server_port": null, 
            "state": "present", 
            "transport": null, 
            "user": null, 
            "validate_certs": null
        }
    }, 
    "rules": [
        "TESTPOLICY-RULES"
    ]
}

TASK [bigip_afm : ///AFM RULE/// Bind rule-list to Rule used in Policy] ************************************************************
task path: /tmp/pycharm_project_513/roles/bigip_afm/tasks/policy.yml:41
<localhost> connection transport is rest
Using module file /tmp/pycharm_project_513/library/modules/bigip_firewall_rule.py
<localhost> ESTABLISH LOCAL CONNECTION FOR USER: pp2854
<localhost> EXEC /bin/sh -c '/usr/bin/python && sleep 0'
changed: [zrdm6bfrwl44scp001 -> localhost] => {
    "changed": true, 
    "description": "Test Rule Binding to Policy", 
    "invocation": {
        "module_args": {
            "action": null, 
            "auth_provider": null, 
            "description": "Test Rule Binding to Policy", 
            "destination": null, 
            "icmp_message": null, 
            "irule": null, 
            "logging": null, 
            "name": "TESTPOLICY-RULES", 
            "parent_policy": "TESTPOLICY", 
            "parent_rule_list": null, 
            "partition": "Common", 
            "password": null, 
            "protocol": null, 
            "provider": {
                "auth_provider": null, 
                "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER", 
                "proxy_to": null, 
                "server": "107.112.169.237", 
                "server_port": null, 
                "ssh_keyfile": null, 
                "timeout": null, 
                "transport": "rest", 
                "user": "admin", 
                "validate_certs": false
            }, 
            "rule_list": "CRICKET-RL-IPV4", 
            "schedule": null, 
            "server": null, 
            "server_port": null, 
            "source": null, 
            "state": "present", 
            "status": null, 
            "transport": null, 
            "user": null, 
            "validate_certs": null
        }
    }
}
META: ran handlers
META: ran handlers

PLAY RECAP *************************************************************************************************************************
zrdm6bfrwl44scp001         : ok=2    changed=2    unreachable=0    failed=0  
```

**Comment by wojtek0806** [comment]
Internal Tracking: FMFA-255

**Comment by wojtek0806** [comment]
This issue is not reproducible, i used the below playbook:
```
---

- name: AFM_RULE_BINDING_TEST
  hosts: f5-test[0]
  connection: local
  gather_facts: no

  roles:
    - role: f5devcentral.f5ansible

  vars:
    f5_provider:
      password: "admin"
      server: "{{ ansible_host }}"
      user: "admin"
      validate_certs: "no"
      server_port: "443"


  tasks:
    - name: Create Policy with Rules
      bigip_firewall_policy:
        name: TESTPOLICY
        rules: TESTPOLICY-RULES
        provider: "{{ f5_provider }}"

    - name: Create a basic rule list
      bigip_firewall_rule_list:
        name: CRICKET-RL-IPV4
        provider: "{{ f5_provider }}"

    - name: Bind rule-list to Rule used in Policy
      bigip_firewall_rule:
        name: "TESTPOLICY-RULES"
        description: "Test Rule Binding to Policy"
        parent_policy: "TESTPOLICY"
        rule_list: "CRICKET-RL-IPV4"
        provider: "{{ f5_provider }}"

```

Results:
```
root@(v13-1)(cfg-sync Standalone)(Active)(/Common)(tmos)# show sys version

Sys::Version
Main Package
  Product     BIG-IP
  Version     13.1.1.4
  Build       0.0.4
  Edition     Point Release 4
  Date        Wed Jan 16 18:04:36 PST 2019
```
```
root@(v13-1)(cfg-sync Standalone)(Active)(/Common)(tmos)# list security firewall policy
security firewall policy TESTPOLICY {
    rules {
        TESTPOLICY-RULES {
            action reject
            description "Test Rule Binding to Policy"
            rule-number 1
        }
    }
}
```
Since the issue cannot be reproduced with the role, (which is a wrapper around devel code), I will close this, once you can provide me with reproduction we will reopen

**Comment by neozoolook** [comment]
@wojtek0806 Your test above shows that this doesn't work... In your 'list security firewall policy' output you should see the rule-list "CRICKET-RL-IPV4" inside the rules/TESTPOLICY-RULES output, you effectively haven't added that rule-list at all to the policy, you have an action reject and rule-number 1 which doesn't event five with what you did above in the playbooks.

It should look like this in output;

```
root@(v13-1)(cfg-sync Standalone)(Active)(/Common)(tmos)# list security firewall policy
security firewall policy TESTPOLICY {
    rules {
        TESTPOLICY-RULES {
            rule-list CRICKET-RL-IPV4
            description "Test Rule Binding to Policy"
        }
    }
}
```

Secondly after add the rule-list to the policy, you should not flag it to 'reject' this doesn't make any sense either.  This needs to be reopened this is 100% reproducible.

**Comment by neozoolook** [comment]
Playbooks to reproduce;

```
---
- name: ///AFM RULE LIST/// Create {{ rule_list_cricket.name }}
  bigip_firewall_rule_list:
    name: "{{ rule_list_cricket.name }}"
    description: "{{ rule_list_cricket.description }}"
    rules:
      - "{{ rule_list_cricket.rule1_name }}"
      - "{{ rule_list_cricket.rule2_name }}"
      - "{{ rule_list_cricket.rule3_name }}"
    provider:
      server: "{{ ansible_host }}"
      user: "{{ username }}"
      password: "{{ password }}"
      validate_certs: "no"
  delegate_to: localhost

- name: ///AFM RULE/// Create {{ rule_list_cricket.rule1_name }}
  bigip_firewall_rule:
    name: "{{ rule_list_cricket.rule1_name }}"
    description: "{{ rule_list_cricket.rule1_desc }}"
    parent_rule_list: "{{ rule_list_cricket.name }}"
    protocol: "{{ rule_list_cricket.rule1_proto }}"
    source:
      - address_list: "{{ rule_list_cricket.rule1_src_addr }}"
    destination:
      - address_list: "{{ rule_list_cricket.rule1_dst_addr }}"
      - port_list: "{{ rule_list_cricket.rule1_dst_port }}"
    action: "{{ rule_list_cricket.rule1_act }}"
    logging: yes
    provider:
      server: "{{ ansible_host }}"
      user: "{{ username }}"
      password: "{{ password }}"
      validate_certs: "no"
  delegate_to: localhost

- name: ///AFM RULE/// Create {{ rule_list_cricket.rule2_name }}
  bigip_firewall_rule:
    name: "{{ rule_list_cricket.rule2_name }}"
    description: "{{ rule_list_cricket.rule2_desc }}"
    parent_rule_list: "{{ rule_list_cricket.name }}"
    protocol: "{{ rule_list_cricket.rule2_proto }}"
    icmp_message:
      - type: 0
      - type: 8
      - type: 30
    action: "{{ rule_list_cricket.rule2_act }}"
    logging: yes
    provider:
      server: "{{ ansible_host }}"
      user: "{{ username }}"
      password: "{{ password }}"
      validate_certs: "no"
  delegate_to: localhost

- name: ///AFM RULE/// Update {{ rule_list_cricket.rule2_name }}
  bigip_firewall_rule:
    name: "{{ rule_list_cricket.rule2_name }}"
    description: "{{ rule_list_cricket.rule2_desc }}"
    parent_rule_list: "{{ rule_list_cricket.name }}"
    protocol: "{{ rule_list_cricket.rule2_proto }}"
    source:
      - address_list: "{{ rule_list_cricket.rule2_src_addr }}"
    destination:
      - address_list: "{{ rule_list_cricket.rule2_dst_addr }}"
    action: "{{ rule_list_cricket.rule2_act }}"
    logging: yes
    provider:
      server: "{{ ansible_host }}"
      user: "{{ username }}"
      password: "{{ password }}"
      validate_certs: "no"
  delegate_to: localhost

- name: ///AFM RULE/// Create {{ rule_list_cricket.rule3_name }}
  bigip_firewall_rule:
    name: "{{ rule_list_cricket.rule3_name }}"
    description: "{{ rule_list_cricket.rule3_desc }}"
    parent_rule_list: "{{ rule_list_cricket.name }}"
    action: "{{ rule_list_cricket.rule3_act }}"
    logging: yes
    provider:
      server: "{{ ansible_host }}"
      user: "{{ username }}"
      password: "{{ password }}"
      validate_certs: "no"
  delegate_to: localhost

- name: ///AFM POLICY/// TEST PLAY
  bigip_firewall_policy:
    name: TESTPOLICY
    rules: TESTPOLICY-RULES
    provider:
      password: "{{ password }}"
      server: "{{ ansible_host }}"
      user: "{{ username }}"
      validate_certs: "no"
  delegate_to: localhost

- name: ///AFM RULE/// Bind rule-list to Rule used in Policy
  bigip_firewall_rule:
    name: "TESTPOLICY-RULES"
    description: "Test Rule Binding to Policy"
    parent_policy: "TESTPOLICY"
    rule_list: "CRICKET-RL-IPV4"
    provider:
      password: "{{ password }}"
      server: "{{ ansible_host }}"
      user: "{{ username }}"
      validate_certs: "no"
  delegate_to: localhost
```

VARS
```
rule_list_cricket:
    name: CRICKET-RL-IPV4
    description: 'Rule List for Cricket IPv4 Flows'
    rule1_name: ALLOW-CRICKET-TCP
    rule1_desc: 'Allow Cricket IT DRA to Originate TCP'
    rule1_act: accept
    rule1_proto: tcp
    rule1_dst_addr: 'ZRDM6BFRWL44-VSCP-BE'
    rule1_dst_port: DIAMETER-TCP
    rule1_src_addr: 'VSCP-CRICKET-IT-DRA'
    rule2_name: ALLOW-CRICKET-ICMP
    rule2_desc: 'Allow Cricket IT DRA to Originate ICMP PING/TRACEROUTE'
    rule2_act: accept
    rule2_proto: icmp
    rule2_dst_addr: 'ZRDM6BFRWL44-VSCP-BE'
    rule2_src_addr: 'VSCP-CRICKET-IT-DRA'
    rule3_name: DEFAULT-DROP
    rule3_desc: 'Drop Policy with Logging'
    rule3_act: drop
```

**Comment by wojtek0806** [comment]
Just to see how it looks like from GUI end, tried something in the GUI, the first policy dos not have any rules the second one has:

```

security firewall policy TEST_POLICY {
    rules {
        _Common_TEST_RULE {
            description "This is a test"
            rule-list TEST_RULE
            rule-number 1
        }
        _Common_TEST_RULE2 {
            rule-list TEST_RULE2
            rule-number 2
        }
    }
}

```
Reopening

@neozoolook for the second comment about the use or 'reject', the correctness of AFM configuration is irrelevant to this issue.

**Comment by wojtek0806** [comment]
@neozoolook 

I think I found the issue:

````
parent_policy:
  description: The policy which contains the rule to be managed.
  returned: changed
  type: str
  sample: FooPolicy
parent_rule_list:
  description: The rule list which contains the rule to be managed.
  returned: changed
  type: str
  sample: FooRuleList
````
The module logic assumes when you specify a parent policy you are adding a single rule, rather than a rule list. The rule list and parent policy parameters here is basically allow adding rules to each separate object: rule-list and policy.
```
        self.mutually_exclusive = [
            ['rule_list', 'action'],
            ['rule_list', 'source'],
            ['rule_list', 'destination'],
            ['rule_list', 'irule'],
            ['rule_list', 'protocol'],
            ['rule_list', 'logging'],
            ['parent_policy', 'parent_rule_list']
        ]
        self.required_one_of = [
            ['parent_policy', 'parent_rule_list']
        ]
```
So the issue looks like here it is adding a a single rule from rule list.  Since we already have adding rules to parent policy here, i will see if it is possible to do this for rule-lists to be assigned to the policy without breaking other things in the module. Thom I think it would make sense to have it in bigip_firewall_rule_list implemented in similar fashion to bigip_firewall_rule. 
I will let you know once I have solution
