### ISSUE TITLE
bigip_ucs_fetch failure to connect

### ISSUE THREAD

**Issue by tyoung4** [F5Networks/f5-ansible#1318]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

bigip_ucs_fetch

##### ANSIBLE VERSION
```
ansible 2.7.10
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /bin/ansible
  python version = 2.7.5 (default, Aug  2 2016, 04:20:16) [GCC 4.8.5 20150623 (Red Hat 4.8.5-4)]
```

##### PYTHON VERSION

```
Python 2.7.5
```

##### BIGIP VERSION

```
Sys::Version
Main Package
  Product     BIG-IP
  Version     12.1.3
  Build       0.0.378
  Edition     Final
  Date        Mon Nov 27 16:41:03 PST 2017
```

##### ROLE VERSION
```
Role: f5devcentral.f5ansible
        description: Ansible role that allows use of the F5 Ansible Modules
        active: True
        commit: 2ff95abd1db769784fbb3b94119a73e57913c875
        commit_message: Merging upstream changes - 2019-05-03T07:01:06Z
        commit_url: https://api.github.com/repos/f5devcentral/ansible-role-f5ansible/git/commits/2ff95abd1db769784fbb3b94119a73e57913c875
        company: F5 Networks
        created: 2018-10-04T16:14:10.510085Z
        dependencies: []
        download_count: 4142
        forks_count: 1
        galaxy_info:
                author: caphrim007
                company: F5 Networks
                galaxy_tags: ['f5', 'networking', 'bigip', 'bigiq']
                license: GPLv3
                min_ansible_version: 2.7
                platforms: [{'name': 'EL', 'versions': ['all']}, {'name': 'Fedora', 'versions': ['all']}, {'name': 'Ubuntu', 'versions': ['all']}, {'name': 'Debian', 'versions': ['all']}]
                role_name: f5ansible
        github_branch: master
        github_repo: ansible-role-f5ansible
        github_user: f5devcentral
        id: 30341
        imported: 2019-05-03T03:03:58.145708-04:00
        install_date: Mon May  6 14:04:11 2019
        installed_version: v2019.4.26
        is_valid: True
        issue_tracker_url: 
        license: GPLv3
        min_ansible_version: 2.7
        modified: 2019-05-03T07:03:58.228596Z
        open_issues_count: 0
        path: [u'/root/.ansible/roles', u'/usr/share/ansible/roles', u'/etc/ansible/roles']
        role_type: ANS
        stargazers_count: 4
        travis_status_url: https://travis-ci.org/f5devcentral/ansible-role-f5ansible.svg?branch=master
```

##### CONFIGURATION

host_key_checking = false
transport      = ssh

##### OS / ENVIRONMENT

Redhat RHEL 7

##### SUMMARY

I am unable to get the UCS fetch module to connect to a remote host. The same credentials have worked for other F5 Modules. I believe the issue is related to the error message below:

"msg": "Unable to connect to REDACTED on port 443. The reported error was \"Unexpected **kwargs: {'verify': False}\"."

##### STEPS TO REPRODUCE

```
- name: F5 Backup
  hosts: REDACTED
  gather_facts: false
  connection: network_cli

  tasks:

  - name: Fetch UCS
    bigip_ucs_fetch:
      backup: yes
      src: "{{ inventory_hostname }}.ucs"
      dest: /opt/ansible/test.ucs
      provider:
        server: "{{ inventory_hostname }}"
        user: REDACTED
        password: REDACTED
        validate_certs: no
    delegate_to: localhost
```
##### EXPECTED RESULTS

UCS file to backup to local host.

##### ACTUAL RESULTS
```
ansible-playbook 2.7.10
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /bin/ansible-playbook
  python version = 2.7.5 (default, Aug  2 2016, 04:20:16) [GCC 4.8.5 20150623 (Red Hat 4.8.5-4)]
Using /etc/ansible/ansible.cfg as config file
setting up inventory plugins
/opt/ansible/inventory.ini did not meet host_list requirements, check plugin documentation if this is unexpected
/opt/ansible/inventory.ini did not meet yaml requirements, check plugin documentation if this is unexpected
Parsed /opt/ansible/inventory.ini inventory source with ini plugin
Loading callback plugin default of type stdout, v2.0 from /usr/lib/python2.7/site-packages/ansible/plugins/callback/default.pyc

PLAYBOOK: ucs_fetch_test.yaml **********************************************************************************************************************************************************************************************
1 plays in ucs_fetch_test.yaml

PLAY [F5 Backup] ***********************************************************************************************************************************************************************************************************
META: ran handlers

TASK [Fetch UCS] ***********************************************************************************************************************************************************************************************************
task path: /opt/ansible/ucs_fetch_test.yaml:8
<localhost> connection transport is rest
<localhost> ESTABLISH LOCAL CONNECTION FOR USER: root
<localhost> EXEC /bin/sh -c 'echo ~root && sleep 0'
<localhost> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /root/.ansible/tmp/ansible-tmp-1557158612.72-103029170816311 `" && echo ansible-tmp-1557158612.72-103029170816311="` echo /root/.ansible/tmp/ansible-tmp-1557158612.72-103029170816311 `" ) && sleep 0'
Using module file /usr/lib/python2.7/site-packages/ansible/modules/network/f5/bigip_ucs_fetch.py
<localhost> PUT /root/.ansible/tmp/ansible-local-10438SAxyLL/tmpYVMTRS TO /root/.ansible/tmp/ansible-tmp-1557158612.72-103029170816311/AnsiballZ_bigip_ucs_fetch.py
<localhost> EXEC /bin/sh -c 'chmod u+x /root/.ansible/tmp/ansible-tmp-1557158612.72-103029170816311/ /root/.ansible/tmp/ansible-tmp-1557158612.72-103029170816311/AnsiballZ_bigip_ucs_fetch.py && sleep 0'
<localhost> EXEC /bin/sh -c '/usr/bin/python2 /root/.ansible/tmp/ansible-tmp-1557158612.72-103029170816311/AnsiballZ_bigip_ucs_fetch.py && sleep 0'
<localhost> EXEC /bin/sh -c 'rm -f -r /root/.ansible/tmp/ansible-tmp-1557158612.72-103029170816311/ > /dev/null 2>&1 && sleep 0'
The full traceback is:
WARNING: The below traceback may *not* be related to the actual failure.
  File "/tmp/ansible_bigip_ucs_fetch_payload_q5GSiZ/__main__.py", line 517, in main
    results = mm.exec_module()
  File "/tmp/ansible_bigip_ucs_fetch_payload_q5GSiZ/__main__.py", line 252, in exec_module
    if self.is_version_v1():
  File "/tmp/ansible_bigip_ucs_fetch_payload_q5GSiZ/__main__.py", line 274, in is_version_v1
    version = self.client.api.tmos_version
  File "/tmp/ansible_bigip_ucs_fetch_payload_q5GSiZ/ansible_bigip_ucs_fetch_payload.zip/ansible/module_utils/network/f5/bigip.py", line 61, in api
    raise F5ModuleError(error)

fatal: [REDACTED -> localhost]: FAILED! => {
    "changed": false, 
    "invocation": {
        "module_args": {
            "attributes": null, 
            "auth_provider": null, 
            "backup": true, 
            "content": null, 
            "create_on_missing": true, 
            "delimiter": null, 
            "dest": "/opt/ansible/test.ucs", 
            "directory_mode": null, 
            "encryption_password": null, 
            "fail_on_missing": false, 
            "follow": false, 
            "force": true, 
            "group": null, 
            "mode": null, 
            "owner": null, 
            "password": null, 
            "provider": {
                "auth_provider": null, 
                "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER", 
                "server": "REDACTED", 
                "server_port": null, 
                "ssh_keyfile": null, 
                "timeout": null, 
                "transport": "rest", 
                "user": "REDACTED", 
                "validate_certs": false
            }, 
            "regexp": null, 
            "remote_src": null, 
            "selevel": null, 
            "serole": null, 
            "server": null, 
            "server_port": null, 
            "setype": null, 
            "seuser": null, 
            "src": "REDACTED.ucs", 
            "transport": null, 
            "unsafe_writes": null, 
            "user": null, 
            "validate_certs": null
        }
    }, 
    "msg": "Unable to connect to REDACTED on port 443. The reported error was \"Unexpected **kwargs: {'verify': False}\"."
}
        to retry, use: --limit @/opt/ansible/ucs_fetch_test.retry

PLAY RECAP *****************************************************************************************************************************************************************************************************************
REDACTED      : ok=0    changed=0    unreachable=0    failed=1  
```
