### ISSUE TITLE
bigip_configsync_actions

### ISSUE THREAD

**Issue by payalsin** [F5Networks/f5-ansible#132]
Setup an HA manually and was at the point at 'Awating initial config sync'

Ran the playbook, the sync happened but the playbook threw an error:

[root@mg-server1 ps_ansible]# ansible-playbook playbooks/bigip-configsync-actions.yaml

TASK [Perform a config sync] ****************************************************************************************************************************************************************************************************************
fatal: [10.192.73.218 -> localhost]: FAILED! => {"changed": false, "failed": true, "msg": "Awaiting Initial Sync"}
        to retry, use: --limit @/root/ps_ansible/playbooks/bigip-configsync-actions.retry

PLAY RECAP **********************************************************************************************************************************************************************************************************************************
10.192.73.218              : ok=0    changed=0    unreachable=0    failed=1

PLAYBOOK

```
- name: Perform a config sync
    bigip_configsync_actions:
      server: "10.192.73.218"
      user: "admin"
      password: "admin"
      device_group: "deviceGrp"
      sync_device_to_group: yes
    delegate_to: localhost
```
