### ISSUE TITLE
bigip_device_facts module returns that the task has changed the target system

### ISSUE THREAD

**Issue by jesmith18** [F5Networks/f5-ansible#1321]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME
```
bigip_device_facts.py
```
##### ANSIBLE VERSION
```
ansible 2.7.6
  config file = None
  configured module search path = ['/Users/jsmith18/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.7/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 3.7.2 (default, Feb 12 2019, 08:16:11) [Clang 9.0.0 (clang-900.0.39.2)]
```
##### PYTHON VERSION
```
Python 3.7.2
```
##### BIGIP VERSION
```
Sys::Version
Main Package
  Product     BIG-IP
  Version     13.1.0.7
  Build       0.0.1
  Edition     Point Release 7
  Date        Tue May 15 15:26:30 PDT 2018
```
##### ROLE VERSION
```
Role: f5devcentral.f5ansible
        description: Ansible role that allows use of the F5 Ansible Modules
        active: True
        commit: 2ff95abd1db769784fbb3b94119a73e57913c875
        commit_message: Merging upstream changes - 2019-05-03T07:01:06Z
        commit_url: https://api.github.com/repos/f5devcentral/ansible-role-f5ansible/git/commits/2ff95abd1db769784fbb3b94119a73e57913c875
        company: F5 Networks
        created: 2018-10-04T16:14:10.510085Z
        download_count: 4218
        forks_count: 1
        github_branch: master
        github_repo: ansible-role-f5ansible
        github_user: f5devcentral
        id: 30341
        imported: 2019-05-03T03:03:58.145708-04:00
        is_valid: True
        issue_tracker_url: 
        license: GPLv3
        min_ansible_version: 2.7
        modified: 2019-05-03T07:03:58.228596Z
        open_issues_count: 0
        path: ['/Users/jsmith18/.ansible/roles', '/usr/share/ansible/roles', '/etc/ansible/roles']
        role_type: ANS
        stargazers_count: 4
        travis_status_url: https://travis-ci.org/f5devcentral/ansible-role-f5ansible.svg?branch=master
```

##### CONFIGURATION
N/A

##### OS / ENVIRONMENT
N/A

##### SUMMARY
The bigip_device_facts module reports to ansible that it has changed the target system when It has not. This gives a false impression and causes confusion.

##### STEPS TO REPRODUCE

```
    - name: Get Device Facts
      bigip_device_facts:
        provider: "{{ creds }}"
        gather_subset:
          - devices
      delegate_to: localhost
      register: output
```

##### EXPECTED RESULTS

TASK [Get Device Facts] ***************************************************************************************************************************************************************************************************************
ok: [lvs1-entlb-101.ilo.paypalcorp.com -> localhost]
##### ACTUAL RESULTS

```
TASK [Get Device Facts] ***************************************************************************************************************************************************************************************************************
changed: [lvs1-entlb-101.ilo.paypalcorp.com -> localhost]
```
