### ISSUE TITLE
importError: cannot import name cleanup_tokens when using bigip_virtual_server

### ISSUE THREAD

**Issue by xbill42** [F5Networks/f5-ansible#1330]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
bigip_virtual_server

##### ANSIBLE VERSION
```
2.7.8
```

##### PYTHON VERSION
```
Python 2.7.5
```

##### BIGIP VERSION
```
14.1.0.3 
```

##### ROLE VERSION
```
Role: f5devcentral.f5ansible
        description: Ansible role that allows use of the F5 Ansible Modules
        active: True
        commit: 6ca988bd260e5620089d8f28490d094d337cd2d9
        commit_message: Merging upstream changes - 2019-05-10T15:01:45Z
        commit_url: https://api.github.com/repos/f5devcentral/ansible-role-f5ansible/git/commits/6ca988bd260e5620089d8f28490d094d337cd2d9
        company: F5 Networks
        created: 2018-10-04T16:14:10.510085Z
        dependencies: []
        download_count: 4613
        forks_count: 1
        galaxy_info:
                author: caphrim007
                company: F5 Networks
                galaxy_tags: ['f5', 'networking', 'bigip', 'bigiq']
                license: GPLv3
                min_ansible_version: 2.7
                platforms: [{'name': 'EL', 'versions': ['all']}, {'name': 'Fedora', 'versions': ['all']}, {'name': 'Ubuntu', 'versions': ['all']}, {'name': 'Debian', 'versions': ['all']}]
                role_name: f5ansible
        github_branch: master
        github_repo: ansible-role-f5ansible
        github_user: f5devcentral
        id: 30341
        imported: 2019-05-10T11:04:32.738510-04:00
        install_date: Sun May 12 20:51:52 2019
        installed_version: v2019.5.10
        is_valid: True
        issue_tracker_url: 
        license: GPLv3
        min_ansible_version: 2.7
        modified: 2019-05-10T15:04:32.856510Z
        open_issues_count: 0
        path: [u'/etc/ansible/roles', u'/usr/share/ansible/roles']
        role_type: ANS
        stargazers_count: 4
        travis_status_url: https://travis-ci.org/f5devcentral/ansible-role-f5ansible.svg?branch=master
```

##### OS / ENVIRONMENT
centos

##### SUMMARY
Trying to deploy a forwarding VS with module  bigip_virtual_server:

Receive this python error :

ImportError: cannot import name cleanup_tokens

##### STEPS TO REPRODUCE

Deploy this task 

- name: Create redirhttps forwarding VS
      bigip_virtual_server:
        destination: 0.0.0.0
        name: redirhttps
        port: 443
        type: forwarding-ip
        state: "{{ extra_state }}"
        snat: automap
        enabled_vlans:
          - /Common/internal
        provider:
          user: "{{ extra_admin_user }}"
          password: "{{ extra_admin_password }}"
          server: "{{ extra_ip_mgt }}"
          server_port: "{{ extra_port_mgt }}"
          validate_certs: no
      delegate_to: localhost

##### EXPECTED RESULTS
Deployed a forwarding VS

##### ACTUAL RESULTS

```
Error :

Traceback (most recent call last):\n  File \"/var/lib/awx/.ansible/tmp/ansible-tmp-1557913427.23-19076383761457/AnsiballZ_bigip_virtual_server.py\", line 113, in <module>\n    _ansiballz_main()\n  File \"/var/lib/awx/.ansible/tmp/ansible-tmp-1557913427.23-19076383761457/AnsiballZ_bigip_virtual_server.py\", line 105, in _ansiballz_main\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\n  File \"/var/lib/awx/.ansible/tmp/ansible-tmp-1557913427.23-19076383761457/AnsiballZ_bigip_virtual_server.py\", line 48, in invoke_module\n    imp.load_module('__main__', mod, module, MOD_DESC)\n  File \"/tmp/ansible_bigip_virtual_server_payload_tNQacY/__main__.py\", line 662, in <module>\nImportError: cannot import name cleanup_tokens\
```
