### ISSUE TITLE
module to change remote_user settings

### ISSUE THREAD

**Issue by wojtek0806** [F5Networks/f5-ansible#1335]
##### ISSUE TYPE

 - Feature Idea

##### SUMMARY

New module needed to change the remote-user settings on bigip. Currently this is achieved by command line with bigip_command module.
##### STEPS TO REPRODUCE

```
   - name: Remote User update
      bigip_command:
        provider: "{{ provider }}"
        commands:
          - modify auth remote-user default-role admin remote-console-access tmsh
      delegate_to: localhost
```
