### ISSUE TITLE
bigip_ucs_fetch error

### ISSUE THREAD

**Issue by UnknownGnome** [F5Networks/f5-ansible#1352]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

bigip_ucs_fetch
##### ANSIBLE VERSION

```
ansible 2.7.9
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, Oct 30 2018, 23:45:53) [GCC 4.8.5 20150623 (Red Hat 4.8.5-36)]
```

##### PYTHON VERSION

```
Python 2.7.5
```

##### BIGIP VERSION

```
Sys::Version
Main Package
  Product     BIG-IP
  Version     12.1.3.5
  Build       0.0.10
  Edition     Point Release 5
  Date        Mon May 21 17:36:20 PDT 2018
```

##### ROLE VERSION

```
Role: f5devcentral.f5ansible
        description: Ansible role that allows use of the F5 Ansible Modules
        active: True
        commit: 8c91ff120a05c31d212dff83f6f189cd4165de80
        commit_message: Merging upstream changes - 2019-05-25T07:00:51Z
        commit_url: https://api.github.com/repos/f5devcentral/ansible-role-f5ansible/git/commits/8c91ff120a05c31d212dff83f6f189cd4165de80
        company: F5 Networks
        created: 2018-10-04T16:14:10.510085Z
        download_count: 5342
        forks_count: 0
        github_branch: master
        github_repo: ansible-role-f5ansible
        github_user: f5devcentral
        id: 30341
        imported: 2019-05-25T03:03:51.598306-04:00
        is_valid: True
        issue_tracker_url:
        license: GPLv3
        min_ansible_version: 2.8
        modified: 2019-05-25T07:03:51.745968Z
        open_issues_count: 0
        path: [u'/root/.ansible/roles', u'/usr/share/ansible/roles', u'/etc/ansible/roles']
        role_type: ANS
        stargazers_count: 4
        travis_status_url: https://travis-ci.org/f5devcentral/ansible-role-f5ansible.svg?branch=master

```

##### SUMMARY

I'm getting an error on just a couple of F5 appliances when I'm running the bigip_ucs_fetch module. This works fine on four other appliances, but fails on two with the attached error.
The UCS file is created on the appliance, but never shows up in the share and eventually I get the error. 
##### STEPS TO REPRODUCE

```
---
- name: Run UCS Archive on F5 BIG-IPs
  hosts: all
  connection: local
  gather_facts: False

  vars:
    f5Provider:
      server: "{{ mgmtAddr }}"
      server_port: 443
      user: "{{ f5_username }}"
      password: "{{ f5_password }}"
      validate_certs: no
      transport: rest

  tasks:

    - name: Set archive name postfix date/time
      local_action: command date +%Y%m%d-%H%M%Z
      changed_when: false
      register: date
      delegate_to: localhost
      
    - name: Set filename
      set_fact: 
        filename: "{{ inventory_hostname }}-{{ date['stdout'] }}.ucs"

    - name: Fetch UCS archive
      bigip_ucs_fetch:
        src: "{{ filename }}"
        dest: "/tmp/{{ filename }}"
        provider: "{{f5Provider}}"
      delegate_to: localhost

    - name: Wipe UCS archive
      bigip_ucs: 
        ucs: "{{ filename }}"
        state: absent
        provider: "{{f5Provider}}"
      delegate_to: localhost
```

##### EXPECTED RESULTS

UCS archive created on F5 device then moved to specified dest location.
##### ACTUAL RESULTS

```
The UCS archive is created on the F5 device. Eventually Ansible gives the following error:
{
    "_ansible_parsed": true,
    "exception": "WARNING: The below traceback may *not* be related to the actual failure.\n  File \"/tmp/ansible_bigip_ucs_fetch_payload_7u1qL0/__main__.py\", line 517, in main\n    results = mm.exec_module()\n  File \"/tmp/ansible_bigip_ucs_fetch_payload_7u1qL0/__main__.py\", line 256, in exec_module\n    return manager.exec_module()\n  File \"/tmp/ansible_bigip_ucs_fetch_payload_7u1qL0/__main__.py\", line 294, in exec_module\n    raise F5ModuleError(str(e))\n",
    "_ansible_no_log": false,
    "_ansible_delegated_vars": {
        "ansible_delegated_host": "localhost",
        "ansible_host": "localhost"
    },
    "changed": false,
    "invocation": {
        "module_args": {
            "directory_mode": null,
            "force": true,
            "remote_src": null,
            "dest": "/tmp/hostname.domain-20190528-1501UTC.ucs",
            "selevel": null,
            "auth_provider": null,
            "create_on_missing": true,
            "user": null,
            "fail_on_missing": false,
            "regexp": null,
            "owner": null,
            "follow": false,
            "password": null,
            "transport": null,
            "src": "hostname.domain-20190528-1501UTC.ucs",
            "group": null,
            "encryption_password": null,
            "unsafe_writes": null,
            "delimiter": null,
            "seuser": null,
            "setype": null,
            "server": null,
            "content": null,
            "validate_certs": null,
            "serole": null,
            "mode": null,
            "server_port": null,
            "provider": {
                "ssh_keyfile": null,
                "server_port": 443,
                "auth_provider": null,
                "server": "10.10.10.10",
                "user": "admin",
                "timeout": null,
                "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
                "validate_certs": false,
                "transport": "rest"
            },
            "attributes": null,
            "backup": false
        }
    },
    "msg": "502 Unexpected Error: Bad Gateway for uri: https://10.10.10.10:443/mgmt/tm/sys/ucs/\nText: u'<?xml version=\"1.0\" encoding=\"ISO-8859-1\"?>\\n<!DOCTYPE html PUBLIC \"-//W3C//DTD XHTML 1.0 Strict//EN\"\\n  \"http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd\">\\n<html xmlns=\"http://www.w3.org/1999/xhtml\" lang=\"en\" xml:lang=\"en\">\\n<head>\\n<title>Bad Gateway!</title>\\n<link rev=\"made\" href=\"mailto:support@f5.com\" />\\n<style type=\"text/css\"><!--/*--><![CDATA[/*><!--*/ \\n    body { color: #000000; background-color: #FFFFFF; }\\n    a:link { color: #0000CC; }\\n    p, address {margin-left: 3em;}\\n    span {font-size: smaller;}\\n/*]]>*/--></style>\\n<style type=\"text/css\"><!--/*--><![CDATA[/*><!--*/ \\n* { width: 400px; font-size: 100%; font-style: normal; }\\nhtml { text-align: center; }\\nbody { background: #ffffff; text-align: left; font-family: sans-serif; font-size: 70%; color: #333333; }\\n\\na,span { width: auto; } \\nh1,h2,h3 { margin: 20px 0px 20px 0px; font-weight: bold; }\\n\\nh1 { padding: 5px; border: 1px solid #999999; background: #eeeeee; color: #000000; font-size: 125%;  }\\nhr { height: 1px; border: none; border-top: 1px solid #999999; }\\nimg { border: 0px; }\\np { width: 350px; margin: 15px 25px 15px 25px; line-height: 135%; }\\n/*]]>*/--></style>\\n\\n</head>\\n\\n<body>\\n<h1>Bad Gateway!</h1>\\n<p>\\n\\n\\n    The proxy server received an invalid\\n    response from an upstream server.\\n\\n  \\n    </p>\\n<p>\\n\\n    The proxy server could not handle the request <em><a href=\"/mgmt/tm/sys/ucs/\">POST&nbsp;/mgmt/tm/sys/ucs/</a></em>.<p>\\nReason: <strong>Error reading from remote server</strong></p>\\n  \\n    \\n</p>\\n\\n<h2>Error 502</h2>\\n<address>\\n  <a href=\"/\">10.10.10.10</a><br />\\n  \\n  <span>Tue May 28 09:01:37 2019<br />\\n  </span>\\n</address>\\n</body>\\n</html>\\n\\n'"
}
```
