### ISSUE TITLE
Does the user exist?

### ISSUE THREAD

**Issue by dfitz82** [F5Networks/f5-ansible#1362]
New Issue. Cannot find issue being reported.

##### ISSUE TYPE
 - Feature Idea

##### COMPONENT NAME
```
bigip_user
    - update_password
```

##### ANSIBLE VERSION
```
ansible 2.7.10
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, Apr  9 2019, 14:30:50) [GCC 4.8.5 20150623 (Red Hat 4.8.5-36)]
```

##### PYTHON VERSION

```
Python 2.7.5
```

##### BIGIP VERSION

```
Sys::Version
Main Package
  Product     BIG-IP
  Version     13.1.1
  Build       0.0.4
  Edition     Final
  Date        Fri Jul 20 17:55:49 PDT 2018
```

##### ROLE VERSION

```
Role: f5devcentral.f5ansible
        description: Ansible role that allows use of the F5 Ansible Modules
        active: True
        commit: 953b7e5b121584e7e5bfa6337a639435e4eb7707
        commit_message: Merging upstream changes - 2019-06-04T07:00:56Z
        commit_url: https://api.github.com/repos/f5devcentral/ansible-role-f5ansible/git/commits/953b7e5b121584e7e5bfa6337a639435e4eb7707
        company: F5 Networks
        created: 2018-10-04T16:14:10.510085Z
        download_count: 5797
        forks_count: 0
        github_branch: master
        github_repo: ansible-role-f5ansible
        github_user: f5devcentral
        id: 30341
        imported: 2019-06-04T03:04:17.276595-04:00
        is_valid: True
        issue_tracker_url: 
        license: GPLv3
        min_ansible_version: 2.8
        modified: 2019-06-04T07:04:17.283820Z
        open_issues_count: 0
        path: [u'/root/.ansible/roles', u'/usr/share/ansible/roles', u'/etc/ansible/roles']
        role_type: ANS
        stargazers_count: 4
        travis_status_url: https://travis-ci.org/f5devcentral/ansible-role-f5ansible.svg?branch=master
```

##### CONFIGURATION

Standard configuration settings    

##### OS / ENVIRONMENT

```
CentOS Linux release 7.6.1810 (Core) 
```

##### SUMMARY

The option "update_password" has a default action of "always" and I expected that to work for creating a new user.    
Instead I must use the "bigip_command" module and conditional statements to automate user changes.

##### STEPS TO REPRODUCE

A playbook to create or update a user requires at least three plays.       
    
The result of the 1st play will determine if the user is to be created or updated.

```
  - name: Check if User Exists
    bigip_command:
      commands: "list auth user {{ af_user }}"
      provider:
        server: "{{ host }}"
        server_port: "{{ host_port }}"
        user: "{{ admin_user }}"
        password: "{{ admin_pw }}"
        validate_certs: no
    tags:
      - f5
    register: user
```    
Creating a user with the module "bigip_user" requires the option "update_password" action "on_create".    
This results in two subsequent plays for a user creation or a password change.

##### EXPECTED RESULTS

The default action for "update_password" is "always".    
I expected this to always set the password to the given value, even if the user is created.    

##### ACTUAL RESULTS

I am able to use the play shown above and simple "when:" statements in the subsequent plays as a workaround.    
I am submitting this because the documentation suggests that any use of the module "bigip_command" should have an issue reported.
