### ISSUE TITLE
bigip_virtual_server - specify custom udp profile with ip_protocol udp results in only udp profile applied

### ISSUE THREAD

**Issue by neozoolook** [F5Networks/f5-ansible#1372]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

bigip_virtual_server.py

##### ANSIBLE VERSION

```
ansible 2.7.8
  config file = /tmp/pycharm_project_52e/ansible.cfg
  configured module search path = [u'/tmp/pycharm_project_52e/library/modules']
  ansible python module location = /usr/local/lib/python2.7/dist-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 2.7.12 (default, Dec  4 2017, 14:50:18) [GCC 5.4.0 20160609]
```

##### PYTHON VERSION

```
Python 2.7.12
```

##### BIGIP VERSION

```
Sys::Version
Main Package
  Product     BIG-IP
  Version     14.1.0
  Build       0.0.116
  Edition     Final
  Date        Wed Nov 14 18:41:56 PST 2018
```

##### ROLE VERSION

```
Role: f5devcentral.f5ansible
        description: Ansible role that allows use of the F5 Ansible Modules
        active: True
        commit: 953b7e5b121584e7e5bfa6337a639435e4eb7707
        commit_message: Merging upstream changes - 2019-06-04T07:00:56Z
        commit_url: https://api.github.com/repos/f5devcentral/ansible-role-f5ansible/
        company: F5 Networks
        created: 2018-10-04T16:14:10.510085Z
        download_count: 5974
        forks_count: 0
        github_branch: master
        github_repo: ansible-role-f5ansible
        github_user: f5devcentral
        id: 30341
        imported: 2019-06-04T03:04:17.276595-04:00
        is_valid: True
        issue_tracker_url: 
        license: GPLv3
        min_ansible_version: 2.8
        modified: 2019-06-04T07:04:17.283820Z
        open_issues_count: 0
        path: [u'/root/.ansible/roles', u'/usr/share/ansible/roles', u'/etc/ansible/r
        role_type: ANS
        stargazers_count: 4
        travis_status_url: https://travis-ci.org/f5devcentral/ansible-role-f5ansible.
```

##### CONFIGURATION

Specified library/module pathing;
inventory      =./hosts.inv
library        =./library/modules
module_utils   =./library/module_utils

##### OS / ENVIRONMENT

Ubuntu 16.04 LTS
##### SUMMARY

when you specify a custom UDP profile to be applied with the creation of a virtual server and ip_protocol UDP is provided the virtual is created but the profile only gets the default UDP profile.

##### STEPS TO REPRODUCE

```
---
- name: ///PROTOCOL PROFILE/// Custom UDP Per Datagram LB
  bigip_profile_udp:
    name: "syslog-udp"
    parent: "udp"
    idle_timeout: 60
    datagram_load_balancing: yes
    state: present
    provider:
      password: "{{ password }}"
      server: "{{ ansible_host }}"
      user: "{{ username }}"
      validate_certs: "no"
  delegate_to: localhost

- name: ///VIRTUAL/// Build {{ hsl_virt_udp }}
  bigip_virtual_server:
    all_profiles:
      - "{{ hsl_virt_udp_profile }}"
    description: "{{ hsl_virt_udp_desc }}"
    destination: "{{ hsl_virt_udp_dest }}"
    enabled_vlans: "{{ hsl_vlan }}"
    ip_protocol: udp
    name: "{{ hsl_virt_udp }}"
    pool: "{{ pool_name }}"
    port: "{{ hsl_virt_udp_port }}"
    profiles:
      - syslog-udp
    state: present
    provider:
      password: "{{ password }}"
      server: "{{ ansible_host }}"
      user: "{{ username }}"
      validate_certs: "no"
  delegate_to: localhost
```

##### EXPECTED RESULTS

You should be able to bind a custom profile that is based off UDP to a virtual when ip_protocol udp is specified.

##### ACTUAL RESULTS

```
pp2854@dark-kyber:/tmp/pycharm_project_52e$ ansible-playbook site.yml --ask-vault-pass --tags virt_hsl -vvvv
ansible-playbook 2.7.8
  config file = /tmp/pycharm_project_52e/ansible.cfg
  configured module search path = [u'/tmp/pycharm_project_52e/library/modules']
  ansible python module location = /usr/local/lib/python2.7/dist-packages/ansible
  executable location = /usr/local/bin/ansible-playbook
  python version = 2.7.12 (default, Dec  4 2017, 14:50:18) [GCC 5.4.0 20160609]
Using /tmp/pycharm_project_52e/ansible.cfg as config file
Vault password: 
setting up inventory plugins
/tmp/pycharm_project_52e/hosts.inv did not meet host_list requirements, check plugin documentation if this is unexpected
/tmp/pycharm_project_52e/hosts.inv did not meet script requirements, check plugin documentation if this is unexpected
/tmp/pycharm_project_52e/hosts.inv did not meet yaml requirements, check plugin documentation if this is unexpected
Parsed /tmp/pycharm_project_52e/hosts.inv inventory source with ini plugin
Loading callback plugin default of type stdout, v2.0 from /usr/local/lib/python2.7/dist-packages/ansible/plugins/callback/default.pyc

PLAYBOOK: site.yml ******************************************************************
1 plays in site.yml

PLAY [zrdm52elogb01] ****************************************************************
META: ran handlers
Trying secret <ansible.parsing.vault.PromptVaultSecret object at 0x7fa463abb0d0> for vault_id=default

TASK [///ROLE/// F5 VIRTUALS] *******************************************************
task path: /tmp/pycharm_project_52e/site.yml:43
statically imported: /tmp/pycharm_project_52e/roles/bigip_virtual/tasks/profile_udp.yml
statically imported: /tmp/pycharm_project_52e/roles/bigip_virtual/tasks/virtual_hsl.yml

TASK [bigip_virtual : ///VIRTUAL/// Build HSL-NET1-UDP-V4] **************************
task path: /tmp/pycharm_project_52e/roles/bigip_virtual/tasks/virtual_hsl.yml:2
<localhost> connection transport is rest
<localhost> connection transport is rest
Using module file /tmp/pycharm_project_52e/library/modules/bigip_virtual_server.py
<localhost> ESTABLISH LOCAL CONNECTION FOR USER: pp2854
<localhost> EXEC /bin/sh -c '/usr/bin/python && sleep 0'
Using module file /tmp/pycharm_project_52e/library/modules/bigip_virtual_server.py
<localhost> ESTABLISH LOCAL CONNECTION FOR USER: pp2854
<localhost> EXEC /bin/sh -c '/usr/bin/python && sleep 0'
changed: [zrdm52elogb01lgb002 -> localhost] => {
    "address_translation": false, 
    "changed": true, 
    "description": "UDP SYSLOG FORWARDER VIRTUAL", 
    "destination": "107.243.192.24", 
    "enabled_vlans": [
        "/Common/HSL-V4"
    ], 
    "invocation": {
        "module_args": {
            "address_translation": null, 
            "all_profiles": [
                "udp"
            ], 
            "auth_provider": null, 
            "clone_pools": null, 
            "default_persistence_profile": null, 
            "description": "UDP SYSLOG FORWARDER VIRTUAL", 
            "destination": "107.243.192.24", 
            "disabled_vlans": null, 
            "enabled_vlans": [
                "HSL-V4"
            ], 
            "fallback_persistence_profile": null, 
            "firewall_enforced_policy": null, 
            "firewall_staged_policy": null, 
            "insert_metadata": true, 
            "ip_intelligence_policy": null, 
            "ip_protocol": "udp", 
            "irules": null, 
            "mask": null, 
            "metadata": null, 
            "mirror": null, 
            "name": "HSL-NET1-UDP-V4", 
            "partition": "Common", 
            "password": null, 
            "policies": null, 
            "pool": "JSA-POOL", 
            "port": "514", 
            "port_translation": null, 
            "profiles": [
                "udp"
            ], 
            "provider": {
                "auth_provider": null, 
                "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER", 
                "proxy_to": null, 
                "server": "107.117.93.102", 
                "server_port": null, 
                "ssh_keyfile": null, 
                "timeout": null, 
                "transport": "rest", 
                "user": "admin", 
                "validate_certs": false
            }, 
            "rate_limit": null, 
            "rate_limit_dst_mask": null, 
            "rate_limit_mode": "object", 
            "rate_limit_src_mask": null, 
            "security_log_profiles": null, 
            "security_nat_policy": null, 
            "server": null, 
            "server_port": null, 
            "snat": null, 
            "source": null, 
            "source_port": null, 
            "state": "present", 
            "transport": null, 
            "type": "standard", 
            "user": null, 
            "validate_certs": null
        }
    }, 
    "ip_protocol": "udp", 
    "mask": "255.255.255.255", 
    "pool": "/Common/JSA-POOL", 
    "port": 514, 
    "port_translation": false, 
    "profiles": [
        {
            "context": "all", 
            "fullPath": "/Common/udp", 
            "name": "udp"
        }
    ], 
    "rate_limit_mode": "object", 
    "type": "standard", 
    "vlans": [
        "/Common/HSL-V4"
    ], 
    "vlans_enabled": true
}
changed: [zrdm52elogb01lgb001 -> localhost] => {
    "address_translation": false, 
    "changed": true, 
    "description": "UDP SYSLOG FORWARDER VIRTUAL", 
    "destination": "107.243.192.24", 
    "enabled_vlans": [
        "/Common/HSL-V4"
    ], 
    "invocation": {
        "module_args": {
            "address_translation": null, 
            "all_profiles": [
                "udp"
            ], 
            "auth_provider": null, 
            "clone_pools": null, 
            "default_persistence_profile": null, 
            "description": "UDP SYSLOG FORWARDER VIRTUAL", 
            "destination": "107.243.192.24", 
            "disabled_vlans": null, 
            "enabled_vlans": [
                "HSL-V4"
            ], 
            "fallback_persistence_profile": null, 
            "firewall_enforced_policy": null, 
            "firewall_staged_policy": null, 
            "insert_metadata": true, 
            "ip_intelligence_policy": null, 
            "ip_protocol": "udp", 
            "irules": null, 
            "mask": null, 
            "metadata": null, 
            "mirror": null, 
            "name": "HSL-NET1-UDP-V4", 
            "partition": "Common", 
            "password": null, 
            "policies": null, 
            "pool": "JSA-POOL", 
            "port": "514", 
            "port_translation": null, 
            "profiles": [
                "udp"
            ], 
            "provider": {
                "auth_provider": null, 
                "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER", 
                "proxy_to": null, 
                "server": "107.117.93.101", 
                "server_port": null, 
                "ssh_keyfile": null, 
                "timeout": null, 
                "transport": "rest", 
                "user": "admin", 
                "validate_certs": false
            }, 
            "rate_limit": null, 
            "rate_limit_dst_mask": null, 
            "rate_limit_mode": "object", 
            "rate_limit_src_mask": null, 
            "security_log_profiles": null, 
            "security_nat_policy": null, 
            "server": null, 
            "server_port": null, 
            "snat": null, 
            "source": null, 
            "source_port": null, 
            "state": "present", 
            "transport": null, 
            "type": "standard", 
            "user": null, 
            "validate_certs": null
        }
    }, 
    "ip_protocol": "udp", 
    "mask": "255.255.255.255", 
    "pool": "/Common/JSA-POOL", 
    "port": 514, 
    "port_translation": false, 
    "profiles": [
        {
            "context": "all", 
            "fullPath": "/Common/udp", 
            "name": "udp"
        }
    ], 
    "rate_limit_mode": "object", 
    "type": "standard", 
    "vlans": [
        "/Common/HSL-V4"
    ], 
    "vlans_enabled": true
}

TASK [bigip_virtual : ///VIRTUAL/// Build HSL-NET1-TCP-V4] **************************
task path: /tmp/pycharm_project_52e/roles/bigip_virtual/tasks/virtual_hsl.yml:23
<localhost> connection transport is rest
Using module file /tmp/pycharm_project_52e/library/modules/bigip_virtual_server.py
<localhost> ESTABLISH LOCAL CONNECTION FOR USER: pp2854
<localhost> EXEC /bin/sh -c '/usr/bin/python && sleep 0'
<localhost> connection transport is rest
Using module file /tmp/pycharm_project_52e/library/modules/bigip_virtual_server.py
<localhost> ESTABLISH LOCAL CONNECTION FOR USER: pp2854
<localhost> EXEC /bin/sh -c '/usr/bin/python && sleep 0'
ok: [zrdm52elogb01lgb002 -> localhost] => {
    "address_translation": false, 
    "changed": false, 
    "invocation": {
        "module_args": {
            "address_translation": null, 
            "all_profiles": [
                "tcp"
            ], 
            "auth_provider": null, 
            "clone_pools": null, 
            "default_persistence_profile": null, 
            "description": "TCP SYSLOG FORWARDER VIRTUAL", 
            "destination": "107.243.192.24", 
            "disabled_vlans": null, 
            "enabled_vlans": [
                "HSL-V4"
            ], 
            "fallback_persistence_profile": null, 
            "firewall_enforced_policy": null, 
            "firewall_staged_policy": null, 
            "insert_metadata": true, 
            "ip_intelligence_policy": null, 
            "ip_protocol": "tcp", 
            "irules": null, 
            "mask": null, 
            "metadata": null, 
            "mirror": null, 
            "name": "HSL-NET1-TCP-V4", 
            "partition": "Common", 
            "password": null, 
            "policies": null, 
            "pool": "JSA-POOL", 
            "port": "514", 
            "port_translation": null, 
            "profiles": [
                "tcp"
            ], 
            "provider": {
                "auth_provider": null, 
                "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER", 
                "proxy_to": null, 
                "server": "107.117.93.102", 
                "server_port": null, 
                "ssh_keyfile": null, 
                "timeout": null, 
                "transport": "rest", 
                "user": "admin", 
                "validate_certs": false
            }, 
            "rate_limit": null, 
            "rate_limit_dst_mask": null, 
            "rate_limit_mode": "object", 
            "rate_limit_src_mask": null, 
            "security_log_profiles": null, 
            "security_nat_policy": null, 
            "server": null, 
            "server_port": null, 
            "snat": null, 
            "source": null, 
            "source_port": null, 
            "state": "present", 
            "transport": null, 
            "type": "standard", 
            "user": null, 
            "validate_certs": null
        }
    }, 
    "port_translation": false
}
ok: [zrdm52elogb01lgb001 -> localhost] => {
    "address_translation": false, 
    "changed": false, 
    "invocation": {
        "module_args": {
            "address_translation": null, 
            "all_profiles": [
                "tcp"
            ], 
            "auth_provider": null, 
            "clone_pools": null, 
            "default_persistence_profile": null, 
            "description": "TCP SYSLOG FORWARDER VIRTUAL", 
            "destination": "107.243.192.24", 
            "disabled_vlans": null, 
            "enabled_vlans": [
                "HSL-V4"
            ], 
            "fallback_persistence_profile": null, 
            "firewall_enforced_policy": null, 
            "firewall_staged_policy": null, 
            "insert_metadata": true, 
            "ip_intelligence_policy": null, 
            "ip_protocol": "tcp", 
            "irules": null, 
            "mask": null, 
            "metadata": null, 
            "mirror": null, 
            "name": "HSL-NET1-TCP-V4", 
            "partition": "Common", 
            "password": null, 
            "policies": null, 
            "pool": "JSA-POOL", 
            "port": "514", 
            "port_translation": null, 
            "profiles": [
                "tcp"
            ], 
            "provider": {
                "auth_provider": null, 
                "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER", 
                "proxy_to": null, 
                "server": "107.117.93.101", 
                "server_port": null, 
                "ssh_keyfile": null, 
                "timeout": null, 
                "transport": "rest", 
                "user": "admin", 
                "validate_certs": false
            }, 
            "rate_limit": null, 
            "rate_limit_dst_mask": null, 
            "rate_limit_mode": "object", 
            "rate_limit_src_mask": null, 
            "security_log_profiles": null, 
            "security_nat_policy": null, 
            "server": null, 
            "server_port": null, 
            "snat": null, 
            "source": null, 
            "source_port": null, 
            "state": "present", 
            "transport": null, 
            "type": "standard", 
            "user": null, 
            "validate_certs": null
        }
    }, 
    "port_translation": false
}
META: ran handlers
META: ran handlers

PLAY RECAP **************************************************************************
zrdm52elogb01lgb001        : ok=2    changed=1    unreachable=0    failed=0   
zrdm52elogb01lgb002        : ok=2    changed=1    unreachable=0    failed=0 
```

**Comment by wojtek0806** [comment]
the guidelines for submitting issues clearly state you need to test with the role and post results with the role in use if the issue persists. Closing until this is is provided

**Comment by wojtek0806** [comment]
also please use gists as the data is quite large. Waiting  for your update with required information.

**Comment by wojtek0806** [comment]
waiting for the requested information before we proceed

**Comment by wojtek0806** [comment]
The issue lies with your playbook, you specify profiles parameter twice, all_profiles is an alias for profiles. The behaviour here is that the first parameter from the top takes precedence, so in your case it would be whatever you got specified under: "{{ hsl_virt_udp_profile }}". The fact that ansible allows this might be a bug but parameter validation is done in ansible core not in the module. 

Invalid playbook run demonstrates this:

```
---

- name: VS_Profiles_Test
  hosts: f5-test[0]
  connection: local
  gather_facts: no

  vars:
    f5_provider:
      password: "admin"
      server: "{{ ansible_host }}"
      user: "admin"
      validate_certs: "no"
      server_port: "443"

  tasks:
    - name: Custom UDP Per Datagram LB
      bigip_profile_udp:
        provider: "{{ f5_provider }}"
        name: "syslog-udp"
        parent: "udp"
        idle_timeout: 60
        datagram_load_balancing: yes
        state: present

    - name: Custom pool
      bigip_pool:
        name: test_pool
        provider: "{{ f5_provider }}"

    - name: Custom vlan1
      bigip_vlan:
        name: vlan1
        provider: "{{ f5_provider }}"

    - name: VS Test
      bigip_virtual_server:
        all_profiles:
          - udp
        provider: "{{ f5_provider }}"
        description: "this is a test"
        destination: 192.168.1.1
        ip_protocol: udp
        enabled_vlans: vlan1
        pool: test_pool
        name: test_udp
        port: 129
        profiles:
          - syslog-udp
        state: present
```
Resulting config:

![Screen Shot 2019-06-07 at 20 17 07](https://user-images.githubusercontent.com/18006037/59128481-15612880-8962-11e9-953e-77fe51200142.png)

Proper playbook run does not have this issue:
```
- name: VS_Profiles_Test
  hosts: f5-test[0]
  connection: local
  gather_facts: no

  vars:
    f5_provider:
      password: "admin"
      server: "{{ ansible_host }}"
      user: "admin"
      validate_certs: "no"
      server_port: "443"

  tasks:
    - name: Custom UDP Per Datagram LB
      bigip_profile_udp:
        provider: "{{ f5_provider }}"
        name: "syslog-udp"
        parent: "udp"
        idle_timeout: 60
        datagram_load_balancing: yes
        state: present

    - name: Custom pool
      bigip_pool:
        name: test_pool
        provider: "{{ f5_provider }}"

    - name: Custom vlan1
      bigip_vlan:
        name: vlan1
        provider: "{{ f5_provider }}"

    - name: VS Test
      bigip_virtual_server:
        provider: "{{ f5_provider }}"
        description: "this is a test"
        destination: 192.168.1.1
        ip_protocol: udp
        enabled_vlans: vlan1
        pool: test_pool
        name: test_udp
        port: 129
        profiles:
          - syslog-udp
        state: present
```
Configuration results:
![Screen Shot 2019-06-07 at 20 13 29](https://user-images.githubusercontent.com/18006037/59128556-45a8c700-8962-11e9-9fe8-e6ea1f3f332e.png)

This has been tested on 2.8 and the role. Closing this as this is not a bug
