### ISSUE TITLE
bigip_monitor_http returning "changed" status if "receive" is empty string

### ISSUE THREAD

**Issue by Sam-Hall** [F5Networks/f5-ansible#1377]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

bigip_monitor_http

##### ANSIBLE VERSION

```
ansible 2.9.0.dev0
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/shall/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /home/shall/venv/local/lib/python2.7/site-packages/ansible
  executable location = /home/shall/venv/bin/ansible
  python version = 2.7.12 (default, Nov 12 2018, 14:36:49) [GCC 5.4.0 20160609]
```

##### PYTHON VERSION

```
Python 2.7.12
```

##### BIGIP VERSION

```
Sys::Version
Main Package
  Product     BIG-IP
  Version     14.1.0.3
  Build       0.0.6
  Edition     Point Release 3
  Date        Mon Mar 25 17:15:27 PDT 2019
```

##### ROLE VERSION

```
Role: f5devcentral.f5ansible
        description: Ansible role that allows use of the F5 Ansible Modules
        active: True
        commit: 5090de7b35c5939fbba08683deaf938761f8dcb3
        commit_message: Merging upstream changes - 2019-06-07T07:01:01Z
        commit_url: https://api.github.com/repos/f5devcentral/ansible-role-f5ansible/git/commits/5090de7b35c5939fbba08683deaf938761f
        company: F5 Networks
        created: 2018-10-04T16:14:10.510085Z
        dependencies: []
        download_count: 6649
        forks_count: 0
        galaxy_info:
                author: caphrim007
                company: F5 Networks
                galaxy_tags: ['f5', 'networking', 'bigip', 'bigiq']
                license: GPLv3
                min_ansible_version: 2.8
                platforms: [{'name': 'EL', 'versions': ['all']}, {'name': 'Fedora', 'versions': ['all']}, {'name': 'Ubuntu', 'versio
                role_name: f5ansible
        github_branch: master
        github_repo: ansible-role-f5ansible
        github_user: f5devcentral
        id: 30341
        imported: 2019-06-07T04:03:27.292264-04:00
        install_date: Fri May 31 01:23:49 2019
        installed_version: v2019.5.24
        is_valid: True
        issue_tracker_url:
        license: GPLv3
        min_ansible_version: 2.8
        modified: 2019-06-07T08:03:27.298571Z
        open_issues_count: 0
        path: (u'/home/shall/.ansible/roles', u'/usr/share/ansible/roles', u'/etc/ansible/roles')
        role_type: ANS
        stargazers_count: 4
        travis_status_url: https://travis-ci.org/f5devcentral/ansible-role-f5ansible.svg?branch=v2019.6.7
```

##### CONFIGURATION
Everything default

##### OS / ENVIRONMENT
"Ubuntu 16.04.5 LTS" on Windows 10

##### SUMMARY
Creating a monitor using bigip_monitor_http with empty string values ("") reports status "changed".

##### STEPS TO REPRODUCE
Here's a test case. Note mon_recv is declared with the value "". If I change this to the word null, I no longer have this issue.
```
- name: testcase.com
  hosts: ltmv141dev
  connection: local
  gather_facts: false
  vars:
    provider:
      server: "{{ host_fqdn }}"
      user: "{{ username }}"
      password: "{{ password }}"
      validate_certs: no
      server_port: 443
    vs_fqdn: "testcase.com"
    mon_send: "GET /"
    mon_recv: ""
  tasks:
    - name: Create HTTP Monitor
      bigip_monitor_http:
        provider: "{{ provider }}"
        name: "{{ vs_fqdn }}_monitor"
        interval: 30
        timeout: 91
        send: "{{ mon_send }} HTTP/1.1\r\nHost: {{ vs_fqdn }}\r\nConnection: Close\r\n\r\n"
        receive: "{{ mon_recv }}"
      delegate_to: localhost
```

##### EXPECTED RESULTS
I'd expect it to only have status "changed" the first time this playbook runs with this same set of variable values regardless of the use of "" as a value. This might seem like a minor thing, especially since I have my workaround, however I'm hoping to get broader adoption of Ansible with some people who have a less technical background, so if we can avoid the need for people to understand what null is and why it's not "", that would be helpful. This was driving me nuts since yesterday, it wasn't until I started logging this bug report and checked the output of "-vvvv" that I finally understood what was going on here.

##### ACTUAL RESULTS

I'm assuming that **"receive": ""** is compared with **"receive": null** and the status is considered as "changed".

```
changed: [ltmv141dev -> localhost] => {
    "changed": true,
    "invocation": {
        "module_args": {
            "auth_provider": null,
            "description": null,
            "interval": 30,
            "ip": null,
            "name": "testcase.com_monitor",
            "parent": "/Common/http",
            "partition": "Common",
            "password": null,
            "port": null,
            "provider": {
                "auth_provider": null,
                "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
                "proxy_to": null,
                "server": "ltmv141dev",
                "server_port": 443,
                "ssh_keyfile": null,
                "timeout": 91,
                "transport": "rest",
                "user": "username",
                "validate_certs": false
            },
            "receive": "",
            "receive_disable": null,
            "reverse": null,
            "send": "GET / HTTP/1.1\nHost: testcase.com\nConnection: Close\n",
            "server": null,
            "server_port": null,
            "state": "present",
            "target_password": null,
            "target_username": null,
            "time_until_up": null,
            "timeout": 91,
            "transport": null,
            "user": null,
            "validate_certs": null
        }
    },
    "receive": ""
}
```
