### ISSUE TITLE
XML files created by the bigip_asm_policy_fetch module are empty.

### ISSUE THREAD

**Issue by gnagorski** [F5Networks/f5-ansible#1390]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
bigip_asm_policy_fetch

##### ANSIBLE VERSION
```
ansible 2.8.1
  config file = None
  configured module search path = [u'/Users/gnagorski/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /Library/Python/2.7/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 2.7.10 (default, Oct  6 2017, 22:29:07) [GCC 4.2.1 Compatible Apple LLVM 9.0.0 (clang-900.0.31)]
```

##### PYTHON VERSION
```
Python 2.7.10
```

##### BIGIP VERSION
```
Sys::Version
Main Package
  Product     BIG-IP
  Version     12.1.3.1
  Build       0.0.9
  Edition     Point Release 1
  Date        Fri Dec 15 21:51:01 PST 2017
```

##### ROLE VERSION
```
Role: f5devcentral.f5ansible
        description: Ansible role that allows use of the F5 Ansible Modules
        active: True
        commit: d8a64711cf8311c0f4dd5c6703606003fc6c0c90
        commit_message: Merging upstream changes - 2019-06-18T07:00:37Z
        commit_url: https://api.github.com/repos/f5devcentral/ansible-role-f5ansible/git/commits/d8a64711cf8311c0f4dd5c6703606003fc6c0c90
        company: F5 Networks
        created: 2018-10-04T16:14:10.510085Z
        download_count: 7706
        forks_count: 0
        github_branch: master
        github_repo: ansible-role-f5ansible
        github_user: f5devcentral
        id: 30341
        imported: 2019-06-18T03:04:45.679606-04:00
        is_valid: True
        issue_tracker_url:
        license: GPLv3
        min_ansible_version: 2.8
        modified: 2019-06-18T07:04:45.687011Z
        open_issues_count: 0
        path: (u'/Users/gnagorski/.ansible/roles', u'/usr/share/ansible/roles', u'/etc/ansible/roles')
        role_type: ANS
        stargazers_count: 4
        travis_status_url: https://travis-ci.org/f5devcentral/ansible-role-f5ansible.svg?branch=master
```

##### CONFIGURATION
None

##### OS / ENVIRONMENT
macOS 10.13.6

##### STEPS TO REPRODUCE

```
---
- name: Fetch ASM policy
  connection: local
  gather_facts: False

  vars_prompt:
    - name: "username"
      prompt: "Enter BIG-IP username"
      private: yes
    - name: "password"
      prompt: "Enter BIG-IP password"
      private: yes

  environment:
    F5_SERVER: ltm01
    F5_USER: "{{ username }}"
    F5_PASSWORD: "{{ password }}"
    F5_SERVER_PORT: 443

  tasks:
    - name: Get ASM policy
      bigip_asm_policy_fetch:
        name: ASM-POLICY
        partition: CUSTOMER-PARTITION
        file: ASM-POLICY.xml
        dest: /tmp/asm-export/
```

##### EXPECTED RESULTS
A file at /tmp/asm-export/ASM-POLICY.xml with the settings of ASM-POLICY

##### ACTUAL RESULTS
The playbook runs without any errors and creates a file at /tmp/asm-export/ASM-POLICY.xml, but the file is empty. I walked through the steps this module takes, and the XML file created on the LTM has the expected content. However, the file that is created on the local machine is empty. I also tried using the `inline` option, but no XML is written to the terminal window with that option.
