### ISSUE TITLE
device_info vCMP VLANs

### ISSUE THREAD

**Issue by DerrickTJ** [F5Networks/f5-ansible#1391]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
bigip_device_info

##### ANSIBLE VERSION
```
ansible 2.9.0.dev0
  config file = /Users/djohnson/Documents/GitHub/djohnson/DJ_TestProject/ansible.cfg
  configured module search path = ['/Users/djohnson/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /Users/djohnson/Documents/GitHub/ansible/lib/ansible
  executable location = /Users/djohnson/Documents/GitHub/ansible/bin/ansible
  python version = 3.7.2 (v3.7.2:9a3ffc0492, Dec 24 2018, 02:44:43) [Clang 6.0 (clang-600.0.57)]

```

##### PYTHON VERSION

```
Python 3.7.2
```

##### BIGIP VERSION

```
Main Package
  Product     BIG-IP
  Version     14.1.0.3
  Build       0.0.6
  Edition     Point Release 3
  Date        Mon Mar 25 17:15:27 PDT 2019
```

##### SUMMARY
Gathering info from the vCMP does not display the currently used VLANs.

##### STEPS TO REPRODUCE
```
     bigip_device_facts:
       gather_subset:
         - vcmp-guests
       <<: *login_host
     delegate_to: localhost
     register: results
```

##### EXPECTED RESULTS
Would like to see the list of VLANs outputted so I can put these into a jinja2 template and output it back into the vCMP modules to keep updating VLANs.

##### ACTUAL RESULTS
```                "boot_priority": 65535,
                "cores_per_slot": 2,
                "full_path": "***-F5-001",
                "hostname": "***-F5-001.***.net",
                "initial_image": "BIGIP-14.1.0.0.0.116.iso",
                "mgmt_address": "10.***/24",
                "mgmt_network": "bridged",
                "mgmt_route": "10.***",
                "min_number_of_slots": 1,
                "name": "***-F5-001",
                "number_of_slots": 1,
                "ssl_mode": "shared",
                "state": "provisioned",
                "virtual_disk": "***-F5-001.img"

```

**Comment by DerrickTJ** [comment]
@wojtek0806 @caphrim007 Any way I could get some priority on this? It is breaking my Jenkin's pipeline without this while we are trying to migrate to our new 11800's with vCMPs. #1296 was kind of the original request but I can work around that if the API can provide the output I need.

**Comment by wojtek0806** [comment]
FMFA-300

**Comment by DerrickTJ** [comment]
Found a workaround for the workaround (lol) to get the results I need for the time being.

Use device facts against the actual vCMP instead of at the host level to query what VLANs it has and reapply them and the new VLANs. This only works if the vCMP host and the vCMP are insync. If you deleted the VLAN off the host but didn't go into the vCMP and remove the VLAN, it will readd it. Removing VLANs from a vCMP at the host level does not remove it from the vCMP itself.

The file created here should be deleted once the playbook is finished. Since it is part of my role, it is automatically deleted because of my pipeline. 

```
    - name: Create F5 VLAN File
      file:
        dest: ./roles/f5_host/vars/f5vlans.yaml
        state: touch
      delegate_to: localhost

    - name: Create VLAN List
      lineinfile:
        dest: ./roles/f5_host/vars/f5vlans.yaml
        line: "vlan_list:"
        insertafter: EOF
      delegate_to: localhost

    - name: Collect BIG-IP VLAN facts
      bigip_device_facts:
        gather_subset:
          - vlans
        provider:
          server: F5_vCMP
          user: admin
          password: ****
          validate_certs: no
      delegate_to: localhost
      register: gathered_vlans

    - name: Appened Existing VLANs to List
      lineinfile:
        dest: ./roles/f5_host/vars/f5vlans.yaml
        line: "- {{ item.name }} "
        insertafter: EOF
      delegate_to: localhost
      with_items: "{{ gathered_vlans.vlans }}"

    - name: Dynamically load vlan_list
      include_vars:
        file: ./roles/f5_host/vars/f5vlans.yaml

    - name: Add VLANs
      bigip_vcmp_guest:
        name: F5_vCMP
        vlans: "{{ vlan_list }}"
        provider:
          server: F5_HOST
          user: admin
          password: *****
          validate_certs: no
      delegate_to: localhost
```
