### ISSUE TITLE
bigip_imish_config "save_when" parameter issue

### ISSUE THREAD

**Issue by m-kratochvil** [F5Networks/f5-ansible#1392]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
bigip_imish_config

##### ANSIBLE VERSION
```
ansible 2.8.0
  config file = /home/michal/homelab/ansible.cfg
  configured module search path = ['/home/michal/homelab/plugins/modules']
  ansible python module location = /home/michal/ccloud-net/venv/lib/python3.7/site-packages/ansible
  executable location = /home/michal/ccloud-net/venv/bin/ansible
  python version = 3.7.3 (default, Apr  3 2019, 05:39:12) [GCC 8.3.0]
```

##### PYTHON VERSION
```
Python 3.7.3
```

##### BIGIP VERSION
```
Sys::Version
Main Package
  Product     BIG-IP
  Version     13.1.1.4
  Build       0.0.4
  Edition     Point Release 4
  Date        Wed Jan 16 18:04:36 PST 2019
```

##### CONFIGURATION
```
[defaults]
roles_path = ./roles
host_key_checking = false
library = ./plugins/modules
filter_plugins= ./plugins/filters
inventory_plugins=./plugins/inventories
fact_caching_connection=./.cache/
deprecation_warnings = false

inventory=./inventory/local

[inventory]
cache=true
cache_timeout=3600
cache_plugin=pickle
unparsed_is_failed=true

[paramiko_connection]
look_for_keys=no
use_persistent_connections=yes
host_key_checking=no
```
##### SUMMARY
The module parameter "save_when" does not save the imish configuration when other than default route-domain is used, even if such route domain is correctly specified in the module "route_domain" parameter. The "save_when" parameter always uses a command ```cmd_data=run util bash -c "imish -e write"``` as visible in the "audit" log which does not save the config in, for example, route domain 1. This is the case with all "save_when" choices (always, modified, changed).

##### STEPS TO REPRODUCE
Use the module in a playbook to apply imish configuration to other than default route domain (in the below example route domain 1).

```
---
- name: Reconfigure routing setup on mgmt clusters
  hosts: all
  order: sorted
  gather_facts: false
  connection: local
  tasks:
# Create the zebos/imish dynamic routing configuration
    - name: Create dynamic routing configuration
      bigip_imish_config:
        provider:
          server: "{{ ansible_host }}"
          user: "{{ restuser }}"
          password: "{{ restpassword }}"
        route_domain: "1"
        src: "files/f5a.cfg"
        save_when: always
        validate_certs: no
```

##### EXPECTED RESULTS
The imish configuration should be saved to disk in its dedicated location:
```
[root@f5a:Active:Disconnected] config # ls -l zebos/rd1/
total 4
-rw-r-----. 1 root root 671 2019-06-20 14:54 ZebOS.conf
```
Also, the "/var/log/audit" should show following command was applied:
```cmd_data=run util bash -c "imish -r 1 -e write"```  (Note the "-r 1" specifying the route domain id 1.)

##### ACTUAL RESULTS
The imish configuration is not saved to disk and remains only in running configuration:
```
[root@f5a:Active:Disconnected] config # ls -l zebos/rd1/
total 0
```
The "/var/log/audit" file shows command:
```cmd_data=run util bash -c "imish -e write"```   (Note the "-r 1" is missing.)
