### ISSUE TITLE
Insert persist cookie in bigip_policy_rule

### ISSUE THREAD

**Issue by sdaynjax** [F5Networks/f5-ansible#1405]
##### ISSUE TYPE

 - Feature Idea

##### COMPONENT NAME

bigip_policy_rule

##### ANSIBLE VERSION

```
2.8
```

##### PYTHON VERSION

```
2.7
```

##### BIGIP VERSION

```
  Version     12.1.4.1
```

##### ROLE VERSION

```
not using a role
```

##### OS / ENVIRONMENT

RHEL 7

##### SUMMARY

I'm looking for a way to add the action of inserting a cookie into a policy rule. This is what it looks like with TMSH:

test_rule {
            actions {
                0 {
                    forward
                    select
                    pool test_pool
                }
                1 {
                    persist
                    cookie-insert
                    name test_cookie
                }
            }
            conditions {
                0 {
                    http-uri
                    path
                    starts-with
                    values { /test }
                }
            }
            ordinal 2
        }
    }
    status published
    strategy first-match
}

##### STEPS TO REPRODUCE

```
- name: Add multiple rules to the new policy
      bigip_policy_rule:
        provider: "{{ cli }}"
        policy: "{{ fqdn }}-{{ vs_port }}_policy"
        name: "{{ item.rl_name }}"
        actions:
          - type: forward
            pool: "{{ item.pool }}"
          - type: persist 
            cookie_insert : "{{ item.cookie }}"
        conditions:
          - type: http_uri
            path_begins_with_any: "{{ item.pl_path }}"
        state: "{{ state }}"
      with_items: "{{ rules }}"
```

##### EXPECTED RESULTS

This should allow cookie persistence to be enabled for the pool traffic is being forwarded to

##### ACTUAL RESULTS

```

```
