### ISSUE TITLE
Extend bigip_policy_rule for SNI Routing

### ISSUE THREAD

**Issue by tsvsj** [F5Networks/f5-ansible#1406]
##### ISSUE TYPE
 - Feature Idea

##### COMPONENT NAME
bigip_policy_rule

##### SUMMARY
For now there seems only to be HTTP-related support in the module for the conditions. As layered virtuals are very important, especially in cloud environments, it would be great to have the SSL extension condition support in the module.

```
- bigip_policy_rule:
    policy: SNI-Routing
    name: "{{ item.rule_name}}"
    conditions:
      - type: ssl_extension
        servername_is_any: "{{ item.sni_server_name}}"
    actions:
      - type: forward
        virtual: "{{ item.forward_destination }}"
    provider:
      ...
  delegate_to: localhost
  loop:
    - { policy_name: "SNI-Routing", rule_name: "routeToDest1", sni_server_name: ["www.example.com","www.example.org"], forward_destination: "/Common/virtual1" }
    - { policy_name: "SNI-Routing", rule_name: "routeToDest2", sni_server_name: ["www.example.net"], forward_destination: "/Common/virtual2" }
    - { policy_name: "SNI-Routing", rule_name: "routeToDest3", sni_server_name: ["www.example.edu"], forward_destination: "/Common/virtual3" }
```

##### EXPECTED RESULTS
Add rules based on SNI SSL extension to LTM policy.

##### ACTUAL RESULTS
Not supported.

Thanks!

**Comment by tsvsj** [comment]
I thought of using the bigip_command module to workaround the not supported SNI extension in the policy rule module. Unfortunately this is not possible, as it would need the create or modify option. Using them would break idempotency of the playbook.

Any ideas?

**Comment by focrensh** [comment]
FMFA-290 was opened to track this internally.

You are correct that bigip_command will not be idempotent, but it could be a workaround for now.

**Comment by tsvsj** [comment]
@focrensh Unfortunately not. The playbook would only run once for create. Or I would need to have several versions or tasks with conditions.

However, I've found an better workaround, which is idempotent and works well:
* Create a Jinja2 template for the TMSH block of the LTM policy
* Use bigip_config module, to merge the template into the BIG-IP config

```
- name: "Create LTM Policies"
      bigip_config:
        merge_content: "{{ lookup('template','ltmPolicy_SniRouting.tmsh.j2') }}"
        provider:
        ...
      delegate_to: localhost
```
The template would look like this:
```
ltm policy /Common/SNI-Routing {
    controls { forwarding }
    requires { http-explicit client-ssl }
    rules {
    {% for ltm_rule in bip_ltm_policy_sni_routing %}
        "{{ ltm_rule.rule_name }}" {
            actions {
                0 {
                    forward
                    proxy-request
                    select
                    virtual {{ ltm_rule.virtual_name }}
                }
            }
            conditions {
                0 {
                    ssl-extension
                    ssl-client-hello
                    server-name
                    values { {% for server_name in ltm_rule.server_names %}{{ server_name }} {% endfor %}}
                }
                1 {
                    tcp
                    client-accepted
                    port
                    values { {% for virtual_port in ltm_rule.virtual_ports %}{{ virtual_port }} {% endfor %}}
                }
            }
        }
    {% endfor %}
    }
    status published
    strategy first-match
}
```
Along with a variable like:
```
bip_ltm_policy_sni_routing:
  - rule_name: "virtual1"
    server_names:
      - "virtual1.example.com"
    virtual_ports:
      - 443
    virtual_name: "/Common/virtual1"
  - rule_name: "virtual2"
    server_names:
      - "virtual2.example.com"
    virtual_ports:
      - 443
    virtual_name: "/Common/virtual2"
```

Hope that helps anyone.
