### ISSUE TITLE
bigp_command timeout when white space encountered after prompt

### ISSUE THREAD

**Issue by wojtek0806** [F5Networks/f5-ansible#1407]
Originally reported in this PR by @atopuzov: 

https://github.com/F5Networks/f5-ansible/pull/1402

##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME

bigip_command
##### ANSIBLE VERSION

```
devel
```

##### PYTHON VERSION

```
2.x, 3.x
```

##### BIGIP VERSION

```

```

##### ROLE VERSION

```
n/a
```

##### SUMMARY

I encountered a timeout issue with Ansible bigip_command where it would get stuck because it would not detect the prompt. Oddly enough devices that were problematic were all (cfg-sync Changes Pending)(Active) state and they would send 2 additional characters, space and a carriage return.

Problematic device (cfg-sync Changes Pending)(Active)(/Common)(tmos)# ^M
Hex for the last few chars: 29:23:20:20:0d

Working device (cfg-sync Changes Pending)(Standby)(/Common)(tmos)# 
Hex for the last few chars: 29:23:20

From http://www.asciitable.com/

![image](https://user-images.githubusercontent.com/18006037/60812332-24b5da80-a189-11e9-8f1e-fd0529d65d82.png)

**Comment by wojtek0806** [comment]
FMFA-291

**Comment by wojtek0806** [comment]
While the original PR had the fix, we need to run all of the tests to ensure the change would not cause regression, no functional tests or log of the tests were provided in the PR anyway

**Comment by atopuzov** [comment]
Would it make any difference if we opened a case?
Version affected:
```
Main Package
  Product     BIG-IP
  Version     12.1.2
  Build       2.0.276
  Edition     Hotfix HF2
```

**Comment by wojtek0806** [comment]
this is not needed as this is logged already, if you can share the playbook that you ran that caused this that would help

**Comment by atopuzov** [comment]
@wojtek0806 It just runs a command using `bigip_command` (could be anything in the command, eg. show sys version, as it doesn't even try to execute it as it fails to detect the prompt)

The task looks pretty much like this.
```
---
- name: Checking GeoIP lookups
  bigip_command:
    commands: run util bash -c 'geoip_lookup -f /shared/GeoIP/v2/F5GeoIPOrg.dat 65.61.115.197'
    provider:
      server: "{{ inventory_hostname }}"
      user: "{{ ansible_ssh_user }}"
      password: "{{ ansible_ssh_pass }}"
      transport: cli
      timeout: 300
  delegate_to: localhost
  register: output
```

**Comment by wojtek0806** [comment]
Your issue is with running bash commands via tmsh, i do not think this is even fully supported. I believe we amended the documentation stating as such. command module serves really as a stopgap for the missing features in the modules, i.e. running tmsh commands that relate to configuring device features, some bash commands were expect to work. I will see if we can fix this without breaking anything else.

**Comment by atopuzov** [comment]
@wojtek0806 nope it's not

This does not work either.
```
- hosts: all
  gather_facts: no
  tasks:
    - name: Version
      bigip_command:
        commands: show sys version
        provider:
          server: "{{ inventory_hostname }}"
          user: "{{ ansible_ssh_user }}"
          password: "{{ ansible_ssh_pass }}"
          transport: cli
          timeout: 30
      delegate_to: localhost
      register: output
```
