### ISSUE TITLE
bigip_gtm_topology_region doesnt remove members

### ISSUE THREAD

**Issue by markatdxb** [F5Networks/f5-ansible#1409]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

bigip_gtm_topology_region

##### ANSIBLE VERSION

```
2.8.0
```

##### PYTHON VERSION

```

```

##### BIGIP VERSION

```

```

##### ROLE VERSION

```
Role: f5devcentral.f5ansible
        description: Ansible role that allows use of the F5 Ansible Modules
        active: True
        commit: b66a4e5337d6200d94408d187ea6a7e69a8c4f20
        commit_message: Merging upstream changes - 2019-06-29T07:00:32Z
        commit_url: https://api.github.com/repos/f5devcentral/ansible-role-f5ansible
        company: F5 Networks
        created: 2018-10-04T16:14:10.510085Z
        dependencies: []
        download_count: 8777
        forks_count: 0
        galaxy_info:
                author: caphrim007
                company: F5 Networks
                galaxy_tags: ['f5', 'networking', 'bigip', 'bigiq']
                license: GPLv3
                min_ansible_version: 2.8
                platforms: [{'name': 'EL', 'versions': ['all']}, {'name': 'Fedora',
                role_name: f5ansible
        github_branch: master
        github_repo: ansible-role-f5ansible
        github_user: f5devcentral

```

##### SUMMARY

when running module with supplied list of members, it correctly adds new members, change existing members but doesnt remove members which exist in GTM but are missing on the list 
is that correct behaviour ? 

##### STEPS TO REPRODUCE

```

```

##### ACTUAL RESULTS

```

```

**Comment by focrensh** [comment]
What members within topology_region are you referring to? With most ansible modules you have to provide a state of "absent" to tell it to remove specific objects, it is not declarative in that it removes objects that are not listed. Please provide the playbook task in question along with the existing and desired state after running the playbook.

**Comment by markatdxb** [comment]
Thank you for clarification. I wasnt clear on the point  - **it is not declarative in that it removes objects that are not listed**.  Somehow i expected that behaviour.  Now im just trying to figure out how to create playbook which basically removes the objects not listed. I understand that i can create playbook with state of "absent" but the problem is that i dont know which objects should be removed. Ill try to explain .
Every week we automatically generate JSON list of subnets used in our environment - its around 180 objects. Then we run simple playbook to update GTM. 
Now if we for example remove one of the subnets from our environment  - JSON list will contain 179  objects but i have no idea which subnet was removed. So in order to keep the environment clean i would have to remove all objects and re-add all 179 newly which is not the right solution. Other possible solution could be, to have option to somehow grab fact of current objects in GTM, compare with new list and and delete the ones not  present in JSON. 
Or is there any possible solution which you would suggest ? 
```
- name: Create topology regions
      bigip_gtm_topology_region:
        name: "{{ item.f5_region }}"
        state: present
        region_members:
          - country: "{{ item.f5_country }}"
          - continent: "{{ item.f5_continent }}"
          - subnet: "{{ item.f5_ip_range }}"
        provider: "{{ provider }}"
      with_items: "{{ jsonvar }}"
      delegate_to: localhost
      when: jsonvar[0] != '[]'
      ignore_errors: yes
      register: f5_top_output
```
