### ISSUE TITLE
adding vlans to an existing collection

### ISSUE THREAD

**Issue by JeyDog** [F5Networks/f5-ansible#1415]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

- bigip_facts
- bigip_routedomain_facts
- bigip_virtual_server:
- bigip_routedomain

##### ANSIBLE VERSION

```
ansible 2.8.1
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/user/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.6/dist-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 3.6.8 (default, Jan 14 2019, 11:02:34) [GCC 8.0.1 20180414 (experimental) [trunk revision 259383]]
```

##### PYTHON VERSION

```
Python 2.7.15+
```

##### BIGIP VERSION

```
Sys::Version
Main Package
  Product     BIG-IP
  Version     14.1.0.3
  Build       0.0.6
  Edition     Point Release 3
  Date        Mon Mar 25 17:15:27 PDT 2019
```

##### ROLE VERSION

```
Role: f5devcentral.f5ansible
        description: Ansible role that allows use of the F5 Ansible Modules
        active: True
        commit: 5ec736fc5427d4fce75876a013803101bfc114e3
        commit_message: Merging upstream changes - 2019-07-16T07:00:35Z
        commit_url: https://api.github.com/repos/f5devcentral/ansible-role-f5ansible/git/commits/5ec736fc5427d4fce75876a013803101bfc114e3
        company: F5 Networks
        created: 2018-10-04T16:14:10.510085Z
        download_count: 9057
        forks_count: 0
        github_branch: master
        github_repo: ansible-role-f5ansible
        github_user: f5devcentral
        id: 30341
        imported: 2019-07-16T03:03:10.127459-04:00
        is_valid: True
        issue_tracker_url:
        license: GPLv3
        min_ansible_version: 2.8
        modified: 2019-07-16T07:03:10.133904Z
        open_issues_count: 0
        path: ('/home/user/.ansible/roles', '/usr/share/ansible/roles', '/etc/ansible/roles')
        role_type: ANS
        stargazers_count: 4
        travis_status_url: https://travis-ci.org/f5devcentral/ansible-role-f5ansible.svg?branch=master
```

##### CONFIGURATION

Standard 
##### OS / ENVIRONMENT

Ubuntu 18.04.2 
##### SUMMARY

Can't add vlans to an existing collection (e.g. adding vlan to route domain, adding vlan to forwarding vs). Existing vlans are overwritten with new ones.
##### STEPS TO REPRODUCE
Adding vlan to route domain

```
---
  - name: Basic network configuration BIG-IP A
    hosts: hostname
    gather_facts: no
    connection: local
    vars:
      bigip_vlan_information:
        - name: transfer
          tag: 402
          interface: 1.1
        - name: internal
          tag: 403
          interface: 1.1

    tasks:
      - name: Assign VLAN to Route Domain on BIG-IP A
        bigip_routedomain:
          id: "{{ routedomain }}"
          state: present
          provider: "{{ provider }}"
          vlans: "{{ item.name }}"
        tags: test
        loop: "{{ bigip_vlan_information }}"
```

Adding vlan to enabled vlans within virtual server configuration
```
---
  - name: Basic network configuration BIG-IP A
    hosts: hostname
    gather_facts: no
    connection: local

    tasks:
      - name: Add vlan to forwarding ip virtual server
        bigip_virtual_server:
          destination: "destination"
          name: "name"
          port: "port"
          enabled_vlans:
            - vlan123
          state: present
          provider: "{{ provider }}"
        tags: test2
```

##### EXPECTED RESULTS

New vlans are being added to the existing collection.
##### ACTUAL RESULTS

Existing vlans are overwritten which leads to the following error message since the default vlan can't be deleted. In case of adding a vlan to an existing virtual server (e.g. forwarding server) all existing vlans are being overwritten.
Is there a module or solution to accomplish that ? I also tried to get the current vlans as a list and attach vlans before i run this module. But i didn't found any information regarding vlans.

```
failed: [hostname] (item={'name': 'transfer', 'tag': 402, 'interface': 1.1}) => {"ansible_facts": {"discovered_interpreter_python": "/usr/bin/python"}, "ansible_loop_var": "item", "changed": false, "item": {"interface": 1.1, "name": "transfer", "tag": 402}, "msg": "01070967:3: The specified vlan, vlangroup or tunnel (/Common/http-tunnel) cannot be removed from its default route domain (/Common/0)."}
failed: [hostname] (item={'name': 'internal', 'tag': 403, 'interface': 1.1}) => {"ansible_loop_var": "item", "changed": false, "item": {"interface": 1.1, "name": "internal", "tag": 403}, "msg": "01070967:3: The specified vlan, vlangroup or tunnel (/Common/http-tunnel) cannot be removed from its default route domain (/Common/0)."}
```
