### ISSUE TITLE
bigip_snat_pool and bigip_snat_translation don't allow route domain

### ISSUE THREAD

**Issue by jmurphyau** [F5Networks/f5-ansible#1428]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

bigip_snat_pool and bigip_snat_translation

##### ANSIBLE VERSION / PYTHON VERSION

```
ansible 2.8.0
  config file = /Users/jamesmurphy/Development/GitHub/globalspeechnetworks/gsn-ansible/ansible.cfg
  configured module search path = [u'/Users/jamesmurphy/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /Library/Python/2.7/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 2.7.10 (default, Feb 22 2019, 21:55:15) [GCC 4.2.1 Compatible Apple LLVM 10.0.1 (clang-1001.0.37.14)]
```

##### BIGIP VERSION

```
[admin@mtva-gsn-ltm01:Active:In Sync] ~ # tmsh show sys version

Sys::Version
Main Package
  Product     BIG-IP
  Version     12.1.2
  Build       1.0.271
  Edition     Hotfix HF1
  Date        Fri Apr 28 20:02:07 PDT 2017
```

##### ROLE VERSION

```
> ansible-galaxy info f5devcentral.f5ansible

Role: f5devcentral.f5ansible
        description: Ansible role that allows use of the F5 Ansible Modules
        active: True
        commit: e7d140613920794d1aa2e2d9bbfb5ff0ff994b55
        commit_message: Merging upstream changes - 2019-07-23T07:00:42Z
        commit_url: https://api.github.com/repos/f5devcentral/ansible-role-f5ansible/git/commits/e7d140613920794d1aa2e2d9bbfb5ff0ff994b55
        company: F5 Networks
        created: 2018-10-04T16:14:10.510085Z
        download_count: 9410
        forks_count: 0
        github_branch: master
        github_repo: ansible-role-f5ansible
        github_user: f5devcentral
        id: 30341
        imported: 2019-07-23T03:03:23.504276-04:00
        is_valid: True
        issue_tracker_url: 
        license: GPLv3
        min_ansible_version: 2.8
        modified: 2019-07-23T07:03:23.510523Z
        open_issues_count: 0
        path: (u'/Users/jamesmurphy/Development/GitHub/globalspeechnetworks/gsn-ansible/roles',)
        role_type: ANS
        stargazers_count: 4
        travis_status_url: https://travis-ci.org/f5devcentral/ansible-role-f5ansible.svg?branch=master
```

##### SUMMARY

bigip_snat_pool and bigip_snat_translation modules do not allow route domain as part of the IP address. I'm happy to put together a PR to fix this but some advise on how you would recommend changing it would be good? Is there a function that validates an IP address WITH route domain, or should I split on the `%` symbol and validate that the first portion of the  value is a valid IP address?

##### STEPS TO REPRODUCE

```
- name: 'create snat translation'
  bigip_snat_translation:
    name: 'diffpart-rd0-1.2.3.4'
    state: present
    address: '1.2.3.4%0'
    partition: 'DiffPartition'
    traffic_group: '/Common/diffpart-site1'
  delegate_to: localhost

- name: 'create snat pool'
  bigip_snat_pool:
    name: 'diffpart-rd0-1.2.3.4'
    state: present
    member: '1.2.3.4%0'
    partition: 'DiffPartition'
  delegate_to: localhost
```

##### ACTUAL RESULTS

```

```
