### ISSUE TITLE
bigip_virtual_address server scope not set on create but changed on update

### ISSUE THREAD

**Issue by jmurphyau** [F5Networks/f5-ansible#1436]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

bigip_virtual_address

##### ANSIBLE VERSION

```
ansible 2.8.0
  config file = /Users/jamesmurphy/Development/GitHub/globalspeechnetworks/gsn-ansible/ansible.cfg
  configured module search path = [u'/Users/jamesmurphy/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /Library/Python/2.7/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 2.7.10 (default, Feb 22 2019, 21:55:15) [GCC 4.2.1 Compatible Apple LLVM 10.0.1 (clang-1001.0.37.14)]
```

##### PYTHON VERSION

```
Python 2.7.10
```

##### BIGIP VERSION

```
Sys::Version
Main Package
  Product     BIG-IP
  Version     12.1.2
  Build       1.0.271
  Edition     Hotfix HF1
  Date        Fri Apr 28 20:02:07 PDT 2017
```

##### SUMMARY

When setting up a virtual address with advertise route always it is not setup correctly. Only when running the task twice does it work.

##### STEPS TO REPRODUCE

Task:
```
bigip_virtual_address:
  name: /ABC/abc-rd23-172.16.10.100
  address: 172.16.10.100
  route_domain: 23
  traffic_group: /Common/abc-mel
  partition: ABC
  route_advertisement: enabled
  availability_calculation: always
  auto_delete: no
```
tmsh output after first run (create):
```
ltm virtual-address /ABC/abc-rd23-172.16.10.100 {
    address 172.16.10.100%23
    auto-delete false
    mask 255.255.255.255
    partition ABC
    route-advertisement enabled
    traffic-group abc-mel
    unit 4
}
```
tmsh output after second run (update):
```
ltm virtual-address /ABC/abc-rd23-172.16.10.100 {
    address 172.16.10.100%23
    auto-delete false
    mask 255.255.255.255
    partition ABC
    route-advertisement enabled
    server-scope none
    traffic-group abc-mel
    unit 4
}
```
