### ISSUE TITLE
Error while adding bigip ltm pool - when using quorum for monitor type "m_of_n"

### ISSUE THREAD

**Issue by payalsin** [F5Networks/f5-ansible#145]
used the bigip_pool2.py code 

Seeing an issue:

failed: [10.192.73.218 -> localhost] (item={u'host': u'192.168.76.76', u'port': 443}) => {"failed": true, "item": {"host": "192.168.76.76", "port": 443}, "module_stderr": "/usr/lib/python2.7/site-packages/requests/packages/urllib3/connectionpool.py:852: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings\n  InsecureRequestWarning)\n/usr/lib/python2.7/site-packages/requests/packages/urllib3/connectionpool.py:852: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings\n  InsecureRequestWarning)\n/usr/lib/python2.7/site-packages/requests/packages/urllib3/connectionpool.py:852: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings\n  InsecureRequestWarning)\nTraceback (most recent call last):\n  File \"/tmp/ansible_NnUlXU/ansible_module_bigip_pool.py\", line 631, in <module>\n    main()\n  File \"/tmp/ansible_NnUlXU/ansible_module_bigip_pool.py\", line 625, in main\n    results = mm.exec_module()\n  File \"/tmp/ansible_NnUlXU/ansible_module_bigip_pool.py\", line 377, in exec_module\n    changed = self.present()\n  File \"/tmp/ansible_NnUlXU/ansible_module_bigip_pool.py\", line 426, in present\n    return self.create()\n  File \"/tmp/ansible_NnUlXU/ansible_module_bigip_pool.py\", line 460, in create\n    self._set_changed_options()\n  File \"/tmp/ansible_NnUlXU/ansible_module_bigip_pool.py\", line 391, in _set_changed_options\n    if getattr(self.want, key) is not None:\n  File \"/tmp/ansible_NnUlXU/ansible_module_bigip_pool.py\", line 298, in monitor\n    prefix = 'min {0} of {'.format(str(quorum))\nValueError: Single '{' encountered in format string\n", "module_stdout": "", "msg": "MODULE FAILURE", "rc": 0}

Playbook:
```
- name: Add Pool
    bigip_pool:
      server: "10.192.73.218"
      user: "admin"
      password: "admin"
      state: "present"
      name: "http-pool"
      partition: "Common"
      lb_method: "round_robin"
      monitors: ['http','tcp']
      monitor_type: "m_of_n"
      quorum: 2
      host: "{{item.host}}"
      port: "{{item.port}}"
      validate_certs: False
    with_items:
    - host: "192.168.78.78"
      port: 80
    - host: "192.168.76.76"
      port: 443
    delegate_to: localhost
```

**Comment by wojtek0806** [comment]
Is this a new pool or existing pool? @payalsin

**Comment by wojtek0806** [comment]
While I look into this issue, there are few comments on this playbook first:

 - When specifying monitors you need to provide full path i.e /Common/http, /Common/tcp etc.
 
- The pool has to exist before you can add the pool members, i mean you would have to run this playbook twice to get the results you expect. 

The reason for it, is that it is how the object would be created in REST. First you create a pool and then using pool object URI as a reference, you call on its sub-collection (pool members) to create objects there. So creating pool with members results in 2 REST calls. Also this is how it has been in the old SOAP based module before, so the behavior of the module has not changed.

**Comment by wojtek0806** [comment]
@payalsin pr has been submitted, waiting for @caphrim007 approval

**Comment by payalsin** [comment]
@wojtek0806 - ok thanks will correct my playbook after the fix is commited..thx

**Comment by caphrim007** [comment]
@wojtek0806 you should not need to specify the partition as part of the monitor.

The behavior that should happen is the following

* if they specify the full path, then use the full path
* if they do not specify a partition in the monitor path, then use the partition that you get for free at self.want.partition

This is the same behavior that should be used everywhere that requires a full path.

**Comment by wojtek0806** [comment]
i have went by what we had in SOAP module, also docstrings state that partition is needed, so yeah :)

**Comment by wojtek0806** [comment]
Quotation from bigip_pool.py:

```
monitors:
    description:
      - Monitor template name list. Always use the full path to the monitor.
    version_added: "1.3"

````
