### ISSUE TITLE
bigip_virtual_server drops route domain on modify

### ISSUE THREAD

**Issue by mojr13** [F5Networks/f5-ansible#1456]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

bigip_virtual_server

##### ANSIBLE VERSION

```
ansible 2.8.3
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/slsp.sk/414292/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, Jun 11 2019, 12:19:05) [GCC 4.8.5 20150623 (Red Hat 4.8.5-36)]
```

##### PYTHON VERSION

```
Python 2.7.5
```

##### BIGIP VERSION

```
Sys::Version
Main Package
  Product     BIG-IP
  Version     14.1.2
  Build       0.0.37
  Edition     Final
  Date        Wed Aug  7 09:56:44 PDT 2019
```

##### ROLE VERSION

```
Role: f5devcentral.f5ansible
        description: Ansible role that allows use of the F5 Ansible Modules
        active: True
        commit: 34e8783728912053ae69a24e36d1e83f2d2bd8c3
        commit_message: Merging upstream changes - 2019-08-14T07:00:29Z
        commit_url: https://api.github.com/repos/f5devcentral/ansible-role-f5ansible/git/commits/34e8783728912053ae69a24e36d1e83f2d2bd8c3
        company: F5 Networks
        created: 2018-10-04T16:14:10.510085Z
        download_count: 12274
        forks_count: 1
        github_branch: master
        github_repo: ansible-role-f5ansible
        github_user: f5devcentral
        id: 30341
        imported: 2019-08-14T03:03:25.120416-04:00
        is_valid: True
        issue_tracker_url:
        license: GPLv3
        min_ansible_version: 2.8
        modified: 2019-08-14T07:03:25.127988Z
        open_issues_count: 0
        path: (u'/home/slsp.sk/414292/.ansible/roles', u'/usr/share/ansible/roles', u'/etc/ansible/roles')
        role_type: ANS
        stargazers_count: 4
        travis_status_url: https://travis-ci.org/f5devcentral/ansible-role-f5ansible.svg?branch=master
```

##### OS / ENVIRONMENT

N/A

##### SUMMARY

When modifying an existing virtual server that has route domain configured with any changes, the module drops the route domain from the virtual server.
i.e. - change profile, add irule ...

Maybe this is related to #959 , and it was not fixed in all the code?

##### STEPS TO REPRODUCE

```
Create a VS with route domain
    - name: Add virtual server
      bigip_virtual_server:
        provider:
          password: "{{ f5password }}"
          server: "10.212.152.4"
          user: "{{ f5user }}"
          validate_certs: no
        partition: "ansible"
        state: "present"
        name: "vs_test"
        destination: "1.2.3.4%2452"
        port: 80
        profiles:
          - http
      delegate_to: localhost

Modify single parameter (in example profile)
    - name: Add iRule to virtual server
      bigip_virtual_server:
        provider:
          password: "{{ f5password }}"
          server: "10.212.152.4"
          user: "{{ f5user }}"
          validate_certs: no
        partition: "ansible"
        name: "vs_test"
#        irules: "testirule"
        profiles:
          - tcp
      delegate_to: localhost

```

##### EXPECTED RESULTS

Change only the mentioned parameters and not any other parameters. Keep the route domain as is. The destination IP should be: "1.2.3.4%2452" and should not be modified.

"destination": "1.2.3.4%2452",

##### ACTUAL RESULTS

The route domain was droped and new destination IP was modifiet to "1.2.3.4"
"destination": "1.2.3.4",

```
ansible-playbook 2.8.3
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/slsp.sk/414292/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible-playbook
  python version = 2.7.5 (default, Jun 11 2019, 12:19:05) [GCC 4.8.5 20150623 (Red Hat 4.8.5-36)]
Using /etc/ansible/ansible.cfg as config file
setting up inventory plugins
host_list declined parsing /home/slsp.sk/414292/f5ansible/playbooks/hosts/hosts as it did not pass it's verify_file() method
script declined parsing /home/slsp.sk/414292/f5ansible/playbooks/hosts/hosts as it did not pass it's verify_file() method
auto declined parsing /home/slsp.sk/414292/f5ansible/playbooks/hosts/hosts as it did not pass it's verify_file() method
Parsed /home/slsp.sk/414292/f5ansible/playbooks/hosts/hosts inventory source with ini plugin
Loading callback plugin default of type stdout, v2.0 from /usr/lib/python2.7/site-packages/ansible/plugins/callback/default.pyc

PLAYBOOK: vsbug.yml *************************************************************************************************************************************************************************
Positional arguments: vsbug.yml
become_method: sudo
inventory: (u'/home/slsp.sk/414292/f5ansible/playbooks/hosts/hosts',)
forks: 5
tags: (u'all',)
verbosity: 4
connection: smart
timeout: 10
1 plays in vsbug.yml

PLAY [Modify F5 aplication] *****************************************************************************************************************************************************************
META: ran handlers

TASK [Add virtual server] *******************************************************************************************************************************************************************
task path: /home/slsp.sk/414292/f5ansible/playbooks/devel-apps/vsbug.yml:11
<localhost> connection transport is rest
<localhost> ESTABLISH LOCAL CONNECTION FOR USER: 414292@slsp.sk
<localhost> EXEC /bin/sh -c 'echo '"'"'~414292@slsp.sk'"'"' && sleep 0'
<localhost> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo ~414292@slsp.sk/.ansible/tmp/ansible-tmp-1565882882.27-100910820307291 `" && echo ansible-tmp-1565882882.27-100910820307291="` echo ~414292@slsp.sk/.ansible/tmp/ansible-tmp-1565882882.27-100910820307291 `" ) && sleep 0'
Using module file /usr/lib/python2.7/site-packages/ansible/modules/network/f5/bigip_virtual_server.py
<localhost> PUT /home/slsp.sk/414292/.ansible/tmp/ansible-local-80616p1cKuD/tmp9N8qJW TO /home/slsp.sk/414292/.ansible/tmp/ansible-tmp-1565882882.27-100910820307291/AnsiballZ_bigip_virtual_server.py
<localhost> EXEC /bin/sh -c 'chmod u+x /home/slsp.sk/414292/.ansible/tmp/ansible-tmp-1565882882.27-100910820307291/ /home/slsp.sk/414292/.ansible/tmp/ansible-tmp-1565882882.27-100910820307291/AnsiballZ_bigip_virtual_server.py && sleep 0'
<localhost> EXEC /bin/sh -c '/usr/bin/python2 /home/slsp.sk/414292/.ansible/tmp/ansible-tmp-1565882882.27-100910820307291/AnsiballZ_bigip_virtual_server.py && sleep 0'
<localhost> EXEC /bin/sh -c 'rm -f -r /home/slsp.sk/414292/.ansible/tmp/ansible-tmp-1565882882.27-100910820307291/ > /dev/null 2>&1 && sleep 0'
 [WARNING]: The value 80 (type int) in a string field was converted to u'80' (type string). If this does not look like what you expect, quote the entire value to ensure it does not change.

changed: [localhost -> localhost] => {
    "address_translation": false,
    "changed": true,
    "invocation": {
        "module_args": {
            "address_translation": null,
            "auth_provider": null,
            "clone_pools": null,
            "default_persistence_profile": null,
            "description": null,
            "destination": "1.2.3.4%2452",
            "disabled_vlans": null,
            "enabled_vlans": null,
            "fallback_persistence_profile": null,
            "firewall_enforced_policy": null,
            "firewall_staged_policy": null,
            "insert_metadata": true,
            "ip_intelligence_policy": null,
            "ip_protocol": null,
            "irules": null,
            "mask": null,
            "metadata": null,
            "mirror": null,
            "name": "vs_test",
            "partition": "ansible",
            "password": null,
            "policies": null,
            "pool": null,
            "port": "80",
            "port_translation": null,
            "profiles": [
                "http"
            ],
            "provider": {
                "auth_provider": null,
                "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
                "proxy_to": null,
                "server": "10.212.152.4",
                "server_port": null,
                "ssh_keyfile": null,
                "timeout": null,
                "transport": "rest",
                "user": "admin",
                "validate_certs": false
            },
            "rate_limit": null,
            "rate_limit_dst_mask": null,
            "rate_limit_mode": "object",
            "rate_limit_src_mask": null,
            "security_log_profiles": null,
            "security_nat_policy": null,
            "server": null,
            "server_port": null,
            "snat": null,
            "source": null,
            "source_port": null,
            "state": "present",
            "transport": null,
            "type": "standard",
            "user": null,
            "validate_certs": null
        }
    },
    "port_translation": false,
    "profiles": [
        {
            "context": "all",
            "fullPath": "/ansible/http",
            "name": "http"
        }
    ]
}

TASK [Add iRule to virtual server] **********************************************************************************************************************************************************
task path: /home/slsp.sk/414292/f5ansible/playbooks/devel-apps/vsbug.yml:27
<localhost> connection transport is rest
<localhost> ESTABLISH LOCAL CONNECTION FOR USER: 414292@slsp.sk
<localhost> EXEC /bin/sh -c 'echo '"'"'~414292@slsp.sk'"'"' && sleep 0'
<localhost> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo ~414292@slsp.sk/.ansible/tmp/ansible-tmp-1565882885.28-14963895448447 `" && echo ansible-tmp-1565882885.28-14963895448447="` echo ~414292@slsp.sk/.ansible/tmp/ansible-tmp-1565882885.28-14963895448447 `" ) && sleep 0'
Using module file /usr/lib/python2.7/site-packages/ansible/modules/network/f5/bigip_virtual_server.py
<localhost> PUT /home/slsp.sk/414292/.ansible/tmp/ansible-local-80616p1cKuD/tmpHHwjrG TO /home/slsp.sk/414292/.ansible/tmp/ansible-tmp-1565882885.28-14963895448447/AnsiballZ_bigip_virtual_server.py
<localhost> EXEC /bin/sh -c 'chmod u+x /home/slsp.sk/414292/.ansible/tmp/ansible-tmp-1565882885.28-14963895448447/ /home/slsp.sk/414292/.ansible/tmp/ansible-tmp-1565882885.28-14963895448447/AnsiballZ_bigip_virtual_server.py && sleep 0'
<localhost> EXEC /bin/sh -c '/usr/bin/python2 /home/slsp.sk/414292/.ansible/tmp/ansible-tmp-1565882885.28-14963895448447/AnsiballZ_bigip_virtual_server.py && sleep 0'
<localhost> EXEC /bin/sh -c 'rm -f -r /home/slsp.sk/414292/.ansible/tmp/ansible-tmp-1565882885.28-14963895448447/ > /dev/null 2>&1 && sleep 0'
changed: [localhost -> localhost] => {
    "address_translation": false,
    "changed": true,
    "destination": "1.2.3.4",
    "invocation": {
        "module_args": {
            "address_translation": null,
            "auth_provider": null,
            "clone_pools": null,
            "default_persistence_profile": null,
            "description": null,
            "destination": null,
            "disabled_vlans": null,
            "enabled_vlans": null,
            "fallback_persistence_profile": null,
            "firewall_enforced_policy": null,
            "firewall_staged_policy": null,
            "insert_metadata": true,
            "ip_intelligence_policy": null,
            "ip_protocol": null,
            "irules": null,
            "mask": null,
            "metadata": null,
            "mirror": null,
            "name": "vs_test",
            "partition": "ansible",
            "password": null,
            "policies": null,
            "pool": null,
            "port": null,
            "port_translation": null,
            "profiles": [
                "tcp"
            ],
            "provider": {
                "auth_provider": null,
                "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
                "proxy_to": null,
                "server": "10.212.152.4",
                "server_port": null,
                "ssh_keyfile": null,
                "timeout": null,
                "transport": "rest",
                "user": "admin",
                "validate_certs": false
            },
            "rate_limit": null,
            "rate_limit_dst_mask": null,
            "rate_limit_mode": "object",
            "rate_limit_src_mask": null,
            "security_log_profiles": null,
            "security_nat_policy": null,
            "server": null,
            "server_port": null,
            "snat": null,
            "source": null,
            "source_port": null,
            "state": "present",
            "transport": null,
            "type": "standard",
            "user": null,
            "validate_certs": null
        }
    },
    "port": 80,
    "port_translation": false,
    "profiles": [
        {
            "context": "all",
            "fullPath": "/ansible/tcp",
            "name": "tcp"
        }
    ]
}
META: ran handlers
META: ran handlers

PLAY RECAP **********************************************************************************************************************************************************************************
localhost                  : ok=2    changed=2    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0


```
