### ISSUE TITLE
Error while adding virtual server using bigip_virtual_server2.py module

### ISSUE THREAD

**Issue by payalsin** [F5Networks/f5-ansible#146]
Playbook
```
- name: VS config on BIG-IP
  hosts: bigip
  gather_facts: false

  tasks:

  - name: Add VS on BIG-IP
    bigip_virtual_server:
      server: "10.192.73.218"
      user: "admin"
      password: "admin"
      name: "httpvs"
      destination: "10.168.90.90"
      port: 80
      irules: ["irule1","irule2"]
      enabled_vlans: "all"
      pool: "VS_HTTP_pool"
      snat: "automap"
      validate_certs: False
    delegate_to: localhost
```
Error
TASK [Add VS on BIG-IP] ********************************************************************************************
fatal: [10.192.73.218 -> localhost]: FAILED! => {"changed": false, "failed": true, "module_stderr": "/usr/lib/python2.7/site-packages/requests/packages/urllib3/connectionpool.py:852: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings\n  InsecureRequestWarning)\n/usr/lib/python2.7/site-packages/requests/packages/urllib3/connectionpool.py:852: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings\n  InsecureRequestWarning)\nTraceback (most recent call last):\n  File \"/tmp/ansible_NYfQjY/ansible_module_bigip_virtual_server.py\", line 682, in <module>\n    main()\n  File \"/tmp/ansible_NYfQjY/ansible_module_bigip_virtual_server.py\", line 676, in main\n    results = mm.exec_module()\n  File \"/tmp/ansible_NYfQjY/ansible_module_bigip_virtual_server.py\", line 487, in exec_module\n    changed = self.present()\n  File \"/tmp/ansible_NYfQjY/ansible_module_bigip_virtual_server.py\", line 499, in present\n    if self.exists():\n  File \"/tmp/ansible_NYfQjY/ansible_module_bigip_virtual_server.py\", line 523, in exists\n    name=self.have.name,\nAttributeError: 'NoneType' object has no attribute 'name'\n", "module_stdout": "", "msg": "MODULE FAILURE", "rc": 0}
