### ISSUE TITLE
bigip_device_trust turns dash next to number to underscore in hostname

### ISSUE THREAD

**Issue by bookfold** [F5Networks/f5-ansible#1465]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

bigip_device_trust

##### ANSIBLE VERSION

```
ansible 2.7.8
  config file = /root/.ansible.cfg
  configured module search path = [u'/usr/lib/python2.7/dist-packages/ansible/modules/network/f5']
  ansible python module location = /root/ansible_2.7/ansible_2.7_env/lib/python2.7/site-packages/ansible
  executable location = /root/ansible_2.7/ansible_2.7_env/bin/ansible
  python version = 2.7.6 (default, Mar 22 2014, 22:59:56) [GCC 4.8.2]
```

##### PYTHON VERSION

```
Python 2.7.6
```

##### BIGIP VERSION

```
Sys::Version
Main Package
  Product     BIG-IP
  Version     14.1.2
  Build       0.0.34
  Edition     Final
  Date        Fri Aug  2 23:19:58 PDT 2019

```

##### ROLE VERSION

```
Role: f5devcentral.f5ansible
        description: Ansible role that allows use of the F5 Ansible Modules
        active: True
        commit: 5b8bbe60c05126d43b2d5a80727e2b1b98cdae14
        commit_message: Merging upstream changes - 2019-08-16T07:00:50Z
        commit_url: https://api.github.com/repos/f5devcentral/ansible-role-f5ansible/git/commits/5b8bbe60c05126d43b2d5a80727e2b1b98cdae14
        company: F5 Networks
        created: 2018-10-04T16:14:10.510085Z
        download_count: 12465
        forks_count: 1
        github_branch: master
        github_repo: ansible-role-f5ansible
        github_user: f5devcentral
        id: 30341
        imported: 2019-08-16T04:03:41.058768-04:00
        is_valid: True
        issue_tracker_url:
        license: GPLv3
        min_ansible_version: 2.8
        modified: 2019-08-16T08:03:41.065101Z
        open_issues_count: 0
        path: [u'/root/.ansible/roles', u'/usr/share/ansible/roles', u'/etc/ansible/roles']
        role_type: ANS
        stargazers_count: 4
        travis_status_url: https://travis-ci.org/f5devcentral/ansible-role-f5ansible.svg?branch=v2019.8.16

```

##### OS / ENVIRONMENT

Control machine:
Linux servitor 3.13.0-32-generic #57-Ubuntu SMP Tue Jul 15 03:51:08 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux

Host:
BIG-IP 14.1.0
##### SUMMARY
This is related to issue #664 but differs slightly in that the dash gets turned to an underscore when it appears next to a number as illustrated below.

When creating a device group, if the peer device has a number next to a dash in the hostname the dash gets turned into an underscore in the DSC name of the device.

##### STEPS TO REPRODUCE

Peer device DSC name and hostname:
list cm device hostname
cm device bigip14-1peer.lab.local {
hostname bigip14-1peer.lab.local
}

Run a playbook with bigip_device_trust to create DSC with two BIG-IPs
Playbook fails on bigip_device_group_member task when attempting to add peer device to device group due to name mismatch

device trust has been created but peer's name has been changed:
list cm device hostname
cm device bigip14-1.lab.local {
    hostname bigip14-1.lab.local
}
cm device bigip14_1peer.lab.local { <---- dash to underscore in peer
    hostname bigip14-1peer.lab.local
}

```
    - name: add trust for all peer devices in play batch
      bigip_device_trust:
        peer_server: "{{ hostvars[item].ansible_host }}"
        peer_hostname: "{{ item }}"
        peer_user: "{{ hostvars[item].bigip_username }}"
        peer_password: "{{ hostvars[item].bigip_password }}"
        provider: "{{ provider }}"
      run_once: True
      loop: "{{ ansible_play_batch }}"

    - name: create device group
      bigip_device_group:
        name: superlative_group
        provider: "{{ provider }}"
        state: present
        type: sync-failover
      run_once: True

    - name: add the hosts in the play batch to device group
      bigip_device_group_member:
        device_group: superlative_group
        name: "{{ item }}"
        provider: "{{ provider }}"
        state: present
      loop: "{{ ansible_play_batch }}"
      run_once: True

```

##### EXPECTED RESULTS

The DSC device name should be the same name as the hostname
##### ACTUAL RESULTS

The DSC device name has a underscore replace the dash
bigip14-1peer.lab.local
bigip14_1peer.lab.local

```
TASK [add the hosts in the play batch to device group] ************************************************************************************************************************************************************************************************************************
changed: [bigip14-1.lab.local] => (item=bigip14-1.lab.local)
failed: [bigip14-1.lab.local] (item=bigip14-1peer.lab.local) => {"changed": false, "item": "bigip14-1peer.lab.local", "msg": "404 Unexpected Error: Not Found for uri: https://10.154.210.209:443/mgmt/tm/cm/device-group/superlative_group/devices/\nText: u'{\"code\":404,\"message\":\"01020036:3: The requested device (bigip14-1peer.lab.local) was not found.\",\"errorStack\":[],\"apiError\":3}'"}

```
