### ISSUE TITLE
 --diff does not produce diff

### ISSUE THREAD

**Issue by erikanderson** [F5Networks/f5-ansible#1473]
##### ISSUE TYPE
 - Feature Idea

##### COMPONENT NAME

All
##### ANSIBLE VERSION

```
ansible 2.8.4
  config file = /Users/eanderson/code/ansible/ansible.cfg
  configured module search path = ['/Users/eanderson/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.7/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 3.7.4 (default, Jul  9 2019, 18:13:23) [Clang 10.0.1 (clang-1001.0.46.4)]
```

##### PYTHON VERSION

```
Python 3.7.4
```

##### BIGIP VERSION

```
Sys::Version
Main Package
  Product     BIG-IP
  Version     12.1.3.5
  Build       0.0.10
  Edition     Point Release 5
  Date        Mon May 21 17:36:20 PDT 2018
```

##### ROLE VERSION

```
Role: f5devcentral.f5ansible
        description: Ansible role that allows use of the F5 Ansible Modules
        active: True
        commit: 3c1b42c67583b42718b6916abdc4cd95d8c1c835
        commit_message: Merging upstream changes - 2019-08-24T07:00:31Z
        commit_url: https://api.github.com/repos/f5devcentral/ansible-role-f5ansible/git/commits/3c1b42c67583b42718b6916abdc4cd95d8c1c835
        company: F5 Networks

        created: 2018-10-04T16:14:10.510085Z
        download_count: 12877
        forks_count: 2
        github_branch: master
        github_repo: ansible-role-f5ansible
        github_user: f5devcentral
        id: 30341
        imported: 2019-08-24T03:03:09.617109-04:00
        is_valid: True
        issue_tracker_url:
        license: GPLv3
        min_ansible_version: 2.8
        modified: 2019-08-24T07:03:09.623354Z
        open_issues_count: 0
        path: ('/Users/eanderson/code/ansible/roles',)
        role_type: ANS
        stargazers_count: 4
        travis_status_url: https://travis-ci.org/f5devcentral/ansible-role-f5ansible.svg?branch=master
```

##### OS / ENVIRONMENT
OSX10.14.6

##### SUMMARY
Running module with `--diff` does not produce diff

##### STEPS TO REPRODUCE

```
ansible-playbook playbooks/bigip/bigip.yml -i inventories/va1/bigip/inventory.yml --check --diff
```

##### EXPECTED RESULTS

Expect to see the delta between running config and changes to be made 

##### ACTUAL RESULTS
No diff is produced

```
$ ansible-playbook playbooks/bigip/bigip.yml -i inventories/va1/bigip/inventory.yml --check --diff

PLAY [bigip] *****************************************************************************************************************************************************************************************************************************************************

TASK [Gathering Facts] *******************************************************************************************************************************************************************************************************************************************
ok: [10.108.0.11]

TASK [bigip : Modify load balancer method] ***********************************************************************************************************************************************************************************************************************
changed: [10.108.0.11 -> localhost]

PLAY RECAP *******************************************************************************************************************************************************************************************************************************************************
10.108.0.11                : ok=2    changed=1    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0
```
With -vvv
```
ansible-playbook 2.8.4
  config file = /Users/eanderson/code/ansible/ansible.cfg
  configured module search path = ['/Users/eanderson/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.7/site-packages/ansible
  executable location = /usr/local/bin/ansible-playbook
  python version = 3.7.4 (default, Jul  9 2019, 18:13:23) [Clang 10.0.1 (clang-1001.0.46.4)]
Using /Users/eanderson/code/ansible/ansible.cfg as config file
host_list declined parsing /Users/eanderson/code/ansible/inventories/va1/bigip/inventory.yml as it did not pass it's verify_file() method
script declined parsing /Users/eanderson/code/ansible/inventories/va1/bigip/inventory.yml as it did not pass it's verify_file() method
Parsed /Users/eanderson/code/ansible/inventories/va1/bigip/inventory.yml inventory source with yaml plugin

PLAYBOOK: bigip.yml **********************************************************************************************************************************************************************************************************************************************
1 plays in playbooks/bigip/bigip.yml

PLAY [bigip] *****************************************************************************************************************************************************************************************************************************************************

TASK [Gathering Facts] *******************************************************************************************************************************************************************************************************************************************
task path: /Users/eanderson/code/ansible/playbooks/bigip/bigip.yml:3
<10.108.0.11> Attempting python interpreter discovery
<10.108.0.11> ESTABLISH LOCAL CONNECTION FOR USER: eanderson
<10.108.0.11> EXEC /bin/sh -c 'echo PLATFORM; uname; echo FOUND; command -v '"'"'/usr/bin/python'"'"'; command -v '"'"'python3.7'"'"'; command -v '"'"'python3.6'"'"'; command -v '"'"'python3.5'"'"'; command -v '"'"'python2.7'"'"'; command -v '"'"'python2.6'"'"'; command -v '"'"'/usr/libexec/platform-python'"'"'; command -v '"'"'/usr/bin/python3'"'"'; command -v '"'"'python'"'"'; echo ENDFOUND && sleep 0'
<10.108.0.11> Python interpreter discovery fallback (unsupported platform for extended discovery: darwin)
Using module file /usr/local/lib/python3.7/site-packages/ansible/modules/system/setup.py
Pipelining is enabled.
<10.108.0.11> EXEC /bin/sh -c '/usr/bin/python && sleep 0'
ok: [10.108.0.11]
META: ran handlers

TASK [bigip : Modify load balancer method] ***********************************************************************************************************************************************************************************************************************
task path: /Users/eanderson/code/ansible/roles/bigip/tasks/main.yml:15
Using module file /usr/local/lib/python3.7/site-packages/ansible/modules/network/f5/bigip_pool.py
Pipelining is enabled.
<localhost> ESTABLISH LOCAL CONNECTION FOR USER: eanderson
<localhost> EXEC /bin/sh -c '/usr/local/opt/python/bin/python3.7 && sleep 0'
changed: [10.108.0.11 -> localhost] => {
    "changed": true,
    "invocation": {
        "module_args": {
            "aggregate": null,
            "auth_provider": null,
            "description": null,
            "lb_method": "predictive-node",
            "metadata": null,
            "monitor_type": null,
            "monitors": null,
            "name": "biz_hst_preprd_3443",
            "partition": "Common",
            "password": null,
            "priority_group_activation": null,
            "provider": {
                "auth_provider": null,
                "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
                "proxy_to": null,
                "server": "10.108.0.11",
                "server_port": 443,
                "ssh_keyfile": null,
                "timeout": null,
                "transport": "rest",
                "user": "ansible",
                "validate_certs": false
            },
            "quorum": null,
            "replace_all_with": false,
            "reselect_tries": null,
            "server": null,
            "server_port": null,
            "service_down_action": null,
            "slow_ramp_time": null,
            "state": "present",
            "transport": null,
            "user": null,
            "validate_certs": null
        }
    },
    "lb_method": "predictive-node",
    "partition": "Common"
}
META: ran handlers
META: ran handlers

PLAY RECAP *******************************************************************************************************************************************************************************************************************************************************
10.108.0.11                : ok=2    changed=1    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0   

```
