### ISSUE TITLE
change examples to use source not file parameter

### ISSUE THREAD

**Issue by lm-sig** [F5Networks/f5-ansible#1482]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

bigip_asm_policy_import

##### ANSIBLE VERSION

```
ansible 2.8.4
  config file = /cygdrive/c/Users/foo/Projects/git/ansible.cfg
  configured module search path = ['/cygdrive/c/Users/foo/Projects/git/custom_modules']
  ansible python module location = /usr/lib/python3.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 3.7.4 (default, Jul 21 2019, 14:43:25) [GCC 7.4.0]
```

##### PYTHON VERSION

```
Python 3.7.4
```

##### BIGIP VERSION

```
Sys::Version
Main Package
  Product     BIG-IP
  Version     13.1.3
  Build       0.0.6
  Edition     Final
  Date        Fri Aug  2 20:39:15 PDT 2019
```

##### ROLE VERSION

```
Role: f5devcentral.f5ansible
        description: Ansible role that allows use of the F5 Ansible Modules
        active: True
        commit: 211ec1db11b62626e50bc1ccc16cf8686fe4ebcc
        commit_message: Merging upstream changes - 2019-09-09T07:00:51Z
        commit_url: https://api.github.com/repos/f5devcentral/ansible-role-f5ansible/git/commits/211ec1db11b6262>
        company: F5 Networks
        created: 2018-10-04T16:14:10.510085Z
        download_count: 13290
        forks_count: 2
        github_branch: master
        github_repo: ansible-role-f5ansible
        github_user: f5devcentral
        id: 30341
        imported: 2019-09-09T03:03:50.829899-04:00
        is_valid: True
        issue_tracker_url:
        license: GPLv3
        min_ansible_version: 2.8
        modified: 2019-09-09T07:03:50.836236Z
        open_issues_count: 0
        path: ('/home/foo/.ansible/roles', '/usr/share/ansible/roles', '/etc/ansible/roles')
        role_type: ANS
        stargazers_count: 5
        travis_status_url: https://travis-ci.org/f5devcentral/ansible-role-f5ansible.svg?branch=master
```

##### OS / ENVIRONMENT

N/A

##### SUMMARY

I am trying to import an ASM XML file into an F5 provisioned for ASM. The import is successful, but the policy is loaded into "/Common" instead of the custom partition I specified.

##### STEPS TO REPRODUCE

```
- name: Import policy
  bigip_asm_policy_import:
    name: "my_policy"
    inline: "{{ lookup('file', 'files/my_policy.xml') }}"
    partition: "My_Partition"
    provider: "{{ f5_provider }}"
```

##### EXPECTED RESULTS

Policy is imported into /My_Partition/my_policy

##### ACTUAL RESULTS

Policy is imported into /Common/my_policy

```
The output is far too large to put here and it has proprietary IP.
```
