### ISSUE TITLE
module bigip_firewall_rule not reading VARS from external files

### ISSUE THREAD

**Issue by arko95** [F5Networks/f5-ansible#1514]
##### ISSUE TYPE

  - Documentation Report

##### COMPONENT NAME

- bigip_firewall_rule:
##### ANSIBLE VERSION

```
ansible 2.8.5
  config file = /Users/pedro.carvalho/GitlabRepos/ansible-f5-firewall-rules/ansible.cfg
  configured module search path = ['/Users/pedro.carvalho/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.7/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 3.7.3 (default, Mar 27 2019, 09:23:15) [Clang 10.0.1 (clang-1001.0.46.3)]
```

##### PYTHON VERSION

```
Python 3.7.3
```

##### BIGIP VERSION

```
Sys::Version
Main Package
  Product     BIG-IP
  Version     13.1.3
  Build       0.0.6
  Edition     Final
  Date        Fri Aug  2 20:39:15 PDT 2019
```

##### CONFIGURATION

```
inventory = hosts
host_key_checking = False
retry_files_enabled = False
interpreter_python = auto_legacy_silent
```
##### OS / ENVIRONMENT

Mac OS Mojave 10.14.6

##### SUMMARY

Executing playbook with module bigip_firewall_rule and his variables works well, but if put the variables in external files, no change are applied on the BigIP with no errors. 
It doesn´t happens with others modules like bigip_firewall_address-list
##### STEPS TO REPRODUCE

```
Playbook that work fines 
- hosts: paris_f5
  connection: local
  gather_facts: no
  
  tasks:

  - name: Create a new rule in rule-list RULES_TO_DB
    bigip_firewall_rule:
      name: Test
      description: "this is a test"
      parent_rule_list: RULES_TO_DB
      protocol: tcp
      source:
        - address_list: test1
        - port_list: SSH
      destination:
        - address_list: test2
        - port_list: HTTP
      action: accept
      logging: no
      state: present
      provider:
        password: "{{ f5_bigip_password }}"
        server: "{{ inventory_hostname }}"
        user: "{{ f5_bigip_username }}"
        validate_certs: no
    delegate_to: localhost
```
```
Playbook that doesn apply change but show any errors
- hosts: paris_f5
  connection: local
  gather_facts: no
  vars_files: 
   - "policies/rules_to_DB.yml"

  tasks:

  - name: Create a new rule in rule-list RULES_TO_DB
    bigip_firewall_rule:
      name: "{{ rule_name }}"
      description: "{{ description }}"
      parent_rule_list: RULES_TO_DB
      protocol: "{{ protocol }}"
      source:
        - address_list: "{{ src_address_list }}"
        - port_list: "{{ src_port_list }}"
      destination:
        - address_list: "{{ dst_address_list }}"
        - port_list: "{{ dst_address_list }}"
      action: "{{ decision }}"
      logging: "{{ logging }}"
      state: "{{ state }}"
      provider:
        password: "{{ f5_bigip_password }}"
        server: "{{ inventory_hostname }}"
        user: "{{ f5_bigip_username }}"
        validate_certs: no
    delegate_to: localhost
```
```
VAR Files for second playbook
- rule_name: "Permit_rule_of_test"
  description: "INFRA-xxxx:  This is a test rule"
  protocol: tcp       #could be protocol name or numeric value, and any for all protocols
  src_address_list:  "test1"                                                       
  src_port_list: "TEST_PORT"
  dst_address_list: "test2"
  dst_port_list : "SSH"
  decision: accept      # set variable to reject for deny 
  logging: no         # set variable to yes to log 
  state: present    #set variable to absent for delete object
```

##### EXPECTED RESULTS

In the second playbook we expect the rule create with Variables in external files
##### ACTUAL RESULTS

Rule not created 

```
ansible-playbook 2.8.5
  config file = /Users/pedro.carvalho/GitlabRepos/ansible-f5-firewall-rules/ansible.cfg
  configured module search path = ['/Users/pedro.carvalho/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.7/site-packages/ansible
  executable location = /usr/local/bin/ansible-playbook
  python version = 3.7.3 (default, Mar 27 2019, 09:23:15) [Clang 10.0.1 (clang-1001.0.46.3)]
Using /Users/pedro.carvalho/GitlabRepos/ansible-f5-firewall-rules/ansible.cfg as config file
host_list declined parsing /Users/pedro.carvalho/GitlabRepos/ansible-f5-firewall-rules/hosts as it did not pass it's verify_file() method
script declined parsing /Users/pedro.carvalho/GitlabRepos/ansible-f5-firewall-rules/hosts as it did not pass it's verify_file() method
auto declined parsing /Users/pedro.carvalho/GitlabRepos/ansible-f5-firewall-rules/hosts as it did not pass it's verify_file() method
Parsed /Users/pedro.carvalho/GitlabRepos/ansible-f5-firewall-rules/hosts inventory source with ini plugin

PLAYBOOK: backup-playbook.yml ************************************************************************************************************************
1 plays in backup-playbook.yml
Read vars_file 'policies/rules_to_DB.yml'
Read vars_file 'policies/rules_to_DB.yml'
Read vars_file 'policies/rules_to_DB.yml'

PLAY [paris_f5] **************************************************************************************************************************************
META: ran handlers
Read vars_file 'policies/rules_to_DB.yml'
Read vars_file 'policies/rules_to_DB.yml'

TASK [Create a new rule in rule-list RULES_TO_DB] ****************************************************************************************************
task path: /Users/pedro.carvalho/GitlabRepos/ansible-f5-firewall-rules/backup-playbook.yml:11
<localhost> ESTABLISH LOCAL CONNECTION FOR USER: pedro.carvalho
<localhost> EXEC /bin/sh -c 'echo ~pedro.carvalho && sleep 0'
<localhost> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /Users/pedro.carvalho/.ansible/tmp/ansible-tmp-1570621648.167685-184073134277028 `" && echo ansible-tmp-1570621648.167685-184073134277028="` echo /Users/pedro.carvalho/.ansible/tmp/ansible-tmp-1570621648.167685-184073134277028 `" ) && sleep 0'
Using module file /usr/local/lib/python3.7/site-packages/ansible/modules/network/f5/bigip_firewall_rule.py
<localhost> PUT /Users/pedro.carvalho/.ansible/tmp/ansible-local-82491lw1tflds/tmpsb7c_rxm TO /Users/pedro.carvalho/.ansible/tmp/ansible-tmp-1570621648.167685-184073134277028/AnsiballZ_bigip_firewall_rule.py
<localhost> EXEC /bin/sh -c 'chmod u+x /Users/pedro.carvalho/.ansible/tmp/ansible-tmp-1570621648.167685-184073134277028/ /Users/pedro.carvalho/.ansible/tmp/ansible-tmp-1570621648.167685-184073134277028/AnsiballZ_bigip_firewall_rule.py && sleep 0'
<localhost> EXEC /bin/sh -c '/usr/local/opt/python/bin/python3.7 /Users/pedro.carvalho/.ansible/tmp/ansible-tmp-1570621648.167685-184073134277028/AnsiballZ_bigip_firewall_rule.py && sleep 0'
<localhost> EXEC /bin/sh -c 'rm -f -r /Users/pedro.carvalho/.ansible/tmp/ansible-tmp-1570621648.167685-184073134277028/ > /dev/null 2>&1 && sleep 0'
changed: [par3-fw-afm1a.par3.odigeo.com -> localhost] => {
    "changed": true,
    "invocation": {
        "module_args": {
            "action": "accept",
            "auth_provider": null,
            "description": "INFRA-xxxx:  This is a test rule",
            "destination": [
                {
                    "address": null,
                    "address_list": "test2",
                    "address_range": null,
                    "country": null,
                    "port": null,
                    "port_list": null,
                    "port_range": null
                },
                {
                    "address": null,
                    "address_list": null,
                    "address_range": null,
                    "country": null,
                    "port": null,
                    "port_list": "test2",
                    "port_range": null
                }
            ],
            "icmp_message": null,
            "irule": null,
            "logging": false,
            "name": "Permit_rule_of_test",
            "parent_policy": null,
            "parent_rule_list": "RULES_TO_DB",
            "partition": "Common",
            "password": null,
            "protocol": "tcp",
            "provider": {
                "auth_provider": null,
                "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
                "proxy_to": null,
                "server": "par3-fw-afm1a.par3.odigeo.com",
                "server_port": null,
                "ssh_keyfile": null,
                "timeout": null,
                "transport": "rest",
                "user": "bcnpsscripts",
                "validate_certs": false
            },
            "rule_list": null,
            "schedule": null,
            "server": null,
            "server_port": null,
            "source": [
                {
                    "address": null,
                    "address_list": "test1",
                    "address_range": null,
                    "country": null,
                    "port": null,
                    "port_list": null,
                    "port_range": null,
                    "vlan": null
                },
                {
                    "address": null,
                    "address_list": null,
                    "address_range": null,
                    "country": null,
                    "port": null,
                    "port_list": "TEST_PORT",
                    "port_range": null,
                    "vlan": null
                }
            ],
            "state": "present",
            "status": null,
            "transport": null,
            "user": null,
            "validate_certs": null
        }
    },
    "irule": null,
    "logging": "no",
    "protocol": "tcp"
}
META: ran handlers
META: ran handlers

PLAY RECAP *******************************************************************************************************************************************
par3-fw-afm1a.par3.odigeo.com : ok=1    changed=1    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0
```
