### ISSUE TITLE
Allow AFM policy for bigip_selfip

### ISSUE THREAD

**Issue by lucytang2017us** [F5Networks/f5-ansible#1527]
##### ISSUE TYPE

 - Feature Idea

##### COMPONENT NAME

bigip_firewall_xxxx modules

##### ANSIBLE VERSION

```
2.7.x
```

##### PYTHON VERSION

```
2.7
```

##### BIGIP VERSION

```
13.x
```

##### OS / ENVIRONMENT

Redhat Linux
##### SUMMARY

-- Couldn't find module/option for enforcing policies at other levels (route-domain, self-ip, virtual, etc) besides 'global' level policies
-- In reality, a rule creation may only require only the source/destination or only the address/port lists, for instance, a rule only requires source port in definition, the bigip_firewall_rule module should be able to fill default value as needed, or allow value "Any". Currently not flexible in utilization.

##### STEPS TO REPRODUCE

```
    - name: Task 7a - Create address lists for domains
      bigip_firewall_address_list:
        partition: "{{ item.partition }}"
        name: "{{ item.name }}"
        description: "{{ item.desc }}"
        addresses: "{{ item.list }}"
       provider: "{{ provider }}"
      with_items: "{{ domain_fwaddrlist_group_primary }}"
      when: inventory_hostname in groups['master']
      delegate_to: localhost
      tags: domain_addr_list

    - name: Task 7b - Create port lists for domains
      bigip_firewall_port_list:
        partition: "{{ item.partition }}"
        name: "{{ item.name }}"
        description: "{{ item.desc }}"
        ports: "{{ item.list }}"
        provider: "{{ provider }}"
      with_items: "{{ domain_fwportlist_group_primary }}"
      when: inventory_hostname in groups['master']
      delegate_to: localhost
      tags: domain_port_list

    - name: Task 7c - Create policies for domains
      bigip_firewall_policy:
        partition: "{{ item.partition }}"
        name: "{{ item.name }}"
        description: "{{ item.desc }}"
        provider: "{{ provider }}"
      with_items: "{{ domain_fwpolicy_group_primary }}"
      when: inventory_hostname in groups['master']
      delegate_to: localhost
      tags: domain_policy_list

    - name: Task 7d - Create rules for domains
      bigip_firewall_rule:
        partition: "{{ item.partition }}"
        name: "{{ item.name }}"
        description: "{{ item.desc }}"
        protocol: "{{ item.ip_protocol }}"
        source:
           - address_list: "{{ item.address_lists_src }}"
           - port_list: "{{ item.port_lists_src }}"
        destination:
           - address_list: "{{ item.address_lists_dst }}"
           - port_list: "{{ item.port_lists_dst }}"
        action: "{{ item.action }}"
        parent_policy: "{{ item.parent_policy }}"
        provider: "{{ provider }}"
      with_items: "{{ domain_fwrule_group_primary }}"
      when: inventory_hostname in groups['master']
      delegate_to: localhost
      tags: domain_rule_list

    - pause:
        minutes: 1

    - name: Task 7e - Enforce policieis
      raw: "tmsh modify net route-domain /{{ item.partition }}/{{ item.domain }} fw-enforced-policy /{{ item.partition }}/{{ item.name }}"
      with_items: "{{ domain_fwpolicy_group_primary }}"
     when: inventory_hostname in groups['master']
      tags: domain_enforce_policy_list

    - name: Task 7f - Save config file
      raw: "tmsh save sys config partitions all"
      tags: save_conf

*************************************************************************
Variables referenced by above tasks are defined in the following format:

domain_fwaddrlist_group_primary:
  - { partition: 'EDN', name: 'ADMIN-DESKTOP-2001.4888.A600-TEST', desc: 'Imported F5 Address List', list: '2001:4888:a600::,2001:4888:a622::' }
  - { partition: 'EDN', name: 'All-CiscoWorks-Test', desc: 'Imported F5 Address List', list: '198.226.102.37,198.226.102.38,198.226.102.39,198.226.102.43,198.226.102.44,199.74.155.180,199.74.155.190' }

domain_fwportlist_group_primary:
  - { partition: 'EDN', name: 'SNMP-udp-destination-destination-udp-test', desc: 'Imported F5 port List', list: '161' }
  - { partition: 'EDN', name: 'UDP_Traceroute-udp-destination-destination-udp-test', desc: 'Generated from F5 port list', list: '33434,33523' }

domain_fwpolicy_group_primary:
  - { partition: 'EDN', domain: 'edn', name: 'ALL-WGW-EDN-TEST', desc: 'Generated a EDN domain policy' }
  - { partition: 'WSN', domain: 'wsn', name: 'ONLY-WGW-TEST', desc: 'Generated a WSN domain policy' }

domain_fwrule_group_primary:
  - { partition: 'EDN', name: '_EDN_Domain_ID-4001-F5-DMW-TEST', desc: 'IPv6 rule requested by R. Solano 7/9/14', ip_protocol: 'udp', address_lists_src: '/EDN/All-CiscoWorks-Test', port_lists_src: '/EDN/UDP_Traceroute-udp-destination-destination-udp-test', address_lists_dst: '/EDN/ADMIN-DESKTOP-2001.4888.A600-TEST', port_lists_dst: '/EDN/SNMP-udp-destination-destination-udp-test', action: 'accept-decisively', parent_policy: 'ALL-WGW-EDN-TEST' }
  - { partition: 'EDN', name: '_EDN_Domain_ID-4002-F5-DMW-TEST', desc: 'IPv6 rule requested by R. Solano 7/9/14', ip_protocol: 'tcp', address_lists_src: '/EDN/All-CiscoWorks-Test', port_lists_src: '/EDN/UDP_Traceroute-udp-destination-destination-udp-test', address_lists_dst: '/EDN/ADMIN-DESKTOP-2001.4888.A600-TEST', port_lists_dst: '/EDN/SNMP-udp-destination-destination-udp-test', action: 'accept-decisively', parent_policy: 'ALL-WGW-EDN-TEST' }

```

##### EXPECTED RESULTS

-- Task 7e is just a workaround with tmsh command, looking for module/option for the policy enforcement at route-domain and other levels besides 'global' level
-- Have to define the addr/port lists for both source/destination in the variables and playbook create rule task, value 'any' or '' won't work, less flexible when utilizing the bigip_firewall_rule module

##### ACTUAL RESULTS

```

```
