### ISSUE TITLE
bigip_command: bash unexpected argument

### ISSUE THREAD

**Issue by anudeepmk** [F5Networks/f5-ansible#1570]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
bigip_command

##### ANSIBLE VERSION
```
ansible 2.9.0
  config file = /Users/myuser/.ansible.cfg
  configured module search path = ['/Users/myuser/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/Cellar/ansible/2.9.0/libexec/lib/python3.7/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 3.7.5 (default, Nov  1 2019, 02:16:32) [Clang 11.0.0 (clang-1100.0.33.8)]

f5-sdk==3.0.21

```

##### PYTHON VERSION

```
Python 3.7.5
```

##### BIGIP VERSION

```
BIG-IP 12.1.2 Build 2.0.276 Hotfix HF2
```

##### OS / ENVIRONMENT
MacOS Mojave 10.14.6

##### SUMMARY
Unable to run any of the bigip_command , always results in ""msg": "\"bash\" unexpected argument"", Even though I pass the server stats under **provider** section or on the fly under that task.
My access on the F5 server is **manager**

I am in the process of automating disabling enabling nodes on F5 based on active members in pool.
I want to do something like **show ltm node** but I am unable to run any of the commands 

##### STEPS TO REPRODUCE
not sure

```
    - name: Check node status
      bigip_command:
        commands:
          - show sys version
          - list ltm virtual
        provider:
          server: myf5server.domain.com
          password: mypass
          user: myuser
          validate_certs: no
      register: result  
      delegate_to: localhost 
      tags:
        - nodestatus
```

##### EXPECTED RESULTS

Show the commands output

##### ACTUAL RESULTS
```
fatal: [localhost -> localhost]: FAILED! => {
    "changed": false,
    "invocation": {
        "module_args": {
            "chdir": null,
            "commands": [
                "show sys version",
                "list ltm virtual"
            ],
            "interval": 1,
            "match": "all",
            "provider": {
                "auth_provider": null,
                "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
                "server": "myf5server.domain.com",
                "server_port": null,
                "ssh_keyfile": null,
                "timeout": null,
                "transport": "rest",
                "user": "myuser",
                "validate_certs": false
            },
            "retries": 10,
            "transport": "rest",
            "wait_for": null,
            "warn": true
        }
    },
    "msg": "\"bash\" unexpected argument"
}
```

```

```
