### ISSUE TITLE
bigip_device_auth_ldap not setting ca_cert, client-cert, or client_key,

### ISSUE THREAD

**Issue by lorinwyatt** [F5Networks/f5-ansible#1590]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME
bigip_device_auth_ldap

##### ANSIBLE VERSION

```
ansible 2.9.2
```

##### PYTHON VERSION

```
Python 2.7.16
```

##### BIGIP VERSION

```
Sys::Version
Main Package
  Product     BIG-IP
  Version     15.0.1
  Build       0.0.11
  Edition     Final
  Date        Fri Aug  2 21:38:03 PDT 2019
```

##### CONFIGURATION

N/A
##### OS / ENVIRONMENT

MAC OS
##### SUMMARY

When setting the ca_cert, client-cert, or client_key parameters it does not change them. It does not see that it needs to change them although the current values are different.
##### STEPS TO REPRODUCE

```
  tasks:
    - name: Change Cert Values
      bigip_device_auth_ldap:
        client_cert: default.crt
        client_key: defaul.key
        ca_cert: default.crt
        provider: "{{ provider }}"
      delegate_to: localhost
```

##### EXPECTED RESULTS

To se the SSL CA Certificate, SSL Client Certificate, and SSL Client Key in user authentication.
##### ACTUAL RESULTS

```
TASK [Change Cert Values] ********************************************************************************************************************
task path: /Users/foo/Documents/repos/f5-ansible/Device_Mgmt/test.yaml:18
<localhost> connection transport is rest
<localhost> ESTABLISH LOCAL CONNECTION FOR USER: foo
<localhost> EXEC /bin/sh -c 'echo ~foo && sleep 0'
<localhost> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /Users/foo/.ansible/tmp/ansible-tmp-1575746515.810401-94208646483665 `" && echo ansible-tmp-1575746515.810401-94208646483665="` echo /Users/foo/.ansible/tmp/ansible-tmp-1575746515.810401-94208646483665 `" ) && sleep 0'
Using module file /usr/local/Cellar/ansible/2.9.2/libexec/lib/python3.7/site-packages/ansible/modules/network/f5/bigip_device_auth_ldap.py
<localhost> PUT /Users/foo/.ansible/tmp/ansible-local-83681ayjkn6m5/tmpp6xqppzs TO /Users/foo/.ansible/tmp/ansible-tmp-1575746515.810401-94208646483665/AnsiballZ_bigip_device_auth_ldap.py
<localhost> EXEC /bin/sh -c 'chmod u+x /Users/foo/.ansible/tmp/ansible-tmp-1575746515.810401-94208646483665/ /Users/foo/.ansible/tmp/ansible-tmp-1575746515.810401-94208646483665/AnsiballZ_bigip_device_auth_ldap.py && sleep 0'
<localhost> EXEC /bin/sh -c '/usr/local/Cellar/ansible/2.9.2/libexec/bin/python3.7 /Users/foo/.ansible/tmp/ansible-tmp-1575746515.810401-94208646483665/AnsiballZ_bigip_device_auth_ldap.py && sleep 0'
<localhost> EXEC /bin/sh -c 'rm -f -r /Users/foo/.ansible/tmp/ansible-tmp-1575746515.810401-94208646483665/ > /dev/null 2>&1 && sleep 0'
ok: [10.15.193.111 -> localhost] => {
    "changed": false,
    "invocation": {
        "module_args": {
            "bind_dn": null,
            "bind_password": null,
            "ca_cert": "default.crt",
            "check_member_attr": null,
            "client_cert": "default.crt",
            "client_key": "default.key",
            "fallback_to_local": null,
            "login_ldap_attr": null,
            "port": null,
            "provider": {
                "auth_provider": null,
                "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
                "server": "1.1.1.1",
                "server_port": 443,
                "ssh_keyfile": null,
                "timeout": null,
                "transport": "rest",
                "user": "admin",
                "validate_certs": false
            },
            "remote_directory_tree": null,
            "scope": null,
            "servers": null,
            "ssl": null,
            "state": "present",
            "update_password": "always",
            "user_template": null,
            "validate_certs": null
        }
    }
}
META: ran handlers
META: ran handlers

PLAY RECAP ***********************************************************************************************************************************
1.1.1.1              : ok=2    changed=0    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0
```

**Comment by lorinwyatt** [comment]
Work Around:
````
  tasks:
    - name: Set ldap cert values workaround
      bigip_command:
        commands: 
          - "modify auth ldap all ssl-ca-cert-file default.crt ssl-client-key default.key ssl-client-cert default.crt "
        provider: "{{ provider }}"
````

**Comment by wojtek0806** [comment]
FMFA-416

**Comment by wojtek0806** [comment]
@lorinwyatt are the names of the files the same, what is the config prior to the module run?, run tmsh list  command to display the config before/after the module is run. The reason I am asking this is that I have fixed a number of issues while testing this module with v15 of TMOS, and rerun all functional tests we have and this was not encountered.

**Comment by wojtek0806** [comment]
@lorinwyatt the issue does not exist, the ssl updates fine:

```
before first task:

root@(v15-ansible)(cfg-sync Standalone)(Active)(/Common)(tmos)# list auth ldap all-properties
auth ldap system-auth {
    app-service none
    bind-dn none
    bind-pw none
    bind-timeout 30
    check-host-attr disabled
    check-roles-group disabled
    debug disabled
    description none
    filter none
    group-dn none
    group-member-attribute none
    idle-timeout 3600
    ignore-auth-info-unavail no
    ignore-unknown-user disabled
    login-attribute none
    partition Common
    port ldap
    referrals yes
    scope sub
    search-base-dn none
    search-timeout 30
    servers { 1.1.1.1 }
    ssl disabled
    ssl-ca-cert-file none
    ssl-check-peer disabled
    ssl-ciphers none
    ssl-client-cert none
    ssl-client-key none
    user-template none
    version 3
    warnings enabled
}

after first task setting the key/cert/ca:

root@(v15-ansible)(cfg-sync Standalone)(Active)(/Common)(tmos)# list auth ldap all-properties
auth ldap system-auth {
    app-service none
    bind-dn none
    bind-pw none
    bind-timeout 30
    check-host-attr disabled
    check-roles-group disabled
    debug disabled
    description none
    filter none
    group-dn none
    group-member-attribute none
    idle-timeout 3600
    ignore-auth-info-unavail no
    ignore-unknown-user disabled
    login-attribute none
    partition Common
    port ldap
    referrals yes
    scope sub
    search-base-dn none
    search-timeout 30
    servers { 1.1.1.1 }
    ssl disabled
    ssl-ca-cert-file default.crt
    ssl-check-peer disabled
    ssl-ciphers none
    ssl-client-cert default.crt
    ssl-client-key default.key
    user-template none
    version 3
    warnings enabled
}

after second task setting back to none:

root@(v15-ansible)(cfg-sync Standalone)(Active)(/Common)(tmos)# list auth ldap all-properties
auth ldap system-auth {
    app-service none
    bind-dn none
    bind-pw none
    bind-timeout 30
    check-host-attr disabled
    check-roles-group disabled
    debug disabled
    description none
    filter none
    group-dn none
    group-member-attribute none
    idle-timeout 3600
    ignore-auth-info-unavail no
    ignore-unknown-user disabled
    login-attribute none
    partition Common
    port ldap
    referrals yes
    scope sub
    search-base-dn none
    search-timeout 30
    servers { 1.1.1.1 }
    ssl disabled
    ssl-ca-cert-file none
    ssl-check-peer disabled
    ssl-ciphers none
    ssl-client-cert none
    ssl-client-key none
    user-template none
    version 3
    warnings enabled
}
```
Test Playbook:

```
---
- name: Start Tests
  gather_facts: no
  hosts: all
  connection: local

  vars:
    provider:
      password: "admin"
      server: "{{ ansible_host }}"
      user: "admin"
      validate_certs: "no"
      server_port: "443"

  tasks:
     - name: Set the cert/key to default
       bigip_device_auth_ldap:
         ssl_client_cert: default.crt
         ssl_client_key: default.key
         ca_cert: default.crt
         provider: "{{ provider }}"
       register: result

     - name: Assert Set the cert/key to default
       assert:
         that:
           - result is changed
           - result is success

     - name: Set the cert/key to default - Idempotent Check
       bigip_device_auth_ldap:
         ssl_client_cert: default.crt
         ssl_client_key: default.key
         ca_cert: default.crt
         provider: "{{ provider }}"
       register: result

     - name: Assert Set the cert/key to default - Idempotent Check
       assert:
         that:
           - result is not changed
           - result is success

     - name: Set the cert/key to none
       bigip_device_auth_ldap:
         ssl_client_cert: none
         ssl_client_key: none
         ca_cert: none
         provider: "{{ provider }}"
       register: result

     - name: Assert Set the cert/key to none
       assert:
         that:
           - result is changed
           - result is success

     - name: Set the cert/key to none - Idempotent Check
       bigip_device_auth_ldap:
         ssl_client_cert: none
         ssl_client_key: none
         ca_cert: none
         provider: "{{ provider }}"
       register: result

     - name: Assert Set the cert/key to none - Idempotent Check
       assert:
         that:
           - result is not changed
           - result is success
```
