### ISSUE TITLE
ipv6/32 network to datagroup is not saved as network but as host

### ISSUE THREAD

**Issue by MarkCon00** [F5Networks/f5-ansible#1607]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

 - bigip_data_group

##### ANSIBLE VERSION

```
ansible 2.8.2
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/usr/lib/python3.6/site-packages/ansible']
  ansible python module location = /usr/lib/python3.6/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 3.6.4 (default, Dec 19 2017, 14:48:12) [GCC 4.8.5 20150623 (Red Hat 4.8.5-16)]

```

##### PYTHON VERSION

```
Python 2.7.5
```

##### BIGIP VERSION

```
Not version specific
```

##### OS / ENVIRONMENT

 - N/A

##### STEPS TO REPRODUCE

```
playbook #1 (internal data-group):

     - name: Create a data group of addresses
       bigip_data_group:
          name: foo
          internal: yes
          records:
            - key: 2402:6941::/32
              value: "Deakin University Network"
          type: address
          provider: "{{ provider }}"
       delegate_to: localhost

```

```
playbook #2 (external data-group):

     - name: Create a data group of IP addresses from a file
       bigip_data_group:
          name: ipv6
          records_src: /var/tmp/ipv6
          type: address
          provider: "{{ provider }}"
       delegate_to: localhost

[root@Linux ansible]# cat /var/tmp/ipv6
2402:6940::/32:= "Deakin University Network"
```

##### EXPECTED RESULTS

```
result #1 (internal data-group):

ltm data-group internal /Common/foo {     
       records {
              2402:6940::/32 {
                     data "Deakin University Network" 
        }
     }
     type ip
 }
```

```
result #2 (external data-group):

root@LTM13:Active:Standalone] config # cat /config/filestore/files_d/Common_d/data_group_d/:Common:ipv6_123791_1
network 2402:6940:: prefixlen 32 :=  "Deakin University Network",
```

##### ACTUAL RESULTS

```
result #1 (internal data-group):

ltm data-group internal /Common/foo {     
       records {
              2402:6940::/128 {
                     data "Deakin University Network" 
        }
     }
     type ip
 }
```

```
result #2 (external data-group):

[root@LTM13:Active:Standalone] config # cat /config/filestore/files_d/Common_d/data_group_d/:Common:ipv6_123785_1
host 2402:6940:: :=  "Deakin University Network",


```
