### ISSUE TITLE
bigip_virtual_server is very slow after migrating from Ansible 2.7 to Ansible 2.8 or 2.9

### ISSUE THREAD

**Issue by slavkv** [F5Networks/f5-ansible#1610]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

bigip_virtual_server

##### ANSIBLE VERSION

```
ansible 2.8.7
  config file = /Users/user1/git/gtld-load-balancers-automation/ansible.cfg
  configured module search path = [u'/Users/user1/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /Users/user1/git/ansible-2.8-virt/lib/python2.7/site-packages/ansible
  executable location = /Users/user1/git/ansible-2.8-virt/bin/ansible
  python version = 2.7.16 (default, Sep  2 2019, 12:00:52) [GCC 4.2.1 Compatible Apple LLVM 10.0.0 (clang-1000.11.45.5)]
```

##### PYTHON VERSION

```
Python 2.7.16
Python 3.7
```

##### BIGIP VERSION

```
Main Package
  Product     BIG-IP
  Version     14.1.2.3
  Build       0.0.5
  Edition     Point Release 3
  Date        Tue Dec 17 19:48:55 PST 2019
```

##### CONFIGURATION

$ cat ansible.cfg
[defaults]
inventory = ./inventories/staging
host_key_checking = False
ask_pass=False
roles_path = ./roles:/usr/local/etc/ansible/roles/
retry_files_enabled = False

##### OS / ENVIRONMENT

N/A

##### SUMMARY

I use Ansible module `bigip_virtual_server` to configure virtual servers.
It was working good, relative ok in terms of speed.

After I started using Ansible 2.8 or Ansible 2.9 all modules work the same except of `bigip_virtual_server`, it takes ages now to execute. When I have a role with many SSL profiles on a Virtual Server, it never completes.

I tried different versions of Python (ver 2 and ver 3) and Ansible 2.8 and 2.9. The same result, although 2.9 takes a little bit faster.

I took traffic dumps of those communications to compare what's going on on network level.
I tested `bigip_virtual_server` and `bigip_pool` for comparison.

Below I provided sizes of tcpdump files (HTTPS traffic between Ansible and F5, port 443 only; there was no other communication on this port between these hosts during tests).
```
Ansible 2.7:
bigip_pool: 24KB size, 2 TCP sessions, time to execute is 0m3.635s
bigip_virtual_server: 105KB size, 15 TCP sessions, time to execute is 0m5.800s
```

```
Ansible 2.8:
bigip_pool: 23KB size, 4 TCP sessions, time to execute is 0m3.611s
bigip_virtual_server: 63MB size !!, 145 TCP sessions, time to execute is 1m13.276s
```

```
Ansible 2.9:
bigip_pool: 23KB size, 4 TCP sessions, time to execute is 0m3.346s
bigip_virtual_server: 39MB size !!, ?? TCP sessions, time to execute is 0m45.710s
```

As you can see, there is no difference for module `bigip_pool` while there is a huge difference for `bigip_virtual_server`, it takes **more than 40 seconds** to update VS and **generate 40+ Megabytes of traffic** for it, which is not normal.

##### STEPS TO REPRODUCE

Even you see `loop` operator below please keep in mind that I tested on a list with a single item.
```
- name: Create pools
  bigip_pool:
    provider: "{{ f5_cli }}"
    state: present
    description: "{{ pool.description | default('') }}"
    name: "{{ pool.name }}"
    partition: Common
    lb_method: round-robin
    monitor_type: single
    monitors:
      - "{{ pool.monitor }}"
  delegate_to: localhost
  notify: Save F5 configuration
  loop: "{{ ltm.pools }}"
  loop_control:
    loop_var: pool
    label: " Create pool {{ pool.name }} "

- name: Add virtual servers (with irules, no policies)
  bigip_virtual_server:
    provider: "{{ f5_cli }}"
    state: "{{ vs.state | default('present') }}"
    partition: Common
    name: "{{ vs.name }}"
    type: "{{ vs.type | default('standard') }}"
    ip_protocol: "{{ vs.ip_protocol | default('tcp')}}"
    destination: "{{ vs.destination }}"
    port: "{{ vs.port }}"
    pool: "{{ vs.pool | default ('') }}"
    description: "{{ vs.description | default('') }}"
    profiles: "{{ vs.profiles }}"
    default_persistence_profile: "{{ vs.persist | default('') }}"
    irules: "{{ vs.irules | default(['']) }}"
    snat: "{{ vs.snat }}"
    enabled_vlans: "{{ vs.enabled_vlans | default('all')}}"
  delegate_to: localhost
  notify: Save F5 configuration
  loop: "{{ ltm.virtuals }}"
  loop_control:
    loop_var: vs
    label: " Create virtual server {{ vs.name }} "
```

##### EXPECTED RESULTS

A `bigip_virtual_server` (in Ansible 2.8 and 2.9) can configure Virtual Server with approximately the same time as Ansible 2.7, and it must not generate so much network traffic for a single Virtual Server.

##### ACTUAL RESULTS

```
Ansible 2.7:
bigip_pool: 24KB size, 2 TCP sessions, time to execute is 0m3.635s
bigip_virtual_server: 105KB size, 15 TCP sessions, time to execute is 0m5.800s
```

```
Ansible 2.8:
bigip_pool: 23KB size, 4 TCP sessions, time to execute is 0m3.611s
bigip_virtual_server: 63MB size !!, 145 TCP sessions, time to execute is 1m13.276s
```

```
Ansible 2.9:
bigip_pool: 23KB size, 4 TCP sessions, time to execute is 0m3.346s
bigip_virtual_server: 39MB size !!, ?? TCP sessions, time to execute is 0m45.710s


When I specify lots of client-ssl profiles for a Virtual Server, it never finishes and times out.
In tcpdump I see that traffic is going on all this time.

<!--- Paste verbatim command output between quotes below -->
```

```
