### ISSUE TITLE
bigip_firewall_dos_vector does not apply DNS and SIP vectors to system level, wrong identifier

### ISSUE THREAD

**Issue by MVogel91** [F5Networks/f5-ansible#1627]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

bigip_firewall_dos_vector

##### ANSIBLE VERSION

```
ansible 2.9.4
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/mvogel/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.5/dist-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 3.5.2 (default, Nov 12 2018, 13:43:14) [GCC 5.4.0 20160609]

```

##### PYTHON VERSION

```
Python 3.5.2
```

##### BIGIP VERSION

```
Sys::Version
Main Package
  Product     BIG-IP
  Version     14.1.0
  Build       0.0.116
  Edition     Final
  Date        Wed Nov 14 18:41:56 PST 2018

```

##### SUMMARY

Setting of Device DoS config is not possible due to parsing errors, e.g. on DNS vectors

##### STEPS TO REPRODUCE

For the below example, the module expects "aaaa" as a vector name, but fails with
```
fatal: [192.168.150.115]: FAILED! => {"changed": false, "msg": "{\"code\":400,\"message\":\"\\\"aaaa\\\" identifier doesn't match to any of the following: arp-flood or bad-ext-hdr-order or bad-icmp-chksum or bad-icmp-frame or bad-igmp-frame or bad-ip-opt or bad-ipv6-hop-cnt or bad-ipv6-ver or bad-sctp-chksum or bad-tcp-chksum or bad-tcp-flags-all-clr or bad-tcp-flags-all-set or bad-ttl-val or bad-udp-chksum or bad-udp-hdr or bad-ver or dns-a-query or dns-aaaa-query or dns-any-query or dns-axfr-query or dns-cname-query or dns-ixfr-query or dns-malformed or dns-mx-query or dns-ns-query or dns-other-query or dns-oversize or dns-ptr-query or dns-qdcount-limit or dns-response-flood or dns-soa-query or dns-srv-query or dns-txt-query or dup-ext-hdr or ether-brdcst-pkt or ether-mac-sa-eq-da or ether-multicst-pkt or ext-hdr-too-large or fin-only-set or flood or hdr-len-gt-l2-len or hdr-len-too-short or hop-cnt-leq-one or host-unreachable or icmp-frag or icmp-frame-too-large or icmpv4-flood or icmpv6-flood or igmp-flood or igmp-frag-flood or ip-bad-src or ip-err-chksum or ip-frag-flood or "}
```

When picking the corresponding vector name from the list (dns-aaaa-query):
```
fatal: [192.168.150.115]: FAILED! => {"changed": false, "msg": "value of name must be one of: ext-hdr-too-large, hop-cnt-low, host-unreachable, icmp-frag, icmpv4-flood, icmpv6-flood, ip-frag-flood, ip-low-ttl, ip-opt-frames, ipv6-frag-flood, opt-present-with-illegal-len, sweep, tcp-bad-urg, tcp-half-open, tcp-opt-overruns-tcp-hdr, tcp-psh-flood, tcp-rst-flood, tcp-syn-flood, tcp-syn-oversize, tcp-synack-flood, tcp-window-size, tidcmp, too-many-ext-hdrs, udp-flood, unk-tcp-opt-type, a, aaaa, any, axfr, cname, dns-malformed, ixfr, mx, ns, other, ptr, qdcount, soa, srv, txt, ack, bye, cancel, invite, message, notify, options, other, prack, publish, register, sip-malformed, subscribe, uri-limit, got: arp-flood"}
```

```
---

- name: DoS Device
  hosts: "{{ node }}"
  connection: local

  vars:
    prov:
      user: "{{ user }}"
      pass: "{{ pass }}"
      server: "{{ node }}"
      validate_certs: no

  tasks:
  - name: "DoS Device AAAA"
    bigip_firewall_dos_vector:
      provider: "{{ prov }}"
      name: aaaa
      state: mitigate
      threshold_mode: manual
      profile: device-config
      detection_threshold_eps: 100
      detection_threshold_percent: infinite
      mitigation_threshold_eps: 100
      bad_actor_detection: no
      auto_blacklist: no
```

```
---

- name: DoS Device
  hosts: "{{ node }}"
  connection: local

  vars:
    prov:
      user: "{{ user }}"
      pass: "{{ pass }}"
      server: "{{ node }}"
      validate_certs: no

  tasks:
  - name: "DoS Device AAAA"
    bigip_firewall_dos_vector:
      provider: "{{ prov }}"
      name: dns-aaaa-query
      state: mitigate
      threshold_mode: manual
      profile: device-config
      detection_threshold_eps: 100
      detection_threshold_percent: infinite
      mitigation_threshold_eps: 100
      bad_actor_detection: no
      auto_blacklist: no
```

##### EXPECTED RESULTS

Expected a DoS device vector to be altered

##### ACTUAL RESULTS

Error thrown, either by module parser or by BIG-IP iControl REST endpoint, depending on what the vector was named.

```
ansible-playbook --extra-vars "node=192.168.150.115 user=admin pass=admin" dos_device.yml
```
