### ISSUE TITLE
bigip_firewall_dos_vector does not offer all vectors for device config

### ISSUE THREAD

**Issue by MVogel91** [F5Networks/f5-ansible#1628]
##### ISSUE TYPE

 - Bug Report
 - Feature Idea

##### COMPONENT NAME
bigip_firewall_dos_vector

##### ANSIBLE VERSION

```
ansible 2.9.4
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/mvogel/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.5/dist-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 3.5.2 (default, Nov 12 2018, 13:43:14) [GCC 5.4.0 20160609]

```

##### PYTHON VERSION

```
Python 3.5.2
```

##### BIGIP VERSION

```
Sys::Version
Main Package
  Product     BIG-IP
  Version     14.1.0
  Build       0.0.116
  Edition     Final
  Date        Wed Nov 14 18:41:56 PST 2018
```

##### OS / ENVIRONMENT

N/A

##### SUMMARY

The IPv6 Extended Header Frames and DNS oversize vectors are not listed in the parser and thus not available for configuration:

```
ipv6-ext-hdr-frames
dns-oversize
```

##### STEPS TO REPRODUCE

```
---

- name: DoS config
  hosts: "{{ node }}"
  connection: local

  vars:
    prov:
      user: "{{ user }}"
      pass: "{{ pass }}"
      server: "{{ node }}"
      validate_certs: no

  tasks:
  - name: "IPv6 Extended Header Frames"
    bigip_firewall_dos_vector:
      provider: "{{ prov }}"
      profile: device-config
      name: ipv6-ext-hdr-frames
      state: mitigate
      threshold_mode: manual
      detection_threshold_eps: infinite
      detection_threshold_percent: infinite
      mitigation_threshold_eps: 10

```

##### EXPECTED RESULTS

IPv6 Extended Header Frames vector to be configured

##### ACTUAL RESULTS

Error thrown for unknown parameter

```
fatal: [192.168.150.115]: FAILED! => {"changed": false, "msg": "value of name must be one of: bad-icmp-chksum, bad-icmp-frame, bad-igmp-frame, bad-ip-opt, bad-ipv6-hop-cnt, bad-ipv6-ver, bad-sctp-chksum, bad-tcp-chksum, bad-tcp-flags-all-clr, bad-tcp-flags-all-set, bad-ttl-val, bad-udp-chksum, bad-udp-hdr, bad-ver, arp-flood, flood, igmp-flood, igmp-frag-flood, ip-bad-src, ip-err-chksum, ip-len-gt-l2-len, ip-other-frag, ip-overlap-frag, ip-short-frag, ip-uncommon-proto, ip-unk-prot, ipv4-mapped-ipv6, ipv6-atomic-frag, ipv6-bad-src, ipv6-len-gt-l2-len, ipv6-other-frag, ipv6-overlap-frag, ipv6-short-frag, l2-len-ggt-ip-len, l4-ext-hdrs-go-end, land-attack, no-l4, no-listener-match, non-tcp-connection, payload-len-ls-l2-len, routing-header-type-0, syn-and-fin-set, tcp-ack-flood, tcp-hdr-len-gt-l2-len, tcp-hdr-len-too-short, hdr-len-gt-l2-len, hdr-len-too-short, bad-ext-hdr-order, ext-hdr-too-large, hop-cnt-low, host-unreachable, icmp-frag, icmp-frame-too-large, icmpv4-flood, icmpv6-flood, ip-frag-flood, ip-low-ttl, ip-opt-frames, ipv6-frag-flood, opt-present-with-illegal-len, sweep, tcp-bad-urg, tcp-half-open, tcp-opt-overruns-tcp-hdr, tcp-psh-flood, tcp-rst-flood, tcp-syn-flood, tcp-syn-oversize, tcp-synack-flood, tcp-window-size, tidcmp, too-many-ext-hdrs, dup-ext-hdr, fin-only-set, ether-brdcst-pkt, ether-multicst-pkt, ether-mac-sa-eq-da, udp-flood, unk-ipopt-type, unk-tcp-opt-type, a, aaaa, any, axfr, cname, dns-malformed, dns-nxdomain-query, dns-response-flood, ixfr, mx, ns, other, ptr, qdcount, soa, srv, txt, ack, bye, cancel, invite, message, notify, options, other, prack, publish, register, sip-malformed, subscribe, uri-limit, got: ipv6-ext-hdr-frames"}
```
