### ISSUE TITLE
bigip_pool_member "replace_with_all" logic doesn't consider ports

### ISSUE THREAD

**Issue by Sam-Hall** [F5Networks/f5-ansible#1668]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
bigip_pool_member

##### ANSIBLE VERSION
```
ansible 2.9.4
  config file = /home/shall/apps-delivery/ansible/ansible.cfg
  configured module search path = [u'/home/shall/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']    ansible python module location = /home/shall/venv/local/lib/python2.7/site-packages/ansible
  executable location = /home/shall/venv/bin/ansible
  python version = 2.7.15+ (default, Oct  7 2019, 17:39:04) [GCC 7.4.0]
```

##### PYTHON VERSION
```
Python 2.7.15+
```

##### BIGIP VERSION
```
BIG-IP 14.1.2 Build 0.0.37 Final
```

##### CONFIGURATION
N/A

##### OS / ENVIRONMENT
N/A

##### SUMMARY
It looks like the "replace_with_all" logic in bigip_pool_member only looks at item['address'] to determine which members to purge. This means if you simply change the port number of a pool member, you will end up with both the new pool member and the old one with the old port number. I discovered this after initially adding members with the wrong port numbers then I noticed that trying to correct my mistake didn't purge the members with the bad port number.

##### STEPS TO REPRODUCE
```
- name: Demo bigip_pool_member replace_with_all bug
  hosts: all
  connection: local
  gather_facts: false

  vars:
    play_state: "present"

  tasks:
    - name: "Create server pool"
      bigip_pool:
        provider: "{{ provider }}"
        name: "replace_with_all_bug_pool"
        state: "{{ play_state }}"
      delegate_to: localhost

    - name: "Create pool member(s)"
      bigip_pool_member:
        provider: "{{ provider }}"
        pool: "replace_with_all_bug_pool"
        aggregate:
          - { ip: "192.168.0.1", port: "10001" }
          - { ip: "192.168.0.2", port: "10001" }
          - { ip: "192.168.0.3", port: "10001" }
          - { ip: "192.168.0.4", port: "10001" }
          - { ip: "192.168.1.1", port: "10001" }
          - { ip: "192.168.1.2", port: "10001" }
          - { ip: "192.168.1.3", port: "10001" }
          - { ip: "192.168.1.4", port: "10001" }
        replace_all_with: "yes"
        state: "{{ play_state }}"
      when: play_state=='present'
      delegate_to: localhost

    - name: "Replace pool member(s)"
      bigip_pool_member:
        provider: "{{ provider }}"
        pool: "replace_with_all_bug_pool"
        aggregate:
          - { ip: "192.168.0.1", port: "10002" }
          - { ip: "192.168.0.2", port: "10002" }
          - { ip: "192.168.0.3", port: "10002" }
          - { ip: "192.168.0.4", port: "10002" }
        replace_all_with: "yes"
        state: "{{ play_state }}"
      when: play_state=='present'
      delegate_to: localhost
```

##### EXPECTED RESULTS
Expect only 4 pool members.

##### ACTUAL RESULTS
We get 8 pool members, because it keeps the 4 pool members from the first time the task runs simply because they had a matching IP address.

```
ansible-playbook replace_all_with_bug.yml
```
