### ISSUE TITLE
bigip_device_auth_ldap validate_certs error

### ISSUE THREAD

**Issue by amolari** [F5Networks/f5-ansible#1674]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME
bigip_device_auth_ldap

##### ANSIBLE VERSION

```
ansible 2.9.4
```

##### PYTHON VERSION

```
Python 2.7.17
```

##### BIGIP VERSION

```
14.1.2.3
```

##### OS / ENVIRONMENT

N/A
##### SUMMARY

If I set the property "validate_certs": yesin bigip_device_auth_ldap, I get the error
"msg": "invalid property value \"ssl-check-peer\":\"true\""
Not setting the property => no error, but of course the setting is not enabled on the BIGIP.
##### STEPS TO REPRODUCE

```
- name: Create a LDAP authentication object
          bigip_device_auth_ldap:
                provider: "{{ provider }}"
                servers: xxx.xxx.xxx.xxx
                port: 636
                ssl: yes
                bind_dn: cn=xxxxxxx
                bind_password: changeme
                remote_directory_tree: cn=xxxxxxx
                scope: sub
                login_ldap_attr: samaccountname
                check_member_attr: no
                ca_cert: xxxxx.crt
                validate_certs: yes
                fallback_to_local: no
          delegate_to: localhost
```

##### EXPECTED RESULTS

Get the BIGIP LDAP Auth setting "SSL Check Peer" enabled.
##### ACTUAL RESULTS

```
"msg": "invalid property value \"ssl-check-peer\":\"true\""
```
