### ISSUE TITLE
bigip_policy_rule: add event types to forward actions for ssl extensions

### ISSUE THREAD

**Issue by amolari** [F5Networks/f5-ansible#1675]
##### ISSUE TYPE

 - Bug Report
 

##### COMPONENT NAME

bigip_policy_rule
>collection from f5networks-f5_modules-1.2.0-devel.tar.gz (daily)
##### ANSIBLE VERSION

```
ansible 2.9.4
```

##### PYTHON VERSION

```
python version = 2.7.17 
```

##### BIGIP VERSION

```
14.1.2.3
```

##### OS / ENVIRONMENT

N/A
##### SUMMARY
LTM policy rule, ssl_extension doesn't work (ref: https://github.com/F5Networks/f5-ansible/issues/1545)

##### STEPS TO REPRODUCE

```
bigip_policy_rule:
                provider: "{{ provider }}"
                name: rule_02
                description: fwd
                policy: main_policy
                partition: Common
                conditions:
                        - type: ssl_extension
                          server_name_is_any: www.example.com
                          event: ssl client hello
                actions:
                        - type: forward
                          virtual: www.example.com
                          event: ssl client hello
                state: present
          delegate_to: localhost

```

##### EXPECTED RESULTS

LTM policy rule with condition "SSL Extension server name is any of www.example.com at ssl client hello" and action "Forward traffic to virtual server www.example.com at ssl client hello" 
##### ACTUAL RESULTS

```
FAILED! => {"changed": false, "msg": "010716ff:3: Policy '/Common/Drafts/main_policy', rule 'rule_02'; operand 'ssl-extension' is not available during event 'request'."}

```
