### ISSUE TITLE
bigip_lx_package module does not create the "enable" file

### ISSUE THREAD

**Issue by m-kratochvil** [F5Networks/f5-ansible#1716]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
bigip_lx_package

##### ANSIBLE VERSION
```
ansible 2.9.5
  config file = /home/michal/ccloud-net/ansible.cfg
  configured module search path = ['/home/michal/ccloud-net/plugins/modules']
  ansible python module location = /home/michal/venv/prod/lib/python3.7/site-packages/ansible
  executable location = /home/michal/venv/prod/bin/ansible
  python version = 3.7.5 (default, Nov 20 2019, 09:21:52) [GCC 9.2.1 20191008]
```

##### PYTHON VERSION
```
Python 3.7.5
```

##### BIGIP VERSION
```
Sys::Version
Main Package
  Product     BIG-IP
  Version     13.1.1.4
  Build       0.0.4
  Edition     Point Release 4
  Date        Wed Jan 16 18:04:36 PST 2019
```

##### CONFIGURATION
Only connection timeout and inventory options are modified

##### OS / ENVIRONMENT
Ubuntu 19.10 server

##### SUMMARY
The `bigip_lx_package` module installs the AS3 package properly but randomly doesn't create the `
/var/config/rest/iapps/enable` file and the `Package Management LX` menu is then missing in the GUI.

##### STEPS TO REPRODUCE
```
  tasks:

    - name: Install the AS3 package.
      throttle: 1
      bigip_lx_package:
        provider: "{{ remoteprovider }}"
        package: ../tmp/{{ as3package }}
        state: "present"
      delegate_to: localhost

    - name: Enable the lx package extensions.
      copy:
        content: ""
        dest: /var/config/rest/iapps/enable
        force: no
```

##### EXPECTED RESULTS
The `/var/config/rest/iapps/enable` file is created and the `Package Management LX` menu item is available in GUI. 

##### ACTUAL RESULTS
Running the playbook above against 8 target devices results in only 4 of them having the file installed via the `bigip_lx_package` module, remaining 4 are missing the file and it gets installed with the additional `copy` task.
For the devices where the module doesn't create the file, Ansible reports the AS3 as already installed (task has status `ok`, no changes).

```
TASK [Install the AS3 package.] *******************************************************************************************************************************************
changed: [ap-cn-1a-f511-01 -> localhost]
changed: [ap-cn-1a-f511-02 -> localhost]
changed: [ap-cn-1a-f511-03 -> localhost]
changed: [ap-cn-1a-f511-mgmt -> localhost]
ok: [ap-cn-1b-f511-01 -> localhost]
ok: [ap-cn-1b-f511-02 -> localhost]
ok: [ap-cn-1b-f511-03 -> localhost]
ok: [ap-cn-1b-f511-mgmt -> localhost]

TASK [Enable the lx package extensions.] **********************************************************************************************************************************
ok: [ap-cn-1a-f511-02]
ok: [ap-cn-1a-f511-01]
ok: [ap-cn-1a-f511-mgmt]
ok: [ap-cn-1a-f511-03]
changed: [ap-cn-1b-f511-01]
changed: [ap-cn-1b-f511-02]
changed: [ap-cn-1b-f511-03]
changed: [ap-cn-1b-f511-mgmt]
```
