### ISSUE TITLE
bigip_lx_package - allow installation of AS3 without forcing package upload

### ISSUE THREAD

**Issue by m-kratochvil** [F5Networks/f5-ansible#1717]
##### ISSUE TYPE
 - Feature Idea

##### COMPONENT NAME
bigip_lx_package

##### SUMMARY
We can download the LX packages directly to Big-IP from cloud storage (Swift).
This is fast and location based.
It would be great if we could use the `bigip_lx_package` module to just install the LX packages without uploading them to the Big-IP. The logic should be:

- check if AS3 is already installed
- if not, check if AS3 installation file is already present on the Big-IP
- if yes, do not upload, just install the package

**Comment by focrensh** [comment]
Thank you for the suggestion. Tracking with FMFA-486 internally.

**Comment by strain17** [comment]
It would also be useful as well if the module supports specifying a remote resource for the package. Eg.

`package: "https://github.com/F5Networks/f5-telemetry-streaming/releases/download/v1.14.0/f5-telemetry-1.14.0-2.noarch.rpm"`

**Comment by focrensh** [comment]
It is best practice to try and reduce duplicate code where possible. Ansible has other modules which handle file downloads very well so we leverage those within an ansible role which is called prior to this module. Example below:

https://galaxy.ansible.com/f5devcentral/f5app_services_package

```
    - name: Download and Install DO RPM sha check - url
      include_role:
        name: f5devcentral.f5app_services_package
      vars:
        f5app_services_package_url: "https://github.com/F5Networks/f5-declarative-onboarding/raw/master/dist/f5-declarative-onboarding-1.3.0-4.noarch.rpm"
        f5app_services_package_checksum_url: "https://github.com/F5Networks/f5-declarative-onboarding/raw/master/dist/f5-declarative-onboarding-1.3.0-4.noarch.rpm.sha256"
        f5app_services_package_path: "/tmp/f5-declarative-onboarding-1.3.0-4.noarch.rpm"
```
