### ISSUE TITLE
Insanely slow performance from 1.3.0-devel collection in 2.9.6 ansible in bigip_virtual_server module

### ISSUE THREAD

**Issue by oniGino** [F5Networks/f5-ansible#1725]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME
bigip_virtual_server
##### ANSIBLE VERSION
```
$ ansible --version
ansible 2.9.6
  config file = /Users/gino.mccarty/Documents/Systems/aoclassic-build/ansible/ansible.cfg
  configured module search path = ['/Users/gino.mccarty/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/Cellar/ansible/2.9.6_1/libexec/lib/python3.8/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 3.8.2 (default, Mar 11 2020, 00:29:50) [Clang 11.0.0 (clang-1100.0.33.17)]
```

##### PYTHON VERSION

```
$ python -V
Python 2.7.16
$ python3 -V
Python 3.7.7
```

##### BIGIP VERSION

```
Sys::Version
Main Package
  Product     BIG-IP
  Version     14.1.2.2
  Build       0.0.4
  Edition     Point Release 2
  Date        Tue Nov  5 10:09:50 PST 2019

```

##### CONFIGURATION

```
 f5networks.f5_modules.bigip_virtual_server:
    state: present
    name: "{{ hostname_short }}_80"
    destination: "{{ internal_lb_ip }}"
    port: http
    pool: "{{ hostname_short }}"
    description: "{{ description }}"
    profiles:
      - customer-instance-compression
      - oneconnect
      - x-forwarded-http
      - name: tcp-lan-optimized
        context: server-side
      - name: tcp-wan-optimized
        context: client-side
    irules:
      - ci-blacklist
      - ci-cloudfront-redirect
      - ci-account-redirect
      - ci-pool-selection
    address_translation: true
    port_translation: true
    metadata:
      ticket: "{{ ticket }}"
    provider: "{{ ltm }}"
```

##### OS / ENVIRONMENT

2000S chassis
##### SUMMARY
Not sure if this problem is my older 2000 chassis or some other code problem, but this action used to be very fast. its not almost unusable

##### STEPS TO REPRODUCE

```
Performance seems to have dropped dramatically since the latest update to 2.9.6 ansible.
Loading our new VIPs via ansible now takes over 30minutes to create 2 VIPS
we have 400VIPs and 3000 client SSL profiles
```

##### ACTUAL RESULTS

No error output of any kind of given, commands do not time out they just take forever to complete.

I downloaded the latest daily 1.3.0-devel branch, and performance remains very poor
