### ISSUE TITLE
bigip_firewall_rule not idempotent when using address_list as source or destination

### ISSUE THREAD

**Issue by Fuochi-YNAP** [F5Networks/f5-ansible#1731]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

bigip_firewall_rule

##### ANSIBLE VERSION

```
ansible 2.9.6
  config file = /ansible/ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, Aug  7 2019, 00:51:29) [GCC 4.8.5 20150623 (Red Hat 4.8.5-39)]
```

##### PYTHON VERSION

```
Python 2.7.5
```

##### BIGIP VERSION

```
Sys::Version
Main Package
  Product     BIG-IP
  Version     15.0.1.1
  Build       0.0.3
  Edition     Point Release 1
  Date        Mon Nov 18 11:30:00 PST 2019

```

##### SUMMARY

When you use an address list as inside the source or destination list to modify an existent rule inside an existent policy, you don't get idempotency. Even launching again the same playbook will result in a "changed status"
##### STEPS TO REPRODUCE

```
---
- hosts: all
  gather_facts: false
  tasks:
  - name: Edit AFM rule in the corresponding policy
    bigip_firewall_rule:
      name: 'rule_test'
      parent_policy: 'policy_test'
      source:
      - address_list: 'list_test'
      action: accept
      logging: yes
      provider:
        server: '{{f5_server}}'
        user: '{{f5_user}}'
        password: '{{f5_password}}'
        validate_certs: no
        transport: rest
    delegate_to: localhost
```

##### EXPECTED RESULTS

I expect that if the playbook is run two times, the status will be 'ok'
##### ACTUAL RESULTS

```
TASK [Edit AFM rule in the corresponding policY] ******************************************************************************************************************************************************
task path: /ansible/afm_acl_update.yml:51
<localhost> ESTABLISH LOCAL CONNECTION FOR USER: root
<localhost> EXEC /bin/sh -c 'echo ~root && sleep 0'
<localhost> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /root/.ansible/tmp/ansible-tmp-1587640929.03-236451353117110 `" && echo ansible-tmp-1587640929.03-236451353117110="` echo /root/.ansible/tmp/ansible-tmp-1587640929.03-236451353117110 `" ) && sleep 0'
Using module file /usr/lib/python2.7/site-packages/ansible/modules/network/f5/bigip_firewall_rule.py
<localhost> PUT /root/.ansible/tmp/ansible-local-15nKy_iA/tmpPA52MR TO /root/.ansible/tmp/ansible-tmp-1587640929.03-236451353117110/AnsiballZ_bigip_firewall_rule.py
<localhost> EXEC /bin/sh -c 'chmod u+x /root/.ansible/tmp/ansible-tmp-1587640929.03-236451353117110/ /root/.ansible/tmp/ansible-tmp-1587640929.03-236451353117110/AnsiballZ_bigip_firewall_rule.py && sleep 0'
<localhost> EXEC /bin/sh -c '/usr/bin/python2 /root/.ansible/tmp/ansible-tmp-1587640929.03-236451353117110/AnsiballZ_bigip_firewall_rule.py && sleep 0'
<localhost> EXEC /bin/sh -c 'rm -f -r /root/.ansible/tmp/ansible-tmp-1587640929.03-236451353117110/ > /dev/null 2>&1 && sleep 0'
changed: [F5_server -> localhost] => {
    "changed": true, 
    "invocation": {
        "module_args": {
            "action": "accept", 
            "description": null, 
            "destination": null, 
            "icmp_message": null, 
            "irule": null, 
            "logging": true, 
            "name": "rule_test", 
            "parent_policy": "policy_test", 
            "parent_rule_list": null, 
            "partition": "Common", 
            "protocol": null, 
            "provider": {F5_server}, 
            "rule_list": null, 
            "schedule": null, 
            "source": [
                {
                    "address": null, 
                    "address_list": "list_test", 
                    "address_range": null, 
                    "country": null, 
                    "port": null, 
                    "port_list": null, 
                    "port_range": null, 
                    "vlan": null
                }
            ], 
            "state": "present", 
            "status": null
        }
    }, 
    "source": {
        "address_list": "list_test"
    }
}
META: ran handlers
META: ran handlers

```
