### ISSUE TITLE
bigip_command: CLI transport fails when bigip is in Auth fallback condition

### ISSUE THREAD

**Issue by amolari** [F5Networks/f5-ansible#1732]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

bigip_command
devel-3.0
##### ANSIBLE VERSION

```
ansible 2.9.7
```

##### PYTHON VERSION

```
2.7.17
```

##### BIGIP VERSION

```
14.1.2.3
```

##### CONFIGURATION

N/A
##### OS / ENVIRONMENT

N/A
##### SUMMARY

I'm running a tmsh through the CLI transport. I get an error, if the authentication is a fallback (from LDAP to local), in the scenario that LDAP is not reachable. If there is no Auth Fallback, it works OK.
Note: when connecting to the device by ssh, connection works with&without auth fallback.
##### STEPS TO REPRODUCE

```
- name: restart restjavad service
  f5networks.f5_modules.bigip_command:
    provider:
      password: "{{ bigip_admin_password }}"
      server: "{{ ansible_host }}"
      user: "{{ bigip_admin_username }}"
      transport: cli
      timeout: 15
    commands:
      - restart sys service restjavad
  delegate_to: localhost

```

##### EXPECTED RESULTS

Connection with bigip_command should work if there is an Auth fallback.
##### ACTUAL RESULTS

```
"Unexpected failure during module execution.",
    "exception": "Traceback (most recent call last):\n  File \"/opt/rh/rh-python36/root/lib/python3.6/site-packages/ansible/executor/task_executor.py\", line 146, in run\n    res = self._execute()\n  File \"/opt/rh/rh-python36/root/lib/python3.6/site-packages/ansible/executor/task_executor.py\", line 645, in _execute\n    result = self._handler.run(task_vars=variables)\n  File \"/opt/rh/rh-python36/root/lib/python3.6/site-packages/ansible/plugins/action/bigip.py\", line 94, in run\n    out = conn.get_prompt()\n  File \"/opt/rh/rh-python36/root/lib/python3.6/site-packages/ansible/module_utils/connection.py\", line 185, in __rpc__\n    raise ConnectionError(to_text(msg, errors='surrogate_then_replace'), code=code)\nansible.module_utils.connection.ConnectionError: Failed to authenticate: Bad authentication type; allowed types: ['publickey', 'keyboard-interactive', 'hostbased']\n"
```
