### ISSUE TITLE
bigip_command: Indicate that running bigip_command will trigger config sync pending changes in HA

### ISSUE THREAD

**Issue by NicCage1337** [F5Networks/f5-ansible#1734]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME
bigip_command
##### ANSIBLE VERSION

```
ansible 2.9.3
```

##### PYTHON VERSION

```
Python 2.7.13
```

##### BIGIP VERSION

```
13.1.3
```

##### CONFIGURATION

N/A
##### OS / ENVIRONMENT

N/A
##### SUMMARY

I need to run bigip_command to verify Config Sync State against a Cluster.
Whenever a new User is running the Playbook, execution of bigip_command triggers Config-Sync.
##### STEPS TO REPRODUCE

```
     - name: Gather ConfigSync Status via TMSH
        bigip_command:
          provider: "{{ provider }}"
          commands:
            - show cm sync-status field-fmt
        register: sync_status

```

##### EXPECTED RESULTS

Running a Show Command should not Trigger Config-Sync, or there should be a clear Warning within the Module Documentation.
##### ACTUAL RESULTS

```
AUDIT - pid=29153 user=XXXXX folder=/Common module=(tmos)# status=[Command OK] cmd_data=modify cli preference pager disabled

```
