### ISSUE TITLE
Adding simple NATs does not have idempotent ansible module

### ISSUE THREAD

**Issue by gandasi** [F5Networks/f5-ansible#1775]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME
create ltm nat

##### ANSIBLE VERSION

```
ansible 2.9.9
  config file = /ansible/playbooks/ansible.cfg
  configured module search path = ['/ansible/playbooks/library/vsphere_provisioner', '/ansible/playbooks/library']
  ansible python module location = /usr/local/lib/python3.8/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 3.8.3 (default, May 20 2020, 20:46:20) [GCC 9.2.0]

```

##### PYTHON VERSION

```
python version = 3.8.3 (default, May 20 2020, 20:46:20) [GCC 9.2.0]

```

##### BIGIP VERSION

```

Sys::Version
Main Package
  Product     BIG-IP
  Version     14.1.2.5
  Build       0.0.3
  Edition     Point Release 5
  Date        Sat May  9 09:31:20 PDT 2020

```

##### SUMMARY
Logging a bug as per output from bigip_command. Am creating simple NATs and there is no specific module for this. Works just fine using bigip_command, but the nag screen tells me after that I should log a bug as "write" commands are not idempotent, so I am

##### STEPS TO REPRODUCE

```
- name: Add NAT Addresses
  bigip_command:
    provider:
      user: "{{ bigip_username }}"
      password: "{{ bigip_password }}"
      server: "{{ ansible_host }}"
      server_port: "{{ bigip_server_port }}"
      validate_certs: no
    commands: "{{item.add_nat_command}}"
  delegate_to: localhost

```

##### EXPECTED RESULTS
Command works as expected, but nags about using bigip_command which is not idempotent

##### ACTUAL RESULTS
NAT is created as expected
```

```
