### ISSUE TITLE
Unsupported parameters for (bigip_command) module

### ISSUE THREAD

**Issue by oteizaa** [F5Networks/f5-ansible#1776]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME
bigip_command

##### ANSIBLE VERSION

```
ansible 2.9.10
  config file = None
  configured module search path = [u'/Users/ZZZZ/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /Library/Python/2.7/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 2.7.16 (default, Apr 17 2020, 18:29:03) [GCC 4.2.1 Compatible Apple LLVM 11.0.3 (clang-1103.0.29.20) (-macos10.15-objc-
```

##### PYTHON VERSION

```
Python 2.7.16
```

##### BIGIP VERSION

```
Sys::Version
Main Package
  Product     BIG-IP
  Version     14.1.2.6
  Build       0.0.2
  Edition     Point Release 6
  Date        Fri Jun  5 11:36:46 PDT 2020
```

##### SUMMARY
Get an error saying that I am using unsupported parameters:

The full traceback is:
WARNING: The below traceback may *not* be related to the actual failure.
  File "/var/folders/7r/kf1jw6gj5lq64y9zt85ydy1hz29r67/T/ansible_bigip_command_payload_GYQzJ7/ansible_bigip_command_payload.zip/ansible/modules/network/f5/bigip_command.py", line 219, in <module>
fatal: [XXX.XXX.XXX.XXX]: FAILED! => {
    "changed": false,
    "invocation": {
        "module_args": {
            "commands": "modify auth user admin password YYYYYYYYYY",
            "provider": {
                "auth_provider": null,
                "password": null,
                "server": "XXX.XXX.XXX.XXX",
                "server_port": null,
                "ssh_keyfile": "/Users/ZZZZZ/.ssh/id_rsa",
                "timeout": null,
                "transport": "cli",
                "user": "admin",
                "validate_certs": false
            },
            "validate_certs": false
        }
    },
    "msg": "Unsupported parameters for (bigip_command) module: validate_certs Supported parameters include: chdir, commands, interval, match, provider, retries, transport, wait_for, warn"
}

##### STEPS TO REPRODUCE

```
---
- name: Set BIG-IP admin password
  bigip_command:
    provider:
      server: "{{ inventory_hostname }}"
      ssh_keyfile: "{{ SSH_KEY_PATH }}"
      transport: cli
      user: admin
    commands: modify auth user admin password {{ ADMIN_PASSWORD }}
    validate_certs: no
  delegate_to: localhost

- name: enable iApps LX Package management in UI
  bigip_command:
    provider:
      server: "{{ inventory_hostname }}"
      ssh_keyfile: "{{ SSH_KEY_PATH }}"
      transport: cli
      user: admin
    commands: run /util bash -c "touch /var/config/rest/iapps/enable"
    validate_certs: no
  delegate_to: localhost%
```

##### EXPECTED RESULTS

There would be no error

##### ACTUAL RESULTS

<localhost> connection transport is cli
<XXX.XXX.XXX.XXX> using connection plugin network_cli
<XXX.XXX.XXX.XXX> starting connection from persistent connection plugin
<XXX.XXX.XXX.XXX> local domain socket does not exist, starting it
<XXX.XXX.XXX.XXX> control socket path is /Users/ZZZZ/.ansible/pc/ffd2ed6a76
<XXX.XXX.XXX.XXX> local domain socket listeners started successfully
<XXX.XXX.XXX.XXX> unable to load cliconf for network_os bigip
<XXX.XXX.XXX.XXX>
<XXX.XXX.XXX.XXX> local domain socket path is /Users/ZZZZ/.ansible/pc/ffd2ed6a76
<XXX.XXX.XXX.XXX> socket_path: /Users/ZZZZ/.ansible/pc/ffd2ed6a76
<localhost> ESTABLISH LOCAL CONNECTION FOR USER: ZZZZ
<localhost> EXEC /bin/sh -c 'echo ~ZZZZZ && sleep 0'
<localhost> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /Users/ZZZZZ/.ansible/tmp `"&& mkdir /Users/ZZZZZ/.ansible/tmp/ansible-tmp-1592949366.27-74034-91150591845197 && echo ansible-tmp-1592949366.27-74034-91150591845197="` echo /Users/ZZZZZ/.ansible/tmp/ansible-tmp-1592949366.27-74034-91150591845197 `" ) && sleep 0'
Using module file /Library/Python/2.7/site-packages/ansible/modules/network/f5/bigip_command.py
<localhost> PUT /Users/ZZZZ/.ansible/tmp/ansible-local-73908JsH470/tmpVV7lsC TO /Users/ZZZZ/.ansible/tmp/ansible-tmp-1592949366.27-74034-91150591845197/AnsiballZ_bigip_command.py
<localhost> EXEC /bin/sh -c 'chmod u+x /Users/ZZZZZ/.ansible/tmp/ansible-tmp-1592949366.27-74034-91150591845197/ /Users/ZZZZZ/.ansible/tmp/ansible-tmp-1592949366.27-74034-91150591845197/AnsiballZ_bigip_command.py && sleep 0'
<localhost> EXEC /bin/sh -c '/System/Library/Frameworks/Python.framework/Versions/2.7/Resources/Python.app/Contents/MacOS/Python /Users/ZZZZZZ/.ansible/tmp/ansible-tmp-1592949366.27-74034-91150591845197/AnsiballZ_bigip_command.py && sleep 0'
<localhost> EXEC /bin/sh -c 'rm -f -r /Users/ZZZZZ/.ansible/tmp/ansible-tmp-1592949366.27-74034-91150591845197/ > /dev/null 2>&1 && sleep 0'
The full traceback is:
WARNING: The below traceback may *not* be related to the actual failure.
  File "/var/folders/7r/kf1jw6gj5lq64y9zt85ydy1hz29r67/T/ansible_bigip_command_payload_Us252E/ansible_bigip_command_payload.zip/ansible/modules/network/f5/bigip_command.py", line 219, in <module>
fatal: [XXX.XXX.XXX.XXX]: FAILED! => {
    "changed": false,
    "invocation": {
        "module_args": {
            "commands": "modify auth user admin password YYYYYYYY",
            "provider": {
                "auth_provider": null,
                "password": null,
                "server": "XXX.XXX.XXX.XXX",
                "server_port": null,
                "ssh_keyfile": "/Users/ZZZZZ/.ssh/id_rsa",
                "timeout": null,
                "transport": "cli",
                "user": "admin",
                "validate_certs": false
            },
            "validate_certs": false
        }
    },
    "msg": "Unsupported parameters for (bigip_command) module: validate_certs Supported parameters include: chdir, commands, interval, match, provider, retries, transport, wait_for, warn"
}

```

```

**Comment by oteizaa** [comment]
resolved.... I have to change the location of "validate_certs: no" within the provider (found a similar issue https://github.com/F5Networks/f5-ansible/issues/670)

new template:

```
---
- name: Set BIG-IP admin password
  bigip_command:
    provider:
      server: "{{ inventory_hostname }}"
      ssh_keyfile: "{{ SSH_KEY_PATH }}"
      transport: cli
      user: admin
      validate_certs: no
    commands: modify auth user admin password {{ ADMIN_PASSWORD }}
  delegate_to: localhost

- name: enable iApps LX Package management in UI
  bigip_command:
    provider:
      server: "{{ inventory_hostname }}"
      ssh_keyfile: "{{ SSH_KEY_PATH }}"
      transport: cli
      user: admin
      validate_certs: no
    commands: run /util bash -c "touch /var/config/rest/iapps/enable"
  delegate_to: localhost%

```
