### ISSUE TITLE
APM Policy fetch fails

### ISSUE THREAD

**Issue by simonkowallik** [F5Networks/f5-ansible#1780]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

`bigip_apm_policy_fetch` from collection version `1.4.0`, also tested with current `devel` branch.

##### ANSIBLE VERSION

```
ansible --version
ansible 2.9.10
  config file = /root/ansible/ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.17 (default, Apr 15 2020, 17:20:14) [GCC 7.5.0]
```

##### PYTHON VERSION

```
python -V
Python 2.7.17
python3 -V
Python 3.6.9
```

##### BIGIP VERSION

```
14.1.2.6
```

##### OS / ENVIRONMENT

Ubuntu 18.06

##### SUMMARY

```yaml
    - name: apm_policy_fetch
      bigip_apm_policy_fetch:
        provider: "{{ provider }}"
        dest: "./"
        file: apm_fetch_test.tgz
        name: export_testing_A
        type: profile_access
        #type: access_policy
      delegate_to: localhost
```

```shell
PLAY [remote command] *********************************************************************************************************************************************************************************************************

TASK [Gathering Facts] ********************************************************************************************************************************************************************************************************
ok: [10.1.1.4]

TASK [apm_policy_import] ******************************************************************************************************************************************************************************************************
changed: [10.1.1.4]

PLAY RECAP ********************************************************************************************************************************************************************************************************************
10.1.1.4                   : ok=2    changed=1    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0
```

`apm_fetch_test.tgz` file is empty after playbook ran successfully.

##### STEPS TO REPRODUCE

```yaml
    - name: apm_policy_fetch
      bigip_apm_policy_fetch:
        provider: "{{ provider }}"
        dest: "./"
        file: apm_fetch_test.tgz
        name: export_testing_A
        type: profile_access
        #type: access_policy
      delegate_to: localhost
```

##### EXPECTED RESULTS
`apm_fetch_test.tgz` is not empty and contains a valid apm policy.

##### ACTUAL RESULTS

`apm_fetch_test.tgz` file is empty after playbook ran successfully.
