### ISSUE TITLE
bigip_pool_member with aggregate and replace_all_with empties the pool before adding nodes

### ISSUE THREAD

**Issue by ernst-at-tv2** [F5Networks/f5-ansible#1789]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME
bigip_pool_member

##### ANSIBLE VERSION

```
ansible 2.9.10
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/var/lib/awx/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.6/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 3.6.8 (default, Apr 16 2020, 01:36:27) [GCC 8.3.1 20191121 (Red Hat 8.3.1-5)]
```

##### PYTHON VERSION

```
Python 3.6.8
```

##### BIGIP VERSION

```
BIG-IP 13.1.3 Build 0.0.6 Final
```

##### OS / ENVIRONMENT

N/A

##### SUMMARY
When using bigip_pool_member with aggregate and replace_all_with empties the pool before adding nodes.

This would be catastrophic if run in production. I don't know if it's by design, if so I think the documentation should mention it somewhere

##### STEPS TO REPRODUCE

```
- name: "Add node to pool"
  bigip_pool_member:
    pool: some_pool
    partition: Dev
    aggregate: 
      - partition: Dev
        address: 10.0.0.1
        port: 80
        reuse_nodes: yes
        name: 10.0.0.1
      - partition: Dev
        address: 10.0.0.2
        port: 80
        reuse_nodes: yes
        name: 10.0.0.2
      - partition: Dev
        address: 10.0.0.3
        port: 80
        reuse_nodes: yes
        name: 10.0.0.3
      - partition: Dev
        address: 10.0.0.4
        port: 80
        reuse_nodes: yes
        name: 10.0.0.4
      - partition: Dev
        address: 10.0.0.5
        port: 80
        reuse_nodes: yes
        name: 10.0.0.5
    replace_all_with: yes
```

##### EXPECTED RESULTS

I expect the module to do a diff with the current pool configuration if the pool exists, and remove or add any changed nodes

##### ACTUAL RESULTS

Monitoring the pool in the management UI we can observe that the pool is emptied of all nodes and then each node is added into the pool again.

**Comment by focrensh** [comment]
Are you seeing a different experience than when running "replace-all-with" within TMSH? This parameter should not be reinventing the logic of how the members are added/removed, but rather exposing the "replace-all-with" functionality already within pools.

**Comment by ernst-at-tv2** [comment]
@focrensh I'm not that familiar with the TMSH, but I've talked with our resident BigIP expert and his take is that using `replace-all-with` should be an almost instant action (not quite atomic) that replaces all members of a pool instantly. This is not how this module behaves.

I've created the following test playbook
```YAML
---
- name: Test Github F5 module issue
  hosts: localhost

  tasks:
    - name: "Create pool for testing"
      bigip_pool:
        name: "github_issue_replace_all_with"
        state: present
        partition: "{{ f5_partition }}"
        lb_method: least-connections-member
        slow_ramp_time: 120
        monitors: ['/Common/tcp_half_open']
        description: "bruges til debugging af https://github.com/F5Networks/f5-ansible/issues/1789"

    - name: "Add nodes to pool"
      bigip_pool_member:
        pool: github_issue_replace_all_with
        partition: "{{ f5_partition }}"
        aggregate:
          - partition: "{{ f5_partition }}"
            address: 10.0.0.1
            port: 80
            reuse_nodes: yes
            name: 10.0.0.1
          - partition: "{{ f5_partition }}"
            address: 10.0.0.2
            port: 80
            reuse_nodes: yes
            name: 10.0.0.2
          - partition: "{{ f5_partition }}"
            address: 10.0.0.3
            port: 80
            reuse_nodes: yes
            name: 10.0.0.3
          - partition: "{{ f5_partition }}"
            address: 10.0.0.4
            port: 80
            reuse_nodes: yes
            name: 10.0.0.4
          - partition: "{{ f5_partition }}"
            address: 10.0.0.5
            port: 80
            reuse_nodes: yes
            name: 10.0.0.5
        replace_all_with: yes
```

Running this playbook produces the following in the BigIP Audit log: 
```
Thu Jul 9 10:10:04 CEST 2020		0-0	pid=20557 user=username folder=/Common module=(tmos)# status=[Command OK transaction submitted] cmd_data=modify ltm pool /Dev/github_issue_replace_all_with { members delete { /Dev/10.0.0.2:80 } }:
Thu Jul 9 10:10:04 CEST 2020		0-0	pid=20557 user=username folder=/Common module=(tmos)# status=[Command OK transaction submitted] cmd_data=modify ltm pool /Dev/github_issue_replace_all_with { members delete { /Dev/10.0.0.1:80 } }:
Thu Jul 9 10:10:04 CEST 2020		0-0	pid=20557 user=username folder=/Common module=(tmos)# status=[Command OK transaction submitted] cmd_data=modify ltm pool /Dev/github_issue_replace_all_with { members delete { /Dev/10.0.0.3:80 } }:
Thu Jul 9 10:10:04 CEST 2020		0-0	pid=20557 user=username folder=/Common module=(tmos)# status=[Command OK transaction submitted] cmd_data=modify ltm pool /Dev/github_issue_replace_all_with { members delete { /Dev/10.0.0.4:80 } }:
Thu Jul 9 10:10:04 CEST 2020		0-0	pid=20557 user=username folder=/Common module=(tmos)# status=[Command OK transaction submitted] cmd_data=modify ltm pool /Dev/github_issue_replace_all_with { members delete { /Dev/10.0.0.5:80 } }:
Thu Jul 9 10:10:04 CEST 2020		0-0	client tmsh, tmsh-pid-20557, user username - transaction #4982100-3 - object 0 - obj_delete { pool_member { pool_member_pool_name "/Dev/github_issue_replace_all_with" pool_member_node_name "/Dev/10.0.0.2" pool_member_port 80 } } [Status=Command OK]:
Thu Jul 9 10:10:04 CEST 2020		0-0	client tmsh, tmsh-pid-20557, user username - transaction #4982100-5 - object 0 - obj_delete { pool_member { pool_member_pool_name "/Dev/github_issue_replace_all_with" pool_member_node_name "/Dev/10.0.0.1" pool_member_port 80 } } [Status=Command OK]:
Thu Jul 9 10:10:04 CEST 2020		0-0	client tmsh, tmsh-pid-20557, user username - transaction #4982100-7 - object 0 - obj_delete { pool_member { pool_member_pool_name "/Dev/github_issue_replace_all_with" pool_member_node_name "/Dev/10.0.0.3" pool_member_port 80 } } [Status=Command OK]:
Thu Jul 9 10:10:04 CEST 2020		0-0	client tmsh, tmsh-pid-20557, user username - transaction #4982100-9 - object 0 - obj_delete { pool_member { pool_member_pool_name "/Dev/github_issue_replace_all_with" pool_member_node_name "/Dev/10.0.0.4" pool_member_port 80 } } [Status=Command OK]:
Thu Jul 9 10:10:04 CEST 2020		0-0	client tmsh, tmsh-pid-20557, user username - transaction #4982100-11 - object 0 - obj_delete { pool_member { pool_member_pool_name "/Dev/github_issue_replace_all_with" pool_member_node_name "/Dev/10.0.0.5" pool_member_port 80 } } [Status=Command OK]:
Thu Jul 9 10:10:04 CEST 2020		0-0	client tmsh, tmsh-pid-20557, user username - transaction #4982329-2 - object 0 - create { pool_member { pool_member_pool_name "/Dev/github_issue_replace_all_with" pool_member_node_name "/Dev/10.0.0.1" pool_member_port 80 pool_member_addr 10.0.0.1%2 pool_member_autoscale 0 pool_member_monitor_state 3 pool_member_new_session_enable 2 } } [Status=Command OK]:
Thu Jul 9 10:10:05 CEST 2020		0-0	pid=20557 user=username folder=/Common module=(tmos)# status=[Command OK] cmd_data=modify ltm pool /Dev/github_issue_replace_all_with { members add { /Dev/10.0.0.1:80 { address 10.0.0.1%2 fqdn { autopopulate disabled } session user-enabled state user-up } } }:
Thu Jul 9 10:10:05 CEST 2020		0-0	client tmsh, tmsh-pid-20557, user username - transaction #4982562-2 - object 0 - create { pool_member { pool_member_pool_name "/Dev/github_issue_replace_all_with" pool_member_node_name "/Dev/10.0.0.2" pool_member_port 80 pool_member_addr 10.0.0.2%2 pool_member_autoscale 0 pool_member_monitor_state 3 pool_member_new_session_enable 2 } } [Status=Command OK]:
Thu Jul 9 10:10:05 CEST 2020		0-0	pid=20557 user=username folder=/Common module=(tmos)# status=[Command OK] cmd_data=modify ltm pool /Dev/github_issue_replace_all_with { members add { /Dev/10.0.0.2:80 { address 10.0.0.2%2 fqdn { autopopulate disabled } session user-enabled state user-up } } }:
Thu Jul 9 10:10:06 CEST 2020		0-0	client tmsh, tmsh-pid-3120, user username - transaction #4983406-2 - object 0 - create { pool_member { pool_member_pool_name "/Dev/github_issue_replace_all_with" pool_member_node_name "/Dev/10.0.0.3" pool_member_port 80 pool_member_addr 10.0.0.3%2 pool_member_autoscale 0 pool_member_monitor_state 3 pool_member_new_session_enable 2 } } [Status=Command OK]:
Thu Jul 9 10:10:06 CEST 2020		0-0	pid=3120 user=username folder=/Common module=(tmos)# status=[Command OK] cmd_data=modify ltm pool /Dev/github_issue_replace_all_with { members add { /Dev/10.0.0.3:80 { address 10.0.0.3%2 fqdn { autopopulate disabled } session user-enabled state user-up } } }:
Thu Jul 9 10:10:08 CEST 2020		0-0	client tmsh, tmsh-pid-20557, user username - transaction #4984237-2 - object 0 - create { pool_member { pool_member_pool_name "/Dev/github_issue_replace_all_with" pool_member_node_name "/Dev/10.0.0.4" pool_member_port 80 pool_member_addr 10.0.0.4%2 pool_member_autoscale 0 pool_member_monitor_state 3 pool_member_new_session_enable 2 } } [Status=Command OK]:
Thu Jul 9 10:10:08 CEST 2020		0-0	pid=20557 user=username folder=/Common module=(tmos)# status=[Command OK] cmd_data=modify ltm pool /Dev/github_issue_replace_all_with { members add { /Dev/10.0.0.4:80 { address 10.0.0.4%2 fqdn { autopopulate disabled } session user-enabled state user-up } } }:
Thu Jul 9 10:10:08 CEST 2020		0-0	pid=20344 user=root folder=/Common module=(tmos)# status=[Command OK] cmd_data=save / sys config partitions all:
Thu Jul 9 10:10:13 CEST 2020		0-0	client tmsh, tmsh-pid-20557, user username - transaction #4987204-2 - object 0 - create { pool_member { pool_member_pool_name "/Dev/github_issue_replace_all_with" pool_member_node_name "/Dev/10.0.0.5" pool_member_port 80 pool_member_addr 10.0.0.5%2 pool_member_autoscale 0 pool_member_monitor_state 3 pool_member_new_session_enable 2 } } [Status=Command OK]:
Thu Jul 9 10:10:13 CEST 2020		0-0	pid=20557 user=username folder=/Common module=(tmos)# status=[Command OK] cmd_data=modify ltm pool /Dev/github_issue_replace_all_with { members add { /Dev/10.0.0.5:80 { address 10.0.0.5%2 fqdn { autopopulate disabled } session user-enabled state user-up } } }:
Thu Jul 9 10:10:17 CEST 2020		0-0	pid=20457 user=root folder=/Common module=(tmos)# status=[Command OK] cmd_data=save / sys config partitions all:
Thu Jul 9 10:10:26 CEST 2020		0-0	pid=20519 user=root folder=/Common module=(tmos)# status=[Command OK] cmd_data=save / sys config partitions all:
```

Now those few seconds of delay might not be an issue if we only had these 5 nodes… but we have 180 😅

**Comment by ernst-at-tv2** [comment]
I've had my resident BigIP expert recreate the above in TMSH only he created 180 dummy hosts… all actions in the Audit log were timestamped to the same second ⏱️

**Comment by focrensh** [comment]
Thank you for all of the info. It looks like as you found it is performing normal functionality of the module per aggregate item in order to maintain the logic within the module.

While it is not a 1:1 of replace-all-with, would it suffice to do the additions before the removals?

You could also loop over the module for adds/removes using the original logic without aggregate in the interim.

**Comment by ernst-at-tv2** [comment]
@focrensh well it would be better, but preferably it also shouldn't take 20 minutes to run with 180 nodes/members.

We've given up trying to get it to work with this module and resorted to using the iControl REST API

```
    - name: icontrol rest replace_all_with (PUT)
      uri:
        url: "https://{{ lookup('env','F5_SERVER') }}/mgmt/tm/ltm/pool/~{{ f5_partition }}~{{ pool_name }}?ver=13.1.3.4"
        method: PUT
        headers:
          X-F5-Auth-Token: "{{ f5_token.json['token']['token'] }}"
        body:
          name: "{{ pool_name }}"
          partition: "{{ f5_partition }}"
          monitor: "/Common/tcp_half_open"
          members: "{{ lookup('template', './kube_pool_icontrol.j2') | from_yaml }}"
        body_format: json
        validate_certs: no
```
