### ISSUE TITLE
Unsupported parameters for (f5networks.f5_modules.bigip_device_info) module: ssh_keyfile found in provider

### ISSUE THREAD

**Issue by PeepOks** [F5Networks/f5-ansible#1804]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME

bigip_device_info

##### ANSIBLE VERSION

```
ansible 2.9.9
  config file = /home/ubuntu/bigip-core-config/ansible.cfg
  configured module search path = ['/home/ubuntu/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/ubuntu/.local/lib/python3.8/site-packages/ansible
  executable location = /home/ubuntu/.local/bin/ansible
  python version = 3.8.2 (default, Jul 16 2020, 14:00:26) [GCC 9.3.0]
```

##### PYTHON VERSION

```
Python 3.8.2
```

##### CONFIGURATION

```
cat ansible.cfg 
[defaults]
inventory = inventory/hosts.yaml
collections_paths = ~/.ansible/collections
deprecation_warnings = False
display_skipped_hosts = False
host_key_checking = False
```

##### OS / ENVIRONMENT

WSL: Ubuntu 20.04
##### SUMMARY

Unable to use module bigip_device_info in versions 1.4 and 1.5
```
TASK [Collect BIG-IP information] ***********************************************************************************************************************************************************************************************
fatal: [ilab-lb01.infralab.ptec -> localhost]: FAILED! => {"changed": false, "msg": "Unsupported parameters for (f5networks.f5_modules.bigip_device_info) module: ssh_keyfile found in provider. Supported parameters include: auth_provider, password, server, server_port, timeout, transport, user, validate_certs"}
```

##### STEPS TO REPRODUCE

```
---
- name: F5 core setup play
  hosts: ilab-lb01.infralab.ptec
  connection: local
  gather_facts: false
  #serial: 1

  vars:
    login_user: "admin"
    login_password: "admin"
    provider:
      server: "{{ ansible_host }}"
      server_port: 443
      validate_certs: no
      user: "{{ login_user }}"
      password: "{{ login_password }}"
      
  tasks:
    - name: Collect BIG-IP information
      f5networks.f5_modules.bigip_device_info:
        gather_subset:
          - system-info
        provider: "{{ provider }}"
      delegate_to: localhost
      register: device_facts
      check_mode: no
      tags:
        - always
```
```
ansible-playbook test-pb.yaml -i inventory/f5_inventory.py --check -v
```

##### EXPECTED RESULTS

It should not give any errors
##### ACTUAL RESULTS

```
ansible-playbook test-pb.yaml -i inventory/f5_inventory.py --check -vvvv
ansible-playbook 2.9.9
  config file = /home/ubuntu/bigip-core-config/ansible.cfg
  configured module search path = ['/home/ubuntu/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/ubuntu/.local/lib/python3.8/site-packages/ansible
  executable location = /home/ubuntu/.local/bin/ansible-playbook
  python version = 3.8.2 (default, Jul 16 2020, 14:00:26) [GCC 9.3.0]
Using /home/ubuntu/bigip-core-config/ansible.cfg as config file
setting up inventory plugins
host_list declined parsing /home/ubuntu/bigip-core-config/inventory/f5_inventory.py as it did not pass its verify_file() method
Parsed /home/ubuntu/bigip-core-config/inventory/f5_inventory.py inventory source with script plugin
Loading callback plugin default of type stdout, v2.0 from /home/ubuntu/.local/lib/python3.8/site-packages/ansible/plugins/callback/default.py

PLAYBOOK: test-pb.yaml **********************************************************************************************************************************************************************************************************
Positional arguments: test-pb.yaml
verbosity: 4
connection: smart
timeout: 10
become_method: sudo
tags: ('all',)
check: True
inventory: ('/home/ubuntu/bigip-core-config/inventory/f5_inventory.py',)
forks: 5
1 plays in test-pb.yaml

PLAY [F5 core setup play] *******************************************************************************************************************************************************************************************************
META: ran handlers
<localhost> connection transport is rest
<localhost> ESTABLISH LOCAL CONNECTION FOR USER: ubuntu
<localhost> EXEC /bin/sh -c 'echo ~ubuntu && sleep 0'
<localhost> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /home/ubuntu/.ansible/tmp `"&& mkdir /home/ubuntu/.ansible/tmp/ansible-tmp-1595922263.5418646-21308-81791141647367 && echo ansible-tmp-1595922263.5418646-21308-81791141647367="` echo /home/ubuntu/.ansible/tmp/ansible-tmp-1595922263.5418646-21308-81791141647367 `" ) && sleep 0'
Using module file /home/ubuntu/.ansible/collections/ansible_collections/f5networks/f5_modules/plugins/modules/bigip_device_info.py
<localhost> PUT /home/ubuntu/.ansible/tmp/ansible-local-21303mwjzqr9c/tmpt1v4t20h TO /home/ubuntu/.ansible/tmp/ansible-tmp-1595922263.5418646-21308-81791141647367/AnsiballZ_bigip_device_info.py
<localhost> EXEC /bin/sh -c 'chmod u+x /home/ubuntu/.ansible/tmp/ansible-tmp-1595922263.5418646-21308-81791141647367/ /home/ubuntu/.ansible/tmp/ansible-tmp-1595922263.5418646-21308-81791141647367/AnsiballZ_bigip_device_info.py && sleep 0'
<localhost> EXEC /bin/sh -c '/usr/bin/python3 /home/ubuntu/.ansible/tmp/ansible-tmp-1595922263.5418646-21308-81791141647367/AnsiballZ_bigip_device_info.py && sleep 0'
<localhost> EXEC /bin/sh -c 'rm -f -r /home/ubuntu/.ansible/tmp/ansible-tmp-1595922263.5418646-21308-81791141647367/ > /dev/null 2>&1 && sleep 0'

TASK [Collect BIG-IP information] ***********************************************************************************************************************************************************************************************
task path: /home/ubuntu/bigip-core-config/test-pb.yaml:19
fatal: [ilab-lb01.infralab.ptec -> localhost]: FAILED! => {
    "changed": false,
    "invocation": {
        "module_args": {
            "gather_subset": [
                "system-info"
            ],
            "provider": {
                "auth_provider": null,
                "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
                "server": "localhost",
                "server_port": 443,
                "ssh_keyfile": null,
                "timeout": null,
                "transport": "rest",
                "user": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
                "validate_certs": false
            }
        }
    },
    "msg": "Unsupported parameters for (f5networks.f5_modules.bigip_device_info) module: ssh_keyfile found in provider. Supported parameters include: auth_provider, password, server, server_port, timeout, transport, user, validate_certs"
}

PLAY RECAP **********************************************************************************************************************************************************************************************************************
ilab-lb01.infralab.ptec    : ok=0    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0 
```

**Comment by wojtek0806** [comment]
Remove the FQN reference to module and use this in your task and report if the issue persists:
```
---
- name: F5 core setup play
  hosts: ilab-lb01.infralab.ptec
  connection: local
  gather_facts: false
  collections:
    - f5networks.f5_modules

  vars:
    login_user: "admin"
    login_password: "admin"
    provider:
      server: "{{ ansible_host }}"
      server_port: 443
      validate_certs: no
      user: "{{ login_user }}"
      password: "{{ login_password }}"
      
  tasks:
    - name: Collect BIG-IP information
      bigip_device_info:
        gather_subset:
          - system-info
        provider: "{{ provider }}"
      register: device_facts
      check_mode: no
      tags:
        - always
```
