### ISSUE TITLE
Issue running bigip_command during BIGIP F5 OS upgrade

### ISSUE THREAD

**Issue by Rohitcmc081** [F5Networks/f5-ansible#1805]
##### ISSUE TYPE

 - Bug Report

 

##### COMPONENT NAME

''' < --- bigip_command --> '''
< ANSIBLE VERSION
```
<!--- ansible-playbook 2.8.13
  config file = /root/F5/ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /bin/ansible-playbook
  python version = 2.7.5 (default, Sep 26 2019, 13:23:47) [GCC 4.8.5 20150623 (Red Hat 4.8.5-39)]
Using /root/F5/ansible.cfg as config file -->

``` >



##### PYTHON VERSION
<!--- Python 2.7.5 -->
```

```

##### BIGIP VERSION
<!---
Sys::Version
Main Package
  Product     BIG-IP
  Version     15.1.0.4
  Build       0.0.6
  Edition     Point Release 4 -->
```

```

##### CONFIGURATION
<!---
[defaults]
inventory = ./hosts
host_key_checking = False
timeout = 10
deprecation_warnings=False -->

##### OS / ENVIRONMENT
<!--- BIGIP VE-200M -->

##### SUMMARY
<!--- While executing the command " cpcfg --source=HD1.15-1-0-3 --reboot HD1.15 " under bigip_command module and sub-module commands , warning encountered with [WARNING]: Using "write" commands is not idempotent. You should use a module that is specifically made for that. If such a module does not
exist, then please file a bug. The command in question is "cpcfg --source=HD1.15-1-0-3 --reboot HD1..." 
ok: [F5] => {"changed": false, "executed_commands": ["tmsh -c \\\"cpcfg --source=HD1.15-1-0-3 --reboot HD1.15\\\""], "stdout": ["Syntax Error: unexpected argument \"cpcfg\""], "stdout_lines": [["Syntax Error: unexpected argument \"cpcfg\""]]} 
-- >


##### STEPS TO REPRODUCE
<!---
---

- name: GRAB F5 FACTS
  hosts: bigips
  connection: local
  gather_facts: false
  vars: 
    provider:
      server: "{{ ansible_host }}"
      user: "{{ bigip_username }}"
      password: "{{ bigip_password }}"
      server_port: "{{ server_port}}"
      validate_certs: "{{ certificate }}"

  tasks:
    - name: Save the running configuration
      bigip_config:
        save: yes
        provider: "{{ provider }}"

    - name: Upload absolute image to the BIG-IP
      bigip_software_image:
        image:  BIGIP-15.1.0.3-0.0.12.iso
        provider: "{{ provider }}"
      tags:
        - upload_bigip

    - name: Installs the BIG-IP OS
      bigip_software_install:
        image: BIGIP-15.1.0.3-0.0.12.iso
        volume: HD1.15
        state:  installed
        provider: "{{ provider }}"
      tags:
        - install_bigip

    - name: Copy the config from HD15-1-0-3 to HD1.15 cpcfg --source=HD1.15-1-0-3 --reboot HD1.15    
      bigip_command: 
        commands: cpcfg --source=HD1.15-1-0-3 --reboot HD1.15
        provider: "{{ provider }}"
      ignore_errors: True
      register: cpcfg
-->

<!--- ---

- name: GRAB F5 FACTS
  hosts: bigips
  connection: local
  gather_facts: false
  vars: 
    provider:
      server: "{{ ansible_host }}"
      user: "{{ bigip_username }}"
      password: "{{ bigip_password }}"
      server_port: "{{ server_port}}"
      validate_certs: "{{ certificate }}"

  tasks:
    - name: Save the running configuration
      bigip_config:
        save: yes
        provider: "{{ provider }}"

    - name: Upload absolute image to the BIG-IP
      bigip_software_image:
        image:  BIGIP-15.1.0.3-0.0.12.iso
        provider: "{{ provider }}"
      tags:
        - upload_bigip

    - name: Installs the BIG-IP OS
      bigip_software_install:
        image: BIGIP-15.1.0.3-0.0.12.iso
        volume: HD1.15
        state:  installed
        provider: "{{ provider }}"
      tags:
        - install_bigip

    - name: Copy the config from HD15-1-0-3 to HD1.15 cpcfg --source=HD1.15-1-0-3 --reboot HD1.15    
      bigip_command: 
        commands: cpcfg --source=HD1.15-1-0-3 --reboot HD1.15
        provider: "{{ provider }}"
      ignore_errors: True
      register: cpcfg -->
```

##### EXPECTED RESULTS

''' BIGIP should copy the config from current volume HD1.15-1-0-3 to the new volume HD1.15 and reload the device  with new volume  '''

##### ACTUAL RESULTS

```
 [root@network_team_auto_platform F5]# ansible-playbook test.yml -vvvv
ansible-playbook 2.8.13
  config file = /root/F5/ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /bin/ansible-playbook
  python version = 2.7.5 (default, Sep 26 2019, 13:23:47) [GCC 4.8.5 20150623 (Red Hat 4.8.5-39)]
Using /root/F5/ansible.cfg as config file
setting up inventory plugins
host_list declined parsing /root/F5/hosts as it did not pass it's verify_file() method
script declined parsing /root/F5/hosts as it did not pass it's verify_file() method
auto declined parsing /root/F5/hosts as it did not pass it's verify_file() method
Parsed /root/F5/hosts inventory source with ini plugin
Loading callback plugin default of type stdout, v2.0 from /usr/lib/python2.7/site-packages/ansible/plugins/callback/default.pyc

PLAYBOOK: test.yml *****************************************************************************************************************************
Positional arguments: test.yml
become_method: sudo
inventory: (u'/root/F5/hosts',)
forks: 5
tags: (u'all',)
verbosity: 4
connection: smart
timeout: 10
1 plays in test.yml

PLAY [GRAB F5 FACTS] ***************************************************************************************************************************
META: ran handlers

TASK [Save the running configuration] **********************************************************************************************************
task path: /root/F5/test.yml:16
<X.X.X.X> connection transport is rest
<X.X.X.X> ESTABLISH LOCAL CONNECTION FOR USER: root
<X.X.X.X> EXEC /bin/sh -c 'echo ~root && sleep 0'
<X.X.X.X> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /root/.ansible/tmp `"&& mkdir /root/.ansible/tmp/ansible-tmp-1596028833.69-30307-108926364969834 && echo ansible-tmp-1596028833.69-30307-108926364969834="` echo /root/.ansible/tmp/ansible-tmp-1596028833.69-30307-108926364969834 `" ) && sleep 0'
<F5> Attempting python interpreter discovery
<X.X.X.X> EXEC /bin/sh -c 'echo PLATFORM; uname; echo FOUND; command -v '"'"'/usr/bin/python'"'"'; command -v '"'"'python3.7'"'"'; command -v '"'"'python3.6'"'"'; command -v '"'"'python3.5'"'"'; command -v '"'"'python2.7'"'"'; command -v '"'"'python2.6'"'"'; command -v '"'"'/usr/libexec/platform-python'"'"'; command -v '"'"'/usr/bin/python3'"'"'; command -v '"'"'python'"'"'; echo ENDFOUND && sleep 0'
<X.X.X.X> EXEC /bin/sh -c '/usr/bin/python && sleep 0'
Using module file /usr/lib/python2.7/site-packages/ansible/modules/network/f5/bigip_config.py
<X.X.X.X> PUT /root/.ansible/tmp/ansible-local-30298yTjKEA/tmptzQ_j9 TO /root/.ansible/tmp/ansible-tmp-1596028833.69-30307-108926364969834/AnsiballZ_bigip_config.py
<X.X.X.X> EXEC /bin/sh -c 'chmod u+x /root/.ansible/tmp/ansible-tmp-1596028833.69-30307-108926364969834/ /root/.ansible/tmp/ansible-tmp-1596028833.69-30307-108926364969834/AnsiballZ_bigip_config.py && sleep 0'
<X.X.X.X> EXEC /bin/sh -c '/usr/bin/python /root/.ansible/tmp/ansible-tmp-1596028833.69-30307-108926364969834/AnsiballZ_bigip_config.py && sleep 0'
<X.X.X.X> EXEC /bin/sh -c 'rm -f -r /root/.ansible/tmp/ansible-tmp-1596028833.69-30307-108926364969834/ > /dev/null 2>&1 && sleep 0'
changed: [F5] => {
    "ansible_facts": {
        "discovered_interpreter_python": "/usr/bin/python"
    }, 
    "changed": true, 
    "invocation": {
        "module_args": {
            "auth_provider": null, 
            "merge_content": null, 
            "password": null, 
            "provider": {
                "auth_provider": null, 
                "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER", 
                "proxy_to": null, 
                "server": "X.X.X.X", 
                "server_port": 443, 
                "ssh_keyfile": null, 
                "timeout": null, 
                "transport": "rest", 
                "user": "admin", 
                "validate_certs": false
            }, 
            "reset": false, 
            "save": true, 
            "server": null, 
            "server_port": null, 
            "transport": null, 
            "user": null, 
            "validate_certs": null, 
            "verify": false
        }
    }, 
    "stdout": [
        "Saving running configuration...\n  /config/bigip.conf\n  /config/bigip_base.conf\n  /config/bigip_user.conf\n  /config/partitions/Test/bigip.conf\n  /config/partitions/Test/bigip_base.conf\nSaving Ethernet map ...done\nSaving PCI map ...\n - verifying checksum .../var/run/f5pcimap: OK\ndone\n - saving ...done\n"
    ], 
    "stdout_lines": [
        [
            "Saving running configuration...", 
            "  /config/bigip.conf", 
            "  /config/bigip_base.conf", 
            "  /config/bigip_user.conf", 
            "  /config/partitions/Test/bigip.conf", 
            "  /config/partitions/Test/bigip_base.conf", 
            "Saving Ethernet map ...done", 
            "Saving PCI map ...", 
            " - verifying checksum .../var/run/f5pcimap: OK", 
            "done", 
            " - saving ...done", 
            ""
        ]
    ]
}

TASK [Upload absolute image to the BIG-IP] *****************************************************************************************************
task path: /root/F5/test.yml:21
<X.X.X.X> connection transport is rest
<X.X.X.X> ESTABLISH LOCAL CONNECTION FOR USER: root
<X.X.X.X> EXEC /bin/sh -c 'echo ~root && sleep 0'
<X.X.X.X> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /root/.ansible/tmp `"&& mkdir /root/.ansible/tmp/ansible-tmp-1596028840.07-30341-237730887256990 && echo ansible-tmp-1596028840.07-30341-237730887256990="` echo /root/.ansible/tmp/ansible-tmp-1596028840.07-30341-237730887256990 `" ) && sleep 0'
Using module file /usr/lib/python2.7/site-packages/ansible/modules/network/f5/bigip_software_image.py
<X.X.X.X> PUT /root/.ansible/tmp/ansible-local-30298yTjKEA/tmpOpLmwC TO /root/.ansible/tmp/ansible-tmp-1596028840.07-30341-237730887256990/AnsiballZ_bigip_software_image.py
<X.X.X.X> EXEC /bin/sh -c 'chmod u+x /root/.ansible/tmp/ansible-tmp-1596028840.07-30341-237730887256990/ /root/.ansible/tmp/ansible-tmp-1596028840.07-30341-237730887256990/AnsiballZ_bigip_software_image.py && sleep 0'
<X.X.X.X> EXEC /bin/sh -c '/usr/bin/python /root/.ansible/tmp/ansible-tmp-1596028840.07-30341-237730887256990/AnsiballZ_bigip_software_image.py && sleep 0'
<X.X.X.X> EXEC /bin/sh -c 'rm -f -r /root/.ansible/tmp/ansible-tmp-1596028840.07-30341-237730887256990/ > /dev/null 2>&1 && sleep 0'
ok: [F5] => {
    "changed": false, 
    "invocation": {
        "module_args": {
            "auth_provider": null, 
            "force": null, 
            "image": "BIGIP-15.1.0.3-0.0.12.iso", 
            "password": null, 
            "provider": {
                "auth_provider": null, 
                "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER", 
                "proxy_to": null, 
                "server": "X.X.X.X", 
                "server_port": 443, 
                "ssh_keyfile": null, 
                "timeout": null, 
                "transport": "rest", 
                "user": "admin", 
                "validate_certs": false
            }, 
            "server": null, 
            "server_port": null, 
            "state": "present", 
            "transport": null, 
            "user": null, 
            "validate_certs": null
        }
    }
}

TASK [Installs the BIG-IP OS] ******************************************************************************************************************
task path: /root/F5/test.yml:28
<X.X.X.X> connection transport is rest
<X.X.X.X> ESTABLISH LOCAL CONNECTION FOR USER: root
<X.X.X.X> EXEC /bin/sh -c 'echo ~root && sleep 0'
<X.X.X.X> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /root/.ansible/tmp `"&& mkdir /root/.ansible/tmp/ansible-tmp-1596028840.99-30365-31814697451882 && echo ansible-tmp-1596028840.99-30365-31814697451882="` echo /root/.ansible/tmp/ansible-tmp-1596028840.99-30365-31814697451882 `" ) && sleep 0'
Using module file /usr/lib/python2.7/site-packages/ansible/modules/network/f5/bigip_software_install.py
<X.X.X.X> PUT /root/.ansible/tmp/ansible-local-30298yTjKEA/tmppzyzlq TO /root/.ansible/tmp/ansible-tmp-1596028840.99-30365-31814697451882/AnsiballZ_bigip_software_install.py
<X.X.X.X> EXEC /bin/sh -c 'chmod u+x /root/.ansible/tmp/ansible-tmp-1596028840.99-30365-31814697451882/ /root/.ansible/tmp/ansible-tmp-1596028840.99-30365-31814697451882/AnsiballZ_bigip_software_install.py && sleep 0'
<X.X.X.X> EXEC /bin/sh -c '/usr/bin/python /root/.ansible/tmp/ansible-tmp-1596028840.99-30365-31814697451882/AnsiballZ_bigip_software_install.py && sleep 0'
<X.X.X.X> EXEC /bin/sh -c 'rm -f -r /root/.ansible/tmp/ansible-tmp-1596028840.99-30365-31814697451882/ > /dev/null 2>&1 && sleep 0'
ok: [F5] => {
    "changed": false, 
    "invocation": {
        "module_args": {
            "auth_provider": null, 
            "image": "BIGIP-15.1.0.3-0.0.12.iso", 
            "password": null, 
            "provider": {
                "auth_provider": null, 
                "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER", 
                "proxy_to": null, 
                "server": "X.X.X.X", 
                "server_port": 443, 
                "ssh_keyfile": null, 
                "timeout": null, 
                "transport": "rest", 
                "user": "admin", 
                "validate_certs": false
            }, 
            "server": null, 
            "server_port": null, 
            "state": "installed", 
            "transport": null, 
            "user": null, 
            "validate_certs": null, 
            "volume": "HD1.15"
        }
    }
}

TASK [Copy the config from HD15-1-0-3 to HD1.15 cpcfg --source=HD1.15-1-0-3 --reboot HD1.15] ***************************************************
task path: /root/F5/test.yml:37
<X.X.X.X> connection transport is rest
<X.X.X.X> ESTABLISH LOCAL CONNECTION FOR USER: root
<X.X.X.X> EXEC /bin/sh -c 'echo ~root && sleep 0'
<X.X.X.X> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /root/.ansible/tmp `"&& mkdir /root/.ansible/tmp/ansible-tmp-1596028841.98-30390-251510548692159 && echo ansible-tmp-1596028841.98-30390-251510548692159="` echo /root/.ansible/tmp/ansible-tmp-1596028841.98-30390-251510548692159 `" ) && sleep 0'
Using module file /usr/lib/python2.7/site-packages/ansible/modules/network/f5/bigip_command.py
<X.X.X.X> PUT /root/.ansible/tmp/ansible-local-30298yTjKEA/tmpjhpUOq TO /root/.ansible/tmp/ansible-tmp-1596028841.98-30390-251510548692159/AnsiballZ_bigip_command.py
<X.X.X.X> EXEC /bin/sh -c 'chmod u+x /root/.ansible/tmp/ansible-tmp-1596028841.98-30390-251510548692159/ /root/.ansible/tmp/ansible-tmp-1596028841.98-30390-251510548692159/AnsiballZ_bigip_command.py && sleep 0'
<X.X.X.X> EXEC /bin/sh -c '/usr/bin/python /root/.ansible/tmp/ansible-tmp-1596028841.98-30390-251510548692159/AnsiballZ_bigip_command.py && sleep 0'
<X.X.X.X> EXEC /bin/sh -c 'rm -f -r /root/.ansible/tmp/ansible-tmp-1596028841.98-30390-251510548692159/ > /dev/null 2>&1 && sleep 0'
[WARNING]: Using "write" commands is not idempotent. You should use a module that is specifically made for that. If such a module does not
exist, then please file a bug. The command in question is "cpcfg --source=HD1.15-1-0-3 --reboot HD1..."

ok: [F5] => {
    "changed": false, 
    "executed_commands": [
        "tmsh -c \\\"cpcfg --source=HD1.15-1-0-3 --reboot HD1.15\\\""
    ], 
    "invocation": {
        "module_args": {
            "auth_provider": null, 
            "chdir": null, 
            "commands": "cpcfg --source=HD1.15-1-0-3 --reboot HD1.15", 
            "interval": 1, 
            "match": "all", 
            "password": null, 
            "provider": {
                "auth_provider": null, 
                "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER", 
                "proxy_to": null, 
                "server": "X.X.X.X", 
                "server_port": 443, 
                "ssh_keyfile": null, 
                "timeout": null, 
                "transport": "rest", 
                "user": "admin", 
                "validate_certs": false
            }, 
            "retries": 10, 
            "server": null, 
            "server_port": null, 
            "transport": "rest", 
            "user": null, 
            "validate_certs": null, 
            "wait_for": null, 
            "warn": true
        }
    }, 
    "stdout": [
        "Syntax Error: unexpected argument \"cpcfg\""
    ], 
    "stdout_lines": [
        [
            "Syntax Error: unexpected argument \"cpcfg\""
        ]
    ]
}
META: ran handlers
META: ran handlers

PLAY RECAP *************************************************************************************************************************************
F5                         : ok=4    changed=1    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0     -->

```
