### ISSUE TITLE
bigip_software_image uploaded image with 600 instead of 644

### ISSUE THREAD

**Issue by jhtut** [F5Networks/f5-ansible#1811]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME
bigip_software_image

##### ANSIBLE VERSION

```
ansible 2.8.5
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/d649534/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, Aug  7 2019, 08:19:52) [GCC 4.8.5 20150623 (Red Hat 4.8.5-39.0.1)]
```

##### PYTHON VERSION

```
$ python -V
Python 2.7.5
```

##### BIGIP VERSION

```
12.1.5.2
```

##### CONFIGURATION
N/A

##### OS / ENVIRONMENT
Centos

##### SUMMARY
bigip_software_image module is used to upload the image from Centos machine to Big-IP 4200 which has 2 guests.  When try to install the image in guest, I'm hit with emerg logger: Re-starting lind in log.  Found this KB https://support.f5.com/csp/article/K75051412 and when I manually set the file permission to 644 to the image in Host, everything is fine.  I believe, it is to do with bigip_software_image not updating the file permission correctly.

##### STEPS TO REPRODUCE

```
---
  - name: Get F5 Image and Volume
    hosts: f5
    gather_facts: no
    connection: local
    vars_files:
      - secrets/all/vault.yml

    vars_prompt: 
      - name: "target_image"
        prompt: "BIG-IP Software file absolute or relative path to playbook"
        default: "BIGIP-12.1.5.2-0.0.10.iso"
        private: no

    tasks:
      - name: Set password for provider
        set_fact:
          f5_provider:
            user: "{{ username }}"
            password: "{{ password }}"
            server: "{{ inventory_hostname }}"
            timeout: 120
            validate_certs: no
            transport: "rest"
            server_port: 443

      - name: Get Software Volume
        bigip_device_facts:
          gather_subset:
            - software-volumes
          provider: "{{ f5_provider }}"
        delegate_to: localhost
        register: bigip_software_volume
        tags: [get,upload,install]
   
      - name: Set Target Volume
        set_fact:
          target_volume: "{{ item.full_path }}"
        loop: "{{ bigip_software_volume.software_volumes }}"
        when: item.active == "no"
        tags: [upload,install]

      - name: Upload image in to the BIG-IP
        bigip_software_image:
          image: "{{ target_image }}"
          provider: "{{ f5_provider }}"
        delegate_to: localhost
        tags: [upload]
```

##### EXPECTED RESULTS

Software image is uploaded successfully with file permission 644.

##### ACTUAL RESULTS

Software image is uploaded with file permission 600.
-rw-------. 2 root root     2094788608 2020-08-03 08:27 BIGIP-12.1.5.2-0.0.10.iso

```

```
