### ISSUE TITLE
bigip_virtual_server is not being idempotent

### ISSUE THREAD

**Issue by fjinkis** [F5Networks/f5-ansible#1813]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

bigip_virtual_server

##### ANSIBLE VERSION

```
ansible 2.9.10
  config file = /home/fjinkis/ansible/legacy_switch_test/ansible.cfg
  configured module search path = [u'/home/fjinkis/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, Aug  4 2017, 00:39:18) [GCC 4.8.5 20150623 (Red Hat 4.8.5-16)]
```

##### PYTHON VERSION

```
Python 2.7.5
```

##### BIGIP VERSION

```
Sys::Version
Main Package
  Product     BIG-IP
  Version     13.1.3.1
  Build       0.0.4
  Edition     Point Release 1
  Date        Mon Aug 26 12:24:07 PDT 2019
```

##### OS / ENVIRONMENT

$ cat /etc/os-release 
NAME="CentOS Linux"
VERSION="7 (Core)"
$ cat /etc/redhat-release 
CentOS Linux release 7.4.1708 (Core)

##### SUMMARY

The execution of a playbook twice is not idempotent. Virtual Server module always reports changes.

##### STEPS TO REPRODUCE

Simple playbook to deploy nodes, pools and virtual servers.

```
- name: "Deploy balanced service"
  hosts: bigip
  connection: local
  gather_facts: no

tasks:
    - name: ENSURE NODE EXISTENCE
      bigip_node:
        provider: "{{ bigip_provider }}"
        address: "{{ item.address }}"
        name: "{{ item.name }}"
        description: "{{ item.optional_desc | default('') }}"
        partition: "{{ global_partition }}"
        monitors: "{{ item.optional_monitors | default('/Common/icmp'.split()) }}"
        state: "{{ global_action }}"
      loop: "{{ nodes }}"
      tags:
        - node

    - name: ENSURE POOL EXISTENCE
      bigip_pool:
        provider: "{{ bigip_provider }}"
        name: "{{ item.name }}"
        partition: "{{ global_partition }}"
        lb_method: "{{ item.optional_lb_method | default('round-robin') }}"
        description: "{{ item.optional_desc | default('') }}"
        monitors: "{{ item.optional_monitors | default('/Common/gateway_icmp'.split()) }}"
        slow_ramp_time: "{{ item.optional_slow_ramp_time | default('10') }}"
        state: "{{ global_action }}"
      loop: "{{ pools }}"
      tags:
        - pool
    
    - name: ENSURE POOLS ARE MEMBERS
      bigip_pool_member:
        provider: "{{ bigip_provider }}"
        partition: "{{ global_partition }}"
        pool: "{{ item.pool }}"
        name: "{{ item.name }}"
        address: "{{ item.address }}"
        port: "{{ item.port }}"
        ratio: "{{ item.optional_ratio | default('1') }}"
        priority_group: "{{ item.optional_priority_group | default('0') }}"
        connection_limit: "{{ item.optional_connection_limit | default('0') }}"
        state: "{{ global_action }}"
      loop: "{{ nodes }}"
      tags:
        - node
        - pool

    #FOR NOW, ASUMME SNAT, PROFILES, IRULES AND POLICIES. I WILL NOT CREATE A TASK TO KEEP THEIR STATE
    - name: ENSURE VIRTUAL SERVERS
      bigip_virtual_server:
        provider: "{{ bigip_provider }}"
        partition: "{{ global_partition }}"
        name: "{{ item.name }}"
        destination: "{{ item.cidr }}"
        description: "{{ item.optional_desc | default('') }}"
        ip_protocol: "{{ item.optional_proto | default('tcp') }}"
        pool: "{{ item.pool }}"
        port: "{{ item.optional_port | default('0') }}"
        profiles: "{{ item.optional_profiles | default('tcp'.split()) }}"
        snat: "{{ item.snat_pool }}"
        state: "{{ global_action }}"
        insert_metadata: no
      loop: "{{ virtual_servers }}"
      tags:
        - pool
        - virtual_server
```

##### EXPECTED RESULTS

After two consecutive executions, I should receive an OK in every task.

##### ACTUAL RESULTS

Change reported over virtual server

```

```
