### ISSUE TITLE
Ansible module for bandwidth control policies

### ISSUE THREAD

**Issue by dbarboza** [F5Networks/f5-ansible#1815]
##### ISSUE TYPE
 - Feature Idea

##### ANSIBLE VERSION
```
ansible 2.9.11
```

##### PYTHON VERSION

```
Python 2.7.17
```

##### BIGIP VERSION

```
Sys::Version
Main Package
  Product     BIG-IP
  Version     15.1.0.4
  Build       0.21.6
  Edition     Engineering Hotfix
  Date        Mon Jul  6 23:16:20 PDT 2020

Hotfix List
ID886841-1
```

##### OS / ENVIRONMENT

N/A
##### SUMMARY
There is no module to create a bandwidth control policy and bigip_command must be used instead:

##### STEPS TO REPRODUCE

```
- name: Create metal bandwidth policies
  bigip_command:
    commands:
      - "create net bwc policy testPolicy dynamic enabled max-rate '1000gbps' max-user-rate '600mbps' "
```

##### EXPECTED RESULTS
Expected testPolicy (which already exists) to be updated with the values given.

##### ACTUAL RESULTS
The bigip_command task creates the policy on the first run but will never modify the policy

```
[WARNING]: Using "write" commands is not idempotent. You should use a module that is specifically made for that. If such a module does not exist, then please file a bug. The command in question is
"create net bwc policy ..."
```
