### ISSUE TITLE
bigip_asm_policy_import broken in v1.5?

### ISSUE THREAD

**Issue by amolari** [F5Networks/f5-ansible#1821]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

bigip_asm_policy_import
from collection v1.5 and devel-1.6
##### ANSIBLE VERSION

```
ansible 2.9.9
```

##### PYTHON VERSION

```
python version = 3.6.8 
```

##### BIGIP VERSION

```
14.1.2.6
```

##### OS / ENVIRONMENT

N/A
##### SUMMARY

With collection v1.5 or above, the ASM policy files won't be uploaded to /var/config/rest/downloads/.
I've seen the change https://github.com/F5Networks/f5-ansible/commit/92a380e620fa2ac0dd3787fa41bda28973e93d58
If I revert the change from
`url = 'https://{0}:{1}/mgmt/tm/asm/file-transfer/uploads'.format(`
to
`url = 'https://{0}:{1}/mgmt/shared/file-transfer/uploads'.format(`
I'll see the file being uploaded to /var/config/rest/downloads/.

Additionally, threre is also an issue that if the policy is already existing and in use (bound to a VS) on the BIG-IP I always see a policy import error (with parameter force=yes). That was no issue in v1.3

##### STEPS TO REPRODUCE

```
- name: Upload new or existing ASM policy
  bigip_asm_policy_import:
    provider: "{{ provider }}"
    name: "{{ (item.path | basename | splitext)[0] }}"
    source: "{{ item.path }}"
    force: yes
  retries: 3
  delay: 120
  loop: "{{ files_matched.files|flatten(levels=1) }}"
  loop_control:
    label: "{{ item.path }}"
  delegate_to: localhost

```

##### EXPECTED RESULTS

TASK [bigip_waf_sync : Upload new or modified ASM policies] ********************
changed: [63.33.210.100] => (item=/tmp/deployment/repos/waf-test/WAF_generic_policy.xml)

which is seen when I use collection v1.3 (however, if the policy has a change, the policy won't be applied)

##### ACTUAL RESULTS

no xml files seen in `/var/config/rest/downloads/`, but if I perform the above mentioned change in the module code, I can see the files being uploaded to /var/config/rest/downloads/

```
failed: [63.33.210.100] (item=/tmp/deployment/repos/waf-test/WAF_generic_policy.xml) => {"ansible_loop_var": "item", "changed": false, "item": {"atime": 1597391083.0576146, "ctime": 1597357023.3633165, "dev": 47, "gid": 0, "gr_name": "root", "inode": 123119, "isblk": false, "ischr": false, "isdir": false, "isfifo": false, "isgid": false, "islnk": false, "isreg": true, "issock": false, "isuid": false, "mode": "0644", "mtime": 1597357023.3633165, "nlink": 1, "path": "/tmp/deployment/repos/waf-test/WAF_generic_policy.xml", "pw_name": "root", "rgrp": true, "roth": true, "rusr": true, "size": 785341, "uid": 0, "wgrp": false, "woth": false, "wusr": true, "xgrp": false, "xoth": false, "xusr": false}, "msg": "Failed to import ASM policy."}
```
