### ISSUE TITLE
bigip_device_info for "ltm-pools" extremely slow, RFE for improved performance

### ISSUE THREAD

**Issue by arunhotra** [F5Networks/f5-ansible#1827]
##### ISSUE TYPE

 - Bug Report
 - Feature Idea

##### COMPONENT NAME

bigip_device_info

##### ANSIBLE VERSION

```
2.9.2

```

##### PYTHON VERSION

```
3.7
```

##### BIGIP VERSION

```
all versions
```

##### OS / ENVIRONMENT

N/A

##### SUMMARY

Once the pool number is high (e.g. > 100), this module takes a long time to run - even though we are just getting "ltm-pools". This makes this module very difficult to use for testing/validation when there are a lot of pools.
 
For example, I tested with 1000 pools and it took 22 mins to run. I also tested just with 50 pools and it still takes about 5 mins. 

##### STEPS TO REPRODUCE

```
- name: COLLECT BIG-IP ltm Pools for "{{ inventory_hostname }}" using the FACTS module
  bigip_device_info:
    provider:
      server: "{{ inventory_hostname }}"
      user: "{{ username }}"
      password: "{{ password }}"
      validate_certs: no
    gather_subset:
      - ltm-pools
  register: pools
```

##### EXPECTED RESULTS

This is the only idempotent module used for validation/facts. This needs better performance if it can be successfully used for validation.

##### ACTUAL RESULTS

Takes a long time
