### ISSUE TITLE
bigip_command: Escaping special characters

### ISSUE THREAD

**Issue by simonkowallik** [F5Networks/f5-ansible#1861]
##### ISSUE TYPE

 - Bug Report
 - Documentation Report

##### COMPONENT NAME
`bigip_command`

##### ANSIBLE VERSION

```
2.9.x
```

##### PYTHON VERSION

```
python 3.8
```

##### BIGIP VERSION

```
13.1.x, 14.1.x
```

##### SUMMARY
escaping special characters is common, unfortunately with `bigip_command` multiple levels of escape sequences are required.

In the below example the tmsh wildcard configuration identifier `*` is part of the `key` field.

##### STEPS TO REPRODUCE

In tmsh the following works:
```shell
modify ltm data-group internal dg_string records add { "my test\*string" { data "value" } }
```

Same task in a playbook:

```yaml
  tasks:
    - name: run bigip command
      delegate_to: localhost
      bigip_command:
        provider: "{{ provider }}"
        commands:
          - modify ltm data-group internal dg_string records add { "my test\*string" { data "value" } }
```

##### EXPECTED RESULTS
It is expected that the command in playbook works in the same way as the tmsh command.

##### ACTUAL RESULTS
The command / playbook fails with:
```
status=[Command OK] cmd_data=run util bash -c "tmsh -c \"modify ltm data-group internal test_uri records add {/string/* {} }\""
Syntax Error: the \"create\" command does not accept wildcard configuration identifiers
```

##### SOLUTION
The backslash to escape the wildcard configuration identifier `*` must be escaped as well. Unfortunately this requires multiple escapes ending in 7 (!!) required backslashes.

```yaml
  tasks:
    - name: run bigip command
      delegate_to: localhost
      bigip_command:
        provider: "{{ provider }}"
        commands:
          - modify ltm data-group internal dg_string records add { "my test\\\\\\\*string" { data "value" } }
```

##### IMPROVEMENT
1. Could this be improved to avoid this without breaking existing implementations which already take care of the multi-level escapes?
2. As an alternative: Improve documentation with explicit information about this requirement and examples?
