### ISSUE TITLE
bigip_policy_rule - add the "disable server_ssl" action

### ISSUE THREAD

**Issue by BapRx** [F5Networks/f5-ansible#1876]
##### ISSUE TYPE

 - Feature Idea

##### COMPONENT NAME

bigip_policy_rule
##### ANSIBLE VERSION

```
ansible 2.10.1
  config file = /home/user/ansible-for-f5/ansible.cfg
  configured module search path = ['/home/user/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.7/dist-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 3.7.3 (default, Jul 25 2020, 13:03:44) [GCC 8.3.0]
```

##### PYTHON VERSION

```
Python 3.7.3
```

##### BIGIP VERSION

```
  Product     BIG-IP
  Version     14.1.2.6
```

##### SUMMARY

We need to trigger the action "disable server_ssl", I opened an issue months ago which was rejected: #1637

##### STEPS TO REPRODUCE

```
- name: Add rule without SSL.
  bigip_policy_rule:
    provider: "{{ provider }}"
    policy: "{{ item.1.policy_name }}"
    name: '{{ rule_name }}'
    conditions:
      - type: http_host
        host_is_any: "{{ item.1.host }}"
    actions:
      **- type: disable
        target: server_ssl**
      - type: forward
        pool: "{{ item.1.pool_name }}"
```

##### EXPECTED RESULTS

```
ltm policy policy_01 {
    rules {
        rule_01 {
            actions {
                0 {
                    server-ssl
                    disable
                }
                1 {
                    forward
                    select
                    pool Pool_01
                }
            }
            conditions {
                0 {
                    http-host
                    host
                    values { example.org }
                }
            }
            ordinal 0
        }
    }
}
```
##### ACTUAL RESULTS

```

```
