### ISSUE TITLE
bigip_policy_rule - add "request" event to the "reset" action

### ISSUE THREAD

**Issue by BapRx** [F5Networks/f5-ansible#1877]
##### ISSUE TYPE

 - Feature Idea

##### COMPONENT NAME

bigip_policy_rule
##### ANSIBLE VERSION

```
ansible 2.10.1
  config file = /home/user/ansible-for-f5/ansible.cfg
  configured module search path = ['/home/user/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.7/dist-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 3.7.3 (default, Jul 25 2020, 13:03:44) [GCC 8.3.0]
```

##### PYTHON VERSION

```
Python 3.7.3
```

##### BIGIP VERSION

```
  Product     BIG-IP
  Version     14.1.2.6
```

##### SUMMARY

We need to trigger the action "disable server_ssl", I opened an issue months ago which was rejected: #1637
We can't use the event currently implemented :
https://github.com/F5Networks/f5-ansible/blob/4d5f4ea5e039a71640acd9997e47da9a78de1427/ansible_collections/f5networks/f5_modules/plugins/modules/bigip_policy_rule.py#L690
because we need to check other conditions and it would trigger the following error:
```
failed: [10.33.49.75] (item=policy_01) => changed=false
  ansible_loop_var: item
  item: policy_01
  msg: '010716e2:3: Policy ''/Common/Drafts/policy_01'', rule ''DropAll''; defines an action which occurs before one of its conditions, or before a condition in an earlier rule with lower ID.'
```
##### STEPS TO REPRODUCE

```
- name: Add rule without SSL.
  bigip_policy_rule:
    provider: "{{ provider }}"
    policy: "{{ item.1.policy_name }}"
    name: '{{ rule_name }}'
    conditions:
      - type: http_host
        host_is_any: "{{ item.1.host }}"
    actions:
      **- type: disable
        target: server_ssl**
      - type: forward
        pool: "{{ item.1.pool_name }}"
```

##### EXPECTED RESULTS

```
ltm policy policy_01 {
    rules {
        DropAll {
            actions {
                0 {
                    shutdown
                    connection
                }
            }
            ordinal 12
        }
    }
}
```
##### ACTUAL RESULTS

```

```
