### ISSUE TITLE
bigip_policy_rule - Ansible converting list of strings to string

### ISSUE THREAD

**Issue by BapRx** [F5Networks/f5-ansible#1878]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

bigip_policy_rule
##### ANSIBLE VERSION

```
ansible 2.10.1
  config file = /home/user/ansible-for-f5/ansible.cfg
  configured module search path = ['/home/user/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.7/dist-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 3.7.3 (default, Jul 25 2020, 13:03:44) [GCC 8.3.0]
```

##### PYTHON VERSION

```
Python 3.7.3
```

##### BIGIP VERSION

```
  Product     BIG-IP
  Version     14.1.2.6
```

##### SUMMARY

Since the version 2.8 of Ansible, a string conversion is applied when the provided argument type is not matching the expected one.
As a result, when I use the module `bigip_policy_rule `with the `path_begins_with_any` condition, my list of strings is converted to a string.
I managed to make it work by adding the expected type in the following line :
https://github.com/F5Networks/f5-ansible/blob/f381f8eb1c5131e090a5f409e221f6c4d6b605b7/ansible_collections/f5networks/f5_modules/plugins/modules/bigip_policy_rule.py#L1290
`path_begins_with_any=dict(),` -> `path_begins_with_any=dict(type="list"),`.

##### STEPS TO REPRODUCE

```
- name: Add policy rule.
  bigip_policy_rule:
    provider: "{{ provider }}"
    policy: policy_01
    name: rule_01
    conditions:
      - type: http_uri
        path_begins_with_any:
          - /TOTO
          - /TATA
          - /TITI
      - type: http_host
        host_is_any: example.org
    actions:
      - type: forward
        pool: pool_01

```

##### EXPECTED RESULTS

```
TASK [policy : Add policy rule.] ***********************************************************************************************************************************************************************************************
changed: [10.xx.xx.xx]

```
##### ACTUAL RESULTS

```
TASK [policy : Add policy rule.] ***********************************************************************************************************************************************************************************************
changed: [10.xx.xx.xx]
[WARNING]: The value "['/TOTO', '/TATA', '/TITI']" (type list) was converted to "u"['/TOTO', '/TATA', '/TITI']"" (type string). If this does not look like what you expect, quote the entire value to ensure it does not change.
```

```

```
