### ISSUE TITLE
bigip_command module possibly ignoring transport: cli 

### ISSUE THREAD

**Issue by s-archer** [F5Networks/f5-ansible#1913]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

bigip_command module

##### ANSIBLE VERSION

```
ansible 2.10.2
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/Users/archer/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /Users/archer/.local/lib/python3.8/site-packages/ansible
  executable location = /Users/archer/.local/bin//ansible
  python version = 3.8.6 (default, Oct 20 2020, 16:44:08) [Clang 12.0.0 (clang-1200.0.32.2)]
```

##### PYTHON VERSION

```
Python 3.8.6
```

##### BIGIP VERSION

```
Product: BIG-IP
Version: 15.1.0.4
Build: 0.0.6
Sequence: 15.1.0.4-0.0.6.0
BaseBuild: 0.0.6
Edition: Point Release 4
```

##### CONFIGURATION
[defaults]
private_key_file = ~/.ssh/id_rsa
host_key_checking = False
callback_whitelist = profile_tasks, timer
stdout_callback = debug

##### OS / ENVIRONMENT

Mac Catalina 10.15.7

##### SUMMARY

I have an Ansible playbook that uses the bigip_command module with transport: cli yet I’m getting an unexpected  HTTP 401 error that suggests the module is using the API and not the CLI.

##### STEPS TO REPRODUCE

```
  - name: CHECK FOR READY SIGNAL FILE - CHECK EVERY 10 (MAX 600)
    bigip_command:
      commands:
        - "run /util bash -c 'test -f /tmp/f5-cloud-libs-signals/ADMIN_CREATED && echo ADMIN_CREATED'"
      wait_for:
        - result contains ADMIN_CREATED
      interval: 10
      retries: 60
      provider:
        server: "{{ inventory_hostname }}"
        user: "{{ bigip_user }}"
        #password: "{{ bigip_pass }}"
        transport: cli
        ssh_keyfile: "{{ ssh_key_file_path }}"
        validate_certs: no
    register: ssh_output
    delegate_to: localhost
```

##### EXPECTED RESULTS

command success
##### ACTUAL RESULTS

```
TASK [CHECK FOR READY SIGNAL FILE - CHECK EVERY 10 (MAX 600)] ****************************************************************************************************************************************************************************************************************************************
task path: **removed**
Tuesday 03 November 2020  14:13:54 +0000 (0:00:00.576)       0:03:04.419 ******
Trying secret <ansible.parsing.vault.PromptVaultSecret object at 0x10b53a130> for vault_id=default
Trying secret <ansible.parsing.vault.PromptVaultSecret object at 0x10b53a130> for vault_id=default
Trying secret <ansible.parsing.vault.PromptVaultSecret object at 0x10b53a130> for vault_id=default
redirecting (type: action) ansible.builtin.bigip to f5networks.f5_modules.bigip
redirecting (type: action) ansible.builtin.bigip to f5networks.f5_modules.bigip
Loading collection ansible.netcommon from <**removed**>/.local/lib/python3.8/site-packages/ansible_collections/ansible/netcommon
<localhost> connection transport is cli
<3.11.76.168> using connection plugin network_cli
redirecting (type: connection) ansible.builtin.persistent to ansible.netcommon.persistent
<3.11.76.168> starting connection from persistent connection plugin
Found ansible-connection at path <**removed**>/.local/bin/ansible-connection
<3.11.76.168> local domain socket does not exist, starting it
<3.11.76.168> control socket path is <**removed**>/.ansible/pc/381ddab9b9
<3.11.76.168> redirecting (type: connection) ansible.builtin.network_cli to ansible.netcommon.network_cli
<3.11.76.168> Loading collection ansible.netcommon from <**removed**>/.local/lib/python3.8/site-packages/ansible_collections/ansible/netcommon
<3.11.76.168> redirecting (type: terminal) ansible.builtin.bigip to f5networks.f5_modules.bigip
<3.11.76.168> Loading collection f5networks.f5_modules from <**removed**>/.local/lib/python3.8/site-packages/ansible_collections/f5networks/f5_modules
<3.11.76.168> local domain socket listeners started successfully
<3.11.76.168> unable to load cliconf for network_os bigip
<3.11.76.168>
<3.11.76.168> local domain socket path is <**removed**>/.ansible/pc/381ddab9b9
<3.11.76.168> socket_path: <**removed**>/.ansible/pc/381ddab9b9
<localhost> ESTABLISH LOCAL CONNECTION FOR USER: <**removed**>
<localhost> EXEC /bin/sh -c 'echo ~<**removed**> && sleep 0'
<localhost> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo <**removed**>/.ansible/tmp `"&& mkdir "` echo <**removed**>/.ansible/tmp/ansible-tmp-1604412840.768887-28175-25378511022919 `" && echo ansible-tmp-1604412840.768887-28175-25378511022919="` echo <**removed**>/.ansible/tmp/ansible-tmp-1604412840.768887-28175-25378511022919 `" ) && sleep 0'
redirecting (type: modules) ansible.builtin.bigip_command to f5networks.f5_modules.bigip_command
redirecting module_util ansible.module_utils.network.common.parsing to ansible_collections.ansible.netcommon.plugins.module_utils.network.common.parsing
redirecting module_util ansible.module_utils.network.common.parsing to ansible_collections.ansible.netcommon.plugins.module_utils.network.common.parsing
redirecting module_util ansible.module_utils.network.common.utils to ansible_collections.ansible.netcommon.plugins.module_utils.network.common.utils
redirecting module_util ansible.module_utils.network.common.utils to ansible_collections.ansible.netcommon.plugins.module_utils.network.common.utils
redirecting module_util ansible.module_utils.network.common.config to ansible_collections.ansible.netcommon.plugins.module_utils.network.common.config
redirecting module_util ansible.module_utils.network.common.config to ansible_collections.ansible.netcommon.plugins.module_utils.network.common.config
redirecting module_util ansible.module_utils.network.common.config to ansible_collections.ansible.netcommon.plugins.module_utils.network.common.config
redirecting module_util ansible.module_utils.network.common.utils to ansible_collections.ansible.netcommon.plugins.module_utils.network.common.utils
redirecting module_util ansible.module_utils.network.common.utils to ansible_collections.ansible.netcommon.plugins.module_utils.network.common.utils
Using module file <**removed**>/.local/lib/python3.8/site-packages/ansible_collections/f5networks/f5_modules/plugins/modules/bigip_command.py
<localhost> PUT <**removed**>/.ansible/tmp/ansible-local-27513kmo4sg81/tmp_av1g_xv TO <**removed**>/.ansible/tmp/ansible-tmp-1604412840.768887-28175-25378511022919/AnsiballZ_bigip_command.py
<localhost> EXEC /bin/sh -c 'chmod u+x <**removed**>/.ansible/tmp/ansible-tmp-1604412840.768887-28175-25378511022919/ <**removed**>/.ansible/tmp/ansible-tmp-1604412840.768887-28175-25378511022919/AnsiballZ_bigip_command.py && sleep 0'
<localhost> EXEC /bin/sh -c 'AWS_ACCESS_KEY_ID=<**removed**> AWS_SECRET_ACCESS_KEY=<**removed**> AWS_REGION=eu-west-2 <**removed**>/.pyenv/versions/3.8.6/bin/python <**removed**>/.ansible/tmp/ansible-tmp-1604412840.768887-28175-25378511022919/AnsiballZ_bigip_command.py && sleep 0'
FAILED - RETRYING: CHECK FOR READY SIGNAL FILE - CHECK EVERY 10 (MAX 600) (5 retries left).Result was: {
    "attempts": 1,
    "changed": false,
    "invocation": {
        "module_args": {
            "chdir": null,
            "commands": [
                "run /util bash -c 'test -f /tmp/f5-cloud-libs-signals/ADMIN_CREATED && echo ADMIN_CREATED'"
            ],
            "interval": 10,
            "match": "all",
            "provider": {
                "auth_provider": null,
                "password": null,
                "server": "3.11.76.168",
                "server_port": null,
                "ssh_keyfile": "<**removed**>/.ssh/id_rsa",
                "timeout": null,
                "transport": "cli",
                "user": "admin",
                "validate_certs": false
            },
            "retries": 60,
            "wait_for": [
                "result contains ADMIN_CREATED"
            ],
            "warn": true
        }
    },
    "retries": 6
}
 
MSG:
 
b'<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">\n<html><head>\n<title>401 Unauthorized</title>\n</head><body>\n<h1>Unauthorized</h1>\n<p>This server could not verify that you\nare authorized to access the document\nrequested.  Either you supplied the wrong\ncredentials (e.g., bad password), or your\nbrowser doesn\'t understand how to supply\nthe credentials required.</p>\n</body></html>\n'
```

**Comment by focrensh** [comment]
I just tested using the 1.6 Collection and had no issue with the below playbook. Are you able to confirm your collection version?

```
$ ansible-galaxy collection list
Collection            Version
--------------------- -------
ansible.netcommon     1.4.1  
f5networks.f5_modules 1.6.0  
```

Playbook used for testing:
```
- name: test command
  hosts: localhost
  gather_facts: false
  connection: local

  collections:
    - f5networks.f5_modules

  vars:
    provider:
      server: mybigip
      user: admin
      transport: cli
      ssh_keyfile: /Users/me/.ssh/id_rsa

  tasks:

  - name : test Command
    bigip_command:
      provider: "{{ provider }}"
      commands:
        - "run /util bash -c 'test -f /tmp/f5-cloud-libs-signals/ADMIN_CREATED && echo ADMIN_CREATED'"
    delegate_to: localhost

```

Output Summary
```
ok: [localhost] => {
    "changed": false,
    "executed_commands": [
        "run /util bash -c 'test -f /tmp/f5-cloud-libs-signals/ADMIN_CREATED && echo ADMIN_CREATED'"
    ],
```
