### ISSUE TITLE
The provided name must be a valid FQDN

### ISSUE THREAD

**Issue by ktreese** [F5Networks/f5-ansible#1920]
##### ISSUE TYPE
 - Feature Idea

##### COMPONENT NAME
bigip_gtm_wide_ip

##### ANSIBLE VERSION
```
ansible 2.9.11
  config file = /Users/reesek/.ansible.cfg
  configured module search path = ['/Users/reesek/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /Users/reesek/miniconda2/envs/ansible2.9/lib/python3.8/site-packages/ansible
  executable location = /Users/reesek/miniconda2/envs/ansible2.9/bin/ansible
  python version = 3.8.3 (default, Jul  2 2020, 11:26:31) [Clang 10.0.0 ]
```

##### PYTHON VERSION

```
Python 3.8.3
```

##### BIGIP VERSION

```
Sys::Version
Main Package
  Product     BIG-IP
  Version     12.1.1
  Build       2.0.204
  Edition     Hotfix HF2
  Date        Fri Oct 21 17:35:48 PDT 2016

Hotfix List
ID600859-4    ID606110-3  ID614599    ID593355    ID599033-3  ID575170-5
ID595064-1    ID513851-2  ID607857-1  ID605314-2  ID599033-4  ID602653-3
ID599068-2    ID599054-4  ID590608-3  ID597708-4  ID603605-1  ID612952-1
ID596814-5    ID601938-8  ID603997    ID599769-1  ID601927-8  ID603605-2
ID594910-4    ID513851-3  ID606509-1  ID589318-2  ID624264-2  ID600859-3
ID596674-1    ID527403-1  ID623048    ID434573-6  ID599068-3  ID612564
ID609677-1    ID585366-2  ID606110-4  ID601927-1  ID606807-1  ID609325
ID596814-9    ID598294-2  ID622529    ID610307    ID607200-1  ID604459-1
ID575170-2    ID590578-5  ID590074-2  ID613127-3  ID598294-1  ID590578-4
ID600778-2    ID585120-2  ID597309-2  ID595394-4  ID608373-2  ID592716-1
ID321971-1    ID608373-1  ID585120-1  ID604211-4  ID595394-2  ID599054-2
ID600778-1    ID606509-3  ID601309    ID589318-1  ID601938-2  ID521270-1
ID618382-4    ID595064-2  ID593355-2  ID602061    ID605682-3  ID604211-3
ID542097-3    ID585366    ID590608-1  ID603997-3  ID561444-1  ID589149-2
ID594910-1    ID590074-1  ID605682-2  ID599769  
```

##### OS / ENVIRONMENT

MacOS

##### SUMMARY

`bigip_gtm_wide_ip` doesn't support wildcard type a wide ips

##### STEPS TO REPRODUCE

Create a wildcard type a wide ip, such as: `*.apps.reese.com`, and attempt to change out the pool for that wide ip.

```
    - name: Setting Maintenance Window Pool for The Platform
      bigip_gtm_wide_ip:
        pool_lb_method: round-robin
        name: "*.apps.reese.com"
        type: a
        pools:
          - name: maint-tst.wwt.com_443_pool
        provider:
          server: prdgtm-device.mycompany.com
          user: admin
          password: password
          validate_certs: false
      delegate_to: localhost
```

##### EXPECTED RESULTS

The command would succeed in swapping out the pool.

##### ACTUAL RESULTS

```
TASK [Setting Maintenance Window Pool for The Platform] *****************************************************************************************************************************************************************************
Thursday 19 November 2020  21:24:42 -0600 (0:00:04.931)       0:00:08.146 ***** 
fatal: [localhost]: FAILED! => {"changed": false, "msg": "The provided name must be a valid FQDN"}
```
