### ISSUE TITLE
bigip_device_certificate restarts httpd but does not change device object name

### ISSUE THREAD

**Issue by ktreese** [F5Networks/f5-ansible#1929]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME
- bigip_device_certificate

##### ANSIBLE VERSION

```
(ansible2.9) ➜  f5-config git:(device_trust_refactor) ansible --version
ansible 2.9.15
  config file = None
  configured module search path = ['/Users/reesek/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /Users/reesek/opt/miniconda3/envs/ansible2.9/lib/python3.9/site-packages/ansible
  executable location = /Users/reesek/opt/miniconda3/envs/ansible2.9/bin/ansible
  python version = 3.9.0 (default, Nov 15 2020, 06:25:35) [Clang 10.0.0 ]
```

##### PYTHON VERSION

```
(ansible2.9) ➜  f5-config git:(device_trust_refactor) python -V
Python 3.9.0
```

##### BIGIP VERSION

```
Sys::Version
Main Package
  Product     BIG-IP
  Version     15.1.1
  Build       0.0.6
  Edition     Point Release 0
  Date        Thu Oct  8 02:52:59 PDT 2020
```

##### CONFIGURATION

None

##### OS / ENVIRONMENT

MacOS

##### SUMMARY

While using Ansible to configure a freshly deployed vcmp guest (and thus bypass use of the GUI Setup Utility), the Identity Certificate retains `CN=bigip1` and the Device Name also retains the name `bigip1`.

```
[root@us-stl-f5-sndltm-int01:/S2-green-P::Active:Standalone] config # tmsh list /cm trust-domain all
cm trust-domain Root {
    ca-cert dtca.crt
    ca-cert-bundle dtca-bundle.crt
    ca-devices { /Common/bigip1 }
    ca-key dtca.key
    status standalone
    trust-group device_trust_group
}
```

It seems while using the setup utility, this is changed and updated to that of the assigned hostname upon supplying a root account password/confirm and clicking the `Next...` button within the "Platform" section of the Setup utility:

```
Dec  2 15:28:14 slot2/us-stl-f5-sndltm-int01.wwt.com info devmgmtd[4166]: 015a0000:6: Changing device object name from '/Common/bigip1' to '/Common/us-stl-f5-sndltm-int01.mycompany.com'
```

and thusly.

```
[root@us-stl-f5-sndltm-int01:/S2-green-P::Active:Standalone] config # tmsh list /cm trust-domain all
cm trust-domain Root {
    ca-cert dtca.crt
    ca-cert-bundle dtca-bundle.crt
    ca-devices { /Common/us-stl-f5-sndltm-int01.mycompany.com }
    ca-key dtca.key
    status standalone
    trust-group device_trust_group
}
```

This can't seem to be replicated via the ansible modules.

##### STEPS TO REPRODUCE

```
---
- hosts: dc1
  connection: local
  gather_facts: false
  tasks:
    - name: Create vCMP guest
      bigip_vcmp_guest:
      name: "{{ inventory_hostname }}"
     initial_image: "{{ image }}"
     allowed_slots:
       - '1'
       - '2'
       - '3'
     cores_per_slot: 4
     vlans: "{{ vlans }}"
     mgmt_network: bridged
     mgmt_address: "{{ guest_mgmt_ip }}/24"
     mgmt_route: "{{ datacenters[datacenter]['vcmp_management_gateway'] }}"
     state: present
     provider: "{{ vcmp_host_provider }}"
  
  - name: Configure the expired admin and root accounts
    block:
      - name: Configure the expired admin password
        uri:
          url: "https://{{ inventory_hostname }}/mgmt/shared/authz/users/admin"
          method: PATCH
          body: '{ "oldPassword": "admin", "password": "{{ guest_password }}" }'
          body_format: json
          validate_certs: no
          force_basic_auth: yes
          user: admin
          password: admin
          headers:
            Content-Type: "application/json"
        register: _result
        until: _result.status == 200
        retries: 12 # 12 * 5 seconds = 1min
        delay: 5 # Every 5 seconds

      - name: Configure the root user's password
        bigip_user:
          username_credential: root
          password_credential: "{{ guest_password }}"
          provider:
            server: "{{ inventory_hostname }}"
            user: admin
            password: "{{ guest_password }}"
            validate_certs: false
        delegate_to: localhost
    when: reset_passwords

  - name: Force create a new certificate to replace not expired certificate
    bigip_device_certificate:
      days_valid: 3650
      new_cert: yes
      force: yes
      issuer:
        country: US
        state: MO
        common_name: us-stl-f5-sndltm-int01.mycompany.com
        organization: Company
        division: IT Infrastructure & Security
        locality: St. Louis
        email: email@email.com
      provider:
        password: "{{ vcmp_guest_provider.password }}"
        server: us-stl-f5-sndltm-int01.mycompany.com
        user: root
        transport: cli
    delegate_to: localhost
```

##### EXPECTED RESULTS

```
[root@us-stl-f5-sndltm-int01:/S2-green-P::Active:Standalone] config # tmsh list /cm trust-domain all
cm trust-domain Root {
    ca-cert dtca.crt
    ca-cert-bundle dtca-bundle.crt
    ca-devices { /Common/us-stl-f5-sndltm-int01.mycompany.com }
    ca-key dtca.key
    status standalone
    trust-group device_trust_group
}
```

##### ACTUAL RESULTS

The modules runs to succession, however, the expected config on the F5 is not as expected.  Again, when manually setting a device certificate within the `Device Certificates` section of the GUI Setup Utility, followed by completing the `Platform` section, the Root trust-domain ca-devices is updated from `/Common/bigip1` to `/Common/us-stl-f5-sndltm-int01.mycompany.com`.  It's not clear where this should be taken care of within Ansible.

```

```

**Comment by ktreese** [comment]
Pressing of the `Next...` button in the Platform section of the setup utility performs the following as captures in /var/log/ltm.  It doesn't seem Ansible replicates this behavior:

```
Dec  2 15:28:13 slot2/us-stl-f5-sndltm-int01.wwt.com warning mcpd[4434]: 01071031:4: Security setting systemauth.disablerootlogin has been disabled by user admin
Dec  2 15:28:14 slot2/us-stl-f5-sndltm-int01.wwt.com info devmgmtd[4166]: 015a0000:6: Changing device object name from '/Common/bigip1' to '/Common/us-stl-f5-sndltm-int01.mycompany.com'
Dec  2 15:28:14 slot2/us-stl-f5-sndltm-int01.wwt.com notice sod[4433]: 010c0056:5: Deactivating traffic group traffic-group-1.
Dec  2 15:28:14 slot2/us-stl-f5-sndltm-int01.wwt.com notice sod[4433]: 010c0057:5: Activating traffic group traffic-group-1.
Dec  2 15:28:14 slot2/us-stl-f5-sndltm-int01.wwt.com notice sod[4433]: 010c0054:5: Offline for traffic group traffic-group-1.
Dec  2 15:28:14 slot2/us-stl-f5-sndltm-int01.wwt.com notice sod[4433]: 010c006d:5: Leaving Offline for Active for dbvar not redundant.
Dec  2 15:28:14 slot2/us-stl-f5-sndltm-int01.wwt.com notice sod[4433]: 010c0053:5: Active for traffic group traffic-group-1.
Dec  2 15:28:18 slot2/us-stl-f5-sndltm-int01.wwt.com info devmgmtd[4166]: 015a0000:6: Initial trust configuration created.
Dec  2 15:28:18 slot2/us-stl-f5-sndltm-int01.wwt.com info devmgmtd[4166]: 015a0000:6: Recreating CA certificate bundle
Dec  2 15:28:18 slot2/us-stl-f5-sndltm-int01.wwt.com info devmgmtd[4166]: 015a0000:6: resetDeviceLocal complete
```

**Comment by ktreese** [comment]
It seems we were able to find a solution to this issue.  I think the problem really lies with the `bigip_vcmp_guest` module NOT updating the DSC device name when it sets the hostname.  

However, we found within [devcentral](https://devcentral.f5.com/s/question/0D51T00006j32lO/device-name-under-device-management) that the `bigip_hostname` Ansible module DOES change the device name even though **it's not documented that it does this**.

Knowing this, we removed the subdomain extension from the name attribute of the `bigip_vcmp_guest` module (added a regex filter to remove .mycompany.com) as follows.  We did this because the value of **name** attribute sets the hostname of the device (more on this later).

```
- name: Create vCMP guest
  bigip_vcmp_guest:
    name: "{{ inventory_hostname | regex_replace('.mycompany.com') }}"
    initial_image: "{{ image }}"
    allowed_slots:
      - "1"
      - "2"
      - "3"
    cores_per_slot: 4
    vlans: "{{ vlans }}"
    mgmt_network: bridged
    mgmt_address: "{{ guest_mgmt_ip }}/24"
    mgmt_route: "{{ datacenters[datacenter]['vcmp_management_gateway'] }}"
    state: present
    provider: "{{ vcmp_host_provider }}
```

This allowed us to use the `bigip_hostname` module to set the hostname to our fqdn.  We wanted to do this because if the **name** attribute supplied in the `bigip_vcmp_guest` _is the same as_ the **hostname** attribute in the `bigip_hostname` module, then `bigip_hostname` is **NOT idempotent** and will not affect a change, thus would not invoke the undocumented part of the `bigip_hostname` module that also updates the DSC device name.  To avoid idempotency here, this is why we shaved off the domain in our `bigip_vcmp_guest` declaration.

```
- name: Set hostname of the guest
  bigip_hostname:
    hostname: "{{ inventory_hostname }}"
    provider: "{{ vcmp_guest_provider }}"
  delegate_to: localhost
  register: hostname_updated
```

After this, we restart the cm trust-domain root via a bigip_command:

```
- name: Restart cm trust-domain Root
  bigip_command:
    commands: restart /cm trust-domain Root
    provider: "{{ vcmp_guest_provider }}"
  delegate_to: localhost
  when: hostname_updated.change
```

And this forces a regeneration of the Identity Certificate and gets us to the behavior we expect.
