### ISSUE TITLE
Bash unexpected argument, unable to run bigip_command as Manager

### ISSUE THREAD

**Issue by vidarno** [F5Networks/f5-ansible#1944]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
bigip_command

##### ANSIBLE VERSION
```
ansible 2.9.16
  config file = /home/user/ansible/ansible.cfg
  configured module search path = [u'/home/user/ansible/library']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, Aug 13 2020, 02:51:10) [GCC 4.8.5 20150623 (Red Hat 4.8.5-39)]
```

##### PYTHON VERSION
```
Python 2.7.5
```

##### BIGIP VERSION
```
Sys::Version
Main Package
  Product     BIG-IP
  Version     14.1.2.7
  Build       0.0.5
  Edition     Point Release 7
  Date        Wed Aug  5 12:43:40 PDT 2020
```

##### OS / ENVIRONMENT
N/A

##### SUMMARY
Using raw/curl to modify server-ssl profile to set autenticate-name works with
```
- name: Set authenticate name
     raw: curl -sk https://mybigip.local/mgmt/tm/ltm/profile/server-ssl/~mypartition~foo_serverssl -X PATCH -H "Content-Type:application/json" -d '{"authenticate-name":"bar.foo"}' -H 'X-F5-Auth-Token:{{bigiptoken}}'
```
But using bigip_command with the same user, which has Manager-permission on the specified partition results in bash-error.

##### STEPS TO REPRODUCE

```
- name: Set authenticate name
     f5networks.f5_modules.bigip_command:
       chdir: mypartition
       commands: "modify /ltm profile server-ssl foo_serverssl authenticate-name bar.foo"
       provider: "{{ provider }}"
```

##### EXPECTED RESULTS
Should modify existing server-ssl profile by setting authenticate-name value

##### ACTUAL RESULTS

```
fatal: [mybigip.local]: FAILED! => {"changed": false, "msg": "\"bash\" unexpected argument"}

```

**Comment by nmenant** [comment]
Hi,

here is a working example: 

``` 
---

- hosts: default
  gather_facts: false
  vars: 
    provider:
      server: 192.168.143.154
      user: admin
      password: xxxxxxx
      validate_certs: no
      server_port: 443

  tasks:

    - name: change authenticate-name to ServerSSL Profile
      f5networks.f5_modules.bigip_command:
        provider: "{{ provider }}"
        commands: 
          - modify /ltm profile server-ssl /test_ansible_ssl/testssl_SSLProfile authenticate-name test.ansible
      delegate_to: localhost

``` 

A few things to highlight: 

- I tested with a BIG-IP v14.1.X and f5_modules v1.7.1
- Since you get a Bash error, it's more likely that you have a syntax issue somewhere
- my user test_ssl is a manager for the test_ansible_ssl partition
- while it's not required when using TMSH on the device to specify the Partition name, it is required via ansible. if you were to use _"modify /ltm profile server-ssl testssl_SSLProfile authenticate-name test.ansible"_ you would get the following error message in /var/log/ltm "_Jan 18 03:03:22 bigip.lab-nico.fr err tmsh[26132]: 01420006:3: 01020036:3: The requested ServerSSL Profile (/Common/testssl_SSLProfile) was not found._"

Let me know if you can mitigate the issue that you're facing. It's not a bug in our ansible modules from my testing
