### ISSUE TITLE
bigip_asm_policy_signature_set not removing signature sets from ASM policy

### ISSUE THREAD

**Issue by gpekarcsik** [F5Networks/f5-ansible#1956]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
bigip_asm_policy_signature_set

##### ANSIBLE VERSION
```
ansible 2.9.1
```

##### PYTHON VERSION

```
Python 2.7.5
```

##### BIGIP VERSION
```
  Version     15.1.0.5
```

##### CONFIGURATION
N/A

##### OS / ENVIRONMENT
Red Hat Enterprise Linux Server release 7.9 (Maipo)

##### SUMMARY
The ansible module bigip_asm_policy_signature_set does not remove the attack signature set from the ASM policy when running the module with the state set to absent.  I am able to add a signature set to an ASM policy when I use the state set to present.  

##### STEPS TO REPRODUCE

```
  - name: Remove Signature Set from ASM Policy to update it
    bigip_asm_policy_signature_set:
      name: "{{ sig_name }}"
      policy_name: Test1-Lab
      partition: Common
      state: absent
      provider:
        user: *********
        password: **********
        server: f5labdevice
        server_port: 443
        validate_certs: no
    delegate_to: localhost
    register: removesig
```

##### EXPECTED RESULTS

The signature set should be removed from the ASM policy. 

##### ACTUAL RESULTS

The module runs and return a status of changed: false, and failed: false.  When looking at the ASM policy on the F5 device, the signature set was not removed from the policy.

```
ok: [sdc01waftlta01x -> localhost] => {
    "ansible_facts": {
        "discovered_interpreter_python": "/usr/bin/python"
    },
    "changed": false,
    "invocation": {
        "module_args": {
            "alarm": null,
            "block": null,
            "learn": null,
            "name": "High Accuracy Signatures",
            "partition": "Common",
            "policy_name": "Test1-Lab",
            "provider": {
                "auth_provider": null,
                "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
                "server": "f5labdevice",
                "server_port": 443,
                "ssh_keyfile": null,
                "timeout": null,
                "transport": "rest",
                "user": "**********",
                "validate_certs": false
            },
            "state": "absent"
        }
    }
}
```

**Comment by trinaths** [comment]
Created INFRAANO-178 for PM tracking

**Comment by wojtek0806** [comment]
@gpekarcsik 
The issue is that under the hood when attaching some signatures to policy BIG-IP will attach additional signature sets on its own, for example when attaching "High Accuracy Signatures" to a new policy, like in the example playbook: 
```
---
- name: Start Tests
  gather_facts: no
  hosts: all
  connection: local

  vars:
    provider:
      password: "admin"
      server: "{{ ansible_host }}"
      user: "admin"
      validate_certs: "no"
      server_port: "8443"

  tasks:
    - name: Create Policy
      bigip_asm_policy_manage:
        name: Test1
        state: present
        provider: "{{ provider }}"
  
    - name: Add Signature Set from ASM Policy
      bigip_asm_policy_signature_set:
        name: "High Accuracy Signatures"
        policy_name: Test1
        provider: "{{ provider }}"
```


When the signature-sets subcollection on policy is queried with Postman it returns the following, see below that the Policy has 2 sets of signatures attached to it:

```
{
    "kind": "tm:asm:policies:signature-sets:signature-setcollectionstate",
    "selfLink": "https://localhost/mgmt/tm/asm/policies/6k9DBocL3keTcKGFNPJvow/signature-sets?ver=15.1.2",
    "totalItems": 2,
    "items": [
        {
            "signatureSetReference": {
                "link": "https://localhost/mgmt/tm/asm/signature-sets/hWVIjEEwOOU58BcLVnXztg?ver=15.1.2",
                "name": "High Accuracy Signatures"
            },
            "lastUpdateMicros": 1.614683987e+15,
            "selfLink": "https://localhost/mgmt/tm/asm/policies/6k9DBocL3keTcKGFNPJvow/signature-sets/ruZZu2GnP46ZB-zXN5zQnA?ver=15.1.2",
            "kind": "tm:asm:policies:signature-sets:signature-setstate",
            "alarm": true,
            "block": true,
            "id": "ruZZu2GnP46ZB-zXN5zQnA",
            "learn": true
        },
        {
            "signatureSetReference": {
                "link": "https://localhost/mgmt/tm/asm/signature-sets/NZlPqTTKcjePnB1BfDWl0A?ver=15.1.2",
                "name": "Generic Detection Signatures (High/Medium Accuracy)"
            },
            "lastUpdateMicros": 1.61468397e+15,
            "selfLink": "https://localhost/mgmt/tm/asm/policies/6k9DBocL3keTcKGFNPJvow/signature-sets/R-pNJJT0nt0zsUTygsUZUQ?ver=15.1.2",
            "kind": "tm:asm:policies:signature-sets:signature-setstate",
            "alarm": true,
            "block": true,
            "id": "R-pNJJT0nt0zsUTygsUZUQ",
            "learn": true
        }
    ]
}
```
When running the play to remove the desired set:
```
    - name: Remove Signature Set from ASM Policy to update it
      bigip_asm_policy_signature_set:
        name: "High Accuracy Signatures"
        policy_name: Test1
        state: absent
        provider: "{{ provider }}"

```

POSTMAN query returns the signature set as removed so the module works as intended:
```
{
    "kind": "tm:asm:policies:signature-sets:signature-setcollectionstate",
    "selfLink": "https://localhost/mgmt/tm/asm/policies/6k9DBocL3keTcKGFNPJvow/signature-sets?ver=15.1.2",
    "totalItems": 1,
    "items": [
        {
            "signatureSetReference": {
                "link": "https://localhost/mgmt/tm/asm/signature-sets/NZlPqTTKcjePnB1BfDWl0A?ver=15.1.2",
                "name": "Generic Detection Signatures (High/Medium Accuracy)"
            },
            "lastUpdateMicros": 1.61468397e+15,
            "selfLink": "https://localhost/mgmt/tm/asm/policies/6k9DBocL3keTcKGFNPJvow/signature-sets/R-pNJJT0nt0zsUTygsUZUQ?ver=15.1.2",
            "kind": "tm:asm:policies:signature-sets:signature-setstate",
            "alarm": true,
            "block": true,
            "id": "R-pNJJT0nt0zsUTygsUZUQ",
            "learn": true
        }
    ]
}
```
If you want to remove all signature sets from Policy you need to be explicit unfortunately. However the module does what it says, it removes any signature sets you ask it to remove and most likely what you see in GUI is the other collection still present.
