### ISSUE TITLE
bigip_imish_config chops off last chars in lines to be added when target device runs 14.1.3.1

### ISSUE THREAD

**Issue by jussisjostrom** [F5Networks/f5-ansible#1964]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
bigip_imish_config

##### ANSIBLE VERSION

```
$ ansible --version
ansible 2.9.6
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/jussi/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 3.8.5 (default, Jul 28 2020, 12:59:40) [GCC 9.3.0]
```

##### PYTHON VERSION

```
$ python3 -V
Python 3.8.5
```

##### BIGIP VERSION

```
# tmsh show sys version

Sys::Version
Main Package
  Product     BIG-IP
  Version     14.1.3.1
  Build       0.0.8
  Edition     Point Release 1
  Date        Wed Dec  9 19:13:18 PST 2020
```

##### CONFIGURATION
$ env | grep ANSIBLE
ANSIBLE_VAULT_PASSWORD_FILE=./.vault_pass.txt

No edits have been made to ansible.cfg.

##### OS / ENVIRONMENT
$ uname -a
Linux ansible02 5.4.0-65-generic #73-Ubuntu SMP Mon Jan 18 17:25:17 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
$ cat /etc/issue
Ubuntu 20.04.2 LTS \n \l

Ansible installed from the Ubuntu package.

f5networks.f5_modules collection has been added using ansible-galaxy, 
```
{
 "collection_info": {
  "namespace": "f5networks",
  "name": "f5_modules",
  "version": "1.7.1",
  ...
```

##### SUMMARY

Some lines to be added to config using a task with bigip_imish_config, has the last character chopped off, resulting in that, depending on the line to be added, either the wrong value ends up in running-config or the line is reject from being added.
Example:
```
    - name: Community-lists 
      f5networks.f5_modules.bigip_imish_config:
        provider: "{{ provider }}"
        route_domain: "0"
        lines:
          - ip community-list standard EXTERNALROUTE permit 64883:1111
          - ip community-list standard SVCVREDISKERNEL permit 64883:2222
          - ip community-list standard DUMMY permit 64883:9999
        save_when: modified
      delegate_to: localhost
      register: outputimish
```
results in this being added:
```
!
ip community-list standard DUMMY permit 64883:999
ip community-list standard EXTERNALROUTE permit 64883:1111
ip community-list standard SVCVREDISKERNEL permit 64883:2222
!
```
As you see, the value for the DUMMY community has been chopped off the last character, instead of 9999 as requested, 999 is in config. 
Adding the DUMMY community acts as a workaround so that I get the two other community-lists in there correctly.
It seems it is usually the last line in the lines-list.

I see this issue after I upgraded to target devices to 14.1.3.1 from 14.1.2.8, the playbook tasks worked correctly when trget devices ran the earlier version.

##### STEPS TO REPRODUCE

```
https://gist.github.com/jussisjostrom/4b9d2a2cc04d0cdca5fab2b5cb5aac2d
```

##### EXPECTED RESULTS

Expected that the exact lines specified in the task would be added as-is to the running config of the zebos.
```
ip community-list standard DUMMY permit 64883:9999
ip community-list standard EXTERNALROUTE permit 64883:1111
ip community-list standard SVCVREDISKERNEL permit 64883:2222
```
To achieve expected results, I can in many cases (as this example) just add one extra character to the line, but that is not very logical. 

##### ACTUAL RESULTS

Last of the lines ends up wrong in config

```
ip community-list standard DUMMY permit 64883:999
```
