### ISSUE TITLE
The last_resort_pool parameter in bigip_gtm_wide_ip is now required?

### ISSUE THREAD

**Issue by mkf-fjell** [F5Networks/f5-ansible#1994]
##### COMPONENT NAME

f5networks.f5_modules.bigip_gtm_wide_ip

##### ANSIBLE VERSION

```
3.7.2
```
##### BIGIP VERSION

```
14.1.4
```
##### CONFIGURATION

N/A
##### OS / ENVIRONMENT

N/A
##### SUMMARY

Upgraded F5 BIG-IP DNS from 14.1.2.6 to 14.1.4 and the module bigip_gtm_wide_ip started to produce errors and failed when trying to create a wideip. This did not occur in 14.1.2.6.  Looks like 14.1.4 requires the last_resort_pool set with a value:

{
    "msg": "b'{\"code\":400,\"message\":\"\\\\\"last-resort-pool\\\\\" requires a value\",\"errorStack\":[],\"apiError\":26214401}'",
    "invocation": {
        "module_args": {

In our environment to work properly we need to be able to set last_resort_pool to the default (None).   The TMSH command to do this is:
 modify gtm wideip a [wideip name] { last-resort-pool none }

I need to know what string to assign the last_resort_pool parameter in Ansible code to do this ( set to None)
I've tried all these but none of these work so hopefully someone can help me with this.  F5 case been submitted 3/18/21 but no traction yet.
    last_resort_pool: "none"
    last_resort_pool: none
    last_resort_pool: ""
    last_resort_pool: "None"
    last_resort_pool: None
    last_resort_pool: ''
    last_resort_pool:

##### STEPS TO REPRODUCE

```

- name: create gtm A record
  f5networks.f5_modules.bigip_gtm_wide_ip:
    name:  "{{ f5_base_name }}.{{ f5_gtm_suffix }}"
    state: present
    type: a
    pools: "{{ f5_gtm_pools }}"
    pool_lb_method: "{% if f5_multi_dc | bool %}global-availability{% else %}round-robin{% endif %}"
    # last_resort_pool: "none"
    # last_resort_pool: none
    # last_resort_pool: ""
    # last_resort_pool: "None"
    # last_resort_pool: None
    # last_resort_pool: ''
    # last_resort_pool:
    provider: "{{ f5_gtm_provider }}"
  run_once: yes
  notify: save gtm configuration

```

##### EXPECTED RESULTS

N/A

##### ACTUAL RESULTS

```
N/A
```

**Comment by nmenant** [comment]
tracking this with INFRAANO-293, i'll do some more testing tomorrow and will keep you posted

**Comment by mkf-fjell** [comment]
Thanks nmenant.   As a workaround I added a TMSH command task to set the last resort pool setting back to none until the issue is resolved.

- name: modify gtm A record last_resort_pool setting to none
  f5networks.f5_modules.bigip_command:
    commands: modify gtm wideip a "{{ f5_base_name }}.{{ f5_vs_suffix }}.{{ f5_gtm_suffix }}" { last-resort-pool none }
    provider: "{{ f5_gtm_provider }}"
  run_once: yes
  notify: save gtm configuration

**Comment by nmenant** [comment]
I tested the following: 

BIG-IP v14.1.2.7
F5 ansible collection 1.8.1

```

---

- hosts: default
  gather_facts: false
  vars: 
    provider:
      server: 192.168.143.154
      user: admin
      password: xxxxxx
      validate_certs: no
      server_port: 443

  tasks:

    - name: create gtm A record
      f5networks.f5_modules.bigip_gtm_wide_ip:
        name:  my-ansible-wideip.lab-nico.fr
        state: present
        type: a
        pools: 
          - name: my_gtm_pool
        pool_lb_method: round-robin
        provider: "{{ provider }}"
      run_once: yes
      delegate_to: localhost

``` 

output:

``` 
(Ansible) BZH $ ansible-playbook -i hosts site.yml

PLAY [default] **********************************************************************************************************************************************************

TASK [create gtm A record] **********************************************************************************************************************************************
ok: [192.168.143.154]

PLAY RECAP **************************************************************************************************************************************************************
192.168.143.154            : ok=1    changed=0    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0
``` 

The wideip is created without any issue

Same test with v14.1.4.1 b004 (i deleted the wideip):

``` 
(Ansible) BZH $ ansible-playbook -i hosts site.yml

PLAY [default] **********************************************************************************************************************************************************

TASK [create gtm A record] **********************************************************************************************************************************************
fatal: [192.168.143.154]: FAILED! => {"changed": false, "msg": "b'{\"code\":400,\"message\":\"\\\\\"last-resort-pool\\\\\" requires a value\",\"errorStack\":[],\"apiError\":26214401}'"}

NO MORE HOSTS LEFT ******************************************************************************************************************************************************

PLAY RECAP **************************************************************************************************************************************************************
192.168.143.154            : ok=0    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0
```  

i can reproduce the issue. It seems like BIG-IP GTM API has changed, we'll investigate this
