### ISSUE TITLE
bigip_policy_rule: Replace http_host value = "Missing arguments"

### ISSUE THREAD

**Issue by DerrickTJ** [F5Networks/f5-ansible#1997]
##### COMPONENT NAME
bigip_policy_rule

##### ANSIBLE VERSION

```
ansible 2.10.7
```
##### BIGIP VERSION

```
14.1.4
```
##### SUMMARY
~~Documentation for PR #1950 is missing or hasn't appeared on Ansible's site yet.~~ I'm going off the PR's documentation for issue-01883.yaml on how this is suppose to be used with the new updates.

If I use the type "replace" with the http_host, it errors out saying I'm missing arguments when I'm supplying a value. Could we get the documentation updated for all the new items that were added with this PR? If I'm reading the issue-01883.yaml file correctly and using this as it is suppose to be used, can we fix this error?

##### STEPS TO REPRODUCE

```
    - name: Add a rule to the new policy
      bigip_policy_rule:
          <<: *login
          policy: DerrickTest
          name: Rule6
          conditions:
            - type: http_host
              host_is_any: site1.com, www.site1.com
            - type: http_uri
              path_begins_with_any: /things
          actions:
            - type: replace
              http_host:
                value: "fakehost"
            - type: forward
              pool: Derrick_Pool
      delegate_to: localhost
```

##### ACTUAL RESULTS

```
fatal: [localhost]: FAILED! => {"changed": false, "msg": "missing required arguments: event found in actions -> http_host"}
```

**Comment by DerrickTJ** [comment]
Maybe my page was cached. Documentation is actually up-to-date. Looks like I was using this correctly. https://docs.ansible.com/ansible/latest/collections/f5networks/f5_modules/bigip_policy_rule_module.html

**Comment by focrensh** [comment]
I added `event` parameter to the action as well as the docs show it as required and the task passes now:

```
          actions:
            - type: replace
              http_host:
                event: request
                value: "fakehost"
```

Please let me know if this resolves the error for you as well.
