### ISSUE TITLE
Problems with simplejson

### ISSUE THREAD

**Issue by rogerscuall** [F5Networks/f5-ansible#2]
This is first time I try this modules for F5, I was trying to run a module "bigip_command" and I'm receiving this error: 
>failed: [ltm1] => {"failed": true}
msg: Error: ansible requires the stdlib json or simplejson module, neither was found!

>FATAL: all hosts have already failed -- aborting
This is my playbook:
```---
- hosts: ltm1
  gather_facts: no
  tasks:
  - name: Run a command
    bigip_command:
     server: 192.168.200.200
     command: create node NODE1 address 1.1.1.21"
     password: XXXX
```
Another question: Do I have to specify the server again?
Thanks.

**Comment by caphrim007** [comment]
@rogerscuall you have the right idea, you're just missing a `delegate_to` line. You need to delegate these tasks to be run on the ansible host itself because BIG-IP does not, as you can see from the error, have JSON python modules available.

So for your example, try this.

```
- hosts: ltm1
  gather_facts: no
  tasks:
  - name: Run a command
    bigip_command:
       server: 192.168.200.200
       command: create node NODE1 address 1.1.1.21"
       password: XXXX
    delegate_to: localhost
```

To your second question, the `server:` argument to the module specifies the BIG-IP to connect to, so you can usually just replace it with `{{ inventory_hostname }}` if your `hosts:` line contains the BIG-IP hosts.

So to take your example a step further, give this a try

```
- hosts: ltm1
  gather_facts: no
  tasks:
  - name: Run a command
    bigip_command:
       server: "{{ inventory_hostname }}"
       command: create node NODE1 address 1.1.1.21"
       password: XXXX
    delegate_to: localhost
```

**Comment by rogerscuall** [comment]
I appreciate your quick response.
I have updated the playbook to look like this:
```
---
- hosts: test_ltm
  gather_facts: no
  tasks:
  - name: Run a command
    bigip_command:
     server: ltm1
     command: "create node CASA address 1.1.1.21"
     password: XXXX
     user: admin
    delegate_to: localhost

```

My hosts or inventory file is now like this: 
```
[test_ltm]
ltm1 ansible_ssh_host=192.168.212.240 ansible_ssh_user=admin ansible_ssh_private_key_file=~/.ssh/id_rsa
[local]
localhost ansible_connection=local

```

But I keep receiving an error that I do not comprehend: 
```

PLAY [test_ltm] ***************************************************************

TASK: [Run a command] *********************************************************
failed: [ltm1 -> localhost] => {"failed": true}
msg: [Errno -2] Name or service not known

FATAL: all hosts have already failed -- aborting

PLAY RECAP ********************************************************************
           to retry, use: --limit @/home/naruto/playbook.retry

ltm1                       : ok=0    changed=0    unreachable=0    failed=1
```

As a side note, reading the module looks like user is not required but I got an error when I did not use it.
Thanks.

**Comment by caphrim007** [comment]
Does the user that you're using there have a shell set in BIG-IP? I think the admin account, by default, doesn't have an interactive shell (tmsh or bash)?

**Comment by rogerscuall** [comment]
Yes, I've modified admin to have advance shell access.
<img width="1135" alt="screen shot 2016-01-24 at 8 14 57 pm" src="https://cloud.githubusercontent.com/assets/5758351/12540436/45fb7b4e-c2d7-11e5-8a00-b8dcbd168c0b.png">
So when I connect I go directly into linux and then from there I can do tmsh commands.

**Comment by caphrim007** [comment]
Can you remove lines 211 and 212 from the bigip_command.py file and see if that provides a more verbose exception that we can use to pinpoint the problem?

**Comment by rogerscuall** [comment]
Here is the output:
```
naruto@ansible:~/Ansible/F5$ ansible-playbook playbook.yml

PLAY [test_ltm] ***************************************************************

TASK: [Run a command] *********************************************************
failed: [ltm1 -> localhost] => {"failed": true, "parsed": false}
Traceback (most recent call last):
  File "/home/naruto/.ansible/tmp/ansible-tmp-1453738922.54-209501883840975/bigip_command", line 1829, in <module>
    main()
  File "/home/naruto/.ansible/tmp/ansible-tmp-1453738922.54-209501883840975/bigip_command", line 200, in main
    obj = BigIpSsh(module)
  File "/home/naruto/.ansible/tmp/ansible-tmp-1453738922.54-209501883840975/bigip_command", line 131, in __init__
    super(BigIpSsh, self).__init__(module)
  File "/home/naruto/.ansible/tmp/ansible-tmp-1453738922.54-209501883840975/bigip_command", line 106, in __init__
    sock = socket.create_connection((self._hostname,443), 60)
  File "/usr/lib/python2.7/socket.py", line 553, in create_connection
    for res in getaddrinfo(host, port, 0, SOCK_STREAM):
socket.gaierror: [Errno -2] Name or service not known


FATAL: all hosts have already failed -- aborting

PLAY RECAP ********************************************************************
           to retry, use: --limit @/home/naruto/playbook.retry

ltm1                       : ok=0    changed=0    unreachable=0    failed=1

```

**Comment by rogerscuall** [comment]
I have tried this in version 11.6 and version 12. I have the same problem in both.

**Comment by caphrim007** [comment]
This leads me to think that the bigip hostname you're using is not in DNS or the local hosts file.

If you do a ping of ltm1, does it respond?

If so, then a common pattern I've seen and used to handle cases where "it might be in DNS or it might be in my ansible inventory" is to use the following in your server: argument.

{{ ansible_ssh_host | default(inventory_hostname) }}

This will prefer the ansible IP/host address if it exists and fallback to what would be gleamed from DNS if it does not exist.

For instance, inventory_hostname may not exist if using a dynamic inventory script like the openstack.py script.

Lemme know!

**Comment by rogerscuall** [comment]
I have added entries in /etc/hosts for the LTM2. So I can ping using names. I have modified the playbook to look like this:
```
---
- hosts: test_ltm
  gather_facts: no
  tasks:
  - name: Run a command
    bigip_command:
     server: '{{ inventory_hostname }}'
     command: "create node CASA address 1.1.1.21"
     password: admin
     user: admin
    delegate_to: localhost
```
The inventory is just two lines:
```
[test-ltm]
LTM2-TEST.contoso.com ansible_ssh_user=admin ansible_ssh_private_key_file=~/.ssh/id_rsa
```
This is the output:
```
naruto@ansible:~/Ansible/F5$ ansible-playbook playbook.yml

PLAY [test_ltm] ***************************************************************

TASK: [Run a command] *********************************************************
failed: [LTM2-TEST.contoso.com -> localhost] => {"failed": true}
msg: Server 'LTM2-TEST.contoso.com' not found in known_hosts

FATAL: all hosts have already failed -- aborting

PLAY RECAP ********************************************************************
           to retry, use: --limit @/home/naruto/playbook.retry

LTM2-TEST.contoso.com      : ok=0    changed=0    unreachable=0    failed=1
```
What is very weird because I have "host_key_checking = False".
Thanks.

**Comment by caphrim007** [comment]
Ok, add this one last line to your command and see if it has an effect.

`validate_certs: "no"`

so all together it would look like this.

```
---
- hosts: test_ltm
  gather_facts: no
  tasks:
  - name: Run a command
    bigip_command:
     server: '{{ inventory_hostname }}'
     command: "create node CASA address 1.1.1.21"
     password: admin
     user: admin
     validate_certs: "no"
    delegate_to: localhost
```

Lemme know.
