### ISSUE TITLE
bigip_imish_config chops off last chars in lines to be added

### ISSUE THREAD

**Issue by gitnetofr** [F5Networks/f5-ansible#2045]
##### COMPONENT NAME
bigip_imish_config

##### ANSIBLE VERSION
```
ansible 2.10.8
collection 1.6.0
```
##### BIGIP VERSION
```
15.1.3
```
##### CONFIGURATION
```
# default values
[defaults]
inventory                     = ./inventory/
roles_path                    = ./roles/
callback_whitelist            = timer
host_key_checking             = False
force_color                   = 1
ansible_python_interpreter    =/usr/bin/python3
[ssh_connection]
ssh_args = -o UserKnownHostsFile=/dev/null -o ForwardAgent=yes -o ControlMaster=auto -o ControlPersist=60s -o StrictHostKeyChecking=no 
```

##### OS / ENVIRONMENT
```
Ubuntu 20.04
```

##### SUMMARY
I have the same issue as the one described in issue https://github.com/F5Networks/f5-ansible/issues/1964
Some lines to be added to config using a task with bigip_imish_config, has the last character chopped off, resulting in that, depending on the line to be added, either the wrong value ends up in running-config or the line is reject from being added.

##### STEPS TO REPRODUCE
Our playbook

```
- name: configure router-id
      bigip_imish_config:
         lines:
           - bgp router-id 10.162.243.194
           - bgp graceful-restart restart-time 120
           - ip prefix-list /Common/nothing_v4 seq 1 deny 0.0.0.0/0
           - route-map RHI_BGP_IPv4 permit 10
           - match ip address prefix-list RHI_VIP_IPv4_active
           - set community 65010:14191
           - route-map RHI_BGP_IPv4 permit 20
           - match ip address prefix-list RHI_VIP_IPv4_passive_niv1
           - set community 65010:14191
           - set as-path prepend 65002
           - route-map RHI_BGP_IPv4 permit 30
           - match ip address prefix-list RHI_VIP_IPv4_passive_niv2
           - set community 65010:14191
           - set as-path prepend 65002 65002
         parents: router bgp 65002
         allow_duplicates: "1"
         save_when: always
         provider: "{{ connectionParams }}"
      delegate_to: localhost
```
results in this being added:
```
router bgp 6500
!
bfd slow-timer 2000
bfd gtsm enable
!
ip prefix-list /Common/nothing_v4 seq 1 deny 0.0.0.0/0
!
route-map RHI_BGP_IPv4 permit 10
 match ip address prefix-list RHI_VIP_IPv4_active
 set community 65010:14191
!
route-map RHI_BGP_IPv4 permit 20
 match ip address prefix-list RHI_VIP_IPv4_passive_niv1
 set community 65010:14191
 set as-path prepend 65002
!
route-map RHI_BGP_IPv4 permit 30
 match ip address prefix-list RHI_VIP_IPv4_passive_niv2
 set community 65010:14191
 set as-path prepend 65002 6500
!
```
As you see, the value of as-path for route-map RHI_BGP_IPv4 permit 30 has been chopped off the last character, instead of 65002 as requested, 6500 is in config.

##### EXPECTED RESULTS
Expected that the exact lines specified in the task would be added as-is to the running config of the zebos.
route-map RHI_BGP_IPv4 permit 30
[...]
 set as-path prepend 65002 **65002**

##### ACTUAL RESULTS
Last of the lines ends up wrong in config
route-map RHI_BGP_IPv4 permit 30
[...]
 set as-path prepend 65002 **6500**
