### ISSUE TITLE
bigip_virtual_server only supports "Standard" VS type

### ISSUE THREAD

**Issue by Smuggla** [F5Networks/f5-ansible#205]
##### ISSUE TYPE
 - Feature Idea

##### COMPONENT NAME

bigip_virtual_server

#### EXPECTED OUTCOME

bigip_virtual_server should have the ability to change the Type of the VS.

IE:

Forwarding (Layer 2)
Forwarding (IP)
Performance (HTTP)
Performance (Layer 4)
Stateless
Reject
DHCP
Internal 
Message Routing

FastL4 is a great capability of the F5 and to not have the ability to manage/use that is a real hamper for using configuration management with the F5.

Thanks!

**Comment by caphrim007** [comment]
@Smuggla this should no longer be an issue with the version of bigip_virtual_server currently in the f5-ansible repo.

FastL4 would be specified like so

```
- name: create a vs
  bigip_virtual_server:
    destination: 1.1.1.1
    name: issue-00205a
    port: 80
    profiles:
      - fastL4
    state: present
```
