### ISSUE TITLE
How to Add one Single Irule to a Virtual Server using Ansible ? 

### ISSUE THREAD

**Issue by hgebrael** [F5Networks/f5-ansible#2053]
Trying to add one single iRule to the virtual server using ansible based on https://clouddocs.f5.com/products/orchestration/ansible/devel/modules/bigip_virtual_server_module.html, if you specify only one iRule in irules, it will simply remove it. 

How this can be done and what is the real difference between these two tasks below: 

- name: Add iRules to the Virtual Server
  bigip_virtual_server:
    name: my-virtual-server
    irules:
      - irule1
      - irule2
    provider:
      server: lb.mydomain.net
      user: admin
      password: secret
  delegate_to: localhost

- name: Remove one iRule from the Virtual Server
  bigip_virtual_server:
    name: my-virtual-server
    irules:
      - irule2
    provider:
      server: lb.mydomain.net
      user: admin
      password: secret
  delegate_to: localhost

**Comment by focrensh** [comment]
Please include the data requested in the bug template, Ansible version, collection version, python version, bigip version, etc.

**Comment by hgebrael** [comment]
##### ANSIBLE VERSION
<  AWX 16.0.0  >                    
Ansible Version 2.9.15
Copyright 2019 Red Hat, Inc.

##### BIGIP VERSION
Sys::Version
Main Package
  Product     BIG-IP
  Version     14.1.4
  Build       0.0.11
  Edition     Final
  Date        Thu Feb 11 19:05:03 PST 2021

##### OS / ENVIRONMENT
Red Hat Enterprise Linux release 8.3 (Ootpa)

##### Python Version
Python 3.6.8

**Comment by trinaths** [comment]
Please refer to https://ansible.github.io/workshops/exercises/ansible_f5/1.6-add-irules for detailed info. I tried the above one and it works. My ansible playbook below. 

```
- name: demo lab
  hosts: f5-test
  gather_facts: no
  connection: local
  collections:
    - f5networks.f5_modules

  vars:
    irules: ["irule1"]
    login_user: "XXXXXX"
    login_password: "XXXXXX"
    provider:
      server: "{{ ansible_host }}"
      server_port: 443
      validate_certs: no
      user: "{{ login_user }}"
      password: "{{ login_password }}"

  tasks:
    - name: Add single iRule
      bigip_irule:
        provider: "{{ provider }}"
        module: "ltm"
        name: "{{item}}"
        content: "{{lookup('file','{{item}}')}}"
       with_items: "{{irules}}"
```

Hope this helps @hgebrael
