### ISSUE TITLE
bigip_ucs_fetch raising Authorization failed exception when trying to perform a backup

### ISSUE THREAD

**Issue by balmasea** [F5Networks/f5-ansible#2057]
##### COMPONENT NAME
bigip_ucs_fetch 

##### ANSIBLE VERSION
```
ansible 2.10.6
  python version = 3.6.9 (default, Jul 17 2020, 12:50:27) [GCC 8.4.0]
```
##### BIGIP VERSION
```
Sys::Version
Main Package
  Product     BIG-IP
  Version     12.1.3.7
  Build       0.0.2
  Edition     Point Release 7
  Date        Tue Sep 11 10:03:49 PDT 2018
```
##### CONFIGURATION
N/A

##### OS / ENVIRONMENT
N/A.

##### SUMMARY
When trying to perform a backup using bigip_ucs_fetch, module raises an Authorization failed exception for one device. However, for a twin device with the exact same features and configuration, it works fine. 

##### STEPS TO REPRODUCE
```
- name: "CREATE VARIABLES FOR TASKS"
  ansible.builtin.set_fact:
    ucs_filename: "ansible_backup.ucs"
    ucs_destination_dir: "/BACKUP_DIR/F5/{{ inventory_hostname }}/{{ inventory_hostname }}_{{ '%Y-%m-%d_%H%M' | strftime }}.ucs"

- name: "REMOVE OLD BACKUP FROM F5 NODE"
  vars:
    ansible_user: "{{ backup_user }}"
  f5networks.f5_modules.bigip_ucs:
    ucs: "{{ ucs_filename }}"
    state: "absent"
    provider:
      user: "{{ f5_user }}"
      password: "{{ f5_password }}"
      server: "{{ ansible_host }}"
      validate_certs: false
  delegate_to: "{{ backup_storage_machine }}"

- name: "ENSURE DIRECTORY EXISTS ON BACKUP SERVER"
  vars:
    ansible_user: "{{ backup_storage_machine_user }}"
  ansible.builtin.file:
    path: "{{ ucs_destination_dir | dirname }}"
    state: "directory"
  delegate_to: "{{ backup_storage_machine }}"

- name: "CREATE NEW BACKUP ON F5 NODE AND TRANSFER TO ANSIBLE CONTROL HOST"
  vars:
    ansible_user: "{{ backup_storage_machine_user }}"
  f5networks.f5_modules.bigip_ucs_fetch:
    src: "{{ ucs_filename }}"
    dest: "{{ ucs_destination_dir }}"
    create_on_missing: true
    provider:
      user: "{{ f5_user }}"
      password: "{{ f5_password }}"
      server: "{{ f5_host_001 }}"
      validate_certs: false
  delegate_to: "{{ backup_storage_machine }}"
```

##### EXPECTED RESULTS

When we execute in the twin machine we get:
```
PLAY [all] *****************************************************************************************************************************************************************

TASK [Retrieve device config] **********************************************************************************************************************************************

TASK [CREATE VARIABLES FOR TASKS] ******************************************************************************************************************************************
ok: [host002]

TASK [REMOVE OLD BACKUP FROM F5 NODE] **************************************************************************************************************************************
changed: [host002-> backup_storage_machine ]

TASK [ENSURE DIRECTORY EXISTS ON BACKUP SERVER] *******************************************************************************************************************************
ok: [host002-> backup_storage_machine ]

TASK [CREATE NEW BACKUP ON F5 NODE AND TRANSFER TO ANSIBLE CONTROL HOST] ***************************************************************************************************
changed: [host002-> backup_storage_machine ]

PLAY RECAP *****************************************************************************************************************************************************************
host002: ok=5    changed=2    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0
```

##### ACTUAL RESULTS
```
PLAY [all] *****************************************************************************************************************************************************************

TASK [Retrieve device config] **********************************************************************************************************************************************

TASK [CREATE VARIABLES FOR TASKS] ******************************************************************************************************************************************
ok: [host001]

TASK [REMOVE OLD BACKUP FROM F5 NODE] **************************************************************************************************************************************
ok: [host001-> backup_storage_machine]

TASK [ENSURE DIRECTORY EXISTS ON BACKUP SERVER] *******************************************************************************************************************************
ok: [host001-> backup_storage_machine]
The full traceback is:
WARNING: The below traceback may *not* be related to the actual failure.
  File "/tmp/ansible_f5networks.f5_modules.bigip_ucs_fetch_payload_lF82xX/ansible_f5networks.f5_modules.bigip_ucs_fetch_payload.zip/ansible_collections/f5networks/f5_modules/plugins/modules/bigip_ucs_fetch.py", line 670, in main
  File "/tmp/ansible_f5networks.f5_modules.bigip_ucs_fetch_payload_lF82xX/ansible_f5networks.f5_modules.bigip_ucs_fetch_payload.zip/ansible_collections/f5networks/f5_modules/plugins/modules/bigip_ucs_fetch.py", line 275, in exec_module
  File "/tmp/ansible_f5networks.f5_modules.bigip_ucs_fetch_payload_lF82xX/ansible_f5networks.f5_modules.bigip_ucs_fetch_payload.zip/ansible_collections/f5networks/f5_modules/plugins/modules/bigip_ucs_fetch.py", line 312, in exec_module
  File "/tmp/ansible_f5networks.f5_modules.bigip_ucs_fetch_payload_lF82xX/ansible_f5networks.f5_modules.bigip_ucs_fetch_payload.zip/ansible_collections/f5networks/f5_modules/plugins/modules/bigip_ucs_fetch.py", line 325, in present
  File "/tmp/ansible_f5networks.f5_modules.bigip_ucs_fetch_payload_lF82xX/ansible_f5networks.f5_modules.bigip_ucs_fetch_payload.zip/ansible_collections/f5networks/f5_modules/plugins/modules/bigip_ucs_fetch.py", line 382, in create
  File "/tmp/ansible_f5networks.f5_modules.bigip_ucs_fetch_payload_lF82xX/ansible_f5networks.f5_modules.bigip_ucs_fetch_payload.zip/ansible_collections/f5networks/f5_modules/plugins/modules/bigip_ucs_fetch.py", line 387, in create_on_device
  File "/tmp/ansible_f5networks.f5_modules.bigip_ucs_fetch_payload_lF82xX/ansible_f5networks.f5_modules.bigip_ucs_fetch_payload.zip/ansible_collections/f5networks/f5_modules/plugins/modules/bigip_ucs_fetch.py", line 416, in create_async_task_on_device
fatal: [host001-> backup_storage_machine]: FAILED! => {
    "changed": false,
    "invocation": {
        "module_args": {
            "async_timeout": 150,
            "attributes": null,
            "backup": false,
            "create_on_missing": true,
            "dest": "/BACKUP_DIR/F5/host001/host001_2021-06-23_1239.ucs",
            "encryption_password": null,
            "fail_on_missing": false,
            "force": true,
            "group": null,
            "mode": null,
            "owner": null,
            "provider": {
                "auth_provider": null,
                "no_f5_teem": null,
                "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
                "server": "141.167.98.156",
                "server_port": 443,
                "timeout": null,
                "transport": "rest",
                "user": "f5bckrw",
                "validate_certs": false
            },
            "selevel": null,
            "serole": null,
            "setype": null,
            "seuser": null,
            "src": "ansible_backup.ucs",
            "unsafe_writes": false
        }
    },
    "msg": "{\"code\":401,\"message\":\"Authorization failed: user=https://localhost/mgmt/cm/system/authn/providers/tmos/1f44a60e-11a7-3c51-a49f-82983026b41b/users/c707b96d-6d72-43e1-bbc3-43bc8ab765bf resource=/mgmt/tm/task/sys/ucs verb=POST uri:http://localhost:8100/mgmt/tm/task/sys/ucs referrer:10.22.85.9 sender:10.22.85.9\",\"referer\":\"10.22.85.9\",\"restOperationId\":2898839513,\"errorStack\":[\"java.lang.SecurityException: Authorization failed: user=https://localhost/mgmt/cm/system/authn/providers/tmos/1f44a60e-11a7-3c51-a49f-82983026b41b/users/c707b96d-6d72-43e1-bbc3-43bc8ab765bf resource=/mgmt/tm/task/sys/ucs verb=POST uri:http://localhost:8100/mgmt/tm/task/sys/ucs referrer:10.22.85.9 sender:10.22.85.9\",\"at com.f5.rest.workers.EvaluatePermissions.failPermissionValidation(EvaluatePermissions.java:236)\",\"at com.f5.rest.workers.EvaluatePermissions.completeEvaluatePermission(EvaluatePermissions.java:198)\",\"at com.f5.rest.workers.EvaluatePermissions.access$000(EvaluatePermissions.java:22)\",\"at com.f5.rest.workers.EvaluatePermissions$1.completed(EvaluatePermissions.java:88)\",\"at com.f5.rest.workers.EvaluatePermissions$1.completed(EvaluatePermissions.java:84)\",\"at com.f5.rest.common.RestOperation.complete(RestOperation.java:2261)\",\"at com.f5.rest.workers.AuthTokenWorker.onGet(AuthTokenWorker.java:209)\",\"at com.f5.rest.common.RestCollectionWorker.callDerivedRestMethod(RestCollectionWorker.java:801)\",\"at com.f5.rest.common.RestWorker.callRestMethodHandler(RestWorker.java:1026)\",\"at com.f5.rest.common.RestServer.processQueuedRequests(RestServer.java:1348)\",\"at com.f5.rest.common.RestServer.access$000(RestServer.java:45)\",\"at com.f5.rest.common.RestServer$1.run(RestServer.java:309)\",\"at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:473)\",\"at java.util.concurrent.FutureTask.run(FutureTask.java:262)\",\"at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:178)\",\"at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:292)\",\"at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1152)\",\"at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:622)\",\"at java.lang.Thread.run(Thread.java:748)\\n\"],\"kind\":\":resterrorresponse\"}"
}
```
