### ISSUE TITLE
bigip_policy_rule - error with doc example for set_variable action

### ISSUE THREAD

**Issue by xavgra2** [F5Networks/f5-ansible#2066]
Trying to improve the automation of F5 config, I try to switch to ansible for policy configuration.
Before trying to implement my need based on the doc (using replace action), I first try to make the example of the galaxy documentation working. All the example are working except : 
 ```
       - name: rule3
          actions:
            - type: set_variable
              variable_name: user-agent
              expression: tcl:[HTTP::header User-Agent]
              event: request
          conditions:
            - type: http_uri
              path_begins_with_any:
                - /HomePage/
```
Which return this error 
`"msg": "Unsupported parameters for (bigip_policy_rule) module: event, expression, variable_name found in actions. Supported parameters include: asm_policy, location, pool, type, virtual"}`
