### ISSUE TITLE
bigip_asm_policy_import creates new policy even when force enabled

### ISSUE THREAD

**Issue by VeselaHouba** [F5Networks/f5-ansible#2067]
##### COMPONENT NAME
`bigip_asm_policy_import`

##### ANSIBLE VERSION
```
ansible 2.10.11
  config file = /opt/ansible/ansible.cfg
  configured module search path = ['/opt/f5-ansible/library']
  ansible python module location = /usr/local/lib/python3.9/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 3.9.6 (default, Jun 29 2021, 19:36:19) [GCC 10.3.1 20210424]
```
##### BIGIP VERSION
```
Sys::Version
Main Package
  Product     BIG-IP
  Version     14.1.4
  Build       0.0.11
  Edition     Final
  Date        Thu Feb 11 19:05:03 PST 2021
```
##### CONFIGURATION
Nothing relevant

##### OS / ENVIRONMENT
N/A

##### SUMMARY
When I first import policy, everything seems to be ok. On second import with the same name the original policy is not overwritten, but new one with number suffix e.g. `_1` is created.
Force option is enabled
This used to work, the issue was introduced in https://github.com/F5Networks/f5-ansible/pull/2042/files#diff-cbec5e9062af8b27702fae3d22f201f25436749b853d32d905e7885c6e99cd32 
Confirmed by replacing the 
```
ansible_collections/f5networks/f5_modules/plugins/modules/bigip_asm_policy_import.py
```
with previous version, then things start working as expected again.

##### STEPS TO REPRODUCE
Task
```
- name: Import ASM policy {{ policy.name }}
  bigip_asm_policy_import:
    provider: "{{ f5_provider }}"
    name: "{{ policy.name }}"
    source: "{{ policy.file }}"
    force: "{{ policy.force | default(false) }}"
    partition: "{{ policy.partition | default(omit) }}"
  notify: Save config
  delegate_to: localhost
```

Vars
```
  - name: policy_name_1.0.1
    file: ../files/ASM_policies/policy_name_1.0.1.xml
    force: true
```

##### EXPECTED RESULTS
Policy overwritten
```
Jun 30 21:41:05 f501.my.site info perl[21177]: 01310053:6: ASMConfig change: Import Policy Task Import Policy Task (1625082065.678096) [add]: Target Name was set to /Common/policy_name_1.0.1.
Jun 30 21:41:05 f501.my.site info perl[21177]: 01310053:6: ASMConfig change: Import Policy Task Import Policy Task (1625082065.678096) [update]: Status was set to STARTED. { audit: username = ansible, clien
t IP = client_ip }
Jun 30 21:41:23 f501.my.site info perl[21177]: 01310053:6: ASMConfig change:  Security Policy /Common/policy_name_1.0.1 [add] { audit: policy = /Common/policy_name_1.0.1, username = ansible, client IP = client_ip }
Jun 30 21:41:23 f501.my.site info perl[21177]: 01310053:6: ASMConfig change: Import Policy Task Import Policy Task (1625082065.678096) [update]: Status was set to COMPLETED.
```

##### ACTUAL RESULTS
New policy was imported - note the name change during the import process
```
Jun 30 21:44:20 f501.my.site info perl[21177]: 01310053:6: ASMConfig change: Import Policy Task Import Policy Task (1625082260.682424) [add]: Target Name was set to /Common/policy_name_1.0.1.
Jun 30 21:44:20 f501.my.site info perl[21177]: 01310053:6: ASMConfig change: Import Policy Task Import Policy Task (1625082260.682424) [update]: Status was set to STARTED. { audit: username = ansible, client IP = client_ip }
Jun 30 21:44:34 f501.my.site info perl[21177]: 01310053:6: ASMConfig change:  Security Policy /Common/policy_name_1.0.1_2 [add] { audit: policy = /Common/policy_name_1.0.1_2, username = ansible, client IP = client_ip }
Jun 30 21:44:34 f501.my.site info perl[21177]: 01310053:6: ASMConfig change: Import Policy Task Import Policy Task (1625082260.682424) [update]: Status was set to COMPLETED.
```

**Comment by VeselaHouba** [comment]
Also the same MR introduced following error when using 
```
- name: Activate ASM policy {{ policy.name }}
  bigip_asm_policy_manage:
    provider: "{{ f5_provider }}"
    name: "{{ policy.name }}"
    active: "{{ policy.active | default(false) }}"
    partition: "{{ policy.partition | default(omit) }}"
    apply: true
  notify: Save config
  delegate_to: localhost
```

```
fatal: [f501.my.site]: FAILED! => changed=false
  msg: 'b''{"code":400,"message":"Could not add the Policy \''/Common/policy_name_1.0.1\''.  Failed validating value \''/Common/policy_name_1.0.1\'' for fullPath: The value \''/Common/policy_name_1.0.1\'' already exists, while the field is a unique field.","referer":"client_ip","restOperationId":6408230,"kind":":resterrorresponse"}''
```

Again, this used to work fine before change.

**Comment by wojtek0806** [comment]
first issue with asm import does not exist, I have ran the following snippets of tests from our integration and correct policy has been created:
https://github.com/F5Networks/f5-ansible/blob/devel/test/integration/targets/bigip_asm_policy_import/tasks/v2-policy.yaml#L27

I have even applied to policy to see if that makes the difference and it was working as expected. 

![Screenshot 2021-07-02 at 10 36 57](https://user-images.githubusercontent.com/18006037/124246710-721f7500-db21-11eb-98a2-dc39967ec69e.png)

**Comment by wojtek0806** [comment]
Second issue is covered by this test:

https://github.com/F5Networks/f5-ansible/blob/devel/test/integration/targets/bigip_asm_policy_manage/tasks/issue-
01730.yaml

Also works as intended

The fix you are referring to was intended to remove contains filters as they were causing issues with policy that shared same parts of their name:

e.g. foo-test and foo-test-changed

The root cause might be your config or v14 has some weird rest api behavior, i have ran my tests on v15 and from release notes there was not much of a change between them. If you have support contract open an issue with support to verify the config and behavior of your device.

**Comment by VeselaHouba** [comment]
Looks like the versioning suffix in policy name is the problematic part. Try changing policy name to `foo-policy_1.0.1`

This works
```
    - name: Import ASM policy first run
      bigip_asm_policy_import:
        provider: "{{ f5_provider }}"
        name: example
        source: ../files/ASM_policies/example.xml
        force: true
      delegate_to: localhost

    - name: Import ASM policy second run
      bigip_asm_policy_import:
        provider: "{{ f5_provider }}"
        name: example
        source: ../files/ASM_policies/example.xml
        force: true
      delegate_to: localhost

    - name: Activate ASM policy
      bigip_asm_policy_manage:
        provider: "{{ f5_provider }}"
        name: example
        active: true
        apply: true
      delegate_to: localhost
```
Following causes issues
```
    - name: Import ASM policy 1.0.1 first run
      bigip_asm_policy_import:
        provider: "{{ f5_provider }}"
        name: example_1.0.1
        source: ../files/ASM_policies/example.xml
        force: true
      delegate_to: localhost

    - name: Import ASM policy 1.0.1 second run
      bigip_asm_policy_import:
        provider: "{{ f5_provider }}"
        name: example_1.0.1
        source: ../files/ASM_policies/example.xml
        force: true
      delegate_to: localhost

    - name: Activate ASM policy
      bigip_asm_policy_manage:
        provider: "{{ f5_provider }}"
        name: example_1.0.1
        active: true
        apply: true
      delegate_to: localhost
```
Result on F5 box
![image](https://user-images.githubusercontent.com/6410423/124253889-c417c900-db28-11eb-9b15-8b17edebf445.png)
