### ISSUE TITLE
bigip_data_group type "str" not supported (but "string" is)

### ISSUE THREAD

**Issue by freedge** [F5Networks/f5-ansible#2076]
##### COMPONENT NAME
bigip_data_group

##### ANSIBLE VERSION

```
ansible [core 2.11.2] 
  config file = /home/frigault/bigip/ansible.cfg
  configured module search path = ['/home/frigault/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/frigault/bigip/myenv/lib/python3.6/site-packages/ansible
  ansible collection location = /home/frigault/bigip
  executable location = /home/frigault/bigip/myenv/bin/ansible
  python version = 3.6.9 (default, Jan 26 2021, 15:33:00) [GCC 8.4.0]
  jinja version = 3.0.1
  libyaml = True
```
##### BIGIP VERSION

```

Sys::Version
Main Package
  Product     BIG-IP
  Version     16.1.0
  Build       0.0.19
  Edition     Final
  Date        Tue Jun 22 23:52:22 PDT 2021

```
##### CONFIGURATION

```
ansible-galaxy collection list | grep f5 
f5networks.f5_modules 1.10.1 
```

##### OS / ENVIRONMENT

Ubuntu 18.04.5 LTS

##### SUMMARY

as per doc https://docs.ansible.com/ansible/latest/collections/f5networks/f5_modules/bigip_data_group_module.html#ansible-collections-f5networks-f5-modules-bigip-data-group-module

we should be able to use "type: str" as documented, but it seems in fact, not supported. Documentation should be fixed.

##### STEPS TO REPRODUCE

```
  - name: Create a data group of strings
    bigip_data_group:
      name: foo
      description: bar
      internal: yes
      records:
        - key: A
          value: ""
        - key: B
          value: ""
        - key: C
          value: ""
      type: "str"
      provider: "{{ provider }}"
    delegate_to: localhost
```

##### EXPECTED RESULTS

data group created fine

##### ACTUAL RESULTS

```
    "msg": "b'{\"code\":400,\"message\":\"a value must be provided for \\\\\"type\\\\\" attribute when creating \\\\\"internal\\\\\"\",\"errorStack\":[],\"apiError\":26214401}'
```

Seems to be due to 
https://github.com/F5Networks/f5-ansible/blob/devel/ansible_collections/f5networks/f5_modules/plugins/modules/bigip_data_group.py#L704-L705

Since "str" was never supported, maybe it's safe to remove it from the choice and the documentation.
