### ISSUE TITLE
Bigip_static_route module does not raise an error even if the API endpoint returns a 401 error response

### ISSUE THREAD

**Issue by selinaarokiaswamy-GSLAB** [F5Networks/f5-ansible#2088]
##### COMPONENT NAME

bigip_static_route

##### ANSIBLE VERSION

```
2.9.17
```
##### BIGIP VERSION

```
BIG-IP v15.1.2.1 
```
##### OS / ENVIRONMENT
Ubuntu (Linux)

##### SUMMARY
For an admin user or any other role that is authorized to create a default gateway/static route, the REST API (appcenter/F5Networks/F5ACIServiceCenter/createbigiproutes.json) returns a 200 success response code and the static route is created successfully on the BIG-IP, whereas for a Guest user Authentication the REST API for creating a static route raises a 401 error response and static route is not created. However if the static route is created using Bigip_static_route ansible module with Guest user credentials and same configuration, it does not raise an error and the output log for this execution displays ok=1, failed=0. 
As the REST API fails to create the static route and returns a 401 error response, the ansible module should also raise an error and display ok = 0, failed=1 in the output log

##### STEPS TO REPRODUCE

```
- name: Create/destroy Static Route
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Create static route
      bigip_static_route:
        provider:
            server: "{{ url }}"
            server_port: "{{ port }}"
            user: "{{ guest_username }}"
            password: "{{ guest_password }}"
            validate_certs: no
            timeout: 60
        partition: "{{ partition }}"
        name: "{{ name }}"
        destination: "{{ destination }}"
        netmask: "{{ netmask }}"
        gateway_address: "{{ gateway }}"
        state: "{{ state }}"


```

##### EXPECTED RESULTS
The static route created using Bigip_static_route ansible module with Guest user credentials should also raise a 401 error and display ok = 0, failed=1 in the output log as the REST API fails to create the static route and returns a 401 error response

{"code":401,"message":"Authorization failed: user=’some url here’ verb=POST,"restOperationId":99307,"kind":":resterrorresponse"}

##### ACTUAL RESULTS

```
PLAY [Create/destroy Static Route] **************************************************************

TASK [Create static route on BIG-IP] ***********************************************************************************
changed: [localhost]

PLAY RECAP *************************************************************************************************************
localhost                  : ok=1    changed=1    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0

```
