### ISSUE TITLE
bigip_virtual_server always return changed: true

### ISSUE THREAD

**Issue by dagheyman** [F5Networks/f5-ansible#2100]
##### COMPONENT NAME

bigip_virtual_server

##### ANSIBLE VERSION

```
ansible 2.9.23
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/usr/users/XXXX/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, Aug 13 2020, 02:51:10) [GCC 4.8.5 20150623 (Red Hat 4.8.5-39)]
```
##### BIGIP VERSION

```
Main Package
  Product     BIG-IP
  Version     14.1.2.6
  Build       0.0.2
  Edition     Point Release 6
  Date        Fri Jun  5 11:36:46 PDT 2020
```
##### OS / ENVIRONMENT
Red Hat Enterprise Linux Server release 7.9 (Maipo)

##### SUMMARY
Every time I use the big_ip_virtual_server module, Ansible reports the result as "changed" (yellow output), even though no values are changed. I am using this together with a non-default partition together with profiles, so I'm guessing this could be related to https://github.com/F5Networks/f5-ansible/issues/961

##### STEPS TO REPRODUCE
Use the bigip_virtual_servers module in a playbook that also specifies a partition and profiles.

##### EXPECTED RESULTS

The module should not report changes when there is none.

##### ACTUAL RESULTS
Module always reports changed:true.

**Comment by trinaths** [comment]
@dagheyman - Please share the playbook you are using. we can try the same and help you resolve this issue.

**Comment by dagheyman** [comment]
```
---

- hosts: all
  connection: local
  serial: 1
  tasks:
    - name: Configure virtual servers.
      bigip_virtual_server:
        partition: TEST
        name: test-vs 
        destination: 8.8.8.8
        port: "80"
        provider:
          server: XXX
          user: XXX
          password: XXX
          validate_certs: false
        snat: Automap
        state: present
        profiles:
          - /Common/http
          - /Common/tcp
```

Here is a minimal playbook to reproduce the issue. Note that if the partition is Common, there is no problem, the partition needs to be a non default one.
