### ISSUE TITLE
bigip_virtual_server - unable to add client ssl profile with client context

### ISSUE THREAD

**Issue by martinkyrc** [F5Networks/f5-ansible#2103]
##### COMPONENT NAME

module ```bigip_virtual_server```, client-side (or server-side) ssl profile. version: ```f5networks.f5_modules 1.11.1```

##### ANSIBLE VERSION

```
ansible [core 2.11.3] 
  config file = /home/horol/DEV/mvsr/mvdc-ansible/ansible.cfg
  configured module search path = ['/home/horol/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/horol/VIRTUALENV/ansible2/lib/python3.8/site-packages/ansible
  ansible collection location = /home/horol/.ansible/collections:/usr/share/ansible/collections
  executable location = /home/horol/VIRTUALENV/ansible2/bin/ansible
  python version = 3.8.10 (default, Jun  2 2021, 10:49:15) [GCC 9.4.0]
  jinja version = 3.0.1
  libyaml = False
```
##### BIGIP VERSION

```
Sys::Version
Main Package
  Product     BIG-IP
  Version     15.1.3
  Build       0.0.11
  Edition     Final
  Date        Thu Apr  8 01:36:32 PDT 2021
```
##### OS / ENVIRONMENT

ansible running from Ubuntu 20.04.3

##### SUMMARY

Unable to add client (and server) ssl profile to client/server 'context'. See this part of verbose output:
```
"profiles": [
                {
                    "context": "client-side",
                    "name": "/Common/f5-tcp-wan"
                },
                {
                    "context": "server-side",
                    "name": "/Common/f5-tcp-lan"
                },
                {
                    "context": "server-side",
                    "name": "/Common/serverssl"
                },
                {
                    "context": "client-side",
                    "name": "/out-ssl/cssl_eidas-thawte"
                }
            ],
```
this works:
```
"profiles": [
                "/out-ssl/cssl_eidas-thawte",
                "/Common/serverssl",
                {
                    "context": "client-side",
                    "name": "/Common/f5-tcp-wan"
                },
                {
                    "context": "server-side",
                    "name": "/Common/f5-tcp-lan"
                }
            ],
```

##### STEPS TO REPRODUCE

task from playbook:
```
- name: "> 01: Virtual Server"
  bigip_virtual_server:
    provider: "{{ provider }}"
    partition: "{{ item.partition | default(default_f5.partition) }}"
    insert_metadata: false
    #
    name: "{{ item.name }}"
    description: "{{ item.descr | default(omit) }}"
    type: "{{ item.type | default(omit) }}"
    destination: "{{ item.destination }}"
    port: "{{ item.port | default(80)}}"
    ip_protocol: "{{ item.proto | default('tcp')}}"
    source: "{{ item.source | default(omit) }}"
    pool: "{{ item.pool | default(omit) }}"
    profiles: "{{ item.profiles | default(omit) }}"
    irules: "{{ item.irule | default(omit) }}"
    default_persistence_profile: "{{ item.persistence | default(omit) }}"
    snat: "{{ item.snat | default('none') }}"
    state: "{{ item.state | default('present') }}"
  delegate_to: localhost
  loop: "{{ vs }}"
  when:
    - vs is defined
    - (item.forwarder is undefined) or not (item.forwarder|bool)
  tags:
    - vs
```

configuration that's not working:
```
default_f5:
  partition: out-ssl
  rd: 14
vs:
  - name: vs_test-443
    destination: 1.2.3.4
    port: 443
    pool: sf_eidas-443
    proto: tcp
    profiles:
      - context: client-side
        name: /out-ssl/cssl_eidas-thawte  << this profile exists
      - context: server-side
        name: /Common/serverssl << this profile exists
      - context: client-side
        name: /Common/f5-tcp-wan
      - context: server-side
        name: /Common/f5-tcp-lan
    snat: automap
    state: disabled
```
result: virtual server is not created with this error:
``` "msg": "b'{\"code\":400,\"message\":\"Partition property does not match the object name.\",\"errorStack\":[],\"apiError\":1}'"```

configuration that is working:
```
  - name: vs_test-443
    destination: 1.2.3.4
    port: 443
    pool: sf_eidas-443
    proto: tcp
    profiles:
      - /out-ssl/cssl_eidas-thawte  << profile defined without "context"
      - /Common/serverssl << profile defined without "context"
      - context: client-side
        name: /Common/f5-tcp-wan
      - context: server-side
        name: /Common/f5-tcp-lan
    snat: automap
    state: disabled
```
result: virtual server with correct client/server ssl profile is created.

##### QUESTION
Based on examples (https://docs.ansible.com/ansible/latest/collections/f5networks/f5_modules/bigip_virtual_server_module.html#examples) client/server ssl profiles should be added with "context" (server/client), but it's not working. It's a wrong example or bug for latest f5networks.f5_modules version (1.11.1)?

**Comment by horol** [comment]
I did some test today and look at this (-vvvv output):

```
"item": {
        "destination": "213.81.171.148",
        "name": "vs_eidas-443",
        "partition": "out-ssl",
        "pool": "sf_eidas-443",
        "port": 443,
        "profiles": [
            "/out-ssl/cssl_eidas-thawte",  <<< ssl profile defined without 'context'
            "/Common/serverssl",  <<< ssl profile defined without 'context'
            {
                "context": "client-side",
                "name": "/Common/f5-tcp-wan"
            },
            {
                "context": "server-side",
                "name": "/Common/f5-tcp-lan"
            }
        ],
        "proto": "tcp",
        "snat": "automap",
        "state": "disabled"
    },
    "profiles": [
        {
            "context": "clientside", <<< but here is correct 'context' included (based on client ssl profile definition)
            "fullPath": "/out-ssl/cssl_eidas-thawte",
            "name": "cssl_eidas-thawte",
            "partition": "out-ssl"
        },
        {
            "context": "serverside", <<< but here is correct 'context' included (based on server ssl profile definition)
            "fullPath": "/Common/serverssl",
            "name": "serverssl",
            "partition": "Common"
        },
        {
            "context": "clientside",
            "fullPath": "/Common/f5-tcp-wan",
            "name": "/Common/f5-tcp-wan",
            "partition": "Common"
        },
        {
            "context": "serverside",
            "fullPath": "/Common/f5-tcp-lan",
            "name": "/Common/f5-tcp-lan",
            "partition": "Common"
        }
    ]
}
```

In other words, client/server ssl profile is defined like client/server, but in virtual server profile is not possible include this type of profile with client/server context (execution ends with error). When this type of profiles is included in virtual server definition WITHOUT context, everything works. 

The question is:
- is this behavior connected to tmos version 15.x (in my case 15.1.3) only or doc for 'bigip_virtual_server_module' is not correct?
- my opinion is, that ssl profiles (client/server ssl profiles) must be defined without 'context' and this behavior is not correctly documented. see 3rd example here: https://docs.ansible.com/ansible/latest/collections/f5networks/f5_modules/bigip_virtual_server_module.html#examples

Thanks,
Martin

**Comment by trinaths** [comment]
Created INFRAANO-552 for internal tracking.

**Comment by urohit011** [comment]
Hi @martinkyrc, the error you mentioned occurs when profile configuration is given like the one below without mentioning explicitly the partition name. So, in case when you give profile configuration that includes more than just the `name` field, the value for the `partition` field is set to `Common` when it is not set explicitly to a different value.   

```
profiles:
  - context: client-side
    name: /out-ssl/cssl_eidas-thawte
```
you can make this work by explicitly giving the partition name:

```
profiles:
  - context: client-side
    name: /out-ssl/cssl_eidas-thawte
    partition: out-ssl
```
