### ISSUE TITLE
BIG-IP Authentication using token  

### ISSUE THREAD

**Issue by kalluri27** [F5Networks/f5-ansible#2123]
Ansible Version:

2.11.2

Python Version:

3.6.3

Issue type:

Feature idea

Issue:

I am able to authenticate to bigip using the API and credentials (local user) with the administrator role but when I use the API and credentials (non-local user, LDAP account) then it is failing to authenticate against the bigip and it is throwing 401 Authorization failed error. I am able to retrieve the auth token using the non-local user (LDAP) credentials using ansible Uri module and curl. 

The basic auth is not supported by the f5 for LDAP accounts and API for us. It is said that the basic auth is only good for local users. The Token Authentication is an iControl REST authentication method and It allows access for not only local users but also remotes users (such as RADIUS or LDAP).

So, I am planning to use token authentication but I don't see any method to retrieve the token using bigip modules also how to use that auth token with BIG-IP modules. How do we retrieve the token using bigip modules and use it? Could you add token-based authentication to these modules?

https://devcentral.f5.com/s/articles/iControl-REST-Authentication-Token-Management

**Comment by wojtek0806** [comment]
no ETA at the moment

**Comment by trinaths** [comment]
@kalluri27  please raise an SR to further investigate this issue.

**Comment by trinaths** [comment]
Created INFRAANO-587 for internal tracking.

**Comment by urohit011** [comment]
Hi @kalluri27 , try giving `remote` for `auth_provider` in your playbook. 

```
- name: auth with token
  bigip_device_info:
    gather_subset:
      - devices
    provider:
      password: xxxxxx
      user: xxxxxx
      server: xxxxxx
      validate_certs: no
      auth_provider: remote
  delegate_to: localhost
```

Also, for configuring LDAP user credentials on BIGIP use a bind account instead of user template as it's mentioned [here](https://support.f5.com/csp/article/K50404727).
