### ISSUE TITLE
bigip_device_info

### ISSUE THREAD

**Issue by stanislaspiron** [F5Networks/f5-ansible#2167]
### Is your feature request related to a problem? Please describe.
Most of customers usage of bigip_device_license module is to renew same license to update license check date:

- Update license check date before upgrades
- Update license check date to be allowed to download last ASM signatures

It should be interesting to gather such information with bigip_device_info module instead of uri module which requires iControl payload parsing with errors.

### Describe the solution you'd like
Add license keys and add-on keys in bigip_device_info module result.

### Additional context
The current workaround is to use uri module

```
  tasks:
  - name: Get device License
    uri:
      url: https://{{ ansible_host }}/mgmt/tm/sys/license/
      user: "{{ user }}"
      password: "{{ password }}"
      return_content: yes
      validate_certs: false
    register: license_status

  - name: reactivate license
    bigip_device_license:
      license_key: "{{ registration_key }}"
      addon_keys: "{{ license_addon.active + license_addon.time_limited }}"
      provider: "{{ bigip_provider }}"
      force: yes
      state: latest
      accept_eula: yes
  vars:
    license_entries: "{{ (license_status.json.entries.values() | list | first).nestedStats.entries }}"
    license_date: "{{ license_entries.serviceCheckDate.description }}"
    registration_key: "{{ license_entries.registrationKey.description }}"
    license_addon:
      active: "{{ (license_entries['https://localhost/mgmt/tm/sys/license/0/active-modules'].nestedStats.entries.values()|list | map(attribute='nestedStats.entries.key.description')) if 'https://localhost/mgmt/tm/sys/license/0/active-modules' in license_entries else [] }}"
      time_limited: "{{ (license_entries['https://localhost/mgmt/tm/sys/license/0/time-limited-modules'].nestedStats.entries.values()|list | map(attribute='nestedStats.entries.key.description')) if 'https://localhost/mgmt/tm/sys/license/0/time-limited-modules' in license_entries else [] }}"
```
