### ISSUE TITLE
Help with bigip_firewall_address_list with ansible tower

### ISSUE THREAD

**Issue by Samuel-Singh** [F5Networks/f5-ansible#2190]
So I'm trying to add an IP to address list in f5 using a playbook being run on ansible tower. I got a working playbook that does this but it overwrites the existing list with my input. I was recommended to use "bigip_device_info" to get the list and add it with my new input. I'm just not sure which choice should I use user "gather_subset". Any recommendations?

```
- name: BigIP_Blacklist
  hosts: all
  connection: local
  gather_facts: false
  collections:
    - f5networks.f5_modules
 tasks:
    - name: Collecting previous list
      bigip_device_info:
        gather_subset:
          - **WHICH ONE TO USE**
        provider:
          server: xx.xx.xx.x
          user: '{{ lookup("env", "ANSIBLE_NET_USERNAME") }}'
          password: '{{ lookup("env", "ANSIBLE_NET_PASSWORD") }}'
          server_port: 443
          validate_certs: false
      register: device_facts
    - name: "Adding the IP to blacklist in Test"
      bigip_firewall_address_list:
        name: test_afm_address_list_blacklist24_drop
        addresses: 
           - "{{Blacklist_IP}}"
           - device_facts
        provider:
          password: '{{ lookup("env", "ANSIBLE_NET_PASSWORD") }}'
          server: xx.xx.xx.x
          server_port: 443
          user: '{{ lookup("env", "ANSIBLE_NET_USERNAME") }}'
          validate_certs: false
      delegate_to: localhost
```
