### ISSUE TITLE
Accessing Row Data with the bigip_iapp_service module for the appsvcs_integration iapp

### ISSUE THREAD

**Issue by mcgonagle** [F5Networks/f5-ansible#220]
##### ISSUE TYPE
 - Feature Idea

##### COMPONENT NAME
bigip_iapp_service

##### ANSIBLE VERSION

```
ansible 2.3.0.0
  config file = /tom/Dropbox/ansible_f5/ansible.cfg
  configured module search path = [u'./library']
  python version = 2.7.12 (default, Oct 11 2016, 05:24:00) [GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.38)]
```

##### PYTHON VERSION

```
(ansible2) tom@tompro:~/Dropbox/ansible_f5> python -V
Python 2.7.12
```

##### BIGIP VERSION

```
Sys::Version
Main Package
  Product     BIG-IP
  Version     12.1.1
  Build       1.0.196
  Edition     Hotfix HF1
  Date        Wed Sep  7 17:48:09 PDT 2016

Hotfix List
ID601938-2    ID595394-2  ID513851-2  ID606110-3  ID527403-1  ID594910-1
ID605682-2    ID599068-2  ID603997    ID585120-1  ID321971-1  ID604211-3
ID598294-1    ID600859-3  ID595064-1  ID589318-1  ID590074-1  ID575170-2
ID590578-4    ID590608-1  ID603605-1  ID608373-2  ID600778-1  ID596814-5
ID614599      ID601927-1  ID585366    ID606509-3  ID599054-2  ID599033-3
ID589149-2    ID593355    ID599769
```

##### SUMMARY

The App appsvcs_integration_v2.0.003 iApp has a number of fields that are rows of input. Namely the 
Pool Monitor(s) Configuration. I don't have a way to access these fields and configure them with the parameters+variables yaml definition. For example:
parameters:
        variables:
          - name: "iapp__mode"
            value: "auto"

##### STEPS TO REPRODUCE

```
---
- name: Configure a service using parameters in YAML
  bigip_iapp_service:
    name: "appsvcs"
    user: "{{ username }}"
    password: "{{ password }}"
    server: "{{ inventory_hostname }}"
    template: "appsvcs_integration_v2.0.003"
    validate_certs: "false"
    state: "present"
    parameters:
        variables:
          - name: "iapp__mode"
            value: "auto"
          - name: "iapp__logLevel"
            value: "7"
          - name: "iapp__routeDomain"
            value: "auto"
          - name: "pool__addr"
            value: "10.0.2.184"
          - name: "pool__mask"
            value: "255.255.255.255"
          - name: "pool__port"
            value: "80"
          - name: "pool__DefaultPoolIndex"
            value: "0"
          - name: "pool__Pools"
            value: "0"
          - name: "pool__MemberDefaultPort"
            value: "0"
          - name: "pool__Members"
            value: "0"
          - name: "vs__ProfileClientProtocol"
            value: "/Common/tcp"
          - name: "vs__ProfileHTTP"
            value: "/Common/http"
          - name: "vs__SNATConfig"
            value: "automap"
  delegate_to: localhost
```

##### EXPECTED RESULTS

I'd like to be able to configure the appsvcs integration iapp via ansible. 

##### ACTUAL RESULTS

Not able to completely setup the iapp.

```

```
