### ISSUE TITLE
bigip_device_sshd enhancement to manage cipher, mac and kex

### ISSUE THREAD

**Issue by mitch-geht-ab** [F5Networks/f5-ansible#2203]
### Is your feature request related to a problem? Please describe.

Company compliance is getting stricter. For example CBC ciphers has to be disabled as well as kex etc.

### Describe the solution you'd like

Would expect that I can manage sshd cipher, kex and mac with the bigip_device_sshd module.
As described for tmsh in 

- K25523031: Disable CBC ciphers mode in SSHD
- K80425458: Modifying the list of ciphers and MAC and key exchange algorithms used by the SSH service on the BIG-IP or BIG-IQ systems

in ansible (comparable with the bigip_device_httpd)
```
- name: Set the cipher for the SSHD service by list
  bigip_device_sshd:
    ciphers:
      - aes128-ctr
      - aes192-ctr
      - ...
    provider:
...

- name: Set the mac for the SSHD service by list
  bigip_device_sshd:
    mac:
      - hmac-sha1
      - hmac-ripemd160
      - ...
    provider:
...

- name: Set the kex for the SSHD service by list
  bigip_device_sshd:
    kex:
      - ecdh-sha2-nistp256
      - ecdh-sha2-nistp384
      - ...
    provider:
...
```

### Describe alternatives you've considered
The alternative I've to use is bigip_command where you wrote

> It is intended as a stop-gap measure to satisfy automation requirements until such a time as a real module has been developed to configure in the way you need.
> If you are using this module, we recommend also filing an issue to have a real module created for your needs.
