### ISSUE TITLE
Ability to drop persistent connections from a virtual server

### ISSUE THREAD

**Issue by perzizzle** [F5Networks/f5-ansible#2213]
### Is your feature request related to a problem? Please describe.
We use the bigip_virtual_server module to disable a virtual server and then after a period of time we use the bigip_command module to drop persistent connections. We do this to give our clients a few minutes to finish their requests before we forcibly drop them.  Recently noticed ansible output includes a warning to request this be supported in a module since write commands aren't idempotent.

``` 
    - name: Drop connections to LTM virtual server
      local_action:
        module: bigip_command
        commands: "tmsh delete sys connection cs-server-addr {{ f5_ltm_virtual_server_ip }}"
        provider:
          server: "{{ f5_ltm_server }}"
          user: "{{ f5_ltm_username }}"
          password: "{{ f5_ltm_password }}"
      until: not ltm_virtual_server_drop['failed']
      retries: 5
      delay: 5

"warnings": [
        "Using \"write\" commands is not idempotent. You should use a module that is specifically made for that. If such a module does not exist, then please file a bug. The command in question is \"delete sys connection cs-server-addr 172...\""
    ]
```

### Describe the solution you'd like
It would be nice to not have a to use tmsh to drop these connections but have it baked into a module.
