### ISSUE TITLE
iControl.py error when connecting to F5 device running version 16.1.2.2 Error: "Expecting value: line 1 column 1 (char 0)"

### ISSUE THREAD

**Issue by jGallicchio** [F5Networks/f5-ansible#2215]
##### COMPONENT NAME
Collections currently applied
- name: f5networks.f5_modules
   version: 1.11.1
   
Modules in use
  f5networks.f5_modules.bigip_profile_client_ssl
  f5networks.f5_modules.bigip_config

### Environment
Ansible Tower version Tower 3.8.2 

##### ANSIBLE VERSION
```
ansible --version
ansible 2.9.27
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/export/home/jg98818e/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.6/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 3.6.8 (default, Dec  5 2019, 15:45:45) [GCC 8.3.1 20191121 (Red Hat 8.3.1-5)]
```
##### BIGIP VERSION
```
Sys::Version
Main Package
Product BIG-IP
Version 16.1.2.2
Build 0.0.28
Edition Point Release 2
Date Thu Apr 7 13:32:41 PDT 2022
```
##### CONFIGURATION
Moved devices from 16.1.2.1 to 16.1.2.2

##### OS / ENVIRONMENT
Red Hat Enterprise Linux release 8.4 (Ootpa)

##### SUMMARY
When running jobs containing f5networks.f5_modules.bigip_config: or f5networks.f5_modules.bigip_profile_client_ssl: job will error out with "msg": "Expecting value: line 1 column 1 (char 0)". Happens at random, for example when running on 2 HA pairs of LTMs, one 5-6 pair will error out, but the 7-8 pair will run successfully with the same code.

##### STEPS TO REPRODUCE
```
- name: upload certificate file
  uri:
    url: https://{{ f5_ltm_provider.server }}/mgmt/shared/file-transfer/uploads/{{ cert_name }}.pfx
    method: POST
    headers:
      Content-Type: application/octet-stream
      Content-Range: 0-{{ stat_out.stat.size -1 }}/{{ stat_out.stat.size }}
    src: cert.pfx
    force_basic_auth: yes
    url_username: "{{ lookup('env', 'F5_USER') }}"
    url_password: "{{ lookup('env', 'F5_PASSWORD') }}"
    validate_certs: "{{ f5_ltm_validate_certs }}"
  register: upload_result
  ignore_errors: yes

- name: register certificate file
  uri:
    url: https://{{ f5_ltm_provider.server }}/mgmt/tm/sys/crypto/pkcs12/~{{ f5_partition }}~{{ cert_name }}
    method: POST
    body_format: json
    body:
      command: install
      fromLocalFile: /var/config/rest/downloads/{{ cert_name }}.pfx
      passphrase: "{{ cert_password }}"
    force_basic_auth: yes
    url_username: "{{ lookup('env', 'F5_USER') }}"
    url_password: "{{ lookup('env', 'F5_PASSWORD') }}"
    validate_certs: "{{ f5_ltm_validate_certs }}"

- name: modify client ssl profile
  f5networks.f5_modules.bigip_profile_client_ssl:
    name: "{{ f5_vs_fqdn }}"
    cert_key_chain:
      - cert: "{{ cert_name }}"
        key: "{{ cert_name }}"
        true_names: yes
    provider: "{{ f5_ltm_provider }}"
  notify:
    - save ltm configuration
    - sync ha cluster
```

##### EXPECTED RESULTS
Expected modify to run successfully and then ltm sync and save successfully

##### ACTUAL RESULTS
Failure on save LTM handler (no verbosity):
```
{
    "msg": "Expecting value: line 1 column 1 (char 0)",
    "invocation": {
        "module_args": {
            "save": true,
            "provider": {
                "server": "hfdhidcf5ltmpd001-002.thehartford.com",
                "validate_certs": true,
                "server_port": null,
                "user": "netansible",
                "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
                "transport": "rest",
                "timeout": null,
                "no_f5_teem": null,
                "auth_provider": null
            },
            "reset": false,
            "verify": false,
            "merge_content": null
        }
    },
    "_ansible_no_log": false,
    "changed": false
}

Failure on modify_ssl (Verbosity 3 (Debug)):
{
    "msg": "Expecting value: line 1 column 1 (char 0)",
    "exception": "  File \"/tmp/ansible_f5networks.f5_modules.bigip_profile_client_ssl_payload_orgxe4ll/ansible_f5networks.f5_modules.bigip_profile_client_ssl_payload.zip/ansible_collections/f5networks/f5_modules/plugins/modules/bigip_profile_client_ssl.py\", line 1237, in main\n  File \"/tmp/ansible_f5networks.f5_modules.bigip_profile_client_ssl_payload_orgxe4ll/ansible_f5networks.f5_modules.bigip_profile_client_ssl_payload.zip/ansible_collections/f5networks/f5_modules/plugins/modules/bigip_profile_client_ssl.py\", line 980, in exec_module\n  File \"/tmp/ansible_f5networks.f5_modules.bigip_profile_client_ssl_payload_orgxe4ll/ansible_f5networks.f5_modules.bigip_profile_client_ssl_payload.zip/ansible_collections/f5networks/f5_modules/plugins/module_utils/icontrol.py\", line 556, in tmos_version\n    raise F5ModuleError(str(ex))\n",
    "invocation": {
        "module_args": {
            "name": "devpersonal04.thehartford.com",
            "cert_key_chain": [
                {
                    "cert": "devpersonal04.thehartford.com_0001B856_2024-05-10",
                    "key": "devpersonal04.thehartford.com_0001B856_2024-05-10",
                    "true_names": true,
                    "chain": null,
                    "passphrase": null
                }
            ],
            "provider": {
                "server": "hfdlb2f57-8.thehartford.com",
                "validate_certs": true,
                "server_port": null,
                "user": "netansible",
                "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
                "transport": "rest",
                "timeout": null,
                "no_f5_teem": null,
                "auth_provider": null
            },
            "state": "present",
            "partition": "Common",
            "parent": null,
            "ciphers": null,
            "cipher_group": null,
            "allow_non_ssl": null,
            "secure_renegotiation": null,
            "options": null,
            "sni_default": null,
            "sni_require": null,
            "server_name": null,
            "client_certificate": null,
            "client_auth_frequency": null,
            "cert_auth_depth": null,
            "retain_certificate": null,
            "trusted_cert_authority": null,
            "advertised_cert_authority": null,
            "client_auth_crl": null,
            "allow_expired_crl": null,
            "strict_resume": null,
            "renegotiation": null,
            "cache_size": null,
            "cache_timeout": null
        }
    },
    "_ansible_no_log": false,
    "changed": false
}
```

**Comment by mojr13** [comment]
Hello, this happens to us as well with random modules, not just certificate. For example on bigip_node. Sometimes at random it works and sometimes it doesn't.
Started happening after upgrade to 16.1.2.2

**Comment by pavleec** [comment]
Hi, it appears that it also affects version 15.1.5.1, as before the upgrade I haven't observerd this. I think it might be related with the recent iControl REST vulnerability patching CVE-2022-1388.

**Comment by david-sieg** [comment]
Same here, as Pavleec says. Since upgrade to 15.1.5.1 F5 modules are unusable for our F5s.

**Comment by trinaths** [comment]
Created [INFRAANO-762] for internal tracking.

**Comment by jbericat** [comment]
Same problem on `BIG-IP 15.1.5.1 Build 0.0.14 Point Release 1`. It appears to be a random issue, since it only fails every now and then with different modules (on this case, the "bigip_command" module)

Ansible version: 2.12.1
Python version: 3.8.8
F5 imperative modules version: 1.16.0

 I haven't noticed the issue until the recent upgrade of several F5 instances. On `BIG-IP 15.01.04 Build 047 Final` the error never appeared. 

```json
{
  "msg": "Expecting value: line 1 column 1 (char 0)",
  "exception": "  File \"/tmp/ansible_f5networks.f5_modules.bigip_command_payload_r50f1a62/ansible_f5networks.f5_modules.bigip_command_payload.zip/ansible_collections/f5networks/f5_modules/plugins/modules/bigip_command.py\", line 738, in main\n  File \"/tmp/ansible_f5networks.f5_modules.bigip_command_payload_r50f1a62/ansible_f5networks.f5_modules.bigip_command_payload.zip/ansible_collections/f5networks/f5_modules/plugins/modules/bigip_command.py\", line 668, in exec_module\n  File \"/tmp/ansible_f5networks.f5_modules.bigip_command_payload_r50f1a62/ansible_f5networks.f5_modules.bigip_command_payload.zip/ansible_collections/f5networks/f5_modules/plugins/modules/bigip_command.py\", line 619, in exec_module\n  File \"/tmp/ansible_f5networks.f5_modules.bigip_command_payload_r50f1a62/ansible_f5networks.f5_modules.bigip_command_payload.zip/ansible_collections/f5networks/f5_modules/plugins/module_utils/icontrol.py\", line 556, in tmos_version\n    raise F5ModuleError(str(ex))\n",
  "invocation": {
    "module_args": {
      "commands": [
        "show ltm virtual | grep -i HIDDEN_DATA"
      ],
      "provider": {
        "user": "HIDDEN_DATA",
        "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
        "server": "HIDDEN_DATA",
        "server_port": 443,
        "validate_certs": false,
        "no_f5_teem": true,
        "transport": "rest",
        "timeout": null,
        "auth_provider": null,
        "ssh_keyfile": null
      },
      "match": "all",
      "retries": 10,
      "interval": 1,
      "warn": true,
      "wait_for": null,
      "chdir": null
    }
  },
  "_ansible_no_log": false,
  "changed": false,
  "_ansible_delegated_vars": {
    "ansible_host": "localhost",
    "ansible_port": null,
    "ansible_user": "root",
    "ansible_connection": "local"
  }
}
```

**Comment by mojr13** [comment]
I created a support ticket on F5 where they said, they are working on Engeneering HF but still nothing after 2 weeks...

Also, it seems to be this bug: https://support.f5.com/csp/article/K91334123

**Comment by mstrent** [comment]
> I created a support ticket on F5 where they said, they are working on Engeneering HF but still nothing after 2 weeks...
> 
> Also, it seems to be this bug: https://support.f5.com/csp/article/K91334123

We also have a ticket open with F5 support for a while now. This issue started with our upgrade to 14.1.4.6. And I agree, it appears to be related to that KB and this bug specifically:
https://cdn.f5.com/product/bugtracker/ID1108181.html

**Comment by mstrent** [comment]
It's un-tested, but given the bug description where a newly-established auth token need a second to "settle" before being used, and the fact that I ONLY get errors first thing in the morning after not hitting the API for hours, I'm trying a workaround of just adding retries:

```
    - name: Collect bigip facts
      bigip_device_info:
        gather_subset: ltm-pools
        provider:
          xxxxx
      register: bigip_facts
      **until: bigip_facts is success
      retries: 2
      delay: 1**
```
