### ISSUE TITLE
bigip_pool error when pool exists 

### ISSUE THREAD

**Issue by himalayanBuddy** [F5Networks/f5-ansible#2223]
##### COMPONENT NAME
bigip_pool

##### ANSIBLE VERSION

```
ansible [core 2.11.6]
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/mottoman/f5_automation_projects/f5automation/library']
  ansible python module location = /usr/lib/python3.9/site-packages/ansible
  ansible collection location = /export/home/mottoman/.ansible/collections:/usr/share/ansible/collections
  executable location = /apps/python3/bin/ansible
  python version = 3.9.5 (default, Oct 27 2021, 16:48:27) [GCC 4.8.5 20150623 (Red Hat 4.8.5-44)]
  jinja version = 3.0.1
  libyaml = True

```
##### BIGIP VERSION

```
Sys::Version
Main Package
  Product     BIG-IP
  Version     15.1.5.1
  Build       0.0.14
  Edition     Point Release 1
  Date        Sun Mar 27 23:23:42 PDT 2022
```
##### SUMMARY
The issue is that I run my playbook and it runs fine and added all the components of my F5 application service. If I run the exact same playbook again I get an error on the task to add pools (bigip_pool) stating "one or more properties must be specified"

##### STEPS TO REPRODUCE

```
- name:  create pool
  bigip_pool:
    name: "{{ pool_name }}"
    slow_ramp_time: "{{ pool_slow_ramp_time }}"
    lb_method: "{{ pool_load_balancing_method }}"
    state: "{{ state }}"
  delegate_to: localhost
  when: active_device_name is defined and inventory_hostname == active_device_name
```

##### EXPECTED RESULTS
I would expect the playbook to pass over the pool add and keep on running

##### ACTUAL RESULTS
The playbook fails with message below

```
FAILED! => {"changed": false, "msg": "one or more properties must be specified"}

LTM log:
module=(tmos)# status=[Syntax Error: one or more properties must be specified] cmd_data=modify ltm pool /Common/ansibletest19-gl-80-http-pool
```
I tried the solution mentioned https://github.com/F5Networks/f5-ansible/issues/1557. But it doesn't resolve my issue. Though I believe it shouldn't matter

**Comment by trinaths** [comment]
Created [NFRAANO-806] for internal tracking.

**Comment by wojtek0806** [comment]
I have tested this on 2 versions:
```Sys::Version
Main Package
  Product     BIG-IP
  Version     15.1.1
  Build       0.0.6
  Edition     Point Release 0
  Date        Thu Oct  8 02:52:59 PDT 2020
```

```
Sys::Version
Main Package
  Product     BIG-IP
  Version     16.1.0
  Build       0.0.19
  Edition     Final
  Date        Tue Jun 22 23:52:22 PDT 2021
```

Playbook used:
```
---
- name: Test Bigip Pool
  hosts: all
  gather_facts: no
  connection: local

  collections:
   - f5networks.f5_modules

  environment:
      F5_SERVER: "{{ ansible_host }}"
      F5_USER: "admin"
      F5_PASSWORD: "admin"
      F5_VALIDATE_CERTS: "false"
      F5_SERVER_PORT: 8443


  tasks:
    - name: Create a pool
      bigip_pool:
        description: "Loss Mitigation"
        name: "test_pool-8640_pool"
        lb_method: "round-robin"
        state: "present"
```
I ran the above playbook twice on each host and the idempotency works fine, I cannot reproduce this. If this issue is consistent on your end can you rerun the task and share the full  -vvvvv output, lets see if we can figure out what is going on from the logs. If this fails then there are furhter steps but they would require you to open support ticket as it requires modifying the module code to get debugging output.
