### ISSUE TITLE
Incorrect permissions on uploaded UCS file via bigip_ucs state present

### ISSUE THREAD

**Issue by ronrem** [F5Networks/f5-ansible#2227]
##### COMPONENT NAME
```
f5networks.f5_modules.bigip_ucs
```
##### ANSIBLE VERSION
```
ansible [core 2.12.5]
  config file = ../../ansible.cfg
  configured module search path = [‘~/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /opt/homebrew/lib/python3.9/site-packages/ansible
  ansible collection location = ~/.ansible/collections:/usr/share/ansible/collections
  executable location = /opt/homebrew/bin/ansible
  python version = 3.9.13 (main, May 24 2022, 21:13:51) [Clang 13.1.6 (clang-1316.0.21.2)]
  jinja version = 3.1.2
  libyaml = True
```
##### BIGIP VERSION
```
Sys::Version
Main Package
  Product     BIG-IP
  Version     14.1.4.6
  Build       0.0.8
  Edition     Point Release 6
  Date        Mon Mar 28 02:38:32 PDT 2022
```
##### OS / ENVIRONMENT
```
macos:12.4
```
##### SUMMARY
```
Incorrect permissions on uploaded UCS file via bigip_ucs state present.
In GUI [system/archive] the (uploaded) UCS file gives an “General database error retrieving information.” Error.
```
##### STEPS TO REPRODUCE
```
---
- hosts: f5
  connection: local
  collections:
    - f5networks.f5_modules
  gather_facts: false

  vars:
    ansible_host: "192.168.123.123"
    ansible_user: "user1"
    ansible_httpapi_password: "mysecret"
    ansible_httpapi_use_ssl: yes
    ansible_ssh_password: "mysecret"
    local_folder_location: "config/f5/"
    file_name: UseCase-00-backup.ucs

  tasks:
    - name: Set provider fact
      set_fact:
        provider:
          server: "{{ ansible_host }}"
          user: "{{ ansible_user }}"
          password: "{{ ansible_httpapi_password }}"
          server_port: 443
          transport: "rest"
          timeout: 1800
          validate_certs: false
          # ansible_network_os: BIG-IP

    - name: set fact_ansible connection
      set_fact:
        ansible_connection: local

    - name: Upload UCS From Backup
      bigip_ucs:
        ucs: "{{local_folder_location}}UseCase-00-backup-myfile"
        force: yes
        state: present
        no_license: yes
        provider: "{{provider}}"
      # ignore_errors: yes
```

##### EXPECTED RESULTS
```
Permissions are CHOWN root:apache and CHMOD 0640, expected CHOWN root:root and CHMOD 0644.

ls -als /var/local/ucs/
total 8480
   4 drwxr-xr-x. 3 root root      4096 Jun 14 00:37 .
   4 drwxr-xr-x. 9 root root      4096 Jun  9 09:28 ..
   4 -r--r--r--. 1 root root       176 Mar 28 01:26 cs_backup_rotate.conf
2836 -rw-r--r--. 1 root root   2901322 Jun 14 00:36 cs_backup.ucs
2812 -rw-r--r--. 1 root root   2878708 Jun 10 09:07 cs_backup.ucs.1
   4 drwxr-xr-x. 2 root root      4096 Jun  9 09:39 tmp
2816 -rw-r--r--. 1 root root   2880358 Jun 14 00:37 UseCase-00-backup-myfile
```

##### ACTUAL RESULTS
```


ansible-playbook f5-restore.yaml --vault-id @prompt -vvv
ansible-playbook [core 2.12.5]
  config file = /Users/undisclosed/Ansible/ansible.cfg
  configured module search path = ['/Users/undisclosed/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /opt/homebrew/lib/python3.9/site-packages/ansible
  ansible collection location = /Users/undisclosed/.ansible/collections:/usr/share/ansible/collections
  executable location = /opt/homebrew/bin/ansible-playbook
  python version = 3.9.13 (main, May 24 2022, 21:13:51) [Clang 13.1.6 (clang-1316.0.21.2)]
  jinja version = 3.1.2
  libyaml = True
Using /Users/undisclosed/Ansible/ansible.cfg as config file
Vault password (default): 
host_list declined parsing /Users/undisclosed/Ansible/hosts.yml as it did not pass its verify_file() method
script declined parsing /Users/undisclosed/Ansible/hosts.yml as it did not pass its verify_file() method
Parsed /Users/undisclosed/Ansible/hosts.yml inventory source with yaml plugin
Skipping callback 'default', as we already have a stdout callback.
Skipping callback 'minimal', as we already have a stdout callback.
Skipping callback 'oneline', as we already have a stdout callback.

PLAYBOOK: f5-restore.yaml ******************************************************************************************************
1 plays in f5-restore.yaml

PLAY [f5] **********************************************************************************************************************
META: ran handlers

TASK [Set provider fact] *******************************************************************************************************
task path: /Users/undisclosed/Ansible/f5-restore.yaml:18
ok: [f5] => {
    "ansible_facts": {
        "provider": {
            "password": “mysecret”,
            "server": "192.168.226.10",
            "server_port": 443,
            "timeout": 1800,
            "transport": "rest",
            "user": “user1”,
            "validate_certs": false
        }
    },
    "changed": false
}

TASK [set fact_ansible connection] *********************************************************************************************
task path: /Users/undisclosed/Ansible/f5-restore.yaml:42
ok: [f5] => {
    "ansible_facts": {
        "ansible_connection": "local"
    },
    "changed": false
}

TASK [Upload UCS From Backup] **************************************************************************************************
task path: /Users/undisclosed/Ansible/f5-restore.yaml:46
<192.168.226.10> ESTABLISH LOCAL CONNECTION FOR USER: user1
<192.168.226.10> EXEC /bin/sh -c 'echo ~user1 && sleep 0'
<192.168.226.10> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /Users/undisclosed/.ansible/tmp `"&& mkdir "` echo /Users/undisclosed/.ansible/tmp/ansible-tmp-1655193160.437197-43269-14744921007585 `" && echo ansible-tmp-1655193160.437197-43269-14744921007585="` echo /Users/undisclosed/.ansible/tmp/ansible-tmp-1655193160.437197-43269-14744921007585 `" ) && sleep 0'
Using module file /Users/undisclosed/.ansible/collections/ansible_collections/f5networks/f5_modules/plugins/modules/bigip_ucs.py
<192.168.226.10> PUT /Users/undisclosed/.ansible/tmp/ansible-local-43262qs2escsr/tmpk_3r00ii TO /Users/undisclosed/.ansible/tmp/ansible-tmp-1655193160.437197-43269-14744921007585/AnsiballZ_bigip_ucs.py
<192.168.226.10> EXEC /bin/sh -c 'chmod u+x /Users/undisclosed/.ansible/tmp/ansible-tmp-1655193160.437197-43269-14744921007585/ /Users/undisclosed/.ansible/tmp/ansible-tmp-1655193160.437197-43269-14744921007585/AnsiballZ_bigip_ucs.py && sleep 0'
<192.168.226.10> EXEC /bin/sh -c '/opt/homebrew/opt/python@3.9/bin/python3.9 /Users/undisclosed/.ansible/tmp/ansible-tmp-1655193160.437197-43269-14744921007585/AnsiballZ_bigip_ucs.py && sleep 0'
<192.168.226.10> EXEC /bin/sh -c 'rm -f -r /Users/undisclosed/.ansible/tmp/ansible-tmp-1655193160.437197-43269-14744921007585/ > /dev/null 2>&1 && sleep 0'
changed: [f5 -> localhost(192.168.226.10)] => {
    "changed": true,
    "invocation": {
        "module_args": {
            "force": true,
            "include_chassis_level_config": null,
            "no_license": true,
            "no_platform_check": null,
            "passphrase": null,
            "provider": {
                "auth_provider": null,
                "no_f5_teem": null,
                "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
                "server": "192.168.226.10",
                "server_port": 443,
                "timeout": 1800,
                "transport": "rest",
                "user": "user1",
                "validate_certs": false
            },
            "reset_trust": null,
            "state": "present",
            "ucs": "config/f5/UseCase-00-backup-myfile.ucs"
        }
    }
}
META: ran handlers
META: ran handlers

PLAY RECAP *********************************************************************************************************************
f5                         : ok=3    changed=1    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0   

The UCS file on the filesystem looks like:

ls -als /var/local/ucs/
total 8480
   4 drwxr-xr-x. 3 root root      4096 Jun 14 00:37 .
   4 drwxr-xr-x. 9 root root      4096 Jun  9 09:28 ..
   4 -r--r--r--. 1 root root       176 Mar 28 01:26 cs_backup_rotate.conf
2836 -rw-r--r--. 1 root root   2901322 Jun 14 00:36 cs_backup.ucs
2812 -rw-r--r--. 1 root root   2878708 Jun 10 09:07 cs_backup.ucs.1
   4 drwxr-xr-x. 2 root root      4096 Jun  9 09:39 tmp
2816 -rw-r-----. 1 root apache 2880358 Jun 14 00:37 UseCase-00-backup-myfile
```

**Comment by ronrem** [comment]
Temporally workaround provided via:
```
    - name: Change file ownership, group and permissions
      ansible.builtin.file:
        path: "/var/local/ucs/UseCase-00-backup-myfile"
        owner: root
        group: root
        mode: '0644'
      register: output
```
