### ISSUE TITLE
Unable to run F5 modules from Ansible AWX but works when run manually

### ISSUE THREAD

**Issue by CatchKarthik** [F5Networks/f5-ansible#2228]
##### COMPONENT NAME

bigip_pool

##### ANSIBLE VERSION

```
ansible [core 2.11.2.post0]
python version = 3.8.12
```
##### BIGIP VERSION

```
Version 14.1.4
Build 0.120.11
```
##### CONFIGURATION

No additional configurations in ansible.cfg. I use ansible AWX 19.2.2 to create job template and run job
##### OS / ENVIRONMENT

N/A
##### SUMMARY

I have a playbook that uses the module bigip_pool to create a pool in F5. The playbook is run using a job template in Ansible AWX. The job runs successfully and provides a successful output. However, the pool is not created in the F5. The same playbook when run manually can create the pool without issues. 

I have validated the connectivity, username and password. It is correct. I have also verified the execution environment and the image that is used for the execution environment in ansible AWX. The F5 module collections are installed in the image and i was able to run the playbook from the docker image successfully.

##### STEPS TO REPRODUCE

```
- name: Create pool
  bigip_pool:
    state: present
    name: my-pool
    partition: Common
    lb_method: least-connections-member
    slow_ramp_time: 120
    provider:
      server: xxxxxx
      user: xxxxx
      password: xxxx
  delegate_to: localhost
```

##### EXPECTED RESULTS

The playbook should be able to create pool in F5 when run from Ansible AWX.
##### ACTUAL RESULTS

The pool is not getting created when the job is run from Ansible AWX. But the pool is created successfully when we run the job manually using ansible-playbook command

```

```
