### ISSUE TITLE
bigip_asm_policy_signature_set module not removing Signature Set from ASM Policy

### ISSUE THREAD

**Issue by brsanche** [F5Networks/f5-ansible#2231]
##### COMPONENT NAME
bigip_asm_policy_signature_set

##### ANSIBLE VERSION

```
ansible-2.9.13
```

##### SUMMARY
bigip_asm_policy_signature_set module not removing Signature Set from ASM Policy

##### STEPS TO REPRODUCE

```
- name: Add Signature Set to ASM Policy
  bigip_asm_policy_signature_set:
    name: IIS and Windows Signatures
    policy_name: FooPolicy
    provider:
      password: secret
      server: lb.mydomain.com
      user: admin
  delegate_to: localhost

- name: Remove Signature Set to ASM Policy
  bigip_asm_policy_signature_set:
    name: IIS and Windows Signatures
    policy_name: FooPolicy
    state: absent
    provider:
      password: secret
      server: lb.mydomain.com
      user: admin
  delegate_to: localhost
```

##### EXPECTED RESULTS
Signature should be successfully removed with the module.

##### ACTUAL RESULTS
Signature will be added successfully but will not be removed.

**Comment by trinaths** [comment]
Created [INFRAANO-809] for internal tracking.

**Comment by wojtek0806** [comment]
@brsanche 
not reproducible, i have tested this with the following playbook:
```
---
- name: Test Bigip Asm Policy Sig
  hosts: all
  gather_facts: no
  connection: local  collections:
   - f5networks.f5_modules  environment:
      F5_SERVER: "{{ ansible_host }}"
      F5_USER: "admin"
      F5_PASSWORD: "admin"
      F5_VALIDATE_CERTS: "false"
      F5_SERVER_PORT: 8443
  tasks:
    - name: Create blank ASM policy and activate
      bigip_asm_policy_manage:
        name: new_blank_policy_active
        active: yes
        state: present    - name: Create blank ASM policy, not active
      bigip_asm_policy_manage:
        name: new_blank_policy_inactive
        state: present    - name: Add Signature Set to active ASM Policy
      bigip_asm_policy_signature_set:
        name: "IIS Signatures (High/Medium Accuracy)"
        policy_name: new_blank_policy_active    - name: Add Signature Set to inactive ASM Policy
      bigip_asm_policy_signature_set:
        name: "IIS Signatures (High/Medium Accuracy)"
        policy_name: new_blank_policy_inactive    - name: Remove Signature Set from active ASM Policy
      bigip_asm_policy_signature_set:
        name: "IIS Signatures (High/Medium Accuracy)"
        policy_name: new_blank_policy_active
        state: absent    - name: Remove Signature Set from inactive ASM Policy
      bigip_asm_policy_signature_set:
        name: "IIS Signatures (High/Medium Accuracy)"
        policy_name: new_blank_policy_inactive
        state: absent 
```
Running this on 16.0.0 and it works fine. I have found few edge cases and other small bugs while testing for this so I will submit PR but the issue you reported here does not occur.

One thing I did not do was applying policy after each change, so I have repeated the above tests this time applying the policy in the GUI (you can also do this with bigip_asm_policy_manage module) but the outcome was the same, POSTMAN queries returned the correct number of signature sets in the policy. See below snippets:

added:
```
{
    "kind": "tm:asm:policies:signature-sets:signature-setcollectionstate",
    "selfLink": "https://localhost/mgmt/tm/asm/policies/eW3Jt-CaqvmJfEblMpFZAw/signature-sets?ver=16.0.0",
    "totalItems": 2,
    "items": [
        {
            "signatureSetReference": {
                "link": "https://localhost/mgmt/tm/asm/signature-sets/HnOBYw9EUtyjWnIYVTTqgA?ver=16.0.0",
                "name": "IIS Signatures (High/Medium Accuracy)"
            },
            "lastUpdateMicros": 1.6599584e+15,
            "selfLink": "https://localhost/mgmt/tm/asm/policies/eW3Jt-CaqvmJfEblMpFZAw/signature-sets/e8Hf1eYWiZF3Mzi4M89dnA?ver=16.0.0",
            "kind": "tm:asm:policies:signature-sets:signature-setstate",
            "alarm": true,
            "block": true,
            "id": "e8Hf1eYWiZF3Mzi4M89dnA",
            "learn": true
        },
        {
            "signatureSetReference": {
                "link": "https://localhost/mgmt/tm/asm/signature-sets/NZlPqTTKcjePnB1BfDWl0A?ver=16.0.0",
                "name": "Generic Detection Signatures (High/Medium Accuracy)"
            },
            "lastUpdateMicros": 1.659956232e+15,
            "selfLink": "https://localhost/mgmt/tm/asm/policies/eW3Jt-CaqvmJfEblMpFZAw/signature-sets/R-pNJJT0nt0zsUTygsUZUQ?ver=16.0.0",
            "kind": "tm:asm:policies:signature-sets:signature-setstate",
            "alarm": true,
            "block": true,
            "id": "R-pNJJT0nt0zsUTygsUZUQ",
            "learn": true
        }
    ]
}
```
removed:
```
{
    "kind": "tm:asm:policies:signature-sets:signature-setcollectionstate",
    "selfLink": "https://localhost/mgmt/tm/asm/policies/eW3Jt-CaqvmJfEblMpFZAw/signature-sets?ver=16.0.0",
    "totalItems": 1,
    "items": [
        {
            "signatureSetReference": {
                "link": "https://localhost/mgmt/tm/asm/signature-sets/NZlPqTTKcjePnB1BfDWl0A?ver=16.0.0",
                "name": "Generic Detection Signatures (High/Medium Accuracy)"
            },
            "lastUpdateMicros": 1.659956232e+15,
            "selfLink": "https://localhost/mgmt/tm/asm/policies/eW3Jt-CaqvmJfEblMpFZAw/signature-sets/R-pNJJT0nt0zsUTygsUZUQ?ver=16.0.0",
            "kind": "tm:asm:policies:signature-sets:signature-setstate",
            "alarm": true,
            "block": true,
            "id": "R-pNJJT0nt0zsUTygsUZUQ",
            "learn": true
        }
    ]
} 
```
