### ISSUE TITLE
bigip_ucs_fetch.py - Missing passphrase argument in class ArgumentSpec(object)

### ISSUE THREAD

**Issue by varulleir** [F5Networks/f5-ansible#2260]
### Is your feature request related to a problem? Please describe.

USC Fetch supports the use of an encryption_password on the UCS however the argument "passphrase" it is not implemented within the ArgumentSpec class to allow it to be used. the "passphrase" argument is used throughout the script and works as intended with the below modifications.

### Describe the solution you'd like

Add the following to class ArgumentSpec(object):

            passphrase=dict(
                default='no',
                type='bool'
            ),

and the following into the Documentation under options:

  passphrase:
    description:
      - Creates an Encrypted UCS using the value set in encryption_password
    type: bool
    default: no

### Describe alternatives you've considered

The only alternative is to have unencrypted UCS Files. This is not permitted by my InfoSec as they contain Private Keys.

### Additional context

Thank you for your time.

**Comment by KrithikaChidambaram** [comment]
Hi, encryption_password is used to encrypt the UCS.
Have you tried using encryption_password and did it work?
If not, please reach out to us.

**Comment by varulleir** [comment]
Krithika,

That is correct, I'm using encryption_password and it does not encrypt the
UCS without the modifications to the code that I mentioned. The passphrase
parameter is needed to trigger the encryption_password being used.

Regards,

Varul Leir

**Comment by KrithikaChidambaram** [comment]
Hi, this has been added to our backlog, tracking internally: INFRAANO-1089, thanks!

**Comment by prateekramani** [comment]
Hi @varulleir 

I tried running the below playbooks, and noticed:

- If I am passing encryption password, I see encrypted as "Yes" on GUI
- If I don't pass encryption password, I see encrypted as "No" on GUI

I did the testing on BIG-IP 17.1.2.1, and it works as expected.

```
- name: Create a UCS with encryption password
  bigip_ucs_fetch:
    dest: "<Path>/test_14.ucs"
    encryption_password: 2admin
    src: "<Path>/test_14.ucs"
```

![Image](https://github.com/user-attachments/assets/ceea0b22-ff8e-4718-83ce-60e8b6b26a56)


```
- name: Create a UCS without encryption
  bigip_ucs_fetch:
    dest: "<Path>/test_15.ucs"
    src: "<Path>/test_15.ucs"
```

![Image](https://github.com/user-attachments/assets/ef2e7405-dc67-4bd4-8915-aa71dc3afb27)
