### ISSUE TITLE
bigip_device_info: not possible to get data from all partitions at once

### ISSUE THREAD

**Issue by wisentius** [F5Networks/f5-ansible#2287]
##### COMPONENT NAME
bigip_device_info

##### ANSIBLE VERSION
```
ansible [core 2.12.2]
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/support/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/support/.local/lib/python3.8/site-packages/ansible
  ansible collection location = /home/support/.ansible/collections:/usr/share/ansible/collections
  executable location = /home/support/.local/bin/ansible
  python version = 3.8.10 (default, Jun 22 2022, 20:18:18) [GCC 9.4.0]
  jinja version = 2.10.1
  libyaml = True
```
##### BIGIP VERSION
```
Sys::Version
Main Package
  Product     BIG-IP
  Version     14.1.4.6
  Build       0.0.8
  Edition     Point Release 6
  Date        Mon Mar 28 02:38:32 PDT 2022
```
##### CONFIGURATION
upgraded ansible module to 1.14

##### OS / ENVIRONMENT
WSL

##### SUMMARY
When using the bigip_device_info it's only possible to filter on 1 partition.
in earlier version all data was gathered. There should be an option to set 
this to "All".

##### STEPS TO REPRODUCE
```
- name: "Get self ips"
  bigip_device_info:
   partition: All
    provider:
      user: "{{ automation_user }}"
      password: "{{ automation_pass }}"
      validate_certs: false
      server: "{{ inventory_hostname }}"
      transport: rest
    gather_subset:
      - self-ips
  delegate_to: localhost
  register: reg_selfips
```

##### EXPECTED RESULTS
Get info from all partitions

##### ACTUAL RESULTS
```
Error message: "The requested folder (/All) was not found
```
