### ISSUE TITLE
bigip_firewall_rule: Unable to reset to "Any" for Source and Destination

### ISSUE THREAD

**Issue by SebastianThorn** [F5Networks/f5-ansible#2290]
##### COMPONENT NAME
bigip_firewall_rule 

##### ANSIBLE VERSION

```
ansible [core 2.13.3]
  config file = /home/user/.ansible.cfg
  configured module search path = ['/home/user/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/user/ansible-venv/lib/python3.8/site-packages/ansible
  ansible collection location = /home/user/.ansible/collections:/usr/share/ansible/collections
  executable location = /home/user/ansible-venv/bin/ansible
  python version = 3.8.10 (default, Jun 22 2022, 20:18:18) [GCC 9.4.0]
  jinja version = 3.0.3
  libyaml = True 
```
##### BIGIP VERSION

```
Version: 16.1.3.2 Build 0.0.4
```
##### OS / ENVIRONMENT
Linux
##### SUMMARY
We are trying to reset the rule "block" to Any/Any.
We have tried different variants without any success.

When adding the block-rule the first time, it gets set to Any/Any, but if someone fiddles with the rule, we want to be able to reset it to Any/Any with code.

##### STEPS TO REPRODUCE

```
- name: Create a new rule in the foo firewall policy
  bigip_firewall_rule:
    provider: "{{ f5_provider }}"
    partition: "{{ f5_partition_name }}"
    name: block
    source:
      - address:
    destination:
      - address: 0.0.0.0
    parent_policy: "{{ loadbalancer.f5_firewall_policy_name }}"
    action: reject
    logging: yes 
```

##### EXPECTED RESULTS
Resset fw-rule to "Any"

##### ACTUAL RESULTS
Nothing, or an errors
