### ISSUE TITLE
modify bigip_device_certificate via ansible playbook 

### ISSUE THREAD

**Issue by smeisenzahl** [F5Networks/f5-ansible#2295]
Attempting to change the device certificate on a newly created BIGIP with an ansible playbook, is not working as expected.  The following article in being referenced for this build;
https://clouddocs.f5.com/products/orchestration/ansible/devel/modules/bigip_device_certificate_module.html#bigip-device-certificate-module-3

The playbook in question is as follows;
```
---
- hosts: tenants
  connection: local
  gather_facts: false

  vars:
    provider:
      server: "{{ten1_ip}}"
      user: "{{def_admin}}"
      password: "{{new_admin_pass}}"
      server_port: 443
      validate_certs: no

      # collections:
      # - f5networks.f5_bigip

  tasks:
    - name: Create a new certificate to replace an expired certificate
      bigip_device_certificate:
        days_valid: 3650
        new_cert: yes
        issuer:
          country: US
          state: WA
          common_name: big-ip-lab1.f5net
        provider:
          password: "{{new_root_pass}}"
          server: "{{inventory_hostname}}"
          user: "{{def_root}}"
          transport: cli
          server_port: 22
      delegate_to: localhost

```
The referenced inventory file is as follows;
[tenants]
big-ip-lab1 inventory_hostname=10.154.85.124 def_admin=admin def_root=root ten1_ip=10.154.85.124 def_admin_pass=admin def_root_pass=default new_root_pass=nLv0zhRn new_admin_pass=nLv0zhRn

Below is the output error when attempting to run the playbook;

TASK [Create a new certificate to replace expired certificate] **********************************
task path: /home/ansible/rseries/post/device-cert2.yaml:18
redirecting (type: modules) ansible.builtin.bigip_device_certificate to f5networks.f5_modules.bigip_device_certificate
redirecting (type: action) ansible.builtin.bigip to f5networks.f5_modules.bigip
redirecting (type: action) ansible.builtin.bigip to f5networks.f5_modules.bigip
<big-ip-lab1> using connection plugin network_cli
redirecting (type: connection) ansible.builtin.persistent to ansible.netcommon.persistent
The full traceback is:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/ansible/executor/task_executor.py", line 159, in run
    res = self._execute()
  File "/usr/lib/python3/dist-packages/ansible/executor/task_executor.py", line 617, in _execute
    result = self._handler.run(task_vars=variables)
  File "/root/.ansible/collections/ansible_collections/f5networks/f5_modules/plugins/action/bigip.py", line 91, in run
    out = conn.get_prompt()
  File "/usr/lib/python3/dist-packages/ansible/module_utils/connection.py", line 200, in __rpc__
    raise ConnectionError(to_text(msg, errors='surrogate_then_replace'), code=code)
ansible.module_utils.connection.ConnectionError: ssh connection failed: ssh connect failed: Failed to resolve hostname inventory_hostname (Temporary failure in name resolution)
fatal: [big-ip-lab1 -> localhost]: FAILED! => {
    "msg": "Unexpected failure during module execution.",
    "stdout": ""
}

PLAY RECAP **************************************************************************************
big-ip-lab1                : ok=0    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0   

### Describe the solution you'd like
I need to understand the correct playbook syntax to be able to automate device certificate changes on over 100 new BIGIPs

### Describe alternatives you've considered
The client does not want to physically touch the BIGIPs, they only want to use playbooks to update and configure objects.
