### ISSUE TITLE
bigip_pool module is unable to remove monitors

### ISSUE THREAD

**Issue by jbisabel** [F5Networks/f5-ansible#2347]
##### COMPONENT NAME
f5networks.f5_modules.bigip_pool

##### ANSIBLE VERSION
```
ansible-playbook [core 2.15.2]
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/****/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/****/python-venv/ansible2.15/lib64/python3.11/site-packages/ansible
  ansible collection location = /home/****/.ansible/collections:/usr/share/ansible/collections
  executable location = /home/****/python-venv/ansible2.15/bin/ansible-playbook
  python version = 3.11.2 (main, Feb 17 2023, 09:28:16) [GCC 8.5.0 20210514 (Red Hat 8.5.0-18)] (/home/****/python-venv/ansible2.15/bin/python)
  jinja version = 3.1.2
  libyaml = True
```
##### BIGIP VERSION
BIG-IP 16.1.2.2 Build 0.0.28 Point Release 2

##### SUMMARY
If you create an LTM pool with a monitor, it's impossible to remove the monitor afterwards

##### STEPS TO REPRODUCE
```
---
- name: Test Bigip Pool
  hosts: localhost
  gather_facts: no
  connection: local

  tasks:
    - name: Create a pool with monitor
      f5networks.f5_modules.bigip_pool:
        name: "testpool"
        priority_group_activation: 1
        lb_method: "least-connections-member"
        monitors:
          - /Common/m_https_common_lbzone
        slow_ramp_time: 300
        partition: "The_Partition"
        provider:
          user: "admin"
          password: "password"
          server: "f5.example.com"
          server_port: 443
          no_f5_teem: true
          timeout: 10
          transport: rest
          validate_certs: true
        state: "present"

    - name: Remove monitor
      f5networks.f5_modules.bigip_pool:
        name: "testpool"
        priority_group_activation: 1
        lb_method: "least-connections-member"
        slow_ramp_time: 300
        partition: "The_Partition"
        provider:
          user: "admin"
          password: "password"
          server: "f5.example.com"
          server_port: 443
          no_f5_teem: true
          timeout: 10
          transport: rest
          validate_certs: true
        state: "present"
```

##### EXPECTED RESULTS
The monitor gets removed

##### ACTUAL RESULTS
```
...

TASK [Remove monitor] *******************************************************************************************************************************************************************************************************************************************************************************************************
The full traceback is:
  File "/tmp/ansible_f5networks.f5_modules.bigip_pool_payload_9wy4j7ta/ansible_f5networks.f5_modules.bigip_pool_payload.zip/ansible_collections/f5networks/f5_modules/plugins/modules/bigip_pool.py", line 1352, in main
  File "/tmp/ansible_f5networks.f5_modules.bigip_pool_payload_9wy4j7ta/ansible_f5networks.f5_modules.bigip_pool_payload.zip/ansible_collections/f5networks/f5_modules/plugins/modules/bigip_pool.py", line 899, in exec_module
  File "/tmp/ansible_f5networks.f5_modules.bigip_pool_payload_9wy4j7ta/ansible_f5networks.f5_modules.bigip_pool_payload.zip/ansible_collections/f5networks/f5_modules/plugins/modules/bigip_pool.py", line 946, in execute
  File "/tmp/ansible_f5networks.f5_modules.bigip_pool_payload_9wy4j7ta/ansible_f5networks.f5_modules.bigip_pool_payload.zip/ansible_collections/f5networks/f5_modules/plugins/modules/bigip_pool.py", line 993, in present
  File "/tmp/ansible_f5networks.f5_modules.bigip_pool_payload_9wy4j7ta/ansible_f5networks.f5_modules.bigip_pool_payload.zip/ansible_collections/f5networks/f5_modules/plugins/modules/bigip_pool.py", line 1014, in update
  File "/tmp/ansible_f5networks.f5_modules.bigip_pool_payload_9wy4j7ta/ansible_f5networks.f5_modules.bigip_pool_payload.zip/ansible_collections/f5networks/f5_modules/plugins/modules/bigip_pool.py", line 1129, in update_on_device
fatal: [localhost]: FAILED! => {
    "changed": false,
    "invocation": {
        "module_args": {
            "aggregate": null,
            "description": null,
            "lb_method": "least-connections-member",
            "metadata": null,
            "min_up_members": null,
            "min_up_members_action": null,
            "min_up_members_checking": null,
            "monitor_type": null,
            "monitors": null,
            "name": "testpool",
            "partition": "The_Partition",
            "priority_group_activation": 1,
            "provider": {
                "auth_provider": null,
                "no_f5_teem": true,
                "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
                "server": "f5.example.com",
                "server_port": 443,
                "timeout": 10,
                "transport": "rest",
                "user": "admin",
                "validate_certs": true
            },
            "quorum": null,
            "replace_all_with": false,
            "reselect_tries": null,
            "service_down_action": null,
            "slow_ramp_time": 300,
            "state": "present"
        }
    },
    "msg": "one or more properties must be specified"
}

PLAY RECAP ******************************************************************************************************************************************************************************************************************************************************************************************************************
localhost                  : ok=1    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0

```
