### ISSUE TITLE
Ansible bigip_ucs_fetch timeout after 2 minutes

### ISSUE THREAD

**Issue by gchambard** [F5Networks/f5-ansible#2349]
##### COMPONENT NAME
ansible_collections/f5networks/f5_modules/plugins/modules/bigip_ucs_fetch.py

##### ANSIBLE VERSION
```
ansible [core 2.12.10]
  config file = /home/sa-automation/.ansible.cfg
  configured module search path = ['/home/sa-automation/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/sa-automation/.local/lib/python3.9/site-packages/ansible
  ansible collection location = /var/lib/ansible/collections:/usr/share/ansible/collections
  executable location = /home/sa-automation/.local/bin/ansible
  python version = 3.9.2 (default, Feb 28 2021, 17:03:44) [GCC 10.2.1 20210110]
  jinja version = 3.0.3
  libyaml = True

```
##### BIGIP VERSION
```
Sys::Version
Main Package
  Product     BIG-IP
  Version     15.1.8.2
  Build       0.0.17
  Edition     Point Release 2
  Date        Thu Mar 16 03:44:11 PDT 2023

```
##### CONFIGURATION
[defaults]
host_key_checking = False
collections_paths  = /var/lib/ansible/collections:/usr/share/ansible/collections
interpreter_python=auto
vault_password_file = ~/.vault_password
timeout=40
jinja2_extensions = jinja2.ext.do,jinja2.ext.loopcontrols

##### OS / ENVIRONMENT

Linux 5.10.0-22-amd64 #1 SMP Debian 5.10.178-3 (2023-04-22) x86_64 GNU/Linux

##### SUMMARY
We save our ucs archive with ansible and f5networks modules. It works for all our clusters except for the largest configuration (Nodes with LTM and APM and ASM etc.).
The job failed with "An exception occurred during task execution. To see the full traceback, use -vvv. The error was: socket.timeout: The read operation timed out"
Our ucs file is heavy ~1Go. Generate ucs file in GUI or CLI work fine and take ~4minutes. We can see an java timeout in restjavad log after 2 minutes.

We try to incrase differents timeout option, with F5 support (async_timeout in playbook, ansible.cfg, icrd and restjavad in Bigip), without success. 

With our devops team we found this, and the F5 support asking to raise the quesitons directly here:

In bigip_ucs_fetch.py, line 505, the "async_wait" def used the "https://{0}:{1}/mgmt/tm/task/sys/ucs/{2}/result" URL to check the result of the task.
https://github.com/F5Networks/f5-ansible/blob/devel/ansible_collections/f5networks/f5_modules/plugins/modules/bigip_ucs_fetch.py
This URL is used line 511 with the "api" property (resp = self.client.api.get(uri)).
This property is in the definition class "iControlRestSession" from icontrol.py, line 130
https://github.com/F5Networks/f5-ansible/blob/devel/ansible_collections/f5networks/f5_modules/plugins/module_utils/icontrol.py
This class has a timeout set at 120 in the def __init__.

If we increase this value, the ansible playbook works normally.

Our analyse:
The line 511 (resp = self.client.api.get(uri)) wait a result and do not exit whitout something.
So, the loop for is useless.
With a big UCS file, the save task take more 120 seconds and the task's result check falls in timeout before the end.
This timeout causes the ansible error.

##### STEPS TO REPRODUCE

Try to generate an heavy UCS file with Ansible playbook and bigip_ucs_fetch or decrease the timeout in icontrol.py

Exemple playbook task:
```
    - name: "Create a new UCS file from {{ hostname }}"
      f5networks.f5_modules.bigip_ucs_fetch:
        src: "{{ ucs_name }}"
        only_create_file: true
        async_timeout: 1200
        provider: "{{ bigip_provider }}"
      delegate_to: localhost

```

##### EXPECTED RESULTS
The playbook generate UCS file without error after 2 minutes.

##### ACTUAL RESULTS
```
The playbook crash after 2 minutes with error: "An exception occurred during task execution. To see the full traceback, use -vvv. The error was: socket.timeout: The read operation timed out"

```

**Comment by pgouband** [comment]
Hi @gchambard,

Have you tried using bigip-ucs-fetch from declarative collection? https://clouddocs.f5.com/products/orchestration/ansible/devel/f5_bigip/modules_2_0/bigip_ucs_fetch_module.html#bigip-ucs-fetch-module-2

There is a timeout parameter.

**Comment by pooyesh-jpg** [comment]
We have the exact same issue !
I cannot run #ansible-galaxy collection list on the current version of Ansible which is installed :2.9.27 
How can I check if declarative collection is installed.
I try to change the playbook as described in above link but is not accepting timeout .

**Comment by pgouband** [comment]
Hi @pooyesh-jpg,

Here is the procedure to install declarative collection:
https://clouddocs.f5.com/products/orchestration/ansible/devel/f5_bigip/install_f5_bigip.html

**Comment by pooyesh-jpg** [comment]
I have installed the declarative collection fine.
but when running the playbook receiving below error:
msg": "unable to load API plugin for network_os f5networks.f5_bigip.bigip"

**Comment by gchambard** [comment]
> Hi @gchambard,
> 
> Have you tried using bigip-ucs-fetch from declarative collection? https://clouddocs.f5.com/products/orchestration/ansible/devel/f5_bigip/modules_2_0/bigip_ucs_fetch_module.html#bigip-ucs-fetch-module-2
> 
> There is a timeout parameter.

Hi,

sorry for my late reply, i've been working on another project.

I've tested the declarative collection and it doesn't seem to take the "timeout" parameter. The playbook return a timeout command error after 30 secondes. I've set it to 300 in my playbook.

    - name: Create a new UCS
      f5networks.f5_bigip.bigip_ucs_fetch:
        src: "{{ ucs_name }}"
        only_create_file: true
        timeout: 300
      register: task

    - name: Check for task completion and download created UCS
      f5networks.f5_bigip.bigip_ucs_fetch:
        dest: "{{ path + bigip + '/' + ucs_name }}"
        src: "{{ task.src }}"
        task_id: "{{ task.task_id }}"
        timeout: 300

If possible, i preferred to stay with the imperative collection. It's more easier to set up provider informations.

**Comment by gchambard** [comment]
HI,

after more tests, I managed to get the script to work with declarative collection and i reproduce the issue.
For that, i needed to increase the "ansible_command_timeout".

My playbook: 

```
- name: Set connection variables
  ansible.builtin.set_fact:
    ansible_host: "{{ bigip_provider.server }}"
    ansible_user: "{{ bigip_provider.user }}"
    ansible_httpapi_password: "{{ bigip_provider.password }}"
    ansible_network_os: f5networks.f5_bigip.bigip
    ansible_httpapi_use_ssl: true
    ansible_httpapi_validate_certs: false
    ansible_command_timeout: 1000
  delegate_to: localhost

- name: Create a new UCS
  f5networks.f5_bigip.bigip_ucs_fetch:
    dest: "{{ path + bigip + '/' + ucs_name }}"
  register: task

- name: Check for task completion and download created UCS
  f5networks.f5_bigip.bigip_ucs_fetch:
    dest: "{{ path + bigip + '/' + ucs_name }}"
    src: "{{ task.src }}"
    task_id: "{{ task.task_id }}"
    timeout: 1000
```

After ~300 secondes i've this error in "Create a new UCS" task: 
```
fatal: [bigip]: FAILED! => {
    "changed": false,
    "module_stderr": "Expecting value: line 1 column 1 (char 0)",
    "module_stdout": "",
    "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error"
}
```
