### ISSUE TITLE
Is there a module to add/remove items from datagroup?

### ISSUE THREAD

**Issue by AndrewSav** [F5Networks/f5-ansible#2352]
>  Using "write" commands is not idempotent. You should use a module that is specifically made for that. If such a module does not exist, then please file a bug. The command in question is "modify ltm data-group internal..."

I was not able to find a module that adds or removes items to/form datagroups. Running the generic command to do that gives the warning above and asks to file a bug. Did I miss the module?

**Comment by AndrewSav** [comment]
@pgouband, no I have not tried using that.

**Comment by pgouband** [comment]
Hi @AndrewSav,

Here the link for data group module in imperative collection:
https://clouddocs.f5.com/products/orchestration/ansible/devel/modules/bigip_data_group_module.html#bigip-data-group-module-3

In declarative collection, there is no module as data group can be managed via AS3.

**Comment by AndrewSav** [comment]
@pgouband thank you for that. Does that module allow to add or remove individual records in a datagroup? That should be quite a common use case, but by reading this documentation I do not see a way of removing a single record.

I'm currently doing something like this:

```
- name: Delete Item from DataGroup on F5
  f5networks.f5_modules.bigip_command:
    commands: modify ltm data-group internal {{ f5_datagroup }} records delete { {{ datagroup_item }} }
    provider:
      server: "{{ f5_server[f5_environment] }}"
      password: "{{ f5_password.data.data.data.password }}"
      user: "{{ f5_user }}"
      validate_certs: "no"
      server_port: 443
      no_f5_teem: true
  delegate_to: localhost
```

Which gives the aforementioned warning. What is the right way to do this then?

**Comment by pgouband** [comment]
Hi @AndrewSav,

You can use bigip_as3_deploy module from declarative collection:
https://clouddocs.f5.com/products/orchestration/ansible/devel/f5_bigip/modules_2_0/bigip_as3_deploy_module.html#bigip-as3-deploy-module-2

Here an example.

as3-dg.yml file
```yaml
- hosts: all
  collections:
    - f5networks.f5_bigip
  connection: httpapi

  vars:
    ansible_host: "X.X.X.X"
    ansible_user: "admin"
    ansible_httpapi_password: "mysecretpassword"
    ansible_network_os: f5networks.f5_bigip.bigip
    ansible_httpapi_use_ssl: yes
    ansible_httpapi_validate_certs: no

  tasks:
    - name: Data group
      bigip_as3_deploy:
        content: "{{ lookup('file', 'as3-dg.json') }}"
```

as3-dg.json file
```ansible
{
     "class": "AS3",
     "action": "deploy",
     "persist": true,
    "declaration": {
        "class": "ADC",
        "schemaVersion": "3.0.0",
        "id": "datagroup",
        "Sample_non_http_04": {
            "class": "Tenant",
            "appWeb": {
                "class": "Application",
                "dataGroupRefInternal": {
                    "class": "Data_Group",
                    "label": "Tag values mapping",
                    "storageType": "internal",
                    "name": "Internal-Int",
                    "keyDataType": "integer",
                    "records": [
                        {
                            "key": 121212,
                            "value": "Summer"
                        },
                        {
                            "key": 3434,
                            "value": "Internal"
                        }
                    ]
                }
            }
        }
    }
}
```

as3-dg.json file after removing one entry.
```ansible
{
     "class": "AS3",
     "action": "deploy",
     "persist": true,
    "declaration": {
        "class": "ADC",
        "schemaVersion": "3.0.0",
        "id": "datagroup",
        "Sample_non_http_04": {
            "class": "Tenant",
            "appWeb": {
                "class": "Application",
                "dataGroupRefInternal": {
                    "class": "Data_Group",
                    "label": "Tag values mapping",
                    "storageType": "internal",
                    "name": "Internal-Int",
                    "keyDataType": "integer",
                    "records": [
                        {
                            "key": 121212,
                            "value": "Summer"
                        }
                    ]
                }
            }
        }
    }
}
```
