### ISSUE TITLE
bigip_device_certificate traceback on line 451 TypeError: '>' not supported between instances of 'int' and 'NoneType'

### ISSUE THREAD

**Issue by apellini** [F5Networks/f5-ansible#2353]
##### COMPONENT NAME
bigip_device_certificate

##### ANSIBLE VERSION
```
ansible [core 2.13.6]
  config file = /spimi/NetDevOps/terraform-deploy-f5/postconfig/ansible.cfg
  configured module search path = ['/root/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.9/site-packages/ansible
  ansible collection location = /root/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/local/bin/ansible
  python version = 3.9.4 (default, Apr 14 2021, 10:57:48) [GCC 4.8.5 20150623 (Red Hat 4.8.5-39)]
  jinja version = 3.1.2
  libyaml = True
```
##### BIGIP VERSION
```
Sys::Version
Main Package
  Product     BIG-IP
  Version     16.1.3.2
  Build       0.0.4
  Edition     Point Release 2
  Date        Wed Sep 14 08:12:07 PDT 2022
```
##### CONFIGURATION
```
[defaults]
inventory = ./inventory
host_key_checking = False
interpreter_python = /usr/local/bin/python3.9
forks = 50
gathering = explicit
roles_path = roles/
deprecation_warnings = False
warnings = False
display_skipped_hosts = no
callback_whitelist = timer, profile_tasks
show_custom_stats = yes
check_mode_markers = yes

[persistent_connection]
ssh_type = paramiko
```
##### OS / ENVIRONMENT
RHEL 7
##### SUMMARY
We receive traceback error:

line 451, in expired\nTypeError: '>' not supported between instances of 'int' and 'NoneType'
##### STEPS TO REPRODUCE

```
      - name: Generate new device certificate
        bigip_device_certificate:
          provider: "{{ provider_cli }}"
          days_valid: "{{ baseline.device_certificate.days | int }}"
          force: "{{ baseline.device_certificate.force }}"
          key_size: "{{ baseline.device_certificate.key_size }}"
          issuer:
            division: "{{ baseline.device_certificate.division }}"
            organization: "{{ baseline.device_certificate.organization }}"
            common_name: "{{ inventory_hostname }}"
            state: "{{ baseline.device_certificate[region].state }}"
            country: "{{ baseline.device_certificate[region].country }}"
            locality: "{{ location }}"
```

##### EXPECTED RESULTS
Certificate created
##### ACTUAL RESULTS

```
{"changed": false, "module_stderr": "Traceback (most recent call last):\n  File \"/home/B0J0456/.ansible/tmp/ansible-tmp-1692695570.796826-3220-229136870993090/AnsiballZ_bigip_device_certificate.py\", line 107, in <module>\n    _ansiballz_main()\n  File \"/home/B0J0456/.ansible/tmp/ansible-tmp-1692695570.796826-3220-229136870993090/AnsiballZ_bigip_device_certificate.py\", line 99, in _ansiballz_main\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\n  File \"/home/B0J0456/.ansible/tmp/ansible-tmp-1692695570.796826-3220-229136870993090/AnsiballZ_bigip_device_certificate.py\", line 47, in invoke_module\n    runpy.run_module(mod_name='ansible_collections.f5networks.f5_modules.plugins.modules.bigip_device_certificate', init_globals=dict(_module_fqn='ansible_collections.f5networks.f5_modules.plugins.modules.bigip_device_certificate', _modlib_path=modlib_path),\n  File \"/usr/local/lib/python3.9/runpy.py\", line 210, in run_module\n    return _run_module_code(code, init_globals, run_name, mod_spec)\n  File \"/usr/local/lib/python3.9/runpy.py\", line 97, in _run_module_code\n    _run_code(code, mod_globals, init_globals,\n  File \"/usr/local/lib/python3.9/runpy.py\", line 87, in _run_code\n    exec(code, run_globals)\n  File \"/tmp/ansible_bigip_device_certificate_payload_g3w_ji00/ansible_bigip_device_certificate_payload.zip/ansible_collections/f5networks/f5_modules/plugins/modules/bigip_device_certificate.py\", line 626, in <module>\n  File \"/tmp/ansible_bigip_device_certificate_payload_g3w_ji00/ansible_bigip_device_certificate_payload.zip/ansible_collections/f5networks/f5_modules/plugins/modules/bigip_device_certificate.py\", line 619, in main\n  File \"/tmp/ansible_bigip_device_certificate_payload_g3w_ji00/ansible_bigip_device_certificate_payload.zip/ansible_collections/f5networks/f5_modules/plugins/modules/bigip_device_certificate.py\", line 406, in exec_module\n  File \"/tmp/ansible_bigip_device_certificate_payload_g3w_ji00/ansible_bigip_device_certificate_payload.zip/ansible_collections/f5networks/f5_modules/plugins/modules/bigip_device_certificate.py\", line 415, in present\n  File \"/tmp/ansible_bigip_device_certificate_payload_g3w_ji00/ansible_bigip_device_certificate_payload.zip/ansible_collections/f5networks/f5_modules/plugins/modules/bigip_device_certificate.py\", line 451, in expired\nTypeError: '>' not supported between instances of 'int' and 'NoneType'\n", "module_stdout": "", "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error", "rc": 1}
```
