### ISSUE TITLE
bigip_gtm_topology_region NOT idempotent when state contains space

### ISSUE THREAD

**Issue by Cesar-EF** [F5Networks/f5-ansible#2376]
##### COMPONENT NAME
bigip_gtm_topology_region

##### ANSIBLE VERSION

```
ansible [core 2.15.4]
```
##### BIGIP VERSION

```
BIG-IP Version 17.1.0.1 
```
##### CONFIGURATION

None
##### OS / ENVIRONMENT

MACOS
##### SUMMARY

space making Ansible return always `changed: true` even the resource was already created
##### STEPS TO REPRODUCE

```
- name: Create region
  bigip_gtm_topology_region: 
    name: TEST
    region_members:
      - state: US/New York
    provider: "{{ provider }}"
    state: present
  delegate_to: localhost
```

##### EXPECTED RESULTS

Result should just return `OK` since it the resource was already created
##### ACTUAL RESULTS

```
changed: [localhost] => {
    "changed": true,
    "invocation": {
        "module_args": {
            "name": "TEST",
            "partition": "Common",
            "provider": {
                "auth_provider": null,
                "no_f5_teem": true,
                "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
                "server": “ip",
                "server_port": port,
                "timeout": null,
                "transport": "rest",
                "user": “ansible-user",
                "validate_certs": false
            },
            "region_members": [
                {
                    "continent": null,
                    "country": null,
                    "datacenter": null,
                    "geo_isp": null,
                    "isp": null,
                    "negate": false,
                    "pool": null,
                    "region": null,
                    "state": "US/New York",
                    "subnet": null
                }
            ],
            "state": "present"
        }
    },
    "region_members": "state US/New York"
}
```
