### ISSUE TITLE
bigip_ucs_fetch - Traceback on UCS fetch

### ISSUE THREAD

**Issue by apellini** [F5Networks/f5-ansible#2388]
##### COMPONENT NAME

- bigip_ucs_fetch

##### ANSIBLE VERSION

```
ansible [core 2.13.6]
  config file = None
  configured module search path = ['/root/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.9/site-packages/ansible
  ansible collection location = /root/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/local/bin/ansible
  python version = 3.9.4 (default, Apr 14 2021, 10:57:48) [GCC 4.8.5 20150623 (Red Hat 4.8.5-39)]
  jinja version = 3.1.2
  libyaml = True

f5networks.f5_modules 1.25.1
```
##### BIGIP VERSION

```
15.1.5.1
16.1.4.1
16.1.3.2
```
##### OS / ENVIRONMENT
RHEL 7.9

##### SUMMARY
UCS Backup not working on some device and traceback not useful to understand the issue

##### STEPS TO REPRODUCE
```
- name: Collect UCS
      f5networks.f5_modules.bigip_ucs_fetch:
        provider: "{{ provider }}"
        async_timeout: 1800
        src: "{{ ucs_file }}"
        dest: "{{ tmp }}/{{ ucs_file }}"
      delegate_to: localhost
      register: ucs_status
      ignore_errors: true
      environment:
        http_proxy: ""
        https_proxy: ""
```

##### EXPECTED RESULTS

Backup performed
##### ACTUAL RESULTS

```
fatal: [hostname -> localhost]: FAILED! => {"changed": false, "msg": "Expecting value: line 1 column 1 (char 0)"}
```
