### ISSUE TITLE
service_down_immediate_action missing from device_info

### ISSUE THREAD

**Issue by minsis** [F5Networks/f5-ansible#2405]
##### COMPONENT NAME
device_info

##### ANSIBLE VERSION

```
ansible [core 2.15.5]
  config file = /home/<me>/.ansible.cfg
  configured module search path = ['/home/<me>/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/<me>/.miniconda/envs/ansible-latest/lib/python3.12/site-packages/ansible
  ansible collection location = /home/<me>/.ansible/collections:/usr/share/ansible/collections
  executable location = /home/<me>/.miniconda/envs/ansible-latest/bin/ansible
  python version = 3.12.1 | packaged by conda-forge | (main, Dec 23 2023, 08:03:24) [GCC 12.3.0] (/home/<me>/.miniconda/envs/ansible-latest/bin/python3.12)
  jinja version = 3.1.2
  libyaml = True
```
##### BIGIP VERSION

```
Sys::Version
Main Package
  Product     BIG-IP
  Version     12.1.2
  Build       2.0.276
  Edition     Hotfix HF2
  Date        Sat Nov 11 04:32:09 PST 2017
```
##### SUMMARY

Data gathering is missing service_down_immediate_action.

##### STEPS TO REPRODUCE

```
- name: "Export F5 Data"
  hosts: localhost
  connection: local
  gather_facts: false
  vars:
    provider:
      no_f5_teem: true
      validate_certs: false
      server: "{{ lookup('ansible.builtin.env', 'F5_SERVER') }}"
      server_port: "{{ lookup('ansible.builtin.env', 'F5_SERVER_PORT') }}"
      user: "{{ lookup('ansible.builtin.env', 'F5_USER') }}"
      password: "{{ lookup('ansible.builtin.env', 'F5_PASSWORD') }}"
  tasks:
    - name: "Geting device info from F5"
      f5networks.f5_modules.bigip_device_info:
        provider: "{{ provider }}"
        gather_subset:
          # - profiles
          # - nodes
          # - monitors
          # - irules
          # - ltm-policies
          # - ltm-pools
          - virtual-servers
      register: device_info

    - name: "Write data to json file"
      ansible.builtin.copy:
        content: "{{ device_info | to_nice_json }}"
        dest: "exported/{{ provider.server }}-vs.json"
        mode: "0644"
```

##### EXPECTED RESULTS

To have info on service_down_immediate_action 

##### ACTUAL RESULTS

Data is not provided.
