### ISSUE TITLE
Unable to delete external Data Group File List via automation

### ISSUE THREAD

**Issue by f5killer** [F5Networks/f5-ansible#2414]
I stuck in one of the automation case. It nightmare since long time. Can help to advice is there any automation way to delete Data Group File List from File Management. 

##### COMPONENT NAME

System  ››  File Management : Data Group File List

### Environment
F5 v14, v15, v16

##### ANSIBLE VERSION

```

```
##### BIGIP VERSION

```

```
##### OS / ENVIRONMENT
BIG-IP 16.1.4.1 Build 0

##### SUMMARY
Can help to advice is there any automation way to delete Data Group File List from File Management. 

We have many unused file under **System  ››  File Management : Data Group File List**,  wanted to add automate deleation via ansible or python. Please suggest best approach. for reference this is locations.

##### STEPS TO REPRODUCE

```

```

##### ACTUAL RESULTS

```

```

**Comment by pgouband** [comment]
Hi @f5killer,

Are you using bigip_data_group?
https://clouddocs.f5.com/products/orchestration/ansible/devel/modules/bigip_data_group_module.html#bigip-data-group-module-3

With state absent?

**Comment by f5killer** [comment]
It work well in internal data group but external doesn't work.. Playbook will pass but still you will find external data group here.
ls -l  /config/filestore/files_d/Common_d/data_group_d -- CLI
System ›› File Management : Data Group File List. -- GUI

is there any solutions?

**Comment by pgouband** [comment]
Hi @f5killer,

Not sure I understand your issue.
Playbook is working and datagroup object is not anymore in the configuration but the file in filestore is still there?

**Comment by f5killer** [comment]
Playbook works well with external datagroup file don't delete. Not sure if i am doing wrong

```
- name: Delete the external Data group file which is not used.
      bigip_data_group:
        provider: '{{ provider }}'
        name: ip_list_entry
        external_file_name: ip_list_entry
        type: address
      delegate_to: localhost
```

**Comment by pgouband** [comment]
Hi @f5killer,

Have you tried with 'state: absent'?

From:
https://clouddocs.f5.com/products/orchestration/ansible/devel/modules/bigip_data_group_module.html#bigip-data-group-module-3

When state is present, ensures the data group exists.
When state is absent, ensures the data group is removed.
The use of state in this module refers to the entire data group, not its members.


So it should look like:
```ansible
- name: Delete the external Data group file which is not used.
      bigip_data_group:
        provider: '{{ provider }}'
        name: ip_list_entry
        external_file_name: ip_list_entry
        type: address
        state: absent
      delegate_to: localhost
```

**Comment by f5killer** [comment]
I feel its bug. Find the below code which i am using along with -vvv

```
        - name: Delete the external Data group file which is not used.
          bigip_data_group:
            provider: '{{ provider }}'
            name: ip_list_entry
            external_file_name: ip_list_entry
            type: address
            state: absent
          delegate_to: localhost
```

ok: [x.x.x.x -> localhost] => {
    "changed": false,
    "invocation": {
        "module_args": {
            "delete_data_group_file": false,
            "description": null,
            "external_file_name": "ip_list_entry",
            "internal": false,
            "name": "ip_list_entry",
            "partition": "Common",
            "provider": {
                "auth_provider": null,
                "no_f5_teem": true,
                "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
                "server": "x.x.x.x",
                "server_port": 443,
                "timeout": null,
                "transport": "rest",
                "user": "xxxx",
                "validate_certs": false
            },
            "records": null,
            "records_src": null,
            "separator": ":=",
            "state": "absent",
            "type": "address"
        }
    }
}

Device Output:
[X:X:X:X::Active:Changes Pending] data_group_d # ls -l *ip_list_entry*
-rw-r--r--. 1 root root 3830 May  7 20:59 :Common:ip_list_entry_80553_1
[X:X:X:X::Active:Changes Pending] data_group_d #

I feel this is bug as F5 GUI file name shows **ip_list_entry** but cli file name append with prefix and postfix **:Common:**ip_list_entry**_80553_1**

Thank you
