### ISSUE TITLE
Unable to connect to BIG IP device using F5 module

### ISSUE THREAD

**Issue by corpslave69** [F5Networks/f5-ansible#2426]
Playbook: main.yml

```
---
- name: Read-only operations on F5 BIG-IP
  hosts: f5
  connection: local
  vars:
    provider:
      server: "10.177.85.144"
      user: "user"
      password: "secret"
      validate_certs: "false"

  tasks:
    - name: run show version on remote devices
      bigip_command:
        provider: "{{ provider }}"
        commands: show sys version
```

Inventory:
```
[f5]
proxy ansible_host=10.177.85.144
```

I'm unable to connect to the BIG IP device using SSH. When I run this playbook, I receive this error:

```
URLError: <urlopen error Tunnel connection failed: 500 handshakefailed>\n",
    "module_stdout": "",
    "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error",
    "rc": 1
```

Why is it trying to connect via HTTP instead of SSH when I have specified connection: local?
