### ISSUE TITLE
Ansible Core version requirements and RHEL 9

### ISSUE THREAD

**Issue by nikatbu** [F5Networks/f5-ansible#2430]
##### COMPONENT NAME

F5Networks / f5-ansible

##### ANSIBLE VERSION

```
# ansible --version
ansible [core 2.14.14]
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.9/site-packages/ansible
  ansible collection location = /usr/share/ansible/collections
  executable location = /usr/bin/ansible
  python version = 3.9.18 (main, Aug 23 2024, 00:00:00) [GCC 11.4.1 20231218 (Red Hat 11.4.1-3)] (/usr/bin/python3)
  jinja version = 3.1.2
  libyaml = True

```
##### BIGIP VERSION

```
[version TBD]
```
##### CONFIGURATION

N/A 

##### OS / ENVIRONMENT

Running Ansible from RHEL 9.4

##### SUMMARY

F5Networks / f5-ansible latest (1.31.0) requires Ansible Core 2.15.0, but RHEL 9.4 only supports up to Ansible Core 2.14.0

https://galaxy.ansible.com/ui/repo/published/f5networks/f5_modules/?version=1.31.0
https://www.redhat.com/en/blog/updates-using-ansible-core-in-rhel

##### STEPS TO REPRODUCE

Install ansible core on RHEL 9.4, then do a galaxy install of the latest:
ansible-galaxy collection install f5networks.f5_modules

Then try running the playbook (for example):

```
    - name: "Upload SSL certificate {{ ssl_certificate_file }} to {{ ssl_certificate }} on the {{ f5_host }} F5"
      f5networks.f5_modules.bigip_ssl_certificate:
        server: "{{ f5_host }}"
        user: "{{ f5_user }}"
        password: "{{ f5_password}} "
        validate_certs: "no"
        name: "{{ ssl_certificate }}"
        content: "{{ lookup('file', ssl_certificate_file) }}"
        state: present

```

##### EXPECTED RESULTS

I expected the playbook to run.
##### ACTUAL RESULTS

I received a warning saying:
[WARNING]: Collection f5networks.f5_modules does not support Ansible version 2.14.14

```

```
