### ISSUE TITLE
bigip_ucs local variable 'obj' references before assignment

### ISSUE THREAD

**Issue by donsantos** [F5Networks/f5-ansible#245]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

bigip_ucs

##### ANSIBLE VERSION

```
ansible 2.4.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, Nov  6 2016, 00:28:07) [GCC 4.8.5 20150623 (Red Hat 4.8.5-11)]
```

##### PYTHON VERSION

```

Python 2.7.5
```

##### BIGIP VERSION

```

Sys::Version
Main Package
  Product     BIG-IP
  Version     11.6.0
  Build       4.0.420
  Edition     Hotfix HF4
  Date        Mon Feb 16 02:21:25 PST 2015

Hotfix List
ID458928-5    ID469512-2  ID472607    ID475262-1  ID477524     ID494078-4
ID478493      ID471874-1  ID481073-1  ID496560-1  ID495698-3   ID477138-1
ID490841      ID466797-6  ID482034    ID493089    ID489929     ID483328-4
ID486638      ID480305-1  ID485948-5  ID478859    ID398657-8   ID486288-1
ID476763      ID455284-4  ID474231-5  ID479889-5  ID484948-1   ID482442-5
ID480623      ID478950-2  ID462258-5  ID474469    ID480264-1   ID478333
ID484379      ID447302-3  ID450033-5  ID470414-4  ID484245-1   ID478662
ID487567-4    ID473728-3  ID476126-1  ID481463    ID480350-1   ID481020-1
ID466877-6    ID472825-2  ID484635-1  ID479152-5  ID478397-1   ID481203-5
ID487553      ID483113-1  ID473509    ID472092-3  ID486001     ID491478-1
ID475770-1    ID479450    ID482046-1  ID471769-1  ID478631     ID474058-5
ID481410-3    ID496447-1  ID421901-2  ID471125    ID500640-1   ID476521-2
ID492918      ID480360-5  ID477642-5  ID478812-2  ID480047-1   ID476753

```

##### OS / ENVIRONMENT

RHEL 7.2
##### SUMMARY

bigip_ucs python script giving an error when trying to upload UCS file

##### STEPS TO REPRODUCE

```

- name: Upload UCS File
  hosts: localhost
  connection: ssh
  gather_facts: false

  tasks:
    - name: Upload UCS File
      bigip_ucs:
        server: ""
        user: "{{un}}"
        password: "{{pwd}}"
        ucs: "/root/f5dev.ucs"
        state: "present"
        validate_certs: "false"
        passphrase: "false"
      delegate_to: localhost
~

```

##### EXPECTED RESULTS

f5dev.ucs file created

##### ACTUAL RESULTS

```
fatal: [localhost -> localhost]: FAILED! => {
    "changed": false,
    "failed": true,
    "invocation": {
        "module_args": {
            "force": false,
            "include_chassis_level_config": false,
            "no_license": false,
            "no_platform_check": false,
            "partition": "Common",
            "passphrase": "false",
            "password": "",
            "reset_trust": false,
            "server": "",
            "server_port": ,
            "state": "present",
            "ucs": "/root/f5dev.ucs",
            "user": "",
            "validate_certs": false
        }
    },
    "msg": "local variable 'obj' referenced before assignment"
}

```
