### ISSUE TITLE
bigip_ucs_fetch.py incorrectly uses 'self.want.dest' instead of 'self.want.fulldest' in multiple locations

### ISSUE THREAD

**Issue by Dan0maN** [F5Networks/f5-ansible#2469]
##### COMPONENT NAME

bigip_ucs_fetch.py

##### ANSIBLE VERSION

```
ansible [core 2.16.3]
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/myuser/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible pythong module location = /home/myuser/.ansible/collections:/usr/share/ansible/collections
  executable locations = /usr/bin/ansible
  python version = 3.12.8 (main, Dec 12 2024, 05:01:27) [GCC 8.5.0 20210514 (Red Hat 8.5.0-22.0.1)] (/usr/bin/python3.12)
  jinja version = 3.1.2
  libyaml = True
```
##### BIGIP VERSION

```
Sys::Version
Main Package
  Product      BIG-IP
  Version      16.1.5.1
  Build        0.0.7
  Edition      Point Release 1
  Date         Tue Sep 10 10:14:21 PDT 2024
  FIPS Module  F5 vCMP Cryptographic Module
```
##### OS / ENVIRONMENT

N/A
##### SUMMARY

igip_ucs_fetch.py uses an incorrect variable when calling the 'download_file' function from the iControl.py module util.  The 'download_file' function is called from both V1 and V2 versions of the 'download_from_device' function.  Those two functions are being passed 'self.want.dest' instead of 'self.want.fulldest' from the 'download' function.  If the 'dest' parameter is a directory (as the [description](https://github.com/F5Networks/f5-ansible/blob/d9433a02c4a7e5151048364282da82a8817db617/ansible_collections/f5networks/f5_modules/plugins/modules/bigip_ucs_fetch.py#L38) shows it should be), the 'download_file' function attempts to open the directory for write as a binary file using the 'open' python call.  Since there is no proper variable checking around this 'open' call in the 'iControl.py' module util, it quietly returns false.  The checking around if the 'download_from_device' and 'download' functions also appear to check 'self.want.dest' instead of 'self.want.fulldest' for the file's existence.  These checks falsely succeed.

The error returned is the generic 'Failed to copy' message located inside of the 'Execute' function, after it calls the 'download' function.

##### STEPS TO REPRODUCE

```
---
- name: Download UCS from test device
  connection: local
  gather_facts: false
  hosts: all
  vars_prompt:
    - name: prompted_user
      prompt: "Enter the username: "
      private: true
    - name: prompted_pass
      prompt: "Enter the password: "
      private: true
  tasks:
    - name: Create the local working directory
      ansible.builtin.file:
        path: ~/ucs-failure
        state: directory
        mode: '0775'
      run_once: true
    - name: Download UCS
      f5networks.f5_modules.bigip_ucs_fetch:
        dest: ~/ucs-failure
        provider:
          user: "{{ prompted_user }}"
          password: "{{ prompted_pass }}"
          server: 1.2.3.4
          validate_certs: false
        src: testunit.ucs
```

##### EXPECTED RESULTS

Expected to have the UCS downloaded
##### ACTUAL RESULTS

```
(Sorry in advance for the unformatted section below.  This was typed manually from an air-gapped computer)
Enter the username: :
Enter the password: :

PLAY [Download UCS from test device] *******************************

TASK [Create local working directory] *******************************
ok: [1.2.3.4]

TASK [Download UCS] *******************************
fatal: [1.2.3.4]: FAILED! => {"changed": false, "msg": "Failed to copy: testunit.ucs to /home/myuser/ucs-failure/testunit.ucs"}
PLAY RECAP *******************************
1.2.3.4                       : ok=1 changed=0 unreachable=0 failed=1 skipped=0 rescued=0 ignored=0
```
