### ISSUE TITLE
bigip_virtual_server - When using check_mode: true, playbook will fail if virtual server is not found in all partitions and hosts

### ISSUE THREAD

**Issue by Ziggi138** [F5Networks/f5-ansible#2478]
### Is your feature request related to a problem? Please describe.
I am working on building a playbook to update the persistence on one or more LTM virtual servers across multiple LTMs that contain multiple partitions partitions. 

The playbook gathers a list of partitions from all LTMs in the inventory then checks to see if any of the virtual servers listed in a list titled __vs_list exists in any LTM/partiton using the bigip_virtual_server with check_mode set to true.

The issue I am encountering is that a virtual server is not found in a partiton, I get an error stating "You must specify both of destination, port", but if the virtual server is found, I get an "ok". Even though the virtual server is found, the playbook fails due to other partitons on the host failing. Below is the tasks that gather the partitions and checks to see if the virtual server exists and a partial output from Ansible:

## Tasks:
```
- name: Get partitions
  f5networks.f5_modules.bigip_device_info:
    gather_subset:
      - partitions
    provider: "{{ provider }}"
  check_mode: false
  register: __f5_partitions
  delegate_to: localhost

- name: Check if each virtual server exists and determine its partition
  check_mode: true
  f5networks.f5_modules.bigip_virtual_server:
    name: "{{ item.0 }}"
    partition: "{{ item.1 }}"
    provider: "{{ provider }}"
  register: vs_status_check
  delegate_to: localhost
  loop: "{{ __vs_list | product(__f5_partitions.partitions | map(attribute='name') | list) | list }}"
  loop_control:
    label: "{{ item.0 }} in partition {{ item.1 }}"
```

## Sanitized Partial Output:

TASK [vs_configuration : Check if each virtual server exists and determine its partition] ***
...
failed: [LTM-1 -> localhost] (item=virtual-server-example in partition PARTITION-2) => {"ansible_loop_var": "item", "changed": false, "item": ["virtual-server-example", "PARTITION-2"], "msg": "You must specify both of destination, port"}
failed: [LTM-2 -> localhost] (item=virtual-server-example in partition Common) => {"ansible_loop_var": "item", "changed": false, "item": ["virtual-server-example", "Common"], "msg": "You must specify both of destination, port"}
failed: [LTM-2 -> localhost] (item=virtual-server-example in partition PARTITION-1) => {"ansible_loop_var": "item", "changed": false, "item": ["virtual-server-example", "PARTITION-1"], "msg": "You must specify both of destination, port"}
ok: [LTM-2 -> localhost] => (item=virtual-server-example in partition PARTITION-2)
failed: [LTM-3 -> localhost] (item=virtual-server-example in partition Common) => {"ansible_loop_var": "item", "changed": false, "item": ["virtual-server-example", "Common"], "msg": "You must specify both of destination, port"}
...

### Describe the solution you'd like
Ideally I'd like to see that if check_mode is set to true, the destination and port is not required or does not throw a failure. Another option is to add a flag into the bigip_virtual_server component to function as a type of check mode that doesn't require the destination and port.

### Describe alternatives you've considered
As a workaround, I've added "ignore_errors: true" to the task "Check if each virtual server exists and determine its partition". This isn't ideal since if any other error occurs, then the playbook will continue to run rather than fail.

**Comment by pgouband** [comment]
Hi @Ziggi138,

Have you tried using AS3?
https://clouddocs.f5.com/products/extensions/f5-appsvcs-extension/latest/
https://clouddocs.f5.com/products/orchestration/ansible/devel/f5_bigip/modules_2_0/bigip_as3_deploy_module.html#bigip-as3-deploy-module-2

**Comment by Ziggi138** [comment]
Hi @pgouband, 

Thanks for the quick reply.

Unfortunately, this is a longstanding environment that we're not ready to convert to AS3 yet. 

I figure that the module should behave that way when in check mode since nothing is being created.

I did find that I can just set the parameter bypass_module_checks to true and that resolved my issue. The documentation has the line "If set to true, the module ignores the value op check_profiles parameter.", so I figured it only applied to the check_profiles parameter

```
- name: Check if each virtual server exists and determine its partition
  check_mode: true
  f5networks.f5_modules.bigip_virtual_server:
    name: "{{ item.0 }}"
    partition: "{{ item.1 }}"
    provider: "{{ provider }}"
    bypass_module_checks: true
  register: vs_status_check
  delegate_to: localhost
  loop: "{{ __vs_list | product(__f5_partitions.partitions | map(attribute='name') | list) | list }}"
  loop_control:
    label: "{{ item.0 }} in partition {{ item.1 }}"
```

I'll go ahead and close this issue out since it is a non-issue.
