### ISSUE TITLE
Ansible Module f5networks.f5_modules.bigip_virtual_server does not properly parse iApp managed profiles

### ISSUE THREAD

**Issue by brtucker-clgx** [F5Networks/f5-ansible#2479]
##### COMPONENT NAME
bigip_virtual_server

##### ANSIBLE VERSION
```
ansible [core 2.18.6],
    config file = /home/jenkins/agent/workspace/folder/F5/F5/ansible/ansible.cfg,
    configured module search path = ['/home/jenkins/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules'],
    ansible python module location = /opt/ansible-v2.18/lib/python3.12/site-packages/ansible,
    ansible collection location = /home/jenkins/.ansible/collections:/usr/share/ansible/collections,
    executable location = /opt/ansible-v2.18/bin/ansible,
    python version = 3.12.3 (main, Feb  4 2025, 14:48:35) [GCC 13.3.0] (/opt/ansible-v2.18/bin/python3.12),
    jinja version = 3.1.6,
    libyaml = True
```
##### BIGIP VERSION
```
Sys::Version
Main Package
  Product     BIG-IP
  Version     17.1.2.2
  Build       0.0.12
  Edition     Point Release 2
  Date        Wed Apr  2 04:30:11 PDT 2025
```
##### CONFIGURATION
```
[defaults]
deprecation_warnings = False
callback_whitelist = profile_tasks
host_key_checking = false
ANSIBLE_FORCE_COLOR = true

[callback_profile_tasks]
sort_order = none

[inventory]
enable_plugins = gcp_compute
```
##### SUMMARY
When using the `bigip_virtual_server` module, profiles created by iApps are stored in a `.app` subfolder (e.g., `/Internal/myiapp.app/myprofile`). The bigip_virtual_server's internal logic uses `os.path.basename()` on profile paths unless the `partition` key is explicitly set in the profile dictionary. If `partition` is not set, `.app` is stripped from the path, causing a 404 error from the F5 API because it looks for `/Internal/myprofile` instead of `/Internal/myiapp.app/myprofile`

**Workaround:** Always include the `partition` key in each profile dictionary. This preserves the full path and allows the module to attach the correct profiles. This workaround is not documented in the official Ansible documentation.

##### STEPS TO REPRODUCE
```
- name: "Deploy iApp service"
  bigip_iapp_service:
    name: "myiapp_internal"
    template: /Common/f5.microsoft_iis
    parameters: parameters as needed
    partition: "Internal"
    strict_updates: no
    traffic_group: /Common/traffic-group-1
    provider: "{{ provider }}"
    state: present
  delegate_to: localhost
  delegate_facts: true

- name: "Attach iApp-managed profiles"
  bigip_virtual_server:
    provider: "{{ provider }}"
    name: "myiapp.app/myiapp_vs"
    destination: "10.0.0.1"
    port: "443"
    snat: Automap
    all_profiles:
      - name: "/Internal/myiapp.app/myiapp_wan-optimized-compression"
      - name: "/Internal/myiapp.app/myiapp_http"
  delegate_to: localhost
  delegate_facts: true
```

Ansible -vvvv shows:
```
profiles: [
{
"name": "/Internal/myiapp.app/myiapp_wan-optimized-compression"
},
...
````

##### EXPECTED RESULTS
The module should attach the profiles using the full path, including the .app subfolder.

##### ACTUAL RESULTS
The module strips the .app subpath (due to internal use of os.path.basename()), resulting in a 404 error from the F5 API:
```
"01020036:3: The requested profile (/Internal/myiapp_wan-optimized-compression) was not found."
```

##### WORKAROUND
Explicitly set the partition parameter within profiles:
```
    all_profiles:
      - name: "/Internal/myiapp.app/myiapp_wan-optimized-compression"
        partition: "Internal"
      - name: "/Internal/myiapp.app/myiapp_http"
        partition: "Internal"
```
However, partition is not documented to be a valid parameter of profile. I've located this workaround from line 2062 of bigip_virtual_server:
https://github.com/F5Networks/f5-ansible/blob/9c02af56110b1cc3267eb9706f7ca1cdfb9338fc/ansible_collections/f5networks/f5_modules/plugins/modules/bigip_virtual_server.py#L2062
```
                if 'partition' not in profile:
                    if isinstance(tmp['name'], str) and len(tmp["name"].split("/")) > 1:
                        tmp["partition"] = tmp["name"].split("/")[1]
                        tmp['name'] = os.path.basename(tmp['name'])
                    else:
                        tmp['partition'] = "Common"
                tmp['fullPath'] = fq_name(tmp['partition'], tmp['name'])
```
