### ISSUE TITLE
bigip_facts not working

### ISSUE THREAD

**Issue by erjac77** [F5Networks/f5-ansible#25]
Hi,

When I try to get facts from a BIG-IP system using the f5-ansible module, I get the following error:

```
sudo ansible-playbook bigip_facts.yml

PLAY [Test bigip_facts] ********************************************************

TASK [setup] *******************************************************************
ok: [x.x.x.x]

TASK [Get all facts from BIG-IP] ***********************************************
fatal: [x.x.x.x]: FAILED! => {"changed": false, "failed": true, "msg": "received exception: object of type 'itertools.imap' has no len()\ntraceback: Traceback (most recent call last):\n  File \"/tmp/ansible_vtXdNG/ansible_module_bigip_facts.py\", line 1657, in main\n    if len(include) > 0:\nTypeError: object of type 'itertools.imap' has no len()\n"}
        to retry, use: --limit @bigip_facts.retry

PLAY RECAP *********************************************************************
x.x.x.x             : ok=1    changed=0    unreachable=0    failed=1
```

Here my playbook:

```
---
- name: Test bigip_facts
  hosts: x.x.x.x
  connection: local

  tasks:
    - name: Get all facts from BIG-IP
      bigip_facts:
        server: "x.x.x.x"
        user: "admin"
        password: "xxxxxx"
        include: "system_info"
```

Thank you.
