### ISSUE TITLE
Can't set trafficGroup in iApp service

### ISSUE THREAD

**Issue by RafalKorepta** [F5Networks/f5-ansible#263]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
bigip_iapp_service

##### ANSIBLE VERSION
```
ansible 2.4.0
  config file = 
  configured module search path = [u'/Users/korepta/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python2.7/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 2.7.13 (default, Apr  4 2017, 08:46:44) [GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.42.1)]
```

##### PYTHON VERSION
```
Python 2.7.13
```

##### BIGIP VERSION
```
Sys::Version
Main Package
  Product     BIG-IP
  Version     12.1.0
  Build       0.0.1434
  Edition     Final
  Date        Wed May 11 11:45:11 PDT 2016
```

##### SUMMARY
One use case isn't idenpotent and fail on second attempt (reconfiguration iApp).

##### STEPS TO REPRODUCE

```
- name: Create app service integration iApp service from iApp template
  bigip_iapp_service:
      name: "f5-http-url-routing-lb"
      template: "appsvcs_integration_v2.0.004"
      parameters: "{{ lookup('file', item) }}"
  with_items:
      - f5-http-url-routing-lb.parameters.json
```

f5-http-url-routing-lb.parameters.json:
https://gist.github.com/RafalKorepta/548789a21ce4c91af410526bceadf7e5

appsvcs_integration_v2.0.004 can be downloaded here:
https://github.com/F5Networks/f5-application-services-integration-iApp/releases/download/v2.0.004/appsvcs_integration_v2.0.004.tmpl

##### EXPECTED RESULTS
Idempotent task should pass.

##### ACTUAL RESULTS
```
ERROR: "01070734:3: Configuration error: The floating traffic-group:
/Common/traffic-group-1 can only be set on /Common/https-waf-lb.app if
its device-group is inherited from the root folder"
```
