### ISSUE TITLE
Module for security logging profiles for AFM

### ISSUE THREAD

**Issue by torzillo** [F5Networks/f5-ansible#270]
Customers would like an Ansible module that can be used to make a security logging profile.  There are several steps involved in creating a logging profile.  Here is an example of what the tmsh commands would look like:

~~create ltm monitor tcp-half-open SECURITYLOGSERVERS-SYSLOG { defaults-from tcp_half_open description "Monitor Status of SECURITYLOGSERVERS Syslog Daemons" destination *:514 interval 30 time-until-up 0 timeout 61 }~~ (part of `bigip_monitor_tcp_half_open`)

~~create ltm pool SECURITYLOGSERVERS-MONITOR { members add { 1.1.1.2:514  { address 1.1.1.2 } } monitor SECURITYLOGSERVERS-SYSLOG }~~ (part of `bigip_pool` and `bigip_pool_member`)

~~create sys log-config destination remote-high-speed-log SECURITYLOGSERVERS-LOGGING { pool-name SECURITYLOGSERVERS-MONITOR }~~ (part of `bigip_log_destination`)

~~create sys log-config destination remote-syslog SECURITYLOGSERVERS-LOG-FORMAT { format rfc5424 remote-high-speed-log SECURITYLOGSERVERS-LOGGING }~~ (part of `bigip_log_destination`)

~~create sys log-config publisher SECURITYLOGSERVERS-HSL-PUBLISHER { destinations replace-all-with { SECURITYLOGSERVERS-LOG-FORMAT } }~~ (part of `bigip_log_publisher`)

```
create security log profile HSL-LOGGING-PROFILE {
  ip-intelligence {
    log-publisher SECURITYLOGSERVERS-HSL-PUBLISHER
    log-translation-fields enabled
  }
  network replace-all-with {
    HSL-LOGGING-PROFILE {
      publisher SECURITYLOGSERVERS-HSL-PUBLISHER
      filter {
        log-acl-match-accept enabled
        log-acl-match-drop enabled
        log-acl-match-reject enabled
        log-ip-errors enabled
        log-tcp-errors enabled
        log-tcp-events enabled
        log-translation-fields enabled
      }
      format {
        field-list {
          date_time
          bigip_hostname
          acl_policy_name
          acl_rule_name
          src_ip
          src_port
          dest_ip
          dest_port
          protocol
          action
          drop_reason
          route_domain
          sa_translation_pool
          sa_translation_type
          translated_dest_ip
          translated_dest_port
          translated_ip_protocol
          translated_route_domain
          translated_src_ip
          translated_src_port
          translated_vlan
          vlan
          context_name
          context_type
          acl_policy_type
          dest_geo
          management_ip_address
          src_geo
        }
        field-list-delimiter " , "
        type field-list
      }
    }
  }
  protocol-dns-dos-publisher SECURITYLOGSERVERS-HSL-PUBLISHER
}
```

**Comment by neozoolook** [comment]
Recommend that this module also allow you to modify the 'security log profile global-network' as an option as well, as you may be leveraging global policy that you want to log from.

```
security log profile global-network {
    description "Default logging profile for network events"
    ip-intelligence {
        log-publisher JSA-HSL-PUBLISHER
        log-translation-fields enabled
    }
    network {
        global-network {
            filter {
                log-acl-match-accept enabled
                log-acl-match-drop enabled
                log-acl-match-reject enabled
                log-ip-errors enabled
                log-tcp-errors enabled
                log-tcp-events enabled
                log-translation-fields enabled
            }
            format {
                field-list { date_time bigip_hostname acl_policy_name acl_rule_name src_ip src_port dest_ip dest_port protocol action drop_reason route_domain sa_translation_pool sa_translation_type translated_dest_ip translated_dest_port translated_ip_protocol translated_route_domain translated_src_ip translated_src_port translated_vlan vlan context_name context_type acl_policy_type dest_geo management_ip_address src_geo }
                field-list-delimiter " , "
                type field-list
            }
            publisher JSA-HSL-PUBLISHER
        }
    }
    protocol-dns-dos-publisher JSA-HSL-PUBLISHER
}
```
How this is done today with use of bigip_command: module

```
---
- name: Check for Exsisting Global Log Profile global-network
  bigip_command:
    commands:
      - list security log profile global-network { network { global-network { publisher }}}
    server: "{{ ansible_host }}"
    user: "{{ username }}"
    password: "{{ password }}"
    validate_certs: "no"
  register: result_profile_global
  delegate_to: localhost

- name: Create HSL Log Profile {{ profile_global }}
  bigip_command:
    commands:
      - modify security log profile {{ profile_global }} { ip-intelligence { log-publisher {{ publisher }} log-translation-fields enabled } protocol-dns-dos-publisher {{ publisher }} }
      - modify security log profile {{ profile_global }} network replace-all-with { {{ profile_global }} {  publisher {{ publisher }} filter { log-acl-match-accept enabled log-acl-match-drop enabled log-acl-match-reject enabled log-ip-errors enabled log-tcp-errors enabled log-tcp-events enabled log-translation-fields enabled } format { field-list { date_time bigip_hostname acl_policy_name acl_rule_name src_ip src_port dest_ip dest_port protocol action drop_reason route_domain sa_translation_pool sa_translation_type translated_dest_ip translated_dest_port translated_ip_protocol translated_route_domain translated_src_ip translated_src_port translated_vlan vlan context_name context_type acl_policy_type dest_geo management_ip_address src_geo } field-list-delimiter ' , ' type field-list } } }
    server: "{{ ansible_host }}"
    user: "{{ username }}"
    password: "{{ password }}"
    validate_certs: "no"
  when: '"publisher none" in result_profile_global.stdout|first'
  delegate_to: localhost

```
