### ISSUE TITLE
bigip_vlan fails to create tagged interfaces as per documentation

### ISSUE THREAD

**Issue by dbeckham** [F5Networks/f5-ansible#30]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
F5 bigip (bigip_vlan)

##### ANSIBLE VERSION
```
ansible 2.2.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
```

##### PYTHON VERSION
```
Python 2.7.12
```

##### F5 BIGIP LTM VERSION
```
Sys::Version
Main Package
  Product     BIG-IP
  Version     12.1.1
  Build       0.0.184
  Edition     Final
  Date        Thu Aug 11 17:09:01 PDT 2016
```

##### CONFIGURATION
```
retry_files_enabled = False
host_key_checking=False
```

##### OS / ENVIRONMENT
Alpine 3.4 (Docker Container)

##### SUMMARY
When attempting to create or modify a VLAN to add a tagged interface, the VLAN ID/tag is assigned to the VLAN, but the interface is always added as an untagged interface.

##### STEPS TO REPRODUCE
Create a task that uses the `bigip_vlan` module that includes a `tag` and `interfaces` parameter as described in the module documentation.

```
- name: Add tagged interface to internal vlan
  bigip_vlan:
    interfaces:
      - 1.1
    name: "internal"
    password: "{{ bigip_password }}"
    server: "{{ inventory_hostname }}"
    tag: "1024"
    user: "{{ bigip_username }}"
    validate_certs: "{{ validate_certs }}"
```

##### EXPECTED RESULTS
It should properly configure the vlan with the interface's tagged property set.

Example `tmsh` configuration with properly tagged interface created from the web admin GUI:

```
(tmos)# list /net vlan internal 
net vlan internal {
    if-index 192
    interfaces {
        1.1 {
            tagged
        }
    }
    tag 50
}
```

##### ACTUAL RESULTS
The VLAN is created with the correct tag, but the interface is missing the `tagged` property.

Example `tmsh` configuration generated by `bigip_vlan`:

```
(tmos)# list /net vlan internal 
net vlan internal {
    if-index 192
    interfaces {
        1.1 { }
    }
    tag 50
}
```
