### ISSUE TITLE
bigip_vlan tagged_interface

### ISSUE THREAD

**Issue by mikeandretta** [F5Networks/f5-ansible#304]
Im looking to use tagged_interface: "Virtuals" as my tagged interface for the newly created bigip_vlan. If I already have a trunk with interface 1.1 and 1.2 inside of it and I want to use the trunked "string" value within the tagged_interface: why is this not an option? Below is my YML for this section. All works for VLAN creation but it will not tag the Network \ Trunks interface im trying to reference (Virtuals).

Thanks!

Just an FYI, I am using a physical pair, not the VE.

```
    - name: Tag Interface
      bigip_vlan:
          tagged_interface: "{{ taggedinterface }}"
          name: "{{ vlanname }}"
          password: "{{ passwordhere }}"
          server: "{{ inventory_hostname }}"
          tag: "{{ vlantag }}"
          user: "admin"
          validate_certs: "false"
      delegate_to: localhost
```
