### ISSUE TITLE
RFE: bigip_command idempotent

### ISSUE THREAD

**Issue by alonsocamaro** [F5Networks/f5-ansible#306]
##### ISSUE TYPE
 - Feature Idea

##### COMPONENT NAME
bigip_command

##### SUMMARY

Hi

Implementing the `creates` and `removes` options of the command module in bigip_command module would allow idempotent behaviour as described in http://codeheaven.io/15-things-you-should-know-about-ansible/

I hope you find this useful

Thanks

       Ulises

**Comment by delgadillo22** [comment]
From link referenced above:
Always have in mind that Ansible has a lot of modules and **most common operations do not require the use of the command module.** For instance, there are modules for creating filesystems, modifying the iptables and managing cron entries. All these modules are idempotent by default, so you always should prefer them.

**Comment by caphrim007** [comment]
@alonsocamaro what do you propose the creates and removes arguments accept for values? tmsh does not provide structures output.

**Comment by alonsocamaro** [comment]
Hi Tim

@caphrim007 the idea is that the user would provide the object name to check against:

```creates``` and ```removes``` would be an additional option and the user would provide an object that ```bigip_command``` would ```tmsh list```, the result would be filtered to check if the condition is true or false. It could be something like:

```
bigip_command:
      server: "{{ bigip }}"
      commands:
      -  modify net vlan customer-100 syn-flood-rate-limit 9999
      creates: net vlan customer-100 syn-flood-rate-limit | regex_search('(syn-flood-rate-limit 9999)')

```      

I think that doing something like this there would be a bit of feature overlap with the ```failed_when:``` statement for error handling but I find it is cleaner. 

I'm not 100% convinced this is worth but I thought the idea was worth to share.

Thanks

     Ulises
