### ISSUE TITLE
bigip_virtual_server default to performance layer 4 type

### ISSUE THREAD

**Issue by amb1s1** [F5Networks/f5-ansible#308]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

bigip_virtual_server

##### ANSIBLE VERSION

```
ansible 2.3.0.0
  config file = /Users/davidg/Documents/ansible/ansible.cfg
  configured module search path = [u'./library']
  python version = 2.7.13 (default, May 24 2017, 10:36:20) [GCC 4.2.1 Compatible Apple LLVM 8.1.0 (clang-802.0.42)]

```

##### PYTHON VERSION

```
Python 2.7.13
```

##### BIGIP VERSION

```
Sys::Version
Main Package
  Product     BIG-IP
  Version     12.1.2
  Build       0.0.249
  Edition     Final
  Date        Wed Nov 30 16:04:00 PST 2016

```

##### SUMMARY
I'm trying to create a virtual server standard type with client and server side profile, but no mater what I do it will make the VS type layer 4.

##### STEPS TO REPRODUCE

```
---
- name: create virtual servers
  connection: local 
  hosts: f5

  tasks:

    - name: Add virtual server
      bigip_virtual_server:
        server: "{{inventory_hostname}}"
        user: "admin"
        password: "admin"
        state: disabled
        name: david-test-please-delete
        destination: 192.168.10.10
        port: 80
        snat: SNATPOOL-VLAN30
        pool: SVC-GRP-DAVID-TEST-PLEASE-DELETE
        enabled_vlans: ALL
        description: Test Virtual Server
        validate_certs: "False"
        all_profiles:
            - tcp
        profiles_server_side:
            - PROFILE-TCP-SERVER
        profiles_client_side:
            - PROFILE-TCP-CLIENT
      delegate_to: localhost



```

##### EXPECTED RESULTS

 I expected the vs to be type standard. To be able to config the profiles for both server and client, the VS type needs to be standard.
```
ltm virtual david-test-please-delete {
    destination 192.168.10.10:http
    ip-protocol tcp
    mask 255.255.255.255
    pool SVC-GRP-DAVID-TEST-PLEASE-DELETE
    profiles {
        PROFILE-HTTP-BASE { }
       PROFILE-TCP-SERVER {
            context clientside
        }
        PROFILE-TCP-CLIENT {
            context serverside
        }
    }
    source 0.0.0.0/0
    source-address-translation {
        pool SNATPOOL-VLAN30
        type snat
    }
    translate-address enabled
    translate-port enabled
    vs-index 285
}
```
##### ACTUAL RESULTS

```
ltm virtual david-test-please-delete {
    destination 192.168.10.10:http
    mask 255.255.255.255
    pool SVC-GRP-DAVID-TEST-PLEASE-DELETE
    profiles {
        fastL4 { }
    }
    source 0.0.0.0/0
    source-address-translation {
        pool SNATPOOL-VLAN30
        type snat
    }
    translate-address enabled
    translate-port enabled
    vs-index 286
}
```
