### ISSUE TITLE
Private IP Checking

### ISSUE THREAD

**Issue by UdhavPawar** [F5Networks/f5-ansible#309]
##### ISSUE TYPE

 - Feature Idea

##### ANSIBLE VERSION

```
ansible 2.4.0
  config file = None
  configured module search path = [u'/home/upawar/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, Nov  6 2016, 00:28:07) [GCC 4.8.5 20150623 (Red Hat 4.8.5-11)]

```

##### PYTHON VERSION

```

```

##### BIGIP VERSION

```
Sys::Version
Main Package
  Product     BIG-IP
  Version     12.1.2
  Build       0.93.249
  Edition     Engineering Hotfix
  Date        Fri Jan 20 15:48:38 PST 2017

Hotfix List
ID624457-5    ID623119  ID639492-1  ID624023-3

```

##### STEPS TO REPRODUCE

```
- name: Checking if the entered Private Ip is being used
  hosts: privateiphost
  connection: local
  gather_facts: no
  vars_files:
     - './password.yml'

  tasks:
    - name: get self_ip
      bigip_facts:
        include: "virtual_address"
        server: "{{ inventory_hostname }}"
        user: "{{ bigip_username }}"
        password: "{{ bigip_password }}"

```

##### ACTUAL RESULTS

```

```
