### ISSUE TITLE
bigip_software fails to create a new boot location with reuse_inactive_volume and a single boot location

### ISSUE THREAD

**Issue by loudsong** [F5Networks/f5-ansible#312]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

bigip_software.py (in devel branch)

##### ANSIBLE VERSION

```
$ ansible --version
ansible 2.3.1.0 (detached HEAD 5122892cef) last updated 2017/05/31 15:48:58 (GMT -700)
  config file = /home/awalker/dev/slide/ansible.cfg
  configured module search path = [u'/home/awalker/dev/slide/git_checkouts/f5-ansible/library']
  python version = 2.7.10 (default, Oct 14 2015, 16:09:02) [GCC 5.2.1 20151010]
```

##### PYTHON VERSION

```
Python 2.7.10
```

##### BIGIP VERSION

```
# tmsh show sys version

Sys::Version
Main Package
  Product     BIG-IP
  Version     12.1.2
  Build       0.0.249
  Edition     Final
  Date        Wed Nov 30 16:04:00 PST 2016

```

##### SUMMARY

Using the `bigip_software` module from the dev branch, I tried to install software on a fresh BIG-IP VE instance. The BIG-IP began with only a single volume, HD1.1 (which was active). There was not HD1.2 nor any other volume. I had set  `reuse_inactive_volume` parameter to `yes`. The task failed while trying to generate and check for a suitable volume name.

Looking at the code, I believe I've found the cause on line: https://github.com/F5Networks/f5-ansible/blob/3cf850fe6e639ca209f605bd822685d9e4272f64/library/bigip_software.py#L614:

        if volume is None:
            if reuse:
                new_volume = self._get_next_available_volume()
                if self._volume_exists_on_device(volume):      <--- should be new_volume, not volume
                    self._values['delete_volume'] = True

It succeeds when I modify the line to pass in `new_volume` instead.

##### STEPS TO REPRODUCE

```
# Run this against a BIG-IP that only has a single boot location present

      - name: Install image - base image only
        bigip_software:
            server: "{{ ansible_host }}"
            server_port: "{{ bigip_port }}"
            user: "{{ bigip_username }}"
            password: "{{ bigip_password }}"
            validate_certs: "{{ validate_certs }}"
            version: "{{ tmos_version }}"
            build: "{{ tmos_build }}"
            software: "http://remote/{{ tmos_version }}.iso"
            software_md5sum: "http://remote/{{ tmos_version }}.iso.md5"
            remote_src: yes
            reuse_inactive_volume: yes
            state: "activated"
        register: bigip_software_install
        delegate_to: localhost


```

##### EXPECTED RESULTS

The software to be downloaded (if necessary), and installed to a new boot location that is automatically created.

##### ACTUAL RESULTS

Task failed while executing `if self._volume_exists_on_device(volume):`

```
TASK [tmos_common : Install image - base image only] ******************************************************************
task path: /home/awalker/dev/slide/roles/tmos_common/tasks/software.yml:114
fatal: [bigips_1 -> localhost]: FAILED! => {
    "changed": false, 
    "failed": true, 
    "module_stderr": "/home/awalker/dev/slide/venv/local/lib/python2.7/site-packages/urllib3/connectionpool.py:852: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings\n  InsecureRequestWarning)\n/home/awalker/dev/slide/venv/local/lib/python2.7/site-packages/urllib3/connectionpool.py:852: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings\n  InsecureRequestWarning)\n/home/awalker/dev/slide/venv/local/lib/python2.7/site-packages/urllib3/connectionpool.py:852: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings\n  InsecureRequestWarning)\n/home/awalker/dev/slide/venv/local/lib/python2.7/site-packages/urllib3/connectionpool.py:852: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings\n  InsecureRequestWarning)\n/home/awalker/dev/slide/venv/local/lib/python2.7/site-packages/urllib3/connectionpool.py:852: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings\n  InsecureRequestWarning)\nTraceback (most recent call last):\n  File \"/tmp/ansible_fkRkbz/ansible_module_bigip_software.py\", line 1407, in <module>\n    main()\n  File \"/tmp/ansible_fkRkbz/ansible_module_bigip_software.py\", line 1401, in main\n    results = mm.exec_module()\n  File \"/tmp/ansible_fkRkbz/ansible_module_bigip_software.py\", line 779, in exec_module\n    return manager.exec_module()\n  File \"/tmp/ansible_fkRkbz/ansible_module_bigip_software.py\", line 804, in exec_module\n    changed = self.activated()\n  File \"/tmp/ansible_fkRkbz/ansible_module_bigip_software.py\", line 846, in activated\n    self.install_volume()\n  File \"/tmp/ansible_fkRkbz/ansible_module_bigip_software.py\", line 900, in install_volume\n    self._set_changed_options()\n  File \"/tmp/ansible_fkRkbz/ansible_module_bigip_software.py\", line 822, in _set_changed_options\n    if getattr(self.want, key) is not None:\n  File \"/tmp/ansible_fkRkbz/ansible_module_bigip_software.py\", line 614, in volume\n    if self._volume_exists_on_device(volume):\n  File \"/tmp/ansible_fkRkbz/ansible_module_bigip_software.py\", line 717, in _volume_exists_on_device\n    result = self.client.api.tm.sys.software.volumes.volume.exists(name=volume)\n  File \"/home/awalker/dev/slide/venv/src/f5-sdk/f5/bigip/resource.py\", line 1094, in exists\n    session.get(base_uri, **kwargs)\n  File \"/home/awalker/dev/slide/venv/local/lib/python2.7/site-packages/icontrol/session.py\", line 252, in wrapper\n    **kwargs)\n  File \"/home/awalker/dev/slide/venv/local/lib/python2.7/site-packages/icontrol/session.py\", line 200, in generate_bigip_uri\n    **kwargs)\n  File \"/home/awalker/dev/slide/venv/local/lib/python2.7/site-packages/icontrol/session.py\", line 168, in _validate_uri_parts\n    _validate_name_partition_subpath(name)\n  File \"/home/awalker/dev/slide/venv/local/lib/python2.7/site-packages/icontrol/session.py\", line 129, in _validate_name_partition_subpath\n    if '~' in element:\nTypeError: argument of type 'NoneType' is not iterable\n", 
    "module_stdout": "", 
    "msg": "MODULE FAILURE", 
    "rc": 0
}

```
