### ISSUE TITLE
bigip_selfip fails with TypeError during json serialization for allow_service parameter

### ISSUE THREAD

**Issue by loudsong** [F5Networks/f5-ansible#315]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

bigip_selfip (devel branch)

##### ANSIBLE VERSION

```
ansible 2.3.1.0 (detached HEAD 5122892cef) last updated 2017/05/31 15:48:58 (GMT -700)
  config file = /home/awalker/dev/slide/ansible.cfg
  configured module search path = [u'/home/awalker/dev/slide/git_checkouts/f5-ansible/library']
  python version = 2.7.10 (default, Oct 14 2015, 16:09:02) [GCC 5.2.1 20151010]
```

##### PYTHON VERSION

```
Python 2.7.10
```

##### BIGIP VERSION

```
Sys::Version
Main Package
  Product     BIG-IP
  Version     12.1.0
  Build       0.0.1434
  Edition     Final
  Date        Wed May 11 11:45:11 PDT 2016

```

##### OS / ENVIRONMENT

Ubuntu 16.04

##### SUMMARY

Creating a self-ip using `bigip_selfip` is failing in the devel branch. It's stumbling over the parameter for `allow_service`:

`TypeError: set(['default']) is not JSON serializable`

Looking at the code, I think I found the error on line https://github.com/F5Networks/f5-ansible/blob/a6f57d271fef366bf8c026a12c8a1030800cd261/library/bigip_selfip.py#L434

        return set(result)

If I turn the set into a list, the problem goes away:

        return list(set(result))

##### STEPS TO REPRODUCE

```
- set_fact:
    self_ips:
      - address: "10.2.1.1/24"
        name: "internal_self"
        vlan: "internal"

- name: Create self-IPs
  bigip_selfip:
      password: "{{ bigip_password }}"
      server: "{{ ansible_host }}"
      server_port: "{{ bigip_port }}"
      user: "{{ bigip_username }}"
      validate_certs: "{{ validate_certs }}"
      name: "{{ item.name }}"
      address: "{{ item.address|ipaddr('address') }}"
      netmask: "{{ item.address|ipaddr('netmask') }}"
      vlan: "{{ item.vlan }}"
      route_domain: "{{ item.route_domain|default(omit) }}"
      allow_service: "default"
      state: present
  notify: tmsh save sys config
  delegate_to: localhost
  with_items: "{{ self_ips }}"

```

##### EXPECTED RESULTS

Self-ip is created without error.
##### ACTUAL RESULTS

Python excpeption thrown.

```
TASK [tmos_common : Create self-IPs] *********************************************************************************************************
task path: /home/awalker/dev/slide/roles/tmos_common/tasks/networking.yml:20
failed: [bigips_1 -> localhost] (item={u'vlan': u'internal', u'name': u'internal_self', u'address': u'10.2.1.1/24'}) => {
    "failed": true, 
    "item": {
        "address": "10.2.1.1/24", 
        "name": "internal_self", 
        "vlan": "internal"
    }, 
    "module_stderr": "/home/awalker/dev/slide/venv/local/lib/python2.7/site-packages/urllib3/connectionpool.py:852: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecureRequestWarning)
/home/awalker/dev/slide/venv/local/lib/python2.7/site-packages/urllib3/connectionpool.py:852: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecureRequestWarning)
/home/awalker/dev/slide/venv/local/lib/python2.7/site-packages/urllib3/connectionpool.py:852: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecureRequestWarning)
Traceback (most recent call last):
  File \"/tmp/ansible_Tc0zXS/ansible_module_bigip_selfip.py\", line 789, in <module>
    main()
  File \"/tmp/ansible_Tc0zXS/ansible_module_bigip_selfip.py\", line 783, in main
    results = mm.exec_module()
  File \"/tmp/ansible_Tc0zXS/ansible_module_bigip_selfip.py\", line 538, in exec_module
    changed = self.present()
  File \"/tmp/ansible_Tc0zXS/ansible_module_bigip_selfip.py\", line 553, in present
    changed = self.create()
  File \"/tmp/ansible_Tc0zXS/ansible_module_bigip_selfip.py\", line 610, in create
    self.create_on_device()
  File \"/tmp/ansible_Tc0zXS/ansible_module_bigip_selfip.py\", line 621, in create_on_device
    **params
  File \"/home/awalker/dev/slide/venv/src/f5-sdk/f5/bigip/resource.py\", line 980, in create
    return self._create(**kwargs)
  File \"/home/awalker/dev/slide/venv/src/f5-sdk/f5/bigip/resource.py\", line 947, in _create
    response = session.post(_create_uri, json=kwargs, **requests_params)
  File \"/home/awalker/dev/slide/venv/local/lib/python2.7/site-packages/icontrol/session.py\", line 258, in wrapper
    response = method(self, REST_uri, **kwargs)
  File \"/home/awalker/dev/slide/venv/local/lib/python2.7/site-packages/icontrol/session.py\", line 477, in post
    return self.session.post(uri, data=data, json=json, **kwargs)
  File \"/home/awalker/dev/slide/venv/local/lib/python2.7/site-packages/requests/sessions.py\", line 560, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File \"/home/awalker/dev/slide/venv/local/lib/python2.7/site-packages/requests/sessions.py\", line 499, in request
    prep = self.prepare_request(req)
  File \"/home/awalker/dev/slide/venv/local/lib/python2.7/site-packages/requests/sessions.py\", line 431, in prepare_request
    hooks=merge_hooks(request.hooks, self.hooks),
  File \"/home/awalker/dev/slide/venv/local/lib/python2.7/site-packages/requests/models.py\", line 306, in prepare
    self.prepare_body(data, files, json)
  File \"/home/awalker/dev/slide/venv/local/lib/python2.7/site-packages/requests/models.py\", line 456, in prepare_body
    body = complexjson.dumps(json)
  File \"/home/awalker/dev/slide/venv/local/lib/python2.7/site-packages/simplejson/__init__.py\", line 380, in dumps
    return _default_encoder.encode(obj)
  File \"/home/awalker/dev/slide/venv/local/lib/python2.7/site-packages/simplejson/encoder.py\", line 291, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File \"/home/awalker/dev/slide/venv/local/lib/python2.7/site-packages/simplejson/encoder.py\", line 373, in iterencode
    return _iterencode(o, 0)
  File \"/home/awalker/dev/slide/venv/local/lib/python2.7/site-packages/simplejson/encoder.py\", line 268, in default
    raise TypeError(repr(o) + \" is not JSON serializable\")
TypeError: set(['default']) is not JSON serializable
", 
    "module_stdout": "", 
    "msg": "MODULE FAILURE", 
    "rc": 0
}

```
