### ISSUE TITLE
Race condition in bigip_software.py when installing software to a new volume causes requests.exceptions.ConnectionError

### ISSUE THREAD

**Issue by loudsong** [F5Networks/f5-ansible#317]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

bigip_software (in devel branch)

##### ANSIBLE VERSION

```
ansible 2.3.1.0 (detached HEAD 5122892cef) last updated 2017/05/31 15:48:58 (GMT -700)
  config file = /home/awalker/dev/slide/ansible.cfg
  configured module search path = [u'/home/awalker/dev/slide/git_checkouts/f5-ansible/library']
  python version = 2.7.10 (default, Oct 14 2015, 16:09:02) [GCC 5.2.1 20151010]

```

##### PYTHON VERSION

```
Python 2.7.10

```

##### BIGIP VERSION

```
Sys::Version
Main Package
  Product     BIG-IP
  Version     12.1.2
  Build       0.0.249
  Edition     Final
  Date        Wed Nov 30 16:04:00 PST 2016

```

##### OS / ENVIRONMENT

Ubuntu 16.04

##### SUMMARY

When installing software on a BIG-IP with this module, a race condition exists between Apache's KeepAliveTimeout on the BIG-IP, and the following loop in `bigip_software.py`:

```
def wait_for_software_install_on_device(self):
    # We need to delay this slightly in case the the volume needs to be
    # created first
    for count in range(10):
        if self.volume_exists_on_device():
            break
        time.sleep(4)                   <---- Sleeps for 4 seconds between polls
```

The code pauses for 4 seconds before checking whether the volume has been created. The problem is that Apache's KeepAliveTimeout on the BIG-IP is also 4 seconds:

```
[root@localhost:Active:Standalone] config # grep -B 3 '^KeepAliveTimeout' /var/run/config/httpd.conf
# KeepAliveTimeout: Number of seconds to wait for the next request from the
# same client on the same connection.
#
KeepAliveTimeout 4
```

This leads to a race where the REST request from the client comes in while Apache is closing down the SSL session. I can reproduce this race quite frequently. I have a tcpdump showing BIG-IP sending an SSL Close Notify and a FIN and the client's GET coming in immediately after (crossing on the wire). 

When the REST client loses the race, it gets no response from the server and the connection is closed. The following error is returned: `requests.exceptions.ConnectionError: ('Connection aborted.', BadStatusLine(\"''\",))`

I adjusted the sleep timer to 3 seconds, and that seems to have resolved the problem completely for me:

        for count in range(10):
            if self.volume_exists_on_device():
                break
            # Reducing to 3. Apache's keepalive timeout on BIG-IP is set to 4
            time.sleep(3)

##### STEPS TO REPRODUCE

Install software onto a target volume that does not yet exist, so that it needs to be created.
```
      - name: Install and activate image
        bigip_software:
            server: "{{ ansible_host }}"
            server_port: "{{ bigip_port }}"
            user: "{{ bigip_username }}"
            password: "{{ bigip_password }}"
            validate_certs: "{{ validate_certs }}"
            version: "{{ tmos_version }}"
            build: "{{ tmos_build }}"
            hotfix: "http://foo/{{ tmos_version }}-hf{{ tmos_hotfix }}.iso"
            hotfix_md5sum: "http://foo/{{ tmos_version }}-hf{{ tmos_hotfix }}.iso.md5"
            software: "http://foo/{{ tmos_version }}.iso"
            software_md5sum: "http://foo/{{ tmos_version }}.iso.md5"
            remote_src: yes
            version: "{{ tmos_version }}"
            volume: "HD1.3"
            state: "installed"
        delegate_to: localhost

```

##### EXPECTED RESULTS

Module to return successfully and specified software to be installed on the newly created volume.

##### ACTUAL RESULTS

The software was properly installed on the target BIG-IP, but the module returned the following error:

```
TASK [tmos_common : Install image - base image with hotfix] **********************************************************
task path: /home/awalker/dev/slide/roles/tmos_common/tasks/software.yml:136
fatal: [bigips_1 -> localhost]: FAILED! => {
    "changed": false, 
    "failed": true, 
    "module_stderr": "
    --snip--
Traceback (most recent call last):
  File \"/tmp/ansible_17tN7t/ansible_module_bigip_software.py\", line 1407, in <module>
    main()
  File \"/tmp/ansible_17tN7t/ansible_module_bigip_software.py\", line 1401, in main
    results = mm.exec_module()
  File \"/tmp/ansible_17tN7t/ansible_module_bigip_software.py\", line 779, in exec_module
    return manager.exec_module()
  File \"/tmp/ansible_17tN7t/ansible_module_bigip_software.py\", line 804, in exec_module
    changed = self.activated()
  File \"/tmp/ansible_17tN7t/ansible_module_bigip_software.py\", line 846, in activated
    self.install_volume()
  File \"/tmp/ansible_17tN7t/ansible_module_bigip_software.py\", line 916, in install_volume
    self.wait_for_software_install_on_device()
  File \"/tmp/ansible_17tN7t/ansible_module_bigip_software.py\", line 1021, in wait_for_software_install_on_device
    if self.volume_exists_on_device():
  File \"/tmp/ansible_17tN7t/ansible_module_bigip_software.py\", line 1347, in volume_exists_on_device
    result = self.client.api.tm.sys.software.volumes.volume.exists(name=self.want.volume)
  File \"/tmp/ansible_17tN7t/ansible_module_bigip_software.py\", line 604, in volume
    if not self._volume_exists_on_device(volume):
  File \"/tmp/ansible_17tN7t/ansible_module_bigip_software.py\", line 717, in _volume_exists_on_device
    result = self.client.api.tm.sys.software.volumes.volume.exists(name=volume)
  File \"/home/awalker/dev/slide/venv/src/f5-sdk/f5/bigip/resource.py\", line 1094, in exists
    session.get(base_uri, **kwargs)
  File \"/home/awalker/dev/slide/venv/local/lib/python2.7/site-packages/icontrol/session.py\", line 258, in wrapper
    response = method(self, REST_uri, **kwargs)
  File \"/home/awalker/dev/slide/venv/local/lib/python2.7/site-packages/icontrol/session.py\", line 427, in get
    return self.session.get(uri, **kwargs)
  File \"/home/awalker/dev/slide/venv/local/lib/python2.7/site-packages/requests/sessions.py\", line 526, in get
    return self.request('GET', url, **kwargs)
  File \"/home/awalker/dev/slide/venv/local/lib/python2.7/site-packages/requests/sessions.py\", line 513, in request
    resp = self.send(prep, **send_kwargs)
  File \"/home/awalker/dev/slide/venv/local/lib/python2.7/site-packages/requests/sessions.py\", line 623, in send
    r = adapter.send(request, **kwargs)
  File \"/home/awalker/dev/slide/venv/local/lib/python2.7/site-packages/requests/adapters.py\", line 490, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', BadStatusLine(\"''\",))
", 
    "module_stdout": "", 
    "msg": "MODULE FAILURE", 
    "rc": 0
}
```
