### ISSUE TITLE
Error Creating Virtual Server in F5 Load Balancer

### ISSUE THREAD

**Issue by UdhavPawar** [F5Networks/f5-ansible#336]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

ansible_module_bigip_virtual_server

##### ANSIBLE VERSION

```
[root@0558a2589f6b work]# ansible --version
ansible 2.4.0.0
  config file = /work/ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, Aug  4 2017, 00:39:18) [GCC 4.8.5 20150623 (Red Hat 4.8.5-16)]

```

##### PYTHON VERSION

```
Python 2.7.5
```

##### BIGIP VERSION

```
Sys::Version
Main Package
  Product     BIG-IP
  Version     12.1.2
  Build       0.93.249
  Edition     Engineering Hotfix
  Date        Fri Jan 20 15:48:38 PST 2017

Hotfix List
ID639492-1    ID623119  ID624457-5  ID624023-3


```

##### SUMMARY

I am not able to create the Virtual Server 80 and 443 using the Ansible Playbook.

##### STEPS TO REPRODUCE

```
---

- name: Collect bigip_facts
  hosts: ablb
  connection: local
  vars_files:
    - '/work/prod-password-ab.yml'

  tasks:
    - name: Add virtual 80 server
      bigip_virtual_server:
          server: "{{ inventory_hostname }}"
          user: "{{ bigip_username }}"
          password: "{{ bigip_password }}"
          state: present
          partition: Common
          name: ab03web-ssl-061-YIV-023_80
          destination: 172.17.208.137
          port: 80
          pool: ab03web_app_http
          snat: Automap
          default_persistence_profile: cookie
          all_rules:
              - Akamai_Throttle_Rule_v3
          all_profiles:
              - http
              - tcp
#             - oneconnect_akamai
          enabled_vlans: ALL
      delegate_to: localhost
    - name: Add virtual 443 server
      bigip_virtual_server:
          server: "{{ inventory_hostname }}"
          user: "{{ bigip_username }}"
          password: "{{ bigip_password }}"
          state: present
          partition: Common
          name: ab03web-ssl-061-YIV-023_443
          destination: 172.17.208.137
          port: 443
          pool: ab03web_app_https
          snat: Automap
          default_persistence_profile: cookie
          all_rules:
              - Akamai_Throttle_Rule_v3
          all_profiles:
              - http
              - tcp
#             - oneconnect_akamai
              - xyz.com
          enabled_vlans: ALL
      delegate_to: localhost

```

##### EXPECTED RESULTS

Virtual server 80 and 443 to be created in the F5 load balancer

##### ACTUAL RESULTS

```
[root@0558a2589f6b work]# ansible-playbook -i /work/privateiphost /work/cases/"061-YIV-023"/"061-YIV-023"-ab-80-443.yml --vault-password-file /work/vault-prod-key.txt -vvvv
ansible-playbook 2.4.0.0
  config file = /work/ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible-playbook
  python version = 2.7.5 (default, Aug  4 2017, 00:39:18) [GCC 4.8.5 20150623 (Red Hat 4.8.5-16)]
Using /work/ansible.cfg as config file
setting up inventory plugins
Parsed /work/privateiphost inventory source with ini plugin
Loading callback plugin default of type stdout, v2.0 from /usr/lib/python2.7/site-packages/ansible/plugins/callback/__init__.pyc

PLAYBOOK: 061-YIV-023-ab-80-443.yml ********************************************
clear: <built-in method clear of dict object at 0x2fa8000>
copy: <built-in method copy of dict object at 0x2fa8000>
fromkeys: <built-in method fromkeys of type object at 0x7fb699ad3a60>
get: <built-in method get of dict object at 0x2fa8000>
has_key: <built-in method has_key of dict object at 0x2fa8000>
items: <built-in method items of dict object at 0x2fa8000>
iteritems: <built-in method iteritems of dict object at 0x2fa8000>
iterkeys: <built-in method iterkeys of dict object at 0x2fa8000>
itervalues: <built-in method itervalues of dict object at 0x2fa8000>
keys: <built-in method keys of dict object at 0x2fa8000>
pop: <built-in method pop of dict object at 0x2fa8000>
popitem: <built-in method popitem of dict object at 0x2fa8000>
setdefault: <built-in method setdefault of dict object at 0x2fa8000>
update: <built-in method update of dict object at 0x2fa8000>
values: <built-in method values of dict object at 0x2fa8000>
viewitems: <built-in method viewitems of dict object at 0x2fa8000>
viewkeys: <built-in method viewkeys of dict object at 0x2fa8000>
viewvalues: <built-in method viewvalues of dict object at 0x2fa8000>
1 plays in /work/cases/061-YIV-023/061-YIV-023-ab-80-443.yml
Trying secret FileVaultSecret(filename='/work/vault-prod-key.txt') for vault_id=default
Read vars_file '/work/prod-password-ab.yml'
Read vars_file '/work/prod-password-ab.yml'

PLAY [Collect bigip_facts] *****************************************************
Read vars_file '/work/prod-password-ab.yml'

TASK [Gathering Facts] *********************************************************
Using module file /usr/lib/python2.7/site-packages/ansible/modules/system/setup.py
<10.1.23.252> ESTABLISH LOCAL CONNECTION FOR USER: root
<10.1.23.252> EXEC /bin/sh -c 'echo ~ && sleep 0'
<10.1.23.252> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /root/.ansible/tmp/ansible-tmp-1505948163.15-110247085307122 `" && echo ansible-tmp-1505948163.15-110247085307122="` echo /root/.ansible/tmp/ansible-tmp-1505948163.15-110247085307122 `" ) && sleep 0'
<10.1.23.252> PUT /tmp/tmpExjVjp TO /root/.ansible/tmp/ansible-tmp-1505948163.15-110247085307122/setup.py
<10.1.23.252> EXEC /bin/sh -c 'chmod u+x /root/.ansible/tmp/ansible-tmp-1505948163.15-110247085307122/ /root/.ansible/tmp/ansible-tmp-1505948163.15-110247085307122/setup.py && sleep 0'
<10.1.23.252> EXEC /bin/sh -c '/usr/bin/python /root/.ansible/tmp/ansible-tmp-1505948163.15-110247085307122/setup.py; rm -rf "/root/.ansible/tmp/ansible-tmp-1505948163.15-110247085307122/" > /dev/null 2>&1 && sleep 0'
ok: [10.1.23.252]
META: ran handlers
Read vars_file '/work/prod-password-ab.yml'
Read vars_file '/work/prod-password-ab.yml'

TASK [Add virtual 80 server] ***************************************************
task path: /work/cases/061-YIV-023/061-YIV-023-ab-80-443.yml:10
Using module file /usr/lib/python2.7/site-packages/ansible/modules/network/f5/bigip_virtual_server.py
<localhost> ESTABLISH LOCAL CONNECTION FOR USER: root
<localhost> EXEC /bin/sh -c 'echo ~ && sleep 0'
<localhost> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /root/.ansible/tmp/ansible-tmp-1505948163.55-89141789338754 `" && echo ansible-tmp-1505948163.55-89141789338754="` echo /root/.ansible/tmp/ansible-tmp-1505948163.55-89141789338754 `" ) && sleep 0'
<localhost> PUT /tmp/tmpUR4ba0 TO /root/.ansible/tmp/ansible-tmp-1505948163.55-89141789338754/bigip_virtual_server.py
<localhost> EXEC /bin/sh -c 'chmod u+x /root/.ansible/tmp/ansible-tmp-1505948163.55-89141789338754/ /root/.ansible/tmp/ansible-tmp-1505948163.55-89141789338754/bigip_virtual_server.py && sleep 0'
<localhost> EXEC /bin/sh -c '/usr/bin/python /root/.ansible/tmp/ansible-tmp-1505948163.55-89141789338754/bigip_virtual_server.py; rm -rf "/root/.ansible/tmp/ansible-tmp-1505948163.55-89141789338754/" > /dev/null 2>&1 && sleep 0'
The full traceback is:
  File "/tmp/ansible_LrzvMn/ansible_module_bigip_virtual_server.py", line 786, in main
    vs_create(api, name, destination, port, pool, all_profiles)
  File "/tmp/ansible_LrzvMn/ansible_module_bigip_virtual_server.py", line 255, in vs_create
    raise Exception('Error on creating Virtual Server : %s' % e)

fatal: [10.1.23.252 -> localhost]: FAILED! => {
    "changed": false, 
    "failed": true, 
    "invocation": {
        "module_args": {
            "all_policies": null, 
            "all_profiles": [
                "http", 
                "tcp"
            ], 
            "all_rules": [
                "Akamai_Throttle_Rule_v3"
            ], 
            "default_persistence_profile": "cookie", 
            "description": null, 
            "destination": "172.17.208.137", 
            "enabled_vlans": [
                "ALL"
            ], 
            "fallback_persistence_profile": null, 
            "name": "ab03web-ssl-061-YIV-023_80", 
            "partition": "Common", 
            "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER", 
            "pool": "ab03web_app_http", 
            "port": "80", 
            "route_advertisement_state": null, 
            "server": "10.1.23.252", 
            "server_port": 443, 
            "snat": "Automap", 
            "state": "present", 
            "user": "netagent", 
            "validate_certs": true
        }
    }, 
    "msg": "received exception: Error on creating Virtual Server : Server raised fault: 'Exception caught in LocalLB::urn:iControl:LocalLB/VirtualServer::create()\nException: Common::OperationFailed\n\tprimary_error_code   : 17241203 (0x01071473)\n\tsecondary_error_code : 0\n\terror_string         : 01071473:3: Create, modify, and delete commands are not valid for (by class: virtual_server) while in the root folder.'"
}
	to retry, use: --limit @/work/cases/061-YIV-023/061-YIV-023-ab-80-443.retry

PLAY RECAP *********************************************************************
10.1.23.252                : ok=1    changed=0    unreachable=0    failed=1   

```
