### ISSUE TITLE
bigip_pool idempotency issue with monitor_type

### ISSUE THREAD

**Issue by jmcgill298** [F5Networks/f5-ansible#341]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

bigip_pool
##### ANSIBLE VERSION

```
2.4.0.0
```

##### PYTHON VERSION

```
2.7.12
```

##### BIGIP VERSION

```
12.1.1 Build 0.0.184
```

##### OS / ENVIRONMENT

NA
##### SUMMARY

The bigip_pool module is not idempotent when specifying the monitor_type parameter.

The reason for the bug is that the F5 Rest API does not return the data for "monitor_type", so the code handling the diff between "want" and "have" will always have `None` for "have": `getattr(self.have, 'monitor_type')`.

The monitor_type is not a configurable property on the F5, but a descriptive attribute of the pool based on how many members it has, and the value of `quorum`. If quorum is used, then `monitor_type=m_of_n`, if multiple monitors are used, then `monitor_type=and_list`, if one monitor is used, then `monitor_type=single`, and if no monitors are used, then `monitor_type=none`.

##### STEPS TO REPRODUCE

give `monitor_type` a value other than null

```
pool:
  state: present
  name: test_pool
  lb_method: round_robin
  monitors:
    - http
    - tcp
  monitor_type: and_list
```
```
- name: BIGIP POOL
  bigip_pool:
    user: "{{ user }}"
    password: "{{ password }}"
    server: "{{ ansible_host }}"
    validate_certs: false
    state: "{{ pool_state | default('present') }}"
    name: "{{ pool.get('name') | default(omit, true) }}"
    lb_method: "{{ pool.get('lb_method') | default(omit, true) }}"
    monitors: "{{ pool.get('monitors') | default(omit, true) }}"
    monitor_type: "{{ pool.get('monitor_type') | default(omit, true) }}"
    quorum: "{{ pool.get('quorum') | default(omit, true) }}"
    slow_ramp_time: "{{ pool.get('slow_ramp_time') | default(omit, true) }}"
    reselect_tries: "{{ pool.get('reselect_tries') | default(omit, true) }}"
    service_down_action: "{{ pool.get('service_down_action') | default(omit, true) }}"
    description: "{{ pool.get('description') | default(omit, true) }}"
```

##### EXPECTED RESULTS

I expect
```
"changed": false
```
##### ACTUAL RESULTS

```
"changed": true
```
