### ISSUE TITLE
[RFE] bigip_iapp_template flag to allow ignore delete failure if used by iApp instances

### ISSUE THREAD

**Issue by alonsocamaro** [F5Networks/f5-ansible#354]
##### ISSUE TYPE
 - Feature Idea

##### COMPONENT NAME

http://docs.ansible.com/ansible/2.4/bigip_iapp_template_module.html

##### SUMMARY

When deleting a template it might happen that there are instances still using it.

This is likely going to happen when a playbook which contains the whole sequence for a service:

`iapp template deploy -> iapp instantiation -> iapp instance destroy -> iapp template undeploy`

and there have been several instances of the iApp instantiated.

When this is the case it is needed to create the following sequence

```
- name: "Undeploy the iApp template customer-service"
  delegate_to: localhost
  bigip_iapp_template:
    content: "{{ lookup('template', 'customer-service.tmpl') }}"
    force: true
    server: "{{ bigip }}"
    user: "{{ bigip_user }}"
    password: "{{ bigip_password }}"
    state: "absent"
  register: delete_iapp_template
  ignore_errors: True
  tags:
    - del

- name: "Check if template deletion didn't succeed because it is used by other instances of the same template"
  fail: msg="Failed when deleting the template customer-service"
  tags:
    - del
```

which makes the playbooks longer and less user-friendly.

**I would propose to add a flag which allows to ignore the case where the template could not be undeployed because there is still an iApp instance using it.**

**Comment by caphrim007** [comment]
@alonsocamaro will a custom "failed_when" not work in this case?

**Comment by alonsocamaro** [comment]
Thanks Tim

Completely right, I was unaware of it.

Maybe we could mention it in the bigip_iapp_template documentation to help customers in this common scenario?

**Comment by caphrim007** [comment]
@alonsocamaro try this

```
- name: Try to remove the iApp template before the service
  bigip_iapp_template:
      name: "web_frontends"
      state: "absent"
  register: result
  failed_when:
    - not result|success
    - "'referenced by one or more applications' not in result.msg"
```
