### ISSUE TITLE
bigip_pool monitor issue

### ISSUE THREAD

**Issue by js-f5** [F5Networks/f5-ansible#376]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

bigip_pool.py

##### ANSIBLE VERSION

```
ansible 2.4.0.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, Aug  4 2017, 00:39:18) [GCC 4.8.5 20150623 (Red Hat 4.8.5-16)]

```

##### PYTHON VERSION

```
Python 2.7.5
```

##### BIGIP VERSION

```
Sys::Version
Main Package
  Product     BIG-IP
  Version     12.1.2
  Build       1.0.271
  Edition     Hotfix HF1
  Date        Fri Apr 28 20:02:07 PDT 2017
```

##### SUMMARY
Error thrown when "monitor_type:" not set even though it is marked as "not required"
##### STEPS TO REPRODUCE

```
hosts: bigip
  connection: local
  gather_facts: false
  vars:
    bigip_user: <scrubbed>
    bigip_password: <scrubbed>
  tasks:
      - name: Creating Pool
        bigip_pool:
            lb_method: "round_robin"
            server: "{{ inventory_hostname }}"
            user: "{{ bigip_user }}"
            password: "{{ bigip_password }}"
            name: "pool01"
            validate_certs: "no"
            monitors: ['/Common/http'] 

-------------------------------------
            monitors: 
                 - /Common/http            
 or 
            monitors:
                  - http

produce the same error.
------------------------------------- 
```

##### EXPECTED RESULTS

Pool should be created without the use of "monitor_type". 
When "monitor_type" is set to "and_list", issue does not occur. 

##### ACTUAL RESULTS

```
The full traceback is:
  File "/tmp/ansible_7EqEWH/ansible_module_bigip_pool.py", line 731, in main
    results = mm.exec_module()
  File "/tmp/ansible_7EqEWH/ansible_module_bigip_pool.py", line 450, in exec_module
    changed = self.present()
  File "/tmp/ansible_7EqEWH/ansible_module_bigip_pool.py", line 512, in present
    return self.create()
  File "/tmp/ansible_7EqEWH/ansible_module_bigip_pool.py", line 546, in create
    self._set_changed_options()
  File "/tmp/ansible_7EqEWH/ansible_module_bigip_pool.py", line 477, in _set_changed_options
    if getattr(self.want, key) is not None:
  File "/tmp/ansible_7EqEWH/ansible_module_bigip_pool.py", line 323, in monitors
    raise F5ModuleError(error1)

fatal: [<scrubbed>]: FAILED! => {
    "changed": false, 
    "failed": true, 
    "invocation": {
        "module_args": {
            "description": null, 
            "host": null, 
            "lb_method": "round_robin", 
            "monitor_type": null, 
            "monitors": [
                "/Common/http"
            ], 
            "name": "pool01", 
            "partition": "Common", 
            "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER", 
            "port": null, 
            "quorum": null, 
            "reselect_tries": null, 
            "server": "<scrubbed>", 
            "server_port": 443, 
            "service_down_action": null, 
            "slow_ramp_time": null, 
            "state": "present", 
            "user": "<scrubbed>", 
            "validate_certs": false
        }
    }, 
    "msg": "The 'monitor_type' parameter cannot be empty when 'monitors' parameter is specified."
}
```
