### ISSUE TITLE
bigip_virtual_server should check assignment of pool parameter

### ISSUE THREAD

**Issue by d2-d2** [F5Networks/f5-ansible#38]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
bigip_virtual_server.py, line: 594

##### ANSIBLE VERSION
```
# ansible --version
ansible 2.3.0 (devel 0a86ddc251) last updated 2016/10/05 11:22:39 (GMT +200)
```

##### PYTHON VERSION
```
# python -V
Python 2.7.6
```

##### BIGIP VERSION
```
Sys::Version
Main Package
  Product     BIG-IP
  Version     11.6.0
  Build       6.0.442
  Edition     Hotfix HF6
  Date        Tue Oct 27 16:12:46 PDT 2015
```

##### CONFIGURATION
standard, no changes

##### OS / ENVIRONMENT
Ubuntu 14.04 LTS

##### SUMMARY
When creating virtual server from role which contains loop, you don't need pool to be assigned every time

##### STEPS TO REPRODUCE
```
- name: create virtual servers
  tags: f5_create_vservers
  bigip_virtual_server:
    validate_certs: False
    server: "ip"
    user: "user"
    password: "pass"
    partition: "partition"
    state: present
    name: "{{ item.lname }}"
    destination: "{{ item.lip }}"
    port: "{{ item.lport }}"
    pool: "{{ item.lpool }}"
    snat: Automap
  delegate_to: localhost
  with_items:
    - { lname: 'VS_HTTP1', lpool: , lip: '1.2.3.4', lport: '80'}
    - { lname: 'VS_HTTP2', lpool: 'test_pool', lip: '1.2.3.5', lport: '80'}
```
##### EXPECTED RESULTS
I expect to see both VS created within the same role, one with default pool assignment, another without default pool assigment.

##### ACTUAL RESULTS
```
failed: [localhost -> localhost] (item={u'lname': u'VS_HTTP1', u'lport': u'80', u'lpool': None, u'lip': u'1.2.3.4'}) => {
    "failed": true,
    "invocation": {
        "module_args": {
            "all_profiles": [
                "http",
                "clientssl"
            ],
            "all_rules": null,
            "default_persistence_profile": null,
            "description": null,
            "destination": "1.2.3.4",
            "enabled_vlans": null,
            "name": "VS_HTTP1",
            "partition": "partition",
            "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "pool": "",
            "port": 80,
            "route_advertisement_state": "disabled",
            "server": "f5_ip",
            "server_port": 443,
            "snat": "Automap",
            "state": "present",
            "user": "admin",
            "validate_certs": false
        },
        "module_name": "bigip_virtual_server"
    },
    "item": {
        "lip": "1.2.3.4",
        "lname": "VS_HTTP1",
        "lpool": null,
        "lport": "80"
    },
    "msg": "received exception: Error on creating Virtual Server : Server raised fault: 'Exception caught in LocalLB::urn:iControl:LocalLB/VirtualServer::create()\nException: Common::OperationFailed\n\tprimary_error_code   : 16908342 (0x01020036)\n\tsecondary_error_code : 0\n\terror_string         : 01020036:3: The requested pool (/partition) was not found.'"
}
```

##### POSSIBLE FIX
Replace line 594 in bigip_virtual_server.py with following:
```
    if module.params['pool'] is not '':
        pool = fq_name(partition, module.params['pool'])
    else:
        pool = ''
```
And this works just fine.
