### ISSUE TITLE
bigip_virtual_server can not assign policies

### ISSUE THREAD

**Issue by d2-d2** [F5Networks/f5-ansible#39]
##### ISSUE TYPE
- Feature request
##### COMPONENT NAME

bigip_virtual_server.py
##### ANSIBLE VERSION

```
# ansible --version
ansible 2.3.0 (devel 0a86ddc251) last updated 2016/10/05 11:22:39 (GMT +200)
```
##### PYTHON VERSION

```
# python -V
Python 2.7.6
```
##### BIGIP VERSION

```
Sys::Version
Main Package
  Product     BIG-IP
  Version     11.6.0
  Build       6.0.442
  Edition     Hotfix HF6
  Date        Tue Oct 27 16:12:46 PDT 2015
```
##### CONFIGURATION

standard, no changes
##### OS / ENVIRONMENT

Ubuntu 14.04 LTS
##### SUMMARY

When creating virtual server with this module, it's not possible to assign any policies.
##### EXPECTED RESULTS

Would be nice to have 'all_policies' parameter for that. Use case: assign http-to-https redirection (yes, I know it can be done with iRule, but since policies exists in F5 BIGIP it feels better to use them instead of iRules).

**Comment by caphrim007** [comment]
@d2-d2 are you referring to policies ala `Local Traffic -> Policies -> Policy List`?

**Comment by d2-d2** [comment]
@caphrim007 yes, exactly. Local Traffic -> Policies -> Policy List is what I meant. To workaround that 'issue' I've created another task that executes bigip_command and tmsh to assign missing policy.

**Comment by caphrim007** [comment]
ok, I can add that.

Are you just specifying the name in the command? Can you provide an example tmsh command here that you're using?

**Comment by d2-d2** [comment]
Sure, here is my task which include exact command:

```
- name: assign policy to http vserver
  tags: f5_assign_policy
  bigip_command:
    validate_certs: False
    server: "{{ f5_host }}"
    user: "{{ f5_user }}"
    password: "{{ f5_pass }}"
    command: 'tmsh modify ltm virtual /partition/vserver_name policies add { policy_to_assign }'
  delegate_to: localhost

```
