### ISSUE TITLE
dots in ssl cert names cause bigip_ssl_certificate to not create certs correctly

### ISSUE THREAD

**Issue by caphrim007** [F5Networks/f5-ansible#399]
certs and files are created and put on the box, but not in a way that TMUI will be able to find them.

**Comment by caphrim007** [comment]
this is not a bug in the ansible modules, but rather a bug in TMUI. TMUI creates everything with a ".crt" suffix. You dont need to include such a suffix when you use tmsh. So you can get yourself in this same situation if you were to do it in tmsh.

The ansible modules have, in certain situations, followed TMUI's behavior and in other situations followed tmsh's behavior. Because you can specify these cert names in a variety of other locations within an ansible playbook, this is why we do not append the ".crt" string to your cert names; because we would need to do it in all other modules too.

So this is expected behavior right now.

**Comment by caphrim007** [comment]
I think this is being caused by the shlex code that is splitting the username extension

**Comment by caphrim007** [comment]
(import_certificate.yml)
```
---
- name: Import PEM Certificate from local disk
  bigip_ssl_certificate:
      user: "{{ username }}"
      password: "{{ password }}"
      server: "{{ inventory_hostname }}"
      name: "wildcard-tatanka-local"
      cert_content: "{{ lookup('file', 'wildcard-tatanka-local.crt') }}"
      key_content: "{{ lookup('file', 'wildcard-tatanka-local.key') }}"
      validate_certs: "no"
      state: "present"
  delegate_to: localhost
...
```
 
Use-Case: Importing wildcard SSL certificates
 
The yml from above (delimiting fqdn names by dash) works perfect but there are some conventions to follow
and I found out to be restricted with ansible instead of using BIG-IP GUI.

Use-Case1 (using dots):
 
```
      name: "wildcard.tatanka.local"
      cert_content: "{{ lookup('file', 'wildcard.tatanka.local.crt') }}"
      key_content: "{{ lookup('file', 'wildcard.tatanka.local.key') }}"
```

Use-Case2 (using asterisks with dots):

``` 
      name: "*.tatanka.local"
      cert_content: "{{ lookup('file', *.tatanka.local.crt') }}"
      key_content: "{{ lookup('file', *.tatanka.local.key') }}"
```

Both use-cases are deployed by ansible with no errors but after that
you can see in the GUI just the names under SSL certifiate store
but if you click on the CRT you would not get the certificate details
as usual and if you click on the key you will get an error.
So, importing certificates with (dot’s) in names as naming convention
does not work via ansible but via BIG-IP GUI.
