### ISSUE TITLE
[feature] bigip_monitor_external.py

### ISSUE THREAD

**Issue by d2-d2** [F5Networks/f5-ansible#40]
##### ISSUE TYPE
- Feature request
##### COMPONENT NAME

bigip_monitor_external.py
##### ANSIBLE VERSION

```
# ansible --version
ansible 2.3.0 (devel 0a86ddc251) last updated 2016/10/05 11:22:39 (GMT +200)
```
##### PYTHON VERSION

```
# python -V
Python 2.7.6
```
##### BIGIP VERSION

```
Sys::Version
Main Package
  Product     BIG-IP
  Version     11.6.0
  Build       6.0.442
  Edition     Hotfix HF6
  Date        Tue Oct 27 16:12:46 PDT 2015
```
##### CONFIGURATION

standard, no changes
##### OS / ENVIRONMENT

Ubuntu 14.04 LTS
##### SUMMARY

This is a feature request. Please provide method for creating external type of monitors (Local Traffic->Monitors->Create->Type:External).
##### EXPECTED RESULTS

Most of such monitors are created after uploading some files to F5. This is an interesting part as my ansible roles fails to do that due to missing simplejson packages on F5 side and I really don't want to mess with it and installing it there. Thought about using API calls compatible with v11.6.x (do you know curl command that could achieve that?).

Next, uploaded file can be chosen from 'External Program'. This can be shell script or something else. With that ready, user should be able to supply:
- name (required)
- type of monitor (external by default)
- parent monitor
- interval
- timeout
- external program
- arguments
- variables:
  - name
  - value

**Comment by d2-d2** [comment]
More information. This is how I do it right now by chaining some ansible roles. This is simple scp and bigip_command usage:

```
- name: include credentials
  include_vars: "{{ local_home }}/.ansible-credentials.yml"
  vars:
    local_home: "{{ lookup('env','HOME') }}"
  tags: include_credentials
  delegate_to: localhost

- name: put all files from scripts under remote tmp location for further use
  shell: 'scp ../../roles/f5_create_monitors_external/scripts/{{ item.lsource }} {{ f5_user }}@{{ f5_host }}:{{ item.ldestination }}'
  tags: f5_send_files
  delegate_to: localhost
  with_items:
    - { lsource: 'f5_check_service.sh', ldestination: '/tmp/' }

- name: create external monitor program file list
  tags: f5_create_file_list
  bigip_command:
    validate_certs: False
    server: "{{ f5_host }}"
    user: "{{ f5_user }}"
    password: "{{ f5_pass }}"
    command: 'tmsh create /sys file external-monitor /PARTITION_{{ ENV | upper }}/{{ item.lsource }} source-path file:/tmp/{{ item.lsource }}'
  delegate_to: localhost
  with_items:
    - { lsource: 'f5_check_service.sh' }

- name: create monitor (external type)
  tags: f5_create_monitor
  bigip_command:
    validate_certs: False
    server: "{{ f5_host }}"
    user: "{{ f5_user }}"
    password: "{{ f5_pass }}"
    command: 'tmsh create ltm monitor external /PARTITION_{{ ENV | upper }}/{{ item.lname }} defaults-from external run /PARTITION_{{ ENV | upper }}/{{ item.lfile }} interval {{ item.linterval }} timeout {{ item.ltimeout }} user-defined {{ item.lud1 }} user-defined {{ item.lud2 }}'
  delegate_to: localhost
  with_items:
    - { lname: 'TL_check_service', lfile: 'f5_check_service.sh', linterval: '5', ltimeout: '15', lud1: 'SOAPRESPONSE f5_health_check', lud2: 'URI /my-service/ws/maintenance?wsdl' }
```

I've also found another way of uploading files and described this [here](https://devcentral.f5.com/questions/upload-bash-script-to-f5-via-api-49442). SOme highlights:

- shell script, where important part is to pass properly set Content-Range header:
```
#!/bin/bash
filename=aaa.sh
filesize=$(wc -c < $filename)
creds='user:pass'
f5_host=1.2.3.4
curl -k -u "$creds" --silent --request POST --header "Content-Type: text/plain" --header "Content-Range: 0-$[filesize-1]/$filesize" --data "@$filename" https://$f5_host/mgmt/shared/file-transfer/uploads/$filename | python -mjson.tool
```

- python code:
```
def _upload(host, creds, fp):

    chunk_size = 512 * 1024
    headers = {
        'Content-Type': 'application/octet-stream'
    }
    fileobj = open(fp, 'rb')
    filename = os.path.basename(fp)
    if os.path.splitext(filename)[-1] == '.iso':
        uri = 'https://%s/mgmt/cm/autodeploy/software-image-uploads/%s' % (host, filename)
    else:
        uri = 'https://%s/mgmt/shared/file-transfer/uploads/%s' % (host, filename)
        
    requests.packages.urllib3.disable_warnings()
    size = os.path.getsize(fp)

    start = 0

    while True:
        file_slice = fileobj.read(chunk_size)
        if not file_slice:
            break

        current_bytes = len(file_slice)
        if current_bytes < chunk_size:
            end = size
        else:
            end = start + current_bytes

        content_range = "%s-%s/%s" % (start, end - 1, size)
        headers['Content-Range'] = content_range
        requests.post(uri,
                      auth=creds,
                      data=file_slice,
                      headers=headers,
                      verify=False)

        start += current_bytes

if __name__ == "__main__":
    import os, requests, argparse, getpass

    parser = argparse.ArgumentParser(description='Upload File to BIG-IP')

    parser.add_argument("host", help='BIG-IP IP or Hostname', )
    parser.add_argument("username", help='BIG-IP Username')
    parser.add_argument("filepath", help='Source Filename with Absolute Path')
    args = vars(parser.parse_args())

    hostname = args['host']
    username = args['username']
    filepath = args['filepath']

    print "%s, enter your password: " % args['username'],
    password = getpass.getpass()

    _upload(hostname, (username, password), filepath)
```
