### ISSUE TITLE
bigip_virtual_server cannot assign an SNAT pool

### ISSUE THREAD

**Issue by awalshsyd** [F5Networks/f5-ansible#41]
##### ISSUE TYPE

 - Feature Idea

##### COMPONENT NAME

bigip_virtual_server

##### ANSIBLE VERSION

```
Ansible 2.2.0
```

##### PYTHON VERSION

```
Python 2.7.6
```

##### BIGIP VERSION

```
Sys::Version
Main Package
  Product     BIG-IP
  Version     12.1.1
  Build       1.0.196
  Edition     Hotfix HF1
  Date        Wed Sep  7 17:48:09 PDT 2016

```

##### OS / ENVIRONMENT

N/A

##### SUMMARY

New feature request to be able to configure SNAT pool with the bigip_virtual_server modules. Not expecting to be able to produce the SNAT pool just to reference it.

##### STEPS TO REPRODUCE

Expected to be used as follows

```
- name: Add virtual server with SNAT Pool
  bigip_virtual_server:
      <extra non relevant config removed>
      snat: Pool
      snatpool: MySNATPool

```

##### EXPECTED RESULTS

A virtual server to be created using an snatpool MySNATPool like the following tmsh
create ltm virtual MyVirtualServer source-address-translation { pool MySNATPool type snat }

##### ACTUAL RESULTS

```

```
