### ISSUE TITLE
bigip_device_connectivity not idempotent if unicast-ip is specified

### ISSUE THREAD

**Issue by JoeReifel** [F5Networks/f5-ansible#412]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME

bigip_device_connectivity

##### ANSIBLE VERSION

```
ansible 2.4.1.0
  config file = /Users/reifel/.ansible.cfg
  configured module search path = [u'/Users/reifel/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/ansible
  executable location = /Library/Frameworks/Python.framework/Versions/2.7/bin/ansible
  python version = 2.7.11 (v2.7.11:6d1b6a68f775, Dec  5 2015, 12:54:16) [GCC 4.2.1 (Apple Inc. build 5666) (dot 3)]
```

##### PYTHON VERSION

```
Python 2.7.11
```

##### BIGIP VERSION

```
Behavior varies, but this applies to 12.x and 13.x
```

##### OS / ENVIRONMENT

N/A

##### SUMMARY

While configuring your failover settings via bigip_device_connectivity, and you're specifying the unicast_failover settings, if you specify the IP address that corresponds to the management IP of the device, BIG-IP won't store the actual IP address, it calls it "management-ip" instead, this is in bigip_base.conf:

```
    unicast-address {
        {
            effective-ip management-ip
            effective-port 1026
            ip management-ip
        }
        {
            effective-ip 10.1.20.241
            effective-port 1026
            ip 10.1.20.241
        }

```
This text is returned back and causes an error in bigip_device_connectivity.

##### STEPS TO REPRODUCE

```
- name: Update device connectivity settings
  bigip_device_connectivity:
    config_sync_ip: "10.1.20.241"
    unicast_failover:
      - address: "10.1.1.245"  <== this happens to be the mgmt IP of the device
      - address: "10.1.20.241"
    mirror_primary_address: "10.1.30.241"
  delegate_to: localhost

```
1. If you run that task on a BIG-IP that doesn't have the cm device settings configured, the task will work.
2. on subsequent attempts the command will fail on invalid IP address.

##### ACTUAL RESULTS

```

```
