### ISSUE TITLE
bigip_selfip run results in MODULE FAILURE.

### ISSUE THREAD

**Issue by neozoolook** [F5Networks/f5-ansible#420]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

bigip_selfip

##### ANSIBLE VERSION

```
ansible 2.4.0.0
  config file = /home/pp2854/dev-vepdg-ansible/ansible-vepdg_fw/ansible.cfg
  configured module search path = [u'/home/pp2854/dev-vepdg-ansible/ansible-vepdg_fw/library']
  ansible python module location = /usr/local/lib/python2.7/dist-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 2.7.12 (default, Nov 19 2016, 06:48:10) [GCC 5.4.0 20160609]
```

##### PYTHON VERSION

```
2.7.12
```

##### BIGIP VERSION

```
Sys::Version
Main Package
  Product     BIG-IP
  Version     12.1.2
  Build       0.0.249
  Edition     Final
  Date        Wed Nov 30 16:04:00 PST 2016
```

##### OS / ENVIRONMENT

Ubuntu 16.04TS

##### SUMMARY

Appears that something has been broken in bigip_selfip, getting module error on outputs when running playbooks using this module.

##### STEPS TO REPRODUCE

```
---
- name: Create Self IPV4 Trusted Address
  bigip_selfip:
    address: "{{ trusted_network_V4[inventory_hostname] }}"
    name: "{{ trusted_vlan }}-V4"
    netmask: "{{ trusted_mask_V4 }}"
    vlan: "{{ trusted_vlan }}"
    allow_service: "none"
    server: "{{ ansible_host }}"
    user: "{{ username }}"
    password: "{{ password }}"
    validate_certs: "no"
    state: "present"
  delegate_to: localhost

- name: Create Self IPV6 Trusted Address
  bigip_selfip:
    address: "{{ trusted_network_V6[inventory_hostname] }}"
    name: "{{ trusted_vlan }}-V6"
    netmask: "{{ trusted_mask_V6 }}"
    vlan: "{{ trusted_vlan }}"
    server: "{{ ansible_host }}"
    user: "{{ username }}"
    password: "{{ password }}"
    validate_certs: "no"
    state: "present"
  delegate_to: localhost

- name: Create Self IPV4 Untrusted Address
  bigip_selfip:
    address: "{{ untrusted_network_V4[inventory_hostname] }}"
    name: "{{ untrusted_vlan }}-V4"
    netmask: "{{ untrusted_mask_V4 }}"
    vlan: "{{ untrusted_vlan }}"
    allow_service: "none"
    server: "{{ ansible_host }}"
    user: "{{ username }}"
    password: "{{ password }}"
    validate_certs: "no"
    state: "present"
  delegate_to: localhost

- name: Create Self IPV6 Untrusted Address
  bigip_selfip:
    address: "{{ untrusted_network_V6[inventory_hostname] }}"
    name: "{{ untrusted_vlan }}-V6"
    netmask: "{{ untrusted_mask_V6 }}"
    vlan: "{{ untrusted_vlan }}"
    server: "{{ ansible_host }}"
    user: "{{ username }}"
    password: "{{ password }}"
    validate_certs: "no"
    state: "present"
  delegate_to: localhost

- name: Create Self IPV4 Hsl Address
  bigip_selfip:
    address: "{{ hsl_network_V4[inventory_hostname] }}"
    name: "{{ hsl_vlan }}-V4"
    netmask: "{{ hsl_mask_V4 }}"
    vlan: "{{ hsl_vlan }}"
    allow_service: "none"
    server: "{{ ansible_host }}"
    user: "{{ username }}"
    password: "{{ password }}"
    validate_certs: "no"
    state: "present"
  delegate_to: localhost
```

##### EXPECTED RESULTS

This worked about a month ago, looks like some bugs were fixed in this module, but something got broken.

##### ACTUAL RESULTS

```

pp2854@dark-kyber:~/dev-vepdg-ansible/ansible-vepdg_fw$ sudo ansible-playbook base.yml --ask-vault-pass --tags interface -vvvv
ansible-playbook 2.4.0.0
  config file = /home/pp2854/dev-vepdg-ansible/ansible-vepdg_fw/ansible.cfg
  configured module search path = [u'/home/pp2854/dev-vepdg-ansible/ansible-vepdg_fw/library']
  ansible python module location = /usr/local/lib/python2.7/dist-packages/ansible
  executable location = /usr/local/bin/ansible-playbook
  python version = 2.7.12 (default, Nov 19 2016, 06:48:10) [GCC 5.4.0 20160609]
Using /home/pp2854/dev-vepdg-ansible/ansible-vepdg_fw/ansible.cfg as config file
Vault password: 
setting up inventory plugins
Parsed /home/pp2854/dev-vepdg-ansible/ansible-vepdg_fw/hosts inventory source with ini plugin
Loading callback plugin default of type stdout, v2.0 from /usr/local/lib/python2.7/dist-packages/ansible/plugins/callback/__init__.pyc

PLAYBOOK: base.yml *********************************************************************************************************************************************************************************************************************************************
1 plays in base.yml

PLAY [single] **************************************************************************************************************************************************************************************************************************************************
META: ran handlers
Trying secret <ansible.parsing.vault.PromptVaultSecret object at 0x7f96a1f58410> for vault_id=default

TASK [f5base : include_tasks] **********************************************************************************************************************************************************************************************************************************
task path: /home/pp2854/dev-vepdg-ansible/ansible-vepdg_fw/roles/f5base/tasks/main.yml:30
included: /home/pp2854/dev-vepdg-ansible/ansible-vepdg_fw/roles/f5base/tasks/bigip_interface/f5_interface.yml for zrdm5afpdg01pdgZZZ

TASK [f5base : Create Self IPV4 Trusted Address] ***************************************************************************************************************************************************************************************************************
task path: /home/pp2854/dev-vepdg-ansible/ansible-vepdg_fw/roles/f5base/tasks/bigip_interface/f5_interface.yml:2
Using module file /home/pp2854/dev-vepdg-ansible/ansible-vepdg_fw/library/bigip_selfip.py
<localhost> ESTABLISH LOCAL CONNECTION FOR USER: root
<localhost> EXEC /bin/sh -c 'echo ~ && sleep 0'
<localhost> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /home/pp2854/.ansible/tmp/ansible-tmp-1509676317.4-242877786188258 `" && echo ansible-tmp-1509676317.4-242877786188258="` echo /home/pp2854/.ansible/tmp/ansible-tmp-1509676317.4-242877786188258 `" ) && sleep 0'
<localhost> PUT /tmp/tmpoaZlnK TO /home/pp2854/.ansible/tmp/ansible-tmp-1509676317.4-242877786188258/bigip_selfip.py
<localhost> EXEC /bin/sh -c 'chmod u+x /home/pp2854/.ansible/tmp/ansible-tmp-1509676317.4-242877786188258/ /home/pp2854/.ansible/tmp/ansible-tmp-1509676317.4-242877786188258/bigip_selfip.py && sleep 0'
<localhost> EXEC /bin/sh -c '/usr/bin/python /home/pp2854/.ansible/tmp/ansible-tmp-1509676317.4-242877786188258/bigip_selfip.py; rm -rf "/home/pp2854/.ansible/tmp/ansible-tmp-1509676317.4-242877786188258/" > /dev/null 2>&1 && sleep 0'
fatal: [zrdm5afpdg01pdgZZZ -> localhost]: FAILED! => {
    "changed": false, 
    "failed": true, 
    "module_stderr": "/usr/local/lib/python2.7/dist-packages/urllib3/connectionpool.py:858: 
InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification
 is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-
warnings\n  InsecureRequestWarning)\n/usr/local/lib/python2.7/dist-
packages/urllib3/connectionpool.py:858: InsecureRequestWarning: Unverified HTTPS request is 
being made. Adding certificate verification is strongly advised. See: 
https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings\n  
InsecureRequestWarning)\n/usr/local/lib/python2.7/dist-packages/urllib3/connectionpool.py:858: 
InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification 
is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-
warnings\n  InsecureRequestWarning)\nTraceback (most recent call last):\n  File 
\"/tmp/ansible_IvbWeW/ansible_module_bigip_selfip.py\", line 783, in <module>\n    main()\n  File 
\"/tmp/ansible_IvbWeW/ansible_module_bigip_selfip.py\", line 776, in main\n    results = 
mm.exec_module()\n  File \"/tmp/ansible_IvbWeW/ansible_module_bigip_selfip.py\", line 533, in 
exec_module\n    changed = self.present()\n  File 
\"/tmp/ansible_IvbWeW/ansible_module_bigip_selfip.py\", line 548, in present\n    changed = 
self.create()\n  File \"/tmp/ansible_IvbWeW/ansible_module_bigip_selfip.py\", line 604, in create\n  
  self.create_on_device()\n  File \"/tmp/ansible_IvbWeW/ansible_module_bigip_selfip.py\", line 615, 
in create_on_device\n    **params\n  File \"/usr/local/lib/python2.7/dist-
packages/f5/bigip/resource.py\", line 974, in create\n    return self._create(**kwargs)\n  File 
\"/usr/local/lib/python2.7/dist-packages/f5/bigip/resource.py\", line 941, in _create\n    response =
 session.post(_create_uri, json=kwargs, **requests_params)\n  File \"/usr/local/lib/python2.7/dist-
packages/icontrol/session.py\", line 258, in wrapper\n    response = method(self, REST_uri, 
**kwargs)\n  File \"/usr/local/lib/python2.7/dist-packages/icontrol/session.py\", line 477, in post\n 
   return self.session.post(uri, data=data, json=json, **kwargs)\n  File 
\"/usr/local/lib/python2.7/dist-packages/requests/sessions.py\", line 555, in post\n    return 
self.request('POST', url, data=data, json=json, **kwargs)\n  File \"/usr/local/lib/python2.7/dist-
packages/requests/sessions.py\", line 494, in request\n    prep = self.prepare_request(req)\n  File 
\"/usr/local/lib/python2.7/dist-packages/requests/sessions.py\", line 437, in prepare_request\n    
hooks=merge_hooks(request.hooks, self.hooks),\n  File \"/usr/local/lib/python2.7/dist-
packages/requests/models.py\", line 308, in prepare\n    self.prepare_body(data, files, json)\n  File
 \"/usr/local/lib/python2.7/dist-packages/requests/models.py\", line 458, in prepare_body\n    
body = complexjson.dumps(json)\n  File \"/usr/local/lib/python2.7/dist-
packages/simplejson/__init__.py\", line 380, in dumps\n    return _default_encoder.encode(obj)\n  
File \"/usr/local/lib/python2.7/dist-packages/simplejson/encoder.py\", line 291, in encode\n    
chunks = self.iterencode(o, _one_shot=True)\n  File \"/usr/local/lib/python2.7/dist-
packages/simplejson/encoder.py\", line 373, in iterencode\n    return _iterencode(o, 0)\n  File 
\"/usr/local/lib/python2.7/dist-packages/simplejson/encoder.py\", line 268, in default\n    raise 
TypeError(repr(o) + \" is not JSON serializable\")\nTypeError: set(['none']) is not JSON 
serializable\n", 
    "module_stdout": "", 
    "msg": "MODULE FAILURE", 
    "rc": 0
}

PLAY RECAP *****************************************************************************************************************************************************************************************************************************************************
zrdm5afpdg01pdgZZZ         : ok=1    changed=0    unreachable=0    failed=1   

```
