### ISSUE TITLE
bigip_remote_syslog not taking hostname from remote_host value

### ISSUE THREAD

**Issue by drakrubt** [F5Networks/f5-ansible#429]
When using a hostname for remote_host, it is throwing a AddrFormatError since netaddr.IPAddress is looking for an IP.  Should it be doing a socket.gethostbyname instead to convert the name to an IP?

**Comment by caphrim007** [comment]
@drakrubt if hostnames are an allowed value, then this is a bug.

**Comment by drakrubt** [comment]
according to module documentation it is implied it can be provided:
```
options:
  remote_host:
    description:
      - Specifies the IP address, or hostname, for the remote system to
        which the system sends log messages.
    required: True
```
It would be nice if the hostname could be passed all the way to the config since it is a valid config entry ... i just recommend the hostname->ip conversion if something about the api interface was only allowing IPs.
