### ISSUE TITLE
Unable to get ucs file by using bigip_ucs_fetch.py

### ISSUE THREAD

**Issue by sajaltiwari** [F5Networks/f5-ansible#432]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME
bigip_ucs_fetch

##### ANSIBLE VERSION

```
ansible 2.5.0
```

##### PYTHON VERSION

```
Python 2.7.6
```

##### BIGIP VERSION

```
Sys::Version
Main Package
  Product     BIG-IP
  Version     11.6.1
  Build       2.0.338
  Edition     Hotfix HF2
  Date        Fri Feb  3 14:44:37 PST 2017

```

##### SUMMARY
unable to backup or copy ucs files using the module bigip_ucs_fetch. 

##### STEPS TO REPRODUCE

```
 tasks:
   - name: run show version on remote devices
     bigip_ucs_fetch:
       validate_certs: "no"
       server: "172.16.129.231"
       user: "username"
       password: "password"
       src: "cs_backup.ucs"
       dest: "/tmp/cs_backup.ucs"
     delegate_to: localhost
```

##### EXPECTED RESULTS
It should copy the ucs files

##### ACTUAL RESULTS

ERROR! no action detected in task. This often indicates a misspelled module name, or incorrect module path.

The error appears to have been in '/etc/ansible/playbooks/copy_f5.yaml': line 8, column 6, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:

  tasks:
   - name: run show version on remote devices
     ^ here

The error appears to have been in '/etc/ansible/playbooks/copy_f5.yaml': line 8, column 6, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:

  tasks:
   - name: run show version on remote devices
     ^ here

```

```

**Comment by sajaltiwari** [comment]
I am able to run other modules like bigip_command on the F5 device.

**Comment by caphrim007** [comment]
@sajaltiwari thats an Ansible error, not a module error. One of two things is wrong

- You're not properly formatting your plays. Your spacing is incorrect or you are missing the common play headers such as `connection` and `hosts`
- You are trying to use a module that is not upstreamed and you have not installed it from this development repo.

**Comment by sajaltiwari** [comment]
Hello,
Below is my full yaml file

```
---

- hosts: RC_F5
  connection: local

  tasks:
   - name: run show version on remote devices
     bigip_ucs_fetch:
       validate_certs: "no"
       server: "172.16.129.231"
       user: "admin"
       password: "LTM$Adm!n"
       src: "cs_backup.ucs"
       dest: "/tmp/cs_backup.ucs"
     delegate_to: localhost


```
Any idea how can i install this module on my ansible, the current location for the existing modules is as shown below 

```
nisadmin@NISLABL1:/usr/local/lib/python2.7/dist-packages/ansible/modules/network/f5$ ls
bigip_command.py              bigip_device_sshd.py      bigip_gtm_virtual_server.py   bigip_irule.py                   bigip_node.py          bigip_routedomain.py   bigip_ssl_certificate.py   bigip_virtual_address.py
bigip_command.pyc             bigip_device_sshd.pyc     bigip_gtm_virtual_server.pyc  bigip_irule.pyc                  bigip_node.pyc         bigip_routedomain.pyc  bigip_ssl_certificate.pyc  bigip_virtual_address.pyc
bigip_config.py               bigip_facts.py            bigip_gtm_wide_ip.py          bigip_monitor_http.py            bigip_pool_member.py   bigip_selfip.py        bigip_sys_db.py            bigip_virtual_server.py
bigip_config.pyc              bigip_facts.pyc           bigip_gtm_wide_ip.pyc         bigip_monitor_http.pyc           bigip_pool_member.pyc  bigip_selfip.pyc       bigip_sys_db.pyc           bigip_virtual_server.pyc
bigip_configsync_actions.py   bigip_gtm_datacenter.py   bigip_hostname.py             bigip_monitor_tcp_echo.py        bigip_pool.py          bigip_snat_pool.py     bigip_sys_global.py        bigip_vlan.py
bigip_configsync_actions.pyc  bigip_gtm_datacenter.pyc  bigip_hostname.pyc            bigip_monitor_tcp_echo.pyc       bigip_pool.pyc         bigip_snat_pool.pyc    bigip_sys_global.pyc       bigip_vlan.pyc
bigip_device_dns.py           bigip_gtm_facts.py        bigip_iapp_service.py         bigip_monitor_tcp_half_open.py   bigip_provision.py     bigip_snmp.py          bigip_ucs.py               __init__.py
bigip_device_dns.pyc          bigip_gtm_facts.pyc       bigip_iapp_service.pyc        bigip_monitor_tcp_half_open.pyc  bigip_provision.pyc    bigip_snmp.pyc         bigip_ucs.pyc              __init__.pyc
bigip_device_ntp.py           bigip_gtm_pool.py         bigip_iapp_template.py        bigip_monitor_tcp.py             bigip_qkview.py        bigip_snmp_trap.py     bigip_user.py
bigip_device_ntp.pyc          bigip_gtm_pool.pyc        bigip_iapp_template.pyc       bigip_monitor_tcp.pyc            bigip_qkview.pyc       bigip_snmp_trap.pyc    bigip_user.pyc

```
Also the latest f5-sdk is already installed

```
nisadmin@NISLABL1:/etc/ansible/playbooks/archived-playbooks$ sudo pip install f5-sdk
The directory '/home/nisadmin/.cache/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
The directory '/home/nisadmin/.cache/pip' or its parent directory is not owned by the current user and caching wheels has been disabled. check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
Requirement already satisfied: f5-sdk in /usr/local/lib/python2.7/dist-packages
Requirement already satisfied: six>=1.9.0 in /usr/local/lib/python2.7/dist-packages (from f5-sdk)
Requirement already satisfied: f5-icontrol-rest>=1.3.0 in /usr/local/lib/python2.7/dist-packages (from f5-sdk)
Requirement already satisfied: requests<3,>=2.5.0 in /usr/local/lib/python2.7/dist-packages (from f5-icontrol-rest>=1.3.0->f5-sdk)

```
I am a novice in ansible and git field so still trying to get upto the speed. Any help would be greatly appreciated.

Many thanks for your understanding.
