### ISSUE TITLE
Help on sync and save

### ISSUE THREAD

**Issue by ric79** [F5Networks/f5-ansible#437]
Hello,
I need help about how to save configuration and syncing the device

**Sync**:
Are these two snippets equivalent?
```
- name: Sync configuration from device to group
  shell: >
          run cm config-sync to-group /Common/{{device_group_name}}
  args:
    executable: tmsh
```
```
- name: Sync configuration from device to group
  bigip_configsync_action:
    device_group: {{device_group_name}}
    sync_device_to_group: yes
    server: "{{inventory_hostname}}"
    user: "{{http.user}}"
    password: "{{http_password}}"
    validate_certs: "{{http.validate_certs}}"
  delegate_to: localhost
```

**Save**:
I've no idea about how to use bigip_config:
```
- name: "Save the data for current partition"
  shell: >
          cd /{{lbf5_partition_name}};
          save /sys config current-partition;
          save /sys config
  args:
    executable: tmsh
```

RR
