### ISSUE TITLE
bigip_selfip.py develop@ansible vs your repo

### ISSUE THREAD

**Issue by ric79** [F5Networks/f5-ansible#443]
Hello,
I think that the current version of [bigip_selfip ](https://github.com/ansible/ansible/commit/02cd88169764232fd63c776456178fe61d3a214a )on develop repo of ansible is broken.
This code:
```
    - name: "Add self IPs in current partition"
      bigip_selfip:
          server: "{{inventory_hostname}}"
          user: "{{http.user}}"
          password: "{{http_password}}"
          validate_certs: "{{http.validate_certs}}"
          name: "MYTEST"
          address: "192.168.249.62"
          netmask: "255.255.255.224"
          vlan: "....._BE_SYSTEST"
          traffic_group: "/Common/traffic-group-1"
          route_domain: "13"
          partition: "...._SYS_TEST"
          state: "present"
      delegate_to: localhost
```
produces a selfip pointing to a wrong traffic group. 
![x1](https://user-images.githubusercontent.com/6887824/32769730-5f4db9e2-c91d-11e7-96ce-a602f5370cb1.jpg)

The current version on your develop branch produces the right configuration. Is it safe to use only that module of this repo?
![x2](https://user-images.githubusercontent.com/6887824/32769734-62609906-c91d-11e7-8c78-20662615e4b3.jpg)

RR
