### ISSUE TITLE
bigip_command.py not honoring non-standard ssh ports in hosts file

### ISSUE THREAD

**Issue by devnullNZ** [F5Networks/f5-ansible#446]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

bigip_command

##### ANSIBLE VERSION

```
ansible 2.5.0
```

##### PYTHON VERSION

```
Python 3.5.2
```

##### BIGIP VERSION

```
Main Package
  Product     BIG-IP
  Version     12.1.2
  Build       0.207.249
  Edition     Engineering Hotfix
  Date        Thu Mar  2 11:46:01 PST 2017
```

##### LIBRARY VERSIONS

```
f5-sdk==3.0.4
```

##### SUMMARY

Does not honor ansible_port setting in hosts file

##### STEPS TO REPRODUCE

In ansible hosts file, set non-standard ssh port for host. Using ansible_ssh_port or ansible_port makes no difference.

[devf5]
lb1.local  ansible_host=2222

```
  tasks:
    - name: get ver
      bigip_command:
        commands: show sys version
        server: "{{ inventory_hostname }}"
        password: "{{ test_passwd }}"
        user: "{{ test_user }}"
        validate_certs: no
        transport: cli
      delegate_to: localhost
```

##### EXPECTED RESULTS

It should return current version

##### ACTUAL RESULTS

Socket timeout. A tcpdump confirms connection attempts are being made on port 22, not port 2222.
Paramiko connection attempt uses port 22, and ignores what has been set in the hosts file.

```

```
