### ISSUE TITLE
support metadata object

### ISSUE THREAD

**Issue by chen23** [F5Networks/f5-ansible#456]
##### ISSUE TYPE

 - Feature Idea

##### COMPONENT NAME
bigip_pool, bigip_virtualserver

##### SUMMARY
Since 11.2.x BIG-IP has supported a "metadata" field for certain LTM/GTM objects.

https://support.f5.com/kb/en-us/products/big-ip_ltm/releasenotes/product/relnote-ltm-11-2-0.html
>Private per-object metadata
>
> In this release, using tmsh or iControl, you can define metadata and retrieve user-defined metadata for certain BIG-IP LTM and GTM configuration objects, including virtual addresses and iApp application services. This metadata is in the form of a string key-value pair, as well as a Boolean value that indicates whether the key should be persisted or is ephemeral.

It would be useful to expose this to allow annotation of records that support metadata.  

Something like:

```
      - name: Create a VIP
        bigip_virtual_server:
            description: "foo-vip"
            destination: "172.16.10.108"
            password: "{{ bigip_password }}"
            name: "vip-1"
            pool: "web"
            port: "80"
            server: "{{ ansible_host }}"
            snat: "Automap"
            user: "{{ bigip_username }}"
            metadata:
                ansible: 2.4
            all_profiles:
                - "http"
                - "clientssl"
            validate_certs: "{{ validate_certs }}"
        delegate_to: localhost
```
Resulting in:

```
ltm virtual vip-1 {
    description foo-vip
    destination 172.16.10.108:http
    ip-protocol tcp
    mask 255.255.255.255
    metadata {
        ansible {
            value 2.4
        }
    }
    pool web
    profiles {
        clientssl {
            context clientside
        }
        http { }
        tcp { }
    }
    source 0.0.0.0/0
    source-address-translation {
        type automap
    }
    translate-address enabled
    translate-port enabled
    vs-index 5
}
```
