### ISSUE TITLE
vcmp_guest module is not idempotent for vlans?

### ISSUE THREAD

**Issue by caphrim007** [F5Networks/f5-ansible#457]
payal is reporting an idempotency issue on her vcmp host. The following is not working for her.

```
  - name: Create vCMP guests
    bigip_vcmp_guest:
      server: "10.192.73.91"
      user: "admin"
      password: "admin"
      name: "ansible-created"
      initial_image: "BIGIP-12.1.2.0.0.249.iso"
      mgmt_network: bridged
      mgmt_address: 10.20.30.40/24
      mgmt_route: 10.20.30.1
      vlans:
       - UM_Tenant1B_External_VLAN
       - UM_Tenant1B_Internal_VLAN
       - OOB_HA
      validate_certs: False
    delegate_to: localhost
```

This is a host that already exists, just updated the VLANS to it, the update works but when I run it again it is not idempotent
