### ISSUE TITLE
bigip_software not working on ve

### ISSUE THREAD

**Issue by mleklund** [F5Networks/f5-ansible#47]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME
bigip_software

##### ANSIBLE VERSION

```
ansible 2.3.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
```

##### PYTHON VERSION

```
Python 2.7.12
```

##### BIGIP VERSION

```
Sys::Version
Main Package
  Product     BIG-IP
  Version     12.1.1
  Build       0.0.184
  Edition     Final
  Date        Thu Aug 11 17:09:01 PDT 2016
```

##### CONFIGURATION
```
retry_files_enabled = False
host_key_checking=False
```
##### OS / ENVIRONMENT
Alpine 3.4 (Docker Container)

##### SUMMARY
Error when attempting to use bigip_software to update partition

##### STEPS TO REPRODUCE

```
#
# vim: ts=2 sts=2 sw=2 et:

- hosts: bigip-hosts
  vars:
  connection: local
  tasks:
    - bigip_software:
        password: "{{ bigip_password }}"
        server: "{{ inventory_hostname }}"
        user: "{{ bigip_username }}"
        validate_certs: "{{ validate_certs }}"
        software: "/root/BIGIP-12.1.1.0.0.184.iso"
        hotfix: "/root/Hotfix-BIGIP-12.1.1.1.0.196-HF1.iso"
        reuse_inactive_volume: yes
        state: "installed"
```

##### EXPECTED RESULTS

Software and hotfix to be applied to newly created partition

##### ACTUAL RESULTS

```
ASK [bigip_software] ************************************************************************************************************************************************
task path: /playbooks/bigip_software.yaml:10
Using module file /playbooks/library/bigip_software.py
<hostname.here> ESTABLISH LOCAL CONNECTION FOR USER: root
<hostname.here> EXEC /bin/sh -c '/usr/bin/python && sleep 0'
An exception occurred during task execution. The full traceback is:
Traceback (most recent call last):
  File "/tmp/ansible_CWDMRh/ansible_module_bigip_software.py", line 1130, in <module>
    main()
  File "/tmp/ansible_CWDMRh/ansible_module_bigip_software.py", line 1111, in main
    except ActiveVolumeError:
NameError: global name 'ActiveVolumeError' is not defined

fatal: [hostname.here]: FAILED! => {
    "changed": false,
    "failed": true,
    "invocation": {
        "module_name": "bigip_software"
    },
    "module_stderr": "Traceback (most recent call last):\n  File \"/tmp/ansible_CWDMRh/ansible_module_bigip_software.py\", line 1130, in <module>\n    main()\n  File \"/tmp/ansible_CWDMRh/ansible_module_bigip_software.py\", line 1111, in main\n    except ActiveVolumeError:\nNameError: global name 'ActiveVolumeError' is not defined\n",
    "module_stdout": "",
    "msg": "MODULE FAILURE"
}
	to retry, use: --limit @/playbooks/bigip_software.retry

PLAY RECAP ***********************************************************************************************************************************************************
lhostname.here     : ok=1    changed=0    unreachable=0    failed=1
```
