### ISSUE TITLE
add module to manage AFM address lists

### ISSUE THREAD

**Issue by caphrim007** [F5Networks/f5-ansible#488]
create security firewall address-list DIAMETER-NODES-FOREIGNNET { addresses replace-all-with { 10.10.10.10-20.20.20.20 { } } description "Covers DIAMETER-NODES FOREIGNNET Range on TRUSTEDNETWORK Protected Net" }

create security firewall address-list DIAMETER-NODES-PARTNERNETWORK-BILLING-DRA { addresses replace-all-with { 1.1.1.1 { } 2.2.2.2 { } } description "Covers DIAMETER-NODES PARTNERNETWORK BILLING DRA Range on TRUSTEDNETWORK Direct Net" }

create security firewall address-list DIAMETER-NODES-PARTNERNETWORK-BILLING-UDR { addresses replace-all-with { 3.3.3.3 { } 4.4.4.4 { } } description "Covers DIAMETER-NODES PARTNERNETWORK BILLING UDR Range on TRUSTEDNETWORK Direct Net" }

**Comment by caphrim007** [comment]
```
bigip_security_address_list
    name: DIAMETER-NODES-PARTNERNETWORK-BILLING-DRA
    description: Covers DIAMETER-NODES PARTNERNETWORK BILLING DRA Range on TRUSTEDNETWORK Direct Net
    addresses:
        - 1.1.1.1
        - 2.2.2.2
    fqdns:
        - google.com (requires a “global context be configured on the box; Security > Options > Network Firewall > FQDN Resolver > Global Context. See more here https://support.f5.com/kb/en-us/products/big-ip-afm/manuals/product/network-firewall-policies-implementations-12-0-0/4.html)
    geolocations:
        - (Afghanistan|AF)/Baghlan (module should know both the short and log country identifiers)
```
