### ISSUE TITLE
bigip_device_httpd.py - Feature Request - Support ALLOW similar to bigip_device_sshd.py

### ISSUE THREAD

**Issue by neozoolook** [F5Networks/f5-ansible#493]
##### ISSUE TYPE

 - Feature Idea

##### COMPONENT NAME

bigip_device_httpd.py

##### ANSIBLE VERSION

```
ansible 2.5.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/pp2854/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python2.7/dist-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 2.7.12 (default, Nov 19 2016, 06:48:10) [GCC 5.4.0 20160609]
```

##### PYTHON VERSION

```
2.7.12
```

##### BIGIP VERSION

```
Sys::Version
Main Package
  Product     BIG-IP
  Version     12.1.2
  Build       0.0.249
  Edition     Final
  Date        Wed Nov 30 16:04:00 PST 2016
```

##### LIBRARY VERSIONS

```
bigsuds==1.0.4
f5-sdk==2.3.3
```

##### CONFIGURATION

Standard ansible.cfg file setup

##### OS / ENVIRONMENT

Ubuntu 16.04TS

##### SUMMARY

Would like to see some additional options supported on the bigip_device_httpd.py similar to bigip_device_sshd.py to support whitelists.

```
  allow:
    description:
      - Specifies, if you have enabled SSH access, the IP address or address
        range for other systems that can use SSH to communicate with this
        system.
    choices:
      - all
      - IP address, such as 172.27.1.10
      - IP range, such as 172.27.*.* or 172.27.0.0/255.255.0.0
```
##### STEPS TO REPRODUCE

Configuration of F5 under HTTPD allows you to specify IP list for ALLOW, would like to be able to leverage the bigip_device_httpd.py similar to how supported in bigip_device_sshd.py.  here is sample playbook and configuration output examples;

```
---
- name: Set SSHD Security Banner & White List
  bigip_device_sshd:
    allow: "{{ sys_whitelist }}"
    banner: "enabled"
    banner_text: "{{ sys_global_sec_banner }}"
    server: "{{ ansible_host }}"
    user: "{{ username }}"
    password: "{{ password }}"
    validate_certs: "no"
  delegate_to: localhost

Example of HTTPD configuration on F5;
sys httpd {
    allow { 10.10.0.0/16 10.10.0.0/16 68.90.0.0/16 }
}

Also you must support 'ALL' as possible option as well.

```

```

```

##### ACTUAL RESULTS

```

```
