### ISSUE TITLE
bigip_iapp_service f5.citrix_vdi.v2.4.2.tmpl using apm__ad_tree parameter

### ISSUE THREAD

**Issue by pgomersbach** [F5Networks/f5-ansible#496]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

bigip_iapp_service
##### ANSIBLE VERSION

```
ansible 2.5.0
  config file = /home/ubuntu/f5-ansible_automation/ansible.cfg
  configured module search path = [u'/home/ubuntu/f5-ansible_automation/library']
  ansible python module location = /usr/lib/python2.7/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.6 (default, Oct 26 2016, 20:30:19) [GCC 4.8.4]
```

##### PYTHON VERSION

```
Python 2.7.6
```

##### BIGIP VERSION

```
Sys::Version
Main Package
  Product     BIG-IP
  Version     12.1.2
  Build       1.0.271
  Edition     Hotfix HF1
  Date        Fri Apr 28 20:02:07 PDT 2017
```

##### LIBRARY VERSIONS

```
bigsuds==1.0.6
f5-sdk==3.0.5
```

##### OS / ENVIRONMENT

N/A
##### SUMMARY

When setting the apm__ad_tree parameter to "ou=Citrix Users, dc=Citrix, dc=example" the bigip_iapp_service tasks fails.
##### STEPS TO REPRODUCE

use apm__ad_tree parameter in iapp.service task fails, suspect a quoting problem.

```
      - name: Create iApp f5.citrix_vdi service from iApp template
        bigip_iapp_service:
            name: "ans-iapp"
            template: "/Common/f5.citrix_vdi.v2.4.2"
            parameters:
                tables:
                  - name: "apm__active_directory_server"
                    rows:
                      - host: "ad1.claranet.nl"
                        addr: "1.1.1.1"
                  - name: "xml_broker_pool__servers"
                    rows:
                      - addr: "12.12.12.12"
                        connection_limit: "0"
                  - name: "xml_broker_virtual__ica_parameters"
                    rows:
                      - name: ""
                        parameter: ""
                        value: ""
                variables:
                    - name: "webui_virtual__sta"
                      value: "12.12.12.12"
                    - name: "webui_virtual__custom_uri"
                      value: "FQDN.WEBTOP"
                    - name: "xml_broker_virtual__addr"
                      value: "12.12.12.12"
                    - name: "apm__active_directory_password"
                      encrypted: "yes"
                      value: "M$Ut$Ii0ovqHLkflZzGsSGCnhngaYJK0QKvOnsFtSc2ha6zw="
                    - name: "apm__active_directory_username"
                      value: "VAR-ADSERVICEACCOUNT"
                    - name: "apm__ad_password"
                      encrypted: "yes"
                      value: "M$a4$h9um+bc1n/KXcDwhMyIIzgaYJK0QKvOnsFtSc2ha6zw="
                    - name: "apm__ad_tree"
                      value: "ou=Citrix Users, dc=Citrix, dc=example"
                    - name: "apm__ad_user"
                      value: "VAR-ADSERVICEACCOUNT"
                    - name: "general__domain_name"
                      value: "ADNETBIOS"
                    - name: "apm__login_domain"
                      value: "VAR-ADFQDN"
                    - name: "webui_pool__webui_dns_name"
                      value: "VAR-FQDNPORTAL"
                    - name: "webui_virtual__addr"
                      value: "11.11.11.11"
                    - name: "webui_virtual__clientssl_profile"
                      value: "/Common/claranet-wildcard"
                    - name: "xml_broker_pool__monitor_app"
                      value: "VAR-TESTAPP"
                    - name: "xml_broker_pool__monitor_password"
                      encrypted: "yes"
                      value: "M$BI$TmhQFUUC1hhTAGBf8Q8ipiKD3NAbzeYXpaH24FmVFqA="
                    - name: "xml_broker_pool__monitor_username"
                      value: "VAR-CITRIXTESTACC"
                    - name: "xml_broker_virtual__client_bundle_url"
                      value: "receiver.citrix.com"
                    - name: "config_mode"
                      value: "advanced"
                    - name: "scenario"
                      value: "apm_scenario"
                    - name: "xml_broker_virtual__http_port"
                      value: "80"
                    - name: "xml_broker_virtual__https_port"
                      value: "443"
                    - name: "xml_broker_virtual__rules"
                      value: ""
                    - name: "xml_broker_virtual__cert"
                      value: ""
                    - name: "xml_broker_virtual__key"
                      value: ""
                    - name: "webui_virtual__https_port"
                      value: "443"
                    - name: "webui_pool__pool"
                      value: "web"
                    - name: "afm__policy"
                      value: "/#do_not_use#"
                    - name: "apm__aaa_profile"
                      value: "/#create_new#"
                    - name: "apm__ad_interval"
                      value: "10"
                    - name: "apm__ad_monitor"
                      value: "ad_create"
                    - name: "apm__ad_port_not_ssl"
                      value: "389"
                    - name: "apm__ad_secure"
                      value: "none"
                    - name: "apm__allow_anonymous_binding"
                      value: "credentials_required"
                    - name: "apm__logging"
                      value: "/Common/default-log-setting"
                    - name: "apm__replace_webui_question"
                      value: "replace"
                    - name: "apm__rsa"
                      value: "No"
                    - name: "apm__smartcard"
                      value: "No"
                    - name: "general__assistance_options"
                      value: "full"
                    - name: "general__config_mode"
                      value: "advanced"
                    - name: "general__scenario"
                      value: "apm_scenario"
                    - name: "webui_virtual__create_redir_vs"
                      value: "create_redir_vs"
                    - name: "webui_virtual__lan_or_wan"
                      value: "WAN"
                    - name: "webui_virtual__location"
                      value: "same_subnet"
                    - name: "webui_virtual__redir_port"
                      value: "80"
                    - name: "webui_virtual__rules"
                      value: ""
                    - name: "xml_broker_pool__caption"
                      value: "Farm Unavailable"
                    - name: "xml_broker_pool__enable_pga"
                      value: "no_pga"
                    - name: "xml_broker_pool__lb_method_choice"
                      value: "least-connections-member"
                    - name: "xml_broker_pool__monitor"
                      value: "/#create_new#"
                    - name: "xml_broker_pool__monitor_interval"
                      value: "30"
                    - name: "xml_broker_pool__pool_alt"
                      value: "/#create_new#"
                    - name: "xml_broker_pool__slow_ramp_enable"
                      value: "enable"
                    - name: "xml_broker_pool__slow_ramp_setvalue"
                      value: "300"
                    - name: "xml_broker_virtual__client_bundle"
                      value: "/#create_new#"
                    - name: "xml_broker_virtual__encrypted"
                      value: "encrypted"
                    - name: "xml_broker_virtual__xml_farms"
                      value: "1"
            server: "{{inventory_hostname}}"
            user: "{{user}}"
            password: "{{password}}"
            validate_certs: "{{validate_certs}}"
            partition: "{{partition}}"
        delegate_to: localhost
```

##### EXPECTED RESULTS

Deploy template
##### ACTUAL RESULTS

TASK [Create iApp f5.citrix_vdi service from iApp template] ***************************************************************************
task path: /home/ubuntu/f5-ansible_automation/tasks/iapp.yml:17
Using module file /home/ubuntu/f5-ansible_automation/library/bigip_iapp_service.py
<localhost> ESTABLISH LOCAL CONNECTION FOR USER: ubuntu
<localhost> EXEC /bin/sh -c 'echo ~ && sleep 0'
<localhost> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /home/ubuntu/.ansible/tmp/ansible-tmp-1512646524.34-75352894881700 `" && echo ansible-tmp-1512646524.34-75352894881700="` echo /home/ubuntu/.ansible/tmp/ansible-tmp-1512646524.34-75352894881700 `" ) && sleep 0'
<localhost> PUT /tmp/tmp3AGBEC TO /home/ubuntu/.ansible/tmp/ansible-tmp-1512646524.34-75352894881700/bigip_iapp_service.py
<localhost> EXEC /bin/sh -c 'chmod u+x /home/ubuntu/.ansible/tmp/ansible-tmp-1512646524.34-75352894881700/ /home/ubuntu/.ansible/tmp/ansible-tmp-1512646524.34-75352894881700/bigip_iapp_service.py && sleep 0'
<localhost> EXEC /bin/sh -c '/usr/bin/python /home/ubuntu/.ansible/tmp/ansible-tmp-1512646524.34-75352894881700/bigip_iapp_service.py; rm -rf "/home/ubuntu/.ansible/tmp/ansible-tmp-1512646524.34-75352894881700/" > /dev/null 2>&1 && sleep 0'
The full traceback is:
  File "/tmp/ansible_dEMM1T/ansible_module_bigip_iapp_service.py", line 665, in main
    results = mm.exec_module()
  File "/tmp/ansible_dEMM1T/ansible_module_bigip_iapp_service.py", line 535, in exec_module
    raise F5ModuleError(str(e))

fatal: [212.61.222.170 -> localhost]: FAILED! => {
    "changed": false,
    "invocation": {
        "module_args": {
            "force": false,
            "name": "ans-iapp",
            "parameters": {
                "tables": [
                    {
                        "name": "apm__active_directory_server",
                        "rows": [
                            {
                                "addr": "1.1.1.1",
                                "host": "ad1.claranet.nl"
                            }
                        ]
                    },
                    {
                        "name": "xml_broker_pool__servers",
                        "rows": [
                            {
                                "addr": "12.12.12.12",
                                "connection_limit": "0"
                            }
                        ]
                    },
                    {
                        "name": "xml_broker_virtual__ica_parameters",
                        "rows": [
                            {
                                "name": "",
                                "parameter": "",
                                "value": ""
                            }
                        ]
                    }
                ],
                "variables": [
                    {
                        "name": "webui_virtual__sta",
                        "value": "12.12.12.12"
                    },
                    {
                        "name": "webui_virtual__custom_uri",
                        "value": "FQDN.WEBTOP"
                    },
                    {
                        "name": "xml_broker_virtual__addr",
                        "value": "12.12.12.12"
                    },
                    {
                        "encrypted": "yes",
                        "name": "apm__active_directory_password",
                        "value": "M$Ut$Ii0ovqHLkflZzGsSGCnhngaYJK0QKvOnsFtSc2ha6zw="
                    },
                    {
                        "name": "apm__active_directory_username",
                        "value": "VAR-ADSERVICEACCOUNT"
                    },
                    {
                        "encrypted": "yes",
                        "name": "apm__ad_password",
                        "value": "M$a4$h9um+bc1n/KXcDwhMyIIzgaYJK0QKvOnsFtSc2ha6zw="
                    },
                    {
                        "name": "apm__ad_tree",
                        "value": "ou=Citrix Users, dc=Citrix, dc=example"
                    },
                    {
                        "name": "apm__ad_user",
                        "value": "VAR-ADSERVICEACCOUNT"
                    },
                    {
                        "name": "general__domain_name",
                        "value": "ADNETBIOS"
                    },
                    {
                        "name": "apm__login_domain",
                        "value": "VAR-ADFQDN"
                    },
                    {
                        "name": "webui_pool__webui_dns_name",
                        "value": "VAR-FQDNPORTAL"
                    },
                    {
                        "name": "webui_virtual__addr",
                        "value": "11.11.11.11"
                    },
                    {
                        "name": "webui_virtual__clientssl_profile",
                        "value": "/Common/claranet-wildcard"
                    },
                    {
                        "name": "xml_broker_pool__monitor_app",
                        "value": "VAR-TESTAPP"
                    },
                    {
                        "encrypted": "yes",
                        "name": "xml_broker_pool__monitor_password",
                        "value": "M$BI$TmhQFUUC1hhTAGBf8Q8ipiKD3NAbzeYXpaH24FmVFqA="
                    },
                    {
                        "name": "xml_broker_pool__monitor_username",
                        "value": "VAR-CITRIXTESTACC"
                    },
                    {
                        "name": "xml_broker_virtual__client_bundle_url",
                        "value": "receiver.citrix.com"
                    },
                    {
                        "name": "config_mode",
                        "value": "advanced"
                    },
                    {
                        "name": "scenario",
                        "value": "apm_scenario"
                    },
                    {
                        "name": "xml_broker_virtual__http_port",
                        "value": "80"
                    },
                    {
                        "name": "xml_broker_virtual__https_port",
                        "value": "443"
                    },
                    {
                        "name": "xml_broker_virtual__rules",
                        "value": ""
                    },
                    {
                        "name": "xml_broker_virtual__cert",
                        "value": ""
                    },
                    {
                        "name": "xml_broker_virtual__key",
                        "value": ""
                    },
                    {
                        "name": "webui_virtual__https_port",
                        "value": "443"
                    },
                    {
                        "name": "webui_pool__pool",
                        "value": "web"
                    },
                    {
                        "name": "afm__policy",
                        "value": "/#do_not_use#"
                    },
                    {
                        "name": "apm__aaa_profile",
                        "value": "/#create_new#"
                    },
                    {
                        "name": "apm__ad_interval",
                        "value": "10"
                    },
                    {
                        "name": "apm__ad_monitor",
                        "value": "ad_create"
                    },
                    {
                        "name": "apm__ad_port_not_ssl",
                        "value": "389"
                    },
                    {
                        "name": "apm__ad_secure",
                        "value": "none"
                    },
                    {
                        "name": "apm__allow_anonymous_binding",
                        "value": "credentials_required"
                    },
                    {
                        "name": "apm__logging",
                        "value": "/Common/default-log-setting"
                    },
                    {
                        "name": "apm__replace_webui_question",
                        "value": "replace"
                    },
                    {
                        "name": "apm__rsa",
                        "value": "No"
                    },
                    {
                        "name": "apm__smartcard",
                        "value": "No"
                    },
                    {
                        "name": "general__assistance_options",
                        "value": "full"
                    },
                    {
                        "name": "general__config_mode",
                        "value": "advanced"
                    },
                    {
                        "name": "general__scenario",
                        "value": "apm_scenario"
                    },
                    {
                        "name": "webui_virtual__create_redir_vs",
                        "value": "create_redir_vs"
                    },
                    {
                        "name": "webui_virtual__lan_or_wan",
                        "value": "WAN"
                    },
                    {
                        "name": "webui_virtual__location",
                        "value": "same_subnet"
                    },
                    {
                        "name": "webui_virtual__redir_port",
                        "value": "80"
                    },
                    {
                        "name": "webui_virtual__rules",
                        "value": ""
                    },
                    {
                        "name": "xml_broker_pool__caption",
                        "value": "Farm Unavailable"
                    },
                    {
                        "name": "xml_broker_pool__enable_pga",
                        "value": "no_pga"
                    },
                    {
                        "name": "xml_broker_pool__lb_method_choice",
                        "value": "least-connections-member"
                    },
                    {
                        "name": "xml_broker_pool__monitor",
                        "value": "/#create_new#"
                    },
                    {
                        "name": "xml_broker_pool__monitor_interval",
                        "value": "30"
                    },
                    {
                        "name": "xml_broker_pool__pool_alt",
                        "value": "/#create_new#"
                    },
                    {
                        "name": "xml_broker_pool__slow_ramp_enable",
                        "value": "enable"
                    },
                    {
                        "name": "xml_broker_pool__slow_ramp_setvalue",
                        "value": "300"
                    },
                    {
                        "name": "xml_broker_virtual__client_bundle",
                        "value": "/#create_new#"
                    },
                    {
                        "name": "xml_broker_virtual__encrypted",
                        "value": "encrypted"
                    },
                    {
                        "name": "xml_broker_virtual__xml_farms",
                        "value": "1"
                    }
                ]
            },
            "partition": "Ansible-test",
            "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "server": "212.61.222.170",
            "server_port": 443,
            "state": "present",
            "strict_updates": null,
            "template": "/Common/f5.citrix_vdi.v2.4.2",
            "traffic_group": null,
            "user": "Paul",
            "validate_certs": false
        }
    },
    "msg": "400 Unexpected Error: Bad Request for uri: https://212.61.222.170:443/mgmt/tm/sys/application/service/\nText: u'{\"code\":400,\"message\":\"{\\\\\"code\\\\\":400,\\\\\"message\\\\\":\\\\\"script did not successfully complete: (\\\\\\\\\\\\\"0\\\\\\\\\\\\\" unknown property\\\\\\\\n    while executing\\\\\\\\n\\\\\\\\\\\\\"tmsh::create [string range $args 7 end] \\\\\\\\\\\\\"\\\\\\\\n    (\\\\\\\\\\\\\"create\\\\\\\\\\\\\" arm line 1)\\\\\\\\n    invoked from within\\\\\\\\n\\\\\\\\\\\\\"switch -exact -- [string range $args 0 5] {\\\\\\\\n            create { tmsh::create [string range $args 7 end] }\\\\\\\\n            modify { tmsh::modify [string r...\\\\\\\\\\\\\"\\\\\\\\n    (procedure \\\\\\\\\\\\\"iapp_conf\\\\\\\\\\\\\" line 14)\\\\\\\\n    invoked from within\\\\\\\\n\\\\\\\\\\\\\"iapp_conf create ltm monitor ldap ${app}_ldap  base \\\\\\\\\\\\\\\\\\\\\\\\\\\\\"$::apm__ad_tree\\\\\\\\\\\\\\\\\\\\\\\\\\\\\"  chase-referrals yes  debug no  defaults-from ldap  destination *:[subst $aaa_...\\\\\\\\\\\\\"\\\\\\\\n    invoked from within\\\\\\\\n\\\\\\\\\\\\\"subst $substa_out\\\\\\\\\\\\\"\\\\\\\\n    invoked from within\\\\\\\\n\\\\\\\\\\\\\"if { [info exists [set substa_in]] } {\\\\\\\\n            set substa_out [subst $$substa_in]\\\\\\\\n            set substa_out [subst $substa_out]\\\\\\\\n        } else {\\\\\\\\n...\\\\\\\\\\\\\"\\\\\\\\n    (\\\\\\\\\\\\\"uplevel\\\\\\\\\\\\\" body line 3)\\\\\\\\n    invoked from within\\\\\\\\n\\\\\\\\\\\\\"uplevel {\\\\\\\\n        append ::substa_debug \\\\\\\\\\\\\"\\\\\\\\\\\\\\\\n$substa_in\\\\\\\\\\\\\"\\\\\\\\n        if { [info exists [set substa_in]] } {\\\\\\\\n            set substa_out\",\"errorStack\":[]}'"
}

```

```
