### ISSUE TITLE
Route Domain inside a partition

### ISSUE THREAD

**Issue by ric79** [F5Networks/f5-ansible#51]
##### ISSUE TYPE
 - Bug Report?

##### COMPONENT NAME
bigip_routedomain

##### ANSIBLE VERSION
ansible 2.2.0.0

##### BIGIP VERSION
Main Package
  Product     BIG-IP
  Version     12.0.0
  Build       1.0.628
  Edition     Hotfix HF1
  Date        Tue Dec 22 13:18:00 PST 2015

Hello,
I have already a partition:
```
    - name: "Crea la partizione"
      bigip_partition:
        server: "..."
        user: "..."
        password: "..."
        validate_certs: "no"
        name: "APS_PARTITION"
        description: "..."
        state: "present"
```
Using the GUI, I select the partition from the upper right dropdown and then I create a default route domain only for that partition. What I'm trying to get is this: 
![pic1](https://cloud.githubusercontent.com/assets/6887824/20482010/660990dc-afea-11e6-8f41-c165a227ab50.jpg)

Now, this task
```
    - name: "Crea un Route Domain"
      bigip_routedomain:
        server: "..."
        user: "..."
        password: "..."
        validate_certs: "no"
        id: "10"
        description: "..."
        state: "present"
      ignore_errors: True
```
will create the R.D. "10" for all partitions not just for "APS_PARTITION". How can I achieve it?

R

**Comment by caphrim007** [comment]
I was about to suggest that you supply the "partition" parameter, but now that I look at the code, I'm not sure that's going to work.

Can you try it anyway just to confirm my suspicion?

`partition: APS_PARTITION`

in the `bigip_routedomain` module

**Comment by ric79** [comment]
KO. The route domain is created for all partitions.
Using tmsh I usually do:
```
tmsh
create auth partition "PART_A" description "blah blah"
cd /PART_A
create net route-domain "ROUTE_DOMAIN_11" id 11
modify auth partition PART_A default-route-domain 11
```

**Comment by caphrim007** [comment]
@ric79 I've pushed updated code for the bigip_routedomain module here. Can you check if this addresses your issue? thanks.

**Comment by ric79** [comment]
Hello, sorry for late late answer. It seems to me that it is working in this way:

```
- name: "Add Route Domain as default in current partition"
  bigip_routedomain:
    server: "..."
    user: "..."
    password: "..."
    validate_certs: "..."
    id: "{{default_rd.id}}"
    #name: "{{default_rd.name}}"
    description: "{{default_rd.description}}"
    strict: "{{default_rd.strict}}"
    partition: "{{partition.name}}"
  delegate_to: localhost

- name: "Modify the partition with route_domain"
  bigip_partition:
    server: "..."
    user: "..."
    password: "..."
    validate_certs: "..."
    name: "{{partition.name}}"
    route_domain: "{{default_rd.id}}"
  delegate_to: localhost
```

Just a quick info: using https://github.com/ansible/ansible/tree/devel/lib/ansible/modules/network/f5 is not possible to name the route domain (is: create net route-domain "ROUTE_DOMAIN_11" id 11). 

"Unsupported parameters for (bigip_routedomain) module: name. Supported parameters include: bwc_policy,connection_limit,description,flow_eviction_policy,id,parent,partition,password,routing_protocol,server,server_port,service_policy,state,strict,user,validate_certs,vlans"}
