### ISSUE TITLE
Traffic group for self ip

### ISSUE THREAD

**Issue by ric79** [F5Networks/f5-ansible#52]
##### ISSUE TYPE
 - Bug Report?

##### COMPONENT NAME
bigip_selfip

##### ANSIBLE VERSION
ansible 2.2.0.0

##### BIGIP VERSION
Main Package
  Product     BIG-IP
  Version     12.0.0
  Build       1.0.628
  Edition     Hotfix HF1
  Date        Tue Dec 22 13:18:00 PST 2015

Hello,
I have a partition and inside it I need to configure as the picture:
![a1](https://cloud.githubusercontent.com/assets/6887824/20503537/3ce7ea9c-b043-11e6-8126-7e78dc58f943.jpg)

```
    - name: Add VLAN xxx as tagged to interface yyy
      bigip_selfip:
          server: "..."
          user: "..."
          password: "..."
          validate_certs: "no"
          name: "{{self_ip.name}}"   
          address: "{{self_ip.ip_address}}"   
          netmask: "{{self_ip.netmask}}"   
          vlan: "{{self_ip.vlan_tunnel}}"   
          partition: "aps_bfx"
          traffic_group: "traffic-group-local-only" #or /Common/traffic-group-local-only   
          state: "present"               
```

I always get :
```
...
"400 Unexpected Error: Bad Request for uri: https://xxx.xxx.xxx.xxx:443/mgmt/tm/net/self/\nText: u'{\"code\":400,\"message\":\"01070734:3: Configuration error: Traffic group (/aps_bfx/traffic-group-local-only) does not exist.\"
```

or
```
{"failed": true, "msg": "The specified traffic group was not found", "self_ip": {"ip_address": "...", "name": "...", "netmask": "...", "traffic_group": "/Common/traffic-group-local-only", "vlan_tunnel": "..."}}
```

R

**Comment by caphrim007** [comment]
hmm. well, indeed the partition that you specify is how we determine which traffic groups you are allowed to use.

I assumed that settings cannot cross partitions, but it seems like that was an invalid assumption to make. So I will need to go back and address this and/or figure out what the REST api expects in case,

1. yours or my assumptions need to change, or
2. we need to file a bug and hack around it

**Comment by ric79** [comment]
I'm not very skilled on F5. I'm just porting on Ansible F5 the configurations made by other collegues. I can confirm that in field we have dozen of those configurations (basically one partition for one VNF) and they works! :)
1 --> I think you should change your assumptions :)

**Comment by caphrim007** [comment]
@ric79 try now

**Comment by ric79** [comment]
Sorry for late answer. I can confirm that everything is ok.

```
- name: "Add self IPs in current partition"
  bigip_selfip:
      server: "{{inventory_hostname}}"
      user: "{{http.user}}"
      password: "{{http.password}}"
      validate_certs: "{{http.validate_certs}}"
      name: "{{self_ip.name.primary}}"
      address: "{{self_ip.ip_address.primary}}"
      netmask: "{{self_ip.netmask}}"
      vlan: "{{self_ip.vlan_tunnel}}"
      traffic_group: "{{self_ip.traffic_group}}"
      route_domain: "{{default_rd.id}}"
      partition: "{{partition.name}}"
      state: "present"
  delegate_to: localhost
```
