### ISSUE TITLE
bigip_gtm_server server-type it suppose to by single-bigip not  standalone-bigip 

### ISSUE THREAD

**Issue by RequinBleu** [F5Networks/f5-ansible#539]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

bigip_gtm_server
##### ANSIBLE VERSION

```
ansible 2.5.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/usr/share/ansible']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, May  3 2017, 07:55:04) [GCC 4.8.5 20150623 (Red Hat 4.8.5-14)]
```

##### PYTHON VERSION

```
Python 2.7.5
```

##### BIGIP VERSION

```
Sys::Version
Main Package
  Product     BIG-IP
  Version     12.1.2
  Build       1.0.271
  Edition     Hotfix HF1
  Date        Fri Apr 28 20:02:07 PDT 2017
```

##### LIBRARY VERSIONS

```
f5-sdk==3.0.6
```

##### CONFIGURATION

N/A

##### OS / ENVIRONMENT

N/A

##### STEPS TO REPRODUCE

The module require standalone-bigip but bigip need single-bigip so the module don't work.

you need to change:
at line 512:
'foundry-server-iron', 'netapp', 'standalone-bigip',
by 
'foundry-server-iron', 'netapp', 'single-bigip',

By the way in you exemple you need to change product by server-type

```
     bigip_gtm_server:
      server: "{{ ansible_host }}"
      name: "{{ inventory_hostname }}"
      datacenter: /Common/{{ item.datacenter }}
      server_type: standalone-bigip
      link_discovery: disabled
      virtual_server_discovery: disabled
      devices:
        - {'name': '{{fqdn}}', 'address': '{{ansible_host}}'}
     with_items: "{{spreadsheet_GTM}}"
     when: 
       - item.mgt_IP in ansible_host
       - item.do == "yes"
```

##### ACTUAL RESULTS

```
msg": "400 Unexpected Error: Bad Request for uri: https://x.x.x.x:443/mgmt/tm/gtm/server/~Common~hostname/\nText: u'{\"code\":400,\"message\":\"invalid property value \\\\\"product\\\\\":\\\\\"standalone-bigip\\\\\"\",\"errorStack\":[],\"apiError\":26214401}'"
```
