### ISSUE TITLE
Bigip_command failed paramiko 

### ISSUE THREAD

**Issue by mmihir82** [F5Networks/f5-ansible#54]
##### ISSUE TYPE

 - Bug Report
 - Feature Idea
 - Documentation Report

##### ANSIBLE VERSION

```
2.2
```

##### PYTHON VERSION

```
2.7.12
```

##### BIGIP VERSION

```
11.6.1
```

##### OS / ENVIRONMENT
List of packages installed:
ansible (2.2.0.0)
bigsuds (1.0.4)
cffi (1.9.1)
cryptography (1.6)
enum34 (1.1.6)
f5-icontrol-rest (1.1.0)
f5-sdk (2.1.0)
idna (2.1)
ipaddress (1.0.17)
Jinja2 (2.8)
MarkupSafe (0.23)
ordereddict (1.1)
paramiko (2.0.2)
pip (9.0.1)
pyasn1 (0.1.9)
pycparser (2.17)
pycrypto (2.6.1)
PyYAML (3.12)
requests (2.12.3)
setuptools (30.0.0)
six (1.10.0)
suds (0.4)
wheel (0.30.0a0)

##### SUMMARY
Received Error:
TASK [f5_command : Run a command] **********************************************
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: NameError: global name 'paramiko' is not defined
fatal: [MABLT1-MFW2 -> None]: FAILED! => {"changed": false, "failed": true, "module_stderr": "Traceback (most recent call last):\n  File \"/var/folders/qz/j01vhkzs5ygddswn06812y54zy407f/T/ansible_K7Ow8O/ansible_module_bigip_command.py\", line 246, in <module>\n    main()\n  File \"/var/folders/qz/j01vhkzs5ygddswn06812y54zy407f/T/ansible_K7Ow8O/ansible_module_bigip_command.py\", line 236, in main\n    except paramiko.ssh_exception.SSHException as e:\nNameError: global name 'paramiko' is not defined\n", "module_stdout": "", "msg": "MODULE FAILURE"}

##### STEPS TO REPRODUCE
Created a environment,
```
Created a f5-comand role
Import the library
run the playbook
```

```
Dry-run thru: https://github.com/F5Networks/f5-ansible

```

##### ACTUAL RESULTS

```

```

**Comment by caphrim007** [comment]
@mmihir82 can you post the playbook you used?

I suspect the code is not being run on your local machine.

**Comment by mmihir82** [comment]
PLAYBOOK
test-command.yml 
```
- name: Test the bigip_command module
  hosts: FW
  connection: local
  roles:
      - f5_command

```
ROLE:
f5_command
```
---
- name: Run a command
  bigip_command:
      server: "{{ inventory_hostname }}"
      user: {{ username }}
      password: {{ password }}
      command: "tmsh list sys auth"
      validate_certs: "no"
  delegate_to: localhost

```
