### ISSUE TITLE
Enhancement - bigip_snmp.py - Support 'Allowed-addresses' in module

### ISSUE THREAD

**Issue by neozoolook** [F5Networks/f5-ansible#552]
##### ISSUE TYPE

 - Feature Idea

##### COMPONENT NAME

bigip_snmp.py

##### ANSIBLE VERSION

```
ansible 2.5.0
  config file = /home/pp2854/dev-vepdg-ansible/ansible-vepdg_fw/ansible.cfg
  configured module search path = [u'/home/pp2854/dev-vepdg-ansible/ansible-vepdg_fw/library']
  ansible python module location = /usr/local/lib/python2.7/dist-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 2.7.12 (default, Nov 19 2016, 06:48:10) [GCC 5.4.0 20160609]
```

##### PYTHON VERSION

```
Python 2.7.12
```

##### BIGIP VERSION

```
Sys::Version
Main Package
  Product     BIG-IP
  Version     12.1.2
  Build       0.0.249
  Edition     Final
  Date        Wed Nov 30 16:04:00 PST 2016
```

##### LIBRARY VERSIONS

```
bigsuds==1.0.4
f5-sdk==2.3.3
```

##### CONFIGURATION

standard ansible.cfg

##### OS / ENVIRONMENT

Ubuntu 16.04TS

##### SUMMARY

Currently the bigip_snmp.py module doesn't have options to support adding an 'allowed-addresses' IP whitelese, nor does it support creation of a community with access string.  This is done post using bigip_command.py which isn't ideal.

##### STEPS TO REPRODUCE

Currently we have to use bigip_command.py to get these items added into the configuration, example below;

```
---
- name: Set SNMP Configuration Extras
  bigip_command:
    commands:
      - 'modify sys snmp allowed-addresses replace-all-with { {{ snmp_whitelist }} }'
      - 'modify sys snmp communities replace-all-with { {{ snmp_comm_name }} { community-name {{ snmp_community }} }}'
    server: "{{ ansible_host }}"
    user: "{{ username }}"
    password: "{{ password }}"
    validate_certs: "no"
  delegate_to: localhost
```
here is example of configuration on F5 using these options;
```
sys snmp {
    agent-addresses { tcp6:161 udp6:161 }
    allowed-addresses { 135.144.38.162 135.21.229.115 135.205.224.69 135.197.237.169 135.207.171.152 135.205.224.108 135.205.224.87 135.213.31.83 135.213.31.112 135.207.170.183 135.21.229.245 107.239.72.7 }
    communities {
        SNMP_RO {
            community-name XXXXXXXXXXXXXXXXX
        }
    }
    disk-monitors {
        root {
            minspace 2000
            path /
        }
        var {
            minspace 10000
            path /var
        }
    }
    process-monitors {
        bigd {
            process bigd
        }
        chmand {
            process chmand
        }
        httpd {
            max-processes infinity
            process httpd
        }
        mcpd {
            process mcpd
        }
        sod {
            process sod
        }
        tmm {
            max-processes infinity
            process tmm
        }
    }
    sys-contact "ATT Labs"
    sys-location zrdm5a
    traps {
        dcaedev1 {
            community XXXXXXXXXXXXXXXXX
            host 135.21.162.4
        }
        dcaedev2 {
            community XXXXXXXXXXXXXXXXX
            host 135.144.38.162
        }
    }
}
```

##### ACTUAL RESULTS

```

```
