### ISSUE TITLE
Feature Request - New Module to support modification to 'sys software update' values

### ISSUE THREAD

**Issue by neozoolook** [F5Networks/f5-ansible#553]
##### ISSUE TYPE

 - Feature Idea

##### COMPONENT NAME

Possible enhancement or new module.

##### ANSIBLE VERSION

```
ansible 2.5.0
  config file = /home/pp2854/dev-vepdg-ansible/ansible-vepdg_fw/ansible.cfg
  configured module search path = [u'/home/pp2854/dev-vepdg-ansible/ansible-vepdg_fw/library']
  ansible python module location = /usr/local/lib/python2.7/dist-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 2.7.12 (default, Nov 19 2016, 06:48:10) [GCC 5.4.0 20160609]
```

##### PYTHON VERSION

```
Python 2.7.12
```

##### BIGIP VERSION

```
Sys::Version
Main Package
  Product     BIG-IP
  Version     12.1.2
  Build       0.0.249
  Edition     Final
  Date        Wed Nov 30 16:04:00 PST 2016
```

##### LIBRARY VERSIONS

```
bigsuds==1.0.4
f5-sdk==2.3.3
```

##### CONFIGURATION

standard ansible.cfg file.

##### OS / ENVIRONMENT

Ubuntu 16.04TS

##### SUMMARY

On the F5 12.x or higher there is a new feature that allows the F5 to do update/poll checks to F5.  In some use cases the product will be utilized in locations where having this feature on is not desirable, simple modification to the auto-check and auto-phonehome values can be set to 'disabled'.  As default is 'enabled'

```
root@(HOSTNAME)(cfg-sync Standalone)(Active)(/Common)(tmos)# list sys software update 
sys software update {
    auto-check disabled
    auto-phonehome disabled
    check-status failure
    errors 11
    frequency weekly
}
```

##### STEPS TO REPRODUCE

Currently leveraging bigip_command.py playbook to modify this, here is example;
```
---
- name: Software update auto check disabled
  bigip_command:
    commands:
      - 'modify sys software update auto-check {{ sys_autocheck_value }}'
      - 'modify sys software update auto-phonehome {{ sys_autocheck_value }}'
    server: "{{ ansible_host }}"
    user: "{{ username }}"
    password: "{{ password }}"
    validate_certs: "no"
  delegate_to: localhost
```

##### ACTUAL RESULTS

```

```

**Comment by caphrim007** [comment]
@neozoolook i believe this exists today in the bigip_software_update module. doesnt look like we've upstreamed that module yet. Can you have a go at it and lemme know if it has the options you want?

**Comment by neozoolook** [comment]
@caphrim007 will do will test today

**Comment by neozoolook** [comment]
@caphrim007 Looks like there may be an issue, as running different plays works fine, but when calling this module I do get an error;

-vvvv
````
PLAYBOOK: base.yml **********************************************************************************************************************************************************************************************************
1 plays in base.yml

PLAY [single] ***************************************************************************************************************************************************************************************************************
META: ran handlers
Trying secret <ansible.parsing.vault.PromptVaultSecret object at 0x7feccff64dd0> for vault_id=default

TASK [f5base : Software update auto check disabled] *************************************************************************************************************************************************************************
task path: /home/pp2854/dev-vepdg-ansible/ansible-vepdg_fw/roles/f5base/tasks/bigip_software/f5_sys_update_autocheck.yml:2
<localhost> connection transport is rest
Using module file /home/pp2854/dev-vepdg-ansible/ansible-vepdg_fw/library/bigip_software_update.py
<localhost> ESTABLISH LOCAL CONNECTION FOR USER: root
<localhost> EXEC /bin/sh -c '/usr/bin/python && sleep 0'
fatal: [zrdm5afpdg01pdgZZZ -> localhost]: FAILED! => {
    "changed": false, 
    "module_stderr": "/usr/local/lib/python2.7/dist-packages/urllib3/connectionpool.py:858: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings\n  InsecureRequestWarning)\n/usr/local/lib/python2.7/dist-packages/urllib3/connectionpool.py:858: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings\n  InsecureRequestWarning)\n/usr/local/lib/python2.7/dist-packages/urllib3/connectionpool.py:858: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings\n  InsecureRequestWarning)\nTraceback (most recent call last):\n  File \"/tmp/ansible_95upzE/ansible_module_bigip_software_update.py\", line 202, in <module>\n    main()\n  File \"/tmp/ansible_95upzE/ansible_module_bigip_software_update.py\", line 198, in main\n    results = mm.exec_module()\n  File \"/tmp/ansible_95upzE/ansible_module_bigip_software_update.py\", line 127, in exec_module\n    changes = self.changes.to_return()\nTypeError: 'NoneType' object is not callable\n", 
    "module_stdout": "", 
    "msg": "MODULE FAILURE", 
    "rc": 1
}

PLAY RECAP ******************************************************************************************************************************************************************************************************************
zrdm5afpdg01pdgZZZ         : ok=0    changed=0    unreachable=0    failed=1  
```

here is playbook;

```
---
- name: Software update auto check disabled
  bigip_software_update:
    auto_check: "{{ sys_autocheck_value }}"
    state: present
    server: "{{ ansible_host }}"
    user: "{{ username }}"
    password: "{{ password }}"
    validate_certs: "no"
  delegate_to: localhost
```
