### ISSUE TITLE
Add Features to virtual server module (bigip_virtual_server.py )

### ISSUE THREAD

**Issue by vs926p** [F5Networks/f5-ansible#554]
##### ISSUE TYPE

 - Feature Idea
Add the following sub options for this module:
- ~~translate-address disabled/enabled~~ ADDED
- ~~translate-port disabled/enabled~~ ADDED
- ip-protocol tcp/udp/sctp

##### COMPONENT NAME
bigip_virtual_server.py

##### ANSIBLE VERSION

```
2.5
```

##### PYTHON VERSION

```

```

##### BIGIP VERSION

```

```

##### LIBRARY VERSIONS

```

```

##### STEPS TO REPRODUCE

```

```

##### ACTUAL RESULTS

```

```

**Comment by realged13** [comment]
+10 for this.  We would use this quite extensively.

**Comment by neozoolook** [comment]
@vs926p I believe that the last bullet item is automatically supported by leveraging the 'all_profiles:' option in bigip_virtual_server.py.  Example if I pass two profiles one with GTP and another with UDP, the ip-protocol is defaulted to UDP.

```
---
- name: Build {{ untrusted_virt_gtp_v4 }} Virtual Server
  bigip_virtual_server:
    state: present
    name: "{{ untrusted_virt_gtp_v4 }}"
    description: "{{ untrusted_virt_gtp_desc }}"
    destination: "{{ untrusted_virt_gtp_dest_v4 }}"
    source: "{{ untrusted_virt_gtp_source_v4 }}"
    port: "{{ untrusted_virt_gtp_port }}"
    all_profiles:
      - "{{ untrusted_virt_gtp_profile_0 }}"
      - "{{ untrusted_virt_gtp_profile_1 }}"
    enabled_vlans: "{{ untrusted_vlan }}"
    snat: "automap"
    server: "{{ ansible_host }}"
    user: "{{ username }}"
    password: "{{ password }}"
    validate_certs: "no"
  delegate_to: localhost
```

**Comment by caphrim007** [comment]
as @neozoolook the ip protocol is already supported in the `profiles` argument. It is usually implied based on the type of "other" profile you set. For instance, HTTP has a default implied profile of `tcp`

**Comment by neozoolook** [comment]
@caphrim007 agreed with your last statement.  I had other post earlier directed to my peer on this one ask as I don't think it's necessary.

**Comment by realged13** [comment]
Having this issue, I wonder if the documentation could be a little more specific when messing with the Protocol.  What if I don't want to set a `HTTP` profile?  What is the method for me to still make it TCP?

**Comment by caphrim007** [comment]
@realged13 just specify the new list sans `http`

before:
```
profiles:
  - http
  - tcp
```

after:
```
profiles:
  - tcp
```

**Comment by realged13** [comment]
@caphrim007 How would I make it a Performance L4 `Type` and use TCP, without setting a http profile?  I have tried multiple combos, but nothing will stick for me.  If i do the `- tcp` it changes the virtual type to standard.  I would like to do the following:

![image](https://user-images.githubusercontent.com/8713511/35696488-a1c88a38-0755-11e8-997a-f83d6991ba61.png)


```            
profiles:
   - name: fastL4
      context: client-side
    - name: tcp
     context: client-side
```

**Comment by caphrim007** [comment]
@realged13 

```
- name: Add virtual server, FastL4
  bigip_virtual_server:
    profiles:
      - fastL4
    destination: "{{ node_host }}"
    name: "{{ vs_name }}"
    port: "{{ vs_port1 }}"
```
