### ISSUE TITLE
bigip_virtual_server does not allow valid port number of 0 (zero)

### ISSUE THREAD

**Issue by johnatspark1** [F5Networks/f5-ansible#56]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

bigip_virtual_server

##### ANSIBLE VERSION

```
ansible 2.2.0.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/root/library/', '/usr/share/ansible/']

```

##### PYTHON VERSION

```
Python 2.7.5
```

##### BIGIP VERSION

```
Sys::Version
Main Package
  Product     BIG-IP
  Version     12.1.1
  Build       1.0.196
  Edition     Hotfix HF1
  Date        Wed Sep  7 17:48:09 PDT 2016

Hotfix List
ID593355      ID321971-1  ID589318-1  ID604211-3  ID599068-2  ID594910-1
ID585120-1    ID603997    ID513851-2  ID585366    ID589149-2  ID599054-2
ID601938-2    ID608373-2  ID606110-3  ID590074-1  ID575170-2  ID600778-1
ID598294-1    ID595394-2  ID605682-2  ID590608-1  ID596814-5  ID590578-4
ID601927-1    ID595064-1  ID600859-3  ID599033-3  ID527403-1  ID603605-1
ID614599      ID599769    ID606509-3
```

##### OS / ENVIRONMENT

“N/A”
##### SUMMARY

Port 0 (zero) is a valid port number for a virtual server.  It designates "any" port.  
When using a 0 for the port number it fails and gives an error.

The "if" statement at about line 696 ( "if (not destination) or (not port):") should probably check instead that "port" is a number between 0 and 65535.  
"not port" is evaluating to "true" if port is 0

##### STEPS TO REPRODUCE

```
      - name: Add update delete virtual servers
        bigip_virtual_server:
            server: "server1"
            user: "admin"
            password: "password"
            name: "testVS"
            state: "present"
            destination: "1.2.3.4"
            port: "0"

```

##### EXPECTED RESULTS

```
A virtual server to be created with a port of Any.
```
##### ACTUAL RESULTS

```
failed: [10.201.97.32] (item={u'routeadvertisement': u'enabled', u'name': u'testVS', u'partition': u'GEN', u'state': u'present', u'address': u'1.2.3.4', u'port': u'0', u'pool': u'', u'description': u'test VS'}) => {"failed": true, "item": {"address": "1.2.3.4", "description": "test VS", "name": "testVS", "partition": "GEN", "pool": "", "port": "0", "routeadvertisement": "enabled", "state": "present"}, "msg": "both destination and port must be supplied to create a VS"}

```
