### ISSUE TITLE
bigip_virtual_server cannot specifiy all_rules without error: pop from empty list

### ISSUE THREAD

**Issue by johnatspark1** [F5Networks/f5-ansible#57]
##### ISSUE TYPE

 - Bug Report
 
##### COMPONENT NAME

bigip_virtual_server
##### ANSIBLE VERSION

```
ansible 2.2.0.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/root/library/', '/usr/share/ansible/']

```

##### PYTHON VERSION

```
Python 2.7.5
```

##### BIGIP VERSION

```
Sys::Version
Main Package
  Product     BIG-IP
  Version     12.1.1
  Build       1.0.196
  Edition     Hotfix HF1
  Date        Wed Sep  7 17:48:09 PDT 2016

Hotfix List
ID593355      ID321971-1  ID589318-1  ID604211-3  ID599068-2  ID594910-1
ID585120-1    ID603997    ID513851-2  ID585366    ID589149-2  ID599054-2
ID601938-2    ID608373-2  ID606110-3  ID590074-1  ID575170-2  ID600778-1
ID598294-1    ID595394-2  ID605682-2  ID590608-1  ID596814-5  ID590578-4
ID601927-1    ID595064-1  ID600859-3  ID599033-3  ID527403-1  ID603605-1
ID614599      ID599769    ID606509-3
```

##### OS / ENVIRONMENT

N/A
##### SUMMARY

I cannot get it to not produce the error when specifying irules ("all_rules") 
##### STEPS TO REPRODUCE

```
root@localhost playbooks]# ansible-playbook -i hosts test4.yaml

[root@localhost playbooks]# cat test4.yaml
---
# Update the F5 DMZ Device Group
- name: Update F5 DMZ Device Group
  hosts:
     - F5DMZ
  connection: local

  tasks:
      - name: Add update virtual server rules
        bigip_virtual_server:
            server: "10.201.97.33"
            user: "admin"
            password: "ommited"
            name: "testVS"
            partition: "GEN"
            state: "present"
            all_rules:
               - /Common/_sys_https_redirect
               - /Common/_sys_auth_tacacs


```

##### EXPECTED RESULTS

OK
##### ACTUAL RESULTS

```

TASK [Add update virtual server rules] *****************************************
task path: /root/playbooks/test4.yaml:9
Using module file /root/library/bigip_virtual_server.py
<10.201.97.33> ESTABLISH LOCAL CONNECTION FOR USER: root
<10.201.97.33> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo $HOME/.ansible/tmp/ansible-tmp-1482455135.45-62810326986053 `" && echo ansible-tmp-1482455135.45-62810326986053="` echo $HOME/.ansible/tmp/ansible-tmp-1482455135.45-62810326986053 `" ) && sleep 0'
<10.201.97.33> PUT /tmp/tmppin4ZK TO /root/.ansible/tmp/ansible-tmp-1482455135.45-62810326986053/bigip_virtual_server.py
<10.201.97.33> EXEC /bin/sh -c 'chmod u+x /root/.ansible/tmp/ansible-tmp-1482455135.45-62810326986053/ /root/.ansible/tmp/ansible-tmp-1482455135.45-62810326986053/bigip_virtual_server.py && sleep 0'
<10.201.97.33> EXEC /bin/sh -c '/usr/bin/python /root/.ansible/tmp/ansible-tmp-1482455135.45-62810326986053/bigip_virtual_server.py; rm -rf "/root/.ansible/tmp/ansible-tmp-1482455135.45-62810326986053/" > /dev/null 2>&1 && sleep 0'
fatal: [10.201.97.33]: FAILED! => {
    "changed": false,
    "failed": true,
    "invocation": {
        "module_args": {
            "all_profiles": null,
            "all_rules": [
                "/Common/_sys_https_redirect",
                "/Common/_sys_auth_tacacs"
            ],
            "default_persistence_profile": null,
            "description": null,
            "destination": null,
            "enabled_vlans": null,
            "fallback_persistence_profile": null,
            "name": "testVS",
            "partition": "GEN",
            "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "pool": null,
            "port": null,
            "route_advertisement_state": "disabled",
            "server": "10.201.97.33",
            "server_port": 443,
            "snat": null,
            "state": "present",
            "user": "admin",
            "validate_certs": true
        },
        "module_name": "bigip_virtual_server"
    },
    "msg": "received exception: Error on updating Virtual Server : pop from empty list"
}
        to retry, use: --limit @/root/playbooks/test4.retry

PLAY RECAP *********************************************************************
10.201.97.33               : ok=1    changed=0    unreachable=0    failed=1


```
