### ISSUE TITLE
bigip_device_group_member.py giving errors

### ISSUE THREAD

**Issue by payalsin** [F5Networks/f5-ansible#574]
playbook
```
- name: device grp add members
    bigip_device_group_member:
      server: "10.192.73.91"
      user: "admin"
      password: "admin"
      device_group: "grp"
      name: "bigip921.bd.local"
      validate_certs: False
    delegate_to: localhost
```

Error
The full traceback is:
Traceback (most recent call last):
  File "/tmp/ansible_ZltF8B/ansible_module_bigip_device_group_member.py", line 271, in <module>
    main()
  File "/tmp/ansible_ZltF8B/ansible_module_bigip_device_group_member.py", line 262, in main
    results = mm.exec_module()
  File "/tmp/ansible_ZltF8B/ansible_module_bigip_device_group_member.py", line 155, in exec_module
    changed = self.present()
  File "/tmp/ansible_ZltF8B/ansible_module_bigip_device_group_member.py", line 167, in present
    if self.exists():
  File "/tmp/ansible_ZltF8B/ansible_module_bigip_device_group_member.py", line 174, in exists
    exists = self.have.device_group.devices_s.devices.exists(
AttributeError: 'NoneType' object has no attribute 'devices_s'

fatal: [localhost -> localhost]: FAILED! => {
    "attempts": 1,
    "changed": false,
    "module_stderr": "Traceback (most recent call last):\n  File \"/tmp/ansible_ZltF8B/ansible_module_bigip_device_group_member.py\", line 271, in <module>\n    main()\n  File \"/tmp/ansible_ZltF8B/ansible_module_bigip_device_group_member.py\", line 262, in main\n    results = mm.exec_module()\n  File \"/tmp/ansible_ZltF8B/ansible_module_bigip_device_group_member.py\", line 155, in exec_module\n    changed = self.present()\n  File \"/tmp/ansible_ZltF8B/ansible_module_bigip_device_group_member.py\", line 167, in present\n    if self.exists():\n  File \"/tmp/ansible_ZltF8B/ansible_module_bigip_device_group_member.py\", line 174, in exists\n    exists = self.have.device_group.devices_s.devices.exists(\nAttributeError: 'NoneType' object has no attribute 'devices_s'\n",
    "module_stdout": "",
    "msg": "MODULE FAILURE",
    "rc": 1
}
