### ISSUE TITLE
bigip_ssl_certificate not uploading complete filename

### ISSUE THREAD

**Issue by hanej** [F5Networks/f5-ansible#58]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

bigip_ssl_certificate

##### ANSIBLE VERSION

```
ansible 2.2.0.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
```

##### PYTHON VERSION

```
Python 2.7.5
```

##### BIGIP VERSION

```
Sys::Version
Main Package
  Product  BIG-IP
  Version  11.5.2
  Build    0.0.141
  Edition  Final
  Date     Fri Jan 30 14:50:39 PST 2015
```

##### SUMMARY

When specifying cert_content, key_content, cert_src, or key_src the files on the F5 are not getting the .key or .crt appended to the certificate name.  This is resulting in duplicate certs on the F5 from a GUI standpoint and either one cannot be deleted.

##### STEPS TO REPRODUCE

```
---
- name: Prepare F5 for SSL Certificate Upload
  hosts: ltm
  remote_user: ansible
  gather_facts: false

  vars_files:
    - vars/secrets.yml

  tasks:
    # This is needed or the upload fails
    - name: ensure download directory exists
      raw: "mkdir -p /var/config/rest/downloads/tmp/"


- name: Upload SSL Certificates to LTMs
  hosts: ltm
  remote_user: root
  gather_facts: false

  vars_files:
    - vars/secrets.yml

  tasks:
    - name: Import PEM Certificate
      bigip_ssl_certificate:
        name: "wildcard_ftscc_net"
        server: "{{ ansible_host }}"
        user: "{{ f5_user }}"
        password: "{{ f5_password }}"
        state: "present"
        validate_certs: false
        cert_content: "{{ cert content goes here }}"
        key_content: "{{ key content goes here }}"
      delegate_to: "{{ jump_server }}"
```

```
ansible-playbook -i inventory/hosts -e "cert_file=wildcard_ftscc_net.yml" --vault-password-file ~/.vault_password import_ssl_cert.yml
```

##### EXPECTED RESULTS

The existing key that was uploaded via GUI was overwritten with new version.

##### ACTUAL RESULTS

A duplicate key was installed without the file extension resulting in 2 of the same SSL certs visible through the GUI.  The certificates below with the 49524 extension was uploaded through the GUI and is the old version.  The 75278 extension was done through Ansible.  The Ansible version should have overwritten the existing version.

```
[ root@f5 /config/filestore/files_d/Common_d]# find . -name "*ftscc*"
./certificate_key_d/:Common:wildcard_ftscc_net_75278_1
./certificate_key_d/:Common:wildcard_ftscc_net.key_49524_2
./certificate_d/:Common:wildcard_ftscc_net_75276_1
./certificate_d/:Common:wildcard_ftscc_net.crt_49528_2
```
