### ISSUE TITLE
GTM Wide IP Failing FQDN Check

### ISSUE THREAD

**Issue by realged13** [F5Networks/f5-ansible#607]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME
bigip_gtm_wide_ip

##### ANSIBLE VERSION

```
ansible 2.5.0
  config file = /home/e116173@test.com/venv/f5-test/inventories/ansible.cfg
  configured module search path = [u'/home/e116173@test.com/venv/f5-test/inventories/library']
  ansible python module location = /home/e116173@test.com/venv/f5-test/lib/python2.7/site-packages/ansible
  executable location = /home/e116173@test.com/venv/f5-test/bin/ansible
  python version = 2.7.5 (default, Nov  6 2016, 00:28:07) [GCC 4.8.5 20150623 (Red Hat 4.8.5-11)]
```

##### PYTHON VERSION

```
Python 2.7.5

```

##### BIGIP VERSION

```
  Product     BIG-IP
  Version     12.1.2
  Build       2.0.276
  Edition     Hotfix HF2
```

##### LIBRARY VERSIONS

```
bigsuds==1.0.6
f5-sdk==3.0.7
```

##### OS / ENVIRONMENT

CentOS

##### SUMMARY
When trying to create a record (company.org) it fails the FQDN check, however, foo.company.com is acceptable.

##### STEPS TO REPRODUCE

```
---

- name: Create GTM Wide IP servers and add pools to servers.
  hosts: GTM_TEST
  connection: local
  gather_facts: no
  roles:
    - GTM_Core

  tasks:

    - name: Set lb method
      bigip_gtm_wide_ip:
        server: "{{server}}"
        user: "{{un}}"
        password: "{{pw}}"
        validate_certs: "{{nossl}}"
        name: company.org
        type: "a"
        lb_method: round-robin
        pools: 
          - name: company.org
```

##### EXPECTED RESULTS
company.org wide ip to be generate with pool member attached.

##### ACTUAL RESULTS

```
The full traceback is:
  File "/tmp/ansible_guv0tw/ansible_module_bigip_gtm_wide_ip.py", line 688, in main
    results = mm.exec_module()
  File "/tmp/ansible_guv0tw/ansible_module_bigip_gtm_wide_ip.py", line 390, in exec_module
    return manager.exec_module()
  File "/tmp/ansible_guv0tw/ansible_module_bigip_gtm_wide_ip.py", line 447, in exec_module
    changed = self.present()
  File "/tmp/ansible_guv0tw/ansible_module_bigip_gtm_wide_ip.py", line 473, in present
    if self.exists():
  File "/tmp/ansible_guv0tw/ansible_module_bigip_gtm_wide_ip.py", line 577, in exists
    name=self.want.name,
  File "/tmp/ansible_guv0tw/ansible_module_bigip_gtm_wide_ip.py", line 254, in name
    "The provided name must be a valid FQDN"

fatal: [company.org]: FAILED! => {
    "attempts": 1,
    "changed": false,
    "failed": true,
    "invocation": {
        "module_args": {
            "lb_method": "round-robin",
            "name": "company.org",
            "partition": "Common",
            "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "pool_lb_method": "round-robin",
            "pools": [
                {
                    "name": "company.org"
                }
            ],
            "provider": {
                "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
                "server": "10.80.2.210",
                "server_port": 443,
                "ssh_keyfile": null,
                "timeout": 10,
                "transport": "rest",
                "user": "svcf5",
                "validate_certs": false
            },
            "server": "10.80.2.210",
            "server_port": 443,
            "state": "present",
            "transport": "rest",
            "type": "a",
            "user": "svcf5",
            "validate_certs": false
        }
    },
    "msg": "The provided name must be a valid FQDN"
}
```
