### ISSUE TITLE
Enhancement: support raw iControl REST calls similar to Ansible uri module

### ISSUE THREAD

**Issue by chen23** [F5Networks/f5-ansible#608]
##### ISSUE TYPE
 - Feature Idea

##### COMPONENT NAME
new
bigip_icontrol_rest_uri

##### SUMMARY
There should be a module to perform "raw" iControl REST calls with GET, PUT, PATCH, POST.

This would facilitate:

a.) getting raw data from BIG-IP
b.) supporting endpoints that may not have an existing F5 Ansible module

This could be thought of similar to bigip_command, but for low-level iControl REST calls (leaving SOAP out of scope).

##### STEPS TO REPRODUCE

via the Python SDK you would want something like.

```
mgmt = ManagementRoot(bigip_ip, bigip_username, bigip_password, port=bigip_port)
session = mgmt._meta_data['bigip']._meta_data['icr_session']
````
Then you could have an Ansible module with semantics similar to the uri module.
```
- name: Create a chen deployment using iControlLX
  bigip_icontrol_rest_uri:
    url: https://bigip/mgmt/tm/chen/deploy
    method: POST
    user: your_username
    password: your_pass
    body: "{{ lookup('file','deploy.json') }}"
    force_basic_auth: yes
    status_code: 201
    body_format: json
```

##### ACTUAL RESULTS

```

```
