### ISSUE TITLE
bigip_static_route.py - creation of ipv6 default route works on first run, second run results in error

### ISSUE THREAD

**Issue by neozoolook** [F5Networks/f5-ansible#618]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

bigip_static_route.py

##### ANSIBLE VERSION

```
ansible 2.5.0
  config file = /home/pp2854/dev-vepdg-ansible/ansible-vepdg_fw/ansible.cfg
  configured module search path = [u'/home/pp2854/dev-vepdg-ansible/ansible-vepdg_fw/library']
  ansible python module location = /usr/local/lib/python2.7/dist-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 2.7.12 (default, Dec  4 2017, 14:50:18) [GCC 5.4.0 20160609]
```

##### PYTHON VERSION

```
Python 2.7.12
```

##### BIGIP VERSION

```
Sys::Version
Main Package
  Product     BIG-IP
  Version     12.1.2
  Build       0.0.249
  Edition     Final
  Date        Wed Nov 30 16:04:00 PST 2016
```

##### LIBRARY VERSIONS

```
bigsuds==1.0.4
f5-sdk==3.0.10
```

##### OS / ENVIRONMENT

Ubuntu 16.04TS

##### SUMMARY

Playbook setup to build some various static routes, there is a default route for IPv4 and IPv6, these work fine, however if the playbook is ran again after routes exist, the IPv6 play will fail with following error;

FAILED! => {"changed": false, "failed": true, "msg": "The provided destination is not an IP address"}

Module was changed to require netmask values, which is fine, however the examples only show IPv4 examples which leads to some confusion.  In addition there is no clear documentation on setting default route on F5 as this is done differently for v4 and v6.

##### STEPS TO REPRODUCE

```
---
- name: Create IPv4 default route
  bigip_static_route:
#    destination: "default"
    destination: 0.0.0.0
    netmask: 0.0.0.0
    gateway_address: "{{ trusted_route_V4 }}"
    name: "DEFAULT-ROUTE-V4"
    server: "{{ ansible_host }}"
    user: "{{ username }}"
    password: "{{ password }}"
    validate_certs: "no"
    state: "present"
  delegate_to: localhost

- name: Create IPv6 default route
  bigip_static_route:
#    destination: '::/128'
    destination: '::'
    netmask: '::'
    gateway_address: "{{ trusted_route_V6 }}"
    name: "DEFAULT-ROUTE-V6"
    server: "{{ ansible_host }}"
    user: "{{ username }}"
    password: "{{ password }}"
    validate_certs: "no"
  delegate_to: localhost

- name: Create IPv4 jsa route
  bigip_static_route:
    destination: "{{ pool_member_host }}"
    netmask: 32
    gateway_address: "{{ jsa_route_V4 }}"
    name: "JSA-ROUTE-V4"
    server: "{{ ansible_host }}"
    user: "{{ username }}"
    password: "{{ password }}"
    validate_certs: "no"
    state: "present"
  delegate_to: localhost

- name: Create S2B V4 AAP Route
  bigip_static_route:
    destination: "{{ pdg_s2b_v4 }}"
    netmask: 32
    gateway_address: "{{ untrusted_route_V4 }}"
    name: "PDG-S2B-ROUTE-V4"
    server: "{{ ansible_host }}"
    user: "{{ username }}"
    password: "{{ password }}"
    validate_certs: "no"
    state: "present"
  delegate_to: localhost

- name: Create S2B V6 AAP Route
  bigip_static_route:
    destination: "{{ pdg_s2b_v6 }}"
    netmask: 128
    gateway_address: "{{ untrusted_route_V6 }}"
    name: "PDG-S2B-ROUTE-V6"
    server: "{{ ansible_host }}"
    user: "{{ username }}"
    password: "{{ password }}"
    validate_certs: "no"
    state: "present"
  delegate_to: localhost

- name: Create S2B V4 AAP Route
  bigip_static_route:
    destination: "{{ pdg_dns_v4 }}"
    netmask: 32
    gateway_address: "{{ untrusted_route_V4 }}"
    name: "PDG-DNS-ROUTE-V4"
    server: "{{ ansible_host }}"
    user: "{{ username }}"
    password: "{{ password }}"
    validate_certs: "no"
    state: "present"
```

##### EXPECTED RESULTS

Plays work on first initial run when IPv6 default doesn't exist, however on second run will fail with error on just Ipv6 one.  syntax appears to be correct per what the F5 is expecting to receive.

##### ACTUAL RESULTS

```
ansible-playbook 2.5.0vv 
  config file = /home/pp2854/dev-vepdg-ansible/ansible-vepdg_fw/ansible.cfg
  configured module search path = [u'/home/pp2854/dev-vepdg-ansible/ansible-vepdg_fw/library']
  ansible python module location = /usr/local/lib/python2.7/dist-packages/ansible
  executable location = /usr/local/bin/ansible-playbook
  python version = 2.7.12 (default, Dec  4 2017, 14:50:18) [GCC 5.4.0 20160609]
Using /home/pp2854/dev-vepdg-ansible/ansible-vepdg_fw/ansible.cfg as config file
Vault password: 
setting up inventory plugins
Parsed /home/pp2854/dev-vepdg-ansible/ansible-vepdg_fw/hosts inventory source with ini plugin
statically imported: /home/pp2854/dev-vepdg-ansible/ansible-vepdg_fw/roles/f5base/tasks/bigip_template/f5_template.yml
statically imported: /home/pp2854/dev-vepdg-ansible/ansible-vepdg_fw/roles/f5base/tasks/bigip_provision/f5_afm_nominal.yml
statically imported: /home/pp2854/dev-vepdg-ansible/ansible-vepdg_fw/roles/f5base/tasks/bigip_provision/f5_ltm_none.yml
statically imported: /home/pp2854/dev-vepdg-ansible/ansible-vepdg_fw/roles/f5base/tasks/bigip_db/f5_sys_db.yml
statically imported: /home/pp2854/dev-vepdg-ansible/ansible-vepdg_fw/roles/f5base/tasks/bigip_software/f5_sys_update_autocheck.yml
statically imported: /home/pp2854/dev-vepdg-ansible/ansible-vepdg_fw/roles/f5base/tasks/bigip_profile/f5_profile_client_ssl.yml
statically imported: /home/pp2854/dev-vepdg-ansible/ansible-vepdg_fw/roles/f5base/tasks/bigip_profile/f5_profile_server_ssl.yml
statically imported: /home/pp2854/dev-vepdg-ansible/ansible-vepdg_fw/roles/f5base/tasks/bigip_command/f5_cmd_httpd_ciphersuite.yml
statically imported: /home/pp2854/dev-vepdg-ansible/ansible-vepdg_fw/roles/f5base/tasks/bigip_global/f5_sys_global.yml
statically imported: /home/pp2854/dev-vepdg-ansible/ansible-vepdg_fw/roles/f5base/tasks/bigip_hostname/f5_hostname.yml
statically imported: /home/pp2854/dev-vepdg-ansible/ansible-vepdg_fw/roles/f5base/tasks/bigip_sshd/f5_ssh.yml
statically imported: /home/pp2854/dev-vepdg-ansible/ansible-vepdg_fw/roles/f5base/tasks/bigip_httpd/f5_httpd.yml
statically imported: /home/pp2854/dev-vepdg-ansible/ansible-vepdg_fw/roles/f5base/tasks/bigip_snmp_trap/f5_snmp_trap.yml
statically imported: /home/pp2854/dev-vepdg-ansible/ansible-vepdg_fw/roles/f5base/tasks/bigip_snmp/f5_snmp.yml
statically imported: /home/pp2854/dev-vepdg-ansible/ansible-vepdg_fw/roles/f5base/tasks/bigip_command/f5_snmp_extras.yml
statically imported: /home/pp2854/dev-vepdg-ansible/ansible-vepdg_fw/roles/f5base/tasks/bigip_command/f5_mgmt_route.yml
statically imported: /home/pp2854/dev-vepdg-ansible/ansible-vepdg_fw/roles/f5base/tasks/bigip_ntp/f5_ntp.yml
statically imported: /home/pp2854/dev-vepdg-ansible/ansible-vepdg_fw/roles/f5base/tasks/bigip_vlan/f5_vlan.yml
statically imported: /home/pp2854/dev-vepdg-ansible/ansible-vepdg_fw/roles/f5base/tasks/bigip_route/f5_route_remove.yml
statically imported: /home/pp2854/dev-vepdg-ansible/ansible-vepdg_fw/roles/f5base/tasks/bigip_interface/f5_interface.yml
statically imported: /home/pp2854/dev-vepdg-ansible/ansible-vepdg_fw/roles/f5base/tasks/bigip_route/f5_route_add.yml
statically imported: /home/pp2854/dev-vepdg-ansible/ansible-vepdg_fw/roles/f5base/tasks/bigip_monitor/f5_monitor_jsa.yml
statically imported: /home/pp2854/dev-vepdg-ansible/ansible-vepdg_fw/roles/f5base/tasks/bigip_pool/f5_pool_jsa.yml
statically imported: /home/pp2854/dev-vepdg-ansible/ansible-vepdg_fw/roles/f5base/tasks/bigip_command/f5_dest_hsl.yml
statically imported: /home/pp2854/dev-vepdg-ansible/ansible-vepdg_fw/roles/f5base/tasks/bigip_command/f5_dest_sys.yml
statically imported: /home/pp2854/dev-vepdg-ansible/ansible-vepdg_fw/roles/f5base/tasks/bigip_command/f5_pub_sys.yml
statically imported: /home/pp2854/dev-vepdg-ansible/ansible-vepdg_fw/roles/f5base/tasks/bigip_command/f5_log_profile.yml
statically imported: /home/pp2854/dev-vepdg-ansible/ansible-vepdg_fw/roles/f5base/tasks/bigip_command/f5_log_profile_global.yml
statically imported: /home/pp2854/dev-vepdg-ansible/ansible-vepdg_fw/roles/f5base/tasks/bigip_config/f5_config_save.yml
statically imported: /home/pp2854/dev-vepdg-ansible/ansible-vepdg_fw/roles/f5base/tasks/bigip_command/f5_gtac.yml
statically imported: /home/pp2854/dev-vepdg-ansible/ansible-vepdg_fw/roles/f5base/tasks/bigip_net/f5_net_timerpolicy.yml
statically imported: /home/pp2854/dev-vepdg-ansible/ansible-vepdg_fw/roles/f5base/tasks/bigip_net/f5_net_servicepolicy.yml
statically imported: /home/pp2854/dev-vepdg-ansible/ansible-vepdg_fw/roles/f5base/tasks/bigip_afm/f5_afm_portlist.yml
statically imported: /home/pp2854/dev-vepdg-ansible/ansible-vepdg_fw/roles/f5base/tasks/bigip_afm/f5_afm_addresslist.yml
statically imported: /home/pp2854/dev-vepdg-ansible/ansible-vepdg_fw/roles/f5base/tasks/bigip_afm/f5_afm_rulelist_icmp.yml
statically imported: /home/pp2854/dev-vepdg-ansible/ansible-vepdg_fw/roles/f5base/tasks/bigip_afm/f5_afm_rulelist_diameter.yml
statically imported: /home/pp2854/dev-vepdg-ansible/ansible-vepdg_fw/roles/f5base/tasks/bigip_afm/f5_afm_rulelist_dns.yml
statically imported: /home/pp2854/dev-vepdg-ansible/ansible-vepdg_fw/roles/f5base/tasks/bigip_afm/f5_afm_rulelist_gtp_pdg.yml
statically imported: /home/pp2854/dev-vepdg-ansible/ansible-vepdg_fw/roles/f5base/tasks/bigip_afm/f5_afm_rulelist_gtp_pgw.yml
statically imported: /home/pp2854/dev-vepdg-ansible/ansible-vepdg_fw/roles/f5base/tasks/bigip_afm/f5_afm_policy.yml
statically imported: /home/pp2854/dev-vepdg-ansible/ansible-vepdg_fw/roles/f5base/tasks/bigip_irule/f5_irule.yml
statically imported: /home/pp2854/dev-vepdg-ansible/ansible-vepdg_fw/roles/f5base/tasks/bigip_datagroup/f5_ltm_datagroup.yml
statically imported: /home/pp2854/dev-vepdg-ansible/ansible-vepdg_fw/roles/f5base/tasks/bigip_virtual_server/f5_virt_hc_untrust.yml
statically imported: /home/pp2854/dev-vepdg-ansible/ansible-vepdg_fw/roles/f5base/tasks/bigip_virtual_server/f5_virt_hc_trust.yml
statically imported: /home/pp2854/dev-vepdg-ansible/ansible-vepdg_fw/roles/f5base/tasks/bigip_virtual_server/f5_virt_diam_untrust_v6.yml
statically imported: /home/pp2854/dev-vepdg-ansible/ansible-vepdg_fw/roles/f5base/tasks/bigip_virtual_server/f5_virt_diam_untrust_v4.yml
statically imported: /home/pp2854/dev-vepdg-ansible/ansible-vepdg_fw/roles/f5base/tasks/bigip_virtual_server/f5_virt_dns_untrust_v4.yml
statically imported: /home/pp2854/dev-vepdg-ansible/ansible-vepdg_fw/roles/f5base/tasks/bigip_virtual_server/f5_virt_gtp_untrust_v6.yml
statically imported: /home/pp2854/dev-vepdg-ansible/ansible-vepdg_fw/roles/f5base/tasks/bigip_virtual_server/f5_virt_gtp_untrust_v4.yml
statically imported: /home/pp2854/dev-vepdg-ansible/ansible-vepdg_fw/roles/f5base/tasks/bigip_virtual_server/f5_virt_gtp_trust_v6.yml
statically imported: /home/pp2854/dev-vepdg-ansible/ansible-vepdg_fw/roles/f5base/tasks/bigip_virtual_server/f5_virt_gtp_trust_v4.yml
statically imported: /home/pp2854/dev-vepdg-ansible/ansible-vepdg_fw/roles/f5base/tasks/bigip_virtual_server/f5_virt_catch_untrust_v4.yml
statically imported: /home/pp2854/dev-vepdg-ansible/ansible-vepdg_fw/roles/f5base/tasks/bigip_virtual_server/f5_virt_catch_trust_v4.yml
statically imported: /home/pp2854/dev-vepdg-ansible/ansible-vepdg_fw/roles/f5base/tasks/bigip_virtual_server/f5_virt_catch_untrust_v6.yml
statically imported: /home/pp2854/dev-vepdg-ansible/ansible-vepdg_fw/roles/f5base/tasks/bigip_virtual_server/f5_virt_catch_trust_v6.yml
statically imported: /home/pp2854/dev-vepdg-ansible/ansible-vepdg_fw/roles/f5base/tasks/bigip_afm/f5_afm_apply_policy.yml
statically imported: /home/pp2854/dev-vepdg-ansible/ansible-vepdg_fw/roles/f5base/tasks/bigip_command/f5_gtac_apply.yml
statically imported: /home/pp2854/dev-vepdg-ansible/ansible-vepdg_fw/roles/f5base/tasks/bigip_config/f5_config_save.yml
Loading callback plugin default of type stdout, v2.0 from /usr/local/lib/python2.7/dist-packages/ansible/plugins/callback/default.pyc

PLAYBOOK: base.yml ************************************************************************************************************
1 plays in base.yml

PLAY [single] *****************************************************************************************************************
META: ran handlers
Trying secret <ansible.parsing.vault.PromptVaultSecret object at 0x7f09d7571750> for vault_id=default

TASK [f5base : Create IPv4 default route] *************************************************************************************
task path: /home/pp2854/dev-vepdg-ansible/ansible-vepdg_fw/roles/f5base/tasks/bigip_route/f5_route_add.yml:2
<localhost> connection transport is rest
Using module file /home/pp2854/dev-vepdg-ansible/ansible-vepdg_fw/library/bigip_static_route.py
<localhost> ESTABLISH LOCAL CONNECTION FOR USER: root
<localhost> EXEC /bin/sh -c '/usr/bin/python && sleep 0'
ok: [zrdm5afpdg01pdgZZZ -> localhost] => {
    "changed": false, 
    "failed": false, 
    "invocation": {
        "module_args": {
            "description": null, 
            "destination": "0.0.0.0", 
            "gateway_address": "166.209.66.1", 
            "mtu": null, 
            "name": "DEFAULT-ROUTE-V4", 
            "netmask": "0.0.0.0", 
            "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER", 
            "pool": null, 
            "provider": {
                "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER", 
                "server": "192.168.116.101", 
                "server_port": 443, 
                "ssh_keyfile": null, 
                "timeout": 10, 
                "transport": "rest", 
                "user": "admin", 
                "validate_certs": false
            }, 
            "reject": null, 
            "route_domain": null, 
            "server": "192.168.116.101", 
            "server_port": 443, 
            "state": "present", 
            "transport": "rest", 
            "user": "admin", 
            "validate_certs": false, 
            "vlan": null
        }
    }
}

TASK [f5base : Create IPv6 default route] *************************************************************************************
task path: /home/pp2854/dev-vepdg-ansible/ansible-vepdg_fw/roles/f5base/tasks/bigip_route/f5_route_add.yml:16
<localhost> connection transport is rest
Using module file /home/pp2854/dev-vepdg-ansible/ansible-vepdg_fw/library/bigip_static_route.py
<localhost> ESTABLISH LOCAL CONNECTION FOR USER: root
<localhost> EXEC /bin/sh -c '/usr/bin/python && sleep 0'
The full traceback is:
  File "/tmp/ansible_oAVHIo/ansible_module_bigip_static_route.py", line 603, in main
    results = mm.exec_module()
  File "/tmp/ansible_oAVHIo/ansible_module_bigip_static_route.py", line 439, in exec_module
    changed = self.present()
  File "/tmp/ansible_oAVHIo/ansible_module_bigip_static_route.py", line 470, in present
    return self.update()
  File "/tmp/ansible_oAVHIo/ansible_module_bigip_static_route.py", line 502, in update
    if not self.should_update():
  File "/tmp/ansible_oAVHIo/ansible_module_bigip_static_route.py", line 495, in should_update
    result = self._update_changed_options()
  File "/tmp/ansible_oAVHIo/ansible_module_bigip_static_route.py", line 419, in _update_changed_options
    change = diff.compare(k)
  File "/tmp/ansible_oAVHIo/ansible_module_bigip_static_route.py", line 353, in compare
    result = getattr(self, param)
  File "/tmp/ansible_oAVHIo/ansible_module_bigip_static_route.py", line 371, in destination
    if self.want.destination_ip != self.have.destination_ip:
  File "/tmp/ansible_oAVHIo/ansible_module_bigip_static_route.py", line 325, in destination_ip
    "The provided destination is not an IP address"
fatal: [zrdm5afpdg01pdgZZZ -> localhost]: FAILED! => {
    "changed": false, 
    "failed": true, 
    "invocation": {
        "module_args": {
            "description": null, 
            "destination": "::", 
            "gateway_address": "2606:ae00:2e10:100::1", 
            "mtu": null, 
            "name": "DEFAULT-ROUTE-V6", 
            "netmask": "::", 
            "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER", 
            "pool": null, 
            "provider": {
                "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER", 
                "server": "192.168.116.101", 
                "server_port": 443, 
                "ssh_keyfile": null, 
                "timeout": 10, 
                "transport": "rest", 
                "user": "admin", 
                "validate_certs": false
            }, 
            "reject": null, 
            "route_domain": null, 
            "server": "192.168.116.101", 
            "server_port": 443, 
            "state": "present", 
            "transport": "rest", 
            "user": "admin", 
            "validate_certs": false, 
            "vlan": null
        }
    }, 
    "msg": "The provided destination is not an IP address"
}

PLAY RECAP ********************************************************************************************************************
zrdm5afpdg01pdgZZZ         : ok=1    changed=0    unreachable=0    failed=1  
```
