### ISSUE TITLE
New Module - Net Service Policy - Leverages Timer Policy See #621 AFM USE CASE

### ISSUE THREAD

**Issue by neozoolook** [F5Networks/f5-ansible#622]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

New Module Request

##### ANSIBLE VERSION

```
Target 2.6 if possible
```

##### PYTHON VERSION

```

```

##### BIGIP VERSION

```

```

##### LIBRARY VERSIONS

```

```

##### STEPS TO REPRODUCE

Below are examples on how we support this today with bigip_command.py module.  The service policy calls a timer policy, so would be ideal to support two modules for this more than likely, see other request under #621 

```
---
- name: Check For Timer-Policy Existence
  bigip_command:
    commands:
      - list net service-policy {{ item.name }}
    server: "{{ ansible_host }}"
    user: "{{ username }}"
    password: "{{ password }}"
    validate_certs: "no"
  register: result_net
  delegate_to: localhost
  with_items: "{{ service_policy }}"

- name: Create For Rule-List
  bigip_command:
    commands:
      - create net service-policy {{ item.name }} timer-policy {{ item.policy }}
    server: "{{ ansible_host }}"
    user: "{{ username }}"
    password: "{{ password }}"
    validate_certs: "no"
  when:
    - '"was not found" in result_net.results[ item.index ].stdout|first'
  delegate_to: localhost
  with_items: "{{ service_policy }}"

```

##### ACTUAL RESULTS

```

```
