### ISSUE TITLE
bigip_security_address_list.py - Modification to support CIDR in IP/Variable Pass

### ISSUE THREAD

**Issue by neozoolook** [F5Networks/f5-ansible#623]
##### ISSUE TYPE

 - Feature Idea

##### COMPONENT NAME

bigip_security_address_list.py

##### ANSIBLE VERSION

```
ansible 2.5.0
  config file = /home/pp2854/dev-vepdg-ansible/ansible-vepdg_fw/ansible.cfg
  configured module search path = [u'/home/pp2854/dev-vepdg-ansible/ansible-vepdg_fw/library']
  ansible python module location = /usr/local/lib/python2.7/dist-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 2.7.12 (default, Dec  4 2017, 14:50:18) [GCC 5.4.0 20160609]
```

##### PYTHON VERSION

```
Python 2.7.12
```

##### BIGIP VERSION

```
Sys::Version
Main Package
  Product     BIG-IP
  Version     12.1.2
  Build       0.0.249
  Edition     Final
  Date        Wed Nov 30 16:04:00 PST 2016
```

##### LIBRARY VERSIONS

```
bigsuds==1.0.4
f5-sdk==3.0.10
```

##### CONFIGURATION

Standard entries in Ansible.cfg

##### OS / ENVIRONMENT

Ubuntu 16.04TS

##### SUMMARY

bigip_security_address_list.py works fine, however when adding addresses as variables it will only allow you to enter them as single IP hosts.  In TMSH command line you also have the option of adding an address with CIDR notation at the end to indicate range as well.  Suggest that the module also support either option in entry.

```
Example Variables;
address_list:
  - index: 0
    name: SWm-V6
    description: 'Covers Diameter on Untrusted Net'
    address: '2606:ae00:2e11:107::4/128'
  - index: 1
    name: DNS-V4
    description: 'Covers DNS Range on Untrusted Net'
    address: '166.201.84.0/27'
```

##### STEPS TO REPRODUCE

```
---
- name: Create Address-List
  bigip_security_address_list:
    description: "{{ item.description }}"
    name: "{{ item.name }}"
    addresses: "{{ item.address }}"
    server: "{{ ansible_host }}"
    user: "{{ username }}"
    password: "{{ password }}"
    validate_certs: "no"
  delegate_to: localhost
  with_items: "{{ address_list }}"

```

##### ACTUAL RESULTS

```

```
