### ISSUE TITLE
[DOC] bigip_command result variable in the examples

### ISSUE THREAD

**Issue by alonsocamaro** [F5Networks/f5-ansible#625]
##### ISSUE TYPE
 - Documentation Report

##### COMPONENT NAME
 bigip_command

##### ANSIBLE VERSION

Ansible Tower 3.1.5

```
(ansible)[root@rhel74-1-ucamaro vcpe]# ansible --version
ansible 2.4.0.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, May  3 2017, 07:55:04) [GCC 4.8.5 20150623 (Red Hat 4.8.5-14)]
```

##### SUMMARY

The doc page http://docs.ansible.com/ansible/latest/bigip_command_module.html contains examples that uses a variable called "result", ie:

```
- name: run show version and check to see if output contains BIG-IP
  bigip_command:
    commands: show sys version
    wait_for: result[0] contains BIG-IP
    server: "lb.mydomain.com"
    password: "secret"
    user: "admin"
    validate_certs: "no"
  delegate_to: localhost
```

But this variable is not documented in the bigip_command page
