### ISSUE TITLE
New Module: Add support for 'auth tacacs', 'auth remote-role' & 'auth source type tacacs'

### ISSUE THREAD

**Issue by neozoolook** [F5Networks/f5-ansible#627]
##### ISSUE TYPE

 - Feature Idea

##### COMPONENT NAME

New Module/s suggested

##### ANSIBLE VERSION

```
Target 2.6 release if possible
```

##### PYTHON VERSION

```

```

##### BIGIP VERSION

```

```

##### LIBRARY VERSIONS

```

```

##### SUMMARY

Portions of the configuration that we leverage bigip_command.py to complete to support authentication of the F5 with TACACS;

```
auth tacacs system-auth {
    authentication use-all-servers
    protocol ip
    secret $XXXXXXXXXXXXXXXXXXXX==
    servers { 10.10.10.10:49163 10.10.10.11:49163 }
    service ppp
}
```
```
auth source {
    type tacacs
}
```

**COMPLETE**
```
auth remote-role {
    role-info {
        AUDITOR {
            attribute F5-LTM-User-Info-1=Auditor
            console %F5-LTM-User-Shell
            line-order 1020
            role %F5-LTM-User-Role
            user-partition %F5-LTM-User-Partition
        }
        FIREWALLMGR {
            attribute F5-LTM-User-Info-1=firewall-manager
            console %F5-LTM-User-Shell
            line-order 1030
            role %F5-LTM-User-Role
            user-partition %F5-LTM-User-Partition
        }
        FULL-ACCESS {
            attribute F5-LTM-User-Info-1=Administrator
            console %F5-LTM-User-Shell
            line-order 1050
            role %F5-LTM-User-Role
            user-partition %F5-LTM-User-Partition
        }
    }
}
```

##### STEPS TO REPRODUCE

Current playbook examples of how this is done with bigip_command.py.

```
---
- name: Add configurations for TACACS Support
  bigip_command:
    commands:
      - create auth tacacs system-auth authentication use-all-servers protocol ip secret XXXXX servers add { {{ tac_serv_1 }} {{ tac_serv_2 }} } service ppp
      - modify auth remote-role role-info add { AUDITOR { attribute F5-LTM-User-Info-1=Auditor console %F5-LTM-User-Shell line-order 1020 role %F5-LTM-User-Role user-partition %F5-LTM-User-Partition } }
      - modify auth remote-role role-info add { FIREWALLMGR { attribute F5-LTM-User-Info-1=firewall-manager console %F5-LTM-User-Shell line-order 1030 role %F5-LTM-User-Role user-partition %F5-LTM-User-Partition } }
      - modify auth remote-role role-info add { FULL-ACCESS { attribute F5-LTM-User-Info-1=Administrator console %F5-LTM-User-Shell line-order 1050 role %F5-LTM-User-Role user-partition %F5-LTM-User-Partition } }
    server: "{{ ansible_host }}"
    user: "{{ username }}"
    password: "{{ password }}"
    validate_certs: "no"
  delegate_to: localhost


---
- name: Apply TACACS as Auth method on F5
  bigip_command:
    commands:
      - modify auth source type tacacs
    server: "{{ ansible_host }}"
    user: "{{ username }}"
    password: "{{ password }}"
    validate_certs: "no"
  delegate_to: localhost
```

##### ACTUAL RESULTS

```

```
