### ISSUE TITLE
Request an option to update the password for F5_USER when config is reset

### ISSUE THREAD

**Issue by yappie452** [F5Networks/f5-ansible#631]
##### ISSUE TYPE
 - Feature Idea

##### COMPONENT NAME
bigip_config

##### ANSIBLE VERSION
```
ansible 2.5.0
  config file = /Users/reifel/Documents/Sources/ansible/ansible_bigip_lab/ansible.cfg
  configured module search path = [u'/Users/reifel/Documents/Sources/ansible/ansible_bigip_lab/library']
  ansible python module location = /Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/ansible
  executable location = /Library/Frameworks/Python.framework/Versions/2.7/bin/ansible
  python version = 2.7.11 (v2.7.11:6d1b6a68f775, Dec  5 2015, 12:54:16) [GCC 4.2.1 (Apple Inc. build 5666) (dot 3)]

```

##### PYTHON VERSION
```
Python 2.7.11
```

##### BIGIP VERSION
```
Sys::Version
Main Package
  Product     BIG-IP
  Version     13.1.0
  Build       0.0.1868
  Edition     Final
  Date        Fri Nov 10 17:27:22 PST 2017
```

##### LIBRARY VERSIONS
```
bigsuds==1.0.6
f5-sdk==3.0.6
```

##### CONFIGURATION
```
inventory = ${PWD}/inventory/hosts
```

##### OS / ENVIRONMENT
```
Darwin xxxxxxl 17.4.0 Darwin Kernel Version 17.4.0: Sun Dec 17 09:19:54 PST 2017; root:xnu-4570.41.2~1/RELEASE_X86_64 x86_64
```

##### SUMMARY
Currently, if you are using an admin password other than the default password, then this play will reset the password back to the default:

```
- name: Reset the BIG-IP
  bigip_config:
    reset: yes
    save: True
  delegate_to: localhost
```

The next task **must** be a password change to your inventory password, or your task will fail because it can't authenticate.

Could the bigip_config module have a parameter called restore_password_after_reset=Yes|No (default Yes) that sets the password to whatever you have set for F5_PASSWORD?

##### STEPS TO REPRODUCE
```
- name: Reset the BIG-IP
  bigip_config:
    reset: yes
    restore_password_after_reset: yes
    save: True
  delegate_to: localhost
```

##### EXPECTED RESULTS
bigip_config reset will automatically fix up your password by default

##### ACTUAL RESULTS
after bigip_config reset you'll need to run another play to set up the admin password.

**Comment by caphrim007** [comment]
I believe the appropriate method to accomplish what you need to do would look like this

```
- name: Reset the BIG-IP
  bigip_config:
    reset: yes
    save: True
  register: r

- name: Change password back
  bigip_user:
    user: admin
    password: default
    username_credential: admin
    password_credential: NewPassword
  when: r is changed
```

I will acknowledge that this is a separate task, however it keeps the module responsibilities clear without mucking the internal implementation of the code.

My recommendation would be that if this is something that you need to do frequently, or want to make it behave like you requested, then a role is the prudent solution.

A user created role such as "reset-config" could accept a parameter as you have mentioned (`restore_password_after_reset`) and run the associated bigip_user module if it is `yes` and there was a change registered by bigip_config.

Does this make sense? If not, lemme know.
