### ISSUE TITLE
"MAC Masquerade Address" in traffic groups

### ISSUE THREAD

**Issue by preisbeck** [F5Networks/f5-ansible#643]
##### ISSUE TYPE

 - Feature Idea

##### COMPONENT NAME

bigip_traffic_group

##### ANSIBLE VERSION

```
ansible 2.5.0b2 (stable-2.5 21b74f7cce) last updated 2018/02/20 10:57:15 (GMT +200)
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/preisbeck/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /home/preisbeck/git/ansible/lib/ansible
  executable location = /home/preisbeck/git/ansible/bin/ansible
  python version = 2.7.12 (default, Dec  4 2017, 14:50:18) [GCC 5.4.0 20160609]
```

##### PYTHON VERSION

```
Python 2.7.12
```

##### BIGIP VERSION

```
Sys::Version
Main Package
  Product     BIG-IP
  Version     12.1.2
  Build       0.0.249
  Edition     Final
  Date        Wed Nov 30 16:04:00 PST 2016
```

##### LIBRARY VERSIONS

```
bigsuds==1.0.6
f5-sdk==3.0.8
```

##### OS / ENVIRONMENT

16.04.1-Ubuntu

##### SUMMARY

The current implementation of the traffic group plugin doesn't allow configuration of the "MAC Masquerade Address" setting. This results in a manual step that's necessary after the Ansible configuration is done, a quit cumbersome one if you defined many traffic groups.
It would be nice to have an additional parameter to define the "MAC Masquerade Address" during the Ansible run.

```
- name: Create a traffic group
  bigip_traffic_group:
    name: foo
    password: secret
    server: lb.mydomain.com
    state: present
    user: admin
    macma: 00:00:00:00:00:01
  delegate_to: localhost
```
