### ISSUE TITLE
Data Group - Skip if Present

### ISSUE THREAD

**Issue by realged13** [F5Networks/f5-ansible#652]
##### ISSUE TYPE

 - Feature Idea

##### COMPONENT NAME
bigip_data_group.py

##### ANSIBLE VERSION

```
2.5
```

##### PYTHON VERSION

```

```

##### BIGIP VERSION

```
12.1.2 HF2
```

##### LIBRARY VERSIONS

```

```

##### CONFIGURATION

None

##### OS / ENVIRONMENT

Centos 7

##### SUMMARY
 
Currently the data group model will overwrite any current existing data if there are duplicates.  I would like for there to be an option to only update data if the data does not currently exist.

##### EXPECTED RESULTS

When the following is true, skip the record unless a "force override" choice is selected.

```
stringName1 := result
2 := result
3 := result
4:= result
stringName1 := result | Skip this line since it was already included.
```

##### ACTUAL RESULTS

```

```

**Comment by caphrim007** [comment]
@realged13 explain the logic behind wanting to include duplicates?

**Comment by realged13** [comment]
I do not want to include duplicates.

Here is my playbook:

```
---

- name: Add Google Auth information to data group list.
  hosts: DEVGTM
  connection: local
  gather_facts: no
  roles:
    - GTM-Special

  tasks:
     - name: Edit a data group with new strings.
       bigip_data_group:
         server: "{{ server }}"
         user: "{{ un }}"
         password: "{{ pw }}"
         validate_certs: no
         name: google_auth_keys
         type: string
         state: present
         internal: yes
         records_src: "./google_auth_list/ga_list.txt"
```
Here is my `records_src:` file:

```
helloworld := GRFGEVZXHFYH2VKX
ted := MFNFQ3JMGZVWS23D
booboo := N4XH2TJXGMZUOVB4
.....
helloworld := abcdefg12345678
```
If I was to run this playbook, it would put the first iteration of `helloworld` into the data group list.  If someone on my team accidentally creates `helloworld` account again, it would append it to the end of my file and when the playbook ran again, it would overwrite the data already entered and would break this persons google authenticator.

The only way I could counter this would be to enter this stuff into a database and verify that record doesn't already exist, but management wants to go ahead and get this going and work on that part later.

So what I would like, is when I run the playbook, if that username already exists, skip it.  I guess I could also append to a host or group var but would like to not do that if possible.
