### ISSUE TITLE
Need new module to configure GTM global settings

### ISSUE THREAD

**Issue by WRJFontenot** [F5Networks/f5-ansible#657]
##### ISSUE TYPE

 - Feature Idea
 
##### COMPONENT NAME

bigip_gtm_global
##### ANSIBLE VERSION

```
ansible 2.4.2.0
```

##### PYTHON VERSION

```
Python 2.7.5
```

##### BIGIP VERSION

```
Sys::Version
Main Package
  Product     BIG-IP
  Version     13.0.0
  Build       2.0.1671
  Edition     Hotfix HF2
  Date        Fri Apr 28 20:36:43 PDT 2017

```

##### LIBRARY VERSIONS

```
bigsuds==1.0.6
f5-sdk==3.0.9
```

##### OS / ENVIRONMENT

CentOS Linux release 7.4.1708 (Core)

##### SUMMARY

Need to enable GTM synchronization, set GTM Sync Group name, and synchronize zone files.  There is not a module that can configure GTM global settings.  Can only be done using bigip_command module and TMSH commands.
##### STEPS TO REPRODUCE

```
    - name: Configure GSLB General Settings
      bigip_command:
        commands:
          - modify gtm global-settings general synchronization yes
          - modify gtm global-settings general synchronization-group-name {{ gtm_sync_group }}
          - modify gtm global-settings general synchronize-zone-files yes
```

##### ACTUAL RESULTS

```

```
