### ISSUE TITLE
bigip_snmp_community: will not remove "public"

### ISSUE THREAD

**Issue by webminster** [F5Networks/f5-ansible#659]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
bigip_snmp_community

##### ANSIBLE VERSION
```
ansible 2.4.3.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/sparksa/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.12 (default, Dec  4 2017, 14:50:18) [GCC 5.4.0 20160609]
```

##### PYTHON VERSION
```
Python 2.7.12
```

##### BIGIP VERSION
```
BIG-IP 13.1.0.2 Build 0.0.6 Point Release 2
```

##### LIBRARY VERSIONS

```
bigsuds==1.0.6
f5-sdk==3.0.12
```

##### CONFIGURATION
None

##### OS / ENVIRONMENT
Linux ubuntu1 4.4.0-91-generic #114-Ubuntu SMP Tue Aug 8 11:56:56 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
Ubuntu Xenial

##### SUMMARY
Trying to remove default "public" community from BIG-IP instance fails silently.   Module reports OK but community remains on device.

##### STEPS TO REPRODUCE
```
  environment:
    F5_SERVER: "{{ ansible_ssh_host }}"
    F5_USER: "{{ bigip_user }}"
    F5_SERVER_PORT: "{{ bigip_port }}"
    F5_PASSWORD: "{{ bigip_password }}"
    F5_VALIDATE_CERTS: False

  tasks:
  - name: Remove public community
    delegate_to: localhost
    bigip_snmp_community:
      state: absent
      community: public

```

##### EXPECTED RESULTS
"public" community no longer in access list on BIG-IP instance.

##### ACTUAL RESULTS
"public" community still on BIG-IP instance, no change.

```
TASK [cluster : Remove public community] ***************************************
ok: [i-09f4b6d23296a99cf -> localhost]

```
