### ISSUE TITLE
bigip_license

### ISSUE THREAD

**Issue by motokof5** [F5Networks/f5-ansible#66]
##### ISSUE TYPE

 - Bug Report
 - Feature Idea
 - Documentation Report

##### ANSIBLE VERSION

```
2.2
```

##### PYTHON VERSION

```
2.7
```

##### BIGIP VERSION

```
11.6/12.0/12.1
```

##### SUMMARY

Dose anyone use "bigip_license"? I tried to use it, but syntax error was displayed. I appreciate it if someone shares a successful playbook.

##### STEPS TO REPRODUCE

```
- name: BIG-IP test play
  hosts: 10.100.35.160
  connection: ssh

  tasks:
    - name: License BIG-IP specifying license options
      bigip_license:
        server: "10.100.35.160"
        user: "admin"
        password: "admin"
        key: "XXXXX-XXXXX-XXXXX-XXXXX-XXXXXXX"
      delegate_to: localhost
```

##### ACTUAL RESULTS

```
ERROR! no action detected in task. This often indicates a misspelled module name, or incorrect module path.

The error appears to have been in '/home/f5/license.yaml': line 6, column 9, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:

  tasks:
      - name: License BIG-IP specifying license options
        ^ here


The error appears to have been in '/home/f5/license.yaml': line 6, column 9, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:

  tasks:
      - name: License BIG-IP specifying license options
        ^ here
```
