### ISSUE TITLE
Question about LTM profiles

### ISSUE THREAD

**Issue by MichalTaratuta** [F5Networks/f5-ansible#673]
Sorry for the blunt question.

Is it possible to create LTM profiles using one of the existing modules? I can't see it anywhere and just wonder of this is achievable through different module or it just missing and scheduled for next release?

**Comment by caphrim007** [comment]
@MichalTaratuta you can use the bigip_command module to create them until such time as there are full-fledged modules to do so

**Comment by MichalTaratuta** [comment]
@caphrim007 I tried to use the bigip_command from Ansible TAG v2.5.0rc3 but it seems to be missing your latest commit c0046c8. Which is a game chnager for that command. Do you know whether c0046c8 will make to Ansible 2.5 ?

**Comment by caphrim007** [comment]
@MichalTaratuta no, 2.5 is feature frozen. that commit will be in 2.6.

Why do you need that commit? Its use case is for limited situations.

**Comment by MichalTaratuta** [comment]
I thought that it introduces the `chdir` feature to `bigip_command` module? 

Is there a way to create an LTM profile using `bigip_command` module for specific partition other then Common ?

I did try this:
```yaml
bigip_command:
    commands:
      - cd ../kitkat
      - create ltm profile http BOB header-erase Accept-Encoding insert-xforwarded-for enabled redirect-rewrite matching
    server: 192.168.1.210
    password: admin
    user: admin
```

But unfortunately it doesn't change the partition. 😞
