### ISSUE TITLE
no action detected in task

### ISSUE THREAD

**Issue by lisahuang** [F5Networks/f5-ansible#68]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME
task

##### ANSIBLE VERSION

```
ansible 2.3.0
  config file = /Users/502639594/Documents/work/f5/f5_ansible/src/ansible.cfg
  configured module search path = [u'/Users/lisa.huang/Documents/work/f5/f5_ansible/env/lib/python2.7', u'library']
```

##### PYTHON VERSION

```
Python 2.7.10
```

##### BIGIP VERSION

```
Sys::Version
Main Package
  Product     BIG-IP
  Version     12.1.0
  Build       0.0.1434
  Edition     Final
  Date        Wed May 11 11:45:11 PDT 2016
```

##### CONFIGURATION

N/A
##### OS / ENVIRONMENT

mac
##### STEPS TO REPRODUCE

```
- name: Show system version
  strategy: debug
  hosts: sandbox
  vars:
      ansible_python_interpreter: "/Users/lisa.huang/Documents/work/f5/f5_ansible/env_ansible/bin/python"
  connection: ssh
  gather_facts: False

  vars:
      cli:
        host: "{{ sandbox }}"
        username: lisa.huang
        password: password
        transport: cli

  tasks:
    - name: run show version on remote devices
      bigip_command:
        commands: show sys version
        provider: "{{ cli }}"
```

##### EXPECTED RESULTS

Able to run the playbook and show sys version

##### ACTUAL RESULTS

```
I couldn't find bigip_command in the version followed 
pip install git+git://github.com/ansible/ansible.git@devel

Where should I get the modules?

(env_ansible)$ ansible-playbook site.yaml -i ../hosts -u lisa.huang
 [WARNING]: While constructing a mapping from /Users/502639594/Documents/work/f5/f5_ansible/src/site.yaml, line 1, column 3, found a duplicate dict key (vars). Using last defined value only.

ERROR! no action detected in task. This often indicates a misspelled module name, or incorrect module path.

The error appears to have been in '/Users/lisa.huang/Documents/work/f5/f5_ansible/src/site.yaml': line 17, column 7, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:

  tasks:
    - name: run show version on remote devices
      ^ here


The error appears to have been in '/Users/lisa.huang/Documents/work/f5/f5_ansible/src/site.yaml': line 17, column 7, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:

  tasks:
    - name: run show version on remote devices
      ^ here
```
