### ISSUE TITLE
New module for "Remote Role Groups"

### ISSUE THREAD

**Issue by preisbeck** [F5Networks/f5-ansible#680]
##### ISSUE TYPE

 - Feature Idea

##### COMPONENT NAME

bigip_remote_role_groups

##### ANSIBLE VERSION

```
ansible 2.6.0 (devel 6ad784bbbb) last updated 2018/03/22 15:50:46 (GMT +200)
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/preisbeck/github/f5-ansible/library']
  ansible python module location = /home/preisbeck/git/ansible/lib/ansible
  executable location = /home/preisbeck/git/ansible/bin/ansible
  python version = 2.7.12 (default, Dec  4 2017, 14:50:18) [GCC 5.4.0 20160609]

```

##### PYTHON VERSION

```
Python 2.7.12
```

##### BIGIP VERSION

```
Sys::Version
Main Package
  Product     BIG-IP
  Version     12.1.3
  Build       0.5.378
  Edition     Engineering Hotfix
  Date        Thu Dec 21 13:44:52 PST 2017

Hotfix List
ID653772-2    ID686029-1  ID669415-1
```

##### LIBRARY VERSIONS

```
bigsuds==1.0.6
f5-sdk==3.0.13
```

##### OS / ENVIRONMENT

16.04.1-Ubuntu

##### SUMMARY

We use the "Remote Role Groups" feature of our BigIps quiet heavily, all user management is done in our ldap, and it would be nice to be able to configure them with Ansible as well.

```
- name: Create a remote role groups
  bigip_remote_role_group:
    user: admin
    password: secret
    server: lb.mydomain.com
    state: present
    group_name: ldap_group
    line_order: 1
    attribute_string: memberOf=cn=ldap_group,cn=ldap.group,ou=ldap
    remote_access: enabled
    assigned_role: administrator
    partition_access: all
    treminal_access: disabled
  delegate_to: localhost
```
