### ISSUE TITLE
"MODULE FAILURE" error while executing playbook

### ISSUE THREAD

**Issue by AnilBabuDasari** [F5Networks/f5-ansible#681]
##### ISSUE TYPE

- Issue

##### COMPONENT NAME

BIGIP
##### ANSIBLE VERSION

```
ansible 2.4.2.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, Aug  4 2017, 00:39:18) [GCC 4.8.5 20150623 (Red Hat 4.8.5-16)]

```

##### PYTHON VERSION

```
python version = 2.7.5
```

##### BIGIP VERSION

```
Main Package
  Product     BIG-IP
  Version     12.1.2
  Build       0.0.249

```

##### LIBRARY VERSIONS

```
bigsuds==1.0.6
f5-sdk==3.0.13

```

##### CONFIGURATION

No
##### OS / ENVIRONMENT

CentOS Linux release 7.2.1511 
##### STEPS TO REPRODUCE

Run below playbook

```
- name: This is my play
  hosts: 192.168.99.35
  tasks:
      - name: This is a task
        bigip_command:
           server: "192.168.99.35"
           user: "root"
           password: "mypassword"
           commands:
            tmsh show sys version
           #delegate_to: localhost
```

##### EXPECTED RESULTS

tmsh show sys version

Sys::Version
Main Package
  Product     BIG-IP
  Version     12.1.2
  Build       0.0.249
  Edition     Final
  Date        Wed Nov 30 16:04:00 PST 2016

##### ACTUAL RESULTS

```
this is only error details
fatal: [192.168.99.35]: FAILED! => {
    "changed": false,
    "module_stderr": "OpenSSH_7.4p1, OpenSSL 1.0.2k-fips  26 Jan 2017\r\ndebug1: Reading 
configuration data /etc/ssh/ssh_config\r\ndebug1: /etc/ssh/ssh_config line 58: Applying options for 
*\r\ndebug1: auto-mux: Trying existing master\r\ndebug2: fd 3 setting O_NONBLOCK\r\ndebug2: 
mux_client_hello_exchange: master version 4\r\ndebug3: mux_client_forwards: request forwardings: 0 
local, 0 remote\r\ndebug3: mux_client_request_session: entering\r\ndebug3: mux_client_request_alive: 
entering\r\ndebug3: mux_client_request_alive: done pid = 3688\r\ndebug3: 
mux_client_request_session: session request sent\r\ndebug1: mux_client_request_session: master 
session id: 2\r\ndebug3: mux_client_read_packet: read header failed: Broken pipe\r\ndebug2: Received 
exit status from master 0\r\nShared connection to 192.168.99.35 closed.\r\n",
    "module_stdout": "Traceback (most recent call last):\r\n  File 
\"/tmp/ansible_Fh90Kn/ansible_module_bigip_command.py\", line 174, in <module>\r\n    from 
ansible.module_utils.f5_utils import iControlUnexpectedHTTPError\r\nImportError: cannot import name 
iControlUnexpectedHTTPError\r\n",
    "msg": "MODULE FAILURE",
    "rc": 0
}
        to retry, use: --limit @/etc/ansible/playbook/f5_basic1.retry

PLAY RECAP *************************************************************************************************************************************************************
192.168.99.35              : ok=1    changed=0    unreachable=0    failed=1


```

**Comment by caphrim007** [comment]
@AnilBabuDasari you must use either a `connection: local` in your play or a `delegate_to: localhost` in your task.

**Comment by caphrim007** [comment]
@AnilBabuDasari additionally, would you provide your Ansible details as asked in the issue template

**Comment by AnilBabuDasari** [comment]
Hi Caphrim,
Thankyou for your reply and updated the Ansible version as requested in the issue template.
Ive used both connection: local and delegate_to: localhost but still the same issue.

**Comment by caphrim007** [comment]
@AnilBabuDasari is it the exact same error when you include delegation or connection local?

**Comment by caphrim007** [comment]
@AnilBabuDasari did you install the f5-sdk via `pip` or some other method

**Comment by AnilBabuDasari** [comment]
@caphrim007 its via pip... 
command : pip install f5-sdk ... the below packages were installed

============
Requirement already satisfied: f5-sdk in /usr/lib/python2.7/site-packages
Requirement already satisfied: six<2.0.0 in /usr/lib/python2.7/site-packages (from f5-sdk)
Requirement already satisfied: f5-icontrol-rest<2.0.0 in /usr/lib/python2.7/site-packages (from f5-sdk)
Requirement already satisfied: requests<3,>=2.5.0 in /usr/lib/python2.7/site-packages (from f5-icontrol-rest<2.0.0->f5-sdk)
Requirement already satisfied: urllib3 in /usr/lib/python2.7/site-packages (from f5-icontrol-rest<2.0.0->f5-sdk)
Requirement already satisfied: certifi>=2017.4.17 in /usr/lib/python2.7/site-packages (from requests<3,>=2.5.0->f5-icontrol-rest<2.0.0->f5-sdk)
Requirement already satisfied: chardet<3.1.0,>=3.0.2 in /usr/lib/python2.7/site-packages (from requests<3,>=2.5.0->f5-icontrol-rest<2.0.0->f5-sdk)
Requirement already satisfied: idna<2.7,>=2.5 in /usr/lib/python2.7/site-packages (from requests<3,>=2.5.0->f5-icontrol-rest<2.0.0->f5-sdk)

**Comment by caphrim007** [comment]
@AnilBabuDasari can you show me your task with delegation included?

**Comment by AnilBabuDasari** [comment]
@caphrim007 , Below is the task 
playbook]# date
Wed Mar 28 10:52:33 IST 2018
[root@avx-cent-99-15 playbook]# cat f5_basic1.yml
- name: This is my play
  hosts: 192.168.99.35

  tasks:
      - name: This is a task
        bigip_command:
           server: "192.168.99.35"
           user: "root"
           password: "mypassword"
           commands:
            tmsh show sys version
           delegate_to: localhost

**Comment by caphrim007** [comment]
@AnilBabuDasari your task is incorrect, `delegate_to: localhost` is indented to far. It should be as shown below.

```
- name: This is my play
  hosts: 192.168.99.35

  tasks:
      - name: This is a task
        bigip_command:
           server: "192.168.99.35"
           user: "root"
           password: "mypassword"
           commands:
             - tmsh show sys version
        delegate_to: localhost
```

Additionally, you should not be using the `root` user account unless you truly want to do SSH authentication to the remote device. By default, we do not do this. To do this, you need to add `transport: cli` to your task.

For SSH, the task would look like this

```
- name: This is my play
  hosts: 192.168.99.35

  tasks:
      - name: This is a task
        bigip_command:
           server: "192.168.99.35"
           user: "root"
           password: "mypassword"
           commands:
             - tmsh show sys version
           transport: cli
        delegate_to: localhost
```
