### ISSUE TITLE
bigip_routedomain module not assigning route domains to vlans

### ISSUE THREAD

**Issue by mlowcher61** [F5Networks/f5-ansible#693]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

bigip_routedomain

##### ANSIBLE VERSION

```
ansible 2.6.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/usr/share/ansible']
  ansible python module location = /usr/local/lib/python2.7/dist-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 2.7.6 (default, Jun 22 2015, 18:00:18) [GCC 4.8.2]
```

##### PYTHON VERSION

```
Python 2.7.6
```

##### BIGIP VERSION

```
Sys::Version
Main Package
  Product     BIG-IP
  Version     12.1.1
  Build       0.0.184
  Edition     Final
  Date        Thu Aug 11 17:09:01 PDT 2016

```

##### LIBRARY VERSIONS

```
bigsuds==1.0.6
f5-sdk==3.0.12

```

##### CONFIGURATION

inventory      = /etc/ansible/hosts
library        = /usr/share/ansible

##### OS / ENVIRONMENT

Ubuntu 16.04
##### SUMMARY

I am creating route domains, vlans and self ips in a playbook. My variables are in a separate vars file. After creating the vlans, I run the  bigip_routedomain module to create the needed route-domains. I then run the module again to set the vlans to the proper route domains. This is failing. All vlans are still in route domain 0

##### STEPS TO REPRODUCE

```
Here is my playbook
---

#      Copyright (c) 2017 F5 Networks
#      All rights reserved.
#
#      author: Mark Lowcher F5 Networks
#      short_description: Playbook for creating route domains,
#      vlans and selfips. Use the appropriate vars file.

- name: Starting the Layer 2 Network Config
  hosts: bigip
  gather_facts: false
  vars_files:
    - ./files/Forward_proxy_vars.yml
#    - ./files/Reverse_proxy_vars.yml
#    - ./files/Inbound_email_vars.yml
#    - ./files/template_for_network_config.yml

  tasks:

  - name: Configuring VLANs on bigip1
    bigip_vlan:
     server: "{{bigip1}}"
     user: "{{username}}"
     password: "{{password}}"
     validate_certs: False
     name: "{{item.name}}"
     tag: "{{item.tag}}"
     tagged_interface: "{{item.interface}}"
    with_items: "{{ vlan_information }}"
    delegate_to: localhost

  - name: Configuring VLANs on bigip2
    bigip_vlan:
     server: "{{bigip2}}"
     user: "{{username}}"
     password: "{{password}}"
     validate_certs: False
     name: "{{item.name}}"
     tag: "{{item.tag}}"
     tagged_interface: "{{item.interface}}"
    with_items: "{{ vlan_information }}"
    delegate_to: localhost

  - name: Configuring VLANs on bigip2
    bigip_vlan:
     server: "{{bigip2}}"
     user: "{{username}}"
     password: "{{password}}"
     validate_certs: False
     name: "{{item.name}}"
     tag: "{{item.tag}}"
     tagged_interface: "{{item.interface}}"
    with_items: "{{ vlan_information }}"
    delegate_to: localhost

  - name: Creating the route domains on bigip1
    bigip_routedomain:
     name: "{{item.name}}"
     id: "{{item.id}}"
     user: "{{username}}"
     password: "{{password}}"
     validate_certs: False
     server: "{{ bigip1 }}"
     state: "present"
    with_items: "{{ routedomain_information }}"
    delegate_to: localhost
  - name: Creating the route domains on bigip2
    bigip_routedomain:
     name: "{{item.name}}"
     id: "{{item.id}}"
     user: "{{username}}"
     password: "{{password}}"
     validate_certs: False
     server: "{{bigip2}}"
     state: "present"
    with_items: "{{ routedomain_information }}"
    delegate_to: localhost

  - name: Setting the VLANs on the route domains for bigip1
    bigip_routedomain:
     name: rd1
     id: "{{item.id}}"
     user: "{{username}}"
     password: "{{password}}"
     validate_certs: False
     server: "{{bigip1}}"
     state: "present"
     vlans:
        - 'to_SSLV1_Decrypt_101'
        - 'to_SSLV2_Decrypt_121'
    with_items: "{{ routedomain_information }}"
    delegate_to: localhost

  - name: Setting the VLANs on the route domains for bigip2
    bigip_routedomain:
     name: "{{item.name}}"
     id: "{{item.id}}"
     user: "{{username}}"
     password: "{{password}}"
     validate_certs: False
     server: "{{bigip2}}"
     state: "present"
     vlans:
         - "{{item.name}}"
    with_items: "{{ routedomain_information }}"
    delegate_to: localhost


  - name: Configuring static SELF-IPs on bigip1
    bigip_selfip:
     server: "{{bigip1}}"
     user: "{{username}}"
     password: "{{password}}"
     validate_certs: False
     name: "{{item.name}}"
     address: "{{item.address_static}}"
     netmask: "{{item.netmask}}"
     route_domain: "{{item.id}}"
     traffic_group: "{{item.traffic_group}}"
     vlan: "{{item.vlan}}"
     allow_service: "{{item.static_allow_service}}"
    with_items: "{{ selfip_information_1 }}"
    delegate_to: localhost

  - name: Configuring static SELF-IPs on bigip2
    bigip_selfip:
     server: "{{bigip2}}"
     user: "{{username}}"
     password: "{{password}}"
     validate_certs: False
     name: "{{item.name}}"
     address: "{{item.address_static}}"
     netmask: "{{item.netmask}}"
     route_domain: "{{item.id}}"
     traffic_group: "{{item.traffic_group}}"
     vlan: "{{item.vlan}}"
     allow_service: "{{item.static_allow_service}}"
    with_items: "{{ selfip_information_2 }}"
    delegate_to: localhost

  - name: Configuring floating SELF-IPs on bigip1
    bigip_selfip:
     server: "{{ bigip1 }}"
     user: "{{username}}"
     password: "{{password}}"
     validate_certs: False
     name: "{{item.name}}"
     address: "{{item.address_float}}"
     netmask: "{{item.netmask}}"
     route_domain: "{{item.id}}"
     traffic_group: "{{item.traffic_group}}"
     vlan: "{{item.vlan}}"
     allow_service: "{{item.float_allow_service}}"
    with_items: "{{ selfip_information_float }}"
    delegate_to: localhost
  - name: Configuring floating SELF-IPs on bigip2
    bigip_selfip:
     server: "{{ bigip2 }}"
     user: "{{username}}"
     password: "{{password}}"
     validate_certs: False
     name: "{{item.name}}"
     address: "{{item.address_float}}"
     netmask: "{{item.netmask}}"
     route_domain: "{{item.id}}"
     traffic_group: "{{item.traffic_group}}"
     vlan: "{{item.vlan}}"
     allow_service: "{{item.float_allow_service}}"
    with_items: "{{ selfip_information_float }}"
    delegate_to: localhost

This is my vars file:

username: admin
password: Agility1

bigip1: 10.1.0.20
bigip2: 10.1.0.21
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
routedomain_information:

  - name: 'rd1'
    id: '1'
    vlans:
     - 'to_SSLV1_Decrypt_101'
     - 'to_SSLV2_Decrypt_121'

  - name: 'rd2'
    id: '2'
    vlans:
     - 'to_Forward_proxy_400'

vlan_information:
#FORWARD PROXY
 - name: 'for_vips_10'
   tag: '10'
   interface: '1.1'
   id: '0'

 - name: 'to_SSLV1_Decrypt_101'
   tag: '101'
   interface: '1.2'
   id: '1'

 - name: 'to_SSLV2_Decrypt_121'
   tag: '121'
   interface: '1.2'
   id: '1'

 - name: 'from_SSLV1_Reencrypt_120'
   tag: '120'
   interface: '1.1'
   id: '0'

 - name: 'from_SSLV2_Reencrypt_124'
   tag: '124'
   interface: '1.1'
   id: '0'

 - name: 'to_Forward_proxy_400'
   tag: '400'
   interface: '1.1'
   id: '2'
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
selfip_information_1:
#FORWARD PROXY
 - name: 'for_vips_10-SelfIP'
   address_static: '10.187.5.28'
   netmask: '255.255.255.224'
   vlan: 'for_vips_10'
   traffic_group: 'traffic-group-local-only'
   id: '0'
   static_allow_service: 'none'

 - name: 'to_SSLV1_Decrypt_101-SelfIP'
   address_static: '172.26.252.145'
   netmask: '255.255.255.248'
   vlan: 'to_SSLV1_Decrypt_101'
   traffic_group: 'traffic-group-local-only'
   id: '1'
   static_allow_service: 'none'

 - name: 'to_SSLV1_Decrypt_121-SelfIP'
   address_static: '172.26.252.177'
   netmask: '255.255.255.248'
   vlan: 'to_SSLV1_Decrypt_121'
   traffic_group: 'traffic-group-local-only'
   id: '1'
   static_allow_service: 'none'

 - name: 'from_SSLV1_Reencrypt_120-SelfIP'
   address_static: '172.26.252.148'
   netmask: '255.255.255.248'
   vlan: 'from_SSLV1_Reencrypt_120'
   traffic_group: 'traffic-group-local-only'
   id: '0'
   static_allow_service: 'none'

 - name: 'from_SSLV2_Reencrypt_124-SelfIP'
   address_static: '172.26.252.180'
   netmask: '255.255.255.248'
   vlan: 'from_SSLV2_Reencrypt_124'
   traffic_group: 'traffic-group-local-only'
   id: '0'
   static_allow_service: 'none'
 - name: 'to_Forward_proxy_400-SelfIP'
   address_static: '10.187.6.28'
   netmask: '255.255.255.248'
   vlan: 'to_Forward_proxy_400'
   traffic_group: 'traffic-group-local-only'
   id: '2'
   static_allow_service: 'none'
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
selfip_information_2:
#FORWARD PROXY
 - name: 'for_vips_10-SelfIP'
   address_static: '10.187.5.29'
   netmask: '255.255.255.224'
   vlan: 'for_vips_10'
   traffic_group: 'traffic-group-local-only'
   id: '0'
   static_allow_service: 'none'

 - name: 'to_SSLV1_Decrypt_101-SelfIP'
   address_static: '172.26.252.146'
   netmask: '255.255.255.248'
   vlan: 'to_SSLV1_Decrypt_101'
   traffic_group: 'traffic-group-local-only'
   id: '1'
   static_allow_service: 'none'

 - name: 'to_SSLV1_Decrypt_121-SelfIP'
   address_static: '172.26.252.178'
   netmask: '255.255.255.248'
   vlan: 'to_SSLV1_Decrypt_121'
   traffic_group: 'traffic-group-local-only'
   id: '1'
   static_allow_service: 'none'
 - name: 'from_SSLV1_Reencrypt_120-SelfIP'
   address_static: '172.26.252.149'
   netmask: '255.255.255.248'
   vlan: 'from_SSLV1_Reencrypt_120'
   traffic_group: 'traffic-group-local-only'
   id: '0'
   static_allow_service: 'none'

 - name: 'from_SSLV2_Reencrypt_124-SelfIP'
   address_static: '172.26.252.181'
   netmask: '255.255.255.248'
   vlan: 'from_SSLV2_Reencrypt_124'
   traffic_group: 'traffic-group-local-only'
   id: '0'
   static_allow_service: 'none'

 - name: 'to_Forward_proxy_400-SelfIP'
   address_static: '10.187.6.29'
   netmask: '255.255.255.248'
   vlan: 'to_Forward_proxy_400'
   traffic_group: 'traffic-group-local-only'
   id: '2'
   static_allow_service: 'none'
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
selfip_information_float:
#FORWARD PROXY
 - name: 'for_vips_10-SelfIP_float'
   address_float: '10.187.5.30'
   netmask: '255.255.255.0'
   vlan: 'vlan30'
   traffic_group: 'traffic-group-1'
   id: '0'
   float_allow_service: 'none'
 - name: 'to_SSLV1_Decrypt_101-SelfIP_float'
   address_float: '172.26.252.147'
   netmask: '255.255.255.248'
   vlan: 'to_SSLV1_Decrypt_101'
   traffic_group: 'traffic-group-1'
   id: '1'
   float_allow_service: 'none'

 - name: 'to_SSLV1_Decrypt_121-SelfIP_float'
   address_float: '172.26.252.179'
   netmask: '255.255.255.248'
   vlan: 'to_SSLV1_Decrypt_121'
   traffic_group: 'traffic-group-1'
   id: '1'
   float_allow_service: 'none'

 - name: 'from_SSLV1_Reencrypt_120-SelfIP_float'
   address_float: '172.26.252.150'
   netmask: '255.255.255.248'
   vlan: 'from_SSLV1_Reencrypt_120'
   traffic_group: 'traffic-group-1'
   id: '0'
   float_allow_service: 'none'

 - name: 'from_SSLV2_Reencrypt_124-SelfIP_float'
   address_float: '172.26.252.182'
   netmask: '255.255.255.248'
   vlan: 'from_SSLV2_Reencrypt_124'
   traffic_group: 'traffic-group-1'
   id: '0'
   float_allow_service: 'none'
 - name: 'to_Forward_proxy_400-SelfIP_float'
   address_float: '10.187.6.1'
   netmask: '255.255.255.248'
   vlan: 'to_Forward_proxy_400'
   traffic_group: 'traffic-group-1'
   id: '2'
   float_allow_service: 'none'


```

##### EXPECTED RESULTS

I expected two of the vlans to be assigned to rd1 and one vlan to be assigned to rd2 and the rest left in route domain 0.

##### ACTUAL RESULTS

All vlans remain in route domain 0

```
The full traceback is:
  File "/tmp/ansible_i8O66h/ansible_module_bigip_routedomain.py", line 572, in main
    result = obj.exec_module()
  File "/tmp/ansible_i8O66h/ansible_module_bigip_routedomain.py", line 528, in exec_module
    changed = self.present()
  File "/tmp/ansible_i8O66h/ansible_module_bigip_routedomain.py", line 254, in present
    return self.update()
  File "/tmp/ansible_i8O66h/ansible_module_bigip_routedomain.py", line 511, in update
    raise F5ModuleError(e)

failed: [10.1.0.20 -> localhost] (item={u'vlans': [u'to_SSLV1_Decrypt_101', u'to_SSLV2_Decrypt_121'], u'name': u'rd1', u'id': u'1'}) => {
    "changed": false,
    "invocation": {
        "module_args": {
            "bwc_policy": null,
            "connection_limit": null,
            "description": null,
            "flow_eviction_policy": null,
            "id": 1,
            "name": "rd1",
            "parent": null,
            "partition": "Common",
            "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "provider": {
                "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
                "server": "10.1.0.20",
                "server_port": 443,
                "ssh_keyfile": null,
                "timeout": 10,
                "transport": "rest",
                "user": "admin",
                "validate_certs": false
            },
            "routing_protocol": null,
            "server": "10.1.0.20",
            "server_port": 443,
            "service_policy": null,
            "state": "present",
            "strict": null,
            "transport": "rest",
            "user": "admin",
            "validate_certs": false,
            "vlans": [
                "rd1"
            ]
        }
    },
    "item": {
        "id": "1",
        "name": "rd1",
        "vlans": [
            "to_SSLV1_Decrypt_101",
            "to_SSLV2_Decrypt_121"
        ]
    },
    "msg": "400 Unexpected Error: Bad Request for uri: https://10.1.0.20:443/mgmt/tm/net/route-domain/~Common~rd1/\nText: u'{\"code\":400,\"message\":\"01070277:3: The requested vlan, vlangroup or tunnel (/Common/rd1) was not found.\",\"errorStack\":[],\"apiError\":3}'"
}

I am putting the name of the route-domain as "name" in the bigip_routedomain module. It looks like it is considering that as the vlan name instead. Based on the trace back error message
```
