### ISSUE TITLE
bigip_virtual_server NOT idempotent 

### ISSUE THREAD

**Issue by MichalTaratuta** [F5Networks/f5-ansible#702]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

bigip_virtual_server

##### ANSIBLE VERSION

```
ansible 2.5.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/etc/ansible/modules']
  ansible python module location = /usr/local/lib/python2.7/dist-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 2.7.12 (default, Nov 19 2016, 06:48:10) [GCC 5.4.0 20160609]

```

##### PYTHON VERSION

```
Python 2.7.12
```

##### BIGIP VERSION

```
Sys::Version
Main Package
  Product     BIG-IP
  Version     13.1.0.1
  Build       0.0.8
  Edition     Point Release 1
  Date        Mon Dec 11 18:03:30 PST 2017

```

##### LIBRARY VERSIONS

```
bigsuds==1.0.6
f5-sdk==3.0.11

```

##### OS / ENVIRONMENT

Ubuntu 16.04

##### SUMMARY

Module is not idempotent thus returning `"changed": true` on every run whether it has changed or not.

##### STEPS TO REPRODUCE

Run the play more then once

```
- name: Add virtual server |  lab_pool
  bigip_virtual_server:
    server: "{{server}}"
    user: "{{user}}"
    password: "{{password}}"
    partition: "{{partition}}"
    state: present
    name: lab_pool
    destination: 10.3.3.3
    port: 80
    description: Banana?
    validate_certs: false
  delegate_to: localhost
```

##### EXPECTED RESULTS

If there was not change to the resource then ansible module should return `"changed": false`

##### ACTUAL RESULTS

On every run ansible returns status `"changed": true`  eventhough there was no changes to this resource.

```
"changed": true,
```
