### ISSUE TITLE
bigip_pool_member used to add a Poolmember to the Pool brakes using Provider

### ISSUE THREAD

**Issue by j-wiesmann** [F5Networks/f5-ansible#703]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME
bigip_pool_member

##### ANSIBLE VERSION
ansible 2.5.0
  config file = None
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python2.7/dist-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 2.7.12 (default, Dec  4 2017, 14:50:18) [GCC 5.4.0 20160609]

##### PYTHON VERSION

```
Python 2.7.12

```

##### BIGIP VERSION

```
13.1.0.1
```

##### LIBRARY VERSIONS

```
bigsuds==1.0.6
f5-sdk==3.0.14

```

##### SUMMARY

I tried to use ansible using provider Settings.
It works well to create a pool a node aso, but it fails when using bigip_pool_member to add it to a pool.

This works:
```
- name: Add_first_node_to_pool
    bigip_pool_member:
        password: "{{F5_PASSWORD}}"
        pool: "{{poolname}}"
        port: "{{member_port}}" 
        server: "{{F5_SERVER}}"
        user: "{{F5_USER}}"
        state: "present"
        validate_certs: "no"
        host: "{{node1}}"
        name: "{{node1name}}"
    delegate_to: localhost
```
This fails:
```
  - name: Add second node to pool
    bigip_pool_member:
        provider: "{{provider}}"
        pool: "{{poolname}}"
        port: "{{member_port}}"
       state: "present"
        host: "{{node2}}"
        name: "{{node2name}}"
    delegate_to: localhost
```

##### STEPS TO REPRODUCE
```
TASK [Add_first_node_to_pool] *************************************************************************************************************
task path: /home/f5admin/ansible/playbooks/error_create_ssl_redirect_vip.yml:64
Using module file /usr/local/lib/python2.7/dist-packages/ansible/modules/network/f5/bigip_pool_member.py
<localhost> ESTABLISH LOCAL CONNECTION FOR USER: root
<localhost> EXEC /bin/sh -c 'echo ~ && sleep 0'
<localhost> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /root/.ansible/tmp/ansible-tmp-1523378449.55-216610666891002 `" && echo ansible-tmp-1523378449.55-216610666891002="` echo /root/.ansible/tmp/ansible-tmp-1523378449.55-216610666891002 `" ) && sleep 0'
<localhost> PUT /root/.ansible/tmp/ansible-local-18786yZDdvy/tmpBJYnIl TO /root/.ansible/tmp/ansible-tmp-1523378449.55-216610666891002/bigip_pool_member.py
<localhost> EXEC /bin/sh -c 'chmod u+x /root/.ansible/tmp/ansible-tmp-1523378449.55-216610666891002/ /root/.ansible/tmp/ansible-tmp-1523378449.55-216610666891002/bigip_pool_member.py && sleep 0'
<localhost> EXEC /bin/sh -c '/usr/bin/python /root/.ansible/tmp/ansible-tmp-1523378449.55-216610666891002/bigip_pool_member.py && sleep 0'
<localhost> EXEC /bin/sh -c 'rm -f -r /root/.ansible/tmp/ansible-tmp-1523378449.55-216610666891002/ > /dev/null 2>&1 && sleep 0'
The full traceback is:
  File "/tmp/ansible_4uX9RC/ansible_module_bigip_pool_member.py", line 467, in main
    if not pool_exists(api, pool):
  File "/tmp/ansible_4uX9RC/ansible_module_bigip_pool_member.py", line 211, in pool_exists
    api.LocalLB.Pool.get_object_status(pool_names=[pool])
  File "/usr/local/lib/python2.7/dist-packages/bigsuds.py", line 379, in __getattr__
    client = self._client_creator('%s.%s' % (self._name, attr))
  File "/usr/local/lib/python2.7/dist-packages/bigsuds.py", line 189, in _create_client
    raise ConnectionError(str(e))

fatal: [bigip.f5demo.com -> localhost]: FAILED! => {
    "changed": false,
    "invocation": {
        "module_args": {
            "connection_limit": null,
            "description": null,
            "host": "www104",
            "monitor_state": null,
            "name": "www104",
            "partition": "Common",
            "password": null,
            "pool": "web_pool",
            "port": 8410,
            "preserve_node": false,
            "priority_group": null,
            "provider": {
                "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
                "server": "bigip.f5demo.com",
                "server_port": 443,
                "ssh_keyfile": null,
                "timeout": 10,
                "transport": "rest",
                "user": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
                "validate_certs": false
            },
            "rate_limit": null,
            "ratio": null,
            "server": null,
            "server_port": 443,
            "session_state": null,
            "state": "present",
            "transport": "rest",
            "user": null,
            "validate_certs": null
        }
    },
    "msg": "received exception: <urlopen error [Errno -2] Name or service not known>"
}
```

```
---
- name: Create a VIP, pool, members and nodes
  hosts: bigip.f5demo.com
  connection: local
  gather_facts: no
  vars:
    lb_method: "round-robin"
    poolname: "web_pool"
    monitor: "http"
    monitor_type: "and_list"
    http_profile: "http"
    node1: "192.168.50.104"
    node2: "192.168.50.105"
    node1name: "www104"
    node2name: "www105"
    vipname: "my_vip"
    vipname_redir: "my_vip_redir"
    member_port: "8410"
    vip_ip: "192.168.30.189"
    vip_port_http: "80"
    vip_port_https: "443"
    clientssl: "clientssl"
    http_redirect: "my_redirect"
    F5_SERVER: "bigip.f5demo.com"
    F5_SERVER_PORT: "443"
    F5_USER: "admin"
    F5_PASSWORD: "admin"
    F5_VALIDATE_CERTS: "no"

    provider:
       server: "{{F5_SERVER}}"
       server_port: "{{F5_SERVER_PORT}}"
       password: "{{F5_PASSWORD}}"
       user: "{{F5_USER}}"
       validate_certs: "{{F5_VALIDATE_CERTS}}"

  tasks:
  - name: Create node1
    bigip_node:
        provider: "{{provider}}"
        host: "{{node1}}"
        name: "{{node1name}}"
        state: "present"
    delegate_to: localhost

  - name: Create node2
    bigip_node:
        provider: "{{provider}}"
        host: "{{node2}}"
        name: "{{node2name}}"
        state: "present"
    delegate_to: localhost

  - name: Create a pool
    bigip_pool:
        provider: "{{provider}}"
        lb_method: "{{lb_method}}"
#       monitors: "{{monitor}}" monitor_type: "{{monitor_type}}"
        name: "{{poolname}}"
        slow_ramp_time: "120"
        state: "present"
    delegate_to: localhost

  - name: Add_first_node_to_pool
    bigip_pool_member:
        provider: "{{provider}}"
        pool: "{{poolname}}"
        port: "{{member_port}}"
        state: "present"
        host: "{{node1}}"
        name: "{{node1name}}"
    delegate_to: localhost

  - name: Add second node to pool
    bigip_pool_member:
        provider: "{{provider}}"
        pool: "{{poolname}}"
        port: "{{member_port}}"
        state: "present"
        host: "{{node2}}"
        name: "{{node2name}}"
    delegate_to: localhost

  - name: Create a VIP
    bigip_virtual_server:
        provider: "{{provider}}"
        description: "{{vipname}}"
        destination: "{{vip_ip}}"
        name: "{{vipname}}"
        pool: "{{poolname}}"
        port: "{{vip_port_https}}"
        snat: "Automap"
        state: "present"
        all_profiles:
            - "{{http_profile}}"
            - "{{clientssl}}"
    delegate_to: localhost

  - name: Create a redirect virtual server
    bigip_virtual_server:
        provider: "{{provider}}"
        description: "{{vipname_redir}}"
        name: "{{http_redirect}}"
        destination: "{{vip_ip}}"
        port: "{{vip_port_http}}"
        all_profiles:
            - "http"
        all_rules:
            - _sys_https_redirect
        validate_certs: "no"
    delegate_to: localhost

```

##### EXPECTED RESULTS

I expected that the 2 Nodes get added to the pool. using the legacy setting of Server, User, and Password works.

##### ACTUAL RESULTS

```
TASK [Add_first_node_to_pool] *************************************************************************************************************
task path: /home/f5admin/ansible/playbooks/error_create_ssl_redirect_vip.yml:64
Using module file /usr/local/lib/python2.7/dist-packages/ansible/modules/network/f5/bigip_pool_member.py
<localhost> ESTABLISH LOCAL CONNECTION FOR USER: root
<localhost> EXEC /bin/sh -c 'echo ~ && sleep 0'
<localhost> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /root/.ansible/tmp/ansible-tmp-1523378449.55-216610666891002 `" && echo ansible-tmp-1523378449.55-216610666891002="` echo /root/.ansible/tmp/ansible-tmp-1523378449.55-216610666891002 `" ) && sleep 0'
<localhost> PUT /root/.ansible/tmp/ansible-local-18786yZDdvy/tmpBJYnIl TO /root/.ansible/tmp/ansible-tmp-1523378449.55-216610666891002/bigip_pool_member.py
<localhost> EXEC /bin/sh -c 'chmod u+x /root/.ansible/tmp/ansible-tmp-1523378449.55-216610666891002/ /root/.ansible/tmp/ansible-tmp-1523378449.55-216610666891002/bigip_pool_member.py && sleep 0'
<localhost> EXEC /bin/sh -c '/usr/bin/python /root/.ansible/tmp/ansible-tmp-1523378449.55-216610666891002/bigip_pool_member.py && sleep 0'
<localhost> EXEC /bin/sh -c 'rm -f -r /root/.ansible/tmp/ansible-tmp-1523378449.55-216610666891002/ > /dev/null 2>&1 && sleep 0'
The full traceback is:
  File "/tmp/ansible_4uX9RC/ansible_module_bigip_pool_member.py", line 467, in main
    if not pool_exists(api, pool):
  File "/tmp/ansible_4uX9RC/ansible_module_bigip_pool_member.py", line 211, in pool_exists
    api.LocalLB.Pool.get_object_status(pool_names=[pool])
  File "/usr/local/lib/python2.7/dist-packages/bigsuds.py", line 379, in __getattr__
    client = self._client_creator('%s.%s' % (self._name, attr))
  File "/usr/local/lib/python2.7/dist-packages/bigsuds.py", line 189, in _create_client
    raise ConnectionError(str(e))

fatal: [bigip.f5demo.com -> localhost]: FAILED! => {
    "changed": false,
    "invocation": {
        "module_args": {
            "connection_limit": null,
            "description": null,
            "host": "www104",
            "monitor_state": null,
            "name": "www104",
            "partition": "Common",
            "password": null,
            "pool": "web_pool",
            "port": 8410,
            "preserve_node": false,
            "priority_group": null,
            "provider": {
                "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
                "server": "bigip.f5demo.com",
                "server_port": 443,
                "ssh_keyfile": null,
                "timeout": 10,
                "transport": "rest",
                "user": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
                "validate_certs": false
            },
            "rate_limit": null,
            "ratio": null,
            "server": null,
            "server_port": 443,
            "session_state": null,
            "state": "present",
            "transport": "rest",
            "user": null,
            "validate_certs": null
        }
    },
    "msg": "received exception: <urlopen error [Errno -2] Name or service not known>"
}
        to retry, use: --limit @/home/f5admin/ansible/playbooks/error_create_ssl_redirect_vip.retry

PLAY RECAP ********************************************************************************************************************************
bigip.f5demo.com           : ok=3    changed=0    unreachable=0    failed=1
```

```

```
