### ISSUE TITLE
DNS: [MINOR] bigip_gtm_virtual_server doesn't allow empty translation_port

### ISSUE THREAD

**Issue by alonsocamaro** [F5Networks/f5-ansible#718]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME

bigip_gtm_virtual_server
##### ANSIBLE VERSION

```
[root@ansible-tower-32 Openshift-F5-Setup-multiapp]# ansible --version
ansible 2.5.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, Feb 20 2018, 09:19:12) [GCC 4.8.5 20150623 (Red Hat 4.8.5-28)]
```

##### PYTHON VERSION
```
Python 2.7.5
```

##### BIGIP VERSION

```
root@(dns)(cfg-sync Standalone)(Active)(/Common)(tmos)# show sys version 

Sys::Version
Main Package
  Product     BIG-IP
  Version     12.1.3
  Build       0.0.378
  Edition     Final
  Date        Mon Nov 27 16:41:03 PST 2017
```

##### LIBRARY VERSIONS

```
[root@ansible-tower-32 Openshift-F5-Setup-multiapp]# pip freeze | egrep '(f5-sdk|bigsuds)'
You are using pip version 8.1.2, however version 10.0.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
bigsuds==1.0.6
f5-sdk==3.0.14

```

##### SUMMARY

It is possible to pass an empty value to the translation_address but not to translation_port.

When passing an empty translation_port ansible complains with the following:

```
TASK [setup-dns : Add LTM virtual server in BIG-IP DNS] ************************
17:07:51
failed: [10.105.157.198 -> localhost] (item=f5plaza.mcd.bd.f5.com) => {"changed": false, "inner_item": "f5plaza.mcd.bd.f5.com", "msg": "argument translation_port is of type <type 'str'> and we were unable to convert to int: invalid literal for int() with base 10: ''"}
```

##### STEPS TO REPRODUCE

I have defined the following dictionaries:

```
routingvip:
  coolstore: "209.194.169.145"
  bookinfo: "209.194.169.145"
  sock-shop: "209.194.169.145"

routingvip_translation:
  coolstore:
  bookinfo:
  sock-shop:

routingvip_port:
  coolstore: "80"
  bookinfo: "8180"
  sock-shop: "8280"

routingvip_port_translation:
  coolstore: 
  bookinfo: 
  sock-shop: 

```

And I would like to be able to apply a the following loop without having to worry if port_translation is filled or not:

```
- name: Add LTM virtual server in BIG-IP DNS
  bigip_gtm_virtual_server:
    server: "{{ bigip_dns }}"
    server_port: "{{ bigip_dns_port }}"
    user: "{{ bigip_user }}"
    password: "{{ bigip_adminpass }}"
    validate_certs: "no"
    server_name: "BIGIP_DC_{{ dcname }}"
    name: "{{ ( '/' + application + '/' + inner_item + '__routestatus' ) | replace(app_baseurl, 'dc-' + dcname + '.' +app_baseurl ) }}"
    address: "{{ routingvip[application] }}"
    port: "{{ routingvip_port[application] }}"
    translation_address: "{{ routingvip_translation[application] }}"
    translation_port: "{{ routingvip_port_translation[application] }}"
    monitors:
      - bigip
    state: present
  delegate_to: localhost
  with_items: "{{ wideips }}"
  loop_control:
    loop_var: inner_item
```

##### EXPECTED RESULTS

translation_port parameter to behave like translation_address and allow for empty parameters.

##### ACTUAL RESULTS

the module errors, the workaround is to use port "0" instead of ""
