### ISSUE TITLE
using provider in bigip_routedomain:

### ISSUE THREAD

**Issue by brettcarr1** [F5Networks/f5-ansible#768]
I've written a playbook to control routing protocols within a route domain, see below
```
- hosts: "{{ targetlb }}"
  gather_facts: no
  vars_prompt:
    - name: "bigip_pwd"
      prompt: "BIGIP Admin Password"
  tasks:
  - name: enable-bgp
    bigip_routedomain:
      routing_protocol:
        - BGP
        - BFD
      state: present
      id: 0
      password: "{{ bigip_pwd }}"
      server: '{{ targetlb }}'
      user: brettcarr
    delegate_to: localhost
```
When I run this It works fine but I get deprecation errors:

[DEPRECATION WARNING]: Param 'user' is deprecated. See the module docs for more information. This feature will be removed in version 2.9. Deprecation
warnings can be disabled by setting deprecation_warnings=False in ansible.cfg.
[DEPRECATION WARNING]: Param 'password' is deprecated. See the module docs for more information. This feature will be removed in version 2.9. Deprecation
warnings can be disabled by setting deprecation_warnings=False in ansible.cfg.
[DEPRECATION WARNING]: Param 'server' is deprecated. See the module docs for more information. This feature will be removed in version 2.9. Deprecation
warnings can be disabled by setting deprecation_warnings=False in ansible.cfg.

I believe I need to pass user, host and password using a provider but I'm not really sure how to do this any help/examples would be really appreciated.

Thanks

Brett

**Comment by caphrim007** [comment]
@brettcarr1 using your example, the task would look like this


```
  - name: enable-bgp
    bigip_routedomain:
      routing_protocol:
        - BGP
        - BFD
      state: present
      id: 0
      provider:
        password: "{{ bigip_pwd }}"
        server: '{{ targetlb }}'
        user: brettcarr
    delegate_to: localhost
```
