### ISSUE TITLE
Add module for creating CLI alias

### ISSUE THREAD

**Issue by tdm00** [F5Networks/f5-ansible#770]
##### ISSUE TYPE
 - Feature Idea

##### COMPONENT NAME
bigip_cli_alias (or whatever follows your naming convention)

##### ANSIBLE VERSION
```
ansible 2.6.0
  config file = /var/ansible/ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.15rc1 (default, Apr 15 2018, 21:51:34) [GCC 7.3.0]
```

##### PYTHON VERSION
```
Python 2.7.15rc1
```

##### BIGIP VERSION
```
Sys::Version
Main Package
  Product     BIG-IP
  Version     13.1.0.7
  Build       0.0.1
  Edition     Point Release 7
  Date        Tue May 15 15:26:30 PDT 2018
```

##### LIBRARY VERSIONS

```
bigsuds==1.0.6
f5-sdk==3.0.17
```

##### CONFIGURATION
N/A

##### OS / ENVIRONMENT
N/A

##### SUMMARY
Our organization has a standard set of CLI alias that we create on each F5 device. Currently we're able to create these in Ansible using the bigip_command module. However using "write" commands is not idempotent and it would be better to use a module that is specifically made for this.

##### STEPS TO REPRODUCE

```
- name: Set CLI Alias
  bigip_command:
    commands:
      - "create /cli alias shared sync_device_to_bside { command 'save /sys config partitions all; run /cm config-sync to-group device-group-1' }"
  delegate_to: localhost
```

##### EXPECTED RESULTS

Idempotency

##### ACTUAL RESULTS

A change is made every time the playbook is run

```
TASK [common : Set CLI Alias] **********************************************************
 [WARNING]: Using "write" commands is not idempotent. You should use a module that is
specifically made for that. If such a module does not exist, then please file a bug. The
command in question is "create /cli alias shared sync_device_to_..."

changed: [192.168.1.231 -> localhost]
```
