### ISSUE TITLE
Add bigip_sys_syslog module for configuring local syslog settings

### ISSUE THREAD

**Issue by tdm00** [F5Networks/f5-ansible#776]
##### ISSUE TYPE
 - Bug Report
 - Feature Idea
 - Documentation Report

##### COMPONENT NAME
N/A, maybe bigip_sys_syslog

##### ANSIBLE VERSION

```
ansible 2.6.1
  config file = /var/ansible/ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.15rc1 (default, Apr 15 2018, 21:51:34) [GCC 7.3.0]
```

##### PYTHON VERSION

```
Python 2.7.15rc1
```

##### BIGIP VERSION

```
Sys::Version
Main Package
  Product     BIG-IP
  Version     13.1.0.7
  Build       0.0.1
  Edition     Point Release 7
  Date        Tue May 15 15:26:30 PDT 2018
```

##### LIBRARY VERSIONS

```
bigsuds==1.0.6
f5-sdk==3.0.17
```

##### CONFIGURATION

N/A

##### OS / ENVIRONMENT

N/A

##### SUMMARY

A module that allows for idempotence with configuring the /sys syslog settings. This would include a way to provide filters for what to include.

##### STEPS TO REPRODUCE

```
- name: syslog-ng settings
  bigip_command:
    commands:
      - "modify sys syslog { auth-priv-from notice auth-priv-to emerg clustered-host-slot enabled clustered-message-slot disabled console-log enabled cron-from warning cron-to emerg daemon-from notice daemon-to emerg description none include ' filter f_remote_syslog { not (facility(local6) and level(info) and match('[ssl_acc\\]')) and not (facility(local6) and level(info) and match('[ssl_req\\]')) and not match (create_if) and not match (system_check) and not match (diskmonitor) and not match ('01060111'); }; destination d_remote_loghost { udp(\"syslog-ng.pncint.net\" port(514)); }; log { source (local); filter(f_remote_syslog); destination(d_remote_loghost); }; filter _audit { facility(local0) and match(AUDIT) and not match (create_if); }; \" iso-date disabled kern-from debug kern-to emerg local6-from notice local6-to emerg mail-from notice mail-to emerg messages-from notice messages-to warning remote-servers none user-log-from notice user-log-to emerg }"
  delegate_to: localhost
```

##### EXPECTED RESULTS

Currently it uses the write commands instead of a command that is specifically made for this configuration. 

##### ACTUAL RESULTS

The command above fails while compiling PCRE expression, which I'm working through and is independent of the request for a module for configuring the local syslog settings of the device.

```

```

**Comment by onurbrc** [comment]
Hello, 

I have the same problem trying to create a syslog configuration with an include filter. 
I'm trying to use bigip_command while we don't have something like this  bigip_sys_syslog. 
However, when I try to pass the command below, the '\"' surrounding the IP address disappear. 
```
modify sys syslog { include "filter f_ssl_acc_req { not (facility(local6) and level(info) and match('[ssl_acc\\]')) and not (facility(local6) and level(info) and match('[ssl_req\\]')); }; destination d_remote_loghost { udp(\"192.168.2.102\" port(514)); }; log { source(s_syslog_pipe); filter(f_ssl_acc_req); destination(d_remote_loghost); };" }
```
I got : 
```
sys syslog {
    include "filter f_ssl_acc_req { not (facility(local6) and level(info) and match('[ssl_acc\\]')) and not (facility(local6) and level(info) and match('[ssl_req\\]'));}; destination d_remote_loghost { udp(\\192.168.2.102\\ port(514)); };log { source(s_syslog_pipe); filter(f_ssl_acc_req); destination(d_remote_loghost);};"
}
```
I tried to manipulate the escape, but the '\"' still missing. 
With verbose dlevel, I got : 
```
"changed": true,
    "executed_commands": [
        "tmsh -c \\\"modify sys syslog remote-servers none\\\"",
        "tmsh -c \\\"modify sys syslog { include \\\\\\\"filter f_ssl_acc_req { not (facility(local6) and level(info) and match(\\'[ssl_acc\\\\]\\')) and not (facility(local6) and level(info) and match(\\'[ssl_req\\\\]\\'));}; destination d_remote_loghost { udp(\\\\\\\\\"192.168.2.102\\\\\\\\\" port(514)); };log { source(s_syslog_pipe); filter(f_ssl_acc_req); destination(d_remote_loghost);};\\\\\\\"}\\\""
    ],
    "invocation": {
        "module_args": {
            "auth_provider": null,
            "chdir": null,
            "commands": [
                "modify sys syslog remote-servers none",
                "modify sys syslog { include \"filter f_ssl_acc_req { not (facility(local6) and level(info) and match('[ssl_acc\\\\]')) and not (facility(local6) and level(info) and match('[ssl_req\\\\]'));}; destination d_remote_loghost { udp(\\\"192.168.2.102\\\" port(514)); };log { source(s_syslog_pipe); filter(f_ssl_acc_req); destination(d_remote_loghost);};\"}"
            ],
```

Do you have any suggestions to create the syslog filter using bigip_command considering the escape ? 

Thank you. 
Best regards.

**Comment by caphrim007** [comment]
@onurbrc use the module I've recently uploaded here.

**Comment by caphrim007** [comment]
@onurbrc can you show me the task you're using exactly?

**Comment by onurbrc** [comment]
@caphrim007 

```

  
  tasks:
  
     - name: Lancement de la configuration syslog
       bigip_device_syslog:
          include: "filter f_ssl_acc_req { not (facility(local6) and level(info) and match('[ssl_acc\\]')) and not (facility(local6) and level(info) and match('[ssl_req\\]'));}; destination d_remote_loghost { udp(\"192.168.2.102\" port(514)); };log { source(s_syslog_pipe); filter(f_ssl_acc_req); destination(d_remote_loghost);};"
          server: "{{ bigip_mgmt_ip }}"
          user: "{{ bigip_user_tmsh }}"
          password: "{{ bigip_password }}"
          validate_certs: no
       delegate_to: localhost
```
