### ISSUE TITLE
Enhance bigip_monitor_external so it can import external monitor files

### ISSUE THREAD

**Issue by WRJFontenot** [F5Networks/f5-ansible#778]
##### ISSUE TYPE

 - Feature Idea
 
##### COMPONENT NAME

bigip_monitor_external

##### ANSIBLE VERSION

```
ansible 2.6.0
```

##### PYTHON VERSION

```
Python 2.7.5
```

##### BIGIP VERSION

```

```

##### LIBRARY VERSIONS

```

```

##### SUMMARY

Add ability to import external programs

##### STEPS TO REPRODUCE

```
- name: Copy https_sni_monitor to device
  connection: "ssh"
  copy:
    src: "{{ devicelist }}/files/https_sni_monitor"
    dest: "/config/monitors"

- name: TMSH Import https_sni_monitor
  bigip_command:
    provider: "{{ f5_rest }}"
    commands: create sys file external-monitor /Common/https_sni_monitor source-path file:///config/monitors/https_sni_monitor
  delegate_to: "localhost"
  ignore_errors: "yes"

- name: Create external monitor
  bigip_monitor_external:
    provider: "{{ f5_rest }}"
    external_program: "/Common/https_sni_monitor"
    interval: "5"
    ip:
    name: "my_https_sni_monitor"
    parent: "/Common/external"
    partition: "{{ f5_partition }}"
    port:
    state: "present"
    timeout: "16"
    variables:
      HOST: "adfs.example.com"
      RECV: "200 OK"
      URI: "/adfs/fs/federationserverservice.asmx"
  delegate_to: "localhost"
```

##### EXPECTED RESULTS

Import external monitor file using bigip_monitor_external module
##### ACTUAL RESULTS

Had to execute TMSH command using bigip_command module to import external monitor

```

```

**Comment by onurbrc** [comment]
Hi, 

This feature will be very nice. 
I've been trying to import the F5 script below to monitoring DNS changing as an external script file, but the script has a several special characters and system variables, so if I try to copy the file content from my machine to the bigip, the special character or nested quotes marks are not considered. The python behind ignore them. 
Script : 
```
#!/bin/sh
# (c) Copyright 1996-2007 F5 Networks, Inc.
#
# This software is confidential and may contain trade secrets that are the
# property of F5 Networks, Inc.  No part of the software may be disclosed
# to other parties without the express written consent of F5 Networks, Inc.
# It is against the law to copy the software.  No part of the software may
# be reproduced, transmitted, or distributed in any form or by any means,
# electronic or mechanical, including photocopying, recording, or information
# storage and retrieval systems, for any purpose without the express written
# permission of F5 Networks, Inc.  Our services are only available for legal
# users of the program, for instance in the event that we extend our services
# by offering the updating of files via the Internet.
#
#
# these arguments supplied automatically for all external monitors:
# $1 = IP (nnn.nnn.nnn.nnn notation or hostname)
# $2 = port (decimal, host byte order) -- not used in this monitor, assumes default port 53
# $3 = name to be looked up
# $4 = string in expected response

node_ip=`echo $1 | sed 's/::ffff://'`

pidfile="/var/run/`basename $0`.$node_ip..$2.pid"
LOGFILE="/var/log/`basename $0`.log"


if [ -f $pidfile ]
then
   kill -9 `cat $pidfile` > /dev/null 2>&1
fi
echo "$$" > $pidfile

#dig @${node_ip} ${3} | egrep -v '^$|^;' | grep ${4} > /dev/null 2>&1
#dig @${4} ${3} | egrep -v '^$|^;' | grep ${node_ip} > /dev/null 2>&1

if [ ${DEBUG} -gt 0 ]
   then
      echo "`date +"%Y-%m-%d %H:%M:%S"`|IP=${node_ip}|QUERY=${QUERY}" >> ${LOGFILE}
   fi

dig ${QUERY} | egrep -v '^$|^;' | grep ${node_ip} > /dev/null 2>&1


# For AAAA lookups, use this instead
# dig @${node_ip} ${3} AAAA| egrep -v '^$|^;' | grep ${4} > /dev/null 2>&1

status=$?
if [ $status -eq 0 ]
then
    if [ ${DEBUG} -gt 0 ]
      then
         echo "`date +"%Y-%m-%d %H:%M:%S"`|Host ${node_ip} found : UP" >> ${LOGFILE}
      fi
    echo "UP"
else
      if [ ${DEBUG} -gt 0 ]
      then
         echo "`date +"%Y-%m-%d %H:%M:%S"`|Host ${node_ip} not found : DOWN" >> ${LOGFILE}
      fi
fi

rm -f $pidfile
```

So, I'm passing by a file transfer without lookup the content file in an explicit way. 
```
tasks: 
 - name: File transfer 
   shell: 'sshpass -p secret scp monitordns.sh root@lb.mydomain.com:/config/monitors/monitordns.sh'
   delegate_to: localhost
   
 - name: Installing the file in a tmsh level 
   bigip_monitor_external:
      commands: "create /sys file external-monitor monitordns source-path file:///config/monitors/monitordns.sh"
      user: admin
      server: lb.mydomain.com
      password: secret
      validate_certs: no 
   delegate_to: localhost
```
Like @WRJFontenot, it works for me to create a external monitor in the end using the module bigip_monitor_external. 

But, I don't know how to proceed when I cannot use file transfer through system level. If I pass the script content into a playbook as a variable or another way, the script content arrives incomplete into the bigip /config/monitors/monitordns.sh dest file, cause some quotes and special characters are parsed/ignored by python. 

So, if there is an evolution of bigip_monitor_external to import files, would it accept that kind of script content above ? 

Best regards.
