### ISSUE TITLE
Module for configuring BIG-IP log configuration

### ISSUE THREAD

**Issue by tdm00** [F5Networks/f5-ansible#782]
##### ISSUE TYPE

 - Feature Idea

##### COMPONENT NAME

There doesn't appear to be a module specifically made for modifying the /sys log-config to provide idempotency. Perhaps bigip_sys_log_config?

##### ANSIBLE VERSION

```
ansible 2.6.1
  config file = /var/ansible/ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.15rc1 (default, Apr 15 2018, 21:51:34) [GCC 7.3.0]
```

##### PYTHON VERSION

```
Python 2.7.15rc1
```

##### BIGIP VERSION

```
Sys::Version
Main Package
  Product     BIG-IP
  Version     13.1.0.7
  Build       0.0.1
  Edition     Point Release 7
  Date        Tue May 15 15:26:30 PDT 2018
```

##### LIBRARY VERSIONS

```
bigsuds==1.0.6
f5-sdk==3.0.17
```

##### CONFIGURATION

```
N/A
```

##### OS / ENVIRONMENT

```
N/A
```

##### SUMMARY

Add a module that allows for idempotency with configuring the /sys log-config settings. 

##### STEPS TO REPRODUCE

```
- name: Create AVR statistics logging
  bigip_command:
    commands:
      - create /sys log-config destination management-port AVR_to_Loginsight { ip-address 1.1.1.1 port 514 protocol udp }
      - create /sys log-config destination remote-syslog syslog_for_avr { format rfc5424 remote-high-speed-log AVR_to_Loginsight }
      - create /sys log-config publisher loginsight_avr_publisher { description "AVR statistics logging to Loginsight" destinations replace-all-with { syslog_for_avr { } } }
  delegate_to: localhost

```

##### ACTUAL RESULTS

```
TASK [common : Create AVR statistics logging] ********************************
fatal: [192.168.1.230 -> localhost]: FAILED! => {"changed": false, "msg": "01020037:3: The requested log destination management port (/Common/AVR_to_Loginsight) already exists."}
fatal: [192.168.1.231 -> localhost]: FAILED! => {"changed": false, "msg": "01020037:3: The requested log destination management port (/Common/AVR_to_Loginsight) already exists."}
	to retry, use: --limit @/var/ansible/site.retry

```
