### ISSUE TITLE
Add support for setting qinq-ethertype option to bigip_trunk module

### ISSUE THREAD

**Issue by rfults** [F5Networks/f5-ansible#783]
##### ISSUE TYPE
 - Feature Idea

##### COMPONENT NAME
bigip_trunk

##### ANSIBLE VERSION

```
ansible 2.6.0
```

##### PYTHON VERSION

```
Python 2.7.5
```

##### BIGIP VERSION

```
  Product     BIG-IP
  Version     13.1.0.5
  Build       0.0.5
  Edition     Point Release 5
```

##### LIBRARY VERSIONS

```
bigsuds==1.0.6
f5-sdk==3.0.17
```

##### OS / ENVIRONMENT

N/A

##### SUMMARY

Add support for setting qinq-ethertype option to bigip_trunk module.

##### STEPS TO REPRODUCE

```
- name: Create a trunk
  bigip_trunk:
    name: foo
    password: secret
    server: lb.mydomain.com
    state: present
    user: admin
    interfaces: "1/1.1,1/1.2"
    lacp_enabled: yes
    ethertype: 0x9100
  delegate_to: localhost
```

##### EXPECTED RESULTS

'list net trunk all-properties|grep -i ether' should return 'qinq-ethertype 0x9100' under 'net trunk foo'.
##### ACTUAL RESULTS

```

```
