### ISSUE TITLE
bigip_device_facts Module Error - ImportError: cannot import name flatten_boolean

### ISSUE THREAD

**Issue by sdaynjax** [F5Networks/f5-ansible#794]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

bigip_device_facts.py
##### ANSIBLE VERSION

```
ansible 2.6.1
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/media/sf_f5_ansible_modules']
  ansible python module location = /usr/lib/python2.7/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.15rc1 (default, Apr 15 2018, 21:51:34) [GCC 7.3.0]

```

##### PYTHON VERSION

```
Python 2.7.15rc1

```

##### BIGIP VERSION

```

Sys::Version
Main Package
  Product     BIG-IP
  Version     12.1.3
  Build       0.0.378
  Edition     Final
  Date        Mon Nov 27 16:41:03 PST 2017
```

##### LIBRARY VERSIONS

```
bigsuds==1.0.6
f5-sdk==3.0.16

```

##### CONFIGURATION

none
##### OS / ENVIRONMENT

Kubuntu version 18.04 

##### SUMMARY

getting error

##### STEPS TO REPRODUCE

```
- name: Display BIG-IP details
  hosts: test_cli
  gather_facts: no
  connection: local

  tasks:
    - name: get bigip facts
      bigip_device_facts:
        server: "{{ inventory_hostname }}"
        user: "admin"
        password: "secret"
        gather_subset: 
          - devices
      delegate_to: localhost
```

##### EXPECTED RESULTS

I would expect to get the device information
##### ACTUAL RESULTS

```
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: ImportError: cannot import name flatten_boolean
fatal: [10.x.x.x -> localhost]: FAILED! => {"changed": false, "module_stderr": "Traceback (most recent call last):\n  File \"/tmp/ansible_weYaaM/ansible_module_bigip_device_facts.py\", line 2573, in <module>\n    from ansible.module_utils.network.f5.common import flatten_boolean\nImportError: cannot import name flatten_boolean\n", "module_stdout": "", "msg": "MODULE FAILURE", "rc": 1}
```
