### ISSUE TITLE
Modify bigip_vlan interfaces parameter(s) for flexible tagging

### ISSUE THREAD

**Issue by rfults** [F5Networks/f5-ansible#800]
##### ISSUE TYPE

 - Feature Idea

##### COMPONENT NAME

bigip_vlan 

##### ANSIBLE VERSION

```
ansible 2.6.0
```

##### PYTHON VERSION

```
Python 2.7.5
```

##### BIGIP VERSION

```
  Product     BIG-IP
  Version     13.1.0.5
  Build       0.0.5
  Edition     Point Release 5
```

##### LIBRARY VERSIONS

```
bigsuds==1.0.6
f5-sdk==3.0.17
```

##### OS / ENVIRONMENT

N/A
##### STEPS TO REPRODUCE

Combine tagged_interfaces and untagged_interfaces into single "interfaces" parameter with a sub-option of "tagging".  Also having some of the other advanced config options such as ~~sFlow~~(done), ~~Fail-safe~~(done) and 
~~Source Check~~ (done) would be helpful.

```
---
- name: Create vlans
  hosts: all

  vars:
    vlans:
      - { name: "vlan_tagged", tag: "2", interfaces: "int_2", tagging: "tagged" }
      - { name: "vlan_untagged", tag: "3", interfaces: "int_3", tagging: "untagged" }
  tasks:
  - name: create vlans
    bigip_vlan:
      name: "{{ item.name }}"
      interfaces: "{{ item.interfaces }}"
	    tagging: "{{ item.tagging }}"
      tag: "{{ item.tag }}"
      provider:
        password: "{{ f5_admin_pass }}"
        user: "{{ f5_admin }}"
        server: "{{ inventory_hostname }}"
        validate_certs: "no"
    loop: "{{ vlans }}"
    delegate_to: localhost
```

##### EXPECTED RESULTS

VLAN interfaces would be configured with correct tagging options.
##### ACTUAL RESULTS

```

```
