### ISSUE TITLE
Network Mirroring options missing from bigip_device_connectivity module

### ISSUE THREAD

**Issue by rfults** [F5Networks/f5-ansible#801]
##### ISSUE TYPE

 - Feature Idea

##### COMPONENT NAME

bigip_device_connectivity 
##### ANSIBLE VERSION

```
ansible 2.6.0
```

##### PYTHON VERSION

```
Python 2.7.5
```

##### BIGIP VERSION

```
  Product     BIG-IP
  Version     13.1.0.5
  Build       0.0.5
  Edition     Point Release 5
```

##### LIBRARY VERSIONS

```
bigsuds==1.0.6
f5-sdk==3.0.17
```

##### OS / ENVIRONMENT

N/A
##### STEPS TO REPRODUCE

Add Network Mirroring options to bigip_device_connectivity to allow selection of "Between Clusters" or "Within Cluster" to align with current big-ip software version.

```
  - name: create HA device connectivity
    bigip_device_connectivity:
      config_sync_ip: "192.168.250.15"
      mirror_primary_address: "10.1.30.1"
      mirror_options: "Between Clusters"
      unicast_failover:
        - address: 10.1.30.1
        - address: 192.168.250.15
      provider:
        password: "{{ f5_admin_pass }}"
        user: "{{ f5_admin }}"
        server: "{{ inventory_hostname }}"
        validate_certs: "no"
    delegate_to: localhost
```

##### EXPECTED RESULTS

Should set Network Mirroring options in Device Management > Devices > DeviceName > Mirroring tab.
##### ACTUAL RESULTS

```

```
