### ISSUE TITLE
bigip_device_connectivity not idempotent when unicast-ip is specified pt.2

### ISSUE THREAD

**Issue by rfults** [F5Networks/f5-ansible#803]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

bigip_device_connectivity
##### ANSIBLE VERSION

```
ansible 2.6.0
```

##### PYTHON VERSION

```
Python 2.7.5
```

##### BIGIP VERSION

```
  Product     BIG-IP
  Version     13.1.0.5
  Build       0.0.5
  Edition     Point Release 5
```

##### LIBRARY VERSIONS

```
bigsuds==1.0.6
f5-sdk==3.0.17
```

##### OS / ENVIRONMENT

N/A
##### SUMMARY

When specifying unicast_failover parameters with bigip_device_connectivity module Ansible will always return changed.
##### STEPS TO REPRODUCE

```
  - name: create HA device connectivity
    bigip_device_connectivity:
      config_sync_ip: "{{ config_sync_ip|default('none') }}"
      mirror_primary_address: "{{ mirror_primary_address|default('none') }}"
      mirror_secondary_address: "{{ mirror_secondary_address|default('none') }}"
      unicast_failover:
        - address:  "{{ item.address|default('management-ip') }}"
          port: "{{ item.port|default('1026') }}"
      failover_multicast: "{{ failover_multicast|default('false') }}"
      provider:
        password: "{{ f5_admin_pass }}"
        user: "{{ f5_admin }}"
        server: "{{ inventory_hostname }}"
        validate_certs: "no"
    loop: "{{ unicast_failover|default([]) }}"
    delegate_to: localhost
```
From host_vars:
```
config_sync_ip: "192.168.250.30"
mirror_primary_address: "192.168.250.30"
unicast_failover:
  - { address:  "management-ip" }
  - { address:  192.168.250.30, port: 1026 }
failover_multicast: yes
```
Existing device config:
```
    unicast-address {
        {
            effective-ip management-ip
            effective-port cap
            ip management-ip
            port cap
        }
        {
            effective-ip 192.168.250.30
            effective-port cap
            ip 192.168.250.30
            port cap
        }
    }

```

##### EXPECTED RESULTS

Should show ok.

##### ACTUAL RESULTS

```
changed: [uso-2150-31 -> localhost] => (item={u'address': u'management-ip'}) => changed=true
  item:
    address: management-ip
  unicast_failover:
  - effectiveIp: management-ip
    effectivePort: 1026
    ip: management-ip
    port: 1026
changed: [uso-2150-31 -> localhost] => (item={u'port': 1026, u'address': u'192.168.250.30'}) => changed=true
  item:
    address: 192.168.250.30
    port: 1026
  unicast_failover:
  - effectiveIp: 192.168.250.30
    effectivePort: 1026
    ip: 192.168.250.30
    port: 1026
 _________________________________________________________

```

**Comment by caphrim007** [comment]
@rfults this is expected behavior. `unicast_failover` may not be looped over. it is an all-or-nothing parameter.

Therefore, you need to specify all of them up-front


```
  - set_fact:
       unicast_failover:
        - address:  "management-ip"
        - address: 192.168.250.30
          port: 1026

  - name: create HA device connectivity
    bigip_device_connectivity:
      config_sync_ip: "{{ config_sync_ip|default('none') }}"
      mirror_primary_address: "{{ mirror_primary_address|default('none') }}"
      mirror_secondary_address: "{{ mirror_secondary_address|default('none') }}"
      unicast_failover: "{{ unicast_failover|default([]) }}"
      failover_multicast: "{{ failover_multicast|default('false') }}"
      provider:
        password: "{{ f5_admin_pass }}"
        user: "{{ f5_admin }}"
        server: "{{ inventory_hostname }}"
        validate_certs: "no"
    loop: "{{ unicast_failover|default([]) }}"
    delegate_to: localhost
```

The behavior that you're seeing is the module overwriting what was configured upon the first iteration of the loop when it runs the second iteration.

**Comment by rfults** [comment]
So what is the best way to make this more dynamic?  I want to be able to run this against the HA pair or multiple sets of devices to set up multiple devices all at once.  Storing all of the needed info in group_vars and host_vars allows me this flexibility with just about every other F5 module I have worked with so far.

**Comment by caphrim007** [comment]
Continue to store it in group_vars and host_vars.

A configuration like this can be stored in two host_vars files

bigip1.yaml
```
  - set_fact:
       unicast_failover:
        - address:  "management-ip"
        - address: 11.11.11.11
          port: 1026
```

bigip2.yaml
```
  - set_fact:
       unicast_failover:
        - address:  "management-ip"
        - address: 10.10.10.10
          port: 1026
```

**Comment by rfults** [comment]
OK.  I think I figured this out:
```
  - name: create HA device connectivity
    bigip_device_connectivity:
      config_sync_ip: "{{ config_sync_ip|default('none') }}"
      mirror_primary_address: "{{ mirror_primary_address|default('none') }}"
      mirror_secondary_address: "{{ mirror_secondary_address|default('none') }}"
      unicast_failover: "{{ unicast_failover|default([]) }}"
      failover_multicast: "{{ failover_multicast|default('false') }}"
      provider:
        password: "{{ f5_admin_pass }}"
        user: "{{ f5_admin }}"
        server: "{{ inventory_hostname }}"
        validate_certs: "no"
    delegate_to: localhost
```

My host_vars are in the same format I had them in originally, just dropped the looping logic from the task itself and let it load the array in one shot.
