### ISSUE TITLE
Case sensitivity and member selection with bigip_device_group_member 

### ISSUE THREAD

**Issue by rfults** [F5Networks/f5-ansible#807]
##### ISSUE TYPE

 - Feature Idea

##### COMPONENT NAME

bigip_device_group_member 
##### ANSIBLE VERSION

```
ansible 2.6.0
```

##### PYTHON VERSION

```
Python 2.7.5
```

##### BIGIP VERSION

```
Viprion 2150:
  Product     BIG-IP
  Version     13.1.0.5
  Build       0.0.5
  Edition     Point Release 5
```

##### LIBRARY VERSIONS

```
bigsuds==1.0.6
f5-sdk==3.0.17
```

##### OS / ENVIRONMENT

n/a
##### SUMMARY

bigip_device_group_member creates a new member entry if there are any case differences between what is on the device already vs what is being passed by the playbook.  Is there anyway to make the module case-insensitive or just select all of the available devices in the cluster including itself?
##### STEPS TO REPRODUCE

Current playbook has members broken out due to looping issues:

```
 - name: Add peer(s) to HA Device Group members
    bigip_device_group_member:
      device_group: "{{ dg_name|default('DG_Sync_only') }}"
      name: "{{ peer_hostname }}"
      state: present
      provider: "{{ provider }}"
    when: ha_enabled == True and ha_enabled is defined
    delegate_to: localhost
    tags:
      - dg

  - name: Add self to HA Device Group members
    bigip_device_group_member:
      device_group: "{{ dg_name|default('DG_Sync_only') }}"
      name: "{{ inventory_hostname }}"
      state: present
      provider: "{{ provider }}"
    when: ha_enabled == True and ha_enabled is defined
    delegate_to: localhost
    tags:
      - dg
```

##### EXPECTED RESULTS

Expecting ansible to show OK when nodes exist.

```
ok: [uso-2150-30 -> localhost] => changed=false
  invocation:
    module_args:
      device_group: DG-Sync-Failover
      name: USO-2150-40
      password: null
      provider:
        password: VALUE_SPECIFIED_IN_NO_LOG_PARAMETER
        server: uso-2150-30
        server_port: null
        ssh_keyfile: null
        timeout: null
        transport: rest
        user: admin
        validate_certs: false
      server: null
      server_port: null
      state: present
      transport: null
      user: null
      validate_certs: null
```
##### ACTUAL RESULTS

```
changed: [uso-2150-40 -> localhost] => changed=true
  invocation:
    module_args:
      device_group: DG-Sync-Failover
      name: USO-2150-30
      password: null
      provider:
        password: VALUE_SPECIFIED_IN_NO_LOG_PARAMETER
        server: uso-2150-40
        server_port: null
        ssh_keyfile: null
        timeout: null
        transport: rest
        user: admin
        validate_certs: false
      server: null
      server_port: null
      state: present
      transport: null
      user: null
      validate_certs: null

```
From conf:
```
cm device-group DG-Sync-Failover {
    app-service none
    asm-sync disabled
    auto-sync disabled
    description none
    devices {
        USO-2150-40 { }
        uso-2150-30 { }
    }
    full-load-on-sync false
    incremental-config-sync-size-max 1024
    network-failover enabled
    partition Common
    save-on-auto-sync false
    type sync-failover
}

```
