### ISSUE TITLE
bigip_node not idempotent when description is 'none'

### ISSUE THREAD

**Issue by rfults** [F5Networks/f5-ansible#810]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

bigip_node
##### ANSIBLE VERSION

```
ansible 2.6.0
```

##### PYTHON VERSION

```
Python 2.7.5
```

##### BIGIP VERSION

```
Viprion 2150:
  Product     BIG-IP
  Version     13.1.0.5
  Build       0.0.5
  Edition     Point Release 5
```

##### LIBRARY VERSIONS

```
bigsuds==1.0.6
f5-sdk==3.0.17
```

##### OS / ENVIRONMENT

N/A
##### SUMMARY

Not sure if this is a bug or just odd behavior from Big-IP software. bigip_node seems to return changed every time the playbook is re-run and description is set to 'none'.  Issue doesn't seem to occur if set to anything else or omitted completely.  I am migrating from old hardware to new Viprion pair and exported everything to yaml vars files and have changed a handful of items, we left 'none' in the description field since it was returned by tmsh.  I am guessing that the module is writing 'none' and Big-IP is just reinterpreting that as NULL.

##### STEPS TO REPRODUCE

```
  - name: create nodes
    bigip_node:
      name: "{{ item.name }}"
      address: "{{ item.address }}"
      description: "{{ item.description|default(omit) }}"
      monitors: "{{ item.monitors|default('gateway_icmp') }}"
      state: "{{ item.state|default('disabled') }}"
      partition: "Common"
      provider: "{{ provider }}"
    loop: "{{ bigip_nodes|default([]) }}"
    delegate_to: localhost
```
from group_vars:
```
  - { name: '192.168.1.50', address: '192.168.1.50', description: 'none', state: disabled }
```

from conf:
```
ltm node 192.168.1.50 {
    address 192.168.1.50
    app-service none
    connection-limit 0
    description none
    dynamic-ratio 1
    ephemeral false
    fqdn {
        address-family ipv4
        autopopulate disabled
        down-interval 5
        interval 3600
        name none
    }
    logging disabled
    metadata none
    monitor gateway_icmp
    partition Common
    rate-limit disabled
    ratio 1
    session user-disabled
    state down
}
```

##### EXPECTED RESULTS

Expecting ansible to return OK.
##### ACTUAL RESULTS

```
changed: [bigip -> localhost] => (item={u'state': u'disabled', u'address': u'192.168.1.50', u'description': u'none', u'name': u'192.168.1.50'}) => changed=true
  description: none
  fqdn: {}
  invocation:
    module_args:
      address: 192.168.1.50
      description: none
      fqdn: null
      fqdn_address_type: null
      fqdn_auto_populate: null
      fqdn_down_interval: null
      fqdn_up_interval: null
      monitor_type: null
      monitors:
      - gateway_icmp
      name: 192.168.1.50
      partition: Common
      password: null
      provider:
        password: VALUE_SPECIFIED_IN_NO_LOG_PARAMETER
        server: bigip
        server_port: null
        ssh_keyfile: null
        timeout: null
        transport: rest
        user: admin
        validate_certs: false
      quorum: null
      server: null
      server_port: null
      state: disabled
      transport: null
      user: null
      validate_certs: null
  item:
    address: 192.168.1.50
    description: none
    name: 192.168.1.50
    state: disabled

```
