### ISSUE TITLE
bigip_data_group - do not create a datagroup with an upper case letter in the name

### ISSUE THREAD

**Issue by mshoaibshafi** [F5Networks/f5-ansible#815]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

bigip_data_group

##### ANSIBLE VERSION

```
[mshoaib@ca01net03 ansible]$ ansible --version
ansible 2.6.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/mshoaib/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.6/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 3.6.5 (default, Apr 10 2018, 17:08:37) [GCC 4.8.5 20150623 (Red Hat 4.8.5-16)]
[mshoaib@ca01net03 ansible]$
```

##### PYTHON VERSION

```
[mshoaib@ca01net03 ansible]$ python3.6 -V
Python 3.6.5
[mshoaib@ca01net03 ansible]$
```

##### BIGIP VERSION

```
[mshoaib@ca01lb11v:Active:In Sync] ~ # tmsh show sys version

Sys::Version
Main Package
  Product     BIG-IP
  Version     12.1.2
  Build       2.0.276
  Edition     Hotfix HF2
  Date        Sat Nov 11 04:32:09 PST 2017

Hotfix List 
( long list of hotfix omitted here )
```

##### LIBRARY VERSIONS

```
[mshoaib@ca01net03 ansible]$ pip3.6 freeze  | egrep '(f5-sdk|bigsuds)'
f5-sdk==3.0.18
[mshoaib@ca01net03 ansible]$ 
```

##### CONFIGURATION

No settings have been changed that I am aware of in ansible.cfg
##### OS / ENVIRONMENT

Ansible running from CentOS
```
[mshoaib@ca01net03 ansible]$ cat /etc/redhat-release 
CentOS Linux release 7.5.1804 (Core) 
[mshoaib@ca01net03 ansible]$ 
```
##### SUMMARY

When I tried to create a Data group whose name contains one or more  "upper" case letter, it error out. 
But with the exact same ansible config as well as data file but all "lower" case letters, it works like a charm.

##### STEPS TO REPRODUCE

```
---
# This script will create a data group
- name: Create a Data Group
  hosts: "{{ hosts }}"
  connection: local

  tasks:
      - name: Create an upper case Data Group
        bigip_data_group:
            server: "{{ bigip_server }}"
            user: "{{ bigip_username }}"
            password: "{{ bigip_password }}"
            validate_certs: no
            state: present
            external_file_name: clients_data_group_Upper_case
            name: clients_data_group_Upper_case
            records_src: data/clients_data_group_Upper_case
            type: string
        delegate_to: localhost

```
data file contents 

```
[mshoaib@ca01net03 ansible]$ pwd
/home/mshoaib/python/bigip/ansible
[mshoaib@ca01net03 ansible]$  cat data/clients_data_group_Upper_case 
"client1" := "pool1",
"client2" := "pool2",
"client3" := "pool3"
[mshoaib@ca01net03 ansible]$

```

##### EXPECTED RESULTS

I expect that "data-group" will be created successfully.
In fact, if i just change the data group name ( make all lower case ) with exact same playbook and data file, it work just fine.

##### ACTUAL RESULTS

```
[mshoaib@ca01net03 ansible]$ pwd
/home/mshoaib/python/bigip/ansible
[mshoaib@ca01net03 ansible]$ sudo ansible-playbook -i inventory/hosts -e "hosts=newevenue-bigips" create-datagroup.yaml 
 [WARNING]: Found variable using reserved name: hosts

PLAY [Create a Data Group] **********************************************************************************************************************************************************************************************

TASK [Gathering Facts] **************************************************************************************************************************************************************************************************
ok: [ca01lb11v]

TASK [Create an Upper case Data Group] *********************************************************************************************************************************************************************************
[DEPRECATION WARNING]: Param 'server' is deprecated. See the module docs for more information. This feature will be removed in version 2.9. Deprecation warnings can be disabled by setting deprecation_warnings=False 
in ansible.cfg.
[DEPRECATION WARNING]: Param 'user' is deprecated. See the module docs for more information. This feature will be removed in version 2.9. Deprecation warnings can be disabled by setting deprecation_warnings=False in 
ansible.cfg.
[DEPRECATION WARNING]: Param 'password' is deprecated. See the module docs for more information. This feature will be removed in version 2.9. Deprecation warnings can be disabled by setting deprecation_warnings=False
 in ansible.cfg.
[DEPRECATION WARNING]: Param 'validate_certs' is deprecated. See the module docs for more information. This feature will be removed in version 2.9. Deprecation warnings can be disabled by setting 
deprecation_warnings=False in ansible.cfg.
changed: [ca01lb11v -> localhost]

TASK [Create an upper case Data Group] **********************************************************************************************************************************************************************************
fatal: [ca01lb11v -> localhost]: FAILED! => {"changed": false, "msg": "'external_file_name' may only contain letters, numbers, underscores, dashes, or a period."}
        to retry, use: --limit @/home/mshoaib/python/bigip/ansible/create-datagroup.retry

PLAY RECAP **************************************************************************************************************************************************************************************************************
ca01lb11v                  : ok=2    changed=1    unreachable=0    failed=1   

```
