### ISSUE TITLE
bigip_sys_global.py - boolean values do not accept 'enabled/disabled' anymore - examples show 'enabled/disabled'

### ISSUE THREAD

**Issue by neozoolook** [F5Networks/f5-ansible#817]
##### ISSUE TYPE

 - Bug Report
or
 - Documentation Report

##### COMPONENT NAME

bigip_sys_global.py

##### ANSIBLE VERSION

```

```

##### PYTHON VERSION

```

```

##### BIGIP VERSION

```

```

##### LIBRARY VERSIONS

```

```

##### STEPS TO REPRODUCE

```
CURRENT BROKEN PLAYBOOK
---
- name: Set sys f5_global values
  bigip_sys_global:
    banner_text: "{{ sys_global_sec_banner }}"
    security_banner: "enabled"
    gui_setup: "disabled"
    mgmt_dhcp: "disabled"
    state: "present"
    server: "{{ ansible_host }}"
    user: "{{ username }}"
    password: "{{ password }}"
    validate_certs: "no"
  delegate_to: localhost


FIXED PLAYBOOK

---
- name: Set sys f5_global values
  bigip_sys_global:
    banner_text: "{{ sys_global_sec_banner }}"
    security_banner: "yes"
    gui_setup: "no"
    mgmt_dhcp: "no"
    state: "present"
    server: "{{ ansible_host }}"
    user: "{{ username }}"
    password: "{{ password }}"
    validate_certs: "no"
  delegate_to: localhost
```

##### EXPECTED RESULTS

```
Documentation Examples... Not sure if enable/disable is deprecated, if so we should update examples;
EXAMPLES = r'''
- name: Disable the setup utility
  bigip_sys_global:
    gui_setup: disabled
    password: secret
    server: lb.mydomain.com
    user: admin
    state: present
  delegate_to: localhost
'''
```
##### ACTUAL RESULTS

```

TASK [f5_global : Set sys f5_global values] ***************************************************************************************
task path: /home/pp2854/ansible-bb_cgifw/roles/f5_global/tasks/f5_sys_global.yml:2
Using module file /home/pp2854/ansible-bb_cgifw/library/modules/bigip_sys_global.py
<localhost> ESTABLISH LOCAL CONNECTION FOR USER: pp2854
<localhost> EXEC /bin/sh -c '/usr/bin/python && sleep 0'
The full traceback is:
  File "/tmp/ansible_igMQGK/ansible_modlib.zip/ansible/module_utils/basic.py", line 2251, in boolean
    return boolean(arg)
  File "/tmp/ansible_igMQGK/ansible_modlib.zip/ansible/module_utils/parsing/convert_bool.py", line 26, in boolean
    raise TypeError("The value '%s' is not a valid boolean.  Valid booleans include: %s" % (to_text(value), ', '.join(repr(i) for i in BOOLEANS)))

fatal: [zrdm8afcgi01cgi002 -> localhost]: FAILED! => {
    "changed": false, 
    "invocation": {
        "module_args": {
            "banner_text": "WARNING THIS IS A PRIVATE AND PROPRIETARY SYSTEM OF AT&T Mobility. UNAUTHORIZED ACCESS TO OR MISUSE OF AT&T SYSTEMS OR DATA MAY RESULT IN CIVIL AND/OR CRIMINAL PROSECUTION.", 
            "gui_setup": "disabled", 
            "mgmt_dhcp": "disabled", 
            "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER", 
            "provider": {
                "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER", 
                "server": "172.20.216.250", 
                "server_port": 443, 
                "ssh_keyfile": null, 
                "timeout": 10, 
                "transport": "rest", 
                "user": "admin", 
                "validate_certs": "no"
            }, 
            "security_banner": "yes", 
            "server": "172.20.216.250", 
            "state": "present", 
            "user": "admin", 
            "validate_certs": "no"
        }
    }, 
    "msg": "The value 'disabled' is not a valid boolean.  Valid booleans include: 0, 'on', 'f', 'false', 1, 'no', 'n', '1', '0', 't', 'y', 'off', 'yes', 'true'"
}

PLAY RECAP ************************************************************************************************************************
zrdm8afcgi01cgi002         : ok=0    changed=0    unreachable=0    failed=1  
```
