### ISSUE TITLE
Issue running F5 Modules in AWX

### ISSUE THREAD

**Issue by glenpekarcsik** [F5Networks/f5-ansible#820]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
bigip_pool

##### ANSIBLE VERSION
Ansible 2.6.1
AWX 1.0.6.35 

##### PYTHON VERSION
Python 2.7.5

##### BIGIP VERSION
BIG-IP 13.1.0.8 Build 0.0.3 Point Release 8

##### OS / ENVIRONMENT
I am connecting to a remote linux host running Red Hat Enterprise Linux Server release 7.5 (Maipo)

##### SUMMARY
When I try to run the Ansible playbooks in AWX, I get the following error:
 
{
    "_ansible_parsed": false,
    "_ansible_no_log": false,
    "module_stderr": "Shared connection to cwb02dacoapp01 closed.\r\n",
    "changed": false,
    "module_stdout": "Traceback (most recent call last):\r\n  File \"/tmp/ansible_lIP2yD/ansible_module_bigip_pool.py\", line 956, in <module>\r\n    main()\r\n  File \"/tmp/ansible_lIP2yD/ansible_module_bigip_pool.py\", line 945, in main\r\n    client = F5Client(**module.params)\r\n  File \"/tmp/ansible_lIP2yD/ansible_modlib.zip/ansible/module_utils/network/f5/bigip.py\", line 32, in __init__\r\n  File \"/tmp/ansible_lIP2yD/ansible_modlib.zip/ansible/module_utils/network/f5/common.py\", line 396, in merge_provider_params\r\nAttributeError: 'NoneType' object has no attribute 'get'\r\n",
    "rc": 1,
    "msg": "MODULE FAILURE"
}

##### STEPS TO REPRODUCE
Run the following playbook in AWX.

```
- name: do things
  hosts: internal 

  tasks:
     - name: create a pool
       bigip_pool:
           lb_method: ratio-member
           name: web-test
           password: ***********
           server: sdc01testgtm1
           slow_ramp_time: 120
           user: f5user
           validate_certs: no
```

##### EXPECTED RESULTS
If the playbook above in run from Ansible engine, it works as expected.  When trying to run the playbook in AWX, I encounter the error.  The playbook should run the same in AWX as it does with ansible engine

##### ACTUAL RESULTS
The following error occurred:

fatal: [cwb02dacoapp01]: FAILED! => {"changed": false, "module_stderr": "Shared connection to cwb02dacoapp01 closed.\r\n", "module_stdout": "Traceback (most recent call last):\r\n  File \"/tmp/ansible_a3CLmr/ansible_module_bigip_pool.py\", line 956, in <module>\r\n    main()\r\n  File \"/tmp/ansible_a3CLmr/ansible_module_bigip_pool.py\", line 945, in main\r\n    client = F5Client(**module.params)\r\n  File \"/tmp/ansible_a3CLmr/ansible_modlib.zip/ansible/module_utils/network/f5/bigip.py\", line 32, in __init__\r\n  File \"/tmp/ansible_a3CLmr/ansible_modlib.zip/ansible/module_utils/network/f5/common.py\", line 396, in merge_provider_params\r\nAttributeError: 'NoneType' object has no attribute 'get'\r\n", "msg": "MODULE FAILURE", "rc": 1}

**Comment by caphrim007** [comment]
@glenpekarcsik hmmm...this is a head-scratcher. I will need to install an AWX to find out. It shouldn't be possible for you to get a `None` there like the error says.

**Comment by caphrim007** [comment]
@glenpekarcsik can you change your playbook you have there to do either;

1. Add a `connection: local` to your playbook
2. Add a `delegate_to: localhost` to your task

The delegate_to should look like this

```
     - name: create a pool
       bigip_pool:
           lb_method: ratio-member
           name: web-test
           password: ***********
           server: sdc01testgtm1
           slow_ramp_time: 120
           user: f5user
           validate_certs: no
       delegate_to: localhost
```
