### ISSUE TITLE
Allow additional types in the bigip_log_destination module

### ISSUE THREAD

**Issue by tdm00** [F5Networks/f5-ansible#824]
##### ISSUE TYPE

 - Feature Idea

##### COMPONENT NAME

The bigip_log_destination module type field has two options presently available, remote-high-speed-log and remote-syslog. However there is actually six different types that are configurable for this within the BIG-IP system. Can these be added as additional options for this type field?

##### ANSIBLE VERSION

```
ansible 2.6.1
  config file = /var/ansible/ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.15rc1 (default, Apr 15 2018, 21:51:34) [GCC 7.3.0]
```

##### PYTHON VERSION

```
Python 2.7.15rc1
```

##### BIGIP VERSION

```
Sys::Version
Main Package
  Product     BIG-IP
  Version     13.1.0.7
  Build       0.0.1
  Edition     Point Release 7
  Date        Tue May 15 15:26:30 PDT 2018
```

##### LIBRARY VERSIONS

```
bigsuds==1.0.6
f5-sdk==3.0.17
```

##### CONFIGURATION

```
N/A
```

##### OS / ENVIRONMENT

```
N/A
```
##### SUMMARY

Add the additional types of remote high-speed log destinations types that are available within the BIG-IP system to the possible list of valid values within this module.

##### STEPS TO REPRODUCE

```
- name: Create a high-speed logging destination
  bigip_log_destination:
    name: foo
    type: splunk
    pool_settings:
      pool: my-ltm-pool
    password: secret
    server: lb.mydomain.com
    state: present
    user: admin
  delegate_to: localhost
```

##### ACTUAL RESULTS

```

```
