### ISSUE TITLE
Add description parameter to all bigip_monitor modules

### ISSUE THREAD

**Issue by rfults** [F5Networks/f5-ansible#827]
##### ISSUE TYPE

 - Feature Idea

##### COMPONENT NAME

 bigip_monitor_*
##### ANSIBLE VERSION

```
ansible 2.6.2
```

##### PYTHON VERSION

```
Python 2.7.5
```

##### BIGIP VERSION

```
Viprion 2150:
  Product     BIG-IP
  Version     13.1.0.5
  Build       0.0.5
  Edition     Point Release 5
```

##### LIBRARY VERSIONS

```
bigsuds==1.0.6
f5-sdk==3.0.18
```

##### OS / ENVIRONMENT

N/A
##### SUMMARY

Add description parameter to all bigip_monitor modules.  It seems to exist in some of the more recent modules.  It seems inconsistent not adding it to all of them.
##### STEPS TO REPRODUCE

```
- name: Create HTTP Monitor
  bigip_monitor_http:
    state: present
    ip: 10.10.10.10
    description: web server http monitor
    server: lb.mydomain.com
    user: admin
    password: secret
    name: my_http_monitor
  delegate_to: localhost
```

##### ACTUAL RESULTS

```

```
