### ISSUE TITLE
bigip_wait with 'ssh_keyfile'

### ISSUE THREAD

**Issue by payalsin** [F5Networks/f5-ansible#842]
bigip_wait is hanging when using ssh_keyfile

```
- name: Wait for BIG-IP to boot up completely
      bigip_wait:
        provider:
          ssh_keyfile: "key-private.pem"
          transport: cli
          user: admin
          server: "<ip_address>"
```

**Use case:** When spinning up BIG-IP in the cloud, the admin password in unknown and to make sure bigip is ready for further configuration the bigip_wait can be handy using the ssh_keyfile.
