### ISSUE TITLE
bigip_user fails on creating or deleting of user account.

### ISSUE THREAD

**Issue by slavkv** [F5Networks/f5-ansible#85]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME
bigip_user

##### ANSIBLE VERSION

```
ansible 2.2.1.0
  config file =
  configured module search path = Default w/o overrides
```

##### PYTHON VERSION

```
Python 2.7.13
```

##### BIGIP VERSION
```
Sys::Version
Main Package
  Product  BIG-IP
  Version  11.5.1
  Build    8.0.175
  Edition  Hotfix HF8
  Date     Mon Feb  9 00:49:11 PST 2015
```

##### CONFIGURATION
host_key_checking = False
ask_pass=False

##### OS / ENVIRONMENT
OSX 10.11.6

##### SUMMARY
Module 'bigip_user' fails when I try to create or delete user. I am using example from documentation.
Modules 'bigip_command' and 'bigip_user_facts' work fine.

##### STEPS TO REPRODUCE

```
  - name: Add user accounts
    bigip_user:
      server: "{{ device_hostname | default(inventory_hostname) }}"
      user: "{{ device_user }}"
      password: "{{ device_pass }}"
      validate_certs: false
      username_credential: "testuser5"
      password_credential: "adasdasdafsafasdf"
      partition_access: "all:admin"
      full_name: "John Doe"
      shell: "bash"
      state: "present"
    delegate_to: localhost
```

##### EXPECTED RESULTS

A user "testuser5" is created.

##### ACTUAL RESULTS

```
fatal: [myf5box -> localhost]: FAILED! => {
    "changed": false,
    "failed": true,
    "invocation": {
        "module_name": "bigip_user"
    },
    "module_stderr": "/usr/local/Cellar/ansible/2.2.1.0/libexec/lib/python2.7/site-packages/requests/packages/urllib3/connectionpool.py:843: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings\n  InsecureRequestWarning)\n/usr/local/Cellar/ansible/2.2.1.0/libexec/lib/python2.7/site-packages/requests/packages/urllib3/connectionpool.py:843: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings\n  InsecureRequestWarning)\nTraceback (most recent call last):\n  File \"/var/folders/4k/lxknkpkn0wg4bmmjwrmb5b8mk_gp_p/T/ansible_gfNAOQ/ansible_module_bigip_user.py\", line 589, in <module>\n    main()\n  File \"/var/folders/4k/lxknkpkn0wg4bmmjwrmb5b8mk_gp_p/T/ansible_gfNAOQ/ansible_module_bigip_user.py\", line 578, in main\n    result = obj.apply_changes()\n  File \"/var/folders/4k/lxknkpkn0wg4bmmjwrmb5b8mk_gp_p/T/ansible_gfNAOQ/ansible_module_bigip_user.py\", line 204, in apply_changes\n    changed = self.present()\n  File \"/var/folders/4k/lxknkpkn0wg4bmmjwrmb5b8mk_gp_p/T/ansible_gfNAOQ/ansible_module_bigip_user.py\", line 218, in present\n    return self.ensure_user_is_present()\n  File \"/var/folders/4k/lxknkpkn0wg4bmmjwrmb5b8mk_gp_p/T/ansible_gfNAOQ/ansible_module_bigip_user.py\", line 421, in ensure_user_is_present\n    params = self.get_user_creation_parameters()\n  File \"/var/folders/4k/lxknkpkn0wg4bmmjwrmb5b8mk_gp_p/T/ansible_gfNAOQ/ansible_module_bigip_user.py\", line 445, in get_user_creation_parameters\n    if self.can_have_advanced_shell_upon_creation():\n  File \"/var/folders/4k/lxknkpkn0wg4bmmjwrmb5b8mk_gp_p/T/ansible_gfNAOQ/ansible_module_bigip_user.py\", line 456, in can_have_advanced_shell_upon_creation\n    for x in self.params['partitionAccess']:\nKeyError: 'partitionAccess'\n",
    "module_stdout": "",
    "msg": "MODULE FAILURE"
}
```

Not sure what I am doing wrong.
