### ISSUE TITLE
Module to work with ZebOS CLI / imish

### ISSUE THREAD

**Issue by pbaitule** [F5Networks/f5-ansible#852]
##### ISSUE TYPE

 - Feature Idea

##### COMPONENT NAME

- bigip_imish

##### ANSIBLE VERSION

```
ansible 2.6.2
  config file = /home/pbaitule/AnsibleProjects/ansible-plays/route-reach-tests/ansible.cfg
  configured module search path = [u'/home/pbaitule/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /home/pbaitule/.virtualenvs/route-reach-tests/lib/python2.7/site-packages/ansible
  executable location = /home/pbaitule/.virtualenvs/route-reach-tests/bin/ansible
  python version = 2.7.15 (default, May 16 2018, 17:50:09) [GCC 8.1.1 20180502 (Red Hat 8.1.1-1)]

```

##### PYTHON VERSION

```
Python 2.7.15
```

##### BIGIP VERSION

```
Sys::Version
Main Package
  Product  BIG-IP
  Version  11.5.4
  Build    4.0.313
  Edition  Hotfix HF4
  Date     Tue Apr 11 15:28:56 PDT 2017

```

##### LIBRARY VERSIONS

```
f5-sdk==3.0.19
bigsuds==1.0.6
```

##### OS / ENVIRONMENT

- Fedora 28

##### SUMMARY

Verify and/or configure BIG-IP Advanced Routing BGP/OSPF/IS-IS/... using Ansible.

##### STEPS TO REPRODUCE

```
N/A
```

##### EXPECTED RESULTS

Example:
- Verify routing table
    - show ip route 0.0.0.0
- Basic routing protocol configuration

##### ACTUAL RESULTS

```
N/A
```

**Comment by caphrim007** [comment]
@pbaitule new ansible modules are written to support 12.x and beyond. For your case, 11.x, the bigip_command module is the only one expected to work. While we can add this module to our todo list, it will not be for versions < 12

**Comment by caphrim007** [comment]
@pbaitule you can also (on 12.x and greater) accomplish the imish related work by using ansible's `copy` or `template` modules and the `command` module to load the imish config into the box.

**Comment by pbaitule** [comment]
@caphrim007 We may upgrade to version 12.x or greater soon. For now, I am just using the command module. One of the plays in my playbook looks like this - 
```
- name: Test for default route
  hosts: bigip
  gather_facts: no
  tasks:
    - block:
        - name: Check for v4 default
          bigip_command:
            commands:
              - zebos -r 0 cmd show ip route 0.0.0.0
            server: "{{ ansible_host }}"
            user: "{{ ansible_user }}"
            password: "{{ ansible_password }}"
            transport: "{{ bigip_transport }}"
            validate_certs: False
          register: def_route
          delegate_to: localhost
        - assert:
            that:
              - "'Routing entry for 0.0.0.0' in def_route.stdout_lines[0][2]"
            msg: "No default"
        - name: Check for v6 default
          bigip_command:
            commands:
              - 'zebos -r 0 cmd show ipv6 route ::' 
            server: "{{ ansible_host }}"
            user: "{{ ansible_user }}"
            password: "{{ ansible_password }}"
            transport: "{{ bigip_transport }}"
            validate_certs: False
          register: def_route
          delegate_to: localhost
        - assert:
            that:
              - "'Routing entry for ::' in def_route.stdout_lines[0][2]"
            msg: "No default"
      tags:
        - bigip

```
I'm not sure if tweaking an existing module like `bigip_management_route` or `bigip_static_route` could be used to do this in a more 'cleaner' way.
