### ISSUE TITLE
New module - bigip_profile_http

### ISSUE THREAD

**Issue by rfults** [F5Networks/f5-ansible#854]
##### ISSUE TYPE

 - Feature Idea

##### COMPONENT NAME

bigip_profile_http 
##### ANSIBLE VERSION

```
ansible 2.6.2
```

##### PYTHON VERSION

```
Python 2.7.5
```

##### BIGIP VERSION

```
Viprion 2150:
  Product     BIG-IP
  Version     13.1.0.5
  Build       0.0.5
  Edition     Point Release 5
```

##### LIBRARY VERSIONS

```
bigsuds==1.0.6
f5-sdk==3.0.18
```

##### OS / ENVIRONMENT

N/A
##### SUMMARY

Requesting new module to support management of HTTP service profiles in BIGIP as they are one of the most commonly created profiles. All options would be nice to have in order to allow the most flexibility however my example includes some of the options I use most commonly.

##### STEPS TO REPRODUCE

```
- name: Create an HTTP profile
  bigip_profile_http:
    name: foo
    description: http custom profile for foo
    insert_xforwarded_for: enabled
    parent: http
    proxy_type: reverse
    redirect-rewrite: all
    state: present
    encrypt_cookie_secret: supersecretpassword
    encrypt-cookies: encrypted_store_cookie
  provider: "{{ provider }}"
  delegate_to: localhos
```

##### ACTUAL RESULTS

```

```
