### ISSUE TITLE
Issue with adding subnet in  bigip_static_route

### ISSUE THREAD

**Issue by ishuguru** [F5Networks/f5-ansible#865]
##### ISSUE TYPE

 - Bug Report

##### ANSIBLE VERSION

```
ansible 2.7.0.dev0
```

##### PYTHON VERSION

```
Python 2.7.5
```

##### BIGIP VERSION

```
BIP-IP 13.1.0.8 Build 0.0.3

```

##### LIBRARY VERSIONS

```
f5-sdk==3.0.18
```

##### OS / ENVIRONMENT

Red Hat 7.5

##### SUMMARY

I try to add a /24 as a static route, but it use the netmask 255.255.255.255 even if i write 255.255.255.0
it work with /32 mask, but i want to add a route for the entire network
##### STEPS TO REPRODUCE

```
---
-  name: yoyo
   connection: local
   hosts: [ltm-dev]
   gather_facts: False

   vars_prompt:
    - name: "password"
      prompts: "enter password"
      private: yes

   vars:
    provider_bigip:
      user: mrcool
      password: "{{ password }}"
      server_port: 443
   tasks:
    - name: add static route
      bigip_static_route:
        destination: 192.168.0.0
        netmask: 255.255.255.0
        gateway_address: 1.1.1.1
        name: 123
        server: "{{inventory_hostname}}"
        provider: "{{ provider_bigip }}"
        validate_certs: no
      delegate_to: localhost

```

##### EXPECTED RESULTS

The route added as a /24 mask
##### ACTUAL RESULTS

It gets a /32 mask
TASK [add static route] **************************************************************************************************************
changed: [ltm01 -> localhost] => {
    "changed": true, 
    "destination": "192.168.0.0/32", 
    "gateway_address": "1.1.1.1", 
    "invocation": {
        "module_args": {
            "description": null, 
            "destination": "192.168.0.0", 
            "gateway_address": "1.1.1.1", 
            "mtu": null, 
            "name": "123", 
            "netmask": "255.255.255.0", 
            "partition": "Common", 
            "password": null, 
            "pool": null, 
            "provider": {
                "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER", 
                "server": "ltm01", 
                "server_port": 443, 
                "ssh_keyfile": null, 
                "timeout": null, 
                "transport": "rest", 
                "user": "mrcool", 
                "validate_certs": false
            }, 
            "reject": null, 
            "route_domain": null, 
            "server": "ltm01", 
            "server_port": null, 
            "state": "present", 
            "transport": null, 
            "user": null, 
            "validate_certs": false, 
            "vlan": null
        }
    }, 
    "netmask": 32
}
changed: [ltm01 -> localhost] => {
    "changed": true, 
    "destination": "192.168.0.0/32", 
    "gateway_address": "1.1.1.1", 
    "invocation": {
        "module_args": {
            "description": null, 
            "destination": "192.168.0.0", 
            "gateway_address": "1.1.1.1", 
            "mtu": null, 
            "name": "123", 
            "netmask": "255.255.255.0", 
            "partition": "Common", 
            "password": null, 
            "pool": null, 
            "provider": {
                "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER", 
                "server": "ltm01", 
                "server_port": 443, 
                "ssh_keyfile": null, 
                "timeout": null, 
                "transport": "rest", 
                "user": "mrcool", 
                "validate_certs": false
            }, 
            "reject": null, 
            "route_domain": null, 
            "server": "ltm01", 
            "server_port": null, 
            "state": "present", 
            "transport": null, 
            "user": null, 
            "validate_certs": false, 
            "vlan": null
        }
    }, 
    "netmask": 32
}
META: ran handlers
META: ran handlers

PLAY RECAP ********************************************************************************************************************************************************
ltm01 : ok=1    changed=1    unreachable=0    failed=0   
ltm01 : ok=1    changed=1    unreachable=0    failed=0   

```

```
