### ISSUE TITLE
[Request Module] bigip_virtual_server.py

### ISSUE THREAD

**Issue by minw9545** [F5Networks/f5-ansible#868]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

- module

##### ANSIBLE VERSION

```
2.4.0
```

##### PYTHON VERSION

```
2.7
```

##### BIGIP VERSION

```
12.1.2
```

##### LIBRARY VERSIONS

```
bigsuds==1.0.6
f5-sdk==3.0.18
```

##### CONFIGURATION

```
      - name: "Create Virtual Server"
        bigip_virtual_server:
            description: "Create a LTM Virtual Server for Basic SLB"
            name: "TEST_VS_Asible"
#            partition: "Common"
#            source: "0.0.0.0/0"
#            type: "standard"
#            destination: "50.0.0.53"
#            port: "80"
#            ip_protocol: "tcp"
#            profiles:
#              - "tcp_30M"
#              - "http"
#            snat: "none"
#            enabled_vlans: "all"
#            pool: "TEST_Pool_Ansible"
#            irules: "TEST_Ansile_Rule"
#            address_translation: "yes"
#            port_translation: "yes"
            default_persistence_profile: ""
```

##### OS / ENVIRONMENT

N/A

##### SUMMARY

Our customers are using ansible version v.2.4.0.

Our customer tries the following settings in VS settings.

=> default_persistence_profile: ""

However, this feature is not supported in v2.4.0.

Our customers are reluctant to upgrade.

Can you help me with ansible v2.4.0?

Thank you.

##### STEPS TO REPRODUCE

```

```

##### ACTUAL RESULTS

```

    "msg": "received exception: Error on setting default persistence profile : Server raised fault: 'Exception caught in LocalLB::urn:iControl:LocalLB/VirtualServer::add_persistence_profile()\nException: Common::OperationFailed\n\tprimary_error_code   : 16908342 (0x01020036)\n\tsecondary_error_code : 0\n\terror_string         : 01020036:3: The requested persist profile (/Common) was not found.'"


```
