### ISSUE TITLE
After SSL setting, "The python f5-sdk module is required"

### ISSUE THREAD

**Issue by yunithon** [F5Networks/f5-ansible#883]
After SSL setting, "The python f5-sdk module is required"

##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

bigip_pool_member

##### ANSIBLE VERSION

```
# ansible --version
ansible 2.6.0
  config file = /opt/ansible/ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /bin/ansible
  python version = 2.7.5 (default, Feb 20 2018, 09:19:12) [GCC 4.8.5 20150623 (Red Hat 4.8.5-28)]
```

##### PYTHON VERSION

```
Python 2.7.5
```

##### BIGIP VERSION

```
Sys::Version
Main Package
  Product     BIG-IP
  Version     12.1.1
  Build       0.0.184
  Edition     Final
  Date        Thu Aug 11 17:09:01 PDT 2016
```

##### LIBRARY VERSIONS

```
bigsuds==1.0.6
f5-sdk==3.0.17
```

##### CONFIGURATION

```
# cat ansible.cfg
[defaults]
log_path = ./log/ansible_opelog.log
roles_path = ./tasks/
deprecation_warnings=False
private_key_file=~/.ssh/id_rsa
```

##### OS / ENVIRONMENT

```
Red Hat Enterprise Linux Server release 7.5 (Maipo)
Linux version 3.10.0-862.3.3.el7.x86_64 (mockbuild@x86-034.build.eng.bos.redhat.com) (gcc version 4.8.5 20150623 (Red Hat 4.8.5-28) (GCC) ) #1 SMP Wed Jun 13 05:44:23 EDT 2018
```

##### SUMMARY

After setting SSH public key authentication, my Playbook doesn't work.
I have seen other Issues reported similar error, and I found the solution adding "connection: to local".
However, I got the different error "The specified pool does not exist"
I dont know how to solve the problem. Can you plese help me.

```
- hosts: targets
  gather_facts: False
  serial: 1

  tasks:
   - name: Force pool member offline
     bigip_pool_member:
        server: "192.168.0.21"
        state: disabled
        pool: "test_pool"
        partition: Common
        port:  30011
        validate_certs: "no"

   - name: Force pool member offline
     bigip_pool_member:
        server: "192.168.0.21"
        state: disabled
        pool: "test_pool"
        partition: Common
        port:  31011
        validate_certs: "no"

   - name: Force pool member offline
     bigip_pool_member:
        server: "192.168.0.21"
        state: disabled
        pool: "test_pool"
        partition: Common
        port:  32011
        validate_certs: "no"

```
##### ACTUAL RESULTS

```
PLAY [targets] ******************************************************************************************************

TASK [Force pool member offline] ************************************************************************************
fatal: [192.168.0.21]: FAILED! => {"changed": false, "msg": "The python f5-sdk module is required"}
        to retry, use: --limit @/opt/ansible/tasks/dispoolmember.retry

PLAY RECAP **********************************************************************************************************
192.168.0.21               : ok=0    changed=0    unreachable=0    failed=1

```
