### ISSUE TITLE
bigip_policy_rule with adtional options 

### ISSUE THREAD

**Issue by onurbrc** [F5Networks/f5-ansible#889]
##### ISSUE TYPE

 - Feature Idea

##### COMPONENT NAME

bigip_policy_rule
##### ANSIBLE VERSION

```
ansible 2.6.1
  config file = /home/ansible/myAnsible/ansible.cfg
  configured module search path = [u'/home/ansible/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python2.7/dist-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 2.7.15rc1 (default, Apr 15 2018, 21:51:34) [GCC 7.3.0]
```

##### PYTHON VERSION

```
Python 2.7.15rc1
```

##### BIGIP VERSION

```
BIG-IP 12.1.3 Build 0.0.378 Final
```

##### LIBRARY VERSIONS

```
bigsuds==1.0.6
f5-sdk==3.0.18
```

##### OS / ENVIRONMENT

```
inventory = ~/myAnsible/inventory/hosts
roles_path = ~/myAnsible/roles/
callback_whitelist = profile_tasks
```
##### SUMMARY

We use to create a policy to do the redirection of http to https for all virtual servers listening on 80 or 443 ports. The CLI example as follow : 
```
create ltm policy http2https
  strategy all-match
  requires add { http }
  controls add { forwarding }
  rules add {
    <RuleName> {
      actions replace-all-with {
        0 {
          http-reply redirect
          location ""https://[getfield [HTTP::host] \"":\"" 1][HTTP::uri]""
        }
      }
    }
  }
```

##### STEPS TO REPRODUCE

```
We imagine the playbook with the "redirect" action type after the policy creation: 

- name: add http2https policy
  bigip_policy:
    name: http2https
    state: present
  delegate_to: localhost

- name: add policy rules
  bigip_policy_rule:
    policy: http2https
    name: http2https
    actions:
      - type: redirect
        location: "tcl:https://[getfield [HTTP::host] \":\" 1][HTTP::uri]"
  delegate_to: localhost
```

##### EXPECTED RESULTS

```
ltm policy http2https {
    controls { forwarding }
    requires { http }
    rules {
        http2https {
            actions {
                0 {
                    http-reply
                    redirect
                    location "tcl:https://[getfield [HTTP::host] \":\" 1][HTTP::uri]"
                }
            }
        }
    }
    status published
    strategy all-match
}
```
##### ACTUAL RESULTS

No results tested with this required option. 

```

```
