### ISSUE TITLE
bigip_profile_client_ssl does not inherit ciphers from parent profile as it should.

### ISSUE THREAD

**Issue by slavkv** [F5Networks/f5-ansible#904]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME
bigip_profile_client_ssl

##### ANSIBLE VERSION

```
ansible 2.6.3
```

##### PYTHON VERSION

```
Python 2.7.15
```

##### BIGIP VERSION

```
Sys::Version
Main Package
  Product     BIG-IP
  Version     12.1.3.4
  Build       0.0.2
  Edition     Point Release 4
```

##### LIBRARY VERSIONS

```
f5-sdk==3.0.20
```

##### CONFIGURATION

[defaults]
remote_user = admin
host_key_checking = False
ask_pass=False

##### OS / ENVIRONMENT

OSX, virtualenv

##### SUMMARY

A new Client SSL profile properties must inherit properties from parent SSL profile by default unless they are specified. Only Client SSL profile 'Name' must be defined.

Example from Web GUI.
If I go to "Local Traffic  ››  Profiles : SSL : Client" and click "Create", I must fill 'Name' field only and the rest will inherit properties from a parent SSL profile which is 'clients' by default. So, if I do not specify ciphers in a new profile (select Custom; then type ciphers) it must inherit ciphers from the parent profile (and if I change ciphers in the parent profile LTM will reflect changes on my new profile).

bigip_profile_client_ssl must inherit ciphers (and other properties) of the parent ssl profile when is created (if a parent profile is not specified then default clientssl is used).

currently => bigip_profile_client_ssl put a default value of 'DEFAULT' when "ciphers" is not defined, which is a customisation. (LTM behaves differently)

##### STEPS TO REPRODUCE

Issue 1.

    - name: Create BASE client SSL profiles
      bigip_profile_client_ssl:
        provider: "{{ f5_cli }}"
        state: present
        name: TEST_BASE_profile
        ciphers: "TLSv1_2:TLSv1_1"
        cert_key_chain:
          - cert: test_self_signed.crt
            key: test_self_signed.key
      delegate_to: localhost

    - name: Create CHILD client SSL profiles
      bigip_profile_client_ssl:
        provider: "{{ f5_cli }}"
        state: present
        name: TEST_CHILD_profile
        parent: TEST_BASE_profile
      delegate_to: localhost

Results:

```
ltm profile client-ssl TEST_BASE_profile {
    app-service none
    cert test_self_signed.crt
    cert-key-chain {
        test_self_signed {
            cert test_self_signed.crt
            key test_self_signed.key
        }
    }
    chain none
    ciphers TLSv1_2:TLSv1_1
    defaults-from clientssl
    inherit-certkeychain false
    key test_self_signed.key
    passphrase none
}
ltm profile client-ssl TEST_CHILD_profile {
    app-service none
    cert test_self_signed.crt
    cert-key-chain {
        test_self_signed {
            cert test_self_signed.crt
            key test_self_signed.key
        }
    }
    chain none
    ciphers DEFAULT
    defaults-from TEST_BASE_profile
    inherit-certkeychain true
    key test_self_signed.key
    passphrase none
}
```
ciphers DEFAULT must not be a default value.

Below is a result of GUI which has a correct inheritance.

```
# Profile created in WEB with name and parent profile set to TEST_BASE_profile
ltm profile client-ssl TEST_GUI {
    app-service none
    cert test_self_signed.crt
    cert-key-chain {
        test_self_signed {
            cert test_self_signed.crt
            key test_self_signed.key
        }
    }
    chain none
    defaults-from TEST_BASE_profile
    inherit-certkeychain true
    key test_self_signed.key
    passphrase none
}
ltm profile client-ssl TEST_GUI {
    ciphers TLSv1_2:TLSv1_1
}
```

##### EXPECTED RESULTS

_(no ciphers output here as it is inherited, shown in a second output)_
```
ltm profile client-ssl TEST_CHILD_profile {
    app-service none
    cert test_self_signed.crt
    cert-key-chain {
        test_self_signed {
            cert test_self_signed.crt
            key test_self_signed.key
        }
    }
    chain none
    defaults-from TEST_BASE_profile
    inherit-certkeychain true
    key test_self_signed.key
    passphrase none
}
```
```
# list ltm profile client-ssl TEST_CHILD_profile ciphers
ltm profile client-ssl TEST_CHILD_profile {
    ciphers TLSv1_2:TLSv1_1
}
```

**Comment by wojtek0806** [comment]
Tested on 12.1.3.6 0.0.3:

````
root@(ansible_test_lab12)(cfg-sync Standalone)(Active)(/Common)(tmos)# list ltm profile client-ssl TEST_BASE_profile 
ltm profile client-ssl TEST_BASE_profile {
    app-service none
    cert default.crt
    cert-key-chain {
        default {
            cert default.crt
            key default.key
        }
    }
    chain none
    ciphers TLSv1_2:TLSv1_1
    defaults-from clientssl
    inherit-certkeychain false
    key default.key
    passphrase none
}
root@(ansible_test_lab12)(cfg-sync Standalone)(Active)(/Common)(tmos)# list ltm profile client-ssl TEST_CHILD_profile 
ltm profile client-ssl TEST_CHILD_profile {
    app-service none
    cert default.crt
    cert-key-chain {
        default {
            cert default.crt
            key default.key
        }
    }
    chain none
    defaults-from TEST_BASE_profile
    inherit-certkeychain true
    key default.key
    passphrase none
}
````

Tested on 13.1.0.8  0.0.3:

````

root@(ansible_test_lab13)(cfg-sync Standalone)(Active)(/Common)(tmos)# list ltm profile client-ssl TEST_BASE_profile
ltm profile client-ssl TEST_BASE_profile {
    app-service none
    cert default.crt
    cert-key-chain {
        default {
            cert default.crt
            key default.key
        }
    }
    chain none
    cipher-group none
    ciphers TLSv1_2:TLSv1_1
    defaults-from clientssl
    inherit-certkeychain false
    key default.key
    passphrase none
}
root@(ansible_test_lab13)(cfg-sync Standalone)(Active)(/Common)(tmos)# list ltm profile client-ssl TEST_CHILD_profile
ltm profile client-ssl TEST_CHILD_profile {
    app-service none
    cert default.crt
    cert-key-chain {
        default {
            cert default.crt
            key default.key
        }
    }
    chain none
    defaults-from TEST_BASE_profile
    inherit-certkeychain true
    key default.key
    passphrase none
}
````

**Comment by wojtek0806** [comment]
my playbook:
```
- name: Create profiles
  hosts: f5-test
  connection: local

  vars:
    provider:
      password: "pass"
      server: "{{ ansible_host }}"
      user: "someuser"
      validate_certs: "no"
      server_port: "443"

  tasks:
    - name: Create BASE client SSL profiles
      bigip_profile_client_ssl:
        provider: "{{ provider }}"
        state: present
        name: TEST_BASE_profile
        ciphers: "TLSv1_2:TLSv1_1"
        cert_key_chain:
          - cert: default.crt
            key: default.key
      delegate_to: localhost

    - name: Create CHILD client SSL profiles
      bigip_profile_client_ssl:
        provider: "{{ provider }}"
        state: present
        name: TEST_CHILD_profile
        parent: TEST_BASE_profile
      delegate_to: localhost
```
