### ISSUE TITLE
bigip_software_install module error

### ISSUE THREAD

**Issue by adolphsons** [F5Networks/f5-ansible#925]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

bigip_software_install.py

##### ANSIBLE VERSION

```
ansible 2.6.2
```

##### PYTHON VERSION

```
Python 2.7.5
```

##### BIGIP VERSION

```
Sys::Version
Main Package
  Product     BIG-IP
  Version     12.1.0
  Build       0.0.1434
  Edition     Final
  Date        Wed May 11 11:45:11 PDT 2016
```

##### LIBRARY VERSIONS

```
f5-sdk==3.0.20
```

##### OS / ENVIRONMENT

N/A

##### SUMMARY
bigip_software_install fails with error: KeyError: 'kind'

##### STEPS TO REPRODUCE

```
- name: Ensure an existing image is installed in specified volume
  bigip_software_install:
    image: Hotfix-BIGIP-13.1.0.7.0.45.1-ENG.iso
    volume: HD1.2
    state: installed
    provider:
      user: "admin"
      password: "{{ passwd }}"
      server: "{{IP_Address}}"
    validate_certs: "no"
  delegate_to: localhost
  tags: install_test
```

##### EXPECTED RESULTS

```
Software deployed to remote BigIP
```
##### ACTUAL RESULTS

```
 ansible-playbook mop_f5_software_13_1_0.yml --tags install_test

PLAY [F5 Software Upgrade] *********************************************************************************************************

TASK [f5_upgrade : Ensure an existing image is installed in specified volume] ******************************************************
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: KeyError: 'kind'

fatal: [f5001 -> localhost]: FAILED! => {"changed": false, "module_stderr": "Traceback (most recent call last):
  File \"/tmp/ansible_hMxNkq/ansible_module_bigip_software_install.py\", line 502, in <module>
    main()
  File \"/tmp/ansible_hMxNkq/ansible_module_bigip_software_install.py\", line 495, in main
    results = mm.exec_module()
  File \"/tmp/ansible_hMxNkq/ansible_module_bigip_software_install.py\", line 302, in exec_module
    changed = self.present()
  File \"/tmp/ansible_hMxNkq/ansible_module_bigip_software_install.py\", line 323, in present
    return self.update()
  File \"/tmp/ansible_hMxNkq/ansible_module_bigip_software_install.py\", line 384, in update
    self.update_on_device()
  File \"/tmp/ansible_hMxNkq/ansible_module_bigip_software_install.py\", line 400, in update_on_device
    self.want.image_type
  File \"/tmp/ansible_hMxNkq/ansible_module_bigip_software_install.py\", line 181, in image_type
    if 'software:image' in self.image_info['kind']:
KeyError: 'kind'
", "module_stdout": "", "msg": "MODULE FAILURE", "rc": 1}

PLAY RECAP *************************************************************************************************************************
localhost                  : ok=1    changed=0    unreachable=0    failed=0   
f5001                       : ok=0    changed=0    unreachable=0    failed=1   

```
