### ISSUE TITLE
bigip_static_route does not working with route domain and partition.

### ISSUE THREAD

**Issue by onurbrc** [F5Networks/f5-ansible#945]
Hello, 

I'm trying to create a static route within a partition and a route domain, but I don't have the same result as the CLI. 
My context : 
##### ANSIBLE VERSION

```
ansible 2.6.1
  config file = /home/ansible/myAnsible/ansible.cfg
  configured module search path = [u'/home/ansible/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python2.7/dist-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 2.7.15rc1 (default, Apr 15 2018, 21:51:34) [GCC 7.3.0]
```

##### PYTHON VERSION

```
Python 2.7.15rc1
```

##### BIGIP VERSION

```
BIG-IP 12.1.3 Build 0.0.378 Final
```

##### LIBRARY VERSIONS

```
bigsuds==1.0.6
f5-sdk==3.0.18
netaddr==0.7.19
```

Partition and route domain : 
```
- Partition: internet
- Route domain: 2 created for the partition internet. 
```
Playbook : 
```
tasks:
     - name: Creating a default static route
        bigip_static_route:
            destination: 0.0.0.0
            netmask: 0.0.0.0
            gateway_address: 10.10.5.254
            partition: "{{ PARTITION }}"
            route_domain: 2
            name: default
            password: "{{ bigip_password }}"
            server: "{{ bigip_hostname }}"
            user: "{{ bigip_user }}"
            validate_certs: no
        delegate_to: localhost
```
CLI : (Active)(/internet)(tmos)# create net route default gw 10.10.5.254%2

Is there any difference between the syntax of the playbook and this command above ? 
When I try to execute the playbook I always get the stdout : 
```
 FAILED! => {"changed": false, "msg": "400 Unexpected Error: Bad Request for uri: https://@IP:443/mgmt/tm/net/route/\nText: u'{\"code\":400,\"message\":\"01070330:3: Static route gateway 10.10.5.254 is not directly connected via an interface.\",\"errorStack\":[],\"apiError\":3}'"}
```
However, I can pass the creation over CLI, the static route is created : 
```
(/internet)(tmos)# list net route
net route default {
    gw 10.10.5.254%2
    network default
    partition internet
}
```
Moreover, the selfip is in the same subnet domain. 
Any Help ?
Best regards.

**Comment by caphrim007** [comment]
@onurbrc are you creating a new route, or updating an existing one?

**Comment by onurbrc** [comment]
@caphrim007 I'm trying to create a new one.

**Comment by onurbrc** [comment]
@caphrim007 Does it work well for you when you try to create a new one ?

**Comment by onurbrc** [comment]
@delgadillo22 Does it work well for you when you try to create a new static route ?

**Comment by onurbrc** [comment]
Hello @caphrim007, 

Thank you for your explanation. 
I reviewed my actions and I have some observations. Could you please analyse them with me ? I think that it would be interesting to have an option inside the bigip_routedomain module to swap the parameter "Partition Default Route Domain" with the value "This route domain is the Partition Default Route Domain" if it is created within a partition. I'll give some details in the end. 

First of all, nothing changed about my context : 
```
- Partition: internet
- Route domain: 2  - created for the partition called "internet". 
```

And, 
```
- The selfip and vlan were already in the partition "internet"
```

Test 1 : 
```
tasks:
     - name: Creating a default static route
        bigip_static_route:
            destination: 0.0.0.0
            netmask: 0.0.0.0
            gateway_address: 10.10.5.254
            partition: internet
            route_domain: 2
            name: default
            password: "{{ bigip_password }}"
            server: "{{ bigip_hostname }}"
            user: "{{ bigip_user }}"
            validate_certs: no
        delegate_to: localhost
```
I thought that if I'm informing the route_domain and the partition, I would not need to put '%ID' after the gateway address, because the route domain that I'm using is already in the partition 'internet'. 
As you know, this didn't work for me. 
Error : 
```
"msg": "01070330:3: Static route gateway 10.10.5.254 is not directly connected via an interface."
```

Test 2 : in response to your suggestion 
```
     - name: Creating a default static route
        bigip_static_route:
            destination: 0.0.0.0
            netmask: 0.0.0.0
            gateway_address: 10.10.5.254%2
            partition: internet
            name: default
            password: "{{ bigip_password }}"
            server: "{{ bigip_hostname }}"
            user: "{{ bigip_user }}"
            validate_certs: no
        delegate_to: localhost
```
It worked for me beautifully. So, the parameter route_domain it was not necessary. I have as a result the route below : 
```
        net route default {
            gw 10.10.5.254%2
            network default%2
            partition internet
        }
```

Therefore, if I don't want to use the syntax above with '%ID', I changed manually the parameter "Partition Default Route Domain" with the value "This route domain is the Partition Default Route Domain" or using : 
```
modify auth partition internet default-route-domain 2
```
After that, I could create the static routes without errors not passing the '%ID' to the gateway : 
Test 3 :
```
     - name: Creating a default static route
        bigip_static_route:
            destination: 0.0.0.0
            netmask: 0.0.0.0
            gateway_address: 10.10.5.254
            partition: internet
            name: default
            password: "{{ bigip_password }}"
            server: "{{ bigip_hostname }}"
            user: "{{ bigip_user }}"
            validate_certs: no
        delegate_to: localhost
```
Result : 
```
(Active)(/internet)(tmos)# list net route
  net route default {
            gw 10.10.5.254
            network default
            partition internet
        }
```

The problem was that in the task which creates my partition, I didn't use the parameter "route_domain", because the creation of the route domain comes after in my sequence. 

So, which task comes first, the partition's creation or the route-domain's ? 
I don't know what to do in this case, because I've created my route domain inside the partition before. 

Is a good idea having a parameter in the module bigip_routedomain to update the partition's default-route-domain automatically ? 

Otherwise, I must do : 
```
1 - Run bigip_partition to create a partition 
2 - create a route-domain in that partition 
3 - Run again the bigip_partition to update the parameter  "default-route-domain"
4 - create the static routes 
```
What do you think ?

Sorry about this amount of text. :-D 
Thank you in advance. 
Best regards. 
BC

**Comment by caphrim007** [comment]
@onurbrc your sequence of events there is correct; there is not always a good reason to have another parameter added to a module. You have thought out the set of Tasks there and its clear what needs to be implemented in your Ansible playbook.

If there were a parameter to do such a thing, I imagine that it would require that the `partition` argument to the `bigip_routedomain` module be specified, and that it would be a simple boolean to indicate whether it is or is not.

For example

```
bigip_partition:
  name: foo

bigip_routedomain:
  name: 1
  partition: foo
  default_for_partition: yes
```

Which would be functionally equivalent to 

```
bigip_partition:
  name: foo
  ...

bigip_routedomain:
  name: 1
  partition: foo

bigip_partition:
  name: foo
  route_domain: xxx
```

would that meet your requirements?
