### ISSUE TITLE
bigip_virtual_server strips route domain

### ISSUE THREAD

**Issue by rdvn** [F5Networks/f5-ansible#959]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

bigip_virtual_server
##### ANSIBLE VERSION

```
ansible 2.6.4
  config file = None
  configured module search path = ['/Users/radovan/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.7/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 3.7.0 (default, Sep 16 2018, 19:30:47) [Clang 10.0.0 (clang-1000.10.43.1)]
```

##### PYTHON VERSION

```
Python 3.7.0
```

##### BIGIP VERSION

```
12.1.3.6
```

##### LIBRARY VERSIONS

```
bigsuds==1.0.6
f5-sdk==3.0.20
```

##### STEPS TO REPRODUCE

Run following play

```
---
- name: Test
  gather_facts: no
  hosts: f5
  connection: local
  tasks:
          - name: create test rd
            bigip_routedomain:
                    name: test-rd
                    id: 1234
                    state: present
                    provider:
                            user: "{{ bigip_user }}"
                            password: "{{ bigip_pass }}"
                            server: "{{ bigip_server }}"
                            server_port: "{{ bigip_port }}"
                            validate_certs: no

          - name: create test pool
            bigip_pool:
                    name: test-pool
                    state: present
                    provider:
                            user: "{{ bigip_user }}"
                            password: "{{ bigip_pass }}"
                            server: "{{ bigip_server }}"
                            server_port: "{{ bigip_port }}"
                            validate_certs: no

          - name: create test vs
            bigip_virtual_server:
                    name: test-vs
                    pool: test-pool
                    destination: "10.10.10.10%10"
                    port: 8080
                    provider:
                            user: "{{ bigip_user }}"
                            password: "{{ bigip_pass }}"
                            server: "{{ bigip_server }}"
                            server_port: "{{ bigip_port }}"
                            validate_certs: no
```

##### EXPECTED RESULTS

Play creates VS with address 10.10.10.10%10
##### ACTUAL RESULTS

Play creates VS with address 10.10.10.10

```
ltm virtual test-vs {
    destination 10.10.10.10:webcache
    ip-protocol tcp
    mask 255.255.255.255
    metadata {
        f5-ansible.last_modified {
            value "2018-09-25 13:25:21.394626"
        }
        f5-ansible.version {
            value 2.6.4
        }
    }
    pool test-pool
    profiles {
        tcp { }
    }
    source 0.0.0.0/0
    translate-address enabled
    translate-port enabled
    vs-index 7
}
```
