### ISSUE TITLE
bigip_virtual_server NOT idempotent when a partition is specified

### ISSUE THREAD

**Issue by erjac77** [F5Networks/f5-ansible#961]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME
bigip_virtual_server

##### ANSIBLE VERSION

```
ansible 2.6.3
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/osboxes/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.12 (default, Dec  4 2017, 14:50:18) [GCC 5.4.0 20160609]
```

##### PYTHON VERSION

```
Python 2.7.12
```

##### BIGIP VERSION

```
Sys::Version
Main Package
  Product     BIG-IP
  Version     12.1.2
  Build       0.0.249
  Edition     Final
  Date        Wed Nov 30 16:04:00 PST 2016
```

##### LIBRARY VERSIONS

```
f5-sdk==3.0.20
```

##### OS / ENVIRONMENT

```
Linux osboxes 4.4.0-131-generic #157-Ubuntu SMP Thu Jul 12 15:51:36 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
```

##### SUMMARY

`bigip_virtual_server` module always returns `"changed": true` when a partition other than `Common` is specified.

##### STEPS TO REPRODUCE

**Idempotent**
```
    - name: Create HTTP to HTTPS Redirection Virtual Server
      bigip_virtual_server:
        provider:
          server: "{{ ansible_host }}"
          user: "{{ http_user }}"
          password: "{{ http_pass }}"
          server_port: "{{ http_port }}"
          validate_certs: false
        name: http_to_https_redirect_virtual
        partition: Common
        description: HTTP to HTTPS Redirection Virtual
        destination: 10.10.10.10
        port: 80
        profiles:
          - tcp
          - http
        irules:
          - /Common/_sys_https_redirect
        state: present
      delegate_to: localhost
```

**NOT Idempotent**
```
    - name: Create HTTP to HTTPS Redirection Virtual Server
      bigip_virtual_server:
        provider:
          server: "{{ ansible_host }}"
          user: "{{ http_user }}"
          password: "{{ http_pass }}"
          server_port: "{{ http_port }}"
          validate_certs: false
        name: http_to_https_redirect_virtual
        partition: Test
        description: HTTP to HTTPS Redirection Virtual
        destination: 10.10.10.10
        port: 80
        profiles:
          - tcp
          - http
        irules:
          - /Common/_sys_https_redirect
        state: present
      delegate_to: localhost
```

##### EXPECTED RESULTS

If there was no changes to the resource, then ansible module should return `"changed": false`.

##### ACTUAL RESULTS

The return status is always `"changed": true`, even if there was no changes to the resource.

```
    changed: [my-big-ip -> localhost] => {
        "address_translation": false,
        "changed": true,
        "description": "HTTP to HTTPS Redirection Virtual",
        "destination": "10.10.10.10",
        "invocation": {
            "module_args": {
                "address_translation": null,
                "default_persistence_profile": null,
                "description": "HTTP to HTTPS Redirection Virtual",
                "destination": "10.10.10.10",
                "disabled_vlans": null,
                "enabled_vlans": null,
                "fallback_persistence_profile": null,
                "firewall_enforced_policy": null,
                "firewall_staged_policy": null,
                "ip_protocol": null,
                "irules": [
                    "/Common/_sys_https_redirect"
                ],
                "metadata": null,
                "name": "http_to_https_redirect_virtual",
                "partition": "Test",
                "password": null,
                "policies": null,
                "pool": null,
                "port": "80",
                "port_translation": null,
                "profiles": [
                    "tcp",
                    "http"
                ],
                "provider": {
                    "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
                    "server": "x.x.x.x",
                    "server_port": 443,
                    "ssh_keyfile": null,
                    "timeout": null,
                    "transport": "rest",
                    "user": "someuser",
                    "validate_certs": false
                },
                "security_log_profiles": null,
                "server": null,
                "server_port": null,
                "snat": null,
                "source": null,
                "state": "present",
                "transport": null,
                "type": "standard",
                "user": null,
                "validate_certs": null
            }
        },
        "irules": [
            "/Common/_sys_https_redirect"
        ],
        "port": 80,
        "port_translation": false,
        "profiles": [
            {
                "context": "all",
                "fullPath": "/Test/tcp",
                "name": "tcp"
            },
            {
                "context": "all",
                "fullPath": "/Test/http",
                "name": "http"
            }
        ],
        "type": "standard"
    }
```
