### ISSUE TITLE
HTTP Error 401: F5 Authorization Required since upgrade to Ansible 2.7

### ISSUE THREAD

**Issue by fad3t** [F5Networks/f5-ansible#976]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
bigip_virtual_server (but other modules seem to be impacted as well)

##### ANSIBLE VERSION
```
ansible 2.7.0
  config file = /root/frm/ansible/5-device-facts/ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python2.7/dist-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 2.7.9 (default, Jun 29 2016, 13:08:31) [GCC 4.9.2]
```

##### PYTHON VERSION
```
Python 2.7.9
```

##### BIGIP VERSION
```
Sys::Version
Main Package
  Product     BIG-IP
  Version     12.0.0
  Build       0.0.606
  Edition     Final
  Date        Fri Aug 21 13:29:22 PDT 2015
```

##### LIBRARY VERSIONS
```
bigsuds==1.0.6
f5-sdk==3.0.20
```

##### OS / ENVIRONMENT
Debian 8

##### SUMMARY
I upgraded Ansible to 2.7 this morning and since then it seems several modules aren't able to authenticate against the BIG-IP device.

##### STEPS TO REPRODUCE
Example playbook:
```
#!/usr/local/bin/ansible-playbook
---
- name: show version
  gather_facts: false
  hosts: all
  environment:
    http_proxy: ""
    https_proxy: ""
  vars:
    credsProvider:
      server: '{{ inventory_hostname }}'
      server_port: '443'
      user: 'admin'
      password: 'admin123'
      validate_certs: 'no'
      transport: 'rest'

  tasks:
    - name: create virtual server
      bigip_virtual_server:
        name: "testVS"
        destination: "10.0.0.50%3"
        port: "443"
        description: "test VS"
        pool: "FE-POOL-1"
        provider: '{{ credsProvider }}'
      delegate_to: localhost
```

##### EXPECTED RESULTS
New "testVS" created on the BIG-IP.

##### ACTUAL RESULTS
Nothing happening, playbook is throwing an authentication error.

```
ansible-playbook 2.7.0
  config file = /root/frm/ansible/4-vs-rd/ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python2.7/dist-packages/ansible
  executable location = /usr/local/bin/ansible-playbook
  python version = 2.7.9 (default, Jun 29 2016, 13:08:31) [GCC 4.9.2]
Using /root/frm/ansible/4-vs-rd/ansible.cfg as config file
Parsed /root/frm/ansible/4-vs-rd/hosts inventory source with ini plugin

PLAYBOOK: test.yml **************************************************************************************************************************************************************************************************************************
1 plays in test.yml

PLAY [show version] *************************************************************************************************************************************************************************************************************************
META: ran handlers

TASK [create virtual server] ****************************************************************************************************************************************************************************************************************
task path: /root/frm/ansible/4-vs-rd/test.yml:19
<localhost> ESTABLISH LOCAL CONNECTION FOR USER: root
<localhost> EXEC /bin/sh -c 'echo ~root && sleep 0'
<localhost> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /root/.ansible/tmp/ansible-tmp-1538656977.08-182592394014296 `" && echo ansible-tmp-1538656977.08-182592394014296="` echo /root/.ansible/tmp/ansible-tmp-1538656977.08-182592394014296 `" ) && sleep 0'
Using module file /usr/local/lib/python2.7/dist-packages/ansible/modules/network/f5/bigip_virtual_server.py
<localhost> PUT /root/.ansible/tmp/ansible-local-29569iTkQam/tmpiDEVGo TO /root/.ansible/tmp/ansible-tmp-1538656977.08-182592394014296/AnsiballZ_bigip_virtual_server.py
<localhost> EXEC /bin/sh -c 'chmod u+x /root/.ansible/tmp/ansible-tmp-1538656977.08-182592394014296/ /root/.ansible/tmp/ansible-tmp-1538656977.08-182592394014296/AnsiballZ_bigip_virtual_server.py && sleep 0'
<localhost> EXEC /bin/sh -c 'https_proxy='"'"''"'"' http_proxy='"'"''"'"' /usr/bin/python /root/.ansible/tmp/ansible-tmp-1538656977.08-182592394014296/AnsiballZ_bigip_virtual_server.py && sleep 0'
<localhost> EXEC /bin/sh -c 'rm -f -r /root/.ansible/tmp/ansible-tmp-1538656977.08-182592394014296/ > /dev/null 2>&1 && sleep 0'
The full traceback is:
WARNING: The below traceback may *not* be related to the actual failure.
  File "/tmp/ansible_bigip_virtual_server_payload_c9F5sh/__main__.py", line 3082, in main
    results = mm.exec_module()
  File "/tmp/ansible_bigip_virtual_server_payload_c9F5sh/__main__.py", line 2800, in exec_module
    changed = self.present()
  File "/tmp/ansible_bigip_virtual_server_payload_c9F5sh/__main__.py", line 2811, in present
    if self.exists():
  File "/tmp/ansible_bigip_virtual_server_payload_c9F5sh/__main__.py", line 2885, in exists
    resp = self.client.api.get(uri)
  File "/tmp/ansible_bigip_virtual_server_payload_c9F5sh/ansible_bigip_virtual_server_payload.zip/ansible/module_utils/network/f5/bigip.py", line 104, in api
    raise F5ModuleError(error)

fatal: [l20lbf02 -> localhost]: FAILED! => {
    "changed": false,
    "invocation": {
        "module_args": {
            "address_translation": null,
            "auth_provider": null,
            "default_persistence_profile": null,
            "description": "test VS",
            "destination": "10.0.0.50%3",
            "disabled_vlans": null,
            "enabled_vlans": null,
            "fallback_persistence_profile": null,
            "firewall_enforced_policy": null,
            "firewall_staged_policy": null,
            "ip_protocol": null,
            "irules": null,
            "metadata": null,
            "name": "testVS",
            "partition": "Common",
            "password": null,
            "policies": null,
            "pool": "FE-POOL-1",
            "port": "443",
            "port_translation": null,
            "profiles": null,
            "provider": {
                "auth_provider": null,
                "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
                "server": "l20lbf02",
                "server_port": 443,
                "ssh_keyfile": null,
                "timeout": null,
                "transport": "rest",
                "user": "admin",
                "validate_certs": false
            },
            "security_log_profiles": null,
            "security_nat_policy": null,
            "server": null,
            "server_port": null,
            "snat": null,
            "source": null,
            "state": "present",
            "transport": null,
            "type": "standard",
            "user": null,
            "validate_certs": null
        }
    },

    "msg": "Unable to connect to l20lbf02 on port 443. The reported error was \"Status code: None. 
Unexpected Error: HTTP Error 401: F5 
Authorization Required for uri: None\nText: <?xml 
version=\"1.0\" encoding=\"ISO-8859-1\"?
>\n<!DOCTYPE html PUBLIC \"-//W3C//DTD 
XHTML 1.0 Strict//EN\"\n  
\"http://www.w3.org/TR/xhtml1/DTD/xhtml1-
strict.dtd\">\n<html 
xmlns=\"http://www.w3.org/1999/xhtml\" 
lang=\"en\" xml:lang=\"en\">\n<head>\n<title>Authentication 
required!</title>\n<link rev=\"made\" 
href=\"mailto:support@f5.com\" />\n<style 
type=\"text/css\"><!--/*--><![CDATA[/*><!--*/ \n    
body { color: #000000; background-color: #FFFFFF; 
}\n    a:link { color: #0000CC; }\n    p, address 
{margin-left: 3em;}\n    span {font-size: 
smaller;}\n/*]]>*/--></style>\n<style 
type=\"text/css\"><!--/*--><![CDATA[/*><!--*/ \n* { 
width: 400px; font-size: 100%; font-style: normal; 
}\nhtml { text-align: center; }\nbody { background: 
#ffffff; text-align: left; font-family: sans-serif; font-
size: 70%; color: #333333; }\n\na,span { width: 
auto; } \nh1,h2,h3 { margin: 20px 0px 20px 0px; 
font-weight: bold; }\n\nh1 { padding: 5px; border: 
1px solid #999999; background: #eeeeee; color: 
#000000; font-size: 125%;  }\nhr { height: 1px; 
border: none; border-top: 1px solid #999999; 
}\nimg { border: 0px; }\np { width: 350px; margin: 
15px 25px 15px 25px; line-height: 135%; }\n/*]]>*/-
-></style>\n\n</head>\n\n<body>\n<h1>
Authentication required!</h1>\n<p>\n\n\n    This 
server could not verify that you are authorized to 
access\n    the URL \"/mgmt/shared/authn/login\".\n    
You either supplied the wrong credentials (e.g., bad
 password), or your\n    browser doesn't 
understand how to supply the credentials 
required.\n\n  </p>\n<p>\n\n\n    In case you are 
allowed to request the document, please\n    
check your user-id and password and try 
again.\n\n</p>\n\n<h2>Error 401</h2>\n<address>\n  <a 
href=\"/\">l20lbf02</a><br />\n  \n  <span>
Thu Oct  4 14:43:09 2018<br />\n  </span>\n</address>\n</body>\n</html>\n\n\"."

}
        to retry, use: --limit @/root/frm/ansible/4-vs-rd/test.retry
```

**Comment by caphrim007** [comment]
@fad3t i'm not experiencing the same error with a fresh install of ansible via pip. are you using the admin account? or are you using an account that is a remote-access-like account such as RADIUS/TACACS?

**Comment by fad3t** [comment]
@caphrim007 yes the admin account is the default admin, so it has the Administrator role. I tried uninstalling ansible and reinstalling it fresh using pip, but it didn't help.
Strange enough, the bigip_device_facts isn't giving this warning, but bigip_virtual_server or bigip_monitor_http do.

**Comment by caphrim007** [comment]
@fad3t does your password have special characters in it that might be causing it to fail? out of curiosity, can you change the admin password to something without special characters (just temporarily) to see if that is the issue? If it is, then its possible we have an encoding problem in our new code for connecting to the device

**Comment by fad3t** [comment]
@caphrim007 I changed the password to "test123" but result is the same.
I downgraded ansible to 2.6.5 and the playbook works again. Then upgraded to 2.7 and it fails.
Is the module using a different uri since 2.7? I find it strange the error message is saying uri: None.
Thanks.

**Comment by caphrim007** [comment]
@fad3t that "none" is irrelevant. The actual error is

"""
Authentication required!</h1>\n<p>\n\n\n    This 
server could not verify that you are authorized to 
access\n    the URL \"/mgmt/shared/authn/login\".\n    
You either supplied the wrong credentials (e.g., bad
 password), or your\n    browser doesn't 
understand how to supply the credentials 
required.\n\n  </p>\n<p>\n\n\n    In case you are 
allowed to request the document, please\n    
check your user-id and password and try 
again.\n\
"""

However, this error suggests that your credentials are wrong, you're running a version of bigip earlier than 12, or you have a network device between your Ansible controller and the bigip that is munging the connection so that the necessary payload is not being sent to the device.

**Comment by caphrim007** [comment]
What are the contents of your /root/frm/ansible/5-device-facts/ansible.cfg file? And u'/root/.ansible/plugins/modules directory?

**Comment by fad3t** [comment]
/root/frm/ansible/5-device-facts/ansible.cfg
```
[defaults]
inventory = hosts
transport = local
deprecation_warnings = False
```
/root/.ansible/plugins/modules doesn't exist.

**Comment by caphrim007** [comment]
@fad3t can we try to eliminate the provider as a problem? Instead of specifying provider, can you try specifying all of the connection parameters inline in the task?

**Comment by fad3t** [comment]
@caphrim007 result is the same. Here's what the task looks like now:
```
    - name: create virtual server
      bigip_virtual_server:
        name: "testVS"
        destination: "10.0.0.50%3"
        port: "443"
        description: "test VS"
        pool: "FE-POOL-1"
        server: "{{ inventory_hostname }}"
        server_port: "443"
        user: "test"
        password: "test123"
        validate_certs: "no"
      delegate_to: localhost
```

**Comment by caphrim007** [comment]
@fad3t can you run this curl command on the Ansible controller and report back what happens

```
curl -k -x POST https://l20lbf02/mgmt/shared/authn/login -d '{"username": "admin", "password": "secret", "loginProviderName": "tmos" }
```

BTW, what role does the "test" account you have above use? We suggest that the admin account be used in nearly all cases because there are known issues in some releases of bigip where a non admin account gets denied even if it has the administrator role

**Comment by fad3t** [comment]
@caphrim007 this one seems to give an issue as well. Why is the bigip_device_facts not giving the error? Is it using a different endpoint? The "test" account has administrator role -- same as admin.
```
# curl -k -X POST https://l20lbf02/mgmt/shared/authn/login -d '{"username": "test", "password": "test123", "loginProviderName": "tmos" }'
<?xml version="1.0" encoding="ISO-8859-1"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
  "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en">
<head>
<title>Authentication required!</title>
<link rev="made" href="mailto:support@f5.com" />
<style type="text/css"><!--/*--><![CDATA[/*><!--*/
    body { color: #000000; background-color: #FFFFFF; }
    a:link { color: #0000CC; }
    p, address {margin-left: 3em;}
    span {font-size: smaller;}
/*]]>*/--></style>
<style type="text/css"><!--/*--><![CDATA[/*><!--*/
* { width: 400px; font-size: 100%; font-style: normal; }
html { text-align: center; }
body { background: #ffffff; text-align: left; font-family: sans-serif; font-size: 70%; color: #333333; }

a,span { width: auto; }
h1,h2,h3 { margin: 20px 0px 20px 0px; font-weight: bold; }

h1 { padding: 5px; border: 1px solid #999999; background: #eeeeee; color: #000000; font-size: 125%;  }
hr { height: 1px; border: none; border-top: 1px solid #999999; }
img { border: 0px; }
p { width: 350px; margin: 15px 25px 15px 25px; line-height: 135%; }
/*]]>*/--></style>

</head>

<body>
<h1>Authentication required!</h1>
<p>


    This server could not verify that you are authorized to access
    the URL "/mgmt/shared/authn/login".
    You either supplied the wrong credentials (e.g., bad password), or your
    browser doesn't understand how to supply the credentials required.

  </p>
<p>


    In case you are allowed to request the document, please
    check your user-id and password and try again.

</p>

<h2>Error 401</h2>
<address>
  <a href="/">l20lbf02</a><br />

  <span>Fri Oct  5 20:08:00 2018<br />
  </span>
</address>
</body>
</html>
```
Thanks.

**Comment by caphrim007** [comment]
Can you provide the device_facts task that is not failing?

**Comment by fad3t** [comment]
For example, in the following playbook, the 1st task succeeds but the 2nd one fails.
```
#!/usr/local/bin/ansible-playbook
---
- name: show version
  gather_facts: false
  hosts: all
  environment:
    http_proxy: ""
    https_proxy: ""
  vars:
    credsProvider:
      server: '{{ inventory_hostname }}'
      server_port: '443'
      user: "test"
      password: "test123"
      validate_certs: 'no'
      transport: 'rest'
  tasks:
    - name: get facts
      bigip_device_facts:
        provider: '{{ credsProvider }}'
        gather_subset: "devices"
      register: facts
      delegate_to: localhost

    - name: set monitor
      bigip_monitor_http:
        provider: '{{ credsProvider }}'
        name: test
      delegate_to: localhost
```
