### ISSUE TITLE
bigip_remote_syslog task is non-idempotent

### ISSUE THREAD

**Issue by vchepkov** [F5Networks/f5-ansible#996]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
bigip_remote_syslog

##### ANSIBLE VERSION
```
ansible 2.6.4
  config file = /Users/vc7733/Sources/bna-ltm/ansible/ansible.cfg
  configured module search path = [u'/Users/vc7733/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python2.7/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 2.7.15 (default, Sep 16 2018, 21:01:16) [GCC 4.2.1 Compatible Apple LLVM 9.1.0 (clang-902.0.39.2)]
```

##### PYTHON VERSION
```
Python 2.7.15
```

##### BIGIP VERSION
```
Sys::Version
Main Package
  Product     BIG-IP
  Version     12.1.3.3
  Build       0.0.1
  Edition     Point Release 3
  Date        Fri Mar  9 14:11:15 PST 2018
```

##### LIBRARY VERSIONS
```
bigsuds==1.0.6
f5-sdk==3.0.20
```

##### CONFIGURATION
```
[defaults]
inventory = hosts
retry_files_enabled = False
host_key_checking = False
```
##### OS / ENVIRONMENT
N/A

##### SUMMARY
while running playbook configuring remote syslog with remote_port receive 'changed' status every run

##### STEPS TO REPRODUCE
```
---
- hosts: all
  gather_facts: no
  connection: local

  vars:
    provider:
      server: "{{ inventory_hostname }}"
      user: "{{ f5_username }}"
      password: "{{ f5_password }}"
      validate_certs: no
  
  tasks:

    - name: Set syslog
      bigip_remote_syslog:
        remote_host: syslog.example.com
        remote_port: 1516
        provider: "{{ provider }}"
```

##### EXPECTED RESULTS

Expect no change after initial run

##### ACTUAL RESULTS
```
TASK [Set syslog] ************************************************************************************************************************************************************************************************************************
changed: [bnsprdn-ltm102] => {"changed": true, "remote_port": 1516}
changed: [infprdn-gtm001] => {"changed": true, "remote_port": 1516}
changed: [infprdn-ltm011] => {"changed": true, "remote_port": 1516}
changed: [infprdn-ltm012] => {"changed": true, "remote_port": 1516}
changed: [bnsprdn-ltm202] => {"changed": true, "remote_port": 1516}
changed: [bnsprdn-ltm101] => {"changed": true, "remote_port": 1516}
changed: [bnsprdn-ltm201] => {"changed": true, "remote_port": 1516}
```

**Comment by wojtek0806** [comment]
as per slack I will have a look at it

**Comment by vchepkov** [comment]
I should note another related defect.

if syslog was already configured without parameter local_ip set,
module fails to change configuration, I receive the following error

```
fatal: [infdevn-ltm102]: FAILED! => {"changed": false, "msg": "400 Unexpected Error: Bad Request for uri: https://infdevn-ltm102:443/mgmt/tm/sys/syslog/\nText: u'{\"code\":400,\"message\":\"one or more properties must be specified\",\"errorStack\":[],\"apiError\":26214401}'"}
```

If I remove existing configuration, then it works

**Comment by wojtek0806** [comment]
In regards to the first issue you reported, I have tested this with the module not refactored yet and on our current devel and on 2.7.0 stable and it is not reproducible.

**My playbook**:
```
---
- name: Create syslog
  hosts: f5-test
  connection: local

  vars:
    provider:
      password: "admin"
      server: "{{ ansible_host }}"
      user: "admin"
      validate_certs: "no"
      server_port: "443"

  tasks:
    - name: Set syslog
      bigip_remote_syslog:
        remote_host: syslog.example.com
        remote_port: 1516
        provider: "{{ provider }}"
      delegate_to: localhost
      register: result

    - name: Assert Set syslog
      assert:
        that:
          - result is changed

    - name: Set syslog - Idempotent Check
      bigip_remote_syslog:
        remote_host: syslog.example.com
        remote_port: 1516
        provider: "{{ provider }}"
      delegate_to: localhost
      register: result

    - name: Assert Set syslog - Idempotent Check
      assert:
        that:
          - result is not changed

    - name: Cleanup
      bigip_remote_syslog:
        remote_host: syslog.example.com
        state: absent
        provider: "{{ provider }}"
      delegate_to: localhost
   ```` 
**Ansible Version**:
```
root@58ccf40bf9a8:/here# ansible --version
ansible 2.7.0
  config file = None
  configured module search path = ['/root/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.6/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 3.6.6 (default, Sep  5 2018, 03:40:52) [GCC 6.3.0 20170516]
```
**Playbook run**:
```
root@58ccf40bf9a8:/here# ansible-playbook -i /settings/inventory/hosts_docker /settings/repros/remote_syslog_broken.yaml 

PLAY [Create syslog] ******************************************************************************************************************************************************************************************************************************************************

TASK [Gathering Facts] ****************************************************************************************************************************************************************************************************************************************************
ok: [bigip_v12]

TASK [Set syslog] *********************************************************************************************************************************************************************************************************************************************************
changed: [bigip_v12 -> localhost]

TASK [Assert Set syslog] **************************************************************************************************************************************************************************************************************************************************
ok: [bigip_v12] => {
    "changed": false,
    "msg": "All assertions passed"
}

TASK [Set syslog - Indempotent Check] *************************************************************************************************************************************************************************************************************************************
ok: [bigip_v12 -> localhost]

TASK [Assert Set syslog - Indempotent Check] ******************************************************************************************************************************************************************************************************************************
ok: [bigip_v12] => {
    "changed": false,
    "msg": "All assertions passed"
}

TASK [Cleanup] ************************************************************************************************************************************************************************************************************************************************************
changed: [bigip_v12 -> localhost]

PLAY RECAP ****************************************************************************************************************************************************************************************************************************************************************
bigip_v12                  : ok=6    changed=2    unreachable=0    failed=0   
```

**Comment by wojtek0806** [comment]
Looking into the second issue you mentioned.

**Comment by vchepkov** [comment]
If I change ansible_host to inventory_hostname, then I can see reproduce my issue

syslog is configured with a different port

and I see message

changed: [infdevn-ltm201 -> localhost] => {"changed": true, "remote_port": 1516}

But I can see in GUI - nothing changed

Cleanup tasks also doesn't remove anything

```
$ ansible-playbook test.yaml

PLAY [Create syslog] ************************************************************************************************************************************************************

TASK [Gathering Facts] **********************************************************************************************************************************************************
ok: [infdevn-ltm201]

TASK [Set syslog] ***************************************************************************************************************************************************************
changed: [infdevn-ltm201 -> localhost]

TASK [Assert Set syslog] ********************************************************************************************************************************************************
ok: [infdevn-ltm201] => {
    "changed": false, 
    "msg": "All assertions passed"
}

TASK [Set syslog - Idempotent Check] ********************************************************************************************************************************************
ok: [infdevn-ltm201 -> localhost]

TASK [Assert Set syslog - Idempotent Check] *************************************************************************************************************************************
ok: [infdevn-ltm201] => {
    "changed": false, 
    "msg": "All assertions passed"
}

TASK [Cleanup] ******************************************************************************************************************************************************************
changed: [infdevn-ltm201 -> localhost]

PLAY RECAP **********************************************************************************************************************************************************************
infdevn-ltm201             : ok=6    changed=2    unreachable=0    failed=0   

```

**Comment by vchepkov** [comment]
Here is a reproducer
```
  tasks:
    - name: Set syslog
      bigip_remote_syslog:
        remote_host: syslog.example.com
        remote_port: 1516
        provider: "{{ provider }}"
      delegate_to: localhost
      register: result

    - name: Assert Set syslog
      assert:
        that:
          - result is changed

    - name: Set syslog
      bigip_remote_syslog:
        remote_host: syslog.example.com
        remote_port: 1517
        provider: "{{ provider }}"
      delegate_to: localhost
      register: result

    - name: Assert Set syslog
      assert:
        that:
          - result is changed

    - name: Set syslog - Idempotent Check
      bigip_remote_syslog:
        remote_host: syslog.example.com
        remote_port: 1517
        provider: "{{ provider }}"
      delegate_to: localhost
      register: result

    - name: Assert Set syslog - Idempotent Check
      assert:
        that:
          - result is not changed

    - name: Cleanup
      bigip_remote_syslog:
        remote_host: syslog.example.com
        state: absent
        provider: "{{ provider }}"
      delegate_to: localhost
```

```
$ ansible-playbook test.yaml

PLAY [Create syslog] ************************************************************************************************************************************************************

TASK [Gathering Facts] **********************************************************************************************************************************************************
ok: [infdevn-ltm201]

TASK [Set syslog] ***************************************************************************************************************************************************************
changed: [infdevn-ltm201 -> localhost]

TASK [Assert Set syslog] ********************************************************************************************************************************************************
ok: [infdevn-ltm201] => {
    "changed": false, 
    "msg": "All assertions passed"
}

TASK [Set syslog] ***************************************************************************************************************************************************************
fatal: [infdevn-ltm201 -> localhost]: FAILED! => {"changed": false, "msg": "400 Unexpected Error: Bad Request for uri: https://infdevn-ltm201:443/mgmt/tm/sys/syslog/\nText: u'{\"code\":400,\"message\":\"one or more properties must be specified\",\"errorStack\":[],\"apiError\":26214401}'"}

PLAY RECAP **********************************************************************************************************************************************************************
infdevn-ltm201             : ok=3    changed=1    unreachable=0    failed=1   

```
